const contentRegistry = new Map<string, string>([
  // ── DEVOPS ──
  ["devops/linux/overview","infrastructure/linux/overview"],
  ["devops/linux/fundamentals","infrastructure/linux/fundamentals"],
  ["devops/linux/intermediate","infrastructure/linux/intermediate"],
  ["devops/linux/advanced","infrastructure/linux/advanced"],
  ["devops/linux/cheatsheets","infrastructure/linux/cheatsheets"],
  ["devops/linux/interview","infrastructure/linux/interview"],
  ["devops/networking/overview","infrastructure/networking/overview"],
  ["devops/shell-scripting/overview","infrastructure/shell-scripting/overview"],
  ["devops/docker/overview","infrastructure/docker/overview"],
  ["devops/docker/fundamentals","infrastructure/docker/fundamentals"],
  ["devops/docker/cheatsheets","infrastructure/docker/cheatsheets"],
  ["devops/docker/interview","infrastructure/docker/interview"],
  ["devops/kubernetes/overview","infrastructure/kubernetes/overview"],
  ["devops/kubernetes/fundamentals","infrastructure/kubernetes/fundamentals"],
  ["devops/kubernetes/advanced","infrastructure/kubernetes/advanced"],
  ["devops/kubernetes/troubleshooting","infrastructure/kubernetes/troubleshooting"],
  ["devops/kubernetes/interview","infrastructure/kubernetes/interview"],
  ["devops/kubernetes/labs","infrastructure/kubernetes/labs"],
  ["devops/kubernetes/cheatsheets","infrastructure/kubernetes/cheatsheets"],
  ["devops/helm/overview","infrastructure/helm/overview"],
  ["devops/helm/fundamentals","infrastructure/helm/fundamentals"],
  ["devops/git/overview","infrastructure/git/overview"],
  ["devops/jenkins/overview","infrastructure/jenkins/overview"],
  ["devops/jenkins/advanced","infrastructure/jenkins/advanced"],
  ["devops/argocd/overview","infrastructure/argocd/overview"],
  ["devops/terraform/overview","infrastructure/terraform/overview"],
  ["devops/terraform/fundamentals","infrastructure/terraform/fundamentals"],
  ["devops/terraform/advanced","infrastructure/terraform/advanced"],
  ["devops/terraform/interview","infrastructure/terraform/interview"],
  ["devops/terraform/cheatsheets","infrastructure/terraform/cheatsheets"],
  ["devops/ansible/overview","infrastructure/ansible/overview"],
  ["devops/ansible/fundamentals","infrastructure/ansible/fundamentals"],
  ["devops/ansible/interview","infrastructure/ansible/interview"],
  ["devops/prometheus/overview","infrastructure/prometheus/overview"],
  ["devops/grafana/overview","infrastructure/grafana/overview"],
  ["devops/elk-stack/overview","infrastructure/elk-stack/overview"],
  ["devops/python/overview","infrastructure/python/overview"],
  ["devops/python/fundamentals","infrastructure/python/fundamentals"],
  ["devops/python/cheatsheets","infrastructure/python/cheatsheets"],
  ["devops/python/interview","infrastructure/python/interview"],
  ["devops/nginx/overview","infrastructure/nginx/overview"],
  // ── CLOUD ──
  ["cloud/aws-iam/overview","cloud/aws-iam/overview"],
  ["cloud/aws-iam/fundamentals","cloud/aws-iam/fundamentals"],
  ["cloud/aws-ec2/overview","cloud/aws-ec2/overview"],
  ["cloud/aws-ec2/fundamentals","cloud/aws-ec2/fundamentals"],
  ["cloud/aws-vpc/overview","cloud/aws-vpc/overview"],
  ["cloud/aws-s3/overview","cloud/aws-s3/overview"],
  ["cloud/aws-rds/overview","cloud/aws-rds/overview"],
  ["cloud/aws-lambda/overview","cloud/aws-lambda/overview"],
  ["cloud/aws-eks/overview","cloud/aws-eks/overview"],
  ["cloud/cloudformation/overview","cloud/cloudformation/overview"],
  ["cloud/route53/overview","cloud/route53/overview"],
  ["cloud/azure-entra/overview","cloud/azure-entra/overview"],
  ["cloud/azure-vms/overview","cloud/azure-vms/overview"],
  ["cloud/azure-vnets/overview","cloud/aws-vpc/overview"],
  ["cloud/azure-aks/overview","cloud/azure-aks/overview"],
  ["cloud/azure-devops/overview","cloud/azure-devops/overview"],
  ["cloud/gke/overview","cloud/gke/overview"],
  ["cloud/bigquery/overview","cloud/bigquery/overview"],
  ["cloud/cloud-run/overview","cloud/aws-lambda/overview"],
  ["cloud/cloud-security/overview","security/security-fundamentals/overview"],
  ["cloud/cost-optimization/overview","cloud/cost-optimization/overview"],
  ["cloud/landing-zones/overview","cloud/aws-vpc/overview"],
  // ── DATABASES ──
  ["databases/postgresql/overview","infrastructure/postgresql/overview"],
  ["databases/mysql/overview","infrastructure/mysql/overview"],
  ["databases/sql/overview","data/sql/overview"],
  ["databases/sql/fundamentals","data/sql/fundamentals"],
  ["databases/mongodb/overview","infrastructure/mongodb/overview"],
  ["databases/cassandra/overview","infrastructure/cassandra/overview"],
  ["databases/dynamodb/overview","infrastructure/redis/overview"],
  ["databases/redis/overview","infrastructure/redis/overview"],
  ["databases/elasticsearch/overview","infrastructure/elk-stack/overview"],
  // ── AI ──
  ["ai/ai-fundamentals/overview","ai/ai-fundamentals/overview"],
  ["ai/prompt-engineering/overview","ai/prompt-engineering/overview"],
  ["ai/langchain/overview","ai/langchain/overview"],
  ["ai/langchain/fundamentals","ai/langchain/fundamentals"],
  ["ai/rag/overview","ai/rag/overview"],
  ["ai/ai-agents/overview","ai/ai-agents/overview"],
  ["ai/llmops/overview","ai/llmops/overview"],
  ["ai/openai/overview","ai/ai-fundamentals/overview"],
  // ── DATA ──
  ["data/excel/overview","data/excel/overview"],
  ["data/pandas/overview","data/pandas/overview"],
  ["data/power-bi/overview","data/power-bi/overview"],
  ["data/tableau/overview","data/tableau/overview"],
  ["data/sql/overview","data/sql/overview"],
  ["data/sql/fundamentals","data/sql/fundamentals"],
  // ── SECURITY ──
  ["security/security-fundamentals/overview","security/security-fundamentals/overview"],
  ["security/network-security/overview","security/network-security/overview"],
  ["security/ethical-hacking/overview","security/ethical-hacking/overview"],
  ["security/soc/overview","security/soc/overview"],
  ["security/siem/overview","security/siem/overview"],
  ["security/pen-testing/overview","security/ethical-hacking/overview"],
  // ── HEALTHCARE ──
  ["healthcare/icd-10-cm/overview","healthcare/icd-10-cm/overview"],
  ["healthcare/icd-10-cm/fundamentals","healthcare/icd-10-cm/fundamentals"],
  ["healthcare/icd-10-cm/interview","healthcare/icd-10-cm/interview"],
  ["healthcare/cpt/overview","healthcare/cpt/overview"],
  ["healthcare/hcpcs/overview","healthcare/hcpcs/overview"],
  ["healthcare/coding-guidelines/overview","healthcare/coding-guidelines/overview"],
  ["healthcare/home-health-coding/overview","healthcare/home-health-coding/overview"],
  ["healthcare/patient-documentation/overview","healthcare/coding-guidelines/overview"],
  ["healthcare/healthcare-admin/overview","healthcare/coding-guidelines/overview"],
  ["healthcare/mock-exams/overview","healthcare/icd-10-cm/interview"],
  // ── ESSENTIALS ──
  ["essentials/gut-health/overview","essentials/gut-health/overview"],
  ["essentials/hygiene/overview","essentials/hygiene/overview"],
  ["essentials/nutrition/overview","essentials/nutrition/overview"],
  ["essentials/mental-health/overview","essentials/mental-health/overview"],
  ["essentials/personal-finance/overview","essentials/personal-finance/overview"],
  ["essentials/first-aid/overview","essentials/first-aid/overview"],
  // ── EDUCATION ──
  ["education/dsa/overview","education/dsa/overview"],
  ["education/os/overview","education/os/overview"],
  ["education/dbms/overview","education/dbms/overview"],
  ["education/cn/overview","education/cn/overview"],
  ["education/system-design/overview","education/system-design/overview"],
  ["education/placement-prep/overview","education/placement-prep/overview"],
  ["education/maths/overview","exams/gate-cse/overview"],
  ["education/science/overview","exams/gate-cse/overview"],
  ["education/cs-school/overview","education/cs-school/overview"],
  // ── EXAMS ──
  ["exams/gate-cse/overview","exams/gate-cse/overview"],
  ["exams/gate-ece/overview","exams/gate-cse/overview"],
  ["exams/jee-maths/overview","exams/jee-maths/overview"],
  ["exams/jee-physics/overview","exams/jee-physics/overview"],
  ["exams/jee-chemistry/overview","exams/jee-chemistry/overview"],
  ["exams/banking-exams/overview","exams/banking-exams/overview"],
  ["exams/ssc-cgl/overview","exams/ssc-cgl/overview"],
  ["exams/rrb-ntpc/overview","exams/banking-exams/overview"],
  ["exams/upsc-prelims/overview","exams/upsc-prelims/overview"],
  ["exams/upsc-mains/overview","exams/upsc-prelims/overview"],
]);

export function hasContent(a: string, t: string, s: string): boolean {
  return contentRegistry.has(`${a}/${t}/${s}`);
}
export async function fetchContent(a: string, t: string, s: string): Promise<string | null> {
  const filePath = contentRegistry.get(`${a}/${t}/${s}`);
  if (!filePath) return null;
  try {
    const res = await fetch(`/content/${filePath}.md`);
    if (!res.ok) return null;
    return await res.text();
  } catch { return null; }
}
export function getContent(_a: string, _t: string, _s: string): string | null { return null; }
