name = "synfracore"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "BLOG_KV"
id = "57d60b769fbe4ae6be430d9dc4975f00"