-- ============================================================
-- AWS Certified Solutions Architect - Associate (SAA-C03) — Seed Data: Paper 9
-- New content, distinct topics from Papers 1-8 — no repeated scenarios.
-- Topic list checked directly against the actual question text of Papers
-- 1-8 (grepped from the files) before writing.
--
-- Domain-question-count breakdown, confirmed BEFORE writing any questions
-- (per standing process, adopted after 3 consecutive papers undercounted
-- a domain at the topic-list-finalization stage): Secure 6 + Resilient 5 +
-- High-Performing 5 + Cost-Optimized 4 = 20, confirmed.
--   Secure (6): Config conformance packs/auto-remediation, S3 Object
--     Ownership (Bucket owner enforced), VPC Traffic Mirroring, IAM Roles
--     Anywhere, AWS Directory Service (Managed Microsoft AD), VPC
--     Reachability Analyzer.
--   Resilient (5): S3 CRR with Replication Time Control, Route 53
--     Application Recovery Controller, EC2 Spread Placement Groups,
--     Cross-Region AMI Copy, S3 One Zone-IA resilience trade-off.
--   High-Performing (5): CloudFront automatic compression, EC2 Instance
--     Store, Aurora Auto Scaling (read replica count), S3 Event
--     Notifications, ElastiCache Redis Cluster Mode.
--   Cost-Optimized (4): S3 Batch Operations, EC2 instance generation
--     upgrade, CloudFront price classes, Cost Allocation Tags.
--
-- IDs were generated via scripts/fill-seed-uuids.mjs, which replaces every
-- distinct placeholder token with a fresh, real UUID (consistently across
-- every occurrence) — this file has already had that script run against
-- it; the UUIDs below are real. Cross-checked against every other seed
-- file in the repo for zero collisions before finalizing, plus the
-- distractor-language sanity scan and a manual re-read of every answer key
-- against its option text. The question_papers ARRAY[...]::TEXT[] literal
-- and every option token were manually re-read once before running the
-- fill script.
-- Run this AFTER docs/question-bank-schema.sql.
-- ============================================================

INSERT INTO question_papers (id, slug, title, exam_type, focus_tags, question_count, difficulty, is_premium, sort_order, time_limit_minutes)
VALUES ('030b206e-c700-49db-9905-3ac82057637b', 'aws-saa-practice-9', 'AWS Certified Solutions Architect - Associate Practice Paper 9', 'aws-saa', ARRAY['Config Remediation', 'S3 Object Ownership', 'Traffic Mirroring', 'IAM Roles Anywhere', 'Route 53 ARC', 'Spread Placement Groups', 'Instance Store', 'S3 Batch Operations']::TEXT[], 20, 'standard', true, 9, 30);

-- ── Domain: Secure Architectures (30% — 6 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('22749421-3032-496f-b44a-c2884e3a12f1', '030b206e-c700-49db-9905-3ac82057637b', 1, 'A company uses AWS Config to detect when an S3 bucket''s public-access settings drift out of compliance with company policy, but currently a human still has to manually notice the finding and manually fix the misconfigured bucket every time — creating a real delay between detection and actual remediation. What AWS Config feature can automatically FIX a non-compliant resource the moment a violation is detected, without waiting for a human to act?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3d9b5676-ba74-4b86-9559-5de3ce5ef276', '22749421-3032-496f-b44a-c2884e3a12f1', 0, 'AWS Config remediation actions (using Config Rules paired with an SSM Automation document) — automatically triggers a predefined remediation action the moment a Config Rule detects a resource as non-compliant, closing the gap between detection and actual fix without requiring a human to notice and manually intervene each time; this can be configured to run automatically, or to require manual approval as an intermediate safety step, depending on how much confidence the organization has in the automated fix for a given rule.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('68759687-c358-4f3d-9669-c9bfbd140e5c', '22749421-3032-496f-b44a-c2884e3a12f1', 1, 'AWS CloudTrail, since CloudTrail is specifically defined as automatically remediating a non-compliant resource the moment a Config Rule violation is detected.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3a6be63c-e29a-4520-8e5f-b57fb9f97993', '22749421-3032-496f-b44a-c2884e3a12f1', 2, 'IAM Access Analyzer, since Access Analyzer''s core function is automatically fixing a non-compliant S3 bucket the moment AWS Config detects a policy drift violation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7206694c-ac58-4750-ae84-cdb53fb4d409', '22749421-3032-496f-b44a-c2884e3a12f1', 3, 'AWS Config can only ever detect configuration drift; no mechanism exists to automatically remediate a non-compliant resource without manual, human intervention every time.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('22749421-3032-496f-b44a-c2884e3a12f1', '3d9b5676-ba74-4b86-9559-5de3ce5ef276', 'Config remediation actions directly extend the AWS Config drift-detection concept (covered generally in a prior paper) with an automated response layer — rather than a Config Rule simply flagging a resource as NON_COMPLIANT and waiting for a human to notice and manually fix it, a remediation action (built on an SSM Automation document, connecting to Systems Manager concepts covered generally elsewhere) can be attached to that rule so the fix executes automatically the instant the violation is detected, meaningfully shrinking the real-world window during which a resource sits misconfigured and exposed. This can be configured for fully automatic execution for well-understood, low-risk fixes, or set to require a manual approval step first for changes an organization wants a human to explicitly confirm before it happens — a genuinely flexible, real capability, not an all-or-nothing automation. CloudTrail (covered in a prior paper) is an API-activity audit log with no remediation capability of its own, and IAM Access Analyzer (covered in a prior paper) detects unintended EXTERNAL access via policy analysis, a different function from fixing a Config-detected compliance violation — AWS Config genuinely does support this automated remediation capability, not detection alone.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('bb0bb979-8f32-40d7-ac5d-58b8ce1d956e', '030b206e-c700-49db-9905-3ac82057637b', 2, 'A company wants to permanently eliminate the risk of an S3 bucket ACL (Access Control List) accidentally granting unintended public or cross-account access — a legacy access-control mechanism that predates and operates independently of bucket policies — by ensuring every object in the bucket is owned by the bucket owner and that ACLs are disabled entirely, simplifying access control down to bucket policies and IAM alone. What S3 setting achieves this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('02104697-8707-4174-a9c8-e905c887b07d', 'bb0bb979-8f32-40d7-ac5d-58b8ce1d956e', 0, 'S3 Object Ownership set to "Bucket owner enforced" — disables ACLs entirely for the bucket, meaning every object is always owned by the bucket owner (regardless of which account originally uploaded it) and access is controlled purely through bucket policies and IAM policies, eliminating the legacy ACL mechanism as a possible source of accidental, hard-to-audit unintended access, and simplifying access control down to a single, more consistently auditable policy-based model.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a78fad17-558b-4b49-8f02-f973ba3bb75a', 'bb0bb979-8f32-40d7-ac5d-58b8ce1d956e', 1, 'S3 Block Public Access, since Block Public Access is specifically defined as disabling ACLs entirely and making every object always owned by the bucket owner regardless of who uploaded it.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7e4d8bce-e484-4d5e-82ce-dc2cb73d4d2b', 'bb0bb979-8f32-40d7-ac5d-58b8ce1d956e', 2, 'S3 Object Lock, since Object Lock''s core function is disabling ACLs and enforcing bucket-owner object ownership.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f2a88d76-611e-4a7a-9d5e-4fe191443964', 'bb0bb979-8f32-40d7-ac5d-58b8ce1d956e', 3, 'S3 provides no mechanism to disable ACLs or standardize object ownership; ACL-based access control can never be turned off for a bucket.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('bb0bb979-8f32-40d7-ac5d-58b8ce1d956e', '02104697-8707-4174-a9c8-e905c887b07d', '"Bucket owner enforced" is the specific S3 Object Ownership setting that fully disables ACLs for a bucket — a genuinely distinct, complementary control from S3 Block Public Access (covered in a prior paper, which specifically prevents PUBLIC access regardless of how it''s granted, whether via ACL or bucket policy) — Object Ownership instead addresses a different, narrower problem: ACLs are a legacy, PER-OBJECT access mechanism that predates bucket policies, can be set individually on each object (sometimes inconsistently across a bucket with many contributors), and can in principle grant access to OTHER AWS accounts or make an object owned by a different account than the bucket owner — creating a genuinely harder-to-audit, inconsistent access surface compared to a single, bucket-wide policy. Setting Object Ownership to "Bucket owner enforced" eliminates this specific risk entirely by disabling ACLs outright and guaranteeing every object is owned by the bucket owner regardless of who originally uploaded it, consolidating access control down to just bucket policies and IAM — a real, standard, and increasingly recommended S3 security baseline setting (and, notably, the DEFAULT for new buckets in recent years), not a non-existent capability.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('69b7084a-f52c-476b-a273-d7860df3ef59', '030b206e-c700-49db-9905-3ac82057637b', 3, 'A security team investigating suspected malicious activity on a specific EC2 instance wants to capture and inspect a COPY of the raw network traffic actually flowing to and from that instance''s network interface — for deep packet analysis with a specialized security tool — without disrupting the instance''s normal operation or needing to install anything directly on the instance itself. What AWS feature supports capturing this kind of full traffic copy at the network level?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f0eec9fb-d2f0-4688-a8de-9954d9d5b4dd', '69b7084a-f52c-476b-a273-d7860df3ef59', 0, 'VPC Traffic Mirroring — copies network traffic from a specified ENI (Elastic Network Interface) and sends that copy to a chosen target (another EC2 instance running a security/monitoring tool, or a Network Load Balancer fronting a fleet of such tools) for deep inspection, entirely OUT-OF-BAND from the original traffic''s normal delivery path, so the source instance''s actual operation and performance are not disrupted, and with no agent needing to be installed on the source instance itself — genuinely distinct from VPC Flow Logs (covered in a prior paper, which records traffic METADATA — source/destination, port, accept/reject — not the actual raw packet contents Traffic Mirroring provides).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('964cc339-c4c3-4d1a-9d26-ffab19b80cf8', '69b7084a-f52c-476b-a273-d7860df3ef59', 1, 'VPC Flow Logs, since Flow Logs are specifically defined as capturing a full raw copy of network packet contents for deep inspection by a security tool.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('834f0e08-de39-4c65-9587-9096e1d75eb4', '69b7084a-f52c-476b-a273-d7860df3ef59', 2, 'AWS Network Firewall, since Network Firewall''s core function is capturing and forwarding a raw copy of an instance''s network traffic to a separate security tool for inspection.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c3f90edf-6607-4163-9540-b3835f7afe25', '69b7084a-f52c-476b-a273-d7860df3ef59', 3, 'No AWS mechanism exists to capture a copy of an EC2 instance''s actual network traffic for external inspection without installing monitoring software directly on the instance.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('69b7084a-f52c-476b-a273-d7860df3ef59', 'f0eec9fb-d2f0-4688-a8de-9954d9d5b4dd', 'VPC Traffic Mirroring fills a genuinely distinct visibility gap from VPC Flow Logs (covered in a prior paper) — Flow Logs capture only traffic METADATA (who talked to whom, on what port, and whether the traffic was accepted or rejected) useful for auditing and high-level analysis, but they do NOT include the actual packet CONTENTS, meaning a security tool doing deep packet inspection, protocol analysis, or forensic investigation of what data was actually being sent has nothing to work with from Flow Logs alone. Traffic Mirroring instead duplicates the ACTUAL raw traffic from a specified network interface and delivers that full copy to a chosen inspection target, entirely out-of-band so the original traffic keeps flowing normally and the source instance''s performance is unaffected, with no agent installation needed directly on the monitored instance since the mirroring happens at the network layer itself. This is a real, standard, purpose-built capability specifically for exactly this kind of deep security investigation and monitoring need — AWS Network Firewall (covered in a prior paper) inspects and filters traffic AT THE VPC level as an active control, a different function from passively mirroring a copy for a separate tool''s analysis.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('4142ac58-5906-4329-8816-92cd2b0c655f', '030b206e-c700-49db-9905-3ac82057637b', 4, 'A company runs workloads on-premises and in a non-AWS data center, and wants those non-AWS workloads to be able to assume an IAM role and obtain temporary AWS credentials — the same way an EC2 instance role works, covered generally in a prior paper — but WITHOUT storing any long-lived AWS access keys on those non-AWS servers, instead authenticating using an existing X.509 certificate from their own private certificate authority. What AWS feature supports this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('60294b69-e801-4571-bc40-8ab04e0fd082', '4142ac58-5906-4329-8816-92cd2b0c655f', 0, 'IAM Roles Anywhere — extends the temporary-credential, no-long-lived-key IAM role pattern (normally available to AWS resources like EC2 instances via an instance role) to workloads running OUTSIDE AWS entirely — on-premises servers or another cloud provider — by letting them authenticate using an X.509 certificate issued by their own trusted certificate authority, then exchanging that certificate for temporary AWS credentials scoped to an assumed IAM role, avoiding the need to ever store static, long-lived AWS access keys on non-AWS infrastructure.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3c405208-cad8-4846-bed6-37ff3228f58e', '4142ac58-5906-4329-8816-92cd2b0c655f', 1, 'AWS IAM Identity Center, since IAM Identity Center is specifically defined as letting non-AWS, on-premises workloads assume an IAM role using an X.509 certificate instead of human SSO login.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('263f2dc3-21e4-4ba9-825c-7f60bb26dc8d', '4142ac58-5906-4329-8816-92cd2b0c655f', 2, 'AWS Directory Service, since Directory Service''s core function is issuing temporary AWS credentials to non-AWS servers based on X.509 certificate authentication.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3ceeeec2-c619-4157-97b1-1a6d382bb0f3', '4142ac58-5906-4329-8816-92cd2b0c655f', 3, 'Only AWS-native resources like EC2 instances can ever assume an IAM role and obtain temporary credentials; non-AWS, on-premises workloads have no equivalent mechanism and must always use long-lived access keys.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('4142ac58-5906-4329-8816-92cd2b0c655f', '60294b69-e801-4571-bc40-8ab04e0fd082', 'IAM Roles Anywhere specifically closes the gap between AWS-native workloads (which get the well-established EC2 instance role pattern — temporary, auto-rotated credentials with no hardcoded keys, covered generally in a prior paper) and NON-AWS workloads, which historically had no equivalent and often ended up relying on long-lived, manually-managed AWS access keys stored directly on the server — a genuinely real security risk, since a long-lived key that leaks (via a misconfigured server, a compromised credential store, or accidental exposure) remains valid and usable until someone notices and manually revokes it. Roles Anywhere instead lets a non-AWS workload present an X.509 certificate (issued by the organization''s own trusted private CA) to prove its identity, in exchange for genuinely short-lived, temporary AWS credentials scoped to an assumed IAM role — directly extending the same "no long-lived credentials sitting on a server" security principle to infrastructure outside AWS entirely. This is meaningfully different from IAM Identity Center (covered in a prior paper, which specifically handles HUMAN SSO login to AWS accounts/applications, not machine-to-machine non-AWS-workload authentication) and from AWS Directory Service (a Windows Active Directory-compatible managed directory service, covered later this paper, unrelated to certificate-based credential exchange) — this is a real, purpose-built AWS feature, not a capability limited exclusively to AWS-native resources.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('0905b6b1-4d06-4bf5-b2a1-1f9c94fb1afd', '030b206e-c700-49db-9905-3ac82057637b', 5, 'A company migrating Windows-based applications to AWS needs a genuinely Microsoft Active Directory-compatible directory service — supporting group policy, domain trust relationships, and the ability for existing on-premises AD-joined Windows servers and applications to authenticate against it directly — rather than a directory service tailored primarily to human sign-in for AWS console/application access. What AWS service provides a fully managed, genuinely AD-compatible directory for this need?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('94b624c8-6a9f-40f7-8ed3-efab30fba968', '0905b6b1-4d06-4bf5-b2a1-1f9c94fb1afd', 0, 'AWS Directory Service (specifically AWS Managed Microsoft AD) — a fully managed, genuinely Microsoft Active Directory-compatible directory running actual Windows Server infrastructure behind the scenes, supporting group policy, domain trust relationships with an existing on-premises AD forest, and direct authentication from AD-joined Windows servers and applications — a fundamentally different tool from IAM Identity Center (covered in a prior paper, which specifically provides SSO login for humans into the AWS Management Console and AWS-integrated applications, not general-purpose AD-compatible directory services for domain-joined infrastructure).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ca1b7003-592a-4e64-9d63-5bf8ec8d48d9', '0905b6b1-4d06-4bf5-b2a1-1f9c94fb1afd', 1, 'IAM Identity Center, since IAM Identity Center is specifically defined as a fully managed, Active Directory-compatible directory supporting group policy and domain trust relationships for Windows workloads.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f7ea633f-738c-4dff-9937-cf11394c5572', '0905b6b1-4d06-4bf5-b2a1-1f9c94fb1afd', 2, 'IAM Roles Anywhere, since IAM Roles Anywhere provides group policy and domain trust support for AD-joined Windows servers and applications.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ccb83f91-5f80-49a3-a0d9-69a1e6aeba94', '0905b6b1-4d06-4bf5-b2a1-1f9c94fb1afd', 3, 'AWS provides no managed service compatible with Microsoft Active Directory; genuinely AD-compatible directory services must always be self-hosted entirely on EC2.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('0905b6b1-4d06-4bf5-b2a1-1f9c94fb1afd', '94b624c8-6a9f-40f7-8ed3-efab30fba968', 'AWS Managed Microsoft AD (under the AWS Directory Service umbrella) is specifically built to be a genuinely compatible Active Directory implementation — actually running real Windows Server/AD Domain Services infrastructure, managed by AWS — meaning it supports the actual AD-specific features Windows-centric enterprise workloads depend on: group policy objects, trust relationships with an existing on-premises AD forest (enabling a genuinely hybrid identity setup), and direct authentication from AD-joined servers and applications exactly the way they would authenticate against an on-premises domain controller. This is a fundamentally different tool from IAM Identity Center (covered in a prior paper), which is specifically focused on HUMAN sign-in to AWS itself (the Management Console, AWS-integrated business applications) via SSO — genuinely useful for that specific purpose, but not a substitute for actual AD-protocol compatibility that domain-joined Windows infrastructure requires. This is a real, standard, and directly relevant AWS service for exactly the Windows-migration and hybrid-AD scenario described, not a gap requiring a fully self-managed EC2-hosted directory as the only option.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('645def3c-2585-49e2-83f0-74bae8ab9d10', '030b206e-c700-49db-9905-3ac82057637b', 6, 'A solutions architect troubleshooting a connectivity issue wants to verify WHETHER a specific EC2 instance in a private subnet can actually reach a specific RDS database in a different subnet — checking route tables, security groups, and NACLs along the entire path — without manually tracing through every individual configuration by hand across potentially many hops. What AWS diagnostic tool automates this kind of network path reachability analysis?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('758ad901-9586-4d1e-9e54-d1e2f2d1e44d', '645def3c-2585-49e2-83f0-74bae8ab9d10', 0, 'VPC Reachability Analyzer — a configuration-analysis diagnostic tool that traces the theoretical network path between two specified resources (like an EC2 instance and an RDS database), automatically evaluating every relevant route table, security group rule, and NACL rule along that path, and reports whether the path is genuinely reachable or specifically identifies which exact configuration element is blocking it — all WITHOUT sending any actual live network traffic, since it analyzes the CONFIGURATION itself rather than testing with real packets.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('857e1498-cee1-4ed4-bc33-e5ec32afa4a5', '645def3c-2585-49e2-83f0-74bae8ab9d10', 1, 'AWS Config, since Config''s core function is automatically tracing network reachability between two specific resources across route tables, security groups, and NACLs.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b222f522-483a-41d0-b754-a6a54ac05c1f', '645def3c-2585-49e2-83f0-74bae8ab9d10', 2, 'VPC Traffic Mirroring, since Traffic Mirroring automatically traces and reports on theoretical network path reachability between two specified resources.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a0e49cb2-7abf-48e4-a280-07e571c98f7f', '645def3c-2585-49e2-83f0-74bae8ab9d10', 3, 'No AWS tool exists to automate network path reachability analysis; verifying connectivity between two resources always requires manually tracing every route table, security group, and NACL by hand.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('645def3c-2585-49e2-83f0-74bae8ab9d10', '758ad901-9586-4d1e-9e54-d1e2f2d1e44d', 'VPC Reachability Analyzer is specifically purpose-built for exactly this "will these two resources actually be able to reach each other, and if not, why" diagnostic need — rather than a human manually cross-referencing route tables, security group rules (both instance-level allow rules), and NACL rules (subnet-level, evaluated in numbered order, both concepts covered generally in prior papers) across potentially many hops by hand, Reachability Analyzer performs that full configuration analysis automatically and reports a clear reachable/not-reachable verdict, and critically, when the path ISN''T reachable, it identifies the SPECIFIC blocking element (a missing security group rule, an incorrect route, a NACL deny) rather than leaving the architect to keep guessing. Genuinely important: this is a pure CONFIGURATION analysis tool — it doesn''t send actual live network packets to test connectivity, meaning it can find a THEORETICAL blocking misconfiguration even for resources that aren''t currently running, or diagnose a path issue without risk of side effects from real traffic. AWS Config (covered in a prior paper) tracks resource CONFIGURATION STATE and compliance drift generally, not path-specific reachability analysis, and Traffic Mirroring (covered earlier this paper) captures actual traffic copies for inspection, an entirely different function — this is a real, standard, and genuinely useful diagnostic tool, not a manual-only troubleshooting requirement.');

-- ── Domain: Resilient Architectures (26% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('a82eb97e-996e-4acd-b8cc-c2fa8965968b', '030b206e-c700-49db-9905-3ac82057637b', 7, 'A company using S3 Cross-Region Replication has a strict regulatory requirement that replicated copies of specific compliance data must be available in the destination Region within a GUARANTEED, contractually-backed time window — not simply "eventually" or "typically fast," but with an actual SLA the company can rely on and be compensated against if AWS fails to meet it. What S3 CRR feature provides this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2ed6484d-22bf-4f67-8a80-7eb6d9fedd96', 'a82eb97e-996e-4acd-b8cc-c2fa8965968b', 0, 'S3 Replication Time Control (S3 RTC) — an optional feature added on top of standard Cross-Region Replication (covered generally in prior papers) that provides a genuine, contractually-backed SLA guaranteeing that 99.99% of new objects will be replicated to the destination Region within 15 minutes, along with visibility metrics tracking actual replication performance against that commitment — meaningfully different from standard CRR''s replication, which happens automatically and generally quickly but carries no formal, contractual time guarantee or SLA-backed commitment on its own.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bbc3bf22-71ac-4d28-8a46-46a87b0ec33e', 'a82eb97e-996e-4acd-b8cc-c2fa8965968b', 1, 'S3 Same-Region Replication, since SRR is specifically defined as the feature adding a contractually-backed 15-minute replication SLA to standard Cross-Region Replication.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('338f99d6-7c80-4f54-9aae-fdad6ca90346', 'a82eb97e-996e-4acd-b8cc-c2fa8965968b', 2, 'S3 Transfer Acceleration, since Transfer Acceleration''s core function is providing a contractually-backed SLA guaranteeing replication completion within a specific time window.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ab438c1a-77db-42ac-9ce5-a86c69c38da0', 'a82eb97e-996e-4acd-b8cc-c2fa8965968b', 3, 'S3 replication provides no mechanism for a contractually-backed replication time guarantee; replication timing can never be measured or committed to under any circumstance.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('a82eb97e-996e-4acd-b8cc-c2fa8965968b', '2ed6484d-22bf-4f67-8a80-7eb6d9fedd96', 'S3 RTC specifically adds a formal, measurable, SLA-backed guarantee on top of the general Cross-Region Replication mechanism (covered generally in prior papers, including its use for RPO-focused disaster recovery) — standard CRR replicates objects automatically and, in ordinary operation, generally quite quickly, but provides no formal, contractually-committed time bound a company could point to for a genuinely strict regulatory or compliance requirement; RTC specifically closes that gap with an actual 99.99%-within-15-minutes commitment, backed by real visibility metrics tracking whether that commitment is actually being met in practice, giving a company genuine grounds for recourse if AWS fails to meet the stated SLA. This is a meaningfully different, additive feature from Same-Region Replication (covered in a prior paper, which changes the DESTINATION scope — same region vs. different region — not the TIMING guarantee) and Transfer Acceleration (covered in a prior paper, which speeds up UPLOAD/download paths via CloudFront edge locations, an entirely different mechanism from replication SLA commitments) — RTC is a real, standard, purpose-built feature specifically for organizations with genuine, contractually-enforceable replication-timing requirements.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('345c6966-2883-4469-a330-41372b1fab37', '030b206e-c700-49db-9905-3ac82057637b', 8, 'A company running a multi-region disaster recovery architecture wants a centralized way to continuously verify that its DR infrastructure is genuinely READY to take over (checking things like whether resources exist in sufficient capacity in the standby Region, whether required configurations match between primary and standby), and a controlled mechanism to actually SHIFT traffic during a real failover event — rather than manually and separately checking readiness and executing DNS changes during an actual, high-pressure disaster. What AWS service is purpose-built for this kind of DR readiness verification and controlled failover orchestration?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('eda69511-e276-4c41-aba4-a6997b4a2149', '345c6966-2883-4469-a330-41372b1fab37', 0, 'Route 53 Application Recovery Controller (Route 53 ARC) — provides ongoing READINESS CHECKS that continuously verify a standby Region''s DR infrastructure is genuinely prepared to take over (sufficient capacity, matching configuration), plus ROUTING CONTROLS that let an operator (or an automated process) actually and safely shift traffic during a real failover event, giving a centralized, purpose-built mechanism for both the ongoing verification AND the controlled execution of a DR failover, rather than manually checking readiness and separately executing DNS changes under the pressure of an actual live incident.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5da52abb-5280-481f-9200-6b496ed6805c', '345c6966-2883-4469-a330-41372b1fab37', 1, 'Route 53 calculated health checks, since calculated health checks are specifically defined as providing ongoing DR readiness verification and controlled traffic-shifting routing controls.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('56e0c1a5-167e-4894-8788-eec0bedf4606', '345c6966-2883-4469-a330-41372b1fab37', 2, 'AWS Elastic Disaster Recovery, since AWS DRS is specifically defined as continuously verifying standby-Region readiness and providing routing controls for controlled traffic failover.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5477f021-3c69-476f-9581-fac792436d79', '345c6966-2883-4469-a330-41372b1fab37', 3, 'No AWS service exists for centrally verifying multi-region DR readiness or orchestrating a controlled failover; every failover step must always be performed entirely manually with no automated readiness checking available.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('345c6966-2883-4469-a330-41372b1fab37', 'eda69511-e276-4c41-aba4-a6997b4a2149', 'Route 53 ARC is specifically purpose-built to close the gap between "we THINK our DR setup would work" and "we have ongoing, automated verification that it actually would" — its readiness checks continuously evaluate whether standby-Region resources genuinely have adequate capacity and configuration parity with primary, catching DR-readiness DRIFT before an actual disaster ever occurs (rather than discovering a gap only during a genuine failover, the worst possible time to find out), while its routing controls provide a safe, deliberate mechanism for actually shifting traffic during a real event, distinct from and more purpose-built for full DR orchestration than a standard Route 53 calculated health check (covered in a prior paper, which combines multiple child health checks into one derived status, a related but narrower capability without ARC''s dedicated readiness-verification and controlled-routing-control features). This is meaningfully different from AWS Elastic Disaster Recovery (covered in a prior paper, which handles continuous REPLICATION of servers into AWS for recovery, a different, complementary layer of the DR stack from ARC''s readiness-verification and routing-orchestration role) — ARC is a real, standard, and purpose-built service specifically for this centralized DR readiness and failover orchestration need, not a manual-only process.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('2ee87cb8-57f6-4c5b-963e-f0ce605c2bca', '030b206e-c700-49db-9905-3ac82057637b', 9, 'A company runs a fleet of EC2 instances where each instance is genuinely critical, and a correlated hardware failure affecting multiple instances SIMULTANEOUSLY (because they happened to be placed on the same underlying physical host or rack) would be a serious availability problem — distinct from the tightly-coupled, low-latency HPC use case a Cluster Placement Group is designed for. What EC2 Placement Group strategy specifically spreads instances across distinct underlying hardware to minimize this correlated-failure risk?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('538ccdb5-451b-4259-a4b1-169002ecb0c3', '2ee87cb8-57f6-4c5b-963e-f0ce605c2bca', 0, 'A Spread Placement Group — places each instance on genuinely DISTINCT underlying hardware (separate racks, with separate power and network sources), specifically minimizing the risk of multiple instances failing simultaneously due to a single correlated underlying hardware or infrastructure failure; this is the OPPOSITE strategy and goal from a Cluster Placement Group (covered generally in a prior paper for HPC workloads, which deliberately places instances physically CLOSE together for the lowest possible inter-instance network latency, at the cost of a genuinely higher correlated-failure risk if that specific physical area experiences a problem).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a0c0f05b-ffb2-40f0-955e-2d87236ef18e', '2ee87cb8-57f6-4c5b-963e-f0ce605c2bca', 1, 'A Cluster Placement Group, since Cluster Placement Groups are specifically defined as placing instances on distinct underlying hardware to minimize correlated hardware failure risk.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a544adcf-5b73-486f-b5f9-4ce278adc57a', '2ee87cb8-57f6-4c5b-963e-f0ce605c2bca', 2, 'EC2 Hibernate, since EC2 Hibernate is the Placement Group strategy that spreads instances across distinct underlying hardware to minimize correlated failure.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('775858fb-819f-448d-a5cc-ab1c42db5669', '2ee87cb8-57f6-4c5b-963e-f0ce605c2bca', 3, 'EC2 provides no mechanism to influence which underlying physical hardware instances are placed on; instance placement is always entirely random with no available strategy.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('2ee87cb8-57f6-4c5b-963e-f0ce605c2bca', '538ccdb5-451b-4259-a4b1-169002ecb0c3', 'A Spread Placement Group directly addresses the correlated-failure risk this scenario describes by deliberately placing each instance on genuinely SEPARATE underlying hardware — distinct host, distinct rack, with independent power and network — meaning a hardware-level failure affecting one instance''s underlying infrastructure is meaningfully less likely to simultaneously take out another instance in the same Spread group, directly useful for genuinely critical individual instances (a small number of instances each critical enough that losing more than one at once from a shared root cause would be a real problem). This is precisely the OPPOSITE goal and strategy from a Cluster Placement Group (covered generally in a prior paper for the low-latency HPC use case) — Cluster groups deliberately place instances CLOSE together specifically to minimize network latency BETWEEN them, accepting a genuinely higher shared-infrastructure-failure risk as the direct trade-off for that latency benefit; the two Placement Group strategies solve genuinely opposite problems and should not be conflated. EC2 Hibernate (covered in a prior paper) preserves an instance''s RAM contents across a stop/start cycle, an entirely unrelated concept to instance PLACEMENT strategy — EC2 genuinely does provide real, configurable control over instance placement, not purely random assignment.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('d9cef02c-659f-44ac-adf8-6618d3d84002', '030b206e-c700-49db-9905-3ac82057637b', 10, 'A company wants to be able to quickly launch a working, ready-to-use copy of a critical EC2 instance in a DIFFERENT AWS Region if their primary Region becomes unavailable — including the instance''s exact configured operating system, installed software, and settings at a specific point in time, not just the underlying data on an attached volume. What AWS mechanism supports making an EC2 instance''s complete machine image (not just its data volumes) available for launching in a different Region?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9e163e34-d3be-4716-b96c-3437e9ab8699', 'd9cef02c-659f-44ac-adf8-6618d3d84002', 0, 'Copying an AMI (Amazon Machine Image) to a different Region — an AMI captures a complete, launchable template of an EC2 instance''s configuration (operating system, installed software, settings) at the point the AMI was created, and AWS supports explicitly copying that AMI to a different Region, so if the primary Region becomes unavailable, a genuinely equivalent instance can be quickly launched in the secondary Region from that copied AMI, rather than needing to rebuild the instance''s full configuration from scratch during an actual disaster.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('30103436-d9f5-479d-9502-b2adf91dcbb3', 'd9cef02c-659f-44ac-adf8-6618d3d84002', 1, 'An EBS snapshot alone, since EBS snapshots by themselves capture an instance''s complete machine image, including its operating system and installed software configuration, not merely the data on its attached volumes.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f52f6249-2d0e-4241-946e-12687dea5897', 'd9cef02c-659f-44ac-adf8-6618d3d84002', 2, 'A Spread Placement Group, since Spread Placement Groups are the mechanism for copying an EC2 instance''s complete machine image to a different AWS Region for disaster recovery.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ac054c1f-71ad-4c38-9f14-d6bea1c131e5', 'd9cef02c-659f-44ac-adf8-6618d3d84002', 3, 'AMIs can never be copied or made available across AWS Regions; an AMI is always permanently confined to the single Region it was originally created in.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('d9cef02c-659f-44ac-adf8-6618d3d84002', '9e163e34-d3be-4716-b96c-3437e9ab8699', 'Copying an AMI to a different Region directly addresses this exact "quickly launch an equivalent instance elsewhere" DR need by preserving the FULL instance template — not just the raw data an EBS snapshot alone captures (an EBS snapshot, covered generally in prior papers, backs up a VOLUME''s data specifically, but an instance''s full bootable configuration — OS, installed packages, settings — is captured at the higher AMI level, which itself references underlying EBS snapshots as part of its definition, a genuinely important distinction: a snapshot alone isn''t directly launchable as a new instance the way a full AMI is). Explicitly copying that AMI to a secondary Region means, during an actual primary-Region outage, a team can launch a new instance directly from the pre-copied AMI in the secondary Region — with the OS and software already correctly configured — rather than needing to provision a blank instance and manually reinstall/reconfigure everything from scratch under the time pressure of an actual disaster, directly complementing cross-region RDS snapshot copy (covered in a prior paper, the equivalent pattern for database backups) for the EC2/AMI side of DR preparedness. AMIs genuinely CAN be copied across Regions — this is a real, standard, and commonly used DR-preparation step, not a permanent single-Region limitation.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('8d560bd0-8a33-4820-89d4-19fa8c8b03ef', '030b206e-c700-49db-9905-3ac82057637b', 11, 'A company stores a dataset in S3 using the One Zone-IA storage class specifically because the cost savings are worthwhile and the data can be regenerated from another source if lost. A solutions architect wants to make sure the TEAM fully understands the real resilience trade-off being made, beyond just the cost savings. What specific availability/durability characteristic distinguishes One Zone-IA from S3 Standard or Standard-IA?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d49fbab7-67bd-47fc-aeb9-926056496d53', '8d560bd0-8a33-4820-89d4-19fa8c8b03ef', 0, 'One Zone-IA stores data in only a SINGLE Availability Zone, meaning that if that specific AZ experiences a genuine, complete AZ-level failure or destruction event, the data stored in One Zone-IA is GENUINELY AT RISK of being lost entirely — a real, meaningful resilience trade-off distinct from S3 Standard and Standard-IA, both of which store data redundantly across MULTIPLE Availability Zones by default, meaning a single AZ failure alone does not put that data at risk of loss; this is exactly why One Zone-IA is only appropriate for data that is genuinely regenerable/replaceable from another source, not for irreplaceable data, regardless of how attractive the cost savings are.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ea02fd08-ce61-43f9-b1db-863302b65e1f', '8d560bd0-8a33-4820-89d4-19fa8c8b03ef', 1, 'One Zone-IA provides identical multi-Availability-Zone redundancy to S3 Standard and Standard-IA, with no meaningful difference in AZ-failure resilience between the storage classes.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fa297ce8-cffb-499e-b775-a90806ee438d', '8d560bd0-8a33-4820-89d4-19fa8c8b03ef', 2, 'S3 Standard and Standard-IA both store data in only a single Availability Zone, while One Zone-IA is the storage class that provides multi-AZ redundancy.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0cb1ea92-a116-4c7e-9065-fd1e7264df05', '8d560bd0-8a33-4820-89d4-19fa8c8b03ef', 3, 'Availability Zone failures affecting stored data are a purely theoretical concern with no real possibility of ever actually causing data loss in any S3 storage class.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('8d560bd0-8a33-4820-89d4-19fa8c8b03ef', 'd49fbab7-67bd-47fc-aeb9-926056496d53', 'This directly names the specific resilience trade-off underlying the "regenerable data" framing One Zone-IA was previously introduced with (covered generally in a prior paper, from more of a cost angle) — the genuinely important, concrete technical fact is that One Zone-IA stores data in exactly ONE Availability Zone, rather than the multiple-AZ redundancy S3 Standard and Standard-IA both provide by default, meaning a real, complete failure or destruction event affecting that single AZ specifically (a genuinely rare but real possibility — connecting to why multi-AZ resilience patterns like RDS Multi-AZ, covered generally in prior papers, and services'' default multi-AZ designs generally exist as a foundational resilience principle) puts data stored ONLY in One Zone-IA at genuine risk of permanent loss, unlike data in a multi-AZ storage class. This is exactly why One Zone-IA''s appropriate use case is narrowly scoped to data that''s genuinely regenerable or reproducible from elsewhere if lost — a real, meaningful, and directly testable trade-off a team choosing this storage class purely for its cost savings needs to genuinely understand and accept, not a purely theoretical or negligible risk, and not a case where One Zone-IA''s specific single-AZ characteristic is reversed with the multi-AZ classes.');

-- ── Domain: High-Performing Architectures (24% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('faaefbc1-6e19-4e7e-b9a5-2e7046ecb90e', '030b206e-c700-49db-9905-3ac82057637b', 12, 'A CloudFront distribution serves text-heavy content (JSON API responses, HTML, CSS, JavaScript) to users worldwide, and the team wants to reduce the amount of data actually transferred over the network for each response, directly improving page load times for end users, without needing to manually compress files themselves before uploading them to the origin. What CloudFront feature handles this automatically?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('18a2f6a6-f228-4836-8536-e17d7c9f82d3', 'faaefbc1-6e19-4e7e-b9a5-2e7046ecb90e', 0, 'CloudFront automatic compression — when enabled, CloudFront automatically compresses eligible text-based content (like JSON, HTML, CSS, and JavaScript) using Gzip or Brotli compression before delivering it to a requesting client that indicates it can accept compressed content, meaningfully reducing the actual bytes transferred over the network for each response and directly improving perceived load time, entirely handled by CloudFront itself with no need to manually pre-compress files before upload to the origin.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c675b319-1928-4b6f-8710-12e47786ea72', 'faaefbc1-6e19-4e7e-b9a5-2e7046ecb90e', 1, 'CloudFront Origin Shield, since Origin Shield''s core function is automatically compressing text-based content using Gzip or Brotli before delivering it to requesting clients.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9b880efd-aba1-4517-b332-bc93db8cdd80', 'faaefbc1-6e19-4e7e-b9a5-2e7046ecb90e', 2, 'CloudFront Regional Edge Caches, since Regional Edge Caches automatically compress eligible content using Gzip or Brotli before delivery to a requesting client.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b2fb47df-88a4-4056-bbe9-35df463aa5a0', 'faaefbc1-6e19-4e7e-b9a5-2e7046ecb90e', 3, 'CloudFront has no capability to compress content; all files must always be manually pre-compressed before being uploaded to the origin for any bandwidth savings to occur.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('faaefbc1-6e19-4e7e-b9a5-2e7046ecb90e', '18a2f6a6-f228-4836-8536-e17d7c9f82d3', 'CloudFront automatic compression is specifically a distinct, opt-in delivery-optimization feature from the caching-hierarchy concepts covered elsewhere (Origin Shield and Regional Edge Caches, both covered in prior papers, which reduce ORIGIN LOAD and improve cache-hit rates but don''t themselves compress the actual response bytes) — automatic compression instead reduces the literal SIZE of eligible text-based responses (compressible content types like JSON, HTML, CSS, JavaScript — binary formats like images/video generally aren''t meaningfully compressible this way and typically aren''t targeted) using standard Gzip or Brotli compression, negotiated automatically based on what the REQUESTING CLIENT indicates it can accept, and delivered transparently with no manual pre-compression step required by whoever manages the origin content. This directly and meaningfully reduces actual network transfer size for compressible content, improving real-world load time for end users, particularly on slower or higher-latency connections where every reduced byte has a proportionally larger impact — a real, standard, and simple-to-enable CloudFront feature, not a capability requiring manual origin-side compression work as the only option.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('cb65686e-2cfc-44ab-aeed-d08551e594ae', '030b206e-c700-49db-9905-3ac82057637b', 13, 'A workload needs extremely high, sustained IOPS for genuinely TEMPORARY data (a scratch/cache directory for intermediate processing results that don''t need to persist if the instance is stopped or terminated), and wants storage with even higher performance characteristics than a provisioned EBS volume can offer, specifically because this data''s ephemeral nature makes EBS''s network-attached persistence unnecessary overhead for this specific use case. What EC2 storage option provides this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a066f8c0-3cc0-41de-897d-09faaba66750', 'cb65686e-2cfc-44ab-aeed-d08551e594ae', 0, 'EC2 Instance Store — physically attached, local NVMe storage directly on the underlying host hardware (not network-attached the way EBS is, covered generally in prior papers), offering genuinely very high IOPS and low latency specifically because it avoids the network round-trip EBS traffic inherently involves, but critically, its data does NOT persist if the instance is stopped, terminated, or if the underlying hardware fails — making it well suited SPECIFICALLY for genuinely temporary/ephemeral data like a scratch directory, buffer, or cache, and a poor fit for anything requiring actual data durability.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e1b16b55-66bb-481f-baaf-57799b016efc', 'cb65686e-2cfc-44ab-aeed-d08551e594ae', 1, 'EBS io2, since io2''s core function is providing physically attached, local NVMe storage whose data does not persist across an instance stop or termination.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('10835240-1508-4810-b105-0c682ba6f966', 'cb65686e-2cfc-44ab-aeed-d08551e594ae', 2, 'EFS, since EFS is specifically defined as ephemeral, physically-attached local storage that does not persist data across an instance stop or termination.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('566d5d2a-1492-49fd-a95a-d59d144fa434', 'cb65686e-2cfc-44ab-aeed-d08551e594ae', 3, 'No EC2 storage option exists that offers higher raw performance than EBS; EBS is always the single fastest storage option available for any EC2 instance regardless of workload characteristics.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('cb65686e-2cfc-44ab-aeed-d08551e594ae', 'a066f8c0-3cc0-41de-897d-09faaba66750', 'Instance Store fills a genuinely distinct performance/durability trade-off point from EBS (covered generally in prior papers, including the io2 volume type''s own high-IOPS characteristics) — because Instance Store is PHYSICALLY attached directly to the same underlying host hardware the instance itself runs on, rather than being a separate, NETWORK-ATTACHED resource the way every EBS volume type is, it can offer genuinely higher raw IOPS and lower latency for workloads that can tolerate (or specifically want) its defining trade-off: data on an Instance Store volume does NOT persist if the instance is stopped, terminated, or if the underlying physical hardware experiences a failure — it is fundamentally EPHEMERAL storage, not a durability guarantee EBS provides. This makes Instance Store specifically well suited to genuinely temporary data with no persistence requirement at all — scratch space for intermediate processing, a local cache, buffer data that''s fully reconstructable or simply doesn''t matter if lost — and a genuinely poor, inappropriate choice for anything requiring real data durability, which is exactly the scenario''s described use case. EFS (covered in prior papers) is a genuinely PERSISTENT, durable, Multi-AZ shared file system, the conceptual opposite characteristic from Instance Store''s ephemeral nature — this is a real, standard, and meaningfully distinct EC2 storage option, not a redundant restatement of EBS or a non-existent alternative.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('5e396e76-3009-42bf-bf52-006c04cb24c6', '030b206e-c700-49db-9905-3ac82057637b', 14, 'An Aurora cluster''s read traffic fluctuates significantly throughout the day — heavy during business hours, near-idle overnight — and the team wants the NUMBER of Aurora read replicas to automatically increase during high-read-traffic periods and automatically decrease (reducing cost) during low-traffic periods, rather than provisioning a fixed number of replicas sized for peak load at all times. What Aurora feature supports this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dec30df8-58a8-4a93-b0ea-21903dbcb9a1', '5e396e76-3009-42bf-bf52-006c04cb24c6', 0, 'Aurora Auto Scaling (for read replicas) — automatically adds or removes Aurora read replicas based on a defined scaling policy tracking an actual performance metric (like average CPU utilization or read-replica-specific connection load across the current replica fleet), so the number of active read replicas genuinely tracks real-time read demand — scaling OUT during genuinely high-traffic periods and scaling IN during low-traffic periods to reduce cost — rather than a fixed replica count permanently sized for worst-case peak load, which would otherwise mean paying for unused replica capacity during every quieter period.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e351ae16-97d5-4cc9-b0da-fd8cbf036220', '5e396e76-3009-42bf-bf52-006c04cb24c6', 1, 'Aurora Serverless v2, since Aurora Serverless v2''s core function is specifically adding or removing the NUMBER of read replicas based on read traffic, rather than adjusting compute capacity within instances.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4d09c5d5-6b78-4675-8b25-cb9b14df73dd', '5e396e76-3009-42bf-bf52-006c04cb24c6', 2, 'Aurora Parallel Query, since Parallel Query is defined as automatically adding or removing the number of Aurora read replicas based on fluctuating read traffic.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ae15d122-7551-4966-9fab-8ec15588e8ba', '5e396e76-3009-42bf-bf52-006c04cb24c6', 3, 'Aurora provides no mechanism to automatically adjust the number of active read replicas based on traffic; the replica count must always be fixed and manually adjusted by an administrator.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('5e396e76-3009-42bf-bf52-006c04cb24c6', 'dec30df8-58a8-4a93-b0ea-21903dbcb9a1', 'Aurora Auto Scaling for read replicas addresses a genuinely distinct scaling DIMENSION from Aurora Serverless v2 (covered generally in a prior paper, which auto-scales COMPUTE CAPACITY within existing database instances up and down based on load, without changing how many separate instances/replicas exist) — Auto Scaling for read replicas instead adjusts the actual COUNT of read replica instances, adding more replicas during genuinely high-read-traffic periods to spread read load across more instances, and removing replicas during quieter periods specifically to avoid paying for replica capacity that isn''t actually needed at that moment, based on a defined scaling policy tracking a real metric like average CPU utilization across the current replica fleet. This directly extends the general Read Replica concept (covered generally in prior papers, for read-scaling a primary database''s load) with genuine elasticity, rather than requiring an administrator to provision a FIXED replica count permanently sized for worst-case peak traffic (wasting cost during every quieter period) or manually adjust replica count by hand as traffic patterns shift. Aurora Parallel Query (covered in a prior paper) speeds up a SINGLE large analytical query via storage-layer parallelization, an entirely different mechanism from adjusting replica COUNT for overall read-traffic elasticity — this is a real, standard, purpose-built Aurora capability, not a manual-only process.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('7b2019cf-b226-41cb-a62f-018b17ed7d86', '030b206e-c700-49db-9905-3ac82057637b', 15, 'A company wants to automatically trigger a specific downstream process the MOMENT a new object is uploaded to a particular S3 bucket — for example, automatically invoking a Lambda function to generate a thumbnail image, or sending a message to an SQS queue for further processing — without needing to build a separate, continuously-polling system that repeatedly checks the bucket for new objects. What S3 feature supports this kind of real-time, event-driven reaction to object changes?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('93d2c317-be67-4a73-8b4d-8cfac691f961', '7b2019cf-b226-41cb-a62f-018b17ed7d86', 0, 'S3 Event Notifications — configures a bucket to automatically send a notification the moment a specific type of event occurs on it (an object created, deleted, or restored), delivering that notification directly to a target like a Lambda function (to invoke it immediately with details about the specific object), an SQS queue, or an SNS topic — enabling genuinely real-time, event-driven processing pipelines reacting to S3 changes as they happen, entirely eliminating the need for a separate system to continuously poll the bucket checking for new objects.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('840e3c20-98f5-49f9-9553-187168be1bf4', '7b2019cf-b226-41cb-a62f-018b17ed7d86', 1, 'S3 Batch Operations, since Batch Operations'' core function is automatically triggering a downstream Lambda function or SQS message the moment a new object is uploaded to a bucket.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9c0a5cac-5e5f-4e66-96ad-ab18e4966ba5', '7b2019cf-b226-41cb-a62f-018b17ed7d86', 2, 'S3 Object Ownership, since Object Ownership is specifically defined as automatically triggering a downstream process the moment a new object is uploaded to a bucket.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bc5d31c2-7e63-45e1-9fe5-4403a2e438bb', '7b2019cf-b226-41cb-a62f-018b17ed7d86', 3, 'S3 has no mechanism to automatically notify or trigger a downstream process when an object is uploaded; any reaction to a new object always requires a separate system continuously polling the bucket.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('7b2019cf-b226-41cb-a62f-018b17ed7d86', '93d2c317-be67-4a73-8b4d-8cfac691f961', 'S3 Event Notifications are specifically the standard, purpose-built mechanism for exactly this "react the moment something happens in the bucket" need — configuring a bucket to automatically fire a notification for specific event types (object created via various upload methods, deleted, restored from an archival storage class, and others) directly to a chosen target, most commonly a Lambda function for immediate, event-driven processing (a thumbnail generator, a file-format validator, a metadata extraction pipeline), an SQS queue (useful for decoupling and buffering high-volume events, connecting to the general SQS decoupling concept covered in a prior paper), or an SNS topic for fan-out to multiple subscribers at once. This entirely eliminates the need for a separate, continuously-polling system that would otherwise have to repeatedly check the bucket for new objects — an inherently less efficient, higher-latency, and more operationally complex pattern than genuinely real-time, push-based event notifications. This is a real, standard, foundational S3 capability specifically enabling event-driven architecture patterns, not a capability requiring a custom-built polling solution as the only option.');

-- ── Domain: Cost-Optimized Architectures (20% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('45a1766c-e958-4183-949f-5382e53eee17', '030b206e-c700-49db-9905-3ac82057637b', 16, 'A company needs to change the storage class of 50 million existing objects in an S3 bucket, and separately needs to copy specific metadata tags onto another 20 million objects — both genuinely large-scale, one-time bulk operations. Individually invoking a Lambda function per object for either operation would be slow and would incur meaningful per-invocation cost at that scale. What S3 feature is purpose-built for efficiently performing a single operation across a massive number of existing objects at once?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('60db2cec-b5b8-405d-8de2-7d0bb300cd62', '45a1766c-e958-4183-949f-5382e53eee17', 0, 'S3 Batch Operations — performs a single specified operation (changing storage class, copying objects, applying tags, invoking a Lambda function once per object in a more cost-and-operationally-efficient managed job, and others) across a massive list of existing objects — potentially billions — as one managed, trackable BATCH JOB, meaningfully more efficient in both cost and operational complexity than manually invoking a separate Lambda function per individual object for a genuinely large-scale, one-time bulk operation like this.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4b7b5e9e-1926-4fb9-9518-a74886c5c5b3', '45a1766c-e958-4183-949f-5382e53eee17', 1, 'S3 Event Notifications, since Event Notifications are specifically defined as the feature for performing one operation efficiently across a massive existing list of objects as a single managed batch job.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ba3364b0-df0a-4983-b2b3-cf25e4060fb9', '45a1766c-e958-4183-949f-5382e53eee17', 2, 'S3 Storage Class Analysis, since Storage Class Analysis''s core function is performing bulk storage class changes or tag updates across millions of existing objects as a single batch job.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4f22d52b-312d-4d59-a360-4aa33e8534ac', '45a1766c-e958-4183-949f-5382e53eee17', 3, 'S3 provides no mechanism for performing a bulk operation across a large number of existing objects at once; each object must always be individually and separately processed one at a time with no batch capability available.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('45a1766c-e958-4183-949f-5382e53eee17', '60db2cec-b5b8-405d-8de2-7d0bb300cd62', 'S3 Batch Operations is specifically designed for exactly this genuinely large-scale, one-time bulk-action need, distinct from S3 Event Notifications (covered earlier this paper, which reacts to NEW, ONGOING object events one at a time in real time — not a mechanism for a single bulk pass across a large EXISTING set of objects) — a Batch Operations job takes a defined list of existing objects (often generated via an S3 Inventory report) and a single specified action to perform across every one of them, tracked and managed as one coherent JOB with progress reporting and completion status, rather than requiring a custom-built script individually invoking a separate Lambda function (with its own per-invocation cost and orchestration complexity) for each of potentially millions or billions of objects one at a time. This directly connects to and complements S3 Storage Class Analysis (covered in a prior paper, which OBSERVES access patterns and RECOMMENDS which objects should transition to a cheaper storage class) — Storage Class Analysis tells you WHAT to change, while Batch Operations is a real, efficient mechanism for actually EXECUTING that bulk change (or other bulk operations like tagging) across a massive object set at genuinely lower operational cost and complexity than a per-object, invocation-based approach.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('71a1a604-7b0e-4ea4-bf61-3fdc0c1a0f39', '030b206e-c700-49db-9905-3ac82057637b', 17, 'A company running a fleet of EC2 instances on an older instance generation (e.g., m4) is considering migrating to a newer generation (e.g., m6i) offering meaningfully better price-performance — more compute/memory capability per dollar spent — for essentially the same or lower hourly cost. What is the standard cost-optimization rationale for periodically evaluating and adopting newer EC2 instance generations, and what practical consideration does this migration require?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('46dbba2e-1d1f-4f00-adda-dfc4c2d1cbd7', '71a1a604-7b0e-4ea4-bf61-3fdc0c1a0f39', 0, 'Newer EC2 instance generations generally offer meaningfully better price-performance than older generations — often more vCPU/memory capability, or newer, more efficient underlying processor architectures, at a comparable or even LOWER hourly price than the older generation being replaced — making periodic evaluation of newer generations a genuine, real cost-optimization lever; the practical consideration is that migrating requires actually STOPPING and changing the instance type (a brief interruption) or launching new instances and cutting over, plus verifying application/workload compatibility with the new instance family, rather than the migration happening automatically with zero effort.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('463f0b14-78cd-4d69-b1ac-1cc46a65ca4e', '71a1a604-7b0e-4ea4-bf61-3fdc0c1a0f39', 1, 'Newer EC2 instance generations always cost meaningfully MORE per hour than older generations while providing identical or worse performance, making a generation upgrade never a valid cost-optimization strategy under any circumstance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('afe838a5-ad95-4fee-958a-77e6f09255a4', '71a1a604-7b0e-4ea4-bf61-3fdc0c1a0f39', 2, 'EC2 automatically and transparently upgrades every running instance to the newest available generation at no cost and with zero interruption or compatibility consideration required.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e367eafd-2cd5-4685-b751-70bef07bd0fd', '71a1a604-7b0e-4ea4-bf61-3fdc0c1a0f39', 3, 'EC2 instance generation has no meaningful relationship to price-performance; every instance generation, regardless of age, offers functionally identical performance per dollar spent.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('71a1a604-7b0e-4ea4-bf61-3fdc0c1a0f39', '46dbba2e-1d1f-4f00-adda-dfc4c2d1cbd7', 'Periodically evaluating newer EC2 instance generations is a real, standard, and genuinely underused cost-optimization lever, directly complementary to (but distinct from) rightsizing recommendations from Compute Optimizer (covered generally in a prior paper, which focuses on whether an instance is over/under-provisioned for its CURRENT generation/size, not on whether a NEWER generation might offer better price-performance for the same workload) — AWS regularly releases new instance generations built on newer, more efficient underlying processor architectures and hardware, frequently offering genuinely more compute/memory capability per dollar than the equivalent older-generation instance, sometimes even at a lower hourly price than what''s being replaced, meaning organizations that never revisit their instance generation choices are frequently leaving real, meaningful savings (or free performance headroom) on the table simply through inertia. The genuine practical consideration is that this migration is NOT automatic or zero-effort — it requires actually changing the instance type (typically requiring the instance to be stopped briefly, or launching new instances of the new generation and cutting traffic over, similar in spirit to the general instance-lifecycle considerations touched on elsewhere) and verifying the specific application or workload is actually compatible with the new instance family''s underlying architecture — a real, genuine migration effort, not something that happens automatically with no consideration required, and newer generations genuinely do NOT typically cost more for worse performance, the reverse of what one distractor claims.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('13be26e7-8ffe-4f8b-9571-2eaac4552d94', '030b206e-c700-49db-9905-3ac82057637b', 18, 'A company wants to reduce their CloudFront costs by limiting which of CloudFront''s globally distributed edge locations are actually used to serve their content — since their audience is concentrated in North America and Europe, they''re willing to accept slightly higher latency for the small percentage of users elsewhere in exchange for lower overall CloudFront pricing, rather than paying for full global edge coverage they don''t genuinely need. What CloudFront setting controls this trade-off?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ce34db2e-3d55-4cb2-8597-4723f1b39231', '13be26e7-8ffe-4f8b-9571-2eaac4552d94', 0, 'CloudFront price classes — lets a distribution owner choose which SUBSET of CloudFront''s global edge location network is actually used to serve their content (e.g., a price class limited to North America and Europe only, versus the default "all edge locations worldwide" class), directly reducing cost for an audience genuinely concentrated in specific regions, at the real trade-off that users OUTSIDE the selected price class''s regions will be served from a more distant edge location (or potentially routed to a Regional Edge Cache or the origin directly), meaningfully increasing latency specifically for those users.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('41517bc1-9b52-43f7-8806-4bf900a8a32a', '13be26e7-8ffe-4f8b-9571-2eaac4552d94', 1, 'CloudFront origin groups, since origin groups are specifically defined as the setting controlling which subset of edge locations is used to serve content and reduce cost.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f607c4f7-1782-4d6b-86b3-15c182ec193d', '13be26e7-8ffe-4f8b-9571-2eaac4552d94', 2, 'CloudFront Signed URLs, since Signed URLs are the mechanism for limiting which global edge locations serve a distribution''s content to reduce cost.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8d06b7eb-fc60-4c6d-8705-caf9d8670c9c', '13be26e7-8ffe-4f8b-9571-2eaac4552d94', 3, 'CloudFront always serves content from every global edge location for every distribution with no way to limit edge location usage or reduce cost based on audience geography.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('13be26e7-8ffe-4f8b-9571-2eaac4552d94', 'ce34db2e-3d55-4cb2-8597-4723f1b39231', 'CloudFront price classes are specifically the direct cost lever for exactly this "our audience is geographically concentrated, we don''t need full global edge coverage" trade-off — since CloudFront''s per-request and data-transfer pricing genuinely varies somewhat by edge-location region, choosing a MORE LIMITED price class (e.g., restricting to North America and Europe only, rather than the default class including every edge location worldwide) can meaningfully reduce overall cost specifically because a distribution simply isn''t paying for or actively using the full global edge network, a genuine, direct, and configurable cost-optimization setting. The real, honestly-stated trade-off is that users outside the selected price class''s covered regions will experience meaningfully worse latency, since their requests get served from a more distant edge location (or fall through to a Regional Edge Cache or the origin directly, both covered in prior papers) rather than a nearby edge specifically in their own region — a genuine cost-versus-latency decision an architect makes deliberately based on actual audience geography, not a free, no-trade-off cost reduction. CloudFront origin groups (covered in a prior paper) handle origin FAILOVER, and Signed URLs (covered in a prior paper) handle access RESTRICTION — both entirely unrelated to this specific edge-location-scope cost setting.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('cbb85aba-d25b-473b-8d12-6f843f2b9b60', '030b206e-c700-49db-9905-3ac82057637b', 19, 'A finance team wants their AWS bill broken down by which specific business unit, project, or environment (dev/staging/production) is actually driving cost — enabling accurate internal chargeback and building on the Cost Explorer team/service breakdown visibility covered in a prior paper. What underlying AWS mechanism must actually be applied to resources FIRST for that kind of cost breakdown to be possible at all?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('524d8432-31d2-462f-8b43-a8ef2468aae3', 'cbb85aba-d25b-473b-8d12-6f843f2b9b60', 0, 'Cost allocation tags — resources must first be TAGGED (with a key like "BusinessUnit," "Project," or "Environment" and an appropriate value) at creation or afterward, and those tags then explicitly ACTIVATED as cost allocation tags in the Billing console, before AWS''s cost and usage reports and tools like Cost Explorer can actually break down and filter spending by those specific tag values — the tagging and activation step is the underlying PREREQUISITE mechanism making that kind of dimensional cost visibility and internal chargeback possible in the first place, not something Cost Explorer or usage reports can do purely on their own without it.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0a017db5-9dc8-4d4e-a0e8-2f27ab9702f0', 'cbb85aba-d25b-473b-8d12-6f843f2b9b60', 1, 'AWS Budgets Actions, since Budgets Actions is specifically defined as the underlying prerequisite mechanism that must be applied to resources before any cost breakdown by business unit or project is possible.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e8e082ba-e679-43e2-820f-8683b20a5f90', 'cbb85aba-d25b-473b-8d12-6f843f2b9b60', 2, 'AWS Cost Anomaly Detection, since Cost Anomaly Detection is the prerequisite mechanism resources must be tagged with before a cost breakdown by business unit or project becomes possible.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f07f200b-56e6-4744-9f2d-0ee163fdca65', 'cbb85aba-d25b-473b-8d12-6f843f2b9b60', 3, 'AWS cost and usage visibility tools can already break down spending by business unit, project, or environment automatically, with no tagging or other prerequisite configuration required.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('cbb85aba-d25b-473b-8d12-6f843f2b9b60', '524d8432-31d2-462f-8b43-a8ef2468aae3', 'Cost allocation tags are specifically the foundational, prerequisite mechanism enabling the kind of dimensional cost visibility (by business unit, project, environment, or any other organizationally meaningful dimension) that the general Cost Explorer team/service breakdown concept (covered in a prior paper) actually depends on — without resources being explicitly tagged with a consistent, meaningful key/value scheme (and those specific tag keys then activated as cost allocation tags in the Billing console, a genuinely required, non-automatic step), AWS''s billing data has no way to know which specific business unit or project a given resource''s cost should actually be attributed to, since AWS itself has no inherent knowledge of an organization''s own internal business structure. This is directly analogous to (and often combined with) the tag-based resource ASSIGNMENT approach AWS Backup (covered in a prior paper) uses to apply backup policies — tags serving as the general-purpose mechanism connecting AWS resources to an organization''s own meaningful categorization scheme, here specifically for cost attribution and internal chargeback purposes. AWS Budgets Actions (covered in a prior paper) and Cost Anomaly Detection (covered in a prior paper) both consume/analyze EXISTING cost data for alerting purposes, neither is the underlying tagging mechanism that actually makes dimensional cost breakdown possible in the first place — this genuinely requires a real, deliberate tagging and activation step, not automatic, zero-configuration breakdown.');

-- ── Domain: High-Performing Architectures (additional — question 20) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('0abc6d21-a991-4ccf-8683-cead13eaebec', '030b206e-c700-49db-9905-3ac82057637b', 20, 'A company running ElastiCache for Redis has a dataset that has grown too large for a single Redis node''s memory capacity to hold, and read/write throughput demand has also grown beyond what one node can serve. They want to horizontally SPLIT (shard) the dataset and its throughput across multiple Redis nodes, rather than only scaling by adding more read-only replicas of one full copy of the data. What ElastiCache for Redis feature supports this kind of horizontal data partitioning across nodes?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cf133cc2-3749-44b3-8c4c-c491cb587c06', '0abc6d21-a991-4ccf-8683-cead13eaebec', 0, 'ElastiCache for Redis Cluster Mode (Enabled) — partitions (shards) the dataset across MULTIPLE node groups/shards, with each shard holding a distinct subset of the overall keyspace, allowing both total data capacity and aggregate write throughput to scale horizontally BEYOND what a single node could hold or serve, genuinely distinct from simply adding more read replicas to Cluster Mode DISABLED (which keeps the FULL dataset replicated identically on every node, scaling READ throughput but not total data capacity or write throughput beyond a single primary node''s limits).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('43d4319b-274c-4145-8bb4-af8b00e45122', '0abc6d21-a991-4ccf-8683-cead13eaebec', 1, 'ElastiCache for Memcached, since Memcached is specifically defined as the ElastiCache engine that shards a dataset across multiple nodes to scale both capacity and write throughput.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e987580e-834a-4c2a-91cd-97b74c2aa7b4', '0abc6d21-a991-4ccf-8683-cead13eaebec', 2, 'DynamoDB Accelerator (DAX), since DAX is the feature that shards an ElastiCache for Redis dataset across multiple nodes to scale beyond one node''s capacity.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0957cefa-dc85-4d93-9549-e36ce0f4289b', '0abc6d21-a991-4ccf-8683-cead13eaebec', 3, 'ElastiCache for Redis has no mechanism to scale a dataset''s total capacity or write throughput beyond what a single node can hold; adding read replicas is the only available scaling option under any circumstance.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('0abc6d21-a991-4ccf-8683-cead13eaebec', 'cf133cc2-3749-44b3-8c4c-c491cb587c06', 'Redis Cluster Mode directly extends the general Redis-vs-Memcached comparison (covered generally in a prior paper) with a genuinely important Redis-specific scaling nuance: Cluster Mode DISABLED (the simpler default) keeps one primary node holding the FULL dataset, with any read replicas holding an identical full COPY of that same data — genuinely useful for scaling READ throughput and providing replication-based high availability (echoing the general replication/HA concepts covered elsewhere), but fundamentally limited by whatever a SINGLE node''s memory can hold, and by that single primary node''s own write-throughput ceiling. Cluster Mode ENABLED instead SHARDS the dataset across multiple distinct node groups, each independently holding and serving only a PORTION of the overall keyspace — meaning total data capacity and aggregate write throughput can now scale horizontally across many nodes'' combined capacity, genuinely beyond what any single node could hold or serve alone, directly addressing the specific "dataset has outgrown one node''s memory, and write throughput has also outgrown one node''s ceiling" scenario described, which simply adding more full-copy read replicas alone cannot solve. Memcached (covered in a prior paper) does support its own multi-node distribution model via client-side hashing, but it lacks Redis''s specific persistence, richer data structures, and this particular Cluster Mode sharding-with-replication architecture — DAX (covered in a prior paper) is an entirely separate DynamoDB-specific caching layer, unrelated to ElastiCache/Redis sharding.');
