-- ============================================================
-- AWS Solutions Architect Associate (SAA-C03) — Seed Data: Paper 3
-- New content, distinct topics from Papers 1 and 2 (docs/aws_saa_seed_paper_1.sql,
-- docs/aws_saa_seed_paper_2.sql) — no repeated scenarios. Same domain
-- weighting: Design Secure 30% (6/20), Design Resilient 26% (5/20), Design
-- High-Performing 24% (5/20), Design Cost-Optimized 20% (4/20). Every
-- question checked against stable, documented AWS service behavior.
-- UUID integrity verified with scratchpad/check_uuid_dupes.mjs AND
-- cross-checked against every other seed file in the repo for zero
-- collisions before finalizing (standing process since Paper 1's real bug).
-- Run this AFTER docs/question-bank-schema.sql.
-- ============================================================

INSERT INTO question_papers (id, slug, title, exam_type, focus_tags, question_count, difficulty, is_premium, sort_order, time_limit_minutes)
VALUES ('f2826ae7-810c-46e3-ba03-0d1634bbe020', 'aws-saa-practice-3', 'AWS SAA-C03 Practice Paper 3', 'aws-saa', ARRAY['STS', 'SCPs', 'CloudHSM', 'Pre-signed URLs', 'Aurora', 'DynamoDB Global Tables', 'Snowball', 'Lambda Concurrency', 'Consolidated Billing']::TEXT[], 20, 'standard', true, 3, 30);

-- ── Domain: Design Secure Architectures (30% — 6 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('3b49753d-485a-4145-8a1f-0e82f8276862', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 1, 'An application running in Account A needs to temporarily access an S3 bucket in Account B, without creating a long-term IAM user or sharing credentials between accounts. What is the correct mechanism?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9b40257f-ddcc-41c3-8883-09adc1dfc7ae', '3b49753d-485a-4145-8a1f-0e82f8276862', 0, 'Create a duplicate IAM user in Account B with the same access key/secret pair used in Account A.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9a21d63c-3351-4513-973d-3d03689956f0', '3b49753d-485a-4145-8a1f-0e82f8276862', 1, 'Use AWS STS (Security Token Service) AssumeRole to temporarily assume an IAM role defined in Account B, which grants short-lived, automatically-expiring credentials scoped to that role''s permissions — no long-term cross-account credential sharing needed.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('69c9d1fc-6816-47bf-b53b-781eb8090606', '3b49753d-485a-4145-8a1f-0e82f8276862', 2, 'Make the S3 bucket in Account B fully public so Account A can access it without any authentication.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1168efa1-b441-4600-8555-7bb25653b6ec', '3b49753d-485a-4145-8a1f-0e82f8276862', 3, 'Cross-account access is not possible on AWS under any circumstances.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('3b49753d-485a-4145-8a1f-0e82f8276862', '9a21d63c-3351-4513-973d-3d03689956f0', 'STS AssumeRole is the standard, secure cross-account access pattern: Account B defines an IAM role with a trust policy specifying that Account A (or a specific principal within it) is allowed to assume it, and with a permissions policy scoping exactly what that role can do (e.g., read this specific S3 bucket). Account A''s application calls AssumeRole, receiving short-lived, automatically-expiring temporary credentials (typically 15 minutes to a few hours) — no long-term secret is ever shared between accounts, and the temporary credentials are scoped precisely to what''s needed. Duplicating IAM users/keys across accounts is exactly the anti-pattern this solves — long-term shared credentials are a real security liability (harder to rotate, easy to leak, no automatic expiration). Making a bucket fully public is a drastically over-broad, insecure solution to what should be a scoped, temporary need.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('fdeab22e-34b9-437b-a49d-4c1ef1230fe8', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 2, 'A company with dozens of AWS accounts under AWS Organizations wants to enforce an account-wide guardrail that NO account, regardless of any IAM permissions granted within it, can ever disable CloudTrail logging or leave a specific AWS Region. What AWS Organizations feature enforces this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e1987067-8e06-4133-8e5f-e1c157480299', 'fdeab22e-34b9-437b-a49d-4c1ef1230fe8', 0, 'IAM policies attached individually to every user in every account, since Organizations has no account-wide policy mechanism.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c8630595-6be9-4b9b-aceb-dedef18eec75', 'fdeab22e-34b9-437b-a49d-4c1ef1230fe8', 1, 'Service Control Policies (SCPs), applied at the Organization or Organizational Unit level, which set the maximum available permissions for all accounts/users/roles under them — an SCP restriction cannot be overridden by any IAM policy within a member account, even by that account''s own administrator.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e1687e49-f008-4012-bae0-b90d5b73c08f', 'fdeab22e-34b9-437b-a49d-4c1ef1230fe8', 2, 'S3 bucket policies, since bucket policies can restrict actions across every account in an Organization.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c89e7627-0fb9-41ab-bc7d-ad46b12bec59', 'fdeab22e-34b9-437b-a49d-4c1ef1230fe8', 3, 'Security Groups, since Security Groups can be applied Organization-wide to restrict API actions like disabling CloudTrail.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('fdeab22e-34b9-437b-a49d-4c1ef1230fe8', 'c8630595-6be9-4b9b-aceb-dedef18eec75', 'SCPs are specifically designed as an organization-wide permission CEILING — they don''t grant permissions themselves, but they define the maximum possible permissions for every account, user, and role beneath them in the OU/Organization hierarchy. Critically, an SCP restriction (e.g., "deny cloudtrail:StopLogging" or "deny actions outside these Regions") cannot be overridden by any IAM policy inside a member account, including that account''s own root/administrator user — this is exactly what makes SCPs the correct tool for a TRUE account-wide, non-overridable guardrail, unlike individual IAM policies (which apply per-user/role and CAN be modified by an account administrator). S3 bucket policies scope only to specific buckets, not account-wide API actions like CloudTrail management. Security Groups control network traffic (IP/port level), not IAM/API-level actions like disabling a logging service — a common category-confusion trap.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('20c1b3d9-3fd1-43d4-b392-9cc114e1cbbb', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 3, 'A financial services company has a strict regulatory requirement to use single-tenant hardware security modules (HSMs) that they have direct administrative control over for cryptographic key storage, rather than a shared/multi-tenant managed key service. Which AWS service meets this specific requirement, and how does it differ from KMS?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3ab9ee8f-efc7-4e4e-b870-00561ec5d06a', '20c1b3d9-3fd1-43d4-b392-9cc114e1cbbb', 0, 'AWS KMS, since KMS and CloudHSM are identical services with no meaningful architectural difference.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7bbb1b71-2109-4596-9bbb-966abdc17130', '20c1b3d9-3fd1-43d4-b392-9cc114e1cbbb', 1, 'AWS CloudHSM, which provisions single-tenant, dedicated hardware security modules under the customer''s direct administrative control — distinct from KMS, which is a shared, fully-managed multi-tenant key management service where AWS manages the underlying HSM infrastructure.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('81691486-ec6c-4b6e-9f43-36600dd7c6df', '20c1b3d9-3fd1-43d4-b392-9cc114e1cbbb', 2, 'Amazon Macie, since Macie provides dedicated single-tenant hardware for cryptographic key storage.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('790c33c4-e4c8-4abc-84ec-47330cb511bd', '20c1b3d9-3fd1-43d4-b392-9cc114e1cbbb', 3, 'This requirement cannot be met on AWS; dedicated single-tenant HSMs are not available as a cloud service.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('20c1b3d9-3fd1-43d4-b392-9cc114e1cbbb', '7bbb1b71-2109-4596-9bbb-966abdc17130', 'CloudHSM provisions dedicated, single-tenant hardware security modules within a VPC that the customer directly administers (including managing the HSM cluster, generating/backing up keys, and full administrative control) — matching a strict regulatory requirement for dedicated, customer-controlled hardware. KMS, by contrast, is a fully-managed, shared multi-tenant service — AWS manages the underlying HSM infrastructure, and while KMS is FIPS 140-2 validated and highly secure, the customer does not get direct administrative control over dedicated hardware the way CloudHSM provides — this is a genuine, testable architectural distinction, not interchangeable branding. Macie is a data classification/PII-discovery service (scanning S3 for sensitive data), entirely unrelated to HSM/key storage.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('73cb13b4-6857-483a-8e44-42fa8de966ff', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 4, 'A three-tier application has a web tier and a database tier in separate subnets. The security architect wants the database tier''s Security Group to allow inbound traffic ONLY from instances in the web tier, regardless of the web tier''s IP addresses changing over time (e.g., due to Auto Scaling replacing instances). What is the correct Security Group configuration approach?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5d0468c5-8909-4432-b5b7-fc1c1b9435d7', '73cb13b4-6857-483a-8e44-42fa8de966ff', 0, 'Hardcode the current IP addresses of the web tier instances as the allowed CIDR range in the database Security Group''s inbound rule.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e34db6f1-db8d-4dd8-aade-ed64a40e3079', '73cb13b4-6857-483a-8e44-42fa8de966ff', 1, 'Reference the web tier''s Security Group ID directly as the source in the database Security Group''s inbound rule — this automatically covers any instance that is a member of the web tier Security Group, regardless of IP address or Auto Scaling replacement.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bdc739fa-5b08-4395-830e-3b5758c147e3', '73cb13b4-6857-483a-8e44-42fa8de966ff', 2, 'Allow inbound traffic from 0.0.0.0/0 on the database Security Group, since this is the simplest way to guarantee the web tier can always connect.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5b3f2329-c0da-44d2-8563-58937e23aeba', '73cb13b4-6857-483a-8e44-42fa8de966ff', 3, 'Security Groups cannot reference other Security Groups as a source; only CIDR ranges are supported.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('73cb13b4-6857-483a-8e44-42fa8de966ff', 'e34db6f1-db8d-4dd8-aade-ed64a40e3079', 'Security Groups support referencing ANOTHER Security Group ID as the source (or destination) in a rule, instead of a CIDR block — this means "allow traffic from any instance that is currently a member of Security Group X," which automatically stays correct as instances in that group are added or removed (exactly what happens continuously with an Auto Scaling Group), with zero manual IP-list maintenance required. Hardcoding IPs is fragile and breaks the moment Auto Scaling replaces an instance with a new IP. Allowing 0.0.0.0/0 (the entire internet) on a DATABASE tier''s Security Group is a serious over-permissive security mistake, not a legitimate simplification. Security-Group-referencing-Security-Group is a real, commonly used, and frequently tested SAA feature — the fourth option is simply false.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('d34b1f95-7f45-4e0c-be92-b828e4730d6b', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 5, 'A media company wants to let anonymous users download a specific private S3 object for exactly 15 minutes (e.g., a link shared for a limited-time promotion), without making the object or bucket publicly accessible, and without requiring the user to have an AWS account or IAM credentials. What S3 feature enables this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a4d8a03d-df8c-45e9-bfd8-a93a8e4f8df5', 'd34b1f95-7f45-4e0c-be92-b828e4730d6b', 0, 'Making the specific object public permanently, then manually deleting it after 15 minutes.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1b40cb8f-ebf5-439f-ac6e-a3b9d9b27e4e', 'd34b1f95-7f45-4e0c-be92-b828e4730d6b', 1, 'An S3 pre-signed URL, generated by a party with legitimate access to the object, embedding a time-limited, cryptographically-signed authorization directly in the URL — anyone with that URL can access the object until it expires, with no AWS account or IAM credentials required on the requester''s side.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c27a13bf-451d-42ba-a037-46b8725f0a50', 'd34b1f95-7f45-4e0c-be92-b828e4730d6b', 2, 'Creating a new IAM user for every anonymous downloader, valid for exactly 15 minutes.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c1bdca3a-43d1-4cd1-8013-d10a70052572', 'd34b1f95-7f45-4e0c-be92-b828e4730d6b', 3, 'S3 has no mechanism for temporary access; only permanent public or permanent private are the two options.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('d34b1f95-7f45-4e0c-be92-b828e4730d6b', '1b40cb8f-ebf5-439f-ac6e-a3b9d9b27e4e', 'A pre-signed URL is generated (via the SDK/CLI) by someone who already has legitimate access to the object, embedding a cryptographic signature and an expiration time directly into the URL itself — anyone possessing that specific URL can perform the specified action (typically GET) until it expires, with the underlying object/bucket remaining otherwise private and no AWS credentials needed on the requester''s end at all. This is the standard, purpose-built mechanism for exactly this "temporary, credential-less access to an otherwise-private object" scenario. Making an object public and manually deleting it is operationally fragile (requires manual/scripted cleanup, and the object is genuinely public — discoverable/cacheable by anyone — during that window, not access-controlled by possession of a specific link). Creating disposable IAM users per anonymous downloader is a real anti-pattern (IAM users are not meant to be created/destroyed at this frequency or for anonymous, unauthenticated use cases) — pre-signed URLs exist specifically so this isn''t necessary.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('2857e42d-5223-4dad-8f27-c9777ed5ccf5', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 6, 'A compliance team needs continuous, automated detection of when any AWS resource''s configuration drifts from an approved baseline (e.g., an S3 bucket''s encryption setting gets disabled, or a Security Group rule is loosened), with a historical record of every configuration change over time. Which AWS service is purpose-built for this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('adeab327-5e60-4d78-943a-f6cee3388adc', '2857e42d-5223-4dad-8f27-c9777ed5ccf5', 0, 'AWS Config, which continuously records resource configuration state, evaluates it against defined compliance rules, and maintains a historical configuration timeline for auditing configuration drift over time.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('55f72309-0fd2-4068-b208-3374cbb25d5a', '2857e42d-5223-4dad-8f27-c9777ed5ccf5', 1, 'AWS CloudTrail, since CloudTrail is the only service capable of detecting configuration drift.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a3174642-68e0-41e0-8898-7ceaadfe0e6e', '2857e42d-5223-4dad-8f27-c9777ed5ccf5', 2, 'Amazon CloudWatch, since CloudWatch''s only function is tracking resource configuration compliance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('670922f1-71b2-44f6-a9c0-edaefd76c6c1', '2857e42d-5223-4dad-8f27-c9777ed5ccf5', 3, 'AWS Trusted Advisor, since Trusted Advisor maintains a full historical configuration timeline for every resource.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('2857e42d-5223-4dad-8f27-c9777ed5ccf5', 'adeab327-5e60-4d78-943a-f6cee3388adc', 'AWS Config is purpose-built specifically for this: it continuously records the configuration state of supported resources, can evaluate that state against Config Rules (either AWS-managed or custom, e.g., "S3 buckets must have encryption enabled") to flag non-compliant resources, and maintains a full historical timeline showing exactly when and how a resource''s configuration changed — directly matching "detect drift from baseline" and "historical record of every change." CloudTrail logs WHO made an API call and WHEN (the action taken), which is related but distinct from Config''s focus on the resulting resource STATE over time — CloudTrail alone doesn''t evaluate compliance rules or show a resource''s configuration history the way Config does. CloudWatch is a metrics/logging/alarming service focused on operational performance data, not configuration-state compliance tracking. Trusted Advisor gives point-in-time best-practice recommendations across cost/performance/security/fault-tolerance categories, not a continuous configuration-change history.');

-- ── Domain: Design Resilient Architectures (26% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('6dafa992-ac67-486c-82b4-da58f68f3ae3', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 7, 'A globally distributed application needs a NoSQL database where data written in one Region is automatically, asynchronously replicated to tables in several other Regions, allowing low-latency reads AND writes from users in each of those Regions against their local table. What DynamoDB feature provides this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2f797499-fa46-4d73-8740-b13f6ef47f1c', '6dafa992-ac67-486c-82b4-da58f68f3ae3', 0, 'DynamoDB Accelerator (DAX), since DAX''s core function is multi-Region replication.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c1d213e3-3c1a-4cd6-9005-f60135eea5f9', '6dafa992-ac67-486c-82b4-da58f68f3ae3', 1, 'DynamoDB Global Tables, which provide fully managed, multi-Region, multi-active replication — writes made in any Region''s replica table are automatically propagated to all other Regions'' replica tables, enabling local low-latency reads and writes everywhere.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6b72bded-14db-4c86-be21-c1d69d89f018', '6dafa992-ac67-486c-82b4-da58f68f3ae3', 2, 'DynamoDB Read Replicas, which is the correct DynamoDB feature name for this capability.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('121a1720-86c2-4926-bfad-b119601913d0', '6dafa992-ac67-486c-82b4-da58f68f3ae3', 3, 'DynamoDB does not support any form of multi-Region replication.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('6dafa992-ac67-486c-82b4-da58f68f3ae3', 'c1d213e3-3c1a-4cd6-9005-f60135eea5f9', 'DynamoDB Global Tables provide fully managed, multi-active (not just read replicas — every replica table accepts both reads AND writes) replication across chosen Regions, with automatic, asynchronous propagation of writes made in any Region to all other participating Regions'' tables — exactly matching "low-latency reads AND writes from users in each Region against their local table," a multi-active pattern distinct from a typical primary/read-replica setup where only one Region accepts writes. DAX is an in-memory caching layer for a SINGLE table''s read performance (covered in Paper 2), not a multi-Region replication feature. "DynamoDB Read Replicas" isn''t the correct DynamoDB feature name — Read Replicas is an RDS term for a different, single-direction (not multi-active) replication pattern; conflating the two services'' terminology is a common test trap.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('8e99a7ed-0d0d-48c2-ac2f-9712d86a1137', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 8, 'A company running a MySQL-compatible database on RDS wants significantly higher availability and faster failover than standard RDS Multi-AZ provides, along with storage that is automatically replicated six ways across three Availability Zones. Which AWS database service should they migrate to?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9e273bad-1501-4b46-aec7-d416519f793a', '8e99a7ed-0d0d-48c2-ac2f-9712d86a1137', 0, 'Amazon Aurora (MySQL-compatible edition), which is designed for higher availability than standard RDS, with storage automatically replicated across 6 copies in 3 AZs and typically faster failover than standard RDS Multi-AZ.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('290d02f1-88a5-4f1d-b343-a87c43cabea0', '8e99a7ed-0d0d-48c2-ac2f-9712d86a1137', 1, 'Amazon Redshift, since Redshift is designed as a drop-in, higher-availability replacement for any transactional MySQL workload.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('983db384-ae21-473a-ba2d-0960b833b469', '8e99a7ed-0d0d-48c2-ac2f-9712d86a1137', 2, 'Amazon Neptune, since Neptune provides the same relational MySQL compatibility with higher availability.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('26a7a17f-777a-4ea4-a7d8-caaf13db9d74', '8e99a7ed-0d0d-48c2-ac2f-9712d86a1137', 3, 'No AWS database service offers higher availability than standard RDS Multi-AZ.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('8e99a7ed-0d0d-48c2-ac2f-9712d86a1137', '9e273bad-1501-4b46-aec7-d416519f793a', 'Aurora is AWS''s own MySQL- and PostgreSQL-compatible relational database, architecturally distinct from standard RDS: its storage layer automatically and continuously replicates data six ways across three Availability Zones, and Aurora typically fails over faster than standard RDS Multi-AZ (often under 30 seconds) because of this storage-level design, plus Aurora supports up to 15 low-latency read replicas that can also serve as failover targets — directly matching "higher availability and faster failover... storage automatically replicated six ways across three AZs." Redshift is a data warehouse for analytics/OLAP workloads (large-scale aggregate queries), not a drop-in replacement for transactional MySQL OLTP workloads. Neptune is a graph database (for highly connected data like social networks or recommendation engines), not MySQL-compatible at all — a clear category mismatch.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('4dae2f76-a32b-4c69-9171-20343ee48494', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 9, 'An Auto Scaling Group needs to run a cleanup script (e.g., deregistering the instance from an internal service registry, flushing logs to S3) on each instance BEFORE it is actually terminated during a scale-in event, rather than the instance being abruptly killed. What ASG feature enables this graceful termination behavior?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('facf7d7b-d405-4bac-b0bb-d2eda56bd386', '4dae2f76-a32b-4c69-9171-20343ee48494', 0, 'Auto Scaling Lifecycle Hooks, which can pause an instance in a "Terminating:Wait" state for a configurable timeout, giving time for a cleanup script/Lambda function to run via an event notification before the instance actually terminates.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6bccdff4-d77f-4ddb-8d2b-bfe04ad2dbc0', '4dae2f76-a32b-4c69-9171-20343ee48494', 1, 'Target Tracking Scaling Policies, since target tracking is what controls graceful termination timing.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('aca91c15-4138-4af8-ad00-fffd5f0b4614', '4dae2f76-a32b-4c69-9171-20343ee48494', 2, 'ASGs always terminate instances instantly with no possible delay or hook mechanism of any kind.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6f9a82d6-2875-4606-b02b-72ee0f262532', '4dae2f76-a32b-4c69-9171-20343ee48494', 3, 'Health checks, since configuring a longer health check grace period is the mechanism for graceful termination scripts.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('4dae2f76-a32b-4c69-9171-20343ee48494', 'facf7d7b-d405-4bac-b0bb-d2eda56bd386', 'Lifecycle Hooks are specifically designed to pause an instance at a defined point in the scale-in (or scale-out) transition — for termination, an instance enters a "Terminating:Wait" state for a configurable timeout (up to 48 hours, with heartbeat extension), during which an event is published (to SNS/EventBridge) that can trigger a Lambda function or other automation to perform cleanup (deregistering from a service registry, flushing logs, gracefully draining connections) before the instance actually completes termination and moves to "Terminating:Proceed." Target Tracking Scaling Policies control WHEN scaling actions happen based on a metric target (e.g., keep average CPU at 50%), not what happens to an individual instance during termination. The health check grace period controls how long a NEWLY LAUNCHED instance is given before health checks start being enforced (avoiding premature termination during startup) — a different mechanism for a different point in an instance''s lifecycle, not scale-in cleanup.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('dda022fe-1f9d-489a-b98f-0376edb295e4', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 10, 'A company wants their RDS automated backups and manual snapshots to also be available in a second Region, so that if the primary Region has an extended outage, they can restore the database there. What is the correct approach?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7a3dec8a-6518-4851-b3aa-921e66e4ac43', 'dda022fe-1f9d-489a-b98f-0376edb295e4', 0, 'RDS snapshots are automatically available in every AWS Region by default with no configuration needed.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6301bc1f-d513-4f0d-b13f-6aeb72a8d1d0', 'dda022fe-1f9d-489a-b98f-0376edb295e4', 1, 'Use the RDS "copy snapshot to another Region" capability (manually or automated via AWS Backup cross-Region copy) to create a copy of the snapshot in the target Region, from which a new database instance can later be restored in that Region if needed.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('63ab3c1e-e8f9-4c6a-838c-509c6b11e46a', 'dda022fe-1f9d-489a-b98f-0376edb295e4', 2, 'RDS snapshots cannot ever be copied or made available outside the Region where the database resides.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('08cb15c4-e94f-41d3-ab23-e15a46934f15', 'dda022fe-1f9d-489a-b98f-0376edb295e4', 3, 'Enabling Multi-AZ automatically copies every snapshot to a second Region.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('dda022fe-1f9d-489a-b98f-0376edb295e4', '6301bc1f-d513-4f0d-b13f-6aeb72a8d1d0', 'RDS snapshots are Regional resources by default — they are NOT automatically available in other Regions. To achieve cross-Region disaster recovery from snapshots, RDS provides a specific "copy snapshot" capability that lets you copy a manual or (via AWS Backup) automated snapshot to a different target Region, where it can later be used to restore a new database instance if the primary Region becomes unavailable — this must be explicitly configured/triggered, not automatic. Multi-AZ (covered in Paper 1) provides HA WITHIN a Region via a standby in a second AZ — it is entirely separate from, and does not by itself provide, cross-REGION snapshot copying or disaster recovery. Understanding that Multi-AZ solves AZ-level failure while cross-Region snapshot copy (or a separate cross-Region read replica) solves REGION-level failure is a key SAA distinction.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('1728c008-c932-428f-bb4c-4da7b041a659', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 19, 'An EC2 instance occasionally fails its underlying hardware (system) status check due to a physical host issue, requiring the instance to be moved to new hardware. The application cannot tolerate manual intervention delays for this specific failure type. What EC2/CloudWatch feature can automatically handle this without an Auto Scaling Group?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fd55589b-a9df-4f9a-afef-51041ed6d4f7', '1728c008-c932-428f-bb4c-4da7b041a659', 0, 'A CloudWatch alarm configured with the "Recover this instance" action, which automatically migrates the instance to new underlying hardware (preserving its instance ID, private IP, EBS volumes, and other configuration) when a system status check failure is detected.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f52c479c-55f0-40f9-9dbd-80a1373db67a', '1728c008-c932-428f-bb4c-4da7b041a659', 1, 'This scenario always requires an Auto Scaling Group; no other AWS mechanism can respond to a system status check failure.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2129ad40-cb30-4c4e-af15-a7aaf6cbc831', '1728c008-c932-428f-bb4c-4da7b041a659', 2, 'System status check failures can only ever be resolved by AWS Support manually intervening, with no automated customer-side option.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('27526758-16b4-49a6-a71e-92f301533995', '1728c008-c932-428f-bb4c-4da7b041a659', 3, 'Enabling S3 Versioning on the instance''s root volume automatically triggers hardware recovery.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('1728c008-c932-428f-bb4c-4da7b041a659', 'fd55589b-a9df-4f9a-afef-51041ed6d4f7', 'EC2 distinguishes two status check types: instance status (issues at the OS/instance level, e.g., a kernel panic) and system status (issues with the underlying physical hardware/host). A CloudWatch alarm can be configured to trigger the "Recover" action specifically on a system status check failure — this automatically stops the instance, migrates it to new, healthy underlying hardware, and restarts it, all while PRESERVING the instance''s ID, private IP address, elastic IPs, and attached EBS volumes — no Auto Scaling Group is required for this specific self-healing behavior on a single, standalone instance. This is a real, standalone EC2/CloudWatch feature, not dependent on ASG membership, and does not require manual AWS Support intervention for this common failure mode. S3 Versioning is an object-storage feature entirely unrelated to EC2 instance hardware recovery.');

-- ── Domain: Design High-Performing Architectures (24% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('5398ac54-daad-4f85-99b3-8bfd894864e4', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 11, 'An application needs to upload a 20GB video file to S3. A single PUT request is slow and, if it fails partway through, requires restarting the ENTIRE upload from scratch. What S3 feature addresses both the speed and the restart-from-scratch problem?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7f2d041e-9cc8-4748-a9c9-0c36f06974fd', '5398ac54-daad-4f85-99b3-8bfd894864e4', 0, 'S3 Multipart Upload, which splits a large object into smaller parts uploaded independently (in parallel, improving speed) — if one part fails, only that part needs to be retried, not the entire object.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('aed9871e-6988-488f-a56a-9516d4100442', '5398ac54-daad-4f85-99b3-8bfd894864e4', 1, 'S3 Versioning, since enabling versioning automatically splits large uploads into faster, resumable parts.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4064c134-8a8c-4b54-9acd-0b70e7204d51', '5398ac54-daad-4f85-99b3-8bfd894864e4', 2, 'S3 Object Lock, since Object Lock is what enables resumable, parallel uploads.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1cdced5c-2c05-48a4-af4a-b18b665a3997', '5398ac54-daad-4f85-99b3-8bfd894864e4', 3, 'There is no way to improve upload speed or resumability for large S3 objects.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('5398ac54-daad-4f85-99b3-8bfd894864e4', '7f2d041e-9cc8-4748-a9c9-0c36f06974fd', 'S3 Multipart Upload splits a large object into independent parts (as small as 5MB each, up to thousands of parts) that can be uploaded in parallel — directly improving throughput/speed — and critically, if a specific part fails partway through, only THAT part needs to be re-uploaded and retried, not the entire 20GB object from the beginning, which is the direct fix for the "restart from scratch" problem. AWS recommends Multipart Upload for any object over 100MB, and it''s required (not just recommended) above 5GB. Versioning tracks multiple versions of a whole object over time — an unrelated concept to how a single upload is split/parallelized. Object Lock provides WORM (write-once-read-many) compliance protection against deletion/overwrite — also unrelated to upload mechanics.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('17195de3-c16d-4f2d-bbe4-591cb6b216f6', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 12, 'A company needs to migrate 500 terabytes of on-premises data to S3. Their available internet bandwidth would take several months to transfer this volume, which is unacceptable. What AWS service is designed specifically for this kind of large-scale, offline data migration?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('69debb72-adc1-4188-8269-090de70775b3', '17195de3-c16d-4f2d-bbe4-591cb6b216f6', 0, 'AWS Snowball (or Snowball Edge for larger volumes/on-device compute), a physical device shipped to the customer, loaded locally with the data, then shipped back to AWS where the data is loaded into S3 — bypassing internet bandwidth limitations entirely for the bulk transfer.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c3d77ee9-3112-404a-8867-8bded0660fb8', '17195de3-c16d-4f2d-bbe4-591cb6b216f6', 1, 'Amazon CloudFront, since CloudFront is designed for bulk one-time data migration from on-premises to S3.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c0a0ddcd-953e-431a-8484-7ad0b23c5476', '17195de3-c16d-4f2d-bbe4-591cb6b216f6', 2, 'AWS Direct Connect is the only option, and always transfers 500TB in under 24 hours regardless of connection speed.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4b3bd89b-b79d-4b00-9a51-2c4ec8dcc815', '17195de3-c16d-4f2d-bbe4-591cb6b216f6', 3, 'S3 Transfer Acceleration alone fully solves any bandwidth-constrained large migration with no additional service needed.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('17195de3-c16d-4f2d-bbe4-591cb6b216f6', '69debb72-adc1-4188-8269-090de70775b3', 'The AWS Snow Family (Snowball, Snowball Edge, and Snowmobile for truly massive exabyte-scale migrations) exists specifically for large-volume, offline data transfer where available network bandwidth would make an online transfer impractically slow: AWS ships a physical, ruggedized storage device to the customer, the customer loads it with data locally over their own LAN (fast), ships it back to AWS, and AWS imports the data directly into S3 — completely bypassing the customer''s internet bandwidth as the bottleneck for the bulk data movement. CloudFront is a content delivery CDN for serving content to end users, unrelated to bulk one-time migration. Direct Connect provides a dedicated network link with more consistent bandwidth/latency than internet transfer, but is still bounded by its provisioned bandwidth — it does not transfer 500TB "in under 24 hours regardless of speed," and for a large enough volume relative to available bandwidth, physical transfer via Snowball is still faster and is the AWS-recommended pattern specifically for this volume/bandwidth mismatch. Transfer Acceleration speeds up transfers over the existing internet path via CloudFront edge locations — it does not eliminate a fundamental bandwidth-vs-volume mismatch the way physical device transfer does.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('06dbde70-35f4-4b2f-bd59-6a9fe4a5cc70', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 13, 'A latency-sensitive Lambda function experiences noticeably slow response times specifically on its first invocation after a period of inactivity, but is fast on subsequent invocations shortly after. What is this phenomenon called, and what AWS feature directly addresses it?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a115b5ea-6b4e-40a5-93cd-215c22238498', '06dbde70-35f4-4b2f-bd59-6a9fe4a5cc70', 0, 'This is called a "cold start" — the delay from Lambda initializing a new execution environment; Provisioned Concurrency keeps a specified number of execution environments pre-initialized and ready to respond immediately, avoiding this delay.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('44d33911-765d-4095-9cf1-2771a94f72e8', '06dbde70-35f4-4b2f-bd59-6a9fe4a5cc70', 1, 'This is called a "warm start," and is an unavoidable, unaddressable characteristic of all serverless compute with no mitigation available.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('881e6e1f-946e-4ac1-bb8b-f5ec61ecb2c3', '06dbde70-35f4-4b2f-bd59-6a9fe4a5cc70', 2, 'This is caused by insufficient EBS volume size attached to the Lambda function, and is fixed by provisioning a larger EBS volume.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c2b8987d-f119-42eb-ab33-d15edee454e9', '06dbde70-35f4-4b2f-bd59-6a9fe4a5cc70', 3, 'This only happens with Lambda functions written in Python, and switching languages is the only fix.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('06dbde70-35f4-4b2f-bd59-6a9fe4a5cc70', 'a115b5ea-6b4e-40a5-93cd-215c22238498', 'A "cold start" is the well-known Lambda phenomenon where, after a period without invocations, Lambda has to initialize a brand-new execution environment (download code, start the runtime, run any initialization code) before it can process the request — adding noticeable latency to that first invocation specifically, while subsequent invocations reuse the already-warm environment and respond quickly. Provisioned Concurrency directly addresses this by keeping a specified number of execution environments pre-initialized and ready at all times, so even a request after a period of inactivity hits an already-warm environment. Cold starts affect Lambda functions across all supported languages to varying degrees (not exclusively Python), and are a genuinely real, addressable characteristic — not something with zero available mitigation. Lambda does not use EBS volumes for its own execution environment in the way this option implies; EBS is unrelated to cold-start latency.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('dfad9208-76d9-4335-b3c0-4bc4eb4a8008', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 14, 'A tightly-coupled, network-latency-sensitive HPC (High Performance Computing) workload requires the lowest possible inter-instance network latency and highest network throughput between EC2 instances, more important than spreading instances across multiple AZs for fault tolerance. What EC2 Placement Group strategy fits this requirement?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('53bbdbc1-accf-40d0-b188-21b6b3651fc7', 'dfad9208-76d9-4335-b3c0-4bc4eb4a8008', 0, 'Spread placement group, which is specifically designed to maximize inter-instance network throughput by placing instances as close together as physically possible.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b1562aef-7a24-4c14-b57e-5b60e35a40a2', 'dfad9208-76d9-4335-b3c0-4bc4eb4a8008', 1, 'Cluster placement group, which packs instances close together within a single Availability Zone specifically to achieve low-latency, high-throughput networking between them — the direct trade-off being reduced fault tolerance (an AZ-level or even rack-level failure affects the whole group) compared to spreading instances out.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0d439f0d-8748-4a86-91a8-be66c9339d08', 'dfad9208-76d9-4335-b3c0-4bc4eb4a8008', 2, 'Partition placement group, since partition groups always provide the lowest possible latency of any placement strategy.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cbaf47d7-82e5-471e-8685-26297dc125f9', 'dfad9208-76d9-4335-b3c0-4bc4eb4a8008', 3, 'Placement groups have no effect on network latency or throughput between instances.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('dfad9208-76d9-4335-b3c0-4bc4eb4a8008', 'b1562aef-7a24-4c14-b57e-5b60e35a40a2', 'A Cluster placement group packs instances close together within a single Availability Zone (often on the same underlying hardware racks with high-bandwidth, low-latency networking between them) — specifically optimized for exactly this scenario: tightly-coupled HPC/big-data workloads where inter-instance network performance matters more than fault tolerance, since a single infrastructure failure could affect many instances in the cluster at once (an explicit, accepted trade-off for this use case). Spread placement groups do the OPPOSITE — they deliberately place each instance on distinct underlying hardware to MINIMIZE simultaneous failure risk (maximizing fault tolerance), which is the wrong trade-off for a workload prioritizing raw network performance over resilience. Partition placement groups divide instances into logical partitions across distinct hardware sets (common for large distributed systems like Hadoop/Cassandra, balancing some fault isolation with some grouping) — not specifically the lowest-latency option; Cluster is the correct answer for the priority stated in this scenario specifically.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('b5d1a76e-caff-4bad-80aa-45e3b2a08db5', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 20, 'An application stores large CSV files in S3 and needs to retrieve only a handful of specific columns and rows matching a filter condition from each file, currently downloading and parsing the ENTIRE file client-side just to discard most of the data. Which S3 feature reduces this waste by filtering server-side, before data is even transferred?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d163619b-7517-40d4-a99f-0510532f581f', 'b5d1a76e-caff-4bad-80aa-45e3b2a08db5', 0, 'S3 Select, which lets an application retrieve only a specific subset of data from within an object using SQL-like expressions, with S3 performing the filtering server-side before sending only the matching data over the network.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a31a7723-8b36-43ad-8bb2-196dc79ec690', 'b5d1a76e-caff-4bad-80aa-45e3b2a08db5', 1, 'S3 Transfer Acceleration, since it filters object content server-side before transfer.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('957ee185-a4d4-44cd-8c47-306825f838a4', 'b5d1a76e-caff-4bad-80aa-45e3b2a08db5', 2, 'S3 Object Lock, since Object Lock is responsible for server-side content filtering.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1de2bcb5-8ae0-464c-bd46-eb0ab65cf125', 'b5d1a76e-caff-4bad-80aa-45e3b2a08db5', 3, 'This is not possible; S3 always returns the entire object regardless of what the application actually needs.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('b5d1a76e-caff-4bad-80aa-45e3b2a08db5', 'd163619b-7517-40d4-a99f-0510532f581f', 'S3 Select lets an application issue a SQL-like expression (SELECT specific columns WHERE a condition is met) against a CSV, JSON, or Parquet object stored in S3, with S3 itself performing the filtering server-side and returning ONLY the matching, requested data over the network — instead of transferring the entire object and discarding most of it client-side, which wastes both network bandwidth and client-side processing time. AWS has reported this can reduce data transfer and improve retrieval performance significantly for exactly this "small subset of a large object" access pattern. Transfer Acceleration speeds up transfer of the FULL object via CloudFront edge locations — it does not filter content at all, an entirely different mechanism. Object Lock is a WORM compliance/retention feature, unrelated to query filtering. S3 absolutely supports this server-side filtering capability — it is a real, purpose-built, commonly used feature specifically to avoid the "download everything, use very little" inefficiency described.');

-- ── Domain: Design Cost-Optimized Architectures (20% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('c54b366f-3fe0-48f0-93f2-025acb437180', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 15, 'A company has 12 separate AWS accounts across different departments, each individually paying On-Demand rates and separately negotiating volume discounts. What AWS Organizations feature allows them to combine usage across all accounts to reach volume pricing tiers faster and receive one consolidated invoice?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f1d520ef-e18a-4b18-95a2-695a58bc0a30', 'c54b366f-3fe0-48f0-93f2-025acb437180', 0, 'Consolidated Billing (a core AWS Organizations feature), which combines usage across all member accounts for volume pricing/discount tier purposes and produces a single bill for the whole Organization, while still providing per-account usage breakdowns.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('39c4fff0-9804-4111-b048-cb9a5bc65ac2', 'c54b366f-3fe0-48f0-93f2-025acb437180', 1, 'Service Control Policies, since SCPs are what combine billing across accounts.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dca4b2d1-9ebe-41b3-a654-98bd9a1be404', 'c54b366f-3fe0-48f0-93f2-025acb437180', 2, 'AWS accounts can never share or combine billing under any AWS feature; each account is always billed in complete isolation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ca4bcb08-d674-422f-9b94-92f89695dc1f', 'c54b366f-3fe0-48f0-93f2-025acb437180', 3, 'Trusted Advisor, since combining billing across accounts is Trusted Advisor''s primary function.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('c54b366f-3fe0-48f0-93f2-025acb437180', 'f1d520ef-e18a-4b18-95a2-695a58bc0a30', 'Consolidated Billing is a core AWS Organizations capability: a designated management/payer account receives one combined invoice covering every member account''s usage, AND usage is aggregated across all accounts for the purpose of reaching volume-based pricing tiers/discounts (e.g., S3 volume discount tiers, Reserved Instance/Savings Plan sharing across accounts) faster than any single account could reach alone — directly matching both stated goals (combine usage for pricing tiers, one consolidated invoice), while still providing itemized per-account breakdowns for cost allocation/chargeback purposes. SCPs (covered earlier in this paper) are a permissions guardrail mechanism, entirely unrelated to billing aggregation. Trusted Advisor provides best-practice recommendations across several categories, but does not itself combine or manage cross-account billing.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('64cb552f-70c9-40c2-bf54-0a292bbb70b0', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 16, 'A company hosts a public dataset in S3 that is downloaded frequently by external researchers, and wants those external downloaders to bear the data transfer cost instead of the company''s own AWS account absorbing it, while keeping the bucket accessible without requiring a support contract or complex access negotiation. What S3 feature enables this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('76150410-3ec0-48ff-b97f-65da644b09cf', '64cb552f-70c9-40c2-bf54-0a292bbb70b0', 0, 'S3 Requester Pays, which shifts the data transfer and request costs to the party downloading the object instead of the bucket owner, while the bucket owner still pays for storage.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6bed5182-3fc2-45f2-9957-e4c7328b79a0', '64cb552f-70c9-40c2-bf54-0a292bbb70b0', 1, 'S3 Object Lock, since enabling Object Lock shifts data transfer costs to whoever downloads an object.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a1e94dfb-348a-414b-acce-71c5c4ee0bf8', '64cb552f-70c9-40c2-bf54-0a292bbb70b0', 2, 'This is not possible; the bucket owner always pays 100% of all data transfer costs with no exception.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e1622e57-b706-465f-b2df-2b3fbcbf2344', '64cb552f-70c9-40c2-bf54-0a292bbb70b0', 3, 'S3 Transfer Acceleration, since enabling Transfer Acceleration automatically shifts billing responsibility to the requester.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('64cb552f-70c9-40c2-bf54-0a292bbb70b0', '76150410-3ec0-48ff-b97f-65da644b09cf', 'S3 Requester Pays is specifically designed for exactly this scenario — a bucket owner hosting data that will be downloaded heavily by others (a public dataset, shared research data) can enable Requester Pays so that the downloading party''s AWS account is billed for the data transfer and request costs, while the bucket owner continues to pay only for storage — the requester must include specific authentication/headers acknowledging they''ll be charged, but no separate support contract or bespoke access negotiation is required beyond that. Object Lock is a WORM compliance/retention feature (preventing deletion/overwrite for a period), entirely unrelated to billing responsibility. Transfer Acceleration speeds up transfers via CloudFront edge locations but does not change WHO is billed — that remains the bucket owner unless Requester Pays is separately enabled.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('224c0faf-985a-4c18-9a92-1a6f267e1e33', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 17, 'A company''s traffic follows a highly predictable pattern: heavy load every weekday from 9 AM to 6 PM, and minimal load overnight and on weekends. They currently run a fixed-size fleet sized for peak load 24/7, which is expensive. What Auto Scaling approach would reduce cost while maintaining performance during known peak hours?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('27cddc52-6618-4d9a-a286-29632c6829fc', '224c0faf-985a-4c18-9a92-1a6f267e1e33', 0, 'Scheduled Scaling, which adjusts the Auto Scaling Group''s minimum/maximum/desired capacity at specific, predictable times (e.g., scale up before 9 AM weekdays, scale down after 6 PM), taking advantage of a known, predictable traffic pattern rather than reacting to it after the fact.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a57c7065-6f40-4c97-965d-ac5b63693b5d', '224c0faf-985a-4c18-9a92-1a6f267e1e33', 1, 'Keep the fixed-size fleet unchanged, since Auto Scaling cannot be configured based on time of day under any circumstance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ac503585-d3d3-4fba-9d77-57d5950b328a', '224c0faf-985a-4c18-9a92-1a6f267e1e33', 2, 'Manually launch and terminate instances by hand every day at the same times, since Auto Scaling has no automated way to do this.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('661622ec-1602-4e66-bf59-96b6aa3eba11', '224c0faf-985a-4c18-9a92-1a6f267e1e33', 3, 'Permanently reduce the fleet to the minimum size needed for overnight/weekend traffic, accepting degraded performance during weekday peak hours as an acceptable trade-off.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('224c0faf-985a-4c18-9a92-1a6f267e1e33', '27cddc52-6618-4d9a-a286-29632c6829fc', 'Scheduled Scaling is the correct fit specifically because the traffic pattern is KNOWN and PREDICTABLE (not reactive/unknown) — it lets an administrator define scaling actions at specific times (increase capacity right before the predictable weekday 9 AM ramp-up, decrease it after the predictable 6 PM drop-off), proactively matching capacity to demand rather than waiting for a dynamic scaling policy to react to a metric threshold being crossed after load has already increased. This directly reduces cost (fewer running instances overnight/weekends) while maintaining performance during the known peak window (capacity is already scaled up before peak arrives, not scrambling to catch up). Auto Scaling absolutely supports time-based scheduled actions — this is a real, commonly used, and frequently tested ASG feature, making manual daily instance management entirely unnecessary and strictly worse operationally. Simply shrinking the fleet permanently would cause real performance degradation during the (still real, still needing full capacity) weekday peak — not an acceptable trade-off when Scheduled Scaling solves the actual problem directly.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('d2f7b4be-fdc9-44d0-9f96-e5a32a61e818', 'f2826ae7-810c-46e3-ba03-0d1634bbe020', 18, 'A finance team wants visibility into which AWS service and which team is driving month-over-month cost increases, and wants to be automatically notified if spending is on pace to exceed a set monthly threshold before the month ends. Which two AWS services together address this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2b261d71-f596-4401-97ee-68fe120f8ab7', 'd2f7b4be-fdc9-44d0-9f96-e5a32a61e818', 0, 'AWS Cost Explorer, for visualizing and analyzing historical cost/usage trends broken down by service, account, or tag; AND AWS Budgets, for setting spend thresholds and receiving proactive alerts (including forecasted-to-exceed notifications) before the threshold is actually reached.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2c2c53af-5b92-4195-9fdc-0b8669030093', 'd2f7b4be-fdc9-44d0-9f96-e5a32a61e818', 1, 'AWS Config and AWS CloudTrail, since these two services are specifically designed for cost visibility and budget alerting.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f3409216-e401-4c12-9091-1b2bb6e6d98f', 'd2f7b4be-fdc9-44d0-9f96-e5a32a61e818', 2, 'There is no AWS-native way to get cost visibility by service or proactive spend-threshold alerts; a third-party tool is required.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7d44e6cb-259f-4a01-836e-a3679b39564d', 'd2f7b4be-fdc9-44d0-9f96-e5a32a61e818', 3, 'Amazon Inspector and Amazon GuardDuty, since these two services provide cost breakdown and budget alerting as their core function.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('d2f7b4be-fdc9-44d0-9f96-e5a32a61e818', '2b261d71-f596-4401-97ee-68fe120f8ab7', 'Cost Explorer provides visual analysis of historical and current cost/usage data, filterable and groupable by service, linked account, tag, and other dimensions — directly answering "which service/team is driving cost increases." AWS Budgets lets you define a spend (or usage) threshold and set up alerts — critically, including alerts based on FORECASTED spend, meaning you can be notified that you''re on pace to exceed a monthly budget before the month actually ends and the overage has already happened, not just after the fact. Config and CloudTrail are configuration-compliance and API-activity-logging services respectively — genuinely useful tools, but not built for cost visibility or budget alerting. Inspector (vulnerability scanning) and GuardDuty (threat detection) are both security services, entirely unrelated to cost management — a clear category mismatch distractor.');
