-- ============================================================
-- AWS Certified Solutions Architect - Associate (SAA-C03) — Seed Data: Paper 10
-- FINAL paper in this batch — brings AWS SAA to 10 papers, matching BCHHC
-- parity. New content, distinct topics from Papers 1-9 — no repeated
-- scenarios. Topic list checked directly against the actual question text
-- of Papers 1-9 (grepped from the files) before writing.
--
-- Domain-question-count breakdown, confirmed BEFORE writing any questions
-- (per standing process): Secure 6 + Resilient 5 + High-Performing 5 +
-- Cost-Optimized 4 = 20, confirmed.
--   Secure (6): Secrets Manager automatic rotation, AWS WAF Bot Control,
--     CloudTrail Organization trail, permissions boundary vs. SCP
--     comparison, KMS multi-Region keys, GuardDuty Malware Protection.
--   Resilient (5): Route 53 Geolocation routing, RDS snapshot
--     cross-account sharing, native EFS replication, ALB connection
--     draining/deregistration delay, S3 CRR delete marker replication.
--   High-Performing (5): DynamoDB GSI/LSI, Aurora reader endpoint, ASG
--     scaling policy types (target tracking/step/simple), ASG predictive
--     scaling, ALB sticky sessions.
--   Cost-Optimized (4): RDS Reserved Instances, S3 Intelligent-Tiering
--     optional archive access tiers, RI/Savings Plan expiration
--     monitoring, AWS Well-Architected Framework cost review.
--
-- IDs were generated via scripts/fill-seed-uuids.mjs, which replaces every
-- distinct placeholder token with a fresh, real UUID (consistently across
-- every occurrence) — this file has already had that script run against
-- it; the UUIDs below are real. Cross-checked against every other seed
-- file in the repo for zero collisions before finalizing, plus the
-- distractor-language sanity scan and a manual re-read of every answer key
-- against its option text. The question_papers ARRAY[...]::TEXT[] literal
-- and every option token were manually re-read once before running the
-- fill script.
-- Run this AFTER docs/question-bank-schema.sql.
-- ============================================================

INSERT INTO question_papers (id, slug, title, exam_type, focus_tags, question_count, difficulty, is_premium, sort_order, time_limit_minutes)
VALUES ('bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 'aws-saa-practice-10', 'AWS SAA-C03 Practice Paper 10', 'aws-saa', ARRAY['Secrets Manager Rotation', 'WAF Bot Control', 'CloudTrail Org Trail', 'KMS Multi-Region Keys', 'Geolocation Routing', 'EFS Replication', 'DynamoDB GSI/LSI', 'Aurora Reader Endpoint', 'RDS Reserved Instances']::TEXT[], 20, 'standard', true, 10, 30);

-- ── Domain: Secure Architectures (30% — 6 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('3b13338d-e425-41a4-bb32-b3d5a78cbca7', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 1, 'A company stores an RDS database password in Secrets Manager (covered generally in a prior paper), but wants that password to be automatically CHANGED on a regular schedule, with the new password value automatically updated both in the database itself and in Secrets Manager, so applications retrieving the credential always get a currently-valid value without any manual rotation process. What Secrets Manager feature supports this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('44f8cb84-1673-43fe-a570-8c25e72d9b09', '3b13338d-e425-41a4-bb32-b3d5a78cbca7', 0, 'Secrets Manager automatic rotation — using a Lambda function (either an AWS-provided template for common services like RDS, or a custom one) that Secrets Manager invokes on a defined schedule to actually change the credential on the target service (here, the RDS database) AND update the stored secret value in Secrets Manager in the same coordinated operation, so applications retrieving the secret always get a currently-valid credential with no manual rotation process, and the actual database password value is never manually handled by a person during a rotation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c680087f-392d-4ab9-b195-b53eb0f0baef', '3b13338d-e425-41a4-bb32-b3d5a78cbca7', 1, 'SSM Parameter Store, since Parameter Store is specifically defined as automatically rotating a stored credential on a schedule and updating the corresponding value on the target database.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dac0373e-6a03-4ce7-9e27-1f829605d744', '3b13338d-e425-41a4-bb32-b3d5a78cbca7', 2, 'AWS Certificate Manager, since ACM''s core function is automatically rotating a database password on a schedule and updating both Secrets Manager and the target RDS instance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('62b47bde-eacd-4d44-a561-7e43d0326d29', '3b13338d-e425-41a4-bb32-b3d5a78cbca7', 3, 'Secrets Manager provides no mechanism for automatic credential rotation; any password change must always be performed and updated manually by an administrator.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('3b13338d-e425-41a4-bb32-b3d5a78cbca7', '44f8cb84-1673-43fe-a570-8c25e72d9b09', 'Automatic rotation is specifically the capability distinguishing Secrets Manager from the more general-purpose SSM Parameter Store (covered generally in a prior paper, which stores configuration and secrets but has no equivalent built-in, coordinated rotation mechanism of its own) — Secrets Manager invokes a Lambda function on a defined schedule that performs the actual coordinated two-sided update: changing the real credential on the target service itself (here, actually changing the RDS database user''s password) AND updating the value stored in Secrets Manager to match, in one managed operation, so there''s never a window where the two are out of sync. This directly closes a real, meaningful security gap that STATIC, never-rotated credentials represent — a credential that never changes remains equally valuable to an attacker indefinitely if ever compromised, whereas regularly rotating credentials meaningfully shrinks that window of usefulness. AWS provides pre-built rotation Lambda templates for common services like RDS specifically to make this easier to adopt, though custom rotation functions are also supported for other credential types. ACM (covered in a prior paper) manages TLS certificates, an entirely different credential type with its own separate renewal mechanism — this is a real, standard, and purpose-built Secrets Manager capability, not a manual-only process.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('647332b0-d537-47b9-af6d-6687191a6cd0', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 2, 'A company''s public-facing application is being hit by a large volume of automated, non-human traffic — bots scraping content, credential-stuffing bots, and bots attempting to bypass promotional-pricing logic — mixed in alongside genuine, legitimate human user traffic that must continue being served normally. Standard WAF rate-based rules (covered generally in a prior paper) alone aren''t effectively distinguishing sophisticated bot traffic from legitimate spikes in real human usage. What AWS WAF feature is purpose-built for more accurately identifying and managing bot traffic specifically?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b52aba32-a5a8-4172-82df-4c001b43ab2d', '647332b0-d537-47b9-af6d-6687191a6cd0', 0, 'AWS WAF Bot Control — a managed rule group specifically designed to identify and categorize bot traffic (distinguishing known-good bots like legitimate search engine crawlers from unwanted or malicious ones) using signals well beyond simple request-rate thresholds, letting a company allow, block, or specifically CAPTCHA-challenge suspected bot traffic with meaningfully more precision than a general rate-based rule alone can provide, since sophisticated bots are often specifically designed to stay under simple volume-based thresholds while still behaving in bot-like ways.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('db01ff66-d9b8-48ed-a065-dee18c5035ad', '647332b0-d537-47b9-af6d-6687191a6cd0', 1, 'AWS Shield Advanced, since Shield Advanced is specifically defined as the WAF feature that identifies and categorizes bot traffic using signals beyond simple request-rate thresholds.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2517a024-3538-4f77-9065-d87f3a6dea82', '647332b0-d537-47b9-af6d-6687191a6cd0', 2, 'Amazon Macie, since Macie''s core function is identifying and managing automated bot traffic on a public-facing web application.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f63e935d-cccd-475d-b0cd-770f686d849e', '647332b0-d537-47b9-af6d-6687191a6cd0', 3, 'AWS WAF has no capability to distinguish bot traffic from legitimate human traffic beyond simple request-rate thresholds; rate-based rules are the only available mechanism for any kind of traffic filtering.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('647332b0-d537-47b9-af6d-6687191a6cd0', 'b52aba32-a5a8-4172-82df-4c001b43ab2d', 'WAF Bot Control specifically addresses a genuine limitation of rate-based rules alone (covered generally in a prior paper) — a sufficiently sophisticated bot can be deliberately designed to stay under a simple volume/rate threshold while still exhibiting other bot-like characteristics (unusual request patterns, missing typical browser behaviors, known malicious bot signatures), meaning rate-limiting alone can miss genuinely unwanted automated traffic while potentially still over-restricting legitimate, bursty human usage. Bot Control specifically categorizes traffic using richer signals than raw request volume, letting an organization take differentiated action — allowing known-good bots (like legitimate search engine crawlers a business genuinely wants indexing its content), blocking clearly malicious ones, or presenting a CAPTCHA challenge specifically to ambiguous traffic as a way to distinguish genuine humans from bots without outright blocking potentially-legitimate users. This is a genuinely more targeted capability than Shield Advanced (covered in a prior paper, which specifically addresses DDoS-scale VOLUMETRIC attacks, a different threat category from the mixed-legitimate-and-bot traffic pattern described here) or Macie (covered in a prior paper, which discovers sensitive data in S3, entirely unrelated to bot traffic management) — this is a real, standard, purpose-built WAF capability, not a gap requiring rate-based rules alone.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('f1729e2b-1ab1-4d63-85b5-0fa71a762240', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 3, 'A company with dozens of AWS accounts under AWS Organizations wants EVERY account''s API activity logged to CloudTrail (covered generally in a prior paper) consistently, without relying on each individual account''s administrator to remember to enable and correctly configure their own trail — and wants all of that activity centrally aggregated into one S3 bucket in a designated management/security account for unified review. What CloudTrail feature is purpose-built for this Organization-wide logging need?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c453e065-9b88-474c-a93e-74a0acf68ab5', 'f1729e2b-1ab1-4d63-85b5-0fa71a762240', 0, 'A CloudTrail Organization trail — created once from the AWS Organizations management account, automatically applies to and logs activity from EVERY member account in the Organization (including future accounts added later, with no per-account manual setup required), delivering all of that activity centrally to one designated S3 bucket, ensuring consistent, Organization-wide audit logging without depending on each individual account administrator to remember to configure their own separate trail.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('de2289d6-454c-4d7b-a011-39a42d13a4b2', 'f1729e2b-1ab1-4d63-85b5-0fa71a762240', 1, 'AWS Config, since Config''s core function is creating a single trail that automatically logs API activity across every account in an AWS Organization to one centralized S3 bucket.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8c0614ee-f872-43a1-b512-0217bdc401f4', 'f1729e2b-1ab1-4d63-85b5-0fa71a762240', 2, 'AWS Firewall Manager, since Firewall Manager is specifically defined as centrally aggregating CloudTrail activity logs from every member account in an Organization.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8ff545f1-9fee-4aba-b2a7-895ade66b0e0', 'f1729e2b-1ab1-4d63-85b5-0fa71a762240', 3, 'CloudTrail has no mechanism for Organization-wide logging; each individual member account must always separately configure and maintain its own independent trail with no centralized option available.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('f1729e2b-1ab1-4d63-85b5-0fa71a762240', 'c453e065-9b88-474c-a93e-74a0acf68ab5', 'A CloudTrail Organization trail directly addresses the real, common problem of relying on every individual member account administrator to independently remember to enable and correctly configure their own trail — a genuinely fragile approach at real multi-account scale, since a single forgotten or misconfigured account creates a real, unmonitored blind spot. Created once from the Organizations management account, an Organization trail automatically applies across EVERY current member account and, critically, every FUTURE account added to the Organization later, with no additional per-account action required, delivering all that activity centrally to one designated S3 bucket in a chosen management/security account — directly extending CloudTrail (covered generally in a prior paper, for single-account API-activity auditing) with Organization-wide consistency and centralization. This is genuinely distinct from AWS Config (covered in a prior paper, which tracks resource CONFIGURATION state, not API call activity) and Firewall Manager (covered in a prior paper, which centrally enforces WAF/Shield/security-group POLICY, not logging) — a real, standard, and purpose-built CloudTrail capability specifically for exactly this multi-account consistency and centralization need, not a manual, per-account-only requirement.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('38146732-ed7f-4012-aa09-de0626cf118b', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 4, 'A solutions architect is explaining the difference between an IAM permissions boundary (covered generally in a prior paper) and an SCP (covered generally in a prior paper) to a team confused about when to use each, since both concepts describe a MAXIMUM permission ceiling rather than granting access directly. What is the key distinction in SCOPE between these two mechanisms?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ef43637f-65ba-49ff-9502-70fff35be6c1', '38146732-ed7f-4012-aa09-de0626cf118b', 0, 'A permissions boundary is attached to and limits an INDIVIDUAL IAM user or role''s maximum possible permissions (useful, for example, when delegating role-creation authority to team leads, ensuring even a role THEY create can''t exceed a defined ceiling), while an SCP is attached at the ACCOUNT or ORGANIZATIONAL UNIT level, capping the maximum permissions available to EVERY principal within that entire account or OU at once, regardless of what any individual principal''s own IAM policies or permissions boundary might otherwise allow — both are "maximum ceiling, not a grant" mechanisms, but they operate at fundamentally different scopes: one principal at a time versus an entire account/OU at once.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('18ec9fec-4a05-4bc1-9282-be889f4bad7e', '38146732-ed7f-4012-aa09-de0626cf118b', 1, 'An SCP is attached to an individual IAM user or role to limit that one specific principal''s maximum permissions, while a permissions boundary applies to an entire AWS account or Organizational Unit at once — the reverse of the correct scope distinction.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1276403b-c098-47b0-9f1a-4195a21e40e4', '38146732-ed7f-4012-aa09-de0626cf118b', 2, 'Permissions boundaries and SCPs are functionally and structurally identical mechanisms operating at the exact same scope, with no meaningful distinction between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a46c56ab-0c3e-4d8c-9961-3cbd2e4e2070', '38146732-ed7f-4012-aa09-de0626cf118b', 3, 'Neither a permissions boundary nor an SCP can ever restrict what an IAM identity-based policy would otherwise allow; both mechanisms only ever grant additional permissions.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('38146732-ed7f-4012-aa09-de0626cf118b', 'ef43637f-65ba-49ff-9502-70fff35be6c1', 'This directly contrasts two concepts covered separately in prior papers, making their genuinely important SCOPE distinction explicit: a permissions boundary is attached to ONE SPECIFIC IAM user or role, capping the maximum permissions THAT SPECIFIC PRINCIPAL can ever have regardless of what its own identity-based policies grant — the canonical use case being delegated role-creation authority, where a permissions boundary ensures even a role created BY a delegated administrator can never exceed a pre-defined ceiling, preventing privilege escalation through that delegation. An SCP instead attaches at the AWS Organizations ACCOUNT or ORGANIZATIONAL UNIT level, capping the maximum permissions available to EVERY principal within that entire account or OU simultaneously — a company-wide or department-wide guardrail, not a per-principal one. Both share the same underlying philosophy — setting a maximum CEILING that IAM policies operate within, never themselves GRANTING access on their own (an important shared characteristic, correctly ruling out the last distractor) — but they''re genuinely complementary tools operating at fundamentally different SCOPES: permissions boundaries for fine-grained, per-principal delegation safety, and SCPs for broad, account/OU-wide organizational guardrails, which is exactly why understanding when each is the appropriate tool matters for real architecture decisions.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('339c0241-712e-4466-984e-43a47ba4272b', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 5, 'A company operates a globally distributed application needing to encrypt and decrypt data using the SAME KMS key material across multiple AWS Regions — for example, encrypting data in one Region and decrypting that same data directly in another Region — without needing to re-encrypt the data separately for each Region using an entirely separate, unrelated key. What KMS feature supports this cross-Region key usage?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('020ff302-3af8-4f9d-920a-0557dce55796', '339c0241-712e-4466-984e-43a47ba4272b', 0, 'KMS multi-Region keys — a set of KMS keys in different Regions that share the SAME underlying key material (created as related "replica keys" from a single "primary key"), allowing data encrypted with the key in one Region to be directly decrypted using its related replica key in another Region, without needing to re-encrypt the data separately per Region or transmit the plaintext data across Regions solely for re-encryption purposes — genuinely distinct from simply having entirely separate, UNRELATED KMS keys independently created in each Region, which would NOT share key material and therefore could not decrypt data encrypted by a different Region''s key at all.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8819af76-e6b1-4ad2-b979-dca4929a1256', '339c0241-712e-4466-984e-43a47ba4272b', 1, 'AWS Certificate Manager Private CA, since ACM Private CA is specifically defined as sharing the same underlying key material across multiple AWS Regions for direct cross-Region decryption.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ca052d37-5737-4dc0-ba6c-006742ccd6e9', '339c0241-712e-4466-984e-43a47ba4272b', 2, 'CloudHSM, since CloudHSM''s core function is automatically sharing identical key material across multiple AWS Regions for direct cross-Region decryption without re-encryption.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3c0e49a8-c987-4570-9a47-a3080d60bdaf', '339c0241-712e-4466-984e-43a47ba4272b', 3, 'KMS keys can never share underlying key material across different AWS Regions; every Region always requires an entirely separate, unrelated key with no cross-Region relationship possible.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('339c0241-712e-4466-984e-43a47ba4272b', '020ff302-3af8-4f9d-920a-0557dce55796', 'KMS multi-Region keys specifically solve the "same key material, usable directly in multiple Regions" need — by default, KMS keys (covered generally in prior papers, including cross-account access and grants) are genuinely Region-specific and independent, meaning data encrypted with a key in one Region normally CANNOT be decrypted using a different, unrelated key created independently in another Region, since they don''t share underlying key material at all. Multi-Region keys specifically change this: a "primary" key in one Region can have "replica" keys created in other Regions that share the SAME underlying cryptographic key material (though each replica still has its own independent key policy and lifecycle for access-control purposes), meaning data encrypted with the primary key can be directly decrypted using a replica key in a different Region, without needing to design a workaround like re-encrypting the data separately for each Region or transmitting decrypted plaintext across Regions purely to re-encrypt it there. This is genuinely useful for global applications with data or disaster-recovery needs spanning multiple Regions — a real, standard, and purpose-built KMS capability, not a permanent Region-siloed limitation, and genuinely distinct from CloudHSM (covered in a prior paper, single-tenant dedicated hardware, not a cross-Region key-sharing mechanism) or ACM Private CA (covered in a prior paper, certificate issuance, unrelated to KMS key material sharing).');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('586eb371-aec8-4f22-b099-9397c63ae1b3', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 6, 'A security team using GuardDuty (covered generally in a prior paper) for continuous threat detection wants GuardDuty to ALSO specifically scan EBS volumes attached to EC2 instances and container workloads that GuardDuty''s other detection mechanisms have flagged as potentially compromised, actively checking for known malware signatures on those specific volumes. What GuardDuty feature provides this additional, targeted malware-scanning capability?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fbab8ad5-4306-43ee-b5bf-a9746ef342d2', '586eb371-aec8-4f22-b099-9397c63ae1b3', 0, 'GuardDuty Malware Protection — extends GuardDuty''s general threat-detection capability (covered generally in a prior paper, which analyzes account activity, network traffic, and DNS logs for anomalous behavior) with the ability to actually scan EBS volumes attached to specific EC2 instances or container workloads that OTHER GuardDuty findings have flagged as potentially compromised, checking those volumes for known malware signatures — providing an additional, targeted layer of verification specifically triggered by an existing suspicious finding, rather than GuardDuty''s baseline detection relying solely on behavioral/network-level signals alone.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f0f46ec8-75cd-43c2-aaa2-50919d2f9f36', '586eb371-aec8-4f22-b099-9397c63ae1b3', 1, 'Amazon Inspector, since Inspector''s core function is scanning EBS volumes for known malware signatures specifically as an extension of GuardDuty''s own findings.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('12a5d44e-fb56-433c-96a1-97f53c8176c9', '586eb371-aec8-4f22-b099-9397c63ae1b3', 2, 'AWS Config, since Config is specifically defined as the feature that scans EBS volumes attached to flagged EC2 instances for known malware signatures.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('861fd326-ff6e-4bfc-83f8-487e2ea62bc4', '586eb371-aec8-4f22-b099-9397c63ae1b3', 3, 'GuardDuty has no capability to scan the actual contents of an EBS volume for malware; it can only ever analyze network traffic and account activity metadata.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('586eb371-aec8-4f22-b099-9397c63ae1b3', 'fbab8ad5-4306-43ee-b5bf-a9746ef342d2', 'GuardDuty Malware Protection specifically extends GuardDuty''s baseline detection capability (covered generally in a prior paper, which analyzes account API activity, VPC Flow Logs-derived network signals, and DNS query logs for anomalous BEHAVIORAL patterns) with an actual CONTENT-level scanning capability targeted specifically at resources GuardDuty''s OTHER findings have already flagged as suspicious — rather than continuously scanning every single EBS volume in an account (which would be far less targeted and more resource-intensive), Malware Protection specifically triggers when an EXISTING GuardDuty finding suggests a specific instance or container workload may be compromised, then scans that SPECIFIC resource''s attached volumes for known malware signatures, adding a genuinely useful additional verification layer confirming (or ruling out) whether an actual malware infection is present, beyond just the behavioral indicator that originally triggered the investigation. This is a real, distinct GuardDuty capability, genuinely different from Amazon Inspector (which performs vulnerability/CVE scanning of EC2 instances and container images for known SOFTWARE WEAKNESSES, a different function from malware-signature scanning of volume contents) and from AWS Config (covered in a prior paper, which tracks resource configuration state, unrelated to malware scanning) — GuardDuty genuinely does support this content-level scanning as a real, purpose-built extension, not a permanent limitation to behavioral/network signals alone.');

-- ── Domain: Resilient Architectures (26% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('1eb7bfe2-32be-4f55-b418-12de36e8e20f', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 7, 'A company wants Route 53 to route users to a SPECIFIC regional endpoint based on the user''s actual GEOGRAPHIC LOCATION — for example, routing all users physically located in France to a France-specific endpoint with localized content and pricing, and users in Japan to a completely different, Japan-specific endpoint — rather than routing based on network latency or simple failover status. What Route 53 routing policy supports this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('83b86971-a842-4edf-a3cb-6536552d590c', '1eb7bfe2-32be-4f55-b418-12de36e8e20f', 0, 'Geolocation routing — routes DNS responses based specifically on the geographic location the DNS query actually originates from (down to a configurable granularity like country or continent), letting a company deliver a genuinely different, localized endpoint (different content, different pricing, or regulatory-driven routing) to users based on where they actually are — a fundamentally different routing GOAL from latency-based routing (covered generally in a prior paper, which optimizes for the fastest RESPONSE TIME regardless of the user''s specific location) or failover routing (covered generally in a prior paper, which reacts to health-check STATUS, not geography).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('110e62c6-c672-48d2-8b0d-4b4c162a1b51', '1eb7bfe2-32be-4f55-b418-12de36e8e20f', 1, 'Latency-based routing, since latency-based routing is specifically defined as routing DNS responses based on a user''s actual geographic location rather than network response time.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ae3374d9-cd0a-4cbf-85eb-5973a26ee1bc', '1eb7bfe2-32be-4f55-b418-12de36e8e20f', 2, 'Multi-value answer routing, since multi-value answer routing is specifically defined as routing users to a region-specific endpoint based on their actual geographic location.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c443acdc-4378-47d8-8a0f-ad4d993f0a81', '1eb7bfe2-32be-4f55-b418-12de36e8e20f', 3, 'Route 53 has no routing policy capable of directing traffic based on a user''s actual geographic location; only latency and health-check-based routing decisions are possible.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('1eb7bfe2-32be-4f55-b418-12de36e8e20f', '83b86971-a842-4edf-a3cb-6536552d590c', 'Geolocation routing is specifically defined by its routing CRITERION — the actual, real geographic origin of the DNS query itself — which is a genuinely different goal from every other Route 53 routing policy covered in prior papers: latency-based routing optimizes purely for the fastest measured network RESPONSE TIME, which doesn''t necessarily correlate with a user''s actual physical location (a user could have lower latency to a Region other than their own geographically nearest one, depending on network topology); failover routing reacts to HEALTH-CHECK status, switching only upon a detected failure; multi-value answer routing (covered in a prior paper) returns several healthy IPs for basic client-side load distribution and resilience, unrelated to geography; and calculated health checks (covered in a prior paper) combine multiple health check statuses into one derived result. Geolocation routing specifically enables genuinely location-driven business or regulatory requirements — serving deliberately different, localized content, pricing, or even complying with data-residency-adjacent routing requirements (connecting to data sovereignty concepts covered generally in Security+ content) based specifically on where a user actually is, a genuine, real, and distinctly different routing use case from optimizing purely for speed or reacting purely to health status.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('7a2388d0-0f4d-447b-a648-c0d25cdd4f97', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 8, 'A company wants to share a specific RDS database SNAPSHOT with a separate AWS account — for example, giving a data analytics team in a different account a point-in-time copy of production data to work with — without granting that other account any ongoing, direct access to the actual live production RDS instance itself. Does RDS support sharing a snapshot across accounts this way?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ea14e7bb-b411-4223-9233-d53b50822138', '7a2388d0-0f4d-447b-a648-c0d25cdd4f97', 0, 'Yes — an RDS snapshot (manual snapshot specifically, covered generally alongside automated backups in a prior paper) can be explicitly shared with one or more other specific AWS accounts (or made public, though that''s rarely appropriate for real data), letting the receiving account restore a NEW RDS instance from that shared snapshot entirely within their own account, giving them a genuinely independent, point-in-time COPY of the data to work with — without ever granting any ongoing, direct access to the original, live production RDS instance itself, which remains fully isolated in the source account throughout.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('631a4fa2-f302-42e6-b1b0-51380644a18d', '7a2388d0-0f4d-447b-a648-c0d25cdd4f97', 1, 'No — RDS snapshots can only ever be restored within the exact same AWS account that originally created them, with cross-account snapshot sharing being technically impossible.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4af50e2b-58b9-4d35-afaf-41efa9ce92c6', '7a2388d0-0f4d-447b-a648-c0d25cdd4f97', 2, 'Sharing an RDS snapshot with another account automatically grants that account ongoing, direct access to the original, live production RDS instance itself, not merely a separate copy.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3879c271-df46-4328-bbf7-30aff160425b', '7a2388d0-0f4d-447b-a648-c0d25cdd4f97', 3, 'RDS snapshots can only be shared across accounts by using AWS DataSync to physically transfer the underlying database files between accounts.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('7a2388d0-0f4d-447b-a648-c0d25cdd4f97', 'ea14e7bb-b411-4223-9233-d53b50822138', 'RDS genuinely supports sharing a manual snapshot directly with one or more specific other AWS accounts — a real, standard capability directly analogous to (though a separate mechanism from) AMI cross-Region copying (covered generally in a prior paper, for EC2) and cross-account S3 replication (covered generally in a prior paper) — the receiving account can then restore an entirely NEW, independent RDS instance from that shared snapshot within their own account, giving them a genuine point-in-time copy of the data to work with (for analytics, testing, or other legitimate purposes) while the ORIGINAL, live production instance remains fully isolated and untouched in the source account, with no ongoing or direct access granted to it at all as a side effect of the snapshot share. This is a meaningfully cleaner and more controlled data-sharing pattern than granting broader ongoing access to the live instance itself would be, since the shared snapshot represents a fixed point in time rather than continuously exposing production. This genuinely does not require any separate data-transfer service like AWS DataSync (a real service, but for a different use case — transferring files/data between storage systems, not database snapshot sharing) — cross-account RDS snapshot sharing is a real, standard, and directly built-in RDS capability.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('82a908fa-3915-41f1-86ad-63579e3e445a', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 9, 'A company running EFS (covered generally in a prior paper for its Multi-AZ resilience within a Region) wants an ADDITIONAL, independent copy of that file system data replicated to a DIFFERENT AWS Region entirely, specifically for disaster recovery in case the entire primary Region becomes unavailable — not just protection against a single-AZ failure, which EFS''s native Multi-AZ design already handles. What EFS feature supports this cross-Region replication?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('df66e8aa-8758-4174-a66d-19891aced7f3', '82a908fa-3915-41f1-86ad-63579e3e445a', 0, 'EFS Replication — a native EFS feature that continuously and automatically replicates a source file system''s data to a destination EFS file system in a DIFFERENT AWS Region (or the same Region), providing genuine cross-Region disaster recovery protection beyond what EFS''s inherent Multi-AZ design (covered generally in a prior paper, which protects specifically against a single-AZ failure WITHIN one Region) already provides on its own — a full Region-level outage is a genuinely different failure scenario Multi-AZ resilience alone does not protect against.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('371b6294-3850-4e56-b933-c709182a1d6b', '82a908fa-3915-41f1-86ad-63579e3e445a', 1, 'EFS''s inherent Multi-AZ design, since Multi-AZ replication within a single Region is specifically defined as also providing full protection against an entire Region becoming completely unavailable.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('41cd6030-c04a-4720-ba26-715360f5faab', '82a908fa-3915-41f1-86ad-63579e3e445a', 2, 'AWS Backup Vault Lock, since Vault Lock''s core function is continuously replicating an EFS file system''s data to a different AWS Region for disaster recovery.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('57ef6f95-b07d-48b4-928a-0d9426d6d122', '82a908fa-3915-41f1-86ad-63579e3e445a', 3, 'EFS provides no mechanism for replicating file system data to a different AWS Region; EFS data is always permanently confined to the single Region it was originally created in.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('82a908fa-3915-41f1-86ad-63579e3e445a', 'df66e8aa-8758-4174-a66d-19891aced7f3', 'EFS Replication specifically addresses a genuinely different failure scenario from EFS''s inherent, built-in Multi-AZ resilience (covered generally in a prior paper) — Multi-AZ protects against the loss of any SINGLE Availability Zone WITHIN one Region, since the file system''s data is already redundantly stored across multiple AZs in that Region by design, but this native characteristic does NOT protect against an entire REGION becoming unavailable, a genuinely different and broader failure scenario requiring an actual second, independent copy of the data living in a completely separate Region. EFS Replication provides exactly that — continuously and automatically replicating data from a source file system to a destination file system in a different Region (directly analogous in purpose to S3 Cross-Region Replication, covered generally in prior papers, and RDS cross-region snapshot copy, also covered in a prior paper, applied specifically to EFS''s own native replication mechanism), giving genuine disaster-recovery protection specifically against a full-Region outage that Multi-AZ resilience alone cannot address. AWS Backup Vault Lock (covered in a prior paper) provides IMMUTABILITY protection for backups, an entirely different function from cross-Region replication — EFS genuinely does support this native replication capability, not a permanent single-Region confinement.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('9e285d62-8605-4256-9528-116e1df8eebb', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 10, 'An Application Load Balancer needs to remove an EC2 instance from active service (for a planned deployment or scale-in event) WITHOUT abruptly terminating any requests currently being actively processed by that instance — instead allowing those specific in-flight requests to genuinely finish, while new requests stop being routed to that instance immediately. What ALB feature supports this graceful instance removal?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1f759ffb-ed95-4a48-b9c0-6408ae912b60', '9e285d62-8605-4256-9528-116e1df8eebb', 0, 'Connection draining (also called deregistration delay) — when an instance is being deregistered from an ALB''s target group, the load balancer immediately STOPS routing any NEW requests to that instance, but allows a configurable grace period during which requests ALREADY in flight on that instance can genuinely finish processing normally, rather than those in-progress requests being abruptly cut off mid-response — directly relevant to a graceful deployment or scale-in event, where abruptly terminating active user requests would be a real, avoidable disruption.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('34c8f29a-4c02-4a97-a375-ca26971680f4', '9e285d62-8605-4256-9528-116e1df8eebb', 1, 'ASG Warm Pools, since Warm Pools are specifically defined as the ALB feature allowing in-flight requests to finish processing before an instance is removed from service.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f03c54d7-16e2-46a4-8a8f-329df8f566d1', '9e285d62-8605-4256-9528-116e1df8eebb', 2, 'ALB path-based routing, since path-based routing is specifically defined as allowing in-flight requests on a deregistering instance to finish before new requests stop being routed to it.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cdf23f0f-4ee3-42c3-8fec-43f481fba3e7', '9e285d62-8605-4256-9528-116e1df8eebb', 3, 'An ALB always abruptly terminates every in-flight request the instant an instance begins deregistration, with no mechanism to allow in-progress requests to finish gracefully.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('9e285d62-8605-4256-9528-116e1df8eebb', '1f759ffb-ed95-4a48-b9c0-6408ae912b60', 'Connection draining (deregistration delay) specifically addresses the real operational need for GRACEFUL instance removal — rather than an abrupt, disruptive cutoff the instant an instance starts deregistering (which would genuinely cut off real, in-progress user requests mid-response, a real and avoidable bad user experience), the ALB immediately stops sending any NEW requests to the deregistering instance (so it genuinely stops receiving additional load right away) while allowing a configurable grace period for requests ALREADY being processed on that instance to actually complete normally before the instance is fully removed from service. This is directly relevant to routine, planned operational events like a rolling deployment or an Auto Scaling Group scale-in event (covered generally in prior papers, including the ASG lifecycle hook concept for running custom actions during instance termination) — connection draining specifically ensures those routine, planned operations don''t create real, avoidable user-facing disruption. This is genuinely different from ASG Warm Pools (covered in a prior paper, which pre-initializes instances for faster SCALE-OUT, the opposite direction of this scenario) and ALB path-based routing (covered in a prior paper, which routes DIFFERENT request paths to different target groups, unrelated to graceful deregistration) — connection draining is a real, standard, and directly configurable ALB target group setting, not a fixed, abrupt-cutoff-only behavior.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('ae43f33f-97c6-4865-8d04-5b0fb56690c5', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 11, 'A company uses S3 Cross-Region Replication (covered generally in prior papers) and later DELETES an object in the SOURCE bucket. By default, does that deletion (specifically, the resulting delete marker S3 creates when versioning is enabled) get replicated to the DESTINATION bucket as well, and why does this specific behavior matter for a company relying on CRR for disaster recovery or compliance purposes?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cd44d577-e386-4282-a377-546866fb9a0f', 'ae43f33f-97c6-4865-8d04-5b0fb56690c5', 0, 'By DEFAULT, delete markers are NOT replicated to the destination bucket — meaning deleting an object in the source bucket does NOT automatically delete (or mark as deleted) the corresponding replicated copy in the destination, which is exactly why CRR is genuinely useful as a protective backup layer against an accidental (or malicious) deletion in the source bucket, since the destination copy remains intact and unaffected by default; this default CAN be explicitly changed via a specific replication configuration option if a company genuinely wants delete markers to also replicate, but that is not the out-of-the-box behavior.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('71ac4c0d-3e9e-4ea4-b626-a98cad93fe07', 'ae43f33f-97c6-4865-8d04-5b0fb56690c5', 1, 'Delete markers are always automatically replicated to the destination bucket by default, with no way to configure or change this behavior under any circumstance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('15ad8de0-a517-44da-8d57-ccddf5def5e7', 'ae43f33f-97c6-4865-8d04-5b0fb56690c5', 2, 'Deleting an object in the source bucket always immediately and permanently deletes the corresponding object in the destination bucket, bypassing S3 Versioning entirely.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5676bfca-115e-46ea-8557-c715606f0d3e', 'ae43f33f-97c6-4865-8d04-5b0fb56690c5', 3, 'S3 Cross-Region Replication has no relationship to or interaction with delete operations or delete markers of any kind; deletions in the source bucket are entirely irrelevant to CRR.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('ae43f33f-97c6-4865-8d04-5b0fb56690c5', 'cd44d577-e386-4282-a377-546866fb9a0f', 'This is a genuinely important, directly testable CRR behavior nuance building on the general S3 Versioning + CRR concept (covered generally in prior papers) — by DEFAULT, S3 does NOT replicate delete markers to the destination bucket, meaning a deletion (or an accidental/malicious deletion, connecting to insider threat concepts covered generally in Security+ content) performed in the source bucket does not automatically propagate to remove or mark-as-deleted the corresponding object in the destination bucket, leaving that destination copy genuinely intact and recoverable — this default behavior is EXACTLY what makes CRR meaningfully useful as a protective layer specifically against accidental or malicious source-bucket deletions, since an attacker or a mistaken administrator who deletes data in the source bucket cannot, by that action alone, also silently wipe out the protected destination copy. This default CAN be explicitly overridden via a specific replication rule configuration if an organization genuinely WANTS delete markers to also replicate (for a use case where mirroring deletions is actually the desired behavior), but that requires deliberate configuration — it is not S3''s out-of-the-box default. This is a real, standard, and genuinely important operational nuance for anyone relying on CRR specifically for its data-protection value, not an arbitrary or non-existent distinction.');

-- ── Domain: High-Performing Architectures (24% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('00dbca58-35d3-433b-aee9-7387ccb0971c', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 12, 'A DynamoDB table stores orders with a partition key of `CustomerId`, but the application also frequently needs to efficiently query orders by `OrderDate` alone, across ALL customers — a query pattern the table''s primary key structure doesn''t directly support without an inefficient full table scan. What DynamoDB feature lets the table support this additional, different query pattern efficiently, without restructuring the primary key or duplicating the entire table?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('80b87052-6329-4ec8-be4f-f2dbba111edf', '00dbca58-35d3-433b-aee9-7387ccb0971c', 0, 'A Global Secondary Index (GSI) — creates an alternate query path into the same DynamoDB table, with its OWN different partition key (and optionally a different sort key) from the base table''s primary key, allowing efficient queries against that different access pattern (here, querying by `OrderDate` across all customers) without needing a full table scan or a separately duplicated, manually-synchronized table; a GSI is queried independently of the base table''s partition key, distinct from a Local Secondary Index (LSI), which must share the base table''s SAME partition key and can only vary the sort key, and — unlike a GSI, which can be added at any time — an LSI must be defined when the table is first created.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f083101e-7c0f-4745-b27d-6ce11380ea16', '00dbca58-35d3-433b-aee9-7387ccb0971c', 1, 'DynamoDB Accelerator (DAX), since DAX''s core function is creating an alternate query path with a different partition key into the same DynamoDB table.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('27b65821-1560-43f4-a510-6603b82630c8', '00dbca58-35d3-433b-aee9-7387ccb0971c', 2, 'DynamoDB adaptive capacity, since adaptive capacity is specifically defined as creating an alternate query path allowing efficient queries against a different partition key than the base table''s primary key.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3425c1de-cace-4a2b-9803-7a5a632bbcb2', '00dbca58-35d3-433b-aee9-7387ccb0971c', 3, 'DynamoDB tables can only ever be queried using their original, fixed primary key structure; supporting an additional, different query pattern always requires creating an entirely separate, independently-managed table.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('00dbca58-35d3-433b-aee9-7387ccb0971c', '80b87052-6329-4ec8-be4f-f2dbba111edf', 'A Global Secondary Index directly addresses this "I need an efficient, different query pattern beyond what my table''s primary key naturally supports" need, without resorting to an inefficient full table SCAN (which reads every item, not a targeted, efficient QUERY) or manually maintaining an entirely separate, independently-synchronized duplicate table. A GSI has its OWN partition key (and optional sort key), genuinely independent of the base table''s primary key structure, enabling efficient queries against that alternate access pattern (here, `OrderDate` as the GSI''s partition key, letting the application efficiently query orders by date across every customer). This is genuinely distinct from a Local Secondary Index, which must share the SAME partition key as the base table and can only offer an alternate SORT key — a narrower, more constrained alternative — and critically, an LSI must be defined at table CREATION time, while a GSI can be added to an existing table at any point after creation, a real, practical, and directly testable distinction. This is entirely separate from DAX (covered generally in a prior paper, a READ-caching layer, not an alternate query-path mechanism) and adaptive capacity (covered generally in a prior paper, which redistributes THROUGHPUT for uneven hot-partition traffic, not a distinct query-pattern-enabling index) — GSIs/LSIs are real, standard, and foundational DynamoDB capabilities specifically for this exact need.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('08bff06e-a7bc-4a5c-af2c-8c18188ba35e', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 13, 'An application connects to an Aurora cluster''s multiple READ replicas, but rather than the application needing to individually track which specific replica instances currently exist (since replicas can be added or removed, including via Aurora Auto Scaling covered generally in a prior paper) and manually load-balance queries across them itself, the team wants Aurora to provide ONE single, stable endpoint that automatically distributes read traffic across whatever replicas currently exist at any given moment. What Aurora feature provides this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8446414a-c1c4-4481-b1a4-09525e345e0e', '08bff06e-a7bc-4a5c-af2c-8c18188ba35e', 0, 'The Aurora reader endpoint — a single, stable DNS endpoint that automatically load-balances read queries across ALL of a cluster''s CURRENT Aurora Replicas, without the connecting application needing to individually track which specific replica instances exist at any given moment or implement its own client-side load-balancing logic; as replicas are added or removed (including automatically via Aurora Auto Scaling for read replicas, covered generally in a prior paper), the reader endpoint automatically reflects that current, correct set of replicas with no application-side reconfiguration required at all.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a4bf2cea-0337-4364-9b76-4f9b8e6f284d', '08bff06e-a7bc-4a5c-af2c-8c18188ba35e', 1, 'The Aurora writer endpoint, since the writer endpoint is specifically defined as automatically load-balancing read queries across every current read replica in a cluster.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b82ec8c6-0bd5-4137-82b3-fe177b6c230c', '08bff06e-a7bc-4a5c-af2c-8c18188ba35e', 2, 'Aurora Parallel Query, since Parallel Query''s core function is providing a single, stable endpoint that automatically load-balances read traffic across a cluster''s current replicas.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('742f240d-0736-401f-9e33-738feda5609c', '08bff06e-a7bc-4a5c-af2c-8c18188ba35e', 3, 'Aurora provides no mechanism for automatically load-balancing read queries across multiple replicas; an application must always manually track and individually connect to each specific replica instance itself.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('08bff06e-a7bc-4a5c-af2c-8c18188ba35e', '8446414a-c1c4-4481-b1a4-09525e345e0e', 'The Aurora reader endpoint specifically solves the "don''t make the application track individual replica instances" problem directly relevant to Aurora Auto Scaling for read replicas (covered generally in a prior paper, where the actual NUMBER of replicas genuinely changes dynamically based on load) — rather than an application needing its own logic to discover currently-existing replica instances and distribute queries across them itself (a genuinely fragile approach as replicas are added or removed), Aurora provides the reader endpoint as one single, stable DNS name the application simply connects to for read queries, with Aurora itself handling the actual load distribution across whichever replicas currently exist at any moment, transparently absorbing replica count changes with zero application-side reconfiguration ever needed. This is genuinely distinct from the Aurora WRITER endpoint (which always points specifically to the current PRIMARY, writable instance, an entirely different, single-target purpose from the reader endpoint''s multi-replica load-balancing) and from Aurora Parallel Query (covered in a prior paper, which speeds up a SINGLE large analytical query via storage-layer parallelization, a different mechanism entirely from endpoint-level connection routing across multiple replica instances) — this is a real, standard, and foundational Aurora capability specifically simplifying read-scaling architecture, not a manual-tracking-only requirement.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('0c60da07-67c8-42ef-8af3-349385f96c81', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 14, 'A company configuring Auto Scaling wants the ASG to automatically maintain average CPU utilization at approximately 60% across the group by adding or removing instances as needed — simply specifying the TARGET metric value and letting AWS handle the actual scaling math, rather than the team needing to manually define specific scaling thresholds and exact instance-count adjustments for each situation themselves. What ASG scaling policy TYPE is specifically designed for this simpler, target-value-based approach?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0a874c0f-1657-47e8-98c7-1f07a3a94515', '0c60da07-67c8-42ef-8af3-349385f96c81', 0, 'A target tracking scaling policy — the ASG administrator simply specifies a TARGET value for a chosen metric (here, 60% average CPU utilization), and AWS automatically calculates and applies the actual scaling adjustments needed to maintain that target, adding or removing instances as needed, without the administrator needing to manually define specific numeric thresholds or exact instance-count changes themselves; this is distinct from a step scaling policy (defining specific, tiered scaling ADJUSTMENTS at different metric threshold breakpoints, giving more granular manual control) and a simple scaling policy (the most basic type, applying one single scaling adjustment per alarm with a mandatory cooldown period before another adjustment can occur).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('834a3d89-e782-4a07-a317-46efd38c4c2e', '0c60da07-67c8-42ef-8af3-349385f96c81', 1, 'A step scaling policy, since step scaling is specifically defined as automatically calculating scaling adjustments from a single target metric value with no manually-defined thresholds required.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('02047444-95a1-431e-8b02-1e768993f9ca', '0c60da07-67c8-42ef-8af3-349385f96c81', 2, 'ASG predictive scaling, since predictive scaling is specifically defined as maintaining a target metric value by automatically calculating scaling adjustments with no forecasting involved.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('be05a413-d26b-4936-8457-63d48c098335', '0c60da07-67c8-42ef-8af3-349385f96c81', 3, 'Auto Scaling Groups only support one single, undifferentiated scaling policy type, with no distinction between target-value-based, threshold-based, or other configurable scaling approaches.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('0c60da07-67c8-42ef-8af3-349385f96c81', '0a874c0f-1657-47e8-98c7-1f07a3a94515', 'Target tracking is specifically the SIMPLEST, most automated of the three real, distinct ASG scaling policy types precisely because it only requires specifying a DESIRED TARGET VALUE for a chosen metric, with AWS itself handling all the underlying math to figure out exactly how many instances to add or remove to actually maintain that target as real conditions change — directly analogous in spirit to Aurora Auto Scaling for read replicas (covered generally in a prior paper), but applied here to general EC2 Auto Scaling Group capacity. Step scaling, by contrast, requires the administrator to manually define specific, tiered scaling ADJUSTMENTS triggered at different metric threshold breakpoints (e.g., "add 2 instances if CPU exceeds 70%, add 4 more if it exceeds 90%") — genuinely more granular, hands-on control, but requiring the administrator to design those specific thresholds and adjustments themselves rather than simply stating a target. Simple scaling is the most basic, oldest type, applying a single scaling adjustment per triggered alarm with a mandatory cooldown period before another adjustment can occur, offering the least sophistication of the three. This is a real, genuinely distinct set of configurable options ASGs actually support, not a single undifferentiated scaling mechanism — and target tracking is meaningfully different from ASG predictive scaling (covered next in this paper, which specifically uses FORECASTING to scale ahead of anticipated demand, a different mechanism from target tracking''s reactive, current-metric-based approach).');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('cd96bd2a-8042-4d6b-8973-3ee59c9b5b1e', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 15, 'A company''s Auto Scaling Group handles a genuinely predictable daily traffic pattern (a sharp spike every weekday morning at 9 AM as users log in), but reactive scaling (waiting for CPU or another metric to actually cross a threshold, as in target tracking) means new instances only start launching AFTER the spike has already begun, causing a real, brief period of degraded performance each morning while capacity catches up. What ASG feature can use historical traffic patterns to FORECAST this kind of predictable spike and proactively scale out BEFORE it actually begins?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bd77f4f8-8b87-4eb6-a0b3-d0cc83e6d145', 'cd96bd2a-8042-4d6b-8973-3ee59c9b5b1e', 0, 'ASG Predictive Scaling — analyzes historical load patterns (using machine learning to identify genuinely recurring, predictable patterns, like a consistent daily 9 AM traffic spike) and proactively schedules capacity to be available BEFORE the forecasted spike actually begins, directly addressing the real lag inherent in purely REACTIVE scaling policies like target tracking (covered earlier this paper, which can only respond AFTER a metric has already crossed its threshold) — genuinely distinct from Scheduled Scaling (covered generally in a prior paper, which requires an administrator to manually define specific scaling actions at specific times) since predictive scaling automatically LEARNS the recurring pattern from actual historical data rather than requiring it to be manually pre-defined.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cf179cd7-871a-4361-a2f1-3ee14b7db188', 'cd96bd2a-8042-4d6b-8973-3ee59c9b5b1e', 1, 'A target tracking scaling policy, since target tracking is specifically defined as using machine learning to forecast historical traffic patterns and proactively scale out before a predicted spike begins.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4bdb6852-3d45-4a52-9849-4756ded6b38b', 'cd96bd2a-8042-4d6b-8973-3ee59c9b5b1e', 2, 'ASG Warm Pools, since Warm Pools are specifically defined as using machine learning to analyze historical traffic patterns and forecast future demand spikes.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('faeb9e1c-b882-43cc-babe-5e35ffea19e2', 'cd96bd2a-8042-4d6b-8973-3ee59c9b5b1e', 3, 'Auto Scaling can never proactively scale out ahead of an anticipated demand spike; every scaling action must always be purely reactive, occurring only after a metric has already crossed a defined threshold.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('cd96bd2a-8042-4d6b-8973-3ee59c9b5b1e', 'bd77f4f8-8b87-4eb6-a0b3-d0cc83e6d145', 'Predictive Scaling directly addresses the inherent LAG in purely reactive scaling approaches like target tracking (covered earlier this paper) — target tracking, by design, can only respond AFTER its chosen metric has already crossed the relevant threshold, meaning for a genuinely sharp, fast-rising spike, real users experience degraded performance during the real-world delay between the spike beginning and new capacity actually becoming available and warmed up. Predictive Scaling instead uses machine learning to analyze an application''s actual HISTORICAL load data, specifically identifying genuinely recurring, forecastable patterns (like a consistent weekday 9 AM spike), and proactively schedules the needed capacity to already be available BEFORE the forecasted spike actually begins, directly closing that reactive-scaling lag for predictable patterns. This is genuinely distinct from Scheduled Scaling (covered generally in a prior paper), which requires an ADMINISTRATOR to manually define specific scaling actions at specific pre-determined times — Predictive Scaling instead automatically LEARNS the pattern from real historical data itself, without requiring that manual, explicit schedule definition, and can adapt if the underlying pattern gradually shifts over time. This directly complements ASG Warm Pools (covered generally in a prior paper, which keeps pre-initialized instances ready for FASTER activation once a scaling decision is triggered, a related but genuinely distinct concept from Predictive Scaling''s forecasting-based EARLY TRIGGERING of that scaling decision in the first place) — Auto Scaling genuinely does support this proactive, forecast-based capability, not purely reactive scaling only.');

-- ── Domain: Cost-Optimized Architectures (20% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('50f81b3d-4b85-45f1-b13f-900cf9f1fceb', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 16, 'A company running a genuinely steady-state RDS database workload for the next 3 years wants to commit to Reserved Instance pricing for meaningful savings over On-Demand rates, the same way they might for EC2 (covered generally in a prior paper). Does RDS support its own Reserved Instance product, and how does it compare conceptually to EC2 RIs?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6ce33bad-9292-4e88-be43-6b2aeec7d18c', '50f81b3d-4b85-45f1-b13f-900cf9f1fceb', 0, 'Yes — RDS has its OWN, separate Reserved Instance product (genuinely distinct from EC2 RIs, since RDS RIs specifically apply to RDS DATABASE instance usage, not general-purpose EC2 compute), offering meaningful discounts (typically comparable in structure to EC2 RIs — a 1- or 3-year commitment in exchange for a lower effective hourly rate than On-Demand) for a genuinely steady-state, predictable database workload, and following the same general commitment-for-discount trade-off philosophy as EC2 RIs, just applied to the RDS-specific database engine/instance-class/Region combination being reserved rather than to general EC2 compute.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c4d8d54b-f438-421d-b6e3-525de2f7566c', '50f81b3d-4b85-45f1-b13f-900cf9f1fceb', 1, 'No — RDS has no Reserved Instance product of its own; only EC2 supports Reserved Instance pricing, and RDS database workloads can never receive any form of commitment-based discount.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a1132e98-d4a3-4797-9b99-6ba514feae74', '50f81b3d-4b85-45f1-b13f-900cf9f1fceb', 2, 'An EC2 Reserved Instance purchased for a specific EC2 instance type automatically and directly extends the exact same discount to any RDS database instance the company also runs, with no separate RDS-specific RI product needed.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('05a31f13-a08b-4cc8-ad00-d069bc1eacd2', '50f81b3d-4b85-45f1-b13f-900cf9f1fceb', 3, 'RDS Reserved Instances provide capacity reservation benefits identical to On-Demand Capacity Reservations but offer no billing discount of any kind compared to standard On-Demand RDS pricing.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('50f81b3d-4b85-45f1-b13f-900cf9f1fceb', '6ce33bad-9292-4e88-be43-6b2aeec7d18c', 'RDS genuinely has its own, SEPARATE Reserved Instance product — conceptually parallel to EC2 RIs (covered generally in prior papers, including the Standard-vs-Convertible flexibility/discount trade-off) in that it follows the same underlying philosophy of committing to a 1- or 3-year term in exchange for a meaningfully lower effective hourly rate than On-Demand pricing for a genuinely steady-state, predictable workload — but it is a genuinely DISTINCT product specifically scoped to RDS database instance usage (tied to a specific database engine, instance class, and Region/deployment configuration), not something automatically inherited from or shared with an EC2 RI purchased for general-purpose compute, since RDS and EC2 are fundamentally different services with entirely separate billing dimensions despite both running on similar underlying EC2 instance-class hardware. This directly extends the broader theme of understanding which AWS COMMITMENT/discount products apply to which specific service — EC2 RIs and Savings Plans (covered generally in prior papers) for EC2 compute specifically, and RDS''s own separate RI product for database workloads specifically — rather than assuming a single, universal reservation mechanism automatically covers every AWS service a company happens to use. RDS RIs genuinely DO provide a real billing discount versus On-Demand, distinct in purpose from On-Demand Capacity Reservations (covered generally in a prior paper, which specifically guarantee EC2 capacity availability WITHOUT any billing discount of their own).');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('bf6dfd8e-0190-423d-aac0-19a8a58f25d1', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 17, 'A company uses S3 Intelligent-Tiering (covered generally in a prior paper) for a dataset with genuinely unpredictable access patterns, and wants Intelligent-Tiering to ALSO automatically move genuinely long-unaccessed objects into even deeper, cheaper archival tiers (comparable to Glacier Flexible Retrieval and Glacier Deep Archive, both covered generally in a prior paper) — not just the standard frequent/infrequent-access tiers Intelligent-Tiering moves objects between by default. Does Intelligent-Tiering support this deeper archival behavior?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e1335b3a-b9c0-40a0-8b76-eb64379835d0', 'bf6dfd8e-0190-423d-aac0-19a8a58f25d1', 0, 'Yes — S3 Intelligent-Tiering supports OPTIONAL, explicitly OPT-IN Archive Access and Deep Archive Access tiers, which, once enabled on the Intelligent-Tiering configuration, will automatically move objects that have genuinely gone unaccessed for a longer, configurable period into those much cheaper archival tiers (with correspondingly longer retrieval times, comparable in spirit to standalone Glacier and Glacier Deep Archive) — entirely automatically, based on actual observed access patterns, with no separate manual lifecycle rule needing to be written specifically for that archival transition, extending Intelligent-Tiering''s core "automatically move objects based on real access patterns" behavior all the way down to the deepest, cheapest archival tiers.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('94971804-6436-44e2-a7d2-d6bb20adf415', 'bf6dfd8e-0190-423d-aac0-19a8a58f25d1', 1, 'No — S3 Intelligent-Tiering can only ever move objects between its default frequent and infrequent access tiers, with absolutely no ability to reach deeper, Glacier-comparable archival tiers under any configuration.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3b6d396e-b2b2-47fa-a8d0-1fc42594c5a0', 'bf6dfd8e-0190-423d-aac0-19a8a58f25d1', 2, 'Reaching deeper archival tiers from Intelligent-Tiering always requires a completely separate, manually-written S3 Lifecycle rule; Intelligent-Tiering itself has no native, built-in mechanism for archival-tier transitions of any kind.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8d0c5b05-743a-46b4-b2d9-1b2d3370a344', 'bf6dfd8e-0190-423d-aac0-19a8a58f25d1', 3, 'S3 Intelligent-Tiering''s Archive Access and Deep Archive Access tiers are enabled automatically and mandatorily for every object by default, with no way for an administrator to opt in or out of this behavior.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('bf6dfd8e-0190-423d-aac0-19a8a58f25d1', 'e1335b3a-b9c0-40a0-8b76-eb64379835d0', 'S3 Intelligent-Tiering''s Archive Access and Deep Archive Access tiers genuinely extend its core, general behavior (covered generally in a prior paper — automatically monitoring real access patterns and moving objects between cost tiers with no manual lifecycle rule required for the STANDARD frequent/infrequent tiers) all the way down to archival-depth cost savings comparable to standalone Glacier Flexible Retrieval and Glacier Deep Archive (both covered generally in a prior paper, including Deep Archive''s specific retrieval-time trade-off) — but these deeper archival tiers are specifically OPT-IN, not automatically applied to every object by default, since moving into genuinely deep archival storage carries real retrieval-time trade-offs (comparable to standalone Glacier''s own retrieval delays) that not every workload''s access pattern would find acceptable, so Intelligent-Tiering deliberately requires an administrator to explicitly enable this behavior for objects that genuinely warrant it. Once enabled, however, the transition into those deeper archival tiers happens automatically based on real, OBSERVED access patterns (an object genuinely going unaccessed for the configured, longer duration), continuing Intelligent-Tiering''s core "let AWS handle the tier movement automatically" value proposition rather than requiring a completely separate, manually-authored Lifecycle rule specifically for archival transitions. This is a real, standard, and genuinely useful Intelligent-Tiering capability, not a permanent ceiling limited to only the default frequent/infrequent tiers.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('aaab4bda-d66a-43e4-a7bd-a0154daeeadb', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 18, 'A company purchased several 1-year Reserved Instances and Savings Plans roughly a year ago, and a finance team member asks whether anyone is actively tracking WHEN each of those specific commitments is due to expire. No one has a clear answer, and the team realizes that if a commitment silently expires with no one noticing, that previously-discounted usage would simply revert to full On-Demand pricing going forward, with no automatic renewal and no alert of any kind. What practical operational gap does this scenario illustrate, and how should it be addressed?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('49ca4050-4492-4c87-9516-5107d611f886', 'aaab4bda-d66a-43e4-a7bd-a0154daeeadb', 0, 'Reserved Instances and Savings Plans do NOT automatically renew when their term expires, and AWS does not automatically alert an organization when a commitment is approaching expiration — meaning ongoing, deliberate MONITORING of commitment expiration dates (via a tracked spreadsheet, a scheduled reminder process, or ideally an automated check against the AWS Cost Explorer RI/Savings Plans inventory) is a genuinely necessary, real operational practice to avoid the real cost impact of previously-discounted usage silently reverting to full On-Demand pricing with nobody noticing until an unexpectedly higher bill arrives.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f0676dd3-8964-42e1-b0bc-1b8199812854', 'aaab4bda-d66a-43e4-a7bd-a0154daeeadb', 1, 'Reserved Instances and Savings Plans always automatically renew for an identical new term the moment the prior term expires, with no possibility of silently reverting to On-Demand pricing under any circumstance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('533c7752-79d9-4ff0-88b6-6bc9cfdfa0a2', 'aaab4bda-d66a-43e4-a7bd-a0154daeeadb', 2, 'AWS Cost Anomaly Detection, since Cost Anomaly Detection is specifically defined as automatically renewing an expiring Reserved Instance or Savings Plan commitment with no manual monitoring or renewal action required.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('40b6beaf-2768-4190-9907-e9f354fb45bb', 'aaab4bda-d66a-43e4-a7bd-a0154daeeadb', 3, 'Once a Reserved Instance or Savings Plan commitment expires, the underlying EC2 usage it was covering must always be immediately and automatically terminated, rather than simply continuing to run at standard On-Demand pricing.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('aaab4bda-d66a-43e4-a7bd-a0154daeeadb', '49ca4050-4492-4c87-9516-5107d611f886', 'This is a genuinely real, practical, and commonly overlooked operational gap directly relevant to the broader RI/Savings Plans commitment concepts covered generally throughout prior papers — neither RIs nor Savings Plans automatically renew when their term (1 or 3 years) expires, and AWS does not proactively alert an organization that a specific commitment is approaching its expiration date; the underlying EC2 (or RDS, connecting to RDS RIs covered earlier this paper) usage that commitment was covering simply continues running normally, but WITHOUT the discount, silently reverting to full On-Demand pricing — a real, meaningful, and entirely avoidable cost increase that''s genuinely easy to miss until an unexpectedly higher bill eventually surfaces the issue well after the fact. This is exactly why deliberate, ongoing tracking of commitment expiration dates — whether via a manually maintained tracking process or, more robustly, an automated check against Cost Explorer''s RI/Savings Plans utilization and inventory data — is a real, standard, and genuinely necessary operational discipline for any organization actually relying on these commitment-based discounts at meaningful scale, directly complementary to (but a distinct concern from) Cost Anomaly Detection (covered generally in a prior paper, which flags unusual SPENDING PATTERNS generally, not specifically commitment expiration dates) or Budgets Actions (covered generally in a prior paper, threshold-based alerting, also not specifically expiration-date tracking).');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('9a30c5a2-aaaa-4ccd-bf12-5a6e88c441e6', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 19, 'Before finalizing a new architecture design, a solutions architect runs it through a structured AWS review process examining the design against six defined pillars — including Cost Optimization specifically — using a standard set of guiding questions to systematically identify where the design could reduce unnecessary spend without compromising its other requirements (reliability, security, performance). What is this structured AWS review process called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('816b4881-ca7e-47f6-9caa-d8cdcd09c50b', '9a30c5a2-aaaa-4ccd-bf12-5a6e88c441e6', 0, 'A Well-Architected Framework review (often performed using the AWS Well-Architected Tool) — a structured, standardized review process evaluating an architecture against six defined pillars (including Cost Optimization, alongside Operational Excellence, Security, Reliability, Performance Efficiency, and Sustainability), using AWS''s own standard set of guiding questions and best practices for each pillar to systematically surface concrete, actionable improvement opportunities — for the Cost Optimization pillar specifically, this connects directly to essentially every cost-related concept covered across this project''s AWS SAA content (right-sizing, Reserved Instances/Savings Plans, S3 storage class selection, and more), providing a structured framework for periodically and systematically revisiting those decisions rather than evaluating them only once, ad hoc, at initial design time.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1dc83701-ceb6-4577-b056-638dfd64e391', '9a30c5a2-aaaa-4ccd-bf12-5a6e88c441e6', 1, 'AWS Trusted Advisor, since Trusted Advisor is specifically defined as the structured, six-pillar architectural review process examining a design against Cost Optimization alongside five other defined pillars.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3e49a78b-dbd0-487d-87c3-b0d1d4182991', '9a30c5a2-aaaa-4ccd-bf12-5a6e88c441e6', 2, 'AWS Config, since Config''s core function is running a structured, six-pillar architectural review examining a design specifically against Cost Optimization and five other defined pillars.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1ec30c7f-b2af-42ab-a960-532a6d7c142f', '9a30c5a2-aaaa-4ccd-bf12-5a6e88c441e6', 3, 'AWS provides no structured, standardized framework or process for systematically reviewing an architecture''s cost-optimization opportunities; every cost evaluation must always be performed in a fully ad hoc, unstructured manner.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('9a30c5a2-aaaa-4ccd-bf12-5a6e88c441e6', '816b4881-ca7e-47f6-9caa-d8cdcd09c50b', 'The Well-Architected Framework provides the OVERARCHING, structured review methodology that essentially every individual cost-optimization concept covered across this project''s AWS SAA content (S3 storage class selection, right-sizing via Compute Optimizer, RI/Savings Plans commitment strategy, and many others) ultimately feeds into and supports — rather than being yet another individual cost-saving TECHNIQUE itself, the Well-Architected Framework (accessible via the free AWS Well-Architected Tool) is the structured PROCESS for systematically evaluating a given architecture against a standard set of guiding questions across six defined pillars: Cost Optimization specifically, alongside Operational Excellence, Security, Reliability, Performance Efficiency, and Sustainability — surfacing concrete, actionable findings a team can then act on, and importantly, designed to be revisited PERIODICALLY as an architecture evolves over time, not just performed once at initial design and then forgotten. This is genuinely distinct from Trusted Advisor (covered generally in a prior paper, which provides more specific, automated, individually-actionable checks and recommendations across cost/security/performance categories) and AWS Config (covered generally in a prior paper, which tracks resource configuration state/drift) — the Well-Architected Framework is a real, standard, and genuinely foundational AWS methodology specifically for this kind of structured, multi-dimensional (including cost) architectural review, not an absence of any formal review process.');

-- ── Domain: High-Performing Architectures (additional — question 20) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('ab6ec2ef-623f-421e-a0cf-de3d6a52dfb5', 'bb1f1fb6-cfbe-4c8c-8d5a-031ce78025cb', 20, 'An Application Load Balancer distributes requests across a target group of stateful web servers, where each server maintains SESSION-specific data locally (like a shopping cart or a login session) that is NOT shared across the other servers. Without any special configuration, a user''s consecutive requests could land on a DIFFERENT server each time, losing access to their session data. What ALB feature ensures a given user''s requests are consistently routed to the SAME target instance for the duration of their session?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('146aa760-198d-47ac-a790-cd8bfb1c591f', 'ab6ec2ef-623f-421e-a0cf-de3d6a52dfb5', 0, 'ALB sticky sessions (session affinity) — using a load-balancer-generated cookie, the ALB binds a specific user''s session to one particular target instance, ensuring that user''s subsequent requests are consistently routed to that SAME instance for the duration of the cookie''s validity, rather than being distributed across the target group as if each request were independent; this directly accommodates STATEFUL applications keeping session data locally on each instance, though the standard, generally more scalable and resilient architectural alternative is to externalize session state entirely (e.g., into ElastiCache, covered generally in a prior paper, or DynamoDB) so that ANY instance can serve ANY request without needing sticky sessions at all.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('10af71d8-f829-4a69-971e-5b3af9c31b6b', 'ab6ec2ef-623f-421e-a0cf-de3d6a52dfb5', 1, 'ALB connection draining, since connection draining is specifically defined as consistently routing a given user''s requests to the same target instance for the duration of their session.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7eca36cf-693c-4f58-a598-5b9f2e3ddcb1', 'ab6ec2ef-623f-421e-a0cf-de3d6a52dfb5', 2, 'ALB path-based routing, since path-based routing is specifically defined as binding a user''s session to one particular target instance using a load-balancer-generated cookie.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('69c0c373-41af-43bf-a6c4-1daffd706d72', 'ab6ec2ef-623f-421e-a0cf-de3d6a52dfb5', 3, 'An Application Load Balancer has no mechanism to consistently route a given user''s requests to the same target instance; every request is always distributed independently with no session-affinity option available.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('ab6ec2ef-623f-421e-a0cf-de3d6a52dfb5', '146aa760-198d-47ac-a790-cd8bfb1c591f', 'Sticky sessions directly address the real problem stateful, session-data-on-the-instance applications face with a standard load balancer''s default behavior of treating every request independently — without sticky sessions enabled, a user''s second request could land on a completely different target instance than their first, one that has no knowledge of session data (like a shopping cart) stored only on the ORIGINAL instance that handled their earlier request. Enabling sticky sessions has the ALB issue a cookie identifying which specific target instance a given user''s session is bound to, and route all of that user''s subsequent requests to that SAME instance for as long as the cookie remains valid, directly solving the immediate problem. This is genuinely distinct from connection draining/deregistration delay (covered earlier this paper, which governs graceful instance REMOVAL, not ongoing session-to-instance binding) and path-based routing (covered generally in a prior paper, which routes different URL PATHS to different target groups, an entirely different routing concern from session affinity within a single target group). It''s worth noting the more architecturally scalable and resilient long-term pattern is often to avoid needing sticky sessions altogether by externalizing session state into a shared, external store like ElastiCache (covered generally in a prior paper) or DynamoDB, so that genuinely ANY instance can serve ANY request statelessly — but sticky sessions remain a real, standard, directly-available ALB feature for applications that do keep session state locally, not a capability ALBs lack.');
