-- ============================================================
-- AWS Solutions Architect Associate (SAA-C03) — Seed Data: Paper 1
-- New content, no pre-existing answer key. Domain weighting matches the
-- real SAA-C03 exam blueprint from certDetail["aws-saa"] (app/certifications/
-- [id]/page.tsx): Design Secure Architectures 30% (6 of 20), Design
-- Resilient Architectures 26% (5 of 20), Design High-Performing
-- Architectures 24% (5 of 20), Design Cost-Optimized Architectures 20%
-- (4 of 20). Every question checked against documented, stable AWS service
-- behavior — not recently-changed pricing specifics or console UI details
-- that would date quickly; scenario mechanics (IAM evaluation logic,
-- Multi-AZ failover behavior, storage class access-pattern trade-offs)
-- rather than exact current prices.
-- Run this AFTER docs/question-bank-schema.sql.
-- ============================================================

-- ---------- Paper 1 ----------
INSERT INTO question_papers (id, slug, title, exam_type, focus_tags, question_count, difficulty, is_premium, sort_order, time_limit_minutes)
VALUES ('8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 'aws-saa-practice-1', 'AWS SAA-C03 Practice Paper 1', 'aws-saa', ARRAY['IAM', 'VPC', 'S3', 'RDS', 'EC2', 'Auto Scaling', 'ELB', 'CloudFront', 'Cost Optimization']::TEXT[], 20, 'standard', true, 1, 30);

-- ── Domain: Design Secure Architectures (30% — 6 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('642cbb9c-f1a4-4aee-a766-be61ff8f6a46', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 1, 'An IAM user has an identity-based policy that ALLOWS s3:GetObject on a specific S3 bucket. A separate policy attached to the same user explicitly DENIES s3:GetObject on all S3 resources. What happens when the user attempts to read an object from that bucket?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('61918614-6282-49d1-892d-8b294539ea07', '642cbb9c-f1a4-4aee-a766-be61ff8f6a46', 0, 'The request is allowed, because the more specific Allow policy takes precedence over the broader Deny.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c3f105ab-d858-4796-9338-7cfe495e99a0', '642cbb9c-f1a4-4aee-a766-be61ff8f6a46', 1, 'The request is denied, because an explicit Deny always overrides any Allow in AWS IAM policy evaluation, regardless of specificity.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5c7a98c1-c0ad-4817-89cf-e95e14374a0e', '642cbb9c-f1a4-4aee-a766-be61ff8f6a46', 2, 'AWS evaluates policies in the order they were attached, so whichever policy was attached most recently wins.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5cf8fef8-ea3a-49ef-9ceb-bb253397ddb0', '642cbb9c-f1a4-4aee-a766-be61ff8f6a46', 3, 'The request succeeds only if the bucket policy also explicitly allows it; the user-level Deny does not apply to bucket-scoped actions.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('642cbb9c-f1a4-4aee-a766-be61ff8f6a46', 'c3f105ab-d858-4796-9338-7cfe495e99a0', 'IAM policy evaluation logic is: implicit deny by default, then any explicit Allow grants access, but an explicit Deny anywhere in the evaluated policies (identity-based, resource-based, permissions boundary, SCP, or session policy) always wins over any Allow, no matter how specific the Allow is or which policy is more targeted. This is a foundational, frequently-tested SAA concept — specificity and attachment order never override an explicit Deny.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('3701b31a-2d76-458d-b08b-bb98fa9fd7c9', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 2, 'A solutions architect needs to control inbound and outbound traffic at both the instance level and the subnet level within a VPC. Which statement correctly distinguishes Security Groups from Network ACLs (NACLs)?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d799eaf9-c253-4cfa-b8db-4b010e6c0b3f', '3701b31a-2d76-458d-b08b-bb98fa9fd7c9', 0, 'Security Groups operate at the subnet level and are stateless; NACLs operate at the instance level and are stateful.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('512dc327-4901-4078-bf3f-b1a651200bc0', '3701b31a-2d76-458d-b08b-bb98fa9fd7c9', 1, 'Security Groups operate at the instance level and are stateful (return traffic is automatically allowed); NACLs operate at the subnet level and are stateless (return traffic must be explicitly allowed by a separate rule).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cc0b5484-2058-485e-b787-cefe9148c638', '3701b31a-2d76-458d-b08b-bb98fa9fd7c9', 2, 'Both Security Groups and NACLs are stateful and operate at the instance level; they differ only in that NACLs support explicit Deny rules and Security Groups do not.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a2de4c2b-7496-4c58-97a5-9964b8456013', '3701b31a-2d76-458d-b08b-bb98fa9fd7c9', 3, 'Both Security Groups and NACLs are stateless and operate at the subnet level; NACLs are simply a legacy name for Security Groups in newer AWS accounts.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('3701b31a-2d76-458d-b08b-bb98fa9fd7c9', '512dc327-4901-4078-bf3f-b1a651200bc0', 'Security Groups act as a stateful, instance-level (technically ENI-level) firewall — Security Groups only support Allow rules, and because they are stateful, a response to an allowed inbound request is automatically allowed out without needing a matching outbound rule. NACLs act as a stateless, subnet-level firewall, evaluated in numbered rule order, and support both explicit Allow and explicit Deny rules — because they are stateless, an administrator must configure both the inbound AND the corresponding outbound rule for two-way traffic to work, which is the single most common NACL misconfiguration in practice.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('669fbc81-8c0c-4baf-a476-d82875f22169', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 3, 'A company must encrypt objects in S3 at rest and requires full control over the encryption key''s rotation policy and access permissions, including the ability to audit every use of the key via CloudTrail. Which S3 encryption option should they use?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3bb555e7-5a71-4d22-9fa8-9478e255f164', '669fbc81-8c0c-4baf-a476-d82875f22169', 0, 'SSE-S3 (Amazon S3-managed keys)');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8b508bad-634e-47f9-a335-6c5c494b1fe2', '669fbc81-8c0c-4baf-a476-d82875f22169', 1, 'SSE-KMS (AWS KMS-managed keys, using a customer-managed CMK)');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fe6a231b-b470-4809-bb8b-0e86b9bf3799', '669fbc81-8c0c-4baf-a476-d82875f22169', 2, 'Client-side encryption only, since S3 has no server-side encryption options');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0c77de4d-0345-4cbe-b41e-d9aece569892', '669fbc81-8c0c-4baf-a476-d82875f22169', 3, 'SSE-S3, because it is the only S3 encryption option that logs key usage to CloudTrail');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('669fbc81-8c0c-4baf-a476-d82875f22169', '8b508bad-634e-47f9-a335-6c5c494b1fe2', 'SSE-KMS with a customer-managed CMK is the correct choice specifically because it gives the customer control over the key''s rotation policy and IAM/key-policy-based access permissions, and every use of a KMS key (encrypt, decrypt, re-encrypt) is logged to CloudTrail as a distinct API call — this audit trail is the key differentiator. SSE-S3 uses AWS-owned keys with no customer control over rotation or granular access, and does not provide this level of per-use auditability. SSE-C (server-side encryption with customer-provided keys) is a third real option not listed here, where the customer supplies the key on every request; it was intentionally omitted from these options since it doesn''t match "full control over rotation policy" as cleanly as a KMS customer-managed CMK does.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('bf35b9f6-afe3-49f2-b659-b260fdc8f3a3', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 4, 'An application running on EC2 instances in a private subnet needs to read and write objects in S3 without traversing the public internet, and without requiring a NAT Gateway. What is the correct solution?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ea7e3ac0-212c-4e57-a78d-a21bb41a63b6', 'bf35b9f6-afe3-49f2-b659-b260fdc8f3a3', 0, 'Attach an Internet Gateway to the private subnet''s route table so instances can reach S3''s public endpoint directly.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4f57ea09-ff0f-46c6-b9e7-72c1190099b6', 'bf35b9f6-afe3-49f2-b659-b260fdc8f3a3', 1, 'Create a Gateway VPC Endpoint for S3 and add a route to it in the private subnet''s route table.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ad1c50a5-ade1-4aaa-a27d-661c5130e09c', 'bf35b9f6-afe3-49f2-b659-b260fdc8f3a3', 2, 'Deploy a NAT Instance instead of a NAT Gateway, since NAT Instances can reach S3 without traversing the internet.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bcf2cec5-3d8f-4d3a-8708-2406aa71409a', 'bf35b9f6-afe3-49f2-b659-b260fdc8f3a3', 3, 'This is not possible — any access to S3 from a VPC must traverse the public internet, since S3 has no VPC-native connectivity option.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('bf35b9f6-afe3-49f2-b659-b260fdc8f3a3', '4f57ea09-ff0f-46c6-b9e7-72c1190099b6', 'A Gateway VPC Endpoint (one of two VPC endpoint types, alongside Interface endpoints) provides private connectivity specifically to S3 and DynamoDB by adding a route in the route table that directs traffic to the endpoint instead of over the internet — no NAT Gateway, NAT Instance, or Internet Gateway is required, and there is no data-transfer or per-hour endpoint charge for Gateway endpoints (unlike Interface endpoints, which use PrivateLink and do carry an hourly + data charge). This is a common SAA cost-optimization-meets-security scenario: it''s both more secure (no internet exposure) and cheaper (no NAT Gateway data-processing charges for this traffic) than the alternatives.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('c45a2a87-8ba4-4ad0-8af4-e42b6d90fec2', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 5, 'An application on an EC2 instance needs to call the S3 and DynamoDB APIs. What is the AWS-recommended way to grant this access, and why?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1cd7a8da-be47-4cb0-865f-4f6ac15426d4', 'c45a2a87-8ba4-4ad0-8af4-e42b6d90fec2', 0, 'Create an IAM user, generate a long-term access key/secret pair, and store the credentials in a configuration file on the instance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('22b3bb4a-1534-48f8-99c0-974abeb7e906', 'c45a2a87-8ba4-4ad0-8af4-e42b6d90fec2', 1, 'Attach an IAM role to the EC2 instance; the instance retrieves temporary credentials automatically via the instance metadata service, with no long-term secrets stored on the instance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fe8a9e26-d1f9-4818-aaf8-af19311dfc7d', 'c45a2a87-8ba4-4ad0-8af4-e42b6d90fec2', 2, 'Embed the AWS root account credentials directly in the application code for the simplest setup.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('399ccf5c-1bd5-493e-8706-77ffbc6d7b4a', 'c45a2a87-8ba4-4ad0-8af4-e42b6d90fec2', 3, 'IAM roles cannot be attached to EC2 instances; roles are only usable by IAM users assuming them manually via STS.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('c45a2a87-8ba4-4ad0-8af4-e42b6d90fec2', '22b3bb4a-1534-48f8-99c0-974abeb7e906', 'Attaching an IAM role to the EC2 instance (via an instance profile) is the AWS-recommended pattern precisely because it eliminates long-term credentials on the instance entirely — the instance retrieves short-lived, automatically-rotated temporary credentials from the instance metadata service (IMDS), removing the risk of leaked long-term access keys (a very common real-world breach vector: keys committed to a public repo, left in an AMI, etc.). Using a long-term IAM user access key on an instance, or worse, root credentials, is exactly the anti-pattern the SAA exam tests against.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('0768cacf-c4b2-47dd-b072-11ab497f453e', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 6, 'Account A owns an S3 bucket encrypted with a KMS customer-managed key that Account A also owns. Account B needs to be granted permission to decrypt objects in that bucket. What must be true for Account B''s access to actually work?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a1f23277-19e6-4b6b-a603-440d29cd022b', '0768cacf-c4b2-47dd-b072-11ab497f453e', 0, 'Only the S3 bucket policy needs to grant Account B access; the KMS key policy is irrelevant to cross-account S3 object decryption.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0626ae75-f54c-4172-8f83-ab3b6c504e0a', '0768cacf-c4b2-47dd-b072-11ab497f453e', 1, 'Only the KMS key policy needs to grant Account B access; the S3 bucket policy is irrelevant once the key policy allows it.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('78b5bdce-7b25-4ae3-ade4-73eb52111a18', '0768cacf-c4b2-47dd-b072-11ab497f453e', 2, 'BOTH the S3 bucket policy (or object ACL) AND the KMS key policy must grant Account B the relevant permissions — access to the encrypted object requires both S3-level permission and KMS-level permission to use the key.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('28c4ffad-b08a-4a93-b667-358fb63427c5', '0768cacf-c4b2-47dd-b072-11ab497f453e', 3, 'Cross-account access to KMS-encrypted S3 objects is not supported by AWS under any configuration.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('0768cacf-c4b2-47dd-b072-11ab497f453e', '78b5bdce-7b25-4ae3-ade4-73eb52111a18', 'Reading a KMS-encrypted S3 object across accounts requires permission at two independent layers: the S3 bucket policy (or object ACL) must grant Account B the s3:GetObject permission, AND the KMS key policy must separately grant Account B (or a role in Account B) kms:Decrypt permission on that specific CMK. Missing either one results in access denied — this two-layer requirement is a frequently-tested SAA trap, since it''s easy to correctly configure S3 permissions and forget the KMS key policy also needs updating for cross-account scenarios specifically.');

-- ── Domain: Design Resilient Architectures (26% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('2eced134-e261-437b-a889-ef36956f6306', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 7, 'An RDS database is configured for Multi-AZ deployment. The primary database instance in AZ-1 fails. What happens?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4a4f5ee1-b1d8-475b-a4cb-ea234206e87e', '2eced134-e261-437b-a889-ef36956f6306', 0, 'RDS automatically fails over to the standby replica in AZ-2, and the application must be manually reconfigured with the new endpoint address.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0b1ea175-b528-42df-bc4f-59fc62a1803f', '2eced134-e261-437b-a889-ef36956f6306', 1, 'RDS automatically fails over to the standby replica in AZ-2, and the DNS endpoint automatically points to the new primary — the application does not need reconfiguration, only a brief connection interruption.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('98b9b043-be3d-4c31-832a-fe42488a87d5', '2eced134-e261-437b-a889-ef36956f6306', 2, 'The database becomes unavailable until an administrator manually promotes the standby, since RDS Multi-AZ failover is not automatic.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('521fce81-2a8c-4456-a219-d902124fabc3', '2eced134-e261-437b-a889-ef36956f6306', 3, 'The standby in Multi-AZ is read-only and cannot serve write traffic even after being promoted, so the database remains write-unavailable permanently.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('2eced134-e261-437b-a889-ef36956f6306', '0b1ea175-b528-42df-bc4f-59fc62a1803f', 'RDS Multi-AZ failover is automatic — AWS detects the primary failure, promotes the standby in the second AZ, and updates the DNS CNAME record for the database endpoint to point to the newly-promoted instance. The application keeps using the same endpoint address and only experiences a brief connection interruption during the failover (typically under a couple of minutes), not a manual reconfiguration. This is the core distinction the SAA exam tests: Multi-AZ is for high availability/failover, NOT for read scaling — that''s what Read Replicas are for (covered separately).');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('3183ce08-850a-4fa7-be5a-af78c956a61d', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 8, 'An Auto Scaling Group is configured behind an Application Load Balancer with ELB health checks enabled. An instance in the group starts failing its health checks, but the instance''s own status checks (EC2 system/instance status) still show healthy. What does the Auto Scaling Group do?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('19487fef-86eb-4434-a1a3-3e4f6ebb0fd7', '3183ce08-850a-4fa7-be5a-af78c956a61d', 0, 'Nothing — since the EC2 status checks report healthy, the Auto Scaling Group ignores the ELB health check result entirely.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('568aea3c-521a-4351-9c7a-0ff90a4ff98f', '3183ce08-850a-4fa7-be5a-af78c956a61d', 1, 'The Auto Scaling Group marks the instance unhealthy based on the ELB health check (since ELB health checks were explicitly enabled for the group) and terminates and replaces it with a new instance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('01020276-153c-4185-bd92-a6f9a5269b74', '3183ce08-850a-4fa7-be5a-af78c956a61d', 2, 'The ALB permanently removes the instance from its target group with no possibility of the Auto Scaling Group replacing it.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8fb92251-12f8-4094-88ba-90efe3a287cc', '3183ce08-850a-4fa7-be5a-af78c956a61d', 3, 'The Auto Scaling Group immediately scales out by launching one additional instance, without touching the unhealthy one.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('3183ce08-850a-4fa7-be5a-af78c956a61d', '568aea3c-521a-4351-9c7a-0ff90a4ff98f', 'When ELB health checks are explicitly enabled on an Auto Scaling Group (in addition to the default EC2 status checks), the ASG uses the ELB''s application-level health check result — which can catch problems the underlying EC2 instance status checks cannot see, such as the web server process crashing while the OS/network layer is still fine. An instance failing ELB health checks is marked unhealthy and the ASG terminates it and launches a replacement to maintain the desired capacity, independent of what the basic EC2 status checks report.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('698effad-9e9d-4302-ad8c-69128716a07c', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 9, 'A company needs its S3 data to survive the accidental deletion of objects AND to be automatically copied to a bucket in a different AWS Region for disaster recovery. Which combination of S3 features achieves both requirements?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6e16af59-9d30-4628-892d-1243c4649409', '698effad-9e9d-4302-ad8c-69128716a07c', 0, 'S3 Versioning alone, since versioning automatically replicates objects to other regions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f2b06e57-194e-4e01-b24a-2b1b75320028', '698effad-9e9d-4302-ad8c-69128716a07c', 1, 'S3 Versioning (to protect against accidental deletion/overwrite by preserving prior object versions) combined with Cross-Region Replication, or CRR, (to automatically copy objects to a bucket in another Region) — CRR itself requires versioning to be enabled on both buckets.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('33d703b7-3162-4e41-8155-d5eb86245150', '698effad-9e9d-4302-ad8c-69128716a07c', 2, 'S3 Lifecycle policies alone, since lifecycle rules handle both versioning and cross-region copying.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f93f96bc-7db5-488a-9cca-7574cdfd22e0', '698effad-9e9d-4302-ad8c-69128716a07c', 3, 'S3 Transfer Acceleration, which both retains old object versions and speeds up cross-region access.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('698effad-9e9d-4302-ad8c-69128716a07c', 'f2b06e57-194e-4e01-b24a-2b1b75320028', 'S3 Versioning protects against accidental deletion or overwrite by keeping every previous version of an object retrievable (a delete becomes a "delete marker," not a permanent removal, and can be undone). Cross-Region Replication (CRR) automatically and asynchronously copies objects to a bucket in a different Region for disaster recovery — and CRR has a hard prerequisite that Versioning must be enabled on both the source and destination buckets, which is exactly why these two features are paired together in this scenario, not because either one alone does both jobs. Transfer Acceleration is an unrelated feature (it speeds up uploads over long distances via CloudFront edge locations) and does neither of the two things asked.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('e870a968-b5c7-467d-99bb-852dfb7496c2', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 10, 'A company is migrating a legacy application that requires raw TCP connection handling and needs to preserve the client''s source IP address at extremely high throughput with ultra-low latency. Which AWS load balancer type should they use?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c5e1f778-33e7-41cf-bc25-5465b8e5a8fd', 'e870a968-b5c7-467d-99bb-852dfb7496c2', 0, 'Application Load Balancer (ALB), since it operates at Layer 7 and offers the most advanced routing features.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('95559157-7242-4270-ad36-33b522854e7e', 'e870a968-b5c7-467d-99bb-852dfb7496c2', 1, 'Network Load Balancer (NLB), since it operates at Layer 4, is designed for ultra-high-performance TCP/UDP traffic, and preserves the client source IP by default.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('93e55d26-6588-4bf7-a830-2b93dd106b22', 'e870a968-b5c7-467d-99bb-852dfb7496c2', 2, 'Classic Load Balancer (CLB), since it is the newest AWS load balancer type and replaces both ALB and NLB.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4377b2c1-8e17-4d58-ba49-f728a8d4ffe8', 'e870a968-b5c7-467d-99bb-852dfb7496c2', 3, 'Gateway Load Balancer, since it is designed specifically for HTTP/HTTPS content-based routing at the lowest possible latency.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('e870a968-b5c7-467d-99bb-852dfb7496c2', '95559157-7242-4270-ad36-33b522854e7e', 'Network Load Balancer (NLB) operates at Layer 4 (transport layer), handles raw TCP/UDP traffic, and is purpose-built for extreme performance — millions of requests per second with ultra-low latency — and it preserves the original client source IP address by default (ALB requires reading the X-Forwarded-For header instead, since it terminates the connection at Layer 7). ALB is the correct choice for HTTP/HTTPS content-based routing (path/host-based rules), not raw TCP performance. CLB is the legacy, oldest load balancer type (not newest) and is generally not recommended for new workloads. Gateway Load Balancer is for deploying and scaling third-party virtual network appliances (firewalls, IDS/IPS), not general HTTP routing.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('a45feae4-4d9c-4009-b5b6-a7b2857512b0', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 11, 'A read-heavy reporting workload is causing performance degradation on the primary RDS database, which also handles the application''s write traffic. What is the correct RDS feature to address this, and how does it differ from Multi-AZ?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e1dbd9db-2c96-4a7f-95f0-6d79546fbbc3', 'a45feae4-4d9c-4009-b5b6-a7b2857512b0', 0, 'Enable Multi-AZ — the standby replica in the second AZ automatically serves read traffic to offload the primary.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c28f3a6c-154f-4ab2-b8aa-fe2520f9556c', 'a45feae4-4d9c-4009-b5b6-a7b2857512b0', 1, 'Create one or more Read Replicas — these are separate, queryable database instances asynchronously replicated from the primary, specifically designed to offload read traffic; Multi-AZ standbys, by contrast, are not directly queryable and exist purely for failover.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2e5b55ee-1f16-48d3-a159-28760bfbd270', 'a45feae4-4d9c-4009-b5b6-a7b2857512b0', 2, 'Multi-AZ and Read Replicas are the same feature under two different names, so either configuration solves the problem identically.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ebe645b8-3b59-4ac2-b0dc-d3f479e6dd19', 'a45feae4-4d9c-4009-b5b6-a7b2857512b0', 3, 'Neither Multi-AZ nor Read Replicas can offload read traffic; only migrating to DynamoDB solves this.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('a45feae4-4d9c-4009-b5b6-a7b2857512b0', 'c28f3a6c-154f-4ab2-b8aa-fe2520f9556c', 'This is one of the most frequently tested SAA distinctions: Multi-AZ exists purely for high availability/failover — the standby is not directly queryable by the application during normal operation and only becomes active after a failover. Read Replicas are separate, independently queryable database instances kept in near-real-time sync via asynchronous replication, specifically intended to offload read-only traffic (like this reporting workload) from the primary, which remains solely responsible for writes. The two features solve genuinely different problems and are commonly used together — Multi-AZ for HA, Read Replicas for read scaling.');

-- ── Domain: Design High-Performing Architectures (24% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('b4d78584-4526-464e-9f03-f7f582ac3a59', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 12, 'An application repeatedly runs the same expensive, frequently-read database query, causing high load on the RDS instance. Introducing which AWS service in front of the database would most directly reduce this repeated read load?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('788f3058-5eee-476d-b88d-d0eecfe640f5', 'b4d78584-4526-464e-9f03-f7f582ac3a59', 0, 'Amazon ElastiCache (Redis or Memcached), used as an in-memory cache layer that stores the query results so repeated identical requests are served from cache instead of hitting the database each time.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('90533a09-de99-464d-9998-e058699c9679', 'b4d78584-4526-464e-9f03-f7f582ac3a59', 1, 'Amazon CloudFront, since it caches database query results the same way it caches static web content.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ae71df91-d432-4efa-8cd1-92e9893958ec', 'b4d78584-4526-464e-9f03-f7f582ac3a59', 2, 'AWS Direct Connect, since it reduces network latency between the application and the database.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d636e091-5cd5-4c83-9a71-b87dfcfe68fb', 'b4d78584-4526-464e-9f03-f7f582ac3a59', 3, 'AWS Global Accelerator, since it improves the performance of database connections specifically.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('b4d78584-4526-464e-9f03-f7f582ac3a59', '788f3058-5eee-476d-b88d-d0eecfe640f5', 'ElastiCache is purpose-built as an in-memory caching layer that sits between the application and the database — the application checks the cache first, and only queries the database on a cache miss, which is exactly the fix for a repeated, expensive, read-heavy query pattern. CloudFront caches HTTP content at edge locations for end users, not database query results, and isn''t positioned between an application and its database. Direct Connect provides a dedicated network link to AWS (a networking/hybrid-connectivity feature, not a caching one). Global Accelerator improves routing to Elastic IP/ALB endpoints over the AWS global network, also not a database-query caching solution.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('9d9f096b-002e-44ea-a527-7e637094462b', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 13, 'A media company serves static video files from an S3 bucket to users worldwide and wants to reduce latency for users far from the bucket''s Region, while also reducing direct load on the S3 bucket. What should they implement?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('252c8dcc-4a80-4eab-836c-61c81bece139', '9d9f096b-002e-44ea-a527-7e637094462b', 0, 'CloudFront with the S3 bucket configured as the origin — CloudFront caches content at edge locations close to end users, serving most requests without going back to S3.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0cf2df60-76ae-4da6-ab0f-5b49aa0bdbec', '9d9f096b-002e-44ea-a527-7e637094462b', 1, 'Enable S3 Transfer Acceleration only, and skip CloudFront entirely, since Transfer Acceleration is a full CDN replacement.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9077525f-34fa-44b5-92d5-e4db46ff8ece', '9d9f096b-002e-44ea-a527-7e637094462b', 2, 'Copy the S3 bucket manually to every AWS Region worldwide and route users based on geography.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f57e223d-f593-40c1-9720-b14f0a744d74', '9d9f096b-002e-44ea-a527-7e637094462b', 3, 'Increase the S3 bucket''s provisioned throughput, since S3 requires manual throughput provisioning like EBS volumes.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('9d9f096b-002e-44ea-a527-7e637094462b', '252c8dcc-4a80-4eab-836c-61c81bece139', 'CloudFront is AWS''s CDN, and using it in front of an S3 origin caches content at edge locations distributed globally — requests from users far from the bucket''s Region are served from a nearby edge cache instead of round-tripping to the origin bucket, directly reducing both latency and the number of requests hitting S3 itself. S3 Transfer Acceleration is a different feature (it speeds up uploads TO S3 over long distances via CloudFront''s edge network, not general content delivery to many downstream readers) and is not a CDN replacement. S3 has no manual "provisioned throughput" setting the way EBS does — it scales automatically. Manually copying buckets per Region is a real DIY pattern in some cases but is operationally far heavier than the built-in CloudFront solution and isn''t what''s being tested here.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('2ef23090-f60b-44a2-9058-38eaba50cf69', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 14, 'A workload requires an EBS volume with the highest possible IOPS and sub-millisecond latency for a mission-critical, latency-sensitive database, with cost being a secondary concern. Which EBS volume type is designed for this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d291fe2b-e815-4b6d-8f89-04f1cfb811cc', '2ef23090-f60b-44a2-9058-38eaba50cf69', 0, 'st1 (Throughput Optimized HDD), designed for high-IOPS, latency-critical workloads.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ba46432e-e58f-4151-a6c3-de43b588ff89', '2ef23090-f60b-44a2-9058-38eaba50cf69', 1, 'sc1 (Cold HDD), designed for the lowest cost per GB regardless of performance needs.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('071d84a4-3f25-4a08-921f-f7c4f222773f', '2ef23090-f60b-44a2-9058-38eaba50cf69', 2, 'io2 Block Express (Provisioned IOPS SSD), designed specifically for the highest-performance, most demanding, latency-sensitive workloads such as large relational or NoSQL databases.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('749aa7c0-221d-414d-9cc3-9ca4866c5600', '2ef23090-f60b-44a2-9058-38eaba50cf69', 3, 'All EBS volume types offer identical performance; the only difference between them is price.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('2ef23090-f60b-44a2-9058-38eaba50cf69', '071d84a4-3f25-4a08-921f-f7c4f222773f', 'io2 Block Express is AWS''s highest-performance Provisioned IOPS SSD tier, purpose-built for the most demanding, latency-sensitive workloads (large-scale relational databases, SAP HANA, etc.) with sub-millisecond latency and the highest IOPS ceiling of any EBS volume type. st1 (Throughput Optimized HDD) is designed for high-throughput, sequential workloads like big data/log processing — not high-IOPS, latency-critical use — and sc1 (Cold HDD) is the lowest-cost, lowest-performance tier for infrequently accessed data. Matching volume type to actual workload access pattern (IOPS-sensitive vs. throughput-sensitive vs. infrequent-access) rather than assuming "faster is always the SSD option" is a core EBS concept on the SAA exam.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('32c0c107-4a03-435a-b688-0f58eb62755e', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 15, 'An application accesses a specific set of S3 objects daily and requires millisecond first-byte latency; those objects must never be moved to a slower storage tier automatically. Which S3 storage class is correct for this access pattern?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('90d0edf5-a64e-4178-9308-dd88be235cb3', '32c0c107-4a03-435a-b688-0f58eb62755e', 0, 'S3 Glacier Flexible Retrieval, since it is the default storage class and offers the lowest storage cost.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('da9a604f-9022-46bd-8cf4-f28be15505ec', '32c0c107-4a03-435a-b688-0f58eb62755e', 1, 'S3 Standard, which is designed for frequently-accessed data and provides millisecond first-byte latency, with no automatic tiering.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5f1ef7f9-a3e3-4281-a2ea-5ad0c6acb32c', '32c0c107-4a03-435a-b688-0f58eb62755e', 2, 'S3 Standard-Infrequent Access (S3 Standard-IA), since "Infrequent Access" is simply a newer name for daily-access workloads.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4e3680c6-46cc-4ce8-991f-934621388e85', '32c0c107-4a03-435a-b688-0f58eb62755e', 3, 'S3 Intelligent-Tiering, since it guarantees objects always remain in the fastest tier and never moves them automatically.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('32c0c107-4a03-435a-b688-0f58eb62755e', 'da9a604f-9022-46bd-8cf4-f28be15505ec', 'S3 Standard is the default, general-purpose storage class for frequently-accessed data, offering millisecond first-byte latency with no minimum storage duration and no automatic movement between tiers. Glacier classes are for archival, with retrieval times ranging from minutes to hours (not millisecond access) and are the opposite of what''s needed here. S3 Standard-IA is designed for infrequently accessed data (with a retrieval fee per GB) — daily access doesn''t fit that pattern well and would incur unnecessary retrieval charges. S3 Intelligent-Tiering actively monitors access patterns and DOES move objects between tiers automatically based on usage — the opposite of "never moved automatically," which rules it out here even though it also offers millisecond access for its frequent-access tier.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('5030560e-6c53-45fb-ba41-8636cdf12730', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 16, 'A machine-learning training workload is CPU/GPU-bound and needs to process large in-memory datasets as fast as possible; cost is secondary to raw compute throughput. Which EC2 instance family is purpose-built for this profile?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1c63a79a-fec4-4d77-b345-e03b066c7ee3', '5030560e-6c53-45fb-ba41-8636cdf12730', 0, 'T-family (burstable general purpose), since burstable CPU credits are ideal for sustained heavy compute workloads.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('254405c3-4e77-4c22-99e9-c71a601745c7', '5030560e-6c53-45fb-ba41-8636cdf12730', 1, 'C-family or P-family (Compute Optimized, or GPU-accelerated for ML specifically), which are purpose-built for high-performance compute-bound and ML training workloads respectively.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4e86cba5-07ae-49a0-b633-9dd0e3c59207', '5030560e-6c53-45fb-ba41-8636cdf12730', 2, 'D-family (Dense storage), since ML training is always storage-bound rather than compute-bound.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('704d8ba7-3d78-40a4-9253-e05ac08936ef', '5030560e-6c53-45fb-ba41-8636cdf12730', 3, 'All EC2 instance families provide identical compute performance; the family designation only affects the instance name shown in billing.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('5030560e-6c53-45fb-ba41-8636cdf12730', '254405c3-4e77-4c22-99e9-c71a601745c7', 'EC2 instance families are purpose-built for different workload profiles: C-family (Compute Optimized) is designed for high-performance, CPU-bound processing; P-family provides GPU acceleration specifically suited to ML training and other GPU-parallel workloads. T-family (burstable) is designed for workloads with occasional CPU spikes and a generally low average utilization — it is explicitly NOT suited to sustained heavy compute, since burst credits deplete and performance is throttled once they''re exhausted, the opposite of what a sustained ML training job needs. D-family targets high-density, sequential-throughput storage workloads (like data warehousing), not primarily compute — matching instance family to actual workload profile (compute-bound vs. memory-bound vs. storage-bound vs. burstable) is a recurring SAA theme.');

-- ── Domain: Design Cost-Optimized Architectures (20% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('2ff70523-f073-4aa9-ae88-250273789e5e', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 17, 'A workload is fault-tolerant, flexible on when it runs, and can be interrupted with minimal impact (e.g., batch data processing that checkpoints progress). Which EC2 purchasing option offers the largest potential cost savings for this specific workload?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e54afca2-2910-46aa-a160-b19e24dce709', '2ff70523-f073-4aa9-ae88-250273789e5e', 0, 'On-Demand Instances, since they offer the lowest possible price for any workload type.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7ac3090f-02dc-4e1f-8dd2-9e9493d43dd2', '2ff70523-f073-4aa9-ae88-250273789e5e', 1, 'Reserved Instances, since a 1- or 3-year commitment always beats every other pricing model regardless of workload interruptibility.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6da6dde4-52f0-4a5a-93f4-fd687721f0d3', '2ff70523-f073-4aa9-ae88-250273789e5e', 2, 'Spot Instances, which offer the deepest discounts (often up to ~90% off On-Demand) specifically for interruptible, flexible workloads, since AWS can reclaim Spot capacity with short notice.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bf1d8e09-36ee-4b1f-9bd1-75b813b7fbe3', '2ff70523-f073-4aa9-ae88-250273789e5e', 3, 'Dedicated Hosts, since dedicating a physical server always reduces cost compared to shared multi-tenant options.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('2ff70523-f073-4aa9-ae88-250273789e5e', '6da6dde4-52f0-4a5a-93f4-fd687721f0d3', 'Spot Instances draw on AWS''s spare capacity at steep discounts (commonly up to ~90% off On-Demand pricing) in exchange for the tradeoff that AWS can reclaim the instance with a short (roughly two-minute) interruption notice — which is exactly why Spot is matched to fault-tolerant, interruption-tolerant, flexible-timing workloads like this one, and a poor fit for anything requiring guaranteed, continuous availability. Reserved Instances trade a 1- or 3-year commitment for a discount on steady-state, predictable workloads, but don''t match a flexible/interruptible batch job as well as Spot''s discount depth does. Dedicated Hosts are for compliance/licensing needs requiring a physical server dedicated to one customer, and are typically more expensive, not cheaper, than shared options.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('1e26fab5-d2d2-4251-afd1-2d5381c0607e', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 18, 'A company stores objects in S3 whose access patterns are unpredictable and change over time — some objects are accessed frequently for a while, then rarely, then sometimes frequently again, with no reliable pattern. They want to minimize storage cost automatically without manually managing lifecycle rules or risking retrieval fees on objects that suddenly become frequently accessed again. What is the best S3 storage class for this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5dfd4061-a149-4267-8dc9-4e3a6b54e957', '1e26fab5-d2d2-4251-afd1-2d5381c0607e', 0, 'S3 Standard-IA, since it always has the lowest cost regardless of access pattern.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9ff20300-df6c-43c2-adca-eb8b25097405', '1e26fab5-d2d2-4251-afd1-2d5381c0607e', 1, 'S3 Intelligent-Tiering, which automatically moves objects between frequent-access and infrequent-access tiers based on observed usage patterns, with no retrieval fees when access patterns change.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('17a595fa-e144-400e-8ffa-eb52cf27ecdf', '1e26fab5-d2d2-4251-afd1-2d5381c0607e', 2, 'S3 One Zone-IA, since storing data in only one Availability Zone is always the cheapest option for any use case.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2d8f0b6a-cf8f-41eb-a36e-9f76db88e6ee', '1e26fab5-d2d2-4251-afd1-2d5381c0607e', 3, 'Manually-configured S3 Lifecycle rules moving objects to Glacier after 30 days, regardless of actual access pattern.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('1e26fab5-d2d2-4251-afd1-2d5381c0607e', '9ff20300-df6c-43c2-adca-eb8b25097405', 'S3 Intelligent-Tiering is designed specifically for unpredictable or changing access patterns — it monitors actual object access and automatically moves objects between a frequent-access tier and lower-cost infrequent/archive tiers, and critically, moving an object BACK to the frequent tier when it starts being accessed again does not incur a retrieval fee (unlike S3 Standard-IA, which charges a per-GB retrieval fee any time an infrequently-accessed object is read). Manually-configured lifecycle rules moving objects to Glacier on a fixed schedule ignore actual access patterns and risk expensive retrieval fees if a "cold" object suddenly needs frequent access again — exactly the scenario Intelligent-Tiering exists to solve automatically.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('69fbc281-1a4f-4bee-a766-be61ff8f6a47', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 19, 'A company runs a steady, predictable baseline of compute usage across multiple EC2 instance families and sizes, and even occasionally uses AWS Fargate and Lambda for parts of the same workload. They want a flexible commitment-based discount that applies across all of this compute usage, not tied to a specific instance family or Region. What should they use?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ecaeb69f-a4b0-4de4-ab4b-4779116a47b9', '69fbc281-1a4f-4bee-a766-be61ff8f6a47', 0, 'Standard Reserved Instances, since they apply automatically to any compute service including Lambda and Fargate.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('448a2aef-b05d-423c-afd8-2f4251ffa8a5', '69fbc281-1a4f-4bee-a766-be61ff8f6a47', 1, 'Compute Savings Plans, which apply a discount in exchange for a commitment to a consistent amount of compute usage (measured in $/hour), automatically applying across instance family, size, OS, Region, and even to Fargate and Lambda usage.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('710859ca-61e3-49b3-a8fc-7d2364fef877', '69fbc281-1a4f-4bee-a766-be61ff8f6a47', 2, 'On-Demand Capacity Reservations, since they provide the deepest possible discount for flexible usage across services.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bb73dd12-6940-4597-97cb-9c69c1b6ed5d', '69fbc281-1a4f-4bee-a766-be61ff8f6a47', 3, 'Spot Instances, since their flexible pricing model automatically extends to Lambda and Fargate usage as well.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('69fbc281-1a4f-4bee-a766-be61ff8f6a47', '448a2aef-b05d-423c-afd8-2f4251ffa8a5', 'Compute Savings Plans are the correct fit specifically because the commitment is measured in $/hour of compute spend, not tied to a specific instance family, size, OS, tenancy, or Region — the discount automatically applies across EC2 (any family/size), AWS Fargate, and AWS Lambda usage, which directly matches this scenario''s mixed-service, flexible usage. Standard Reserved Instances, by contrast, are tied to a specific instance family and Region (with EC2 Instance Savings Plans being a similarly-flexible-but-EC2-only alternative) and do not extend to Fargate/Lambda the way Compute Savings Plans do. Capacity Reservations reserve capacity in a specific AZ but do not themselves provide a discount — they''re about guaranteeing availability, not saving money, and are often paired with an RI or Savings Plan rather than being a discount mechanism on their own. Spot pricing is a separate purchasing model for EC2 specifically and does not apply to Lambda/Fargate at all.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('e9b12f34-2c56-4a89-b7d3-8f4e6a9c1d02', '8f0a1c23-3d76-4ea9-af5d-aac648412e1b', 20, 'A company has several NAT Gateways running in multiple Availability Zones, each incurring an hourly charge plus a per-GB data processing charge, even during off-peak hours when very little outbound traffic occurs. Which action would reduce cost without compromising the private subnets'' ability to initiate outbound internet connections during business hours?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f966e964-542c-444c-a3c7-e3524f0d97e5', 'e9b12f34-2c56-4a89-b7d3-8f4e6a9c1d02', 0, 'Delete all NAT Gateways permanently, since private subnets never need outbound internet access under any circumstances.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('10d909e0-c56c-43c6-90fb-f48a0f2d74fe', 'e9b12f34-2c56-4a89-b7d3-8f4e6a9c1d02', 1, 'Replace NAT Gateways with Gateway VPC Endpoints only, since Gateway Endpoints can handle all outbound internet traffic to any destination, not just AWS services.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5b08b203-4a55-46c2-bea0-84c2d6276151', 'e9b12f34-2c56-4a89-b7d3-8f4e6a9c1d02', 2, 'Consolidate to fewer NAT Gateways where the availability trade-off is acceptable, AND route traffic destined for AWS services (S3, DynamoDB) through Gateway/Interface VPC Endpoints instead of through the NAT Gateway, reducing the data volume that actually needs to traverse (and be billed by) the NAT Gateway.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('030a1e0f-aa02-4cde-be3f-aa9e49f8d6c4', 'e9b12f34-2c56-4a89-b7d3-8f4e6a9c1d02', 3, 'Switch every NAT Gateway to a larger instance size, since NAT Gateways are billed based on provisioned instance size like EC2.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('e9b12f34-2c56-4a89-b7d3-8f4e6a9c1d02', '5b08b203-4a55-46c2-bea0-84c2d6276151', 'NAT Gateways are billed hourly per gateway plus per-GB of data processed through them, so the cost-optimization lever is twofold: reduce the number of NAT Gateways where the resulting AZ-redundancy trade-off is acceptable for the workload, and — importantly — route traffic to AWS services like S3/DynamoDB through VPC Endpoints instead of the NAT Gateway, since that traffic no longer counts toward the NAT Gateway''s data-processing charge at all. Deleting NAT Gateways entirely would break legitimate outbound internet access needed for things like software updates or third-party API calls, not just AWS-service traffic, which VPC Endpoints don''t cover. NAT Gateway is a managed AWS service with no "instance size" to configure — that option describes EC2, not NAT Gateway, which is intentionally not user-provisioned by size.');
