-- ============================================================
-- AWS Solutions Architect Associate (SAA-C03) — Seed Data: Paper 2
-- New content, distinct topics from Paper 1 (docs/aws_saa_seed_paper_1.sql)
-- — no repeated scenarios. Same domain weighting as Paper 1, matching the
-- real SAA-C03 blueprint: Design Secure 30% (6/20), Design Resilient 26%
-- (5/20), Design High-Performing 24% (5/20), Design Cost-Optimized 20%
-- (4/20). Every question checked against stable, documented AWS service
-- behavior. UUID integrity verified with scratchpad/check_uuid_dupes.mjs
-- before finalizing (see Paper 1's real duplicate-ID bug, now a standing
-- verification step for every paper going forward).
-- Run this AFTER docs/question-bank-schema.sql and docs/aws_saa_seed_paper_1.sql.
-- ============================================================

INSERT INTO question_papers (id, slug, title, exam_type, focus_tags, question_count, difficulty, is_premium, sort_order, time_limit_minutes)
VALUES ('d289b99e-2765-4074-8f63-9cb49323cc79', 'aws-saa-practice-2', 'AWS SAA-C03 Practice Paper 2', 'aws-saa', ARRAY['WAF', 'Secrets Manager', 'Route 53', 'DynamoDB', 'RDS Proxy', 'Auto Scaling', 'S3 Lifecycle', 'Compute Optimizer']::TEXT[], 20, 'standard', true, 2, 30);

-- ── Domain: Design Secure Architectures (30% — 6 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('fda444a2-579e-4759-b0a0-e1ba59c87a96', 'd289b99e-2765-4074-8f63-9cb49323cc79', 1, 'A company''s public-facing web application is being targeted by repeated SQL injection and cross-site scripting (XSS) attempts. Which AWS service should sit in front of the application to inspect and filter this type of malicious HTTP traffic?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d14499b1-d907-43ba-9b6a-379c0ee5680b', 'fda444a2-579e-4759-b0a0-e1ba59c87a96', 0, 'AWS Shield Standard, since it is designed specifically to inspect HTTP request content for SQL injection and XSS patterns.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c6939cad-3c03-454c-9dc8-e87a039cb6df', 'fda444a2-579e-4759-b0a0-e1ba59c87a96', 1, 'AWS WAF (Web Application Firewall), attached to CloudFront or an ALB, using managed or custom rules to inspect and block requests matching SQL injection/XSS signatures.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f4c74f46-f421-4223-a3f9-5c491384a82d', 'fda444a2-579e-4759-b0a0-e1ba59c87a96', 2, 'Security Groups, since they can inspect HTTP request bodies for malicious payloads.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1bb27cc1-3b10-4912-afb2-5d731cfbdf46', 'fda444a2-579e-4759-b0a0-e1ba59c87a96', 3, 'Network ACLs, since they operate at Layer 7 and can filter based on HTTP request content.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('fda444a2-579e-4759-b0a0-e1ba59c87a96', 'c6939cad-3c03-454c-9dc8-e87a039cb6df', 'AWS WAF operates at Layer 7 and is purpose-built to inspect the actual content of HTTP requests — headers, body, query strings — against rules (AWS Managed Rules include ready-made SQL injection and XSS rule groups, or custom rules can be written) and block matching requests before they reach the application. AWS Shield protects against DDoS (volumetric/network-layer attacks), not content-based application-layer attacks like SQLi/XSS — Shield and WAF are complementary, not interchangeable. Both Security Groups and NACLs operate at Layer 3/4 (IP/port level) and have no visibility into HTTP request content at all.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('81aee77d-2042-4a83-bf77-718042754f9a', 'd289b99e-2765-4074-8f63-9cb49323cc79', 2, 'An application currently reads a database password from a hardcoded value in its configuration file. The company wants to store this credential securely, rotate it automatically on a schedule without any application code changes to fetch the new value''s location, and integrate directly with RDS for rotation. Which AWS service is the best fit?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('30b40a9e-4012-4ed7-b71e-1c0f2e1c1384', '81aee77d-2042-4a83-bf77-718042754f9a', 0, 'AWS Systems Manager Parameter Store (Standard tier), since it has built-in automatic rotation integration with RDS out of the box.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7d1f9398-55c7-4c2b-9d47-3d56aa86f0d8', '81aee77d-2042-4a83-bf77-718042754f9a', 1, 'AWS Secrets Manager, which supports automatic, scheduled credential rotation with built-in Lambda rotation templates for RDS, without the application needing to track a changing storage location.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5f326125-8a84-4d51-9d0a-3e3a4cb1c6d6', '81aee77d-2042-4a83-bf77-718042754f9a', 2, 'Amazon S3 with versioning enabled, since S3 versioning provides automatic credential rotation for database passwords.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a2c571f7-a7bd-4493-ae88-82261b13553a', '81aee77d-2042-4a83-bf77-718042754f9a', 3, 'AWS KMS, since KMS keys can directly store and automatically rotate database passwords.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('81aee77d-2042-4a83-bf77-718042754f9a', '7d1f9398-55c7-4c2b-9d47-3d56aa86f0d8', 'Secrets Manager is purpose-built for exactly this: it natively supports automatic, scheduled rotation of credentials and provides pre-built Lambda rotation function templates specifically for RDS (and other services), so the actual password value changes on schedule while the application always retrieves the current value via the same secret name/ARN — no code change needed to track a new location. Parameter Store (Standard tier) can store secrets but does not have this same built-in automatic-rotation-with-RDS integration (Parameter Store Advanced tier has some rotation support via custom automation, but Secrets Manager''s RDS integration is more direct and purpose-built). S3 versioning tracks object version history, not credential rotation. KMS manages encryption keys, not application secrets/passwords directly — it''s commonly used to encrypt secrets stored elsewhere (including in Secrets Manager itself), not as a secrets store on its own.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('0a2a5d05-793a-4913-8551-933bd2de5819', 'd289b99e-2765-4074-8f63-9cb49323cc79', 3, 'A security team needs to audit exactly which IP addresses and ports had traffic accepted or rejected at the network interface level for EC2 instances in a VPC, for forensic investigation after a suspected intrusion. Which AWS feature provides this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('560d4ce1-b314-40e2-b7ef-d6f2b5cd315e', '0a2a5d05-793a-4913-8551-933bd2de5819', 0, 'VPC Flow Logs, which capture metadata about IP traffic (source/destination IP and port, protocol, accept/reject) going to and from network interfaces in the VPC.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('20ff0569-7f25-407d-8f05-929e4a831fce', '0a2a5d05-793a-4913-8551-933bd2de5819', 1, 'CloudTrail, since it logs the actual packet contents of every network connection made to an EC2 instance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5d713049-dadf-424d-8a9a-3733d6600ffc', '0a2a5d05-793a-4913-8551-933bd2de5819', 2, 'AWS Config, since it records every individual network packet sent between EC2 instances.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a7cd2046-0dec-4fe7-afae-a01bf8395084', '0a2a5d05-793a-4913-8551-933bd2de5819', 3, 'Amazon Inspector, since its core function is logging historical network traffic for forensic review.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('0a2a5d05-793a-4913-8551-933bd2de5819', '560d4ce1-b314-40e2-b7ef-d6f2b5cd315e', 'VPC Flow Logs capture IP traffic metadata (source/destination IP, source/destination port, protocol, bytes transferred, and whether the traffic was ACCEPTed or REJECTed by a Security Group or NACL) at the ENI, subnet, or VPC level — exactly the accept/reject-by-IP-and-port audit trail needed here. CloudTrail logs AWS API calls/management-plane actions (who created/modified/deleted a resource), not network packet-level traffic. AWS Config tracks resource configuration state and changes over time, not network traffic. Amazon Inspector is a vulnerability-scanning service (assessing EC2/container/Lambda for known vulnerabilities and unintended network exposure), not a traffic-logging service — none of the three distractors actually log traffic metadata the way Flow Logs do.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('3ebfb72f-fb4e-4f0b-aa22-06a3ebe32b38', 'd289b99e-2765-4074-8f63-9cb49323cc79', 4, 'An S3 bucket was accidentally made publicly readable due to a misconfigured bucket policy, exposing sensitive data. What is the single most direct AWS feature to prevent this class of mistake from happening again, account-wide, even if a future bucket policy or ACL is misconfigured?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7a21a74f-da22-4a40-87ea-0cffa80c33d5', '3ebfb72f-fb4e-4f0b-aa22-06a3ebe32b38', 0, 'S3 Versioning, since keeping old versions of objects prevents public exposure of the current version.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d8cc2bbf-4baa-45fe-95b6-b0cc04171efb', '3ebfb72f-fb4e-4f0b-aa22-06a3ebe32b38', 1, 'S3 Block Public Access, enabled at the account level, which overrides any bucket policy or ACL that would otherwise grant public access — the safest, most direct account-wide guardrail against this specific mistake.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('25abe7dc-9bde-4c56-8ee0-edc649d3d408', '3ebfb72f-fb4e-4f0b-aa22-06a3ebe32b38', 2, 'S3 Transfer Acceleration, since accelerating transfers reduces the window of time during which data could be exposed.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b256a698-6895-4875-b9ce-ebab5d1f17be', '3ebfb72f-fb4e-4f0b-aa22-06a3ebe32b38', 3, 'S3 Requester Pays, since it prevents the public from accessing objects without an AWS account.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('3ebfb72f-fb4e-4f0b-aa22-06a3ebe32b38', 'd8cc2bbf-4baa-45fe-95b6-b0cc04171efb', 'S3 Block Public Access is specifically designed as an override guardrail: once enabled (at the account level or per-bucket), it blocks public access even if a bucket policy or ACL is later misconfigured to grant it — this is precisely the "prevent this class of mistake account-wide, even against a future misconfiguration" requirement in the question, and AWS enables it by default on new accounts/buckets for exactly this reason. Versioning protects against accidental deletion/overwrite, not public exposure. Transfer Acceleration is a performance feature (faster uploads via CloudFront edge locations), unrelated to access control. Requester Pays shifts data-transfer cost to the requester but does not prevent public read access on its own — an object can still be public AND have Requester Pays enabled.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('42f590e3-bec9-481c-84af-fcdb4c451bac', 'd289b99e-2765-4074-8f63-9cb49323cc79', 5, 'An IAM policy needs to restrict a set of users so they can only access AWS resources when connecting from the company''s corporate office IP range. Which IAM policy feature achieves this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ac19a690-6761-49d5-b4f0-77ff09a03258', '42f590e3-bec9-481c-84af-fcdb4c451bac', 0, 'A Condition element in the IAM policy using the aws:SourceIp condition key, restricting when the policy''s Allow/Deny applies based on the requester''s IP address.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('19778cf3-bc19-41b4-a106-6286bdb3443b', '42f590e3-bec9-481c-84af-fcdb4c451bac', 1, 'The Resource element, since it is the only part of an IAM policy that can reference network information.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5720fe48-364c-435d-987c-c16e53b08021', '42f590e3-bec9-481c-84af-fcdb4c451bac', 2, 'IAM policies cannot reference IP addresses at all; this can only be enforced with a Security Group.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ffcdd60c-025d-4bfb-af33-73b012491a79', '42f590e3-bec9-481c-84af-fcdb4c451bac', 3, 'The Principal element, since it defines which IP addresses are allowed to assume the policy.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('42f590e3-bec9-481c-84af-fcdb4c451bac', 'ac19a690-6761-49d5-b4f0-77ff09a03258', 'IAM policy Condition elements let a policy''s Allow or Deny apply only when a specified condition is true — the aws:SourceIp global condition key specifically evaluates the requester''s source IP address (supporting CIDR ranges), making it the correct mechanism to restrict access to a corporate office IP range directly within the IAM policy itself. The Resource element specifies which AWS resource(s) the policy applies to (an ARN), not network conditions. The Principal element specifies WHO the policy applies to (used in resource-based policies), not IP restriction. Security Groups can also restrict network-level access, but the question specifically asks about restricting IAM/API-level access by source IP, which is what the Condition/aws:SourceIp combination is built for.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('27b1c041-7a64-4071-bdc5-aff50e936003', 'd289b99e-2765-4074-8f63-9cb49323cc79', 6, 'A company wants baseline protection against common, large-scale DDoS attacks (e.g., SYN floods, UDP reflection) on their public-facing resources with no additional cost or configuration. What AWS feature already provides this by default?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('40c9679d-54b5-44b8-9a5c-d22252784ebf', '27b1c041-7a64-4071-bdc5-aff50e936003', 0, 'AWS Shield Advanced, which is automatically and freely enabled on every AWS account with no opt-in required.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ce01269d-0882-4f86-8bbd-57d40c56da5c', '27b1c041-7a64-4071-bdc5-aff50e936003', 1, 'AWS Shield Standard, which is automatically included at no additional cost for all AWS customers, providing protection against common network/transport-layer DDoS attacks.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3847e8a6-9446-4955-81c1-2824692f049d', '27b1c041-7a64-4071-bdc5-aff50e936003', 2, 'AWS WAF, which is automatically enabled on every AWS resource by default with zero configuration.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('00ebfbdb-6a37-4348-9144-f9825a8060cf', '27b1c041-7a64-4071-bdc5-aff50e936003', 3, 'No baseline DDoS protection exists on AWS without manually enabling and paying for a dedicated service.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('27b1c041-7a64-4071-bdc5-aff50e936003', 'ce01269d-0882-4f86-8bbd-57d40c56da5c', 'AWS Shield Standard is automatically active for every AWS customer at no additional cost, providing protection against the most common, frequently occurring network and transport layer (Layer 3/4) DDoS attacks (like SYN/UDP floods and reflection attacks) on resources such as CloudFront, Route 53, and ELB. Shield ADVANCED is the paid, opt-in tier that adds more sophisticated attack detection, near-real-time visibility, cost protection, and direct AWS DDoS Response Team (DRT) access — it is explicitly NOT free/automatic, which is the key distinction being tested. WAF requires deliberate configuration (rules must be created and associated) and is not "zero configuration."');

-- ── Domain: Design Resilient Architectures (26% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('7bb72be4-0f44-454d-8eab-c2a584d06649', 'd289b99e-2765-4074-8f63-9cb49323cc79', 7, 'An Auto Scaling Group needs to remain highly available even if an entire Availability Zone becomes unavailable. What is the correct configuration approach?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7c880cc1-a563-4a21-a516-a04e44b40cca', '7bb72be4-0f44-454d-8eab-c2a584d06649', 0, 'Configure the Auto Scaling Group to launch all instances in a single Availability Zone for simpler management.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fdf20197-60ee-4d1a-9446-aa304a399f94', '7bb72be4-0f44-454d-8eab-c2a584d06649', 1, 'Configure the Auto Scaling Group to span multiple Availability Zones (specifying multiple subnets in different AZs), so instance capacity is distributed and an AZ outage only affects a portion of the fleet.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b481998b-eb21-4d75-a0f9-fbb65911033b', '7bb72be4-0f44-454d-8eab-c2a584d06649', 2, 'Auto Scaling Groups are automatically multi-region by default and require no AZ configuration at all.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('69565d7a-9895-4450-9eb0-a6404bf15e57', '7bb72be4-0f44-454d-8eab-c2a584d06649', 3, 'Deploy a separate Auto Scaling Group per Availability Zone with no shared load balancer, and manually split traffic using Route 53 weighted routing.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('7bb72be4-0f44-454d-8eab-c2a584d06649', 'fdf20197-60ee-4d1a-9446-aa304a399f94', 'An Auto Scaling Group is configured to span multiple AZs by associating it with subnets in more than one AZ — the ASG then distributes launched instances across those AZs (and, with an ELB attached, the load balancer routes traffic to healthy instances regardless of which AZ they''re in). This means an entire AZ failure only removes a portion of capacity, and the ASG can launch replacement instances in the remaining healthy AZ(s) to restore desired capacity. ASGs are Regional constructs that span AZs within that Region — they are NOT automatically multi-Region, and a single-AZ configuration is exactly the anti-pattern that creates the failure risk described in the question. Splitting into separate per-AZ ASGs with manual Route 53 weighted routing is a real but far more operationally complex pattern than simply configuring one ASG across multiple subnets/AZs behind a single ELB.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('0fcda11d-d020-41a9-a5a0-d5b67380bcdc', 'd289b99e-2765-4074-8f63-9cb49323cc79', 8, 'A solutions architect is explaining S3''s "eleven nines" (99.999999999%) figure to a stakeholder who assumes it means the S3 service itself is guaranteed to be reachable 99.999999999% of the time. What is the correct clarification?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('54b34aac-3ab5-4485-82dd-0ad60fe808e4', '0fcda11d-d020-41a9-a5a0-d5b67380bcdc', 0, 'The stakeholder is correct — eleven nines refers to S3''s guaranteed uptime/availability for accessing objects.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('da17b8ce-dcfa-4de7-a4f9-cac9125fb0aa', '0fcda11d-d020-41a9-a5a0-d5b67380bcdc', 1, 'Eleven nines refers to S3''s DURABILITY — the extremely low statistical likelihood of actually losing a stored object over a given year — which is a distinct metric from AVAILABILITY (the percentage of time the service is reachable/operational), which S3 Standard specifies separately (e.g., 99.99%) via its own SLA.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('846ddb46-d9df-49bd-a3d9-e1da9948d206', '0fcda11d-d020-41a9-a5a0-d5b67380bcdc', 2, 'Eleven nines is a marketing figure with no formal technical definition or SLA backing it.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bba5051b-9a20-4229-81ab-7cf3f8c9546e', '0fcda11d-d020-41a9-a5a0-d5b67380bcdc', 3, 'Eleven nines refers to encryption strength, not a reliability or availability metric at all.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('0fcda11d-d020-41a9-a5a0-d5b67380bcdc', 'da17b8ce-dcfa-4de7-a4f9-cac9125fb0aa', 'Durability and availability are genuinely distinct S3 concepts and a frequently tested SAA distinction: durability (99.999999999%, "eleven nines") describes how unlikely S3 is to actually lose your data once stored — a function of how many copies are stored redundantly across multiple facilities. Availability describes what percentage of the time the service is actually operational and able to serve requests, which is a separate, lower figure specified in S3''s own published SLA (S3 Standard targets 99.99% availability) — a much more achievable number than eleven nines, and the two should never be conflated. It is a real, backed technical distinction with published SLAs, not just marketing, and has nothing to do with encryption.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('10481296-c07d-4df4-a25e-3d26e408136b', 'd289b99e-2765-4074-8f63-9cb49323cc79', 9, 'A company runs a primary application in the us-east-1 Region and wants to automatically fail over DNS resolution to a standby deployment in us-west-2 if the primary becomes unhealthy. Which Route 53 feature combination achieves this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b7133761-f50e-4c01-af81-1f8d9a6f144a', '10481296-c07d-4df4-a25e-3d26e408136b', 0, 'Route 53 Health Checks monitoring the primary endpoint, combined with a Failover routing policy that automatically directs DNS resolution to the secondary record when the primary is marked unhealthy.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b2c3c352-56c4-49d3-aab0-b60cedd51790', '10481296-c07d-4df4-a25e-3d26e408136b', 1, 'Simple routing policy, since it automatically detects unhealthy endpoints and reroutes traffic without any health check configuration.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('046a8ad5-d8a3-46b5-906d-7221dee155b1', '10481296-c07d-4df4-a25e-3d26e408136b', 2, 'Geolocation routing policy, since it is specifically designed for automatic health-based failover between Regions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8decfc1a-24a6-498b-a517-7144d5607aed', '10481296-c07d-4df4-a25e-3d26e408136b', 3, 'Route 53 cannot perform health-based failover; this requires a third-party DNS provider.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('10481296-c07d-4df4-a25e-3d26e408136b', 'b7133761-f50e-4c01-af81-1f8d9a6f144a', 'Route 53 Health Checks actively monitor an endpoint''s health (via HTTP/HTTPS/TCP checks), and the Failover routing policy uses that health check status to automatically route DNS queries to a designated primary record when healthy, and to the secondary record when the primary is marked unhealthy — exactly the automatic cross-region failover behavior described. Simple routing policy has no health-check awareness at all — it just returns a fixed set of values with no failover logic. Geolocation routing routes based on the requester''s geographic location, not endpoint health, and is not the failover-specific policy type. Route 53 absolutely supports this natively; no third-party DNS provider is required.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('a8ae9f66-8b04-467c-a2f0-e7dac8f93d97', 'd289b99e-2765-4074-8f63-9cb49323cc79', 10, 'A microservice occasionally experiences traffic spikes that overwhelm a downstream processing service, causing failed requests. The upstream and downstream services do not need to communicate synchronously. Which AWS service, inserted between them, would improve resilience by absorbing the spike and decoupling the two services?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6bcc341c-2121-41cc-b73d-23d9553d3389', 'a8ae9f66-8b04-467c-a2f0-e7dac8f93d97', 0, 'Amazon SQS (Simple Queue Service), which buffers messages between the two services so the downstream service processes them at its own sustainable rate, absorbing traffic spikes instead of dropping requests.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9c5a19ca-0330-498c-ace6-b4405d78b404', 'a8ae9f66-8b04-467c-a2f0-e7dac8f93d97', 1, 'Amazon CloudFront, since it is the standard way to decouple two backend microservices from each other.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b7061c35-e64a-449e-86ff-4a71e66944f5', 'a8ae9f66-8b04-467c-a2f0-e7dac8f93d97', 2, 'AWS Direct Connect, since it increases the downstream service''s processing capacity automatically.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c1bfbad2-fda8-4cfd-a50b-a0b1c7fdab29', 'a8ae9f66-8b04-467c-a2f0-e7dac8f93d97', 3, 'AWS Certificate Manager, since decoupling services requires TLS certificates issued between them.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('a8ae9f66-8b04-467c-a2f0-e7dac8f93d97', '6bcc341c-2121-41cc-b73d-23d9553d3389', 'SQS is the classic decoupling pattern for exactly this scenario: the upstream service pushes messages onto a queue instead of calling the downstream service directly, and the downstream service pulls and processes messages at whatever rate it can sustainably handle — a traffic spike fills the queue rather than overwhelming or crashing the downstream service, directly improving resilience through asynchronous buffering. CloudFront is a CDN for content delivery to end users, not a service-to-service decoupling mechanism. Direct Connect is a dedicated network link to AWS, unrelated to buffering or scaling. Certificate Manager issues/manages TLS certificates and has nothing to do with resilience against traffic spikes.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('5931453a-ca32-4c68-b536-132f9daf70da', 'd289b99e-2765-4074-8f63-9cb49323cc79', 11, 'A company needs point-in-time recovery for their RDS database, allowing restoration to any specific second within the last 7 days, in addition to daily backups. What RDS capability provides this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6e02a62a-4986-445d-a69d-0f6fe36bc71d', '5931453a-ca32-4c68-b536-132f9daf70da', 0, 'Manual DB snapshots taken once per day only allow restoration to the exact moment each snapshot was taken, not to an arbitrary second in between.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7b8bf638-4cea-430d-a5cd-476144afe197', '5931453a-ca32-4c68-b536-132f9daf70da', 1, 'RDS automated backups, which combine daily full snapshots with continuously captured transaction logs, enabling point-in-time restore to any specific second within the configured retention window (up to 35 days).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cba05928-7280-4977-895e-172315a70e68', '5931453a-ca32-4c68-b536-132f9daf70da', 2, 'RDS Read Replicas, since a read replica automatically provides point-in-time restore for the primary database.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9b6cf2a9-c8ac-4a6a-a11c-ab621c02cebc', '5931453a-ca32-4c68-b536-132f9daf70da', 3, 'RDS does not support point-in-time recovery; only full-database snapshot restoration is available.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('5931453a-ca32-4c68-b536-132f9daf70da', '7b8bf638-4cea-430d-a5cd-476144afe197', 'RDS automated backups are the feature that specifically enables point-in-time recovery: RDS takes a daily full snapshot during the configured backup window AND continuously captures transaction logs throughout the day, so a restore operation can replay logs up to (and stop at) any specific second within the retention window (configurable up to 35 days) — reconstructing the database exactly as it existed at that moment, not just at the last daily snapshot. Manual snapshots alone (option A''s premise) only restore to the exact snapshot moment, which is why automated backups'' continuous log capture is the actual answer. Read Replicas serve read traffic and provide no backup/point-in-time-restore capability of their own. RDS absolutely supports point-in-time recovery via automated backups — this is a core, frequently-tested RDS feature.');

-- ── Domain: Design High-Performing Architectures (24% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('4d0af331-9c20-4039-a3f2-7175db9b7ef8', 'd289b99e-2765-4074-8f63-9cb49323cc79', 12, 'A DynamoDB table uses a customer''s signup date as its partition key. As the table grows, most read/write traffic concentrates on the most recent dates, causing throttling on those specific partitions while older partitions sit nearly idle. What is the root cause and the general fix?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b73e070e-8787-4ee7-bfd6-1858af1023fd', '4d0af331-9c20-4039-a3f2-7175db9b7ef8', 0, 'The table simply needs more provisioned read/write capacity units overall; the partition key choice is unrelated to the throttling.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9a640304-6775-4f77-a1fc-5c0da8ef966c', '4d0af331-9c20-4039-a3f2-7175db9b7ef8', 1, 'This is a "hot partition" problem — the low-cardinality, time-clustered partition key causes traffic to concentrate on a small number of partitions; the fix is choosing a higher-cardinality partition key (or adding a random/calculated suffix) that spreads traffic more evenly across partitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c2a49b0e-1e53-4b2b-ab4b-1d21e495ff2d', '4d0af331-9c20-4039-a3f2-7175db9b7ef8', 2, 'DynamoDB does not use partitioning at all, so partition key choice cannot cause this symptom.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ad3d2d82-36cf-42db-9c20-839732fcf889', '4d0af331-9c20-4039-a3f2-7175db9b7ef8', 3, 'The fix is to switch to RDS, since DynamoDB fundamentally cannot handle any workload with uneven access patterns.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('4d0af331-9c20-4039-a3f2-7175db9b7ef8', '9a640304-6775-4f77-a1fc-5c0da8ef966c', 'DynamoDB distributes data (and the request throughput budget) across partitions based on the partition key''s hash — a partition key like "signup date" has low cardinality (relatively few distinct values) and is naturally time-clustered, so a large share of real-world traffic concentrates on whichever date-partitions are currently "hot" (most recent), overwhelming those specific partitions'' individual throughput allocation even if the table''s AGGREGATE provisioned capacity is more than sufficient overall — simply adding more total capacity doesn''t fix an uneven distribution problem. The standard fix is picking a higher-cardinality key (e.g., a user ID) or adding a calculated/random suffix to spread the same logical data across many more distinct partition key values, distributing load evenly. This is a well-known, frequently-tested DynamoDB design pattern, not a reason to abandon DynamoDB entirely.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('6d7d0081-65c5-4cf8-a122-7f96bdaeeef0', 'd289b99e-2765-4074-8f63-9cb49323cc79', 13, 'A company runs a real-time multiplayer gaming backend using UDP and TCP, requiring the lowest possible latency and consistent routing over the AWS global network for users worldwide — not caching of static content. Which service is the better fit: CloudFront or Global Accelerator?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8cc754e8-4fc1-4c70-91ef-b2d5d0c0c02e', '6d7d0081-65c5-4cf8-a122-7f96bdaeeef0', 0, 'CloudFront, since it is AWS''s only global-network-optimization service and works for any traffic type, including raw UDP/TCP.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f574dff5-f71e-4bef-afe7-60ee3d88758f', '6d7d0081-65c5-4cf8-a122-7f96bdaeeef0', 1, 'AWS Global Accelerator, which improves performance for non-HTTP TCP/UDP traffic (and HTTP too) by routing over the AWS global network to the optimal endpoint, without content caching being the point — a better fit than CloudFront, which is a caching CDN specifically for HTTP(S) content.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ad975fa3-5a6b-4ebb-9606-a4f3ffb4c174', '6d7d0081-65c5-4cf8-a122-7f96bdaeeef0', 2, 'Neither service supports UDP traffic under any configuration, so a third-party CDN is required.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c21a5f25-041b-4cf0-bd22-7b97996da0f8', '6d7d0081-65c5-4cf8-a122-7f96bdaeeef0', 3, 'CloudFront and Global Accelerator are the same service with two different names for billing purposes.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('6d7d0081-65c5-4cf8-a122-7f96bdaeeef0', 'f574dff5-f71e-4bef-afe7-60ee3d88758f', 'Global Accelerator is designed for exactly this profile: it improves performance for a broader range of traffic (TCP and UDP, not just HTTP/HTTPS) by using static anycast IP addresses and routing over the AWS global backbone network to the optimal, healthy endpoint — well suited to real-time gaming, VoIP, and IoT workloads where content caching is irrelevant and low, consistent latency for non-HTTP protocols is the actual goal. CloudFront is a content-delivery/caching CDN specifically for HTTP(S) content (web assets, video, APIs) — it does not accelerate raw UDP game traffic and caching isn''t applicable to a real-time multiplayer stream. The two are genuinely different services solving different problems, often used together in different parts of an architecture, not interchangeable or identical.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('e895d1ca-7ff1-4da4-a04b-d4cf3d66311a', 'd289b99e-2765-4074-8f63-9cb49323cc79', 14, 'A serverless application using AWS Lambda experiences database connection exhaustion on its RDS instance during traffic spikes, because each concurrent Lambda invocation opens its own new database connection and RDS has a hard connection limit. What AWS feature is designed specifically to solve this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('60ca10bf-dab9-4cdd-af54-41986fba56ec', 'e895d1ca-7ff1-4da4-a04b-d4cf3d66311a', 0, 'RDS Multi-AZ, since adding a standby replica increases the total number of available database connections.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f0e9e785-3c66-44db-bdac-dbbb8d1b90f2', 'e895d1ca-7ff1-4da4-a04b-d4cf3d66311a', 1, 'Amazon RDS Proxy, which sits between the application (Lambda) and the database, pooling and sharing a smaller number of actual database connections across many concurrent Lambda invocations.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ed368da0-020c-4bb4-8dea-e808b3193303', 'e895d1ca-7ff1-4da4-a04b-d4cf3d66311a', 2, 'AWS X-Ray, since tracing Lambda invocations automatically reduces the number of database connections opened.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dd63e70e-77d0-43b7-8c5a-f00eb0978541', 'e895d1ca-7ff1-4da4-a04b-d4cf3d66311a', 3, 'This is not solvable on AWS; Lambda cannot be used with RDS under any configuration.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('e895d1ca-7ff1-4da4-a04b-d4cf3d66311a', 'f0e9e785-3c66-44db-bdac-dbbb8d1b90f2', 'RDS Proxy is a fully managed database proxy purpose-built for exactly this Lambda-plus-RDS connection-exhaustion problem: it maintains a pool of actual database connections and multiplexes many concurrent Lambda invocations'' logical connections over that smaller, managed pool, instead of every invocation opening (and RDS having to accept) a brand-new physical connection — directly preventing the connection-limit exhaustion described. Multi-AZ adds a standby for failover/HA, not additional usable connection capacity during normal operation (the standby isn''t serving application traffic). X-Ray provides distributed tracing/observability and has no effect on connection pooling. Lambda-to-RDS is a well-supported, common architecture — RDS Proxy exists specifically because it''s common enough to need this dedicated solution.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('3bf81f0e-f6db-42b4-89d2-cd37ce406a0c', 'd289b99e-2765-4074-8f63-9cb49323cc79', 15, 'A company needs a shared file system that multiple EC2 instances across several Availability Zones can mount and read/write to concurrently, with POSIX file semantics (not object storage). Which AWS storage service fits this requirement?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3443cbd3-9da2-441f-af73-7809e1f15c68', '3bf81f0e-f6db-42b4-89d2-cd37ce406a0c', 0, 'Amazon EBS, since an EBS volume can be attached to and shared by multiple EC2 instances across multiple Availability Zones simultaneously.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('75ae38b0-b0d9-49f8-aa22-eb1e0ec0a35d', '3bf81f0e-f6db-42b4-89d2-cd37ce406a0c', 1, 'Amazon EFS (Elastic File System), a managed NFS file system that can be mounted concurrently by many EC2 instances across multiple AZs, providing POSIX-compliant shared file access.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e7180a27-da84-4d02-a4cb-7198a595c51d', '3bf81f0e-f6db-42b4-89d2-cd37ce406a0c', 2, 'Amazon S3, since S3 provides POSIX file system semantics identical to a traditional file server.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c061f803-132b-4772-b78b-b42a09d71ef4', '3bf81f0e-f6db-42b4-89d2-cd37ce406a0c', 3, 'This is not possible on AWS; each EC2 instance must always have entirely separate, non-shared storage.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('3bf81f0e-f6db-42b4-89d2-cd37ce406a0c', '75ae38b0-b0d9-49f8-aa22-eb1e0ec0a35d', 'EFS is a managed, scalable NFS (Network File System) that natively supports being mounted concurrently by thousands of EC2 instances across multiple Availability Zones, with standard POSIX file permissions and semantics — exactly matching this shared-file, cross-AZ, POSIX requirement. EBS volumes, in the standard (non-io2-Multi-Attach) case, attach to only a single EC2 instance at a time (io2 Multi-Attach is a narrow exception limited to instances in the same AZ, not the general case, and still isn''t a full shared file system with POSIX semantics across many instances) — EBS is fundamentally block storage for one instance, not concurrent shared file access. S3 is object storage accessed via HTTP API calls, not a mountable POSIX file system, despite tools existing to approximate file-system-like access on top of it.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('b85aa220-506c-489b-9282-43424e0bc66a', 'd289b99e-2765-4074-8f63-9cb49323cc79', 16, 'A DynamoDB-backed application requires microsecond (not just millisecond) read latency for its most frequently accessed items, significantly faster than DynamoDB alone typically provides. Which AWS service is purpose-built as an in-memory cache specifically for DynamoDB, requiring minimal application code changes?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6817d8b8-7a8f-4f6e-b1c1-b616871b216f', 'b85aa220-506c-489b-9282-43424e0bc66a', 0, 'Amazon ElastiCache, since it is a general-purpose cache with no meaningful difference from DAX for DynamoDB workloads.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1f9854b2-71dc-4637-95b4-9311f7d6350b', 'b85aa220-506c-489b-9282-43424e0bc66a', 1, 'DynamoDB Accelerator (DAX), a DynamoDB-specific, fully managed in-memory cache that sits directly in front of DynamoDB and is compatible with existing DynamoDB API calls with minimal code changes, reducing read latency to microseconds.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4f316c8d-158e-4d69-9990-7fa7a6248ad6', 'b85aa220-506c-489b-9282-43424e0bc66a', 2, 'AWS Global Accelerator, since it caches DynamoDB query results at edge locations worldwide.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6039057f-508c-4036-8fb7-a7339d5cff27', 'b85aa220-506c-489b-9282-43424e0bc66a', 3, 'DynamoDB has no compatible caching layer available; microsecond latency is not achievable on AWS.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('b85aa220-506c-489b-9282-43424e0bc66a', '1f9854b2-71dc-4637-95b4-9311f7d6350b', 'DAX (DynamoDB Accelerator) is a DynamoDB-specific, fully managed, write-through in-memory cache that sits directly in front of a DynamoDB table, is API-compatible with the DynamoDB SDK (requiring minimal code changes — often just swapping the client), and reduces read latency from single-digit milliseconds down to microseconds for cached items. ElastiCache (Redis/Memcached) is a general-purpose cache that CAN be used in front of any database including DynamoDB, but requires the application to explicitly manage cache read/write logic itself and is not purpose-built or API-compatible with DynamoDB the way DAX is — this is a genuine, testable distinction, not interchangeable tools. Global Accelerator improves network routing performance, it does not cache database query results at all.');

-- ── Domain: Design Cost-Optimized Architectures (20% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('2521a3e6-c5ae-4993-8d25-d1f9d7fd37bc', 'd289b99e-2765-4074-8f63-9cb49323cc79', 17, 'A company has S3 objects that are frequently accessed for the first 30 days after creation, rarely accessed for the next 60 days, and almost never accessed after that (but must be retained for compliance for 7 years). They want this transition automated without manual intervention. What is the correct approach?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ddd3c536-cffc-4b5d-94a4-6286293ae58c', '2521a3e6-c5ae-4993-8d25-d1f9d7fd37bc', 0, 'Manually move each object between storage classes on a fixed calendar reminder, since S3 cannot automate this.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4d4479a1-6c3e-4fba-839e-62babd2dc06d', '2521a3e6-c5ae-4993-8d25-d1f9d7fd37bc', 1, 'Configure an S3 Lifecycle policy that transitions objects to S3 Standard-IA after 30 days, then to S3 Glacier (or Glacier Deep Archive) after 90 days, and expires them after 7 years — all automatic based on object age.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2a6b8dd0-cbef-4db3-bd53-5085b910f1c3', '2521a3e6-c5ae-4993-8d25-d1f9d7fd37bc', 2, 'Store all objects permanently in S3 Standard, since automated tiering does not exist on S3 under any configuration.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d20560b7-5756-4b58-a81a-9652d92d8ef4', '2521a3e6-c5ae-4993-8d25-d1f9d7fd37bc', 3, 'Use CloudFront to automatically archive S3 objects older than 30 days.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('2521a3e6-c5ae-4993-8d25-d1f9d7fd37bc', '4d4479a1-6c3e-4fba-839e-62babd2dc06d', 'S3 Lifecycle policies are the built-in mechanism for exactly this predictable, age-based transition pattern — rules can be configured to automatically transition objects to a cheaper storage class after a defined number of days (Standard → Standard-IA → Glacier → Glacier Deep Archive), and to expire (delete) objects after a defined retention period, all without any manual intervention or custom automation code, based purely on object age since creation. This differs from S3 Intelligent-Tiering, which reacts to actual observed access patterns rather than following a fixed, predictable age-based schedule — for a KNOWN, predictable access pattern like this one (fixed 30/90-day thresholds), Lifecycle rules are the more direct, standard answer. CloudFront is a content delivery/caching service, not a storage-class management or archival tool.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('38475de3-101e-4b4c-8176-b31eacf2df11', 'd289b99e-2765-4074-8f63-9cb49323cc79', 18, 'A company suspects several of their EC2 instances are significantly over-provisioned (low CPU/memory utilization relative to instance size) but does not want to manually analyze CloudWatch metrics for every instance individually. Which AWS service analyzes historical utilization and provides specific instance right-sizing recommendations?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('88e8cdc9-6375-4ee0-9c1f-6dca218a56b8', '38475de3-101e-4b4c-8176-b31eacf2df11', 0, 'AWS Compute Optimizer, which analyzes historical CloudWatch utilization metrics and provides specific right-sizing recommendations (e.g., a smaller or differently-shaped instance type) per resource.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0fad9084-7a21-450f-8931-6f49d38fea5f', '38475de3-101e-4b4c-8176-b31eacf2df11', 1, 'AWS Direct Connect, since it automatically resizes EC2 instances based on network utilization.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d5a7def4-c4cb-45ac-a4b4-8527a3e6335e', '38475de3-101e-4b4c-8176-b31eacf2df11', 2, 'AWS Certificate Manager, since it includes a built-in instance-sizing analysis feature.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3c62f0e3-8e3b-48e0-9424-a8af4000ee4c', '38475de3-101e-4b4c-8176-b31eacf2df11', 3, 'This type of analysis is not available as an AWS-provided service and would require a third-party tool.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('38475de3-101e-4b4c-8176-b31eacf2df11', '88e8cdc9-6375-4ee0-9c1f-6dca218a56b8', 'AWS Compute Optimizer is purpose-built for this: it analyzes historical CloudWatch utilization data (CPU, memory with the CloudWatch agent installed, network, EBS) across EC2 instances, Auto Scaling Groups, EBS volumes, and Lambda functions, and produces specific, actionable recommendations — such as "this instance is over-provisioned, consider downsizing to instance type X" — at no additional cost, without requiring manual per-instance metric analysis. Direct Connect is a dedicated network connectivity service, unrelated to instance sizing. Certificate Manager issues/manages TLS certificates, also unrelated. This is a real, first-party AWS capability specifically because manually right-sizing a large fleet by hand doesn''t scale.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('f6fa1991-067d-4f57-876a-208a4031ee0e', 'd289b99e-2765-4074-8f63-9cb49323cc79', 19, 'Two EC2 instances that transfer large volumes of data between each other are currently deployed in two different Availability Zones within the same Region. What is the most direct way to reduce the data transfer cost between them, assuming no other constraint prevents it?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0f198fd1-7f7c-49d7-96f8-303f1de4b333', 'f6fa1991-067d-4f57-876a-208a4031ee0e', 0, 'Move both instances into the same Availability Zone (or use a placement group), since data transfer within the same AZ is priced lower than cross-AZ transfer within the same Region.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8b688509-6ad6-4eba-8217-6edf5c568cb5', 'f6fa1991-067d-4f57-876a-208a4031ee0e', 1, 'Data transfer cost is identical regardless of whether instances are in the same or different Availability Zones, so no change would reduce cost.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b77d1feb-cfda-4927-8a1e-ffcb4dc7c304', 'f6fa1991-067d-4f57-876a-208a4031ee0e', 2, 'Enable S3 Transfer Acceleration on both instances to reduce inter-instance data transfer cost.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5cb8049f-37d5-40de-80ce-6afb113046d1', 'f6fa1991-067d-4f57-876a-208a4031ee0e', 3, 'Switch both instances to use IPv6 addressing, which eliminates all data transfer charges between EC2 instances.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('f6fa1991-067d-4f57-876a-208a4031ee0e', '0f198fd1-7f7c-49d7-96f8-303f1de4b333', 'AWS data transfer pricing genuinely differs by scope: transfer between instances in the SAME Availability Zone (especially within the same placement group/using private IPs) is free or lowest-cost, transfer between different AZs within the same Region carries a per-GB charge in both directions, and transfer across Regions or to the internet costs more still. Consolidating tightly-coupled, high-volume-transfer instances into the same AZ (trading away some AZ-level redundancy for this specific pair, a real trade-off to weigh) is the direct cost lever here. S3 Transfer Acceleration is unrelated (it''s for accelerating uploads to S3 over long distances, not EC2-to-EC2 transfer). IPv6 vs IPv4 addressing does not itself change AWS''s data transfer pricing structure — that''s a routing/addressing choice, not a cost lever.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('00a604ff-00bf-4438-ba05-0037525c3513', 'd289b99e-2765-4074-8f63-9cb49323cc79', 20, 'A company allocated several Elastic IP addresses for EC2 instances that have since been terminated, leaving the Elastic IPs unattached. A cost review later flags unexpectedly high networking charges. What is the correct explanation?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('67c2a291-aafb-435e-bac0-cb7204d3d553', '00a604ff-00bf-4438-ba05-0037525c3513', 0, 'Elastic IP addresses are always free regardless of whether they are attached to a running instance, so this cannot be the cause.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f1f2aebf-91ad-47d1-8a3d-18f2adc6bf95', '00a604ff-00bf-4438-ba05-0037525c3513', 1, 'AWS charges an hourly rate for an Elastic IP address that is allocated but NOT attached to a running instance (or attached to a stopped instance) — an idle/unattached Elastic IP is a real, easy-to-overlook cost that a terminated-instance cleanup commonly misses.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6d2eaf2e-a9d2-4840-aae6-5f3c9910d33e', '00a604ff-00bf-4438-ba05-0037525c3513', 2, 'The charges must be unrelated to Elastic IPs, since AWS never bills for IP addresses under any circumstance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9ee492a5-239a-4e58-a081-307d7ecc1896', '00a604ff-00bf-4438-ba05-0037525c3513', 3, 'Elastic IPs only incur charges when attached to a RUNNING instance, and are always free when unattached.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('00a604ff-00bf-4438-ba05-0037525c3513', 'f1f2aebf-91ad-47d1-8a3d-18f2adc6bf95', 'This is a genuinely counter-intuitive, frequently-tested AWS billing detail, and exactly the opposite of what most people assume: an Elastic IP address attached to a RUNNING instance is free, but AWS charges an hourly rate for an Elastic IP that is allocated to an account but NOT attached to a running instance (including one attached to a STOPPED instance) — the logic being that idle IPv4 addresses are a scarce resource AWS wants to discourage hoarding. This is a classic real-world cost leak: terminating an instance without also releasing its associated Elastic IP leaves it silently accruing hourly charges indefinitely, exactly matching the scenario described. This is a real, current, documented AWS pricing behavior, not a misconception to dismiss.');
