-- ============================================================
-- AWS Certified Solutions Architect - Associate (SAA-C03) — Seed Data: Paper 7
-- New content, distinct topics from Papers 1-6 — no repeated scenarios.
-- Topic list checked directly against the actual question text of Papers
-- 1-6 (grepped from the files, not recalled from memory) before writing —
-- this discipline was adopted after Security+ Paper 4 was found to have
-- duplicated 3 of Paper 3's actual scenarios despite an earlier good-faith
-- topic check based on recollection alone.
-- Domain-weighted to the real SAA-C03 blueprint: Secure Architectures 30%
-- (6/20), Resilient Architectures 26% (5/20), High-Performing
-- Architectures 24% (5/20), Cost-Optimized Architectures 20% (4/20).
--
-- IDs were generated via scripts/fill-seed-uuids.mjs, which replaces every
-- distinct placeholder token with a fresh, real UUID (consistently across
-- every occurrence) — this file has already had that script run against
-- it; the UUIDs below are real. Cross-checked against every other seed
-- file in the repo for zero collisions before finalizing, plus the
-- distractor-language sanity scan and a manual re-read of every answer key
-- against its option text.
-- Run this AFTER docs/question-bank-schema.sql.
-- ============================================================

INSERT INTO question_papers (id, slug, title, exam_type, focus_tags, question_count, difficulty, is_premium, sort_order, time_limit_minutes)
VALUES ('7d059e9a-f045-47d6-87c0-db4b365cdf41', 'aws-saa-practice-7', 'AWS SAA-C03 Practice Paper 7', 'aws-saa', ARRAY['CloudTrail', 'IAM Access Analyzer', 'Network Firewall', 'Aurora Backtrack', 'DynamoDB PITR', 'Lambda@Edge', 'Enhanced Networking', 'Cost Anomaly Detection']::TEXT[], 20, 'standard', true, 7, 30);

-- ── Domain: Secure Architectures (30% — 6 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('dfd4d77e-a5ea-48d2-a4c5-2cbcac014636', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 1, 'A security team needs to answer "which specific IAM principal made this exact API call, from what source IP, and at what time" for a suspicious change discovered on a production resource — not what network traffic occurred, and not whether a resource''s configuration currently matches a compliance baseline. What AWS service is specifically built to answer this kind of "who did what, and when" question?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('71daeaed-c564-496d-b033-a01030d22665', 'dfd4d77e-a5ea-48d2-a4c5-2cbcac014636', 0, 'AWS CloudTrail — records a detailed, chronological log of API calls made across an AWS account (by users, roles, and AWS services), capturing WHO made a call (the calling identity), WHAT action was taken, WHEN it occurred, and the source IP it came from, making it the standard tool for exactly this kind of account-activity audit and forensic "who did this" investigation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('989fe5b9-3404-4c19-85ce-b977f7f2e67b', 'dfd4d77e-a5ea-48d2-a4c5-2cbcac014636', 1, 'VPC Flow Logs, since Flow Logs record which specific IAM principal made a given API call and at what time.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a82eaa6c-f098-4c1a-8a35-b414cd9b716c', 'dfd4d77e-a5ea-48d2-a4c5-2cbcac014636', 2, 'AWS Config, since Config''s core function is recording which IAM principal made a specific API call and from what source IP.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1947322d-2555-4e63-9e13-331005899438', 'dfd4d77e-a5ea-48d2-a4c5-2cbcac014636', 3, 'AWS provides no service capable of recording which specific IAM principal performed a given API action.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('dfd4d77e-a5ea-48d2-a4c5-2cbcac014636', '71daeaed-c564-496d-b033-a01030d22665', 'CloudTrail is specifically the API-activity audit log — every management-level (and optionally data-level) API call made in an account gets recorded with the calling identity, the specific action, the timestamp, the source IP, and the request/response details, making it the authoritative source for "who did this, when, and from where" investigations, directly supporting security incident investigation and compliance audit trails. This is a genuinely distinct service from VPC Flow Logs (covered in Paper 2, which records NETWORK-layer traffic metadata — source/destination IP and port, accepted/rejected — with no visibility into WHICH IAM principal or WHAT AWS API action was involved) and from AWS Config (covered in Paper 3, which tracks a resource''s CONFIGURATION STATE over time and compliance drift, not who specifically issued the API call that changed it) — three genuinely different, complementary logging/auditing services answering three different questions, a common and directly testable point of confusion. CloudTrail is a real, foundational, and near-universally-enabled AWS service specifically for this need, not a missing capability.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('175bdd3d-d6f7-4870-82db-11ffb567fa03', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 2, 'A security group allows inbound traffic on port 443 from a specific IP range, but has no explicit outbound rule permitting the RETURN traffic for those same connections. A Network ACL protecting the same subnet has an inbound rule allowing port 443, but no matching outbound rule for ephemeral return ports. Which of these two constructs will still allow the return traffic through automatically, and why?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b2a71802-1ba6-46be-9baa-e1b61a41bdad', '175bdd3d-d6f7-4870-82db-11ffb567fa03', 0, 'The security group is STATEFUL — once inbound traffic is allowed in, the security group automatically permits the corresponding RETURN traffic out, regardless of outbound rules, because it tracks the connection''s state. The NACL is STATELESS — it evaluates each direction of traffic independently against its own explicit rules, so an inbound-only rule with no matching outbound rule for the ephemeral return ports will actually BLOCK that return traffic, a genuinely common source of "why can''t my client reach this" troubleshooting confusion.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('58c745db-2c42-40ee-af74-db64960aaf6e', '175bdd3d-d6f7-4870-82db-11ffb567fa03', 1, 'The NACL is stateful and will automatically allow the return traffic, while the security group is stateless and requires an explicit matching outbound rule.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('99084370-ccd3-4010-8d36-200c2a6cdd02', '175bdd3d-d6f7-4870-82db-11ffb567fa03', 2, 'Both the security group and the NACL are fully stateful, so both will automatically allow the return traffic with no explicit outbound rule needed in either case.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b14a50e6-c497-4469-aea8-ece2ae437e82', '175bdd3d-d6f7-4870-82db-11ffb567fa03', 3, 'Neither construct will allow the return traffic under any circumstance without an explicit outbound rule configured on both.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('175bdd3d-d6f7-4870-82db-11ffb567fa03', 'b2a71802-1ba6-46be-9baa-e1b61a41bdad', 'This stateful-versus-stateless distinction is a foundational, frequently-tested nuance building on the instance-level-versus-subnet-level security group/NACL concept covered generally in Paper 1: a security group tracks the STATE of each connection, so once it permits an inbound request, it automatically recognizes and allows the corresponding response traffic flowing back out, with no separate outbound rule needed for that specific return traffic — this is why security groups are commonly configured with permissive or default outbound rules, since the INBOUND rule is usually doing the real access-control work for a request/response pattern. A NACL, by contrast, evaluates inbound and outbound traffic completely independently against its own separately configured rule sets, with no memory of "this outbound packet is a response to that inbound request" — meaning a NACL needs an explicit outbound rule permitting the ephemeral port range typically used for return traffic, or legitimate responses get silently blocked even though the original inbound request was allowed. This is a genuinely common, real operational gotcha (a security group correctly configured but a NACL missing the ephemeral-port outbound rule) and a frequently tested exam distinction specifically because the two constructs behave so differently despite superficially similar-sounding rule structures.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('49ed2656-c985-4992-ba51-27d09ed9a57c', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 3, 'A company wants to guarantee that objects uploaded to a specific S3 bucket are ALWAYS encrypted in transit — rejecting any request made over plain, unencrypted HTTP rather than HTTPS — enforced at the bucket level regardless of what any individual client happens to use. What bucket policy mechanism enforces this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('01144e51-ed3a-4246-9909-e669ef6a5523', '49ed2656-c985-4992-ba51-27d09ed9a57c', 0, 'A bucket policy with an explicit Deny statement using the `aws:SecureTransport` condition key set to `false` — this denies any S3 request that did NOT arrive over HTTPS, enforcing encryption-in-transit at the bucket level itself rather than depending on every individual client being correctly configured to use HTTPS on its own, closing the gap left by a purely client-side assumption.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1b619649-342b-4da8-98dc-90c3fd2b7cb8', '49ed2656-c985-4992-ba51-27d09ed9a57c', 1, 'Enabling SSE-KMS encryption at rest on the bucket, since encryption at rest automatically also enforces that all requests to the bucket arrive over HTTPS.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d46c4e3e-b34d-49f4-a490-0508041e1e90', '49ed2656-c985-4992-ba51-27d09ed9a57c', 2, 'S3 Object Lock, since Object Lock''s core function is rejecting any S3 request made over plain, unencrypted HTTP.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ae98dafe-10eb-44a2-b41e-a7bb970fe65b', '49ed2656-c985-4992-ba51-27d09ed9a57c', 3, 'S3 has no mechanism to enforce that requests to a bucket use HTTPS; this depends entirely and unavoidably on individual client configuration.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('49ed2656-c985-4992-ba51-27d09ed9a57c', '01144e51-ed3a-4246-9909-e669ef6a5523', 'The `aws:SecureTransport` condition key is specifically designed for exactly this enforcement need — a bucket policy statement that explicitly Denies any request where `aws:SecureTransport` evaluates to `false` (meaning the request arrived over plain HTTP rather than HTTPS) makes the encryption-in-transit requirement a SERVER-SIDE guarantee enforced by S3 itself, rather than an assumption resting entirely on every client being correctly configured to use HTTPS — directly connecting to the explicit-deny-always-wins policy evaluation principle covered in Paper 6, since this Deny applies regardless of what any identity-based policy might otherwise allow. This is meaningfully different from SSE-KMS or any at-rest encryption setting (covered generally in Paper 1) — encryption AT REST protects data sitting in S3''s storage, while `aws:SecureTransport` protects data specifically WHILE IN TRANSIT to/from the bucket, directly connecting to the data-states framework (at rest / in transit / in use) covered generally in Security+ content — enabling one does not automatically enforce the other, a genuinely important, testable distinction. S3 Object Lock (covered in Paper 5) is a WORM/retention compliance feature, entirely unrelated to transport encryption enforcement.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('7b07d85e-1b7e-4871-8b5a-887871500229', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 4, 'A company has grown organically for years with dozens of IAM roles and resource policies created by different teams, and worries that some S3 buckets or IAM roles may have unintentionally been left accessible from OUTSIDE the organization''s own AWS accounts, without anyone realizing it. What AWS service is purpose-built to automatically identify this kind of unintended external access across an account or organization?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4ff676a6-5832-4083-b80c-add6f1490a12', '7b07d85e-1b7e-4871-8b5a-887871500229', 0, 'IAM Access Analyzer — continuously analyzes resource policies (S3 bucket policies, IAM role trust policies, KMS key policies, and others) across an account or an entire AWS Organization, and specifically surfaces findings where a resource is accessible from OUTSIDE the account/organization''s trusted zone of accounts — directly catching unintentional external exposure that accumulated gradually across many individually-reasonable-looking policy changes, which is exactly the kind of gap that''s hard to spot by manually reviewing policies one at a time.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a54803d2-dcc4-4620-91b1-8cd5215fdba3', '7b07d85e-1b7e-4871-8b5a-887871500229', 1, 'AWS Trusted Advisor, since Trusted Advisor''s core function is analyzing every resource and IAM role policy for unintended external access across an organization.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d731c66c-ac36-41ef-bcf9-73530bf15f68', '7b07d85e-1b7e-4871-8b5a-887871500229', 2, 'GuardDuty, since GuardDuty specifically analyzes resource-based and IAM trust policies to identify unintended external access, rather than detecting active threats.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1050a5d6-5867-4155-9b1b-28dc7cdf5c97', '7b07d85e-1b7e-4871-8b5a-887871500229', 3, 'No AWS service can automatically identify unintentional external access across an account''s accumulated resource and IAM policies; this must always be done through manual review alone.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('7b07d85e-1b7e-4871-8b5a-887871500229', '4ff676a6-5832-4083-b80c-add6f1490a12', 'IAM Access Analyzer is specifically purpose-built for exactly this "did policy sprawl accidentally create external exposure" problem — using logic-based reasoning across an account''s or organization''s resource-based policies and IAM role trust policies, it identifies specific findings where a resource is reachable from outside the defined "zone of trust" (an account, or the whole organization), which is a genuinely hard thing to catch by manually eyeballing dozens or hundreds of individually-reasonable-looking policy statements one at a time, especially as they accumulate gradually over years across different teams. This is a meaningfully different service from GuardDuty (covered in Paper 4, which detects active, ANOMALOUS BEHAVIOR and threat indicators in account activity/network traffic, not static policy analysis) and from Trusted Advisor (covered in Paper 4, which gives broader cost/performance/security best-practice checks, not this specific deep policy-reachability analysis) — Access Analyzer''s specific value is proactively surfacing unintended access BEFORE it''s exploited, a real, purpose-built, and increasingly standard governance tool, not a manual-only problem.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('ec4c0f0f-9e18-406a-9daf-68a044d9b99a', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 5, 'A company wants a managed, stateful firewall that inspects and filters traffic AT THE VPC level — based on domain names, IP reputation, and custom rules — protecting an entire VPC''s traffic (including outbound traffic to the internet) more comprehensively than security groups or NACLs alone provide. What AWS service is purpose-built for this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('699551dd-894e-408c-9797-0feea3a37e6f', 'ec4c0f0f-9e18-406a-9daf-68a044d9b99a', 0, 'AWS Network Firewall — a managed, stateful network firewall deployed at the VPC level, supporting domain-name filtering, IP reputation lists, deep packet inspection, and custom rule groups (including intrusion prevention-style signature rules), providing more comprehensive traffic filtering — for traffic entering, leaving, or moving between subnets within a VPC — than security groups (instance-level, covered in Paper 1) or NACLs (subnet-level, covered in Paper 1) alone are designed to provide.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f504e332-49df-472a-a680-b9b6a4f47599', 'ec4c0f0f-9e18-406a-9daf-68a044d9b99a', 1, 'AWS WAF, since WAF is specifically designed to inspect and filter traffic at the VPC level based on domain names and IP reputation, rather than at the web-application-request layer.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('37506ab2-c9c2-4381-8202-cf9319399b82', 'ec4c0f0f-9e18-406a-9daf-68a044d9b99a', 2, 'A Gateway VPC Endpoint, since Gateway Endpoints provide stateful, VPC-wide traffic inspection based on domain names and IP reputation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bb5c7523-ac85-41cd-8b18-03973dd53b40', 'ec4c0f0f-9e18-406a-9daf-68a044d9b99a', 3, 'No managed AWS service exists for VPC-level stateful traffic inspection; only security groups and NACLs are available for any traffic filtering need.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('ec4c0f0f-9e18-406a-9daf-68a044d9b99a', '699551dd-894e-408c-9797-0feea3a37e6f', 'AWS Network Firewall fills a genuinely distinct layer in the defense-in-depth stack from security groups and NACLs: rather than simple IP/port/protocol allow-lists at the instance or subnet level, Network Firewall provides STATEFUL, deep packet inspection with support for domain-name-based filtering (e.g., blocking outbound traffic to a specific malicious or disallowed domain regardless of its changing underlying IP), IP reputation-based rules, and custom rule groups including signature-based detection more comparable to a traditional IDS/IPS (covered generally in Security+ content) but applied at the VPC network layer, and can inspect traffic moving between subnets or leaving the VPC entirely, not just what a single instance''s security group happens to allow. WAF (covered in Paper 2, and its rate-based rules in Paper 5) operates at a different layer entirely — inspecting HTTP(S) web APPLICATION requests specifically (SQL injection patterns, XSS, rate limits on web traffic) — not general VPC network traffic across all protocols, a genuinely important distinction between two often-confused "firewall-sounding" services. A Gateway VPC Endpoint (covered in Papers 1 and 6) provides private routing to S3/DynamoDB, entirely unrelated to traffic inspection — this is a real, standard, purpose-built AWS service, not a missing capability.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('b0e02984-89e5-481b-896e-808b295aa936', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 6, 'A company has three VPCs connected to each other using individual VPC Peering connections (A-to-B, B-to-C, but no direct A-to-C peering), and is surprised to discover that instances in VPC A cannot reach instances in VPC C at all, despite both being peered with VPC B. What VPC Peering limitation explains this, and how does it differ from Transit Gateway?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f57e669b-e057-45bf-84e9-3c214a3e630f', 'b0e02984-89e5-481b-896e-808b295aa936', 0, 'VPC Peering connections are NOT transitive — a peering connection only allows direct communication between the two SPECIFIC VPCs it directly connects, so VPC A being peered with B, and B being peered with C, does NOT automatically allow A to reach C; a direct A-to-C peering connection would need to be created separately. Transit Gateway (covered generally in Paper 5) solves this specific limitation by acting as a central hub all VPCs connect to once, enabling transitive routing between every attached VPC without needing a separate point-to-point connection for every single pair.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8c83cd27-24a8-4fa0-95ff-10edb059fb89', 'b0e02984-89e5-481b-896e-808b295aa936', 1, 'VPC Peering connections are fully transitive by default, so this scenario describes a misconfiguration rather than an inherent limitation of VPC Peering itself.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('72e7e6bb-8f34-477e-bd22-7eddf89532d7', 'b0e02984-89e5-481b-896e-808b295aa936', 2, 'Transit Gateway has the exact same non-transitive limitation as VPC Peering, with no meaningful difference in how the two handle multi-VPC connectivity.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('998cee05-8eec-412f-9067-cd1c2e1bfb2e', 'b0e02984-89e5-481b-896e-808b295aa936', 3, 'VPC Peering connections can never connect more than two VPCs under any circumstance, even with multiple separate peering connections configured.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('b0e02984-89e5-481b-896e-808b295aa936', 'f57e669b-e057-45bf-84e9-3c214a3e630f', 'VPC Peering''s non-transitive nature is a genuinely important, frequently-tested architectural limitation: each peering connection is a direct, point-to-point relationship between exactly two VPCs, and traffic cannot "hop through" an intermediate VPC''s peering relationships to reach a third VPC it isn''t directly peered with — meaning a company connecting N VPCs pairwise via peering alone would need a separate peering connection for every single pair (an increasingly unwieldy full-mesh topology as N grows), which is exactly the scaling problem Transit Gateway (covered generally in Paper 5, in the context of a company having grown from 3 to 30+ VPCs) was built to solve — every VPC instead connects ONCE to the central Transit Gateway hub, which then handles routing between every attached VPC without requiring that pairwise full-mesh of individual connections. This is a genuinely real, well-documented VPC Peering limitation (not a misconfiguration in this scenario, and not a limitation Transit Gateway shares) that directly explains why Transit Gateway exists as a distinct, purpose-built solution rather than simply being "VPC Peering with a different name" — a single VPC absolutely can have multiple separate peering connections to different other VPCs, contrary to the last distractor, it just cannot ROUTE THROUGH one to reach another transitively.');

-- ── Domain: Resilient Architectures (26% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('75732e68-3023-4215-957a-b8997f954672', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 7, 'A company has a regulatory requirement to maintain a second, independent copy of specific S3 data WITHIN the same AWS Region as the original (not in a different region), so that a scenario like an accidental deletion or an application bug affecting the original bucket doesn''t also affect the compliance copy. What S3 replication feature is purpose-built for this same-region use case?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8888e96b-9ba4-4e64-83dc-fc9a58c541f4', '75732e68-3023-4215-957a-b8997f954672', 0, 'Same-Region Replication (SRR) — automatically and asynchronously replicates objects to a DIFFERENT bucket within the SAME AWS Region, suited to needs like regulatory data-residency requirements that specifically prohibit moving data to another region, maintaining a separate compliance/audit copy, or aggregating data from multiple buckets — genuinely distinct from Cross-Region Replication (CRR, covered generally in Papers 1 and 5), which specifically moves data to a DIFFERENT region, typically for disaster recovery or global latency purposes.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d2dd4df0-3df8-4e30-b905-f6e6ae36f4d5', '75732e68-3023-4215-957a-b8997f954672', 1, 'Cross-Region Replication is the only S3 replication feature that exists; there is no way to replicate objects to a second bucket within the same Region.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('23b372f0-68fc-449f-a903-490c12726557', '75732e68-3023-4215-957a-b8997f954672', 2, 'S3 Object Lock, since Object Lock''s core function is replicating objects to a second bucket within the same AWS Region.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2e2efbba-ca81-4be0-bc7b-dcac92bfc170', '75732e68-3023-4215-957a-b8997f954672', 3, 'S3 Transfer Acceleration, since Transfer Acceleration is the feature that replicates objects to a separate bucket within the same Region.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('75732e68-3023-4215-957a-b8997f954672', '8888e96b-9ba4-4e64-83dc-fc9a58c541f4', 'Same-Region Replication addresses a genuinely distinct requirement from Cross-Region Replication (CRR) — while CRR (covered generally in Papers 1 and 5, typically for DR/global-latency purposes) specifically moves a copy of data OUT of the original region, SRR keeps the replicated copy within the SAME region, which matters directly for regulatory/data-residency requirements that specifically prohibit data from ever leaving a particular region even for backup/compliance purposes, or simply for maintaining a logically separate copy (different account, different bucket, potentially different storage class or lifecycle policy) protected from an accidental deletion or application bug affecting the original bucket specifically, without any cross-region data movement being a factor at all. Both SRR and CRR share the same underlying S3 replication mechanism (requiring versioning enabled on both buckets) but differ specifically in whether the destination bucket sits in the same or a different region — a genuinely real, purpose-built, and directly testable distinction, not a redundant restatement of CRR or an unrelated feature like Object Lock (covered in Paper 5, a WORM/retention feature) or Transfer Acceleration (covered in Paper 6, a transfer-speed feature).');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('882745fe-cbd7-4697-b057-530c2226f6ce', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 8, 'A company running a DynamoDB table wants the ability to restore that table to any specific second within the last 35 days, protecting against an accidental bulk delete or a bad application deployment that corrupted data — without needing to manually schedule or manage individual backup jobs. What DynamoDB feature provides this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7e41d8a4-28cf-4ef9-a857-b13532383917', '882745fe-cbd7-4697-b057-530c2226f6ce', 0, 'DynamoDB Point-in-Time Recovery (PITR) — once enabled, continuously backs up a table''s data automatically (with no manual backup scheduling required), enabling restoration to any specific second within a configurable retention window of up to 35 days, protecting against exactly this kind of accidental deletion or corruption without an administrator needing to manage individual backup jobs at all.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2f98eeea-f010-4fdb-866c-ffc6fcd7c4cf', '882745fe-cbd7-4697-b057-530c2226f6ce', 1, 'DynamoDB Global Tables, since Global Tables'' core function is continuously backing up a table for restoration to any specific second within the last 35 days.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('021d066d-6c2a-46e1-a9d7-72799604d256', '882745fe-cbd7-4697-b057-530c2226f6ce', 2, 'DynamoDB Accelerator (DAX), since DAX provides continuous point-in-time backup and restoration for a DynamoDB table.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e949d88e-def5-4541-a502-37792816d4e1', '882745fe-cbd7-4697-b057-530c2226f6ce', 3, 'DynamoDB provides no mechanism for restoring a table to a specific point in time; only full, manually-scheduled table backups are possible.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('882745fe-cbd7-4697-b057-530c2226f6ce', '7e41d8a4-28cf-4ef9-a857-b13532383917', 'DynamoDB PITR mirrors the same underlying "continuous, automatic, restore-to-any-second" concept as RDS PITR (covered in Paper 2), but as DynamoDB''s own equivalent feature for its NoSQL tables — once enabled, DynamoDB continuously captures the changes needed to restore to any specific second within the retention window (up to 35 days), entirely removing the need to manually schedule or manage discrete backup jobs the way traditional periodic backups require, and directly protecting against exactly the kind of accidental bulk-delete or bad-deployment-corruption scenario described. This is a genuinely distinct feature from DynamoDB Global Tables (covered in Paper 3, which provides MULTI-REGION active-active replication for low-latency global access and regional resilience, not point-in-time historical restoration) and from DAX (covered in Paper 2, a caching layer for read performance, entirely unrelated to backup/restore) — three separate DynamoDB features solving three separate problems, a common point of exam confusion given they''re all DynamoDB-specific capabilities. DynamoDB genuinely does support this kind of granular point-in-time restoration, not just full manual backups.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('867c0349-5df5-4c8f-b15b-2a893e163b64', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 9, 'A company running Aurora needs to quickly undo the effects of an accidental, erroneous bulk UPDATE statement that ran a few minutes ago, restoring the database to its state immediately before that statement — without going through a full point-in-time restore to an entirely new database instance, which would take considerably longer for a database of this size. What Aurora-specific feature is purpose-built for this fast, in-place "rewind" capability?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1a389030-719c-481b-9fb1-025e8a58541c', '867c0349-5df5-4c8f-b15b-2a893e163b64', 0, 'Aurora Backtrack — rewinds an Aurora cluster to a specific point in time IN PLACE, without creating an entirely new database instance and without the time cost of a full point-in-time restore-and-swap process, making it well suited to quickly undoing the effects of a recent, specific mistake (like an erroneous bulk update) when the target recovery point is close to the current time.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b6efb6e9-13ba-4de1-aeaa-33b584f7161e', '867c0349-5df5-4c8f-b15b-2a893e163b64', 1, 'Aurora Global Database, since Aurora Global Database''s core function is rewinding a cluster in place to undo a recent erroneous bulk update.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a3d15614-cecd-460b-b6d1-0027589c7dc0', '867c0349-5df5-4c8f-b15b-2a893e163b64', 2, 'Aurora Serverless v2, since Aurora Serverless v2 is specifically designed to rewind a database cluster to a point in time without creating a new instance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('acf7b579-3776-417c-b269-ad2b8f46dba2', '867c0349-5df5-4c8f-b15b-2a893e163b64', 3, 'Aurora has no feature for quickly undoing a recent erroneous change; a full point-in-time restore to a new instance is always the only available option.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('867c0349-5df5-4c8f-b15b-2a893e163b64', '1a389030-719c-481b-9fb1-025e8a58541c', 'Aurora Backtrack is specifically Aurora''s own distinct capability for this "fast, in-place rewind" need — rather than the standard point-in-time restore pattern (creating an entirely NEW database instance from a backup and a specific recovery point, then redirecting the application to it, which takes real time proportional to the database''s size), Backtrack rewinds the EXISTING cluster in place to an earlier point within a configured backtrack window, making it meaningfully faster specifically for undoing a recent, well-understood mistake like an erroneous bulk update, where the desired recovery point is close to the current time. This is a genuinely distinct feature from Aurora Global Database (covered in Paper 6, addressing cross-region replication and read latency, not point-in-time rewind) and from Aurora Serverless v2 (covered in Paper 5, addressing auto-scaling capacity, not backup/recovery) — three separate, purpose-built Aurora capabilities solving three separate problems, each a real, standard, and directly testable feature rather than Aurora lacking any fast-recovery option beyond a full restore.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('471bef5d-7e7b-4ce7-8a3f-03042c2717f1', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 10, 'A company has S3 Versioning enabled on a sensitive bucket, but is concerned that even with versioning on, a compromised or malicious IAM credential could still PERMANENTLY delete specific object versions outright, or even disable versioning itself, undermining the protection versioning is meant to provide. What additional S3 setting specifically requires MFA authentication for these particularly destructive actions?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('394ca793-845c-4424-a911-042ddd1a328f', '471bef5d-7e7b-4ce7-8a3f-03042c2717f1', 0, 'MFA Delete — an additional S3 Versioning setting that specifically requires the bucket owner''s MFA authentication to (1) permanently delete a specific object version, or (2) change the bucket''s versioning state (like suspending it) — adding a genuinely meaningful extra barrier against exactly the "compromised single credential" scenario, since a stolen access key alone is no longer sufficient to perform either of these particularly destructive actions without also having the physical/registered MFA device.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3d626c1d-bef6-464a-82ef-9b91c33e4624', '471bef5d-7e7b-4ce7-8a3f-03042c2717f1', 1, 'S3 Object Lock, since Object Lock is the setting that specifically requires MFA authentication to permanently delete a version or change versioning state.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d603932c-2743-438d-9d56-b5feb1f4ccb2', '471bef5d-7e7b-4ce7-8a3f-03042c2717f1', 2, 'S3 Same-Region Replication, since SRR requires MFA authentication before permanently deleting an object version or altering versioning state.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c677db75-5c7d-48d2-8917-07d076c70a9e', '471bef5d-7e7b-4ce7-8a3f-03042c2717f1', 3, 'S3 Versioning alone, with no additional setting, already fully prevents any possibility of permanent version deletion under any circumstance.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('471bef5d-7e7b-4ce7-8a3f-03042c2717f1', '394ca793-845c-4424-a911-042ddd1a328f', 'MFA Delete adds a genuinely meaningful additional layer specifically closing a real gap in standard S3 Versioning (covered generally in Paper 1) on its own: without MFA Delete, versioning protects against accidental overwrites/deletes (since a delete just adds a delete marker, and prior versions remain recoverable), but a sufficiently privileged credential can still issue a PERMANENT version-delete request or suspend versioning entirely, removing that protection going forward — exactly the scenario a compromised credential (whether stolen or from a malicious insider, covered in Security+ content) could exploit. Requiring MFA specifically for those two particularly destructive actions (permanent version deletion, and changing versioning state) means a stolen access key/secret alone is insufficient — the attacker would ALSO need the registered MFA device, directly connecting to the broader MFA concept covered generally elsewhere as an extra-factor defense. This is meaningfully different from S3 Object Lock (covered in Paper 5, a WORM-style retention/legal-hold feature enforcing IMMUTABILITY for a defined period regardless of credentials, a stronger but differently-mechanized protection) — MFA Delete specifically adds an authentication BARRIER to the destructive action, while Object Lock makes the action IMPOSSIBLE outright during the lock period; genuinely complementary, not identical, features.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('f4dbb689-dcb7-4199-a598-f2c0bd0f1de0', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 11, 'A company mounts a shared file system from multiple EC2 instances spread across three different Availability Zones, and needs that file system to remain fully available even if one entire Availability Zone becomes unreachable, with no manual failover step required. Without any additional configuration beyond a standard setup, does EFS provide this Multi-AZ resilience, and how does this compare to a standard EBS volume?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9476e5e4-89ac-456f-bfd8-9838c844fc9e', 'f4dbb689-dcb7-4199-a598-f2c0bd0f1de0', 0, 'Yes — EFS is inherently a REGIONAL, Multi-AZ service by design, automatically storing data redundantly across multiple Availability Zones within a Region with no additional Multi-AZ configuration required, so it remains available even if one entire AZ becomes unreachable; this is a fundamental architectural difference from a standard EBS volume (covered generally in Paper 1), which is inherently tied to a SINGLE specific Availability Zone and is not directly accessible from instances in a different AZ without a separate replication or snapshot-based mechanism.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('53f8a481-3193-4e3b-b1c5-d138372fd106', 'f4dbb689-dcb7-4199-a598-f2c0bd0f1de0', 1, 'No — EFS is inherently tied to a single Availability Zone by default, identically to a standard EBS volume, and requires explicit additional Multi-AZ configuration to survive an AZ outage.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c634b9b7-d9a0-468d-b7be-f6bee12dca09', 'f4dbb689-dcb7-4199-a598-f2c0bd0f1de0', 2, 'EFS and EBS provide identical Multi-AZ availability characteristics by default, with no architectural difference between the two services in this respect.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0d578bfc-f84b-4514-805e-291a65a894eb', 'f4dbb689-dcb7-4199-a598-f2c0bd0f1de0', 3, 'Neither EFS nor EBS can be made available across multiple Availability Zones under any circumstance, with or without additional configuration.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('f4dbb689-dcb7-4199-a598-f2c0bd0f1de0', '9476e5e4-89ac-456f-bfd8-9838c844fc9e', 'EFS''s Multi-AZ resilience is a fundamental, built-in architectural characteristic rather than an opt-in feature — as a REGIONAL file system (covered generally in Paper 2 for its multi-instance mountability, refined here specifically on its availability characteristic), EFS automatically stores file data redundantly across multiple Availability Zones within the chosen Region by default, meaning instances in any of those AZs can mount and access the same file system, and the loss of any single AZ does not make the file system as a whole unavailable — genuinely no additional Multi-AZ configuration step is required to get this characteristic, it''s inherent to the service. This stands in real, meaningful contrast to a standard EBS volume, which is inherently and permanently tied to a SINGLE specific Availability Zone at creation — an instance in a different AZ cannot directly attach to that same EBS volume at all, and achieving any cross-AZ EBS resilience requires a separate mechanism entirely (like a snapshot copied and restored to a volume in a different AZ, a different pattern from EFS''s native Multi-AZ design). This is a genuinely important, directly testable architectural distinction between the two storage services, not an equivalence between them.');

-- ── Domain: High-Performing Architectures (24% — 5 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('42b365e5-bccd-432d-9d2c-f1925d8a187f', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 12, 'A company is choosing between ElastiCache for Redis and ElastiCache for Memcached for a new caching layer. They specifically need built-in data persistence and replication for high availability, plus support for complex data structures beyond simple key-value pairs (like sorted sets). Which engine fits this need, and what does the other engine offer instead as its main advantage?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('810b1f41-0e75-4381-b5d7-536d4a875c1a', '42b365e5-bccd-432d-9d2c-f1925d8a187f', 0, 'ElastiCache for Redis supports data persistence (snapshotting to disk), built-in replication with automatic failover for high availability, and complex data structures (sorted sets, lists, hashes, not just simple key-value pairs) — directly fitting this requirement; Memcached, by contrast, offers no persistence or built-in replication, but its main advantage is simplicity and native multi-threaded architecture, which can provide higher raw throughput for simple, high-volume key-value caching workloads that don''t need Redis''s richer feature set.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3004ba31-a5c2-448e-a010-4ffe060f1941', '42b365e5-bccd-432d-9d2c-f1925d8a187f', 1, 'ElastiCache for Memcached is the engine that supports data persistence, built-in replication, and complex data structures, while Redis offers only simple key-value caching with no advanced features.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('42e23b76-baba-4319-b540-bc927f52c52b', '42b365e5-bccd-432d-9d2c-f1925d8a187f', 2, 'Redis and Memcached are functionally identical engines with no meaningful difference in persistence, replication, or data structure support.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8c7fb706-c662-4442-82a5-b5c1d8209f4a', '42b365e5-bccd-432d-9d2c-f1925d8a187f', 3, 'ElastiCache does not support any form of data persistence or replication under either engine; all cached data is always fully ephemeral with no exception.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('42b365e5-bccd-432d-9d2c-f1925d8a187f', '810b1f41-0e75-4381-b5d7-536d4a875c1a', 'This refines the general ElastiCache concept (covered in Paper 1) with the genuinely important, directly testable engine-choice distinction: Redis is the meaningfully more feature-rich engine — supporting persistence (so cached data can survive a restart rather than being purely ephemeral), built-in replication with automatic failover (a real high-availability characteristic, echoing the Multi-AZ automatic-failover pattern covered generally for RDS in Paper 6, applied here to the caching layer), and richer data structures beyond simple key-value pairs (sorted sets, useful for leaderboards; lists; hashes; pub/sub messaging) — which is exactly why Redis fits requirements needing HA and anything beyond the simplest caching pattern. Memcached, by design, deliberately trades away those richer features for simplicity and a multi-threaded architecture that can achieve higher raw throughput specifically for simple, high-volume key-value lookups with no persistence or replication requirement — a genuinely valid, different choice for a genuinely different, simpler workload profile, not an inferior option in every case. This is a real, standard, and frequently tested engine-selection decision, not a case of the two engines being interchangeable or ElastiCache lacking persistence/replication entirely.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('3df4885a-e92a-497b-b96f-f7709b154266', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 13, 'A company runs a network-intensive workload on EC2 (a high-throughput data processing application) and wants to minimize network latency, reduce jitter, and increase packets-per-second capacity beyond what the default virtualized network interface provides, without changing instance type. What EC2 networking feature specifically improves these characteristics?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fc8bfd38-6247-4dce-9786-bf68e59a67b6', '3df4885a-e92a-497b-b96f-f7709b154266', 0, 'Enhanced Networking — uses techniques like single root I/O virtualization (SR-IOV) to provide higher packets-per-second (PPS) performance, lower inter-instance latency, and lower jitter compared to traditional virtualized networking, by giving the instance more direct access to the underlying network hardware; most current-generation instance types support it by default or with a straightforward driver-level enablement, with no instance type CHANGE required.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bb76d5da-82e0-4ee6-be91-ea3cec19cd68', '3df4885a-e92a-497b-b96f-f7709b154266', 1, 'EBS optimization, since EBS-optimized instances are the feature that specifically reduces network latency, jitter, and increases packets-per-second capacity.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ac3f4cf7-e44f-4ca6-a701-39d678d2faba', '3df4885a-e92a-497b-b96f-f7709b154266', 2, 'Placement Groups, since Placement Groups are defined as the feature providing SR-IOV-based higher packets-per-second and lower jitter on a single instance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7053cae1-4e6a-440d-a67c-c2e4d09fa3f5', '3df4885a-e92a-497b-b96f-f7709b154266', 3, 'EC2 network performance is entirely fixed by instance type alone, with no feature able to improve packets-per-second, latency, or jitter beyond that baseline.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('3df4885a-e92a-497b-b96f-f7709b154266', 'fc8bfd38-6247-4dce-9786-bf68e59a67b6', 'Enhanced Networking specifically targets raw network performance characteristics — packets-per-second capacity, latency, and jitter — using SR-IOV to give the instance more direct, less-virtualization-overhead access to the underlying network hardware, distinct from EBS optimization (covered in Paper 6, which specifically provides dedicated bandwidth for STORAGE/EBS traffic, not general network packet performance) and from Placement Groups (covered in Paper 3 in a cluster/HPC context, which affects instance PLACEMENT relative to each other for lower inter-instance latency via physical proximity, a related but genuinely distinct mechanism from the network-interface-level improvement Enhanced Networking provides — the two are frequently used TOGETHER for the most latency-sensitive workloads, complementary rather than identical). Most current-generation instance types provide Enhanced Networking by default, meaningfully improving network performance without necessarily requiring an instance type change at all — this is a real, standard, and directly relevant feature for network-intensive workloads, not a fixed, unchangeable ceiling.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('4c87b3f8-c788-43fc-862c-c49f3f489cdb', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 14, 'A media application needs to let users stream and seek within very large video files stored in S3 (many gigabytes each) without downloading the entire file first — jumping directly to a specific timestamp should only require fetching the specific portion of the file needed for that segment. What S3 capability supports retrieving only a specific portion of a large object rather than the whole thing?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c1996282-d668-446d-8aa5-59010fecb8b5', '4c87b3f8-c788-43fc-862c-c49f3f489cdb', 0, 'S3 byte-range GET requests — an S3 GET request can specify a `Range` header requesting only a specific byte range of an object, rather than the object''s complete contents, allowing an application (or CloudFront in front of it) to fetch only the specific portion of a large file actually needed for a given moment (like a video seek), and enabling parallel downloading of different ranges simultaneously to improve overall throughput for very large objects.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d234e0b9-31b8-4620-a5fb-badbd1094dcd', '4c87b3f8-c788-43fc-862c-c49f3f489cdb', 1, 'S3 Multipart Upload, since Multipart Upload is the mechanism for retrieving only a specific byte range of an object during a GET request.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d27e0c76-4a5f-445c-b49f-ad8690d39a7c', '4c87b3f8-c788-43fc-862c-c49f3f489cdb', 2, 'S3 Select, since S3 Select''s core function is retrieving arbitrary byte ranges of unstructured video file content.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('110cb30f-d460-49aa-9e50-4366e757e1e7', '4c87b3f8-c788-43fc-862c-c49f3f489cdb', 3, 'S3 GET requests can only ever retrieve an object''s complete contents in full; there is no mechanism for requesting a partial byte range.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('4c87b3f8-c788-43fc-862c-c49f3f489cdb', 'c1996282-d668-446d-8aa5-59010fecb8b5', 'Byte-range GET requests directly address this exact "seek within a large file without downloading it all" need — by including a standard HTTP `Range` header on a GET request, a client requests only specific bytes of an object rather than its entirety, which is exactly the mechanism video streaming/seeking relies on (jumping to a timestamp translates to requesting the byte range corresponding to that portion of the encoded file) and is also useful more generally for downloading a single very large object faster by fetching multiple non-overlapping ranges IN PARALLEL rather than one single sequential download. This is a genuinely different mechanism and use case from S3 Multipart Upload (covered in Paper 3, which is specifically about UPLOADING a large object in parts, not retrieving portions of an existing one) and from S3 Select (covered in Paper 3, which retrieves specific ROWS/COLUMNS from a STRUCTURED file like CSV/JSON/Parquet via a query — not arbitrary byte ranges of an unstructured video file, a genuinely different retrieval mechanism entirely) — S3 GET requests genuinely do support this partial-range retrieval as a standard, real HTTP-level capability, not an all-or-nothing download model.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('315c73ff-3728-4809-a479-5053c3a0b228', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 15, 'A company wants to run lightweight custom logic directly at CloudFront''s edge locations — for example, rewriting a request''s URL path, inspecting/modifying headers, or generating a custom response — as close as possible to the end user, without that logic needing to reach all the way back to an origin server for every single request. What AWS capability supports running code directly at the CloudFront edge?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('472257ec-1353-4e95-8223-382bd489d939', '315c73ff-3728-4809-a479-5053c3a0b228', 0, 'Lambda@Edge — runs Lambda functions directly at CloudFront''s globally distributed edge locations, close to the end user, allowing custom logic (URL rewrites, header inspection/modification, generating a response without ever reaching the origin) to execute as part of the CloudFront request/response lifecycle, reducing latency compared to routing that same logic all the way back to an origin server for every request.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('75021d9b-aa66-44cd-a76c-60a1ffe3346c', '315c73ff-3728-4809-a479-5053c3a0b228', 1, 'AWS Step Functions, since Step Functions'' core function is running custom logic directly at CloudFront''s globally distributed edge locations.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2d8be0b5-78e9-45f1-bab0-7d56e378a4f0', '315c73ff-3728-4809-a479-5053c3a0b228', 2, 'Provisioned concurrency, since provisioned concurrency is the mechanism that executes custom logic at CloudFront edge locations rather than in a specific AWS Region.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5dbfb549-3677-40f9-b36d-fe4917e5e770', '315c73ff-3728-4809-a479-5053c3a0b228', 3, 'CloudFront has no capability to run custom code at the edge; all request/response logic must always execute at the origin server.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('315c73ff-3728-4809-a479-5053c3a0b228', '472257ec-1353-4e95-8223-382bd489d939', 'Lambda@Edge is specifically designed to run Lambda function code directly within CloudFront''s request/response lifecycle at edge locations around the world, meaningfully different from standard Lambda (covered generally elsewhere, including provisioned concurrency in Paper 6) which runs in a specific AWS Region rather than at globally distributed edge locations — this matters directly for latency-sensitive request-manipulation logic, since executing it at the edge (physically close to the requesting user) avoids the round-trip latency of sending that same logic all the way back to a centralized origin server or Regional Lambda function for every single request, particularly valuable for things like A/B testing logic, authentication token validation, or URL/header manipulation that needs to happen before a request even reaches the origin (or entirely without reaching it, for a fully edge-generated response). Step Functions (covered in Paper 4) orchestrates multi-step workflows, an entirely unrelated capability to edge code execution, and provisioned concurrency (covered in Paper 6) addresses cold-start latency for standard Regional Lambda invocations, not edge placement — this is a real, standard, and purpose-built capability, not a limitation CloudFront lacks.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('5d5d44c1-9b15-4e34-9783-83aa442eff6b', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 16, 'A global company has the same S3 dataset that needs to be accessed by application servers in multiple AWS Regions, and wants each region''s traffic automatically routed to the lowest-latency copy of the data, without the application itself needing separate, hardcoded logic to pick which regional bucket endpoint to use. What S3 feature is purpose-built for this kind of simplified, latency-based multi-region data access?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1fac2c18-6f98-4bcd-a7d2-83a10be26a23', '5d5d44c1-9b15-4e34-9783-83aa442eff6b', 0, 'S3 Multi-Region Access Points — provides a single, global endpoint that automatically routes requests to the lowest-latency replicated copy of the underlying data across multiple Regions (working together with S3 Cross-Region Replication to keep those copies in sync), so an application uses ONE endpoint without needing its own custom logic to determine which regional bucket to query for the best latency.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('35fbd1ce-b197-4ed3-8819-3debec3b6181', '5d5d44c1-9b15-4e34-9783-83aa442eff6b', 1, 'S3 Object Lock, since Object Lock''s core function is providing a single global endpoint that automatically routes requests to the lowest-latency regional copy of data.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4b91b925-a468-4c9e-ac4a-ab8c8c46991f', '5d5d44c1-9b15-4e34-9783-83aa442eff6b', 2, 'S3 Requester Pays, since Requester Pays is the feature that automatically routes multi-region requests to the lowest-latency replicated copy.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1259b54d-d385-4511-984c-87f8c3440b2d', '5d5d44c1-9b15-4e34-9783-83aa442eff6b', 3, 'S3 provides no mechanism for simplifying multi-region access to replicated data; applications must always hardcode their own region-selection logic across separate bucket endpoints.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('5d5d44c1-9b15-4e34-9783-83aa442eff6b', '1fac2c18-6f98-4bcd-a7d2-83a10be26a23', 'S3 Multi-Region Access Points specifically solve the "which of my several regional bucket copies should this request go to" problem by providing ONE global endpoint that AWS''s network automatically routes to the lowest-latency healthy replica for the requesting client — removing the need for an application to embed its own custom, hardcoded region-selection logic, and directly complementing S3 Cross-Region Replication (covered generally in Papers 1 and 5, and refined with Same-Region Replication earlier this paper), which is what actually keeps the underlying regional copies in sync in the first place; Multi-Region Access Points sit on top of that replication as the simplified, unified ACCESS layer. This is a genuinely different concern from S3 Object Lock (covered in Paper 5, a retention/compliance feature) and S3 Requester Pays (covered in Paper 3, a billing-attribution feature for public datasets) — this is a real, purpose-built S3 feature specifically for simplifying multi-region access patterns, not a gap requiring custom application-level routing logic to work around.');

-- ── Domain: Cost-Optimized Architectures (20% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('ec396760-29d1-404c-9b10-fbbd2b84d6f8', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 17, 'A company must retain certain compliance records for 10 years, accessed maybe once or twice in that entire period (e.g., for a regulatory audit), and wants the absolute lowest possible S3 storage cost for this data, accepting that retrieval may take up to several hours when genuinely needed. Which S3 storage class fits this specific profile, and what is its key trade-off compared to S3 Glacier (Flexible Retrieval)?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('12684af8-33e5-4b61-91c7-9a914f29750c', 'ec396760-29d1-404c-9b10-fbbd2b84d6f8', 0, 'S3 Glacier Deep Archive — the lowest-cost S3 storage class available, purpose-built for data retained for extended, multi-year periods (like this 10-year compliance retention requirement) with genuinely rare access; its trade-off compared to S3 Glacier (Flexible Retrieval) is retrieval TIME — Deep Archive retrieval standard tier typically takes around 12 hours, meaningfully longer than Glacier Flexible Retrieval''s standard retrieval (typically a few hours), a direct cost-versus-retrieval-speed trade-off appropriate specifically because this data is accessed so rarely that the extra retrieval wait time genuinely doesn''t matter in exchange for the lowest possible ongoing storage cost.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bc9ac82a-10a1-48ed-99e6-4e6bf4ef9871', 'ec396760-29d1-404c-9b10-fbbd2b84d6f8', 1, 'S3 Standard, since S3 Standard is specifically the lowest-cost storage class for data retained for 10 years with genuinely rare access.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('34f41bc3-f5d6-4b68-9557-bee9b83408c7', 'ec396760-29d1-404c-9b10-fbbd2b84d6f8', 2, 'S3 Intelligent-Tiering, since Intelligent-Tiering always provides a lower cost than every other S3 storage class for any access pattern, including 10-year archival retention.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c5782b86-e79a-4fd6-a471-40f7a6feb5b2', 'ec396760-29d1-404c-9b10-fbbd2b84d6f8', 3, 'S3 offers no storage class specifically optimized for long-term, rarely-accessed archival data; every storage class has identical cost regardless of access frequency or retention period.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('ec396760-29d1-404c-9b10-fbbd2b84d6f8', '12684af8-33e5-4b61-91c7-9a914f29750c', 'S3 Glacier Deep Archive is specifically S3''s lowest-cost storage tier, purpose-built for exactly this profile — long retention periods (years, not weeks/months) with genuinely rare, non-urgent access — directly connecting to the broader S3 lifecycle/storage-class-selection concepts covered generally across Papers 1 and 2 (IA, Glacier) and Paper 6 (Storage Class Analysis, One Zone-IA), extending that spectrum to its lowest-cost, slowest-retrieval extreme. The genuinely important, directly testable trade-off against standard Glacier (Flexible Retrieval) is specifically RETRIEVAL TIME, not availability or durability (both remain very high across all Glacier tiers) — Deep Archive''s standard retrieval tier takes meaningfully longer (roughly half a day) than Glacier Flexible Retrieval''s standard tier (a few hours), a trade worth making specifically when access is rare enough that the extra wait genuinely doesn''t matter, in exchange for the lowest possible ongoing storage cost over a long retention period. S3 Standard (covered generally in Paper 1) and S3 Intelligent-Tiering (also Paper 1, which optimizes for UNPREDICTABLE, changing access patterns, not this predictable "years of rare access" profile) are both meaningfully more expensive for genuinely long-term, rarely-touched archival data than Deep Archive specifically is.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('6f34cd01-73b4-41fb-8858-581760d03bbc', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 18, 'A finance team wants to be automatically alerted when AWS spending deviates from its normal, expected pattern in a statistically unusual way (e.g., a sudden spike in a specific service''s cost that doesn''t match typical usage trends) — rather than only finding out when a manually-configured fixed dollar threshold in AWS Budgets happens to be crossed, or having to notice it themselves while reviewing Cost Explorer. What AWS service is purpose-built for this kind of automatic, pattern-based spend-anomaly alerting?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0d9b04f5-a496-45f5-a904-731ea8c5409e', '6f34cd01-73b4-41fb-8858-581760d03bbc', 0, 'AWS Cost Anomaly Detection — uses machine learning to learn an account''s normal spending PATTERNS over time, and automatically alerts when spending deviates from that learned pattern in a statistically unusual way, catching unexpected cost spikes that might not yet have crossed any manually-configured fixed dollar threshold in AWS Budgets, and without requiring someone to notice the deviation themselves while manually reviewing Cost Explorer.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('104c249e-d85f-4a18-b2dd-cf26f4c3f267', '6f34cd01-73b4-41fb-8858-581760d03bbc', 1, 'AWS Compute Optimizer, since Compute Optimizer''s core function is using machine learning to detect statistically unusual AWS spending patterns and alert on them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2150c22a-6f53-44fa-a2cf-8b6d4acc0ceb', '6f34cd01-73b4-41fb-8858-581760d03bbc', 2, 'AWS Budgets Actions, since Budgets Actions is defined as automatically learning an account''s normal spending pattern using machine learning, independent of any manually-configured threshold.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('898dd6b5-0826-43be-bf03-b0916db4b47d', '6f34cd01-73b4-41fb-8858-581760d03bbc', 3, 'No AWS service exists to automatically detect statistically unusual spending patterns; only fixed, manually-configured dollar thresholds are available for any cost alerting.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('6f34cd01-73b4-41fb-8858-581760d03bbc', '0d9b04f5-a496-45f5-a904-731ea8c5409e', 'Cost Anomaly Detection fills a genuinely distinct gap from the fixed-threshold-based tools covered elsewhere — AWS Budgets (covered generally, with its Actions capability in Paper 5) requires a human to decide and configure a specific dollar threshold in advance, meaning a genuine anomaly that stays UNDER that threshold (but is still wildly unusual relative to normal patterns) would go completely unflagged, and Cost Explorer (covered generally, with forecasting in Paper 5) requires someone to actively notice the deviation while manually reviewing it. Cost Anomaly Detection instead uses machine learning to learn what NORMAL spending actually looks like for the specific account/service over time, and proactively alerts when actual spending deviates from that learned baseline in a statistically meaningful way — directly complementary to, not a replacement for, fixed-threshold Budgets alerts, since the two catch genuinely different kinds of cost problems (a known, hard limit being crossed, versus an unexpected pattern shift that might still be under any given fixed limit). AWS Compute Optimizer (covered in Paper 2) gives resource RIGHT-SIZING recommendations, an entirely different, unrelated function from spend-pattern anomaly alerting.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('6f644598-4c9b-4ef3-8682-0779aa44cedc', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 19, 'A company runs a large, flexible, interruption-tolerant Spot workload and wants AWS to prioritize actually FINDING enough available Spot capacity across multiple instance types/AZs to keep the fleet running with minimal interruption, even if that means paying a slightly higher price for some instances — rather than always choosing strictly the cheapest available Spot price, which might come from a pool more likely to be reclaimed soon. What Spot Fleet allocation strategy fits this priority?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f6ff262a-5b33-430a-9af6-fa17f321d152', '6f644598-4c9b-4ef3-8682-0779aa44cedc', 0, 'The `capacity-optimized` allocation strategy — launches instances from the Spot capacity pools AWS estimates have the deepest available capacity and therefore the LOWEST likelihood of near-term interruption, potentially at a slightly higher price than the strict cheapest option, directly prioritizing minimizing interruption over squeezing out the absolute lowest possible price — the inverse trade-off of the `lowest-price` allocation strategy, which instead always selects the cheapest available Spot pools regardless of that pool''s relative interruption risk.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8c661a6d-4d6b-453a-890d-93929bb42026', '6f644598-4c9b-4ef3-8682-0779aa44cedc', 1, 'The `lowest-price` allocation strategy, since `lowest-price` is defined as prioritizing the deepest available capacity pools with the lowest interruption likelihood over the cheapest price.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f8ff8d10-8d4f-4d7c-a52e-695a57691d77', '6f644598-4c9b-4ef3-8682-0779aa44cedc', 2, 'Spot Fleet has no configurable allocation strategy; every Spot Fleet always selects instances using an identical, fixed, non-configurable method.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e922c010-2311-46ac-b4ac-cfa305276aee', '6f644598-4c9b-4ef3-8682-0779aa44cedc', 3, 'Spot capacity availability and interruption likelihood are always identical and uniform across every instance type and Availability Zone, making any allocation strategy choice irrelevant.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('6f644598-4c9b-4ef3-8682-0779aa44cedc', 'f6ff262a-5b33-430a-9af6-fa17f321d152', 'This refines the general Spot Instance concept (covered in Paper 1, for fault-tolerant, flexible, interruptible batch workloads, and Fargate Spot in Paper 5) with a genuinely important, directly testable operational nuance: Spot Fleet''s `capacity-optimized` allocation strategy specifically prioritizes launching from the pools AWS''s own data indicates have the DEEPEST available capacity (and therefore statistically the lowest near-term interruption risk), even if that means a somewhat higher price than the absolute cheapest currently-available pool — a deliberate trade favoring FLEET STABILITY over squeezing out maximum savings, well suited to workloads where minimizing interruption frequency matters more than shaving the last few percent off cost. The `lowest-price` strategy makes the opposite trade — always chasing the cheapest available price across pools, accepting whatever interruption risk that specific pool happens to carry, which can mean MORE frequent interruptions if the cheapest pool also happens to be a shallower, more contested one. This is a real, configurable, and directly relevant choice for anyone actually running Spot Fleets at scale, not a fixed, non-configurable, one-size-fits-all mechanism, and Spot capacity/interruption risk genuinely does vary meaningfully across pools, instance types, and AZs — that variation is exactly what these allocation strategies exist to navigate.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('f68891b7-a680-41ef-97e6-76cbf7782a9d', '7d059e9a-f045-47d6-87c0-db4b365cdf41', 20, 'A company serves a popular set of static assets (images, videos) directly from an S3 bucket to end users worldwide, and is paying substantial S3 data transfer OUT charges as a result, since every single request currently reaches all the way back to the origin bucket. Without changing where the files are stored, what architectural change would meaningfully reduce these S3 data transfer costs?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f09e00c5-7280-474c-b36f-b0704d168032', 'f68891b7-a680-41ef-97e6-76cbf7782a9d', 0, 'Placing a CloudFront distribution in front of the S3 bucket as its origin — repeated requests for the same popular content get served from CloudFront''s cached copy at edge locations WITHOUT reaching back to the S3 origin at all for each request, meaningfully reducing the volume of data transferred directly OUT of S3 itself (since CloudFront-to-viewer data transfer is typically priced differently, and often more favorably at higher volumes, than direct S3-to-internet data transfer, and cache hits avoid hitting the origin at all).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('13a60447-7874-4f14-aebf-7af366bf2f76', 'f68891b7-a680-41ef-97e6-76cbf7782a9d', 1, 'Enabling S3 Requester Pays, since Requester Pays reduces the bucket owner''s own S3 data transfer OUT costs for a popular, publicly-served static asset bucket.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ae0d5d28-dda1-48a6-a179-ab20434d10ef', 'f68891b7-a680-41ef-97e6-76cbf7782a9d', 2, 'Enabling S3 Versioning, since S3 Versioning is the standard mechanism for reducing data transfer OUT costs for frequently-requested static content.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a43a5ffd-2a2b-4962-8431-d338a2169ca8', 'f68891b7-a680-41ef-97e6-76cbf7782a9d', 3, 'S3 data transfer OUT costs for popular, frequently-requested static content cannot be reduced by any architectural change; the cost is always fixed regardless of caching or content delivery configuration.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('f68891b7-a680-41ef-97e6-76cbf7782a9d', 'f09e00c5-7280-474c-b36f-b0704d168032', 'Placing CloudFront (covered generally in Paper 1) in front of an S3 origin directly reduces the volume of requests and data that actually reach the S3 bucket itself — once content is cached at a CloudFront edge location, subsequent requests for that same popular content from nearby users are served directly from the edge cache, never touching the S3 origin at all for those cache-hit requests, meaningfully reducing S3''s own data-transfer-out volume and cost specifically (a distinct benefit from Transfer Acceleration, covered in Paper 6, which speeds up the UPLOAD/transfer path TO S3 rather than reducing repeat-serving costs for popular download content, and from CloudFront origin groups, covered in Paper 6, which addresses origin failover rather than cost). This directly connects to why CloudFront is the standard, recommended pattern for serving popular static content broadly, rather than serving it directly from S3 to every individual requester regardless of how often the same content is requested repeatedly. S3 Requester Pays (covered in Paper 3) shifts data transfer cost to the REQUESTER rather than reducing the bucket owner''s cost for content THEY want to serve for free, and S3 Versioning (covered generally in Paper 1) is an entirely unrelated data-protection feature with no bearing on data transfer cost.');
