-- ============================================================
-- UPSC History Optional Paper II — PYQ & Model Answers (2023)
-- PYQ + Model Answer collection (28 questions)
-- ============================================================

-- ---------- Collection ----------
INSERT INTO pyq_collections (id, slug, subject, title, exam_paper, year, is_premium, question_count, sort_order)
VALUES ('3de2b668-b48f-4cee-a3de-a8f94c956ed3', 'upsc-history-optional-paper-2-pyq', 'history', 'UPSC History Optional Paper II — PYQ & Model Answers (2023)', 'paper-2', 2023, true, 28, 2);

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('21ac2fd7-a429-4c6f-8182-409d956ade1e', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 1, 'A', '1(a)', 10, 150, 'Critically examine the following statement: "Colonialism had a twisted logic of its own for commercialization. It emerges on analysis to have been often an artificial and forced process."');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('21ac2fd7-a429-4c6f-8182-409d956ade1e', 'Colonial commercialisation of Indian agriculture -- the shift from subsistence to market/export-oriented cropping (indigo, cotton, jute, opium, tea) under British rule -- is rightly described as artificial and forced rather than a natural market-driven development.

Evidence of a ''twisted logic'': cash-crop cultivation was frequently imposed through coercion rather than voluntary market response -- the indigo planters'' tinkathia system forced Champaran ryots to grow indigo on a fixed portion of their land regardless of profitability; opium cultivation in Bihar was enforced through a state monopoly with advances (peshgi) that trapped cultivators in debt; commercialisation served metropolitan industrial and revenue needs (raw material for British textile mills, opium revenue for the China trade) rather than Indian cultivators'' own economic interest. Revenue demands payable in cash forced peasants into the market even when crop prices were unfavourable, a ''forced'' commercialisation rather than one driven by genuine comparative advantage. This ''de-industrialisation cum commercialisation'' pattern impoverished cultivators while enriching colonial trade interests, confirming the artificial, coercive character the statement identifies.', 'The tinkathia system (Champaran) and the opium peshgi advance system are the two specific, concrete illustrations examiners expect for ''artificial and forced''; the answer should explicitly connect commercialisation''s purpose (serving metropolitan/revenue needs) to why it was forced rather than organic.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q1(a). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('92ffe226-cd02-4bc1-a4af-348b031917c3', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 2, 'A', '1(b)', 10, 150, 'Critically examine the following statement: "After 1857, the peasants emerged as the main force in agrarian movements."');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('92ffe226-cd02-4bc1-a4af-348b031917c3', 'The statement is broadly valid: while pre-1857 agrarian unrest (e.g. the Sanyasi-Fakir uprisings, tribal revolts) often had composite leadership including displaced zamindars and religious mendicants, the post-1857 period saw peasants themselves emerge as the primary, direct actors and leadership base of agrarian protest.

Evidence: the Indigo Revolt (1859-60) in Bengal was led directly by ryots (Digambar Biswas, Bishnu Biswas) refusing indigo cultivation, with limited zamindar or elite involvement, later immortalised in Dinabandhu Mitra''s Nil Darpan. The Pabna agrarian riots (1873) and Deccan Riots (1875) saw peasants directly organising against oppressive zamindars and moneylenders respectively, prompting protective legislation (Deccan Agriculturists'' Relief Act, 1879). Later, the Champaran Satyagraha (1917) and Kheda Satyagraha (1918), though drawing Gandhian leadership, mobilised around genuine peasant grievances with peasants as the mass base. This reflects growing peasant political consciousness and direct agency, distinct from earlier revolts often channelled through traditional elite or religious leadership.

Qualification: peasant movements still frequently required external leadership/legal articulation (Gandhi, local lawyers) even as peasants supplied the mass agency, so ''main force'' is accurate as mass base though not always as sole leadership.', 'Naming the Indigo Revolt, Pabna riots, Deccan Riots and Champaran/Kheda in chronological sequence with their specific peasant-agency features is expected; noting that external leadership often still mediated peasant movements is the nuance that elevates a ''critically examine'' response.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q1(b). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('b14b6889-6364-4165-b3a0-4b6afca548f2', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 3, 'A', '1(c)', 10, 150, 'Critically examine the following statement: "Awakened political consciousness of Indian masses, bound with dishonourable and cowardly insults of the British led to the movement of Non-Cooperation."');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('b14b6889-6364-4165-b3a0-4b6afca548f2', 'The Non-Cooperation Movement (1920-22) did emerge from a convergence of rising mass political consciousness and specific grievances widely perceived as humiliating British conduct, substantiating the statement, though it was not the sole cause.

Triggering ''insults'': the Jallianwala Bagh massacre (1919) and the subsequent Hunter Committee''s lenient treatment of General Dyer, combined with the Rowlatt Act''s repressive provisions, were widely experienced as a dishonourable assault on Indian dignity and due process. The Khilafat issue -- Britain''s harsh post-WWI treatment of the Ottoman Caliphate -- was seen by Indian Muslims as a betrayal of wartime promises, generating parallel outrage that Gandhi skilfully united with the broader nationalist movement (Khilafat-Non-Cooperation alliance).

Mass consciousness: WWI''s economic hardships (inflation, war-loan extraction, forced recruitment), returning soldiers'' exposure to wider world events, and Gandhi''s own mass-mobilisation techniques (satyagraha, symbolic swadeshi) converted elite-led politics into genuine mass movement for the first time.

Qualification: economic grievances (price rise, weaver distress) and long-building constitutional disappointment (Montagu-Chelmsford reforms seen as inadequate) were equally structural causes, so the ''insults'' framing captures the emotional trigger but not the full material and political causation.', 'Jallianwala Bagh/Rowlatt Act and the Khilafat betrayal are the two specific ''insults'' the question''s quote alludes to; a critical answer should add the underlying economic/constitutional causes to avoid reducing NCM''s origin to emotional humiliation alone.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q1(c). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('8ad589f5-20e9-4b6f-8a16-802402b24f13', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 4, 'A', '1(d)', 10, 150, 'Critically examine the following statement: "When Gandhiji launched the Civil Disobedience Movement he was ''desperately in search of an effective formula.''"');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('8ad589f5-20e9-4b6f-8a16-802402b24f13', 'This characterisation captures the genuinely experimental, searching quality behind Gandhi''s initiation of the Civil Disobedience Movement (1930), even if ''desperate'' somewhat understates his strategic deliberation.

Evidence of a search for formula: after the Non-Cooperation Movement''s abrupt withdrawal (1922, post-Chauri Chaura) and years of relative organisational quiet, Gandhi needed an issue that was simultaneously symbolically powerful, materially resonant with ordinary people, and legally provocative without inviting immediate mass violence. His choice of the salt tax -- affecting every Indian regardless of class, religion or region, and dramatizing British exploitation through a basic necessity -- reflected careful calculation after considering and rejecting other possible issues, resulting in the Dandi March (12 March-6 April 1930) as a highly deliberate, symbolically choreographed act rather than an improvised gesture.

Why ''desperate'' fits: the years of political drift after 1922, factional divisions (Swarajists vs no-changers), and pressure from younger radicals (Bhagat Singh''s revolutionary activity, Nehru''s more radical Independence resolution at the 1929 Lahore Congress) created urgency for Gandhi to demonstrate his method''s continued relevance.

Conclusion: the salt satyagraha was less a desperate improvisation than the calculated product of Gandhi''s search for a formula combining symbolic resonance and safe, controlled mass mobilisation.', 'The salt tax''s specific appeal (universal, apolitical, materially resonant necessity) and the political context (post-Chauri Chaura drift, Lahore Congress radicalism) are the key substantiating points; candidates should note that ''desperate'' overstates improvisation given how calculated the Dandi March actually was.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q1(d). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('4e024226-6603-4ce8-bd0c-b8efb34b20eb', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 5, 'A', '1(e)', 10, 150, 'Critically examine the following statement: "''If abdication of British responsibility at the time of transfer of power was callous, the speed with which it was done made it worse.''"');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('4e024226-6603-4ce8-bd0c-b8efb34b20eb', 'This statement is substantially supported by the historical record of the 1947 transfer of power, widely criticised for its rushed and inadequately prepared execution.

Evidence of callousness and speed: Mountbatten advanced the original June 1948 target date to August 1947 shortly after arriving as Viceroy, compressing an already complex partition process into about ten weeks. The Radcliffe Boundary Commission was given roughly five weeks to demarcate Punjab and Bengal''s boundaries, with Radcliffe himself having no prior knowledge of Indian geography or communities, producing boundaries announced only after independence, leaving millions of people uncertain of their nationality during the most dangerous period of migration. Inadequate security arrangements, absence of coordinated evacuation planning, and the abrupt withdrawal of British administrative and military machinery left law and order collapse largely unaddressed, contributing to the horrific communal violence and one of history''s largest forced migrations (estimates of up to 15 million displaced and up to 1-2 million deaths).

Counter-consideration: some historians argue deteriorating communal relations and British administrative exhaustion post-WWII made an early exit strategically necessary regardless of pace, and further delay might have deepened rather than reduced violence.

Conclusion: while some urgency was arguably unavoidable, the specific compression of the boundary-award and transition timeline is well-documented as having directly worsened the human cost of partition.', 'The compressed Radcliffe Line timeline (about five weeks, no prior India experience, boundaries announced after independence) is the single most important concrete fact examiners expect; a critical answer should weigh the counter-argument that a longer British presence might not have prevented violence either.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q1(e). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('ca5ff385-4c39-4fcd-94fc-f7d39f98bc95', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 6, 'A', '2(a)', 20, 350, 'The Carnatic Wars, the Anglo-Mysore Wars and the Anglo-Maratha Wars had virtually eliminated the French from the contest of supremacy in South India. Discuss.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('ca5ff385-4c39-4fcd-94fc-f7d39f98bc95', 'Introduction: The struggle for supremacy in 18th-century South India was fundamentally an Anglo-French colonial rivalry fought largely through Indian proxies and alliances; the Carnatic Wars directly, and the subsequent Anglo-Mysore and Anglo-Maratha Wars indirectly, eliminated France as a serious contender for Indian empire.

The Carnatic Wars (1746-1763): the First (1746-48) saw Dupleix capture Madras but it was restored by the Treaty of Aix-la-Chapelle; the Second (1749-54) saw Robert Clive''s defence of Arcot (1751) reverse French momentum under Dupleix''s protege Chanda Sahib, leading to Dupleix''s recall; the Third (1756-63), fought as part of the global Seven Years'' War, culminated in the decisive Battle of Wandiwash (1760) where Eyre Coote crushed the French army under Lally, followed by the fall of Pondicherry (1761) -- the Treaty of Paris (1763) restored French trading posts but stripped them of fortification/garrison rights, ending any French political-military ambition in India.

Anglo-Mysore Wars (1767-1799): though primarily an Anglo-Mysore contest, French support for Haidar Ali and Tipu Sultan (French officers training Mysore''s army, hopes of French naval and military intervention against the British) represented France''s last realistic hope of a comeback via an Indian ally; British victory in the Fourth Anglo-Mysore War (1799) and Tipu''s death eliminated this remaining French-aligned power base in the south.

Anglo-Maratha Wars (1775-1818): French officers (Benoit de Boigne, briefly) had trained some Maratha forces, offering another indirect avenue of French military influence; the definitive British victory in the Third Anglo-Maratha War (1817-18) removed the last major Indian power that could have hosted renewed French ambitions.

Conclusion: while the Carnatic Wars directly and decisively ended France''s own territorial-military presence in India, the subsequent Anglo-Mysore and Anglo-Maratha Wars eliminated the two remaining major Indian powers through which France might have re-entered the contest by proxy, together completing the total exclusion of France from any realistic claim to Indian supremacy by 1818.', 'The three war-series must each be linked explicitly to the French-elimination theme (direct defeat in the Carnatic Wars, French-aligned Indian allies eliminated in the later wars) rather than narrated as unconnected episodes; Wandiwash (1760) and the Treaty of Paris (1763) are the specific turning points examiners expect for the Carnatic Wars component.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q2(a). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('9a3ecdba-34ed-465b-9330-91d723d9c6b7', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 7, 'A', '2(b)', 20, 350, 'While introducing the Indian Councils Bill of 1861, the British thought that the only Government suitable for India ''is a despotism controlled from home''. Comment.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('9a3ecdba-34ed-465b-9330-91d723d9c6b7', 'Introduction: The Indian Councils Act of 1861, enacted in the aftermath of the 1857 revolt, reformed colonial legislative machinery while explicitly preserving an essentially autocratic structure -- accurately reflected in the quoted characterisation of British thinking at the time.

What the Act did: it enlarged the Governor-General''s Executive Council by adding a legislative wing with additional (Indian and European) non-official members (nominated, not elected) for legislative purposes only, restored legislative powers to the Bombay and Madras presidencies (removed after 1833), and permitted the Governor-General to issue emergency ordinances. Legislative Councils could discuss and vote on bills but could not raise financial matters or discuss executive policy without prior sanction, and the Viceroy retained a veto over all legislation, with ultimate authority resting in London (the Secretary of State for India and Parliament).

Why ''despotism controlled from home'' fits: Indian members were nominated (not elected) in small numbers, purely advisory rather than genuinely legislative in the sense of holding the executive accountable; no responsible government or ministerial accountability to the legislature existed; real power remained concentrated in the Viceroy''s Executive Council and, above it, the India Office in London -- meaning Indian ''representation'' was cosmetic, a controlled consultative mechanism rather than any devolution of sovereign authority. The post-1857 mood among British administrators (reflected in figures like Sir Charles Wood) explicitly favoured firm, centralised control after the shock of the revolt, precisely the ''despotism'' the quote describes, while London''s ultimate oversight supplied the ''controlled from home'' element.

Significance: the 1861 Act nonetheless marked the beginning of gradual, token Indian association with legislation -- a a precedent later expanded (however slowly) by the 1892, 1909 and 1919 reforms -- even though its own immediate character remained firmly autocratic and metropolitan-controlled, exactly as British policymakers themselves openly described it.', 'Candidates must explain the Act''s actual mechanics (nominated non-official members, no budget/policy discussion rights, Viceroy''s veto, Secretary of State''s ultimate authority) to substantiate ''despotism controlled from home'' concretely, rather than treating the quote as a rhetorical flourish; noting its role as a first, however limited, precedent for later reforms shows balanced historical judgment.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q2(b). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('9f981c98-c77a-4eab-be54-60a620b969f9', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 8, 'A', '2(c)', 10, 150, '''The root of the whole question behind the Indigo Revolt is the struggle to make the raiyats grow indigo plants without paying them the price of it''. Analyse.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('9f981c98-c77a-4eab-be54-60a620b969f9', 'The Indigo Revolt (1859-60) in Bengal arose from the coercive tinkathia system, under which European planters forced raiyats to cultivate indigo on a fixed portion (typically one-twentieth, or three kathas per bigha) of their best land, at prices far below the cost of cultivation or market value of alternative crops (rice), effectively extracting indigo without adequate compensation.

Mechanisms of coercion: advances (dadan) given to peasants trapped them in perpetual debt bondage, since the advance was rarely enough to cover real cultivation costs and had to be repaid through further indigo cultivation, creating an inescapable cycle; planters used private enforcement (lathiyals, illegal detention, crop destruction of rival food crops) rather than free contractual agreement; and indigo, being far less profitable than rice for the actual cultivator, meant peasants resisted precisely because the price paid did not reflect the land''s true value or the labour invested.

The 1859-60 revolt saw peasants (led by figures like Digambar and Bishnu Biswas) simply refuse further cultivation, supported by some sympathetic zamindars, missionaries and the vernacular press (Hindoo Patriot, Nil Darpan), leading to the Indigo Commission (1860) which confirmed the exploitative character of the system and effectively ended forced indigo cultivation in Bengal.', 'The tinkathia land-allocation mechanism and the dadan advance-debt trap are the two specific structural features that substantiate ''without paying them the price of it''; naming the Indigo Commission''s outcome shows the analysis extends to resolution, not just grievance.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q2(c). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('07b88007-5528-4bfd-9869-6d6cc055725a', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 9, 'A', '3(a)', 20, 350, 'Do you agree that ''the decline of traditional Indian artisan production was a fact, sad but inevitable''? Discuss.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('07b88007-5528-4bfd-9869-6d6cc055725a', 'Introduction: The decline of India''s traditional handicraft/artisan production (especially textiles) under colonial rule is a well-documented fact; whether it was ''inevitable'' rather than a consequence of specific, avoidable colonial policy choices is the more contested part of the statement.

Evidence of decline: Indian handloom textile exports, once dominant in world trade (Bengal muslin, Dacca cotton), collapsed through the 19th century as British machine-made textiles from Manchester and Lancashire flooded Indian markets, aided by discriminatory tariff policy (heavy import duties on Indian goods entering Britain versus minimal or no duties on British goods entering India), the deliberate ''deindustrialisation'' associated with colonial policy documented by economic historians, and railway expansion that ironically enabled cheap British goods to penetrate even remote Indian markets that traditional artisans had previously served without competition.

Was it inevitable? Arguments for inevitability: the Industrial Revolution''s productivity advantages (mechanised spinning/weaving) meant handicraft production faced a genuine, technology-driven competitive disadvantage that any pre-industrial producer, colonised or not, would eventually have confronted as global industrialisation proceeded.

Arguments against pure inevitability: the SPEED and completeness of decline, and specifically the discriminatory tariff structure (protecting British manufacturers in the domestic Indian market rather than allowing fair competition, or supporting Indian industrial modernisation instead), reflected deliberate colonial policy choices serving metropolitan industrial interests -- not a neutral market outcome. Nationalist economic critics (Dadabhai Naoroji, R.C. Dutt) argued a genuinely independent or differently-configured colonial policy could have supported Indian industrial transition (as Japan achieved through protective, state-guided industrialisation in the same era) rather than simply de-industrialising without compensating industrial development.

Conclusion: the decline itself was indeed a fact, and some degree of disruption from global industrial competition was likely unavoidable; however, calling it simply ''inevitable'' understates the extent to which specific, non-neutral colonial tariff and trade policy actively accelerated and shaped the decline in ways that a different (or independent) policy regime, as the Japanese comparison suggests, might have substantially mitigated.', 'A strong answer must take an explicit position on ''inevitable'' rather than only describing the decline -- the discriminatory tariff structure and the Japan comparison (nationalist economic critique) are the specific points that distinguish agreement-with-qualification from simple description.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q3(a). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('7406600e-1433-4c19-952c-3e457131c77a', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 10, 'A', '3(b)', 20, 350, 'The historical significance of tribal and peasant uprisings in India ''lies in that they established strong and valuable traditions of resistance to British rule''. Discuss.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('7406600e-1433-4c19-952c-3e457131c77a', 'Introduction: Numerous tribal and peasant uprisings across colonial India, though largely localised, defeated and often pre-dating organised nationalist politics, are historically significant primarily as early, sustained demonstrations that colonial authority could be actively resisted -- a tradition later movements consciously or structurally drew upon.

Key uprisings: the Santhal Hul (1855-56) saw the Santhal tribes of Bihar-Bengal rise against zamindars, moneylenders and colonial revenue administration under Sidhu and Kanhu Murmu, demonstrating organised mass tribal resistance predating 1857. The Munda Ulgulan (1899-1900) under Birsa Munda combined religious revivalism with resistance to land alienation and the exploitative beth-begari (forced labour) system, forcing the colonial state to enact the Chotanagpur Tenancy Act (1908) protecting tribal land rights. The Kol uprising (1831-32) and various Bhil revolts similarly resisted the erosion of traditional tribal autonomy and land rights under expanding colonial administration. Among peasants, the Indigo Revolt (1859-60), Pabna riots (1873) and Deccan Riots (1875) established a template of organised, if localised, agrarian resistance to specific exploitative structures (indigo planters, zamindars, moneylenders).

Significance as a ''tradition of resistance'': these uprisings, though militarily defeated and often brutally suppressed, demonstrated that colonial and associated exploitative authority was neither natural nor unchallengeable, kept alive local memories and repertoires of collective resistance (petitioning, boycott, armed uprising, millenarian mobilisation), and in several cases forced genuine protective legislative concessions (Chotanagpur Tenancy Act, Deccan Agriculturists'' Relief Act), establishing that organised pressure could extract state response. They also provided symbolic and, in some historiographical readings, organisational inspiration for later nationalist and left agrarian movements (the Tebhaga and Telangana movements of the 1940s drew on similar grievance structures and, in some regions, folk memory of earlier revolts).

Conclusion: while these uprisings did not by themselves achieve independence or permanently resolve the underlying exploitation, their historical significance lies precisely in demonstrating, well before organised nationalist politics matured, that resistance to British rule and its local intermediaries was possible, sustained and occasionally successful in extracting concessions -- establishing a genuine, valuable tradition later movements could draw upon.', 'The Santhal Hul, Munda Ulgulan (Birsa Munda) and the specific protective legislation each forced (Chotanagpur Tenancy Act) are the essential named examples; the answer should explicitly connect these to the ''tradition'' claim by noting their influence on or resemblance to later 20th-century agrarian movements.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q3(b). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('1f022442-f7fa-4846-b0f5-06c889ce0e11', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 11, 'A', '3(c)', 10, 150, 'To accomplish the aims of education, ''political propaganda and formation as well as propagation of nationalist ideology'', the press became the chief instrument. Comment.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('1f022442-f7fa-4846-b0f5-06c889ce0e11', 'The vernacular and English-language Indian press of the 19th-20th centuries served simultaneously as an educational, propagandist and nationalist-ideological instrument, making it central to the growth of Indian political consciousness.

Educational role: newspapers and journals (Raja Ram Mohan Roy''s Sambad Kaumudi, later many vernacular papers) spread literacy-linked awareness of social reform, scientific ideas and civic issues to readerships beyond formal educational institutions.

Political propaganda and nationalist ideology: papers like Kesari and Maratha (Tilak), Amrita Bazar Patrika, Hindoo Patriot, Young India and Harijan (Gandhi), and Bengalee (Surendranath Banerjee) directly propagated nationalist critique of colonial policy, publicised movements (Swadeshi, Non-Cooperation, Civil Disobedience), built ideological consensus around self-rule, and mobilised public opinion during crises (Bengal Partition, Jallianwala Bagh). Colonial responses (Vernacular Press Act, 1878; Press Act, 1910) confirm how seriously the state regarded the press''s ideological power, restricting it precisely because it was so effective an instrument of nationalist formation and propagation.', 'Naming specific papers tied to specific leaders/movements (Kesari-Tilak, Young India-Gandhi) and the colonial repressive legislation (Vernacular Press Act 1878) as evidence of the press''s perceived power together substantiate the ''chief instrument'' claim concretely.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q3(c). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('92ab5490-a0bb-4bd0-aea2-472cc70009c2', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 12, 'A', '4(a)', 20, 350, 'The universalist perspective of socio-religious reform movements was not a ''purely philosophic'' concern; it strongly influenced the political and social outlook of the time. Examine.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('92ab5490-a0bb-4bd0-aea2-472cc70009c2', 'Introduction: 19th-century Indian socio-religious reform movements (Brahmo Samaj, Arya Samaj, Prarthana Samaj, Aligarh movement, and others) articulated universalist philosophical claims (monotheism, rational religion, human equality) that were never merely abstract theology -- they directly shaped contemporary political consciousness and social reform practice.

Universalist tenets and their practical/political translation: Raja Ram Mohan Roy''s Brahmo Samaj (1828) advocated monotheistic, rational religion transcending sectarian ritualism, but this philosophical universalism directly underpinned his practical campaigns against sati (leading to its 1829 abolition), for women''s property rights, and against caste rigidity -- linking abstract theological reform to concrete social legislation and early proto-nationalist civic engagement with colonial authority. The Arya Samaj (Dayananda Saraswati, 1875), despite its more assertively Hindu-revivalist ''back to the Vedas'' universalism, translated this into practical shuddhi (reconversion) campaigns, opposition to caste discrimination in some respects, promotion of women''s and Dalit education (DAV institutions), and later fed directly into cultural-nationalist political mobilisation in Punjab and North India. Sir Syed Ahmed Khan''s Aligarh movement, while communally particular in one sense, articulated a universalist rationalist engagement with modern science and education that shaped Muslim political outlook toward constitutional, education-focused engagement with colonial modernity.

Political outlook impact: these movements collectively generated a generation of Indian leadership (many early Indian National Congress leaders emerged from Brahmo/reformist backgrounds) that linked religious-philosophical reform to demands for civic and political rights, self-respect, and eventually self-rule; they also shaped the emerging discourse of a reformed, ''modern'' Indian civilisational identity capable of political self-assertion vis-a-vis colonial claims of Indian civilisational inferiority.

Social outlook impact: campaigns against sati, child marriage, purdah, and for widow remarriage and women''s/lower-caste education directly reshaped social norms and legislation (Widow Remarriage Act 1856, Age of Consent Act 1891), demonstrating the movements'' philosophic universalism had immediate, measurable social consequences rather than remaining confined to theological debate.

Conclusion: far from a ''purely philosophic'' concern, the universalist perspective of socio-religious reform directly generated concrete social legislation, educational institution-building, and a politically consequential reformist leadership class, confirming its substantial influence on both the social and political outlook of the era.', 'The answer must move beyond describing each movement''s theology to explicitly tracing the causal link to concrete political/social outcomes (legislation, leadership formation, institution-building) for at least two or three movements -- Brahmo Samaj''s sati-abolition link and Arya Samaj''s DAV-education/shuddhi translation are the specific expected anchors.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q4(a). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('91eb5759-0118-4796-b880-a86269bbb25b', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 13, 'A', '4(b)', 20, 350, 'The Congress Socialist Party agenda was not to cut off from the Congress, but ''intended to give the Congress and the national movement a socialist direction''. Analyse.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('91eb5759-0118-4796-b880-a86269bbb25b', 'Introduction: The Congress Socialist Party (CSP), founded in 1934 by Acharya Narendra Deva, Jayaprakash Narayan, Minoo Masani and others, operated explicitly as an organised left-wing bloc WITHIN the Indian National Congress rather than as a separate party competing against it, consistent with the statement''s characterisation of its agenda.

Evidence supporting the statement: the CSP''s founding constitution explicitly defined it as a group working inside Congress to influence its ideology and programme toward socialism, not to split the nationalist movement -- a strategic choice reflecting the CSP leadership''s assessment that the Congress remained the only organisation capable of mass anti-imperialist mobilisation, and that a parallel or breakaway socialist party would fragment and weaken the nationalist movement rather than strengthen socialist influence. CSP members held formal Congress membership and worked through Congress organisational structures (provincial committees, the AICC) to push resolutions incorporating socio-economic radicalism -- most visibly the Karachi Resolution (1931, prior to CSP''s formal founding but reflecting the same broader current) on Fundamental Rights and economic policy, and continued pressure that contributed to Congress''s increasingly explicit commitment to land reform, nationalisation of key industries and labour rights in later programmatic statements (e.g. the 1936 Faizpur Congress''s agrarian programme, influenced by Nehru''s and the CSP''s socialist advocacy).

Tensions and limits: the relationship was not without friction -- Gandhi and more conservative Congress leaders were often uncomfortable with CSP''s Marxist-influenced rhetoric and class-struggle framing, and the CSP itself contained internal debate about how far to compromise with Gandhian methods versus pursue a more independent Marxist line; some CSP members eventually left to form more explicitly Marxist formations (contributing indirectly to post-independence socialist party formation), showing the ''stay inside and influence'' strategy had real strains even though it remained the CSP''s formal, stated agenda throughout the pre-independence period.

Conclusion: the CSP''s agenda was accurately one of ideological pressure and programmatic influence from within a unified national movement rather than organisational secession, successfully embedding socialist economic ideas into mainstream Congress thinking (visible in Nehru''s own socialist orientation and post-independence Five Year Plan-era economic policy) even as this ''stay and influence'' strategy produced periodic internal tension.', 'Candidates must explicitly address the ''not to cut off'' claim by explaining the CSP''s deliberate strategic choice to remain within Congress rather than simply describing CSP''s socialist ideology in isolation; naming specific leaders (Narendra Deva, JP Narayan) and at least one concrete programmatic influence (Faizpur''s agrarian programme, Nehru''s socialist orientation) is expected.', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q4(b). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('7357773f-f526-468f-aefb-1d8e726daf24', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 14, 'A', '4(c)', 10, 150, 'How did the factionalised Dalit leadership in Hyderabad undergo a period of intense re-organization between 1948 and 1953?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('7357773f-f526-468f-aefb-1d8e726daf24', 'Following the Indian Union''s military annexation of Hyderabad State (Operation Polo, September 1948) and the end of Nizam rule, Dalit political organisation in the former princely state underwent significant reorganisation as it transitioned from Nizam-era politics into the Indian constitutional-democratic framework.

Key dynamics: pre-1948 Dalit politics in Hyderabad had operated under distinct constraints and alliances shaped by Nizam-era communal and caste dynamics (relations with the Nizam''s Muslim-dominated administration, the Razakar movement, and competing Congress/Communist mobilisation in the Telangana countryside during the contemporaneous Telangana peasant armed struggle). After 1948, Dalit leaders had to reposition within the new Indian political and administrative structure (military administration transitioning to civil government, eventual integration into Andhra state politics), engage with the changed opportunities created by the Indian Constitution''s (1950) reservation and anti-untouchability provisions, and rebuild organisational unity across previously fragmented factional lines as new political alignments (Congress, Scheduled Castes Federation influence, local factional leadership) competed for Dalit political allegiance during this five-year transitional period culminating in the 1952 first general elections.', 'This is a narrowly specific regional-historiographical question; a reasonable answer situates the reorganisation within the 1948 annexation, the concurrent Telangana peasant struggle''s political churn, and the new opportunities/pressures created by the 1950 Constitution and 1952 elections, since granular primary-source detail on this specific factional history is not widely available in general secondary literature (needs verification against specialised regional historiography for further granularity).', 'UPSC CSE Mains 2023, History Optional Paper II, Section A, Q4(c). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('0f651495-b768-462c-8055-2843625647f1', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 15, 'B', '5(a)', 10, 150, 'Critically examine the following statement: "The American War of Independence finally ended in 1783 when Britain acknowledged the independence of the United States of America."');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('0f651495-b768-462c-8055-2843625647f1', 'The statement is factually accurate as to the formal legal endpoint -- the Treaty of Paris (3 September 1783) formally ended the American War of Independence (1775-1783) and secured British recognition of American sovereignty -- but a fuller critical examination requires situating this endpoint within the war''s broader course and significance.

Key elements: military defeat was effectively sealed earlier, at the Battle of Yorktown (October 1781), where Cornwallis''s surrender to combined American-French forces made continued British prosecution of the war politically and militarily untenable, though formal peace negotiations and the treaty took nearly two more years. French (and Spanish and Dutch) intervention from 1778 onward was decisive in tipping the military balance against Britain, showing that American independence resulted as much from European great-power rivalry as from purely American military effort. The Treaty of Paris granted the United States all territory east of the Mississippi (except Florida, returned to Spain), formally establishing the new nation''s boundaries.

Significance beyond the immediate date: the American Revolution''s ideals (natural rights, popular sovereignty, republicanism) and its practical demonstration that colonial rule could be successfully overthrown had wider global political influence, including on the subsequent French Revolution.

Conclusion: the statement is correct as to the treaty date but understates that the war''s decisive turning point was Yorktown (1781) and that French intervention was critical to the ultimate outcome.', 'A critical answer should distinguish the effective military conclusion (Yorktown, 1781) from the formal legal conclusion (Treaty of Paris, 1783), and note French intervention''s decisive role -- treating 1783 as simply ''when the war ended'' without this nuance misses the ''critically examine'' instruction.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q5(a). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('85182931-1cae-462b-ad7f-6166d0fa3d76', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 16, 'B', '5(b)', 10, 150, 'Critically examine the following statement: "The Chartist Movement not only fulfilled some of the demands of the middle class, but its ramifications were felt among the working class and the colonies as well."');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('85182931-1cae-462b-ad7f-6166d0fa3d76', 'Chartism (1838-1848), Britain''s first mass working-class political movement centred on the People''s Charter''s six demands (universal male suffrage, secret ballot, no property qualification for MPs, equal constituencies, payment of MPs, annual parliaments), is more accurately described as primarily a WORKING-CLASS movement whose ramifications extended beyond, rather than one that ''fulfilled middle-class demands'' as its primary character.

Assessment: the Reform Act of 1832 had already substantially satisfied middle-class enfranchisement demands, and Chartism arose specifically because the industrial working class remained excluded from that settlement -- making Chartism''s core demands and mass base explicitly working-class rather than middle-class in origin. Its immediate political demands were not achieved in the Chartist era itself (all three petitions -- 1839, 1842, 1848 -- were rejected by Parliament), but most of its six points (except annual parliaments) were eventually enacted through later 19th/early 20th-century Reform Acts, showing long-term influence beyond immediate failure.

Colonial ramifications: Chartist ideas and some Chartist activists influenced colonial working-class and reform politics (Australian labour movements, and Chartist-influenced radical currents among British migrants), and the movement''s demonstration of organised mass working-class political action provided a template later drawn upon in Britain''s colonies and by international labour movements.', 'The critical correction here is that Chartism was fundamentally a working-class (not middle-class) movement responding to the middle class''s own prior 1832 gains -- an answer that accepts the quote''s ''middle class'' framing at face value without this correction misses the central critical point.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q5(b). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('94fab339-c248-4d5d-b557-8e8906234f0c', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 17, 'B', '5(c)', 10, 150, 'Critically examine the following statement: "The Revolutions of 1848 were shaped by the ideas of democracy and nationalism."');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('94fab339-c248-4d5d-b557-8e8906234f0c', 'The Revolutions of 1848 -- erupting across France, the German and Italian states, the Austrian Empire and elsewhere -- were indeed substantially shaped by democratic and nationalist ideas, though economic distress and social class conflict were equally significant, often intertwined, causal forces.

Democratic ideas: revolutionaries across Europe demanded constitutional government, universal male suffrage, freedom of press and assembly, and an end to absolutist monarchy -- most explicitly in France (Second Republic''s proclamation, universal male suffrage) and in the Frankfurt Parliament''s attempt to draft a liberal-democratic constitution for a unified Germany.

Nationalist ideas: the revolutions strongly expressed aspirations for national unification (Italian and German unification movements) and national self-determination (Hungarian, Czech, and other nationalities within the multi-ethnic Austrian Empire seeking autonomy or independence, as in Kossuth''s Hungarian uprising).

Qualification: economic crisis (the 1846-47 harvest failures and the broader economic depression) and working-class social grievances (the June Days uprising in Paris reflecting distinct proletarian demands beyond bourgeois-liberal constitutionalism) were equally significant triggers, meaning the revolutions combined liberal-democratic, nationalist AND socio-economic class dimensions rather than being reducible to democracy and nationalism alone.

Conclusion: democracy and nationalism were central shaping ideas, but not the sole causal forces -- economic hardship and class conflict were equally constitutive of 1848''s revolutionary wave.', 'The Frankfurt Parliament (German nationalism/democracy) and the June Days in Paris (class-conflict dimension often overlooked in a democracy-and-nationalism-only framing) are the specific examples that let a candidate both substantiate and critically qualify the statement.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q5(c). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('38204666-dd11-4da4-b234-636d7b1c2068', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 18, 'B', '5(d)', 10, 150, 'Critically examine the following statement: "The British imperialism in South Africa from 1867 to 1902 was influenced to a large extent by the capitalist mining of diamonds."');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('38204666-dd11-4da4-b234-636d7b1c2068', 'The statement is well-supported: mineral discoveries were a decisive driver of intensified British imperial involvement in South Africa across this period, though strategic and settler-political factors also mattered.

Evidence: the discovery of diamonds at Kimberley (1867 onward) triggered a diamond rush and rapid capitalist mining consolidation (Cecil Rhodes''s De Beers Consolidated Mines, 1888, monopolising diamond production), drawing direct British annexation of Griqualand West (1871) specifically to secure the diamond fields. The subsequent discovery of gold on the Witwatersrand (1886) in the Boer-controlled Transvaal dramatically raised the economic stakes of British-Boer relations, with mining capitalists (Rhodes and the ''Randlords'') actively lobbying for British political control to secure favourable mining conditions, culminating in the Jameson Raid (1895-96) and ultimately the Second Boer War (1899-1902), fought substantially over control of the gold-mining Transvaal and Orange Free State.

Qualification: broader strategic imperial considerations (securing the Cape sea route to India, geopolitical rivalry with other European powers, and settler-colonial expansion ambitions) also shaped British policy independently of mineral interests specifically.

Conclusion: capitalist mining interests (diamonds, then gold) were a major and arguably decisive driver of British imperial assertion in this period, working alongside but not entirely reducible to broader strategic imperial motives.', 'The Kimberley diamond rush/Griqualand West annexation and the Witwatersrand gold discovery/Jameson Raid/Boer War sequence are the two specific mineral-driven episodes that substantiate the statement concretely; noting the Cape sea-route strategic motive provides the necessary critical qualification.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q5(d). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('47a1c05e-7486-425f-a987-98cf5c0e244e', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 19, 'B', '5(e)', 10, 150, 'Critically examine the following statement: "The supremacy of USA after the end of Cold War had its challenges as well."');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('47a1c05e-7486-425f-a987-98cf5c0e244e', 'The statement is well-supported: while the USSR''s 1991 collapse left the USA as the sole global superpower (''unipolar moment''), this supremacy faced substantial and growing challenges rather than proving unchallenged or permanent.

Challenges: (i) Rising powers -- China''s sustained economic growth and, later, growing military-strategic assertiveness; the European Union''s economic weight; and Russia''s later resurgence under Putin, all gradually eroded pure unipolarity toward a more multipolar or at least contested global order. (ii) Asymmetric and non-state threats -- the 9/11 attacks (2001) demonstrated American vulnerability to non-state terrorist actors despite overwhelming conventional military superiority, triggering costly, protracted wars (Afghanistan, Iraq) that strained American resources, credibility and international legitimacy (especially the 2003 Iraq invasion''s contested legal basis). (iii) Economic challenges -- the 2008 global financial crisis, originating in the US financial system, damaged American economic prestige and exposed structural vulnerabilities, while trade competition and globalisation''s uneven domestic effects generated internal political backlash. (iv) Institutional and alliance strain -- unilateralist tendencies in US foreign policy periodically strained relationships with traditional allies, while regional powers increasingly pursued independent foreign policies.

Conclusion: American post-Cold War supremacy, while real and substantial especially militarily, faced significant and multiplying challenges from rising powers, asymmetric threats, and its own economic and institutional strains, confirming that unipolarity was never simply unchallenged dominance.', '9/11 and the costly Afghanistan/Iraq wars, China''s rise, and the 2008 financial crisis are the three specific challenge-categories examiners expect (asymmetric threat, rising-power competition, economic vulnerability); the answer should avoid treating unipolarity as static and instead trace its erosion across the post-Cold War decades.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q5(e). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('92388972-908c-43be-a08b-9bac6be66a2a', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 20, 'B', '6(a)', 20, 350, 'The philosophers and thinkers may have laid the foundation of the French Revolution, but it was precipitated by social and economic reasons. Explain.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('92388972-908c-43be-a08b-9bac6be66a2a', 'Introduction: the French Revolution (1789) is best understood as resulting from the interaction of long-term Enlightenment intellectual preparation and immediate, precipitating socio-economic crisis -- the statement''s framing that ideas laid the foundation while social/economic factors triggered the actual outbreak is well-supported by the historical sequence.

Intellectual foundation: Enlightenment thinkers -- Montesquieu (separation of powers), Rousseau (popular sovereignty, the social contract), Voltaire (critique of absolutism and clerical privilege), and the Encyclopedistes -- circulated ideas questioning divine-right absolutism, aristocratic and clerical privilege, and advocating rational, contractual, rights-based government, providing the ideological vocabulary and legitimating framework the revolutionaries would later draw upon (Declaration of the Rights of Man directly echoes Enlightenment natural-rights language).

Social structure: France''s rigid Ancien Regime social hierarchy (the three Estates -- clergy, nobility, and the Third Estate comprising the vast majority yet bearing almost the entire tax burden) generated deep, structurally embedded grievance, particularly among an increasingly wealthy and politically excluded bourgeoisie and burdened peasantry.

Economic precipitants: chronic state fiscal crisis (worsened by costly French support for the American Revolution and Louis XVI''s inability to reform an inequitable tax system against noble/clerical resistance), poor harvests (1788) causing bread price spikes and widespread subsistence crisis, and rising unemployment, created acute, immediate mass distress that ideas alone could not have produced.

Immediate trigger: the fiscal crisis forced Louis XVI to convene the Estates-General (1789) for the first time since 1614, whose procedural disputes (voting by order vs by head) and the Third Estate''s self-declaration as the National Assembly (Tennis Court Oath) converted accumulated grievance into open revolutionary rupture, with the Bastille''s storming (14 July 1789) -- prompted by economic desperation and fear of royal military crackdown -- marking the point of no return.

Conclusion: Enlightenment philosophy supplied the intellectual justification and aspirational vocabulary that shaped what the Revolution demanded and how it was legitimised, but the specific timing, urgency and mass mobilisation behind its outbreak were driven by concrete fiscal crisis, food scarcity and social-structural grievance -- confirming the statement''s distinction between foundational ideas and precipitating socio-economic causes.', 'The answer must explicitly separate ''foundation'' (Enlightenment thinkers, named individually) from ''precipitation'' (fiscal crisis, 1788 harvest failure, Estates-General convening) rather than blending them into one undifferentiated causal narrative -- this distinction is exactly what the question''s own wording asks candidates to explain.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q6(a). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('89964feb-11b0-49d7-a779-a1639c371015', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 21, 'B', '6(b)', 20, 350, 'Marxian socialism claims itself to be a scientific socialist theory capable of explaining the history of humankind. Discuss.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('89964feb-11b0-49d7-a779-a1639c371015', 'Introduction: Marx and Engels distinguished their ''scientific socialism'' from earlier ''utopian socialism'' (Saint-Simon, Fourier, Owen) by claiming a rigorous, materialist, empirically-grounded theory of historical development (historical materialism) capable of explaining all human history, not merely proposing an idealistic vision of a better society.

Claims to scientific status: historical materialism posits that economic base (forces and relations of production) determines social superstructure, and that history progresses through a determinate sequence of modes of production (primitive communism, ancient slave society, feudalism, capitalism, and, Marx predicted, socialism/communism) driven by internal contradictions (particularly class conflict) within each mode -- presented as an objective, law-like pattern discoverable through analysis of material conditions, analogous to natural-scientific laws, rather than as moral exhortation or utopian blueprint. Marx''s Capital applied rigorous (for its time) economic analysis -- theory of surplus value, the falling rate of profit, capitalism''s inherent contradictions -- to argue capitalism''s collapse and supersession by socialism was a scientifically predictable, inevitable outcome of its own internal dynamics, not merely a desirable moral aspiration.

Critical assessment of the ''scientific'' claim: critics (Karl Popper prominently) argue historical materialism fails the falsifiability test central to genuine scientific theory -- its predictions (proletarian revolution in advanced capitalist states) have not materialised as forecast, and Marxist theory has often been defended through ad hoc reinterpretation rather than abandoned in the face of disconfirming evidence, a hallmark Popper associated with pseudo-science. Weber and others challenged the theory''s economic determinism, arguing culture, religion and ideas (e.g. the Protestant Ethic) possess independent causal force Marx''s base-superstructure model underplays. The theory''s claim to explain ALL human history through a single deterministic schema has also been criticised as overly totalising, ignoring genuine historical contingency, non-economic causation, and non-Western historical trajectories that do not fit the postulated universal stage-sequence.

Conclusion: Marxian socialism''s claim to scientific status rests on its systematic, materialist and law-seeking methodology, genuinely distinguishing it from utopian predecessors, but its predictive failures and totalising universalism have led most contemporary scholars to treat it as a powerful and influential but not strictly ''scientific'' (in the falsifiable, natural-science sense) theory of history.', 'Popper''s falsifiability critique is the specific, expected theoretical counterpoint to Marx''s ''scientific'' claim; a complete answer must engage both what makes Marx''s theory claim scientific status (materialism, law-like stages, Capital''s economic analysis) and the substantive critiques of that claim (Popper, Weber) rather than treating ''scientific socialism'' as self-evidently either true or false.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q6(b). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('01079f38-9ef7-4432-97df-55a2bb8b3488', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 22, 'B', '6(c)', 10, 150, 'Enlightenment was not confined to scientific revolution alone, but humanism and ideas of progress too were its inseparable constituents. Examine.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('01079f38-9ef7-4432-97df-55a2bb8b3488', 'The 18th-century Enlightenment indeed extended well beyond the preceding Scientific Revolution''s empirical-mathematical achievements (Newton, Galileo) to encompass a broader intellectual and moral programme centred on humanism and the idea of progress.

Humanism: Enlightenment thinkers placed human reason, dignity and natural rights at the centre of philosophical and political thought -- Locke''s natural rights (life, liberty, property), Rousseau''s concern with human freedom and the social contract, and Kant''s emphasis on rational autonomy (''dare to know'') reflected a humanist reorientation of philosophy toward human capacity and worth rather than purely divine or scientific-mechanistic concerns.

Ideas of progress: Enlightenment thinkers (Condorcet''s Sketch for a Historical Picture of the Progress of the Human Mind, Turgot) articulated an explicitly progressive philosophy of history -- the belief that human society was moving, through the application of reason, education and science, toward continuous moral, social and material improvement, a decisively new historical-optimist framework distinct from earlier cyclical or providential views of history.

These strands were mutually reinforcing with scientific method (empirical, reason-based inquiry) rather than separate from it, together constituting the Enlightenment''s full, integrated intellectual character.', 'Naming Condorcet''s progress-of-the-human-mind thesis and Kant''s rational-autonomy humanism are the specific citations that substantiate the claim beyond generic assertion; the answer should show these strands as integrated with, not separate from, the scientific-method component.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q6(c). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('9d7e7528-b745-4c06-9713-d2e7563b396d', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 23, 'B', '7(a)', 20, 350, 'The impact of industrial revolution on the middle class worldview is reflected in the views of Adam Smith, Thomas Malthus and Jeremy Bentham. Comment.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('9d7e7528-b745-4c06-9713-d2e7563b396d', 'Introduction: the rising industrial and commercial middle class of late 18th/early 19th-century Britain found its emerging economic and social worldview -- individualism, free markets, and rational self-interest -- systematically articulated in the classical economic and utilitarian theories of Adam Smith, Thomas Malthus and Jeremy Bentham, each responding to and rationalising the transformations the Industrial Revolution was producing.

Adam Smith (The Wealth of Nations, 1776): articulated the doctrine of laissez-faire and the ''invisible hand'', arguing that individuals pursuing rational self-interest in free, unregulated markets would collectively produce optimal social wealth, directly reflecting and legitimising the industrial and commercial middle class''s interest in minimal state interference with trade, manufacturing and labour markets -- providing the emerging capitalist class an intellectual framework justifying entrepreneurial freedom against mercantilist state control and guild restriction.

Thomas Malthus (Essay on the Principle of Population, 1798): argued population grows geometrically while food supply grows only arithmetically, producing inevitable poverty and subsistence crisis unless checked -- a theory that, while genuinely concerned with demographic pressure, was readily used by the industrial middle class to rationalise opposition to poor relief and welfare measures (since aiding the poor was seen as merely encouraging further population growth and prolonging inevitable suffering), aligning with middle-class resistance to redistributive taxation.

Jeremy Bentham (utilitarianism, ''the greatest happiness of the greatest number''): provided a rationalist, calculative ethical framework judging institutions and policies by their measurable social utility rather than tradition or religious authority, appealing to the middle class''s preference for rational, efficiency-oriented reform (Bentham influenced Poor Law reform, 1834, and administrative/legal rationalisation) over aristocratic privilege and inherited custom.

Synthesis: together, these thinkers supplied the emerging industrial middle class with an integrated worldview -- free-market economic liberalism (Smith), a rationale for limiting welfare/state intervention (Malthus), and a rational-utilitarian basis for institutional reform (Bentham) -- that legitimised its economic interests as consistent with scientific reason and general social benefit, shaping 19th-century British economic policy (free trade, Poor Law reform, laissez-faire governance) accordingly.

Conclusion: Smith, Malthus and Bentham''s ideas were not merely abstract theory but functioned as the middle class''s own self-justifying worldview during the Industrial Revolution, rationalising its economic ascendancy and shaping public policy in directions favourable to industrial-capitalist interests.', 'Each thinker''s specific contribution must be linked explicitly to middle-class interest (Smith to laissez-faire/entrepreneurial freedom, Malthus to opposition to poor relief, Bentham to rational reform and the 1834 Poor Law) rather than summarised as isolated economic theories -- this explicit linkage is the ''Comment'' the question requires.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q7(a). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('5f76fdf4-c820-4f2c-a2db-2587d313adc9', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 24, 'B', '7(b)', 20, 350, 'Discuss the different stages of the unification of Italy from 1848 to the occupation of Rome in 1870.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('5f76fdf4-c820-4f2c-a2db-2587d313adc9', 'Introduction: Italian unification (Risorgimento) proceeded through several distinct stages between the failed revolutions of 1848 and the final incorporation of Rome in 1870, driven by the interplay of Piedmontese diplomacy (Cavour), popular nationalist mobilisation (Mazzini, Garibaldi) and favourable great-power politics.

Stage 1 -- 1848-49 failed revolutions: nationalist uprisings across Italian states (Sardinia-Piedmont''s war against Austria, Roman Republic under Mazzini, Venetian uprising) were crushed by Austrian and French intervention, but demonstrated the depth of nationalist sentiment and discredited purely popular-insurrectionary strategies, shifting subsequent leadership toward Piedmontese state-led diplomacy.

Stage 2 -- Cavour''s diplomacy and the war of 1859: Count Cavour, Piedmont''s prime minister, pursued a calculated alliance strategy, securing French support (Napoleon III, Plombieres agreement, 1858) against Austria in exchange for Nice and Savoy; the Franco-Piedmontese war against Austria (1859, battles of Magenta and Solferino) resulted in Piedmont''s annexation of Lombardy, with Venetia remaining under Austrian control.

Stage 3 -- Central Italian annexations (1859-60): plebiscites in Tuscany, Parma, Modena and the Romagna resulted in their voluntary union with Piedmont, extending unification through diplomatic-electoral rather than purely military means.

Stage 4 -- Garibaldi''s Expedition of the Thousand (1860): Garibaldi''s volunteer force conquered Sicily and Naples (the Kingdom of the Two Sicilies) from Bourbon rule, and, in a decisive act of nationalist statesmanship, handed over his conquered southern territories to King Victor Emmanuel II of Piedmont rather than establishing a separate republic, enabling the proclamation of the Kingdom of Italy (1861) under Piedmontese leadership.

Stage 5 -- Venetia (1866): Italy''s alliance with Prussia in the Austro-Prussian War (1866) secured Venetia''s transfer to Italy following Austria''s defeat.

Stage 6 -- Rome (1870): the final piece, Rome (protected by French garrison as the Pope''s temporal territory), was occupied by Italian forces once France withdrew its garrison due to the Franco-Prussian War (1870), completing unification with Rome becoming the capital (1871), though the Papacy''s non-recognition of the annexation (''Roman Question'') remained unresolved until 1929.

Conclusion: Italian unification thus proceeded through a combination of failed popular revolution (1848-49), calculated great-power diplomacy and limited war under Cavour (1859), popular military conquest ceded to monarchy (Garibaldi, 1860), and opportunistic exploitation of wider European conflicts (1866, 1870), completing a decades-long process by 1870-71.', 'The six-stage chronological structure (1848-49 failure, Cavour''s 1859 war, central Italian plebiscites, Garibaldi''s 1860 conquest and handover, 1866 Venetia via Prussian alliance, 1870 Rome via Franco-Prussian War) must all be covered with correct chronology and named actors -- omitting Garibaldi''s handover to Victor Emmanuel or the Franco-Prussian War trigger for Rome are the most common gaps.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q7(b). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('79aeb7fe-2dcf-4740-9771-ea31a2b9d8c6', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 25, 'B', '7(c)', 10, 150, 'The Treaty of Versailles contained in itself the seeds of the Second World War. Examine.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('79aeb7fe-2dcf-4740-9771-ea31a2b9d8c6', 'The Treaty of Versailles (1919), which formally ended WWI, is widely regarded by historians as having created conditions that substantially contributed to WWII''s outbreak two decades later.

Key seeds of future conflict: the ''war guilt clause'' (Article 231) forced Germany to accept sole responsibility for the war, generating deep and lasting German resentment. Punitive reparations demands crippled the German economy, contributing to hyperinflation (1923) and later depression-era instability that Nazi propaganda exploited. Territorial losses (Alsace-Lorraine, the Polish Corridor separating East Prussia, loss of colonies) and military restrictions (army capped at 100,000, demilitarised Rhineland) were experienced as humiliating impositions (''Diktat'') rather than a negotiated peace, fuelling revanchist nationalism that Hitler directly mobilised (rearmament, remilitarisation of the Rhineland, 1936, all framed as reversing Versailles''s injustices). The League of Nations'' weakness (US non-membership, no enforcement mechanism) failed to manage the resulting tensions.

Qualification: the Great Depression, appeasement policy, and Hitler''s own ideological expansionism were equally necessary independent causes; Versailles created grievance and opportunity, but did not alone make war inevitable.', 'Article 231 (war guilt), reparations-driven economic collapse, and the specific territorial/military restrictions Hitler explicitly campaigned against are the concrete links examiners expect; a critical answer notes Versailles created conditions/grievance rather than being solely and directly deterministic of WWII.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q7(c). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('69a0a386-087b-45a7-a697-33e1ae0015f8', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 26, 'B', '8(a)', 20, 350, '''UNO was the necessity of the time when World War II ended.'' Critically examine its achievements and shortcomings.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('69a0a386-087b-45a7-a697-33e1ae0015f8', 'Introduction: the United Nations Organisation, established in 1945 as WWII ended, responded to a genuine and urgent necessity -- the League of Nations'' demonstrated failure to prevent aggression and a second world war -- by creating a stronger international body for collective security, decolonisation management and international cooperation.

Why it was a necessity: the League''s lack of universal membership (the US never joined), absence of an enforcement mechanism, and failure to stop Japanese, Italian and German aggression through the 1930s had catastrophically failed to prevent WWII; the wartime Allied powers (Atlantic Charter, 1941; Dumbarton Oaks and Yalta conferences) recognised the need for a body with broader membership, a Security Council with enforcement ''teeth'', and mechanisms addressing not just security but economic development, human rights and decolonisation.

Achievements: near-universal membership (193 states today) gave it far greater legitimacy and reach than the League; it has provided a continuous forum for diplomacy averting numerous potential conflicts from escalating to world war during the Cold War''s most dangerous moments; UN peacekeeping operations, though imperfect, have managed numerous regional conflicts; specialised agencies (WHO, UNESCO, UNICEF, UNHCR) have achieved substantial humanitarian, health and development successes (smallpox eradication, refugee protection); it provided an important platform for decolonisation, human rights articulation (Universal Declaration of Human Rights, 1948), and multilateral treaty-making (nuclear non-proliferation, climate agreements).

Shortcomings: the Security Council''s five permanent members'' veto power has repeatedly paralysed decisive action on major crises (Cold War gridlock, Syria, Ukraine), reflecting the same great-power-privilege problem that weakened the League in different form; it has failed to prevent numerous conflicts and genocides (Rwanda, 1994; Srebrenica, 1995) despite member states'' awareness; chronic underfunding and dependence on voluntary member contributions limits its operational capacity and independence from powerful member states'' interests; and it has struggled to reform its structure (Security Council composition unchanged since 1965 despite calls for expansion) to reflect contemporary geopolitical realities.

Conclusion: the UN was indeed a necessary and largely successful institutional upgrade over the League in scope, legitimacy and functional capacity, but its core structural flaw -- great-power veto privilege mirroring rather than transcending the power politics it was meant to restrain -- has produced recurring, serious shortcomings that limit its effectiveness as a genuine guarantor of collective security.', 'The veto-power paralysis (naming specific failures like Rwanda/Srebrenica or Cold War gridlock) is the central shortcoming examiners expect discussed in depth, balanced against genuine achievements (near-universal membership, specialised agencies'' humanitarian record) -- a purely celebratory or purely critical answer misses the ''achievements and shortcomings'' balance the question demands.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q8(a). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('4746bc39-47bb-49ec-8a07-4ba911f065f0', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 27, 'B', '8(b)', 20, 350, 'The historical causes for the rise of anti-colonial movement in South-East Asia were cultural differences, spread of western education and the emergence of Communist ideas. Discuss.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('4746bc39-47bb-49ec-8a07-4ba911f065f0', 'Introduction: anti-colonial nationalism across Southeast Asia (Vietnam, Indonesia, Burma, the Philippines, Malaya) in the early-to-mid 20th century emerged from a convergence of the three factors named in the statement, alongside economic exploitation and the demonstration effect of Japanese wartime occupation.

Cultural differences: colonial rule (French in Indochina, Dutch in the East Indies, British in Burma/Malaya, American in the Philippines) imposed alien administrative, legal, religious and educational structures atop deeply rooted indigenous cultural, religious (Buddhist in Burma, Islamic in Indonesia/Malaya, Catholic-influenced in the Philippines) and social traditions, generating persistent cultural friction and a sense of externally imposed, illegitimate rule that fed nationalist self-assertion grounded in reclaiming indigenous cultural identity.

Spread of western education: colonial powers'' establishment of Western-style schools (intended to create a loyal, useful clerical class) inadvertently exposed a new indigenous educated elite to Enlightenment political ideas -- liberalism, nationalism, self-determination (reinforced by Woodrow Wilson''s post-WWI rhetoric) -- that this same elite then turned against colonial rule itself; figures like Sukarno (Indonesia, Dutch-educated engineer) and Aung San (Burma) exemplify Western-educated leaders who became nationalist organisers.

Emergence of Communist ideas: the Russian Revolution (1917) and subsequent Comintern activity spread Marxist-Leninist anti-imperialist ideology throughout the region, providing both an ideological framework explicitly linking colonialism to capitalist exploitation and organisational models (disciplined party structure, peasant-worker mobilisation) -- Ho Chi Minh''s Indochinese Communist Party (1930) and the Communist-influenced strands of Indonesian nationalism (PKI) exemplify Communist ideas'' direct contribution to anti-colonial organisation, particularly appealing given the acute economic exploitation (plantation labour, extractive resource economies) colonial rule had produced.

Additional factor -- WWII/Japanese occupation: Japan''s wartime occupation (1942-45), despite its own harsh character, shattered the myth of European invincibility, armed and trained some nationalist forces (as in Indonesia and Burma), and created a power vacuum that accelerated post-war independence movements.

Conclusion: the three named factors -- cultural friction, Western-educated elite formation, and Communist ideological/organisational influence -- together with underlying economic exploitation and the catalytic effect of Japanese occupation, jointly explain the rise and eventual success of Southeast Asian anti-colonial nationalism across the region''s diverse colonial contexts.', 'Country-specific examples for each factor (Sukarno for Western education, Ho Chi Minh/ICP for Communism, and religious-cultural friction across multiple colonies) are essential; a strong answer also adds the Japanese occupation''s catalytic role even though it is not named in the question''s own three factors, since it is historiographically central to the region''s anti-colonial timeline.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q8(b). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('28141620-2e4d-40ed-b9ec-4f263d4e38b4', '3de2b668-b48f-4cee-a3de-a8f94c956ed3', 28, 'B', '8(c)', 10, 150, 'Arab nationalism was not only a cultural movement, but also an anti-colonial struggle. Comment.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('28141620-2e4d-40ed-b9ec-4f263d4e38b4', 'Arab nationalism (pan-Arabism), emerging in the late 19th/early 20th century, indeed combined a cultural-linguistic revivalist dimension with an explicitly anti-colonial political struggle.

Cultural dimension: the Nahda (''awakening'') movement promoted revival of Arabic language, literature and a shared Arab cultural-historical identity transcending the fragmenting effects of Ottoman rule and subsequent European mandates, providing an ideological basis for imagining a unified Arab political community.

Anti-colonial dimension: Arab nationalism directly opposed both residual Ottoman control (the Arab Revolt of 1916, led by Sharif Hussein with British support against Ottoman rule) and, more significantly, the subsequent European colonial/mandate system (British mandates in Iraq, Palestine, Transjordan; French mandates in Syria and Lebanon) imposed after WWI despite wartime promises of Arab independence -- generating deep grievance (the Sykes-Picot Agreement''s secret partition plans, seen as betrayal) that fuelled sustained anti-colonial mobilisation, including the Great Syrian Revolt (1925-27) against French rule and Iraqi and Egyptian nationalist movements against British control, culminating in Gamal Abdel Nasser''s mid-20th-century pan-Arabist, explicitly anti-imperialist politics (Suez Crisis, 1956).', 'The Sykes-Picot betrayal narrative and the Great Syrian Revolt/Nasser''s Suez-era anti-imperialism are the specific anti-colonial anchors expected, alongside the Nahda cultural-revival dimension -- both halves must be substantiated, not just the cultural or the anti-colonial component alone.', 'UPSC CSE Mains 2023, History Optional Paper II, Section B, Q8(c). Verified directly against a scanned photograph of the official bilingual (Hindi/English) printed question paper (booklet code SKYC-B-HST, pwonlyias.com/wp-content/uploads/2023/09/History-Paper-02.pdf), read page-by-page for exact wording and marks. Cross-checked against two independent sources that matched exactly: LotusArise''s full question-paper reproduction (lotusarise.com) and SelfStudyHistory''s paper-structure transcription with marks (selfstudyhistory.com).');
