-- ============================================================
-- UPSC PSIR Optional Paper II — PYQ & Model Answers (2023)
-- PYQ + Model Answer collection (28 questions)
-- ============================================================

-- ---------- Collection ----------
INSERT INTO pyq_collections (id, slug, subject, title, exam_paper, year, is_premium, question_count, sort_order)
VALUES ('4a11e53c-ebf8-4b15-af6e-a859527cdd83', 'upsc-psir-optional-paper-2-pyq', 'psir', 'UPSC PSIR Optional Paper II — PYQ & Model Answers (2023)', 'paper-2', 2023, true, 28, 2);

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('b3c74b6a-d766-45e2-beb4-13a85f183e23', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 1, 'A', '1(a)', 10, 150, 'What are the crucial functions of empirical political theory in Comparative Politics?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('b3c74b6a-d766-45e2-beb4-13a85f183e23', 'Empirical political theory studies political phenomena as they actually ARE -- through systematic observation, data collection and causal analysis -- rather than prescribing what political arrangements ought to be, and it performs several crucial functions specifically within Comparative Politics.

Key functions: (i) Description -- it systematically documents political institutions, processes and behaviour across countries (electoral systems, party structures, executive-legislative relations), providing the factual basis comparative analysis requires. (ii) Classification -- it enables typologies (e.g., parliamentary vs presidential systems, federal vs unitary states, party-system classifications) that organise diverse political realities into comparable categories. (iii) Explanation -- through hypothesis-testing and causal-inference methods, it identifies WHY political outcomes (democratic stability, regime transitions, policy variation) differ across countries, moving beyond mere description to causal understanding. (iv) Prediction -- empirically grounded models allow forecasting of likely political outcomes under specified conditions (e.g., predicting democratic breakdown risk from structural indicators). (v) Theory-building and testing -- it generates and empirically tests middle-range theories (modernisation theory, structural-functionalism, rational-choice institutionalism) that comparative politics uses to generalise beyond single-country studies.

Significance: without empirical theory''s rigorous, comparable, falsifiable data and method, Comparative Politics would remain a descriptive catalogue of individual country cases rather than a genuinely comparative, generalising social science.', 'Candidates should list distinct functions (description, classification, explanation, prediction, theory-building) rather than a single vague statement that ''empirical theory studies real politics''. Tying each function explicitly back to Comparative Politics'' cross-country generalising purpose, not just political science broadly, is what the question specifically demands.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q1(a). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('ca817231-b740-4580-a496-8d09eb0b0b51', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 2, 'A', '1(b)', 10, 150, 'What are the difficulties faced by a political theorist in comparing the States?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('ca817231-b740-4580-a496-8d09eb0b0b51', 'Comparing states -- a core task of Comparative Politics -- faces several serious methodological and conceptual difficulties.

(i) Conceptual equivalence problem: key terms (democracy, federalism, the state itself) do not carry identical meaning across different political and cultural contexts -- applying a Western-derived concept uncritically to a non-Western state risks ''conceptual stretching'' or, conversely, missing genuine cross-context similarity by defining concepts too narrowly (Giovanni Sartori''s classic warning). (ii) Small-N problem: with a limited number of states/cases available for comparison (unlike large-sample quantitative social science), statistical generalisation is inherently constrained, forcing reliance on qualitative, case-based methods with weaker external validity. (iii) Context-dependence: political institutions do not operate identically across different historical, cultural and socio-economic contexts -- the same formal institution (e.g., a written constitution or parliamentary system) can function very differently depending on political culture, informal norms and historical legacy. (iv) Data availability and reliability: authoritarian or weakly institutionalised states often produce unreliable, incomplete or politically manipulated data, undermining comparability. (v) Ethnocentrism/bias: theorists trained in one (often Western, liberal-democratic) tradition risk imposing their own normative assumptions as a universal comparative yardstick, distorting analysis of fundamentally different political systems. (vi) Rapid political change can also outdate comparative classifications before they are even published.', 'Naming Sartori''s ''conceptual stretching''/travelling problem and the small-N methodological constraint are the two most specific, examiner-recognisable points; a purely generic list of ''countries are different'' without these named methodological concepts scores lower.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q1(b). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('6124a2b9-24a7-4ebd-a5fa-7c0952cfc267', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 3, 'A', '1(c)', 10, 150, 'How does democratic politics construct citizenship?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('6124a2b9-24a7-4ebd-a5fa-7c0952cfc267', 'Citizenship is not a pre-political given but is actively constructed through democratic institutions, participation and discourse -- democratic politics shapes who counts as a citizen, what rights and duties citizenship entails, and how citizens understand their own identity and belonging.

Mechanisms of construction: (i) Legal-institutional construction -- constitutions, electoral laws and naturalisation rules formally define citizenship''s boundaries and entitlements (voting rights, legal equality), which democracies periodically expand (universal suffrage extending citizenship''s substantive content to women, minorities, previously excluded groups). (ii) Participatory construction -- T.H. Marshall''s classic account traces citizenship''s historical expansion through civil rights, then political rights (the franchise), then social rights (welfare entitlements), each secured through democratic struggle and participation, actively remaking what citizenship means over time. (iii) Deliberative/discursive construction -- democratic public debate, civic education and political socialisation shape citizens'' self-understanding as rights-bearing, responsible members of a political community, not merely subjects of rule. (iv) Inclusion/exclusion struggles -- social movements (suffrage, civil rights, LGBTQ+ rights movements) continuously renegotiate citizenship''s boundaries within democracies, showing citizenship as a contested, evolving construction rather than a fixed status.

Significance: this makes democratic citizenship a dynamic political achievement, continuously constructed and contested through institutions and struggle, rather than a static legal category.', 'T.H. Marshall''s civil-political-social rights framework is the standard anchor theory examiners expect. Candidates should show citizenship as actively CONSTRUCTED (contested, expanding, changing) rather than merely defining citizenship status in static legal terms.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q1(c). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('b1f99238-082a-417e-8e02-6e99154dad33', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 4, 'A', '1(d)', 10, 150, 'What is the structure and functions of International Court of Justice?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('b1f99238-082a-417e-8e02-6e99154dad33', 'The International Court of Justice (ICJ), established by the UN Charter (1945) and seated at The Hague, is the principal judicial organ of the United Nations, succeeding the Permanent Court of International Justice.

Structure: it comprises 15 judges, elected for nine-year renewable terms by simultaneous, independent voting in the UN General Assembly and Security Council, with no two judges from the same nationality permitted, and the bench designed to represent the world''s principal legal systems and geographic regions. The Court elects its own President and Vice-President for three-year terms.

Functions: (i) Contentious jurisdiction -- settling legal disputes between STATES (not individuals or organisations) that voluntarily submit to its jurisdiction, based on treaties, general international law, or specific compromis agreements; judgments are binding on parties but the Court has no independent enforcement mechanism, relying on UN Security Council action (subject to veto) for enforcement. (ii) Advisory jurisdiction -- providing non-binding advisory opinions on legal questions referred by authorised UN organs and specialised agencies (General Assembly, Security Council, WHO, etc.), clarifying international law without resolving a specific state-to-state dispute.

Significance and limitation: the ICJ has adjudicated significant inter-state disputes (border, maritime and treaty disputes) but its effectiveness is constrained by the requirement of state consent to jurisdiction and weak enforcement, limiting its role compared to domestic courts.', 'The 15-judge composition, nine-year terms, and the contentious/advisory jurisdiction distinction are the specific facts to include. Noting the enforcement limitation (dependence on the Security Council, itself subject to veto) is an important critical addition beyond pure description.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q1(d). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('24ae311f-3735-4407-ad6b-6d0f87d4fb69', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 5, 'A', '1(e)', 10, 150, 'Discuss the structure and functions of UN Security Council.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('24ae311f-3735-4407-ad6b-6d0f87d4fb69', 'The UN Security Council (UNSC), established under the UN Charter (1945), bears the primary responsibility for maintaining international peace and security among the UN''s principal organs.

Structure: it has 15 members -- five permanent members (P5: US, UK, France, Russia, China) holding veto power over substantive resolutions, and ten non-permanent members elected by the General Assembly for two-year terms (with regional rotation and no immediate re-election), giving it a distinctive, unequal power structure compared to the General Assembly''s one-state-one-vote principle.

Functions: (i) maintaining international peace and security, including investigating disputes, recommending settlement methods, and determining the existence of threats to peace, breaches of peace, or acts of aggression; (ii) imposing binding measures -- economic sanctions, arms embargoes, and (under Chapter VII) authorising collective military action -- decisions that are legally binding on all UN member states, unlike General Assembly resolutions; (iii) authorising UN peacekeeping operations and establishing their mandates; (iv) recommending admission of new UN members and the appointment of the Secretary-General to the General Assembly; (v) referring situations to the International Criminal Court.

Criticism: the P5 veto power is widely criticised as anachronistic and as having repeatedly paralysed Council action on major crises (Syria, Ukraine) where a permanent member''s own interests are implicated, fuelling long-standing reform demands (including India''s claim to permanent membership) that remain unresolved.', 'The P5-veto structure and the binding (Chapter VII) vs non-binding distinction from the General Assembly are the essential structural facts. A brief critical note on veto-driven paralysis and UNSC reform demands (relevant to India''s own aspirations, tested elsewhere in this same paper) adds valuable context.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q1(e). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('453ed808-7f69-431a-9327-7699992f179b', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 6, 'A', '2(a)', 20, 350, 'Discuss the relevance of the normative ethos of the Non-Aligned Movement in magnifying India''s soft power in pursuit of her national interest.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('453ed808-7f69-431a-9327-7699992f179b', 'Introduction: The Non-Aligned Movement (NAM), co-founded by Nehru along with Tito, Nasser, Sukarno and Nkrumah at Bandung (1955) and formally launched at Belgrade (1961), was built on a normative ethos of anti-colonialism, sovereign equality, peaceful coexistence (Panchsheel) and refusal to align with either Cold War bloc -- an ethos that has continued to shape and magnify India''s soft power well beyond the Cold War''s end.

Normative ethos and its soft-power relevance: NAM''s principled anti-colonial, anti-imperial stance gave India enormous moral credibility across the newly decolonised Global South, positioning India as a natural leader and voice for developing nations'' collective interests -- an early and durable source of the soft power Joseph Nye later theorised as the ability to attract and persuade rather than coerce. NAM''s ethos of sovereign equality and non-interference resonated with post-colonial states wary of both superpower blocs, allowing India to build trust-based diplomatic relationships across Asia, Africa and Latin America that pure material/military power could not have secured.

Contemporary relevance: even though NAM as a formal bloc has lost much Cold War-era salience, its normative legacy continues to inform India''s self-presentation as a ''leader of the Global South'' -- visible in India''s advocacy at the WTO and climate negotiations (common but differentiated responsibilities), its Voice of Global South Summits, and its G20 presidency framing (''Vasudhaiva Kutumbakam'' -- one earth, one family). This normative continuity lets India claim a distinctive, non-hegemonic leadership identity distinct from both Western and Chinese models of engagement with developing nations.

Limitations: critics note NAM''s principles sit in some tension with India''s more recent strategic-autonomy/multi-alignment practice (Quad membership, defence ties with the US) -- pursuing concrete security and economic interests sometimes appears to compromise the NAM ethos, and some newly assertive Global South states (or China''s own South-South outreach) now compete for the same normative space India once occupied largely unchallenged.

Conclusion: NAM''s founding normative ethos, even in a transformed contemporary form, remains a genuine and distinctive soft-power resource that allows India to pursue its national interest -- global influence, developing-world leadership and diplomatic goodwill -- through attraction and moral legitimacy rather than coercive power alone.', 'Candidates should connect NAM''s specific historical principles (Panchsheel, anti-colonialism, sovereign equality) explicitly to Nye''s soft-power concept, and bring in a contemporary example (Voice of Global South Summit, G20 presidency) to show ongoing relevance rather than treating NAM as purely historical. Noting the tension with India''s current strategic-autonomy/multi-alignment practice adds needed critical balance.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q2(a). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('d2353030-6261-4432-9390-ce70403af36a', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 7, 'A', '2(b)', 15, 250, 'In what ways does the functionalist approach in International relations help in maintaining peace and order in global politics?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('d2353030-6261-4432-9390-ce70403af36a', 'Functionalism, most associated with David Mitrany (A Working Peace System, 1943), argues that international peace is best achieved not through grand political/constitutional unification but through practical, technical cooperation on shared, non-political needs -- economic development, health, communication, transport -- which gradually builds habits of cooperation that reduce the likelihood of conflict.

Mechanisms for peace and order: (i) Task-specific international organisations (e.g., WHO, ILO, UPU, ICAO) address concrete functional needs that cut across political and ideological divides, allowing cooperation to proceed even between rival states, since technical/welfare cooperation is seen as apolitical and mutually beneficial. (ii) ''Ramification''/spillover -- Mitrany argued that successful cooperation in one technical sector creates functional pressure and habit for cooperation in adjacent sectors, gradually expanding the web of interdependence (a concept later formalised as ''spillover'' in neofunctionalism, Ernst Haas''s account of European integration). (iii) Building interdependence and mutual interest -- as states become economically and functionally interlinked through shared institutions, the cost of conflict rises and incentives for cooperation strengthen, indirectly promoting peace (''form follows function''). (iv) Depoliticising cooperation -- by separating technical welfare cooperation from high-politics sovereignty disputes, functionalism allows states to cooperate on shared problems even amid political rivalry (Cold War-era WHO/UN specialized-agency cooperation between opposing blocs is a key illustration).

Limitations: functionalism has been criticised (notably by realists and by neofunctionalists like Haas) for underestimating how deeply intertwined technical and political questions actually are, and for assuming spillover is automatic rather than requiring active political will -- limiting its explanatory power for genuinely high-stakes security conflicts.', 'Mitrany must be named as the founding theorist, with ''ramification''/spillover as the specific mechanism explaining how functional cooperation builds toward broader peace. A brief critical note (Haas''s neofunctionalist correction, or realist scepticism) strengthens an otherwise purely descriptive answer.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q2(b). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('2a0fd8b4-9814-4e37-aa8c-e77fe52b3d26', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 8, 'A', '2(c)', 15, 250, 'How does the regime change and political crisis in Myanmar threaten regional security and peace?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('2a0fd8b4-9814-4e37-aa8c-e77fe52b3d26', 'The February 2021 military coup in Myanmar, overthrowing Aung San Suu Kyi''s elected government, and the sustained civil conflict/resistance it triggered, has produced significant regional security spillovers across South and Southeast Asia.

Regional security threats: (i) Refugee and displacement flows -- ongoing conflict has driven large-scale internal displacement and cross-border refugee flows into Bangladesh, India (Mizoram, Manipur) and Thailand, straining host-country resources and, in India''s northeast, complicating already-sensitive ethnic and security dynamics given cross-border ethnic kinship (Chin-Mizo ties). (ii) Border insecurity and insurgent safe havens -- weakened central authority in Myanmar''s borderlands has allowed India''s own northeastern insurgent groups to find renewed safe havens and arms-trafficking routes across the porous India-Myanmar border, threatening India''s internal security. (iii) Narcotics and arms trafficking -- state collapse in border regions has intensified the Golden Triangle drug trade and illicit arms flows, affecting neighbouring states'' internal security. (iv) ASEAN credibility and regional institutional strain -- Myanmar''s crisis has exposed ASEAN''s limited capacity to enforce its own Five-Point Consensus peace plan (agreed 2021 but largely unimplemented), straining ASEAN unity and effectiveness as a regional security institution. (v) Great-power competition -- China''s continued engagement with the junta (economic and infrastructure ties, including China-Myanmar Economic Corridor projects) versus Western sanctions has turned Myanmar into another arena of India-China and US-China strategic competition, complicating India''s own ''Act East'' policy and connectivity projects (Kaladan Multi-Modal project, trilateral highway) that transit Myanmar.

Conclusion: Myanmar''s crisis therefore threatens regional peace through humanitarian spillover, insurgency/security linkages, institutional strain on ASEAN, and its entanglement in broader great-power rivalry, directly implicating India''s own border-security and connectivity interests.', 'Candidates should move beyond a generic ''Myanmar coup is bad'' narrative to specific regional security mechanisms: refugee flows into India/Bangladesh, cross-border insurgent safe havens (directly relevant to India''s Northeast security), ASEAN''s Five-Point Consensus failure, and India''s Act East/Kaladan project exposure. This India-specific angle is what elevates the answer for a PSIR paper.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q2(c). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('810e1eb9-1d82-4ab3-919b-6c82e76e17b4', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 9, 'A', '3(a)', 20, 350, '"During the Cold War, the Non-Aligned Movement tried to become a ''Third force'' in World Politics, but failed because it was too large and unwieldy." Discuss.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('810e1eb9-1d82-4ab3-919b-6c82e76e17b4', 'Introduction: The Non-Aligned Movement (NAM), formally launched at Belgrade in 1961 by Nehru, Tito, Nasser, Sukarno and Nkrumah, sought to carve out an independent ''Third Force'' or ''Third World'' position between the US-led capitalist and Soviet-led communist blocs during the Cold War -- a project whose ultimate limited success invites the critical assessment the question poses.

The aspiration: NAM aimed to give newly decolonised and developing states a collective voice independent of bipolar bloc politics, championing sovereign equality, anti-colonialism, peaceful coexistence (Panchsheel) and a more equitable international economic order (the New International Economic Order demand at the UN in the 1970s) -- positioning itself as a genuine alternative pole of global influence rather than a passive bystander to superpower rivalry.

Evidence of the ''too large and unwieldy'' problem: NAM grew to over 100 member states by the 1970s-80s, spanning vastly different regimes, ideologies, economic systems and, crucially, actual alignment behaviour -- many self-declared ''non-aligned'' states (Cuba, Vietnam) were in practice closely aligned with the Soviet bloc, while others (Pakistan, at various points) tilted toward the US, undermining NAM''s claimed coherence. This ideological and strategic heterogeneity made consensus on substantive positions difficult, diluting NAM''s ability to act as a unified bloc on concrete Cold War issues (e.g., NAM member states frequently took opposing sides in regional conflicts like the Iran-Iraq War or Soviet intervention in Afghanistan). Economic diversity among members (oil-rich Gulf states vs impoverished African states) further fragmented any unified NIEO negotiating position.

Structural limitation beyond size: NAM also lacked institutional enforcement mechanisms, a standing secretariat with real authority, or economic/military capability to back its declarations, meaning even where consensus existed, NAM could rarely translate moral positions into concrete leverage against superpower behaviour.

Partial success, however: NAM did succeed in giving the Global South collective voice and visibility at the UN, shaping decolonisation norms and contributing to a genuine non-aligned diplomatic space that avoided formal bloc entrapment for many members.

Conclusion: NAM''s size and internal heterogeneity, combined with weak institutionalisation, substantially explain why it could not consolidate into an effective ''Third Force'' capable of independently shaping Cold War outcomes, even though it retained real value as a normative and diplomatic platform for the developing world.', 'A strong answer must engage critically with BOTH halves of the quoted claim -- the aspiration to be a Third Force, and the specific ''too large and unwieldy'' causal explanation for its limited success -- with concrete evidence of internal heterogeneity (Cuba/Vietnam''s Soviet alignment despite ''non-aligned'' status is the classic illustrative fact). A purely descriptive history of NAM without engaging the causal ''why it failed'' claim misses the question''s actual demand.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q3(a). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('a0c2a5c2-5f7c-4a72-bfa9-74880a90fc51', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 10, 'A', '3(b)', 15, 250, 'Account for the rise of European Union as a highly influential regional organisation.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('a0c2a5c2-5f7c-4a72-bfa9-74880a90fc51', 'The European Union''s rise from a post-war coal-and-steel arrangement to the world''s most institutionally developed regional organisation reflects a combination of historical necessity, functional spillover, and deliberate institutional design.

Historical/security foundation: the European Coal and Steel Community (1951, Schuman Plan) was explicitly designed to make renewed Franco-German war ''materially impossible'' by pooling the very resources (coal, steel) needed for war-making -- embedding peace through economic interdependence in the immediate aftermath of two catastrophic World Wars.

Functional spillover: as neofunctionalist theorist Ernst Haas argued, integration in one sector (coal/steel) generated functional and political pressure (''spillover'') for integration in adjacent sectors -- leading progressively to the European Economic Community (1957, Treaty of Rome), the Single European Act (1986) establishing the single market, and the Maastricht Treaty (1992) creating the EU itself with a common currency (Euro) and foreign-policy cooperation ambitions.

Institutional design: the EU built genuinely supranational institutions (European Commission, European Court of Justice, European Parliament with direct elections) with real transferred sovereignty in key domains, giving it far greater authority and coherence than looser regional bodies (ASEAN, SAARC) that rely on intergovernmental consensus alone.

Economic scale and market power: the EU''s combined single market of hundreds of millions of consumers gives it substantial global economic leverage (regulatory power -- the ''Brussels effect'', where EU standards become de facto global standards) and trade-negotiation weight that individual member states could not achieve alone.

Enlargement and normative appeal: successive enlargement rounds (including post-Communist Central/Eastern Europe after 1989) extended the EU''s institutional and normative model (democracy, rule of law, market economy) as a condition of membership, expanding both its geographic scope and soft-power influence as a democratising and stabilising force in Europe.', 'The Schuman Plan''s security logic and Haas''s neofunctionalist spillover concept are the two theoretical anchors examiners expect, alongside concrete institutional milestones (Treaty of Rome, Maastricht). The ''Brussels effect'' (EU regulatory influence) is a strong, less commonly cited addition that shows contemporary awareness beyond textbook history.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q3(b). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('6a0f1ce1-3aed-4171-88ff-b16f3babfc48', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 11, 'A', '3(c)', 15, 250, 'Narrate the various ways in which rapid environmental degradation is posing a serious threat to human security.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('6a0f1ce1-3aed-4171-88ff-b16f3babfc48', 'Environmental degradation has become a central concern of the ''human security'' framework (UNDP''s 1994 Human Development Report), which broadens security beyond state/military threats to include threats to individuals'' survival, livelihood and dignity -- environmental decline directly threatens several of its dimensions.

(i) Food security -- soil degradation, desertification and climate-driven crop failures threaten agricultural productivity and food availability, particularly in already food-insecure regions of Sub-Saharan Africa and South Asia. (ii) Water security -- glacial retreat, groundwater depletion and pollution of freshwater sources threaten reliable access to clean water, a foundational human need, and are already a source of inter-community and inter-state tension (e.g., transboundary river disputes). (iii) Health security -- air and water pollution directly cause respiratory and waterborne disease; climate change is expanding the range of vector-borne diseases (malaria, dengue) into previously unaffected regions. (iv) Livelihood/economic security -- degradation of fisheries, forests and arable land destroys the resource base millions depend on for subsistence livelihoods, particularly affecting the rural poor and indigenous communities. (v) Displacement and ''climate refugees'' -- sea-level rise, desertification and extreme weather events are driving growing environmental displacement (low-lying island states, Bangladesh''s coastal areas), a form of forced migration with no dedicated international legal protection regime. (vi) Conflict linkage -- resource scarcity (water, arable land) exacerbated by environmental degradation is increasingly identified as a contributing driver of local and inter-communal conflict, particularly in fragile states (e.g., linkages drawn to conflict dynamics in the Sahel).

Conclusion: because environmental degradation threatens survival, livelihood and community stability simultaneously and often irreversibly, it has become recognised as one of the most serious contemporary human security challenges, cutting across food, water, health, economic and conflict dimensions.', 'Grounding the answer explicitly in the UNDP 1994 human security framework (rather than discussing environmental degradation generically) is what makes this a PSIR/IR answer rather than a Geography or Environmental Science one. Candidates should cover multiple distinct dimensions (food, water, health, livelihood, displacement, conflict) for full marks.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q3(c). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('7adb6438-ecd4-41ef-9cf1-54057ba9bb9f', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 12, 'A', '4(a)', 20, 350, 'Critically examine the impact of Globalisation on the developing countries of the world.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('7adb6438-ecd4-41ef-9cf1-54057ba9bb9f', 'Introduction: Globalisation -- the accelerating cross-border integration of trade, capital, technology, information and culture -- has had profound, deeply contested effects on developing countries, generating both genuine developmental opportunity and significant new vulnerabilities.

Positive impacts: (i) Trade and investment -- integration into global markets has enabled export-led growth strategies (East Asian ''tiger economies'', and more recently India, Vietnam) lifting hundreds of millions out of poverty through manufacturing and services export growth. (ii) Foreign Direct Investment and technology transfer -- globalisation has channelled capital and technological know-how to developing economies that domestic savings alone could not have generated, accelerating industrialisation. (iii) Knowledge and information access -- global information flows and digital connectivity have expanded access to education, innovation and global best practices. (iv) Diversification of trade/diplomatic partners -- developing countries have gained greater agency by diversifying economic relationships beyond former colonial powers.

Negative/critical impacts: (i) Unequal terms of integration -- developing countries often integrate into global value chains at low-value-added, labour-intensive stages, while advanced economies and multinational corporations capture disproportionate value, reproducing dependency-theory-style core-periphery dynamics (Andre Gunder Frank, Immanuel Wallerstein''s world-systems theory remain analytically relevant). (ii) Volatility and vulnerability -- deep integration into global capital markets exposes developing economies to external financial shocks (the 1997 Asian Financial Crisis, capital flight episodes) largely beyond their own policy control. (iii) Erosion of policy autonomy -- WTO rules, IMF/World Bank conditionalities and global capital mobility constrain developing states'' ability to pursue independent industrial or protectionist development strategies that today''s advanced economies themselves historically used (Ha-Joon Chang''s ''kicking away the ladder'' critique). (iv) Inequality -- while globalisation has reduced inter-country inequality in aggregate (driven substantially by China and India''s growth), within-country inequality has often risen, and benefits have been unevenly distributed across regions and social groups even within fast-growing developing economies. (v) Environmental and labour costs -- global competition has sometimes driven a ''race to the bottom'' on environmental and labour standards to attract investment. (vi) Cultural homogenisation concerns -- globalisation''s cultural dimension raises concerns about the erosion of local/indigenous cultural practices under globally dominant (often Western) media and consumption patterns.

Conclusion: globalisation''s impact on developing countries is therefore genuinely double-edged -- real developmental opportunity has coexisted with new vulnerabilities and unequal power relations, meaning outcomes have depended heavily on individual countries'' capacity to manage and selectively regulate their own terms of integration rather than globalisation''s effects being uniform or predetermined.', 'The word ''critically'' requires genuinely balanced treatment -- both real gains (East Asian export-led growth) and structural critiques (dependency theory, policy-autonomy erosion, Ha-Joon Chang) must appear, not simply a list of pros and cons. Naming specific theoretical frameworks (world-systems theory, ''kicking away the ladder'') is what distinguishes a strong PSIR answer from a generic economics essay.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q4(a). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('30f4ca9d-87b7-441a-a86e-4abb8503a7c4', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 13, 'A', '4(b)', 15, 250, 'What do you mean by offensive and defensive realism?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('30f4ca9d-87b7-441a-a86e-4abb8503a7c4', 'Offensive and defensive realism are two competing branches of structural (neo)realism in International Relations theory, both sharing realism''s core assumptions (international anarchy, states as primary rational actors, self-help), but diverging sharply on how much power states should rationally seek.

Defensive realism (associated principally with Kenneth Waltz, Theory of International Politics, 1979): argues that the anarchic international system incentivizes states to seek only an APPROPRIATE, sufficient amount of power needed for security -- because excessive power-seeking triggers balancing coalitions from threatened states (balance-of-power dynamics) and is ultimately self-defeating and destabilising. States are fundamentally security-seeking (not power-maximising), and the international system tends toward equilibrium as states balance against emerging threats. Waltz argued that seeking hegemony is typically counterproductive because it invites overwhelming counter-balancing.

Offensive realism (associated principally with John Mearsheimer, The Tragedy of Great Power Politics, 2001): argues that under anarchy and given the impossibility of ever being certain of others'' intentions, the rational strategy for great powers is to maximise relative power continuously, ultimately seeking regional or even global hegemony as the only reliable guarantee of survival -- since ''more power is always better'' when survival cannot otherwise be assured. Mearsheimer argues great powers are inherently and perpetually revisionist, not satisfied status-quo actors, explaining recurrent great-power competition and conflict (his framework has been widely applied to explain US-China strategic rivalry).

Key distinction: defensive realism predicts states seek security through moderate, balanced power (status-quo oriented); offensive realism predicts states seek maximum relative power and hegemony (revisionist, expansionist), producing sharply different predictions about great-power behaviour, arms races, and the likelihood of conflict in the international system.', 'Waltz (defensive) and Mearsheimer (offensive) must be named as the specific originating theorists -- this is a direct-recall theory question where naming the correct scholar-to-branch pairing is essential. The core distinction (moderate/sufficient power vs power-maximisation/hegemony-seeking) should be stated explicitly and precisely, not just ''both are about power''.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q4(b). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('82d10aa3-2a65-48d7-8eb8-04cd16b244eb', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 14, 'A', '4(c)', 15, 250, 'Discuss the various constraints on American hegemony today. Which of these are likely to become more prominent in the future?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('82d10aa3-2a65-48d7-8eb8-04cd16b244eb', 'American hegemony, dominant since the Cold War''s end, faces multiple contemporary constraints that qualify claims of unchallenged unipolarity.

Current constraints: (i) Rise of China -- China''s rapid economic growth, military modernisation, and expanding global institutional footprint (Belt and Road Initiative, AIIB, growing UN and multilateral influence) represents the most significant structural constraint, producing what many IR scholars now describe as an emerging bipolar or multipolar transition. (ii) Multipolar diffusion of power -- the EU, India, Russia, Japan and regional powers each constrain unilateral US action in their respective spheres, and ''middle powers'' increasingly hedge rather than automatically align with US preferences. (iii) Domestic political constraints -- polarised domestic politics, periodic isolationist/''America First'' currents, and fiscal constraints (large national debt) limit the sustained resource commitment global hegemonic leadership requires. (iv) Institutional overstretch and credibility costs -- costly, prolonged military interventions (Iraq, Afghanistan) damaged US credibility and appetite for further large-scale interventions, while allies increasingly question the reliability of US security guarantees. (v) Economic interdependence limiting coercive leverage -- deep economic interdependence (especially US-China trade/financial ties) constrains the US''s ability to use pure coercive economic power without significant self-harm. (vi) Rise of non-state and transnational challenges (terrorism, cyber threats, pandemics, climate change) that traditional hegemonic military power is poorly suited to address unilaterally.

Future prominence: China''s continued rise is widely judged the constraint most likely to grow in prominence, given its trajectory toward matching or exceeding US economic scale and its deliberate strategy of institutional and technological competition (AI, semiconductors) rather than direct military confrontation; climate change and transnational/non-traditional security challenges are also likely to grow as constraints, since they structurally require multilateral cooperation that unilateral hegemonic power cannot substitute for.', 'The question has two explicit parts (current constraints, AND which will grow) -- candidates must not just list constraints but make an explicit forward-looking judgment (China''s rise and non-traditional/transnational challenges are the standard, well-supported answers) with reasoning, not just restate the list a second time.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section A, Q4(c). Verified against a full-paper transcription of Paper II Section A hosted on EduRev (edurev.in), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('5a74ab0c-91a9-4447-8d04-03e17ad2cf2a', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 15, 'B', '5(a)', 10, 150, 'Explain the major features of India''s Foreign Policy in the 21st century.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('5a74ab0c-91a9-4447-8d04-03e17ad2cf2a', 'India''s 21st-century foreign policy displays continuity with its founding non-aligned principles alongside significant pragmatic adaptation to a changed global order.

Key features: (i) Strategic autonomy/multi-alignment -- India avoids formal alliance commitment, instead cultivating simultaneous partnerships across competing power blocs (US, Russia, and increasingly Quad partners) to maximise its own bargaining space, a modern evolution of non-alignment rather than its abandonment. (ii) Economic diplomacy and growth-oriented engagement -- foreign policy has become closely tied to attracting investment, technology and market access supporting domestic economic growth (post-1991 reform-era shift). (iii) Neighbourhood First policy -- renewed priority on South Asian relations (following the earlier Gujral Doctrine''s non-reciprocal generosity principle), alongside ''Act East'' engagement with Southeast/East Asia. (iv) Leadership of the Global South -- continuing NAM-era leadership claims through platforms like the Voice of Global South Summit and G20 presidency advocacy on climate finance and debt relief. (v) Soft power emphasis -- leveraging diaspora diplomacy, yoga/cultural diplomacy, vaccine diplomacy (Vaccine Maitri) and space/knowledge diplomacy to project influence. (vi) Great-power balancing -- deepening strategic ties with the US and Quad partners as a hedge against China''s rise, while maintaining traditional defence ties with Russia. (vii) Civilisational/exceptionalist framing -- growing emphasis, particularly articulated by EAM Jaishankar, on India''s distinct civilisational identity and ''multi-alignment'' as a deliberate strategic choice rather than weakness.', 'This is a frequently repeated PYQ (asked in 2022, 2021, 2018, 2013, 2012, 2011 in various forms) -- examiners expect candidates to show BOTH continuity (strategic autonomy''s roots in non-alignment) and change (multi-alignment, Quad, economic diplomacy) rather than treating 21st-century policy as either purely new or purely unchanged.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q5(a). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('8f93689a-e67b-44b9-992a-2f46db5e8081', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 16, 'B', '5(b)', 10, 150, 'What are the reasons for the lack of ''regionness'' in South Asia?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('8f93689a-e67b-44b9-992a-2f46db5e8081', '''Regionness'' refers to the degree of coherent regional identity, integration and cooperative institutionalisation among neighbouring states -- and South Asia scores persistently low on this measure despite geographic proximity and cultural-historical ties, for several structural reasons.

(i) India-Pakistan rivalry -- the foundational, unresolved territorial and security dispute (Kashmir) and repeated wars have made SAARC''s consensus-based decision-making structurally hostage to bilateral India-Pakistan hostility, paralysing collective regional initiatives. (ii) Asymmetric power structure -- India''s overwhelming size and centrality relative to every other South Asian state (unlike more balanced regional groupings like the EU or ASEAN) generates persistent ''big brother'' anxieties and smaller states'' hedging behaviour (seeking external, often Chinese, counterbalancing partners) rather than deep regional trust. (iii) Weak intra-regional trade -- South Asia has among the lowest intra-regional trade shares of any world region (roughly 5% of total trade), reflecting protectionism, poor connectivity infrastructure, and non-tariff barriers, unlike ASEAN''s more functionally integrated economies. (iv) Historical grievances and mutual mistrust -- Partition''s legacy, unresolved border disputes, and ethnic/religious cross-border tensions (Bangladesh, Sri Lanka, Myanmar spillovers) impede functional cooperation. (v) Institutional weakness -- SAARC''s consensus rule (any member can block action) and absence of supranational authority prevent the kind of pooled-sovereignty integration seen in more successful regional blocs.', 'The comparative framing against ASEAN/EU-style ''regionness'' and India-Pakistan rivalry as the central structural blocker are the key expected points; the low intra-regional trade statistic (~5%) is a strong specific fact examiners reward when included accurately.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q5(b). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('fa452cb4-08fa-4153-bee4-20762a125645', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 17, 'B', '5(c)', 10, 150, 'Why is the compromise reached at WTO regarding the Covid-19 vaccine manufacturing not a Trade Related Intellectual Property Rights (TRIPS) waiver?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('fa452cb4-08fa-4153-bee4-20762a125645', 'In 2022, India and South Africa had originally proposed a broad, comprehensive TRIPS waiver at the WTO covering vaccines, treatments and diagnostics, seeking to suspend multiple categories of intellectual-property protection (patents, trade secrets, industrial designs) to accelerate equitable global Covid-19 vaccine production and access.

What the WTO Ministerial Conference (June 2022) actually agreed was a far narrower compromise: a decision permitting eligible developing-country members to authorise use of patented vaccine subject matter (manufacturing and export) without the patent-holder''s consent for five years, under streamlined procedures -- but this applied ONLY to vaccines (not therapeutics or diagnostics, which were deferred for a later, still-unresolved decision), and it modified/clarified existing TRIPS flexibilities (like compulsory licensing procedures under Article 31bis) rather than broadly suspending intellectual-property protection across the board as the original waiver proposal sought.

Why it falls short of a genuine ''waiver'': it did not eliminate underlying patent rights, left significant implementation ambiguity (eligibility criteria, scope of ''main patents''), excluded trade secrets and know-how transfer (critical for actually replicating complex mRNA vaccine manufacturing), and left therapeutics/diagnostics for future negotiation that has seen little progress -- making it, in the assessment of India and public-health advocates, a much-diluted procedural adjustment rather than the substantive, comprehensive waiver originally proposed.', 'The key distinguishing fact examiners want is that the actual 2022 decision covered ONLY vaccines (not treatments/diagnostics) and modified/streamlined existing compulsory-licensing mechanisms rather than suspending IP protection broadly -- candidates should be precise about this narrower scope rather than describing it as a full TRIPS waiver.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q5(c). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('3389639d-ade2-4d49-8b5e-a07ed1f00130', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 18, 'B', '5(d)', 10, 150, 'Why do ethnic conflicts and insurgencies continue to remain major impediments to regional cooperation in South Asia?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('3389639d-ade2-4d49-8b5e-a07ed1f00130', 'Ethnic conflicts and insurgencies impede South Asian regional cooperation through several reinforcing mechanisms.

(i) Cross-border ethnic kinship and spillover -- many South Asian ethnic groups straddle international borders (Tamils in India/Sri Lanka, Chin-Mizo/Naga communities across India-Myanmar, Bengali populations across India-Bangladesh), meaning internal conflicts in one state routinely generate cross-border refugee flows, arms trafficking and diplomatic friction with neighbours, as seen in Sri Lanka''s civil war straining India-Sri Lanka relations, and Myanmar''s Rohingya crisis burdening Bangladesh and complicating India''s Northeast security. (ii) Insurgent safe havens -- weak state control in conflict-affected border regions allows insurgent groups to use neighbouring territory for sanctuary, training and cross-border operations (India''s Northeast insurgencies historically using Bangladesh/Myanmar territory), generating persistent bilateral security friction and mutual distrust that blocks broader cooperation. (iii) Securitisation of neighbourhood policy -- conflict-driven security concerns push states toward border militarisation and restrictive visa/trade policies rather than open regional integration. (iv) Heightened regional mistrust -- accusations of states harbouring or covertly supporting insurgent/separatist groups in a neighbour''s territory (a recurring India-Pakistan and India-Bangladesh dynamic) poison the diplomatic atmosphere needed for functional SAARC-level cooperation. Together, these dynamics keep security and mistrust, rather than shared developmental interest, as the dominant frame for South Asian inter-state relations.', 'Concrete named examples (Sri Lanka''s Tamil conflict, Rohingya crisis, Northeast Indian insurgencies with cross-border safe havens) are essential; a purely abstract answer about ''ethnic conflict causing distrust'' without naming specific South Asian cases will underperform against the paper''s clear expectation of regional specificity.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q5(d). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('08a6bec2-a029-4b44-bd9a-ed80001d4ae0', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 19, 'B', '5(e)', 10, 150, 'What diplomatic steps has India taken to articulate the interests of the Global South in international politics?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('08a6bec2-a029-4b44-bd9a-ed80001d4ae0', 'India has pursued multiple concrete diplomatic initiatives asserting leadership and voice for the Global South''s collective interests.

(i) Voice of Global South Summit -- India convened two such summits (January 2023 and November 2023) bringing together over 120 developing countries to directly consult on shared priorities before India''s G20 presidency, an unprecedented direct-representation mechanism. (ii) G20 presidency agenda-setting (2023) -- India used its G20 chairmanship to push developing-world priorities onto the agenda of a forum historically dominated by advanced economies, including securing permanent African Union membership in the G20, and championing debt relief, climate finance and equitable digital public infrastructure. (iii) Climate negotiations -- India has consistently championed ''Common but Differentiated Responsibilities'' (CBDR) at UNFCCC negotiations, insisting developed countries bear greater mitigation and financing responsibility given historical emissions, and launched the International Solar Alliance as a Global-South-oriented climate-cooperation platform. (iv) Vaccine diplomacy -- the Vaccine Maitri initiative supplied Covid-19 vaccines to dozens of developing countries. (v) WTO advocacy -- India has consistently pushed for developing-country flexibilities (special safeguard mechanisms, public stockholding for food security) at the WTO. (vi) Continuing NAM-legacy multilateral advocacy at the UN for Security Council and global-governance reform to better represent developing-world interests.', 'The Voice of Global South Summit and India''s 2023 G20 presidency (especially securing AU''s G20 membership) are the specific, contemporary, highly citable facts examiners expect for full marks on this question -- generic references to NAM history alone are insufficient given the question''s clear focus on concrete diplomatic steps.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q5(e). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('44a918c6-4534-4f59-84c3-febf3260a689', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 20, 'B', '6(a)', 20, 350, 'Arms trade, economic ties and congruent geo-political interests are no longer the three pillars of India-Russia relationship in the emerging strategic context. Comment.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('44a918c6-4534-4f59-84c3-febf3260a689', 'Introduction: The India-Russia relationship, historically anchored in three pillars identified by scholars such as R. Menon and E. Rumer -- Soviet-era arms sales, shared public-sector-heavy economic philosophy, and a congruent Soviet/Russia-India-versus-US-Pakistan-China geopolitical alignment during the Cold War -- has undergone substantial transformation in the emerging strategic context, though the relationship persists in evolved form.

Erosion of the traditional three pillars: (i) Arms trade remains significant (Russia is still India''s largest single supplier by cumulative volume, including the S-400 system, BrahMos joint development, and Su-30MKI licensed production), but India has deliberately diversified defence procurement toward the US, France and Israel, reducing exclusive dependence and diluting arms trade''s status as an uncontested singular pillar. (ii) The shared economic philosophy pillar has essentially dissolved -- India''s post-1991 liberalisation and Russia''s post-Soviet market transition eliminated the earlier ideological/planned-economy convergence; bilateral trade, while growing (helped by discounted Russian crude oil purchases after the Ukraine war and Western sanctions), is not underpinned by shared economic ideology but by opportunistic complementarity. (iii) The Cold War-era congruent geopolitical alignment (Soviet-India vs US-Pakistan-China axis) no longer applies -- Russia has deepened its own ties with China and, to some extent, Pakistan, even as India has deepened strategic partnership with the US and Quad, meaning India and Russia''s respective geopolitical orientations have partially diverged rather than remaining congruent.

Emerging/transformed basis of the relationship: what remains and has been actively cultivated instead is a ''special and privileged strategic partnership'' (declared 2010) built on energy cooperation (oil imports, nuclear cooperation at Kudankulam), continued but diversifying defence-technology cooperation, multipolar-world-order convergence (both favouring a multipolar system resistant to unipolar US dominance, expressed through shared BRICS/SCO participation), and personal-level high-trust diplomatic continuity built over decades.

Conclusion: the statement is substantially correct -- the original three pillars have eroded or transformed under new strategic conditions (India''s US/Quad tilt, Russia''s China tilt, post-Soviet economic convergence loss) -- but the relationship has not collapsed; it has been reconstituted around energy security, selective defence-technology cooperation, and shared multipolarity preferences, representing adaptation rather than rupture.', 'Candidates should explicitly name and then individually assess each of the three original pillars (arms/economic ties/geopolitical congruence) rather than discussing India-Russia relations generically, since the question''s structure demands evaluating specifically whether EACH pillar still holds. A strong answer proposes what has replaced or transformed the old pillars (energy, multipolarity) rather than concluding the relationship has simply ended.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q6(a). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('c58eba54-6948-4bc6-80ea-9e9978b01a81', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 21, 'B', '6(b)', 15, 250, 'Discuss the importance of India''s role in UN peacekeeping operations as a ground for its claim to a permanent seat in the UN Security Council.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('c58eba54-6948-4bc6-80ea-9e9978b01a81', 'India has one of the longest and largest histories of contribution to UN peacekeeping of any member state, and cites this record as a central, concrete justification for its long-standing claim to permanent UNSC membership.

Scale and history of contribution: India has contributed more personnel to UN peacekeeping missions than any other country over the organisation''s history, having participated in the majority of UN peacekeeping operations since their inception (starting with UNMOGIP in Kashmir, 1948-49, and Korea in 1950), with tens of thousands of Indian troops having served across multiple continents. India was the first country to deploy an all-women Formed Police Unit (Liberia, 2007), demonstrating leadership in inclusive peacekeeping practice, and has undertaken specialised roles -- medical care, engineering, veterinary support (e.g., in South Sudan) -- beyond pure security functions.

Why this supports the UNSC claim: (i) It demonstrates sustained, substantial and costly (in both financial and human-life terms) practical commitment to international peace and security -- the UNSC''s core mandate -- arguably exceeding the peacekeeping contributions of several existing permanent members. (ii) It establishes India''s credibility, operational experience and moral standing as a genuine security-provider rather than merely a norm-advocate. (iii) It reflects India''s demonstrated multilateralism and non-partisan approach (as a historically non-aligned power) that could bring balanced perspective to Council decision-making, unlike P5 members whose peacekeeping and Council votes are sometimes seen as advancing narrow national interest.

Limitation: despite this strong operational record, translating peacekeeping contribution into actual UNSC reform requires P5 consensus (each holding veto power over Charter amendment), meaning India''s substantive case has not, to date, been sufficient to overcome the structural and geopolitical obstacles to Security Council expansion.', 'Specific facts (largest cumulative troop contributor, first all-women FPU in Liberia, presence since UNMOGIP/Korea) should anchor the argument rather than a vague ''India helps UN peacekeeping''. Candidates should also note the structural obstacle (P5 veto over Charter reform) that limits how far even a strong record can carry the UNSC claim, for balance.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q6(b). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('ebf7eb2a-9506-44f4-b0ab-d2d29e112fa2', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 22, 'B', '6(c)', 15, 250, 'Quadrilateral security dialogue (QUAD) performs an important role in India''s strategic balancing act to withstand the dominance of China in Asia. Discuss.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('ebf7eb2a-9506-44f4-b0ab-d2d29e112fa2', 'The Quadrilateral Security Dialogue (QUAD) -- India, the US, Japan and Australia -- has evolved from an informal 2004 tsunami-relief coordination mechanism (''Quad 1.0'') into a significant, renewed strategic grouping (''Quad 2.0'', consolidating from 2017) explicitly aimed at shaping a stable, rules-based Indo-Pacific order amid China''s rising assertiveness.

Role in India''s balancing strategy: (i) Deterrence and strategic signalling -- Quad naval exercises (Malabar) and coordination send a collective signal of resistance to unilateral Chinese assertiveness in the South China Sea and broader Indo-Pacific, giving India multilateral backing beyond its own bilateral capacity against China. (ii) Post-Galwan strategic shift -- the 2020 Galwan Valley clashes catalysed India''s deeper Quad engagement, reflecting a recognition that bilateral deterrence alone was insufficient and that partnering with like-minded powers strengthens India''s overall position vis-a-vis China. (iii) Non-security functional cooperation building resilience -- Quad cooperation on vaccines, critical/emerging technology, infrastructure and supply-chain resilience (reducing dependence on China-centric supply chains) indirectly reduces China''s economic leverage over Quad members. (iv) Balancing without formal alliance -- crucially, the Quad allows India to strategically balance China while preserving its strategic-autonomy tradition, since it is explicitly not a formal mutual-defence treaty alliance (unlike NATO), reconciling containment-adjacent behaviour with India''s continued non-aligned diplomatic identity and continuing relations with Russia.

Limitations: the Quad has faced criticism for lacking institutionalisation (no secretariat, no binding security commitments) and for members'' differing risk-appetite regarding China (Australia and the US more confrontational; India and Japan more cautious given proximity/trade ties), meaning its balancing function, while real, remains looser and less certain than a formal alliance would provide.

Conclusion: the Quad meaningfully strengthens India''s capacity to balance China''s regional dominance through deterrence signalling, functional resilience-building and multilateral legitimacy, while preserving the flexibility central to India''s strategic-autonomy doctrine.', 'Post-Galwan (2020) recalibration is the key contemporary anchor fact linking directly to ''withstanding Chinese dominance''; candidates should also note the Quad''s deliberate non-alliance character as what makes it compatible with India''s strategic autonomy, which is what makes this a nuanced PSIR answer rather than a simple pro-Quad summary.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q6(c). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('2162977e-8e34-4c70-aa65-c879ba86af90', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 23, 'B', '7(a)', 20, 350, '"India''s nuclear policy is deeply influenced by its cultural beliefs and its pragmatic approach to foreign policy". Discuss.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('2162977e-8e34-4c70-aa65-c879ba86af90', 'Introduction: India''s nuclear trajectory -- from Nehru''s early disarmament advocacy to becoming a de facto nuclear-weapon state -- reflects a genuine, sustained tension and synthesis between deep-rooted cultural/ethical beliefs and hard-nosed strategic pragmatism.

Cultural/ethical influence: India''s nuclear discourse has always been shaped by Gandhian non-violence and Nehruvian idealism -- India was an early, vigorous advocate of global nuclear disarmament at the UN, framing nuclear weapons as fundamentally immoral instruments (Nehru personally viewed them as ''evil and diabolical''). Even after acquiring nuclear capability, India''s declared doctrine reflects this ethical inheritance: a No-First-Use commitment (rare among nuclear powers), a policy of ''credible minimum deterrence'' rather than maximalist arsenal expansion, and continued rhetorical commitment to eventual global disarmament -- all reflecting an underlying discomfort with nuclear weapons as instruments of first resort, distinguishing India''s doctrine from more aggressive nuclear postures elsewhere.

Pragmatic strategic influence: alongside this ethical framing, India pursued nuclear capability for unambiguously pragmatic security reasons -- the 1962 China war and China''s own 1964 nuclear test created an enduring security rationale, and India''s 1974 ''Smiling Buddha'' peaceful nuclear explosion and the 1998 Pokhran-II tests reflected calculated strategic decisions to establish deterrence credibility against both China and Pakistan, accepting resultant international sanctions as an acceptable pragmatic cost. Scholars like C. Raja Mohan and S. Jaishankar have described the 1998 tests as an ''exercise in strategic retrieval'' -- correcting decades of perceived strategic drift and asserting India''s arrival as a great power, a distinctly pragmatic, power-political calculation. The subsequent 2008 India-US civil nuclear deal, converting India''s outsider status into de facto nuclear-weapon-state recognition without NPT membership, exemplifies pragmatic diplomatic maneuvering to secure recognition and access despite India''s non-signatory status.

Synthesis: India''s nuclear policy is best understood not as a contradiction but as continuous management of this tension -- ethical/cultural inheritance shapes the RESTRAINT and doctrine (No-First-Use, minimum deterrence, disarmament advocacy) while strategic pragmatism shapes the DECISION to acquire and maintain capability at all, and to leverage it diplomatically once acquired.

Conclusion: India''s nuclear policy thus authentically reflects both cultural/ethical beliefs (shaping restraint and doctrine) and pragmatic strategic calculation (shaping acquisition and diplomatic leverage), making the statement''s characterisation substantially accurate rather than overstated.', 'Candidates should explicitly separate the cultural/ethical evidence (No-First-Use, minimum deterrence, disarmament advocacy, Gandhi/Nehru''s ethical discomfort) from the pragmatic evidence (1962 war/1964 Chinese test triggering the programme, 1998 tests as ''strategic retrieval'', 2008 nuclear deal) and then synthesise rather than treating them as separate, unconnected halves of the answer.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q7(a). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('8314609e-d4eb-46c0-bb53-a23c17807bc7', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 24, 'B', '7(b)', 15, 250, 'What steps has India taken to regain its foothold in Afghanistan since the Taliban has taken over the country in August 2021?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('8314609e-d4eb-46c0-bb53-a23c17807bc7', 'Following the Taliban''s August 2021 takeover, which initially disrupted India''s substantial prior development investment and diplomatic presence in Afghanistan, India has pursued a cautious, calibrated re-engagement strategy rather than either full recognition or complete withdrawal.

Steps taken: (i) Humanitarian assistance as engagement channel -- India has provided substantial humanitarian aid (wheat shipments, medical supplies including Covid-19 essentials, winter relief) as a people-to-people goodwill mechanism that maintains presence and influence without implying political recognition of the Taliban government. (ii) Limited technical/diplomatic presence -- India reopened a technical mission in Kabul (June 2022) to coordinate humanitarian assistance and monitor the situation, a calibrated step short of full embassy-level diplomatic recognition. (iii) Multilateral engagement -- India has participated in multilateral formats, including regional National Security Advisor-level dialogues on Afghanistan (Moscow format discussions), to coordinate with regional powers (Russia, Iran, Central Asian states) on shared concerns rather than acting unilaterally. (iv) Counter-terrorism vigilance -- India''s engagement is shaped by concern over Pakistan-based groups (Jaish-e-Mohammed, Lashkar-e-Taiba) and ISKP/al-Qaeda exploiting Afghan territory, and India has pushed for Taliban commitments (referencing the 2021 Delhi Declaration) against allowing Afghan soil to be used for terrorism against India. (v) Continued infrastructure stake protection -- India has sought to preserve its substantial prior development investments (Afghan Parliament building, Salma Dam, Zaranj-Delaram highway) as leverage and goodwill capital for eventual fuller engagement. (vi) Avoiding a ''boots on the ground'' approach, relying instead on developmental and diplomatic tools consistent with India''s traditional regional engagement style.

Conclusion: India''s approach balances pragmatic humanitarian/technical engagement to preserve influence and counter Pakistan-China inroads, against continued non-recognition and vigilance over terrorism concerns, reflecting cautious hedging rather than a decisive policy shift in either direction.', 'The June 2022 Kabul technical mission reopening and continued humanitarian aid are the specific, citable concrete steps examiners expect; candidates should also note India''s underlying motivation (countering Pakistan-China inroads, counter-terrorism vigilance) rather than describing the steps in a policy vacuum.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q7(b). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('a0281dd5-c019-4191-afbf-9027d19beebc', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 25, 'B', '7(c)', 15, 250, 'What are the challenges and limitations in India-Iran relations?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('a0281dd5-c019-4191-afbf-9027d19beebc', 'Despite historical civilisational ties and shared strategic interest in Afghanistan and connectivity, India-Iran relations face significant structural challenges that have limited the relationship''s practical depth.

Key challenges: (i) US sanctions -- India was compelled to halt oil imports from Iran after May 2019 under US pressure (loss of the sanctions waiver), removing what had been a major pillar of bilateral economic engagement and forcing India to prioritise its larger strategic relationship with Washington over Iran ties. (ii) Iran''s deepening ties with India''s rivals -- Iran''s growing strategic and economic closeness with China (including a 25-year strategic partnership agreement) and improving ties with Pakistan complicate India''s calculus, introducing a degree of strategic hedging by Tehran that limits India''s confidence in the relationship''s exclusivity. (iii) Limited trade diversification -- despite frequent high-level visits and dialogue, actual trade has not scaled up significantly, and mechanisms for alternative payment/trade routes around sanctions (e.g., rupee-rial arrangements) have seen limited practical uptake. (iv) Chabahar port''s underperformance relative to potential -- India''s flagship connectivity investment (Chabahar port, intended to bypass Pakistan for access to Afghanistan and Central Asia) has faced slow implementation, financing constraints linked to sanctions risk, and competition from China-backed alternatives (Gwadar port in Pakistan). (v) Third-party hostage dynamics -- Indo-Iranian relations are frequently held hostage to India''s relations with the US (sanctions compliance) and Israel (India''s own growing strategic partnership with Israel creates some friction, given Iran-Israel hostility), limiting India''s room for independent manoeuvre. (vi) Regional instability -- broader Middle East volatility (Iran-Israel tensions, Houthi attacks affecting shipping) adds unpredictability to any Iran-linked connectivity or energy plans.

Conclusion: India-Iran relations thus remain constrained less by bilateral disagreement than by the structural pressure of India''s other major relationships (US, Israel) and Iran''s own deepening China/Pakistan ties, limiting the partnership''s practical scope despite genuine shared interests.', 'The 2019 loss of the US sanctions waiver (ending Indian oil imports) and Chabahar port''s underperformance are the two most specific, examinable facts; candidates should also explicitly note the ''third-party hostage'' dynamic (US and Israel ties constraining India-Iran relations) as the deeper structural explanation the question is probing for.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q7(c). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('26fa9439-99a6-45e1-a9a4-494aa811a419', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 26, 'B', '8(a)', 20, 350, 'What are the external determinants of the Foreign Policy of the state?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('26fa9439-99a6-45e1-a9a4-494aa811a419', 'Introduction: A state''s foreign policy is shaped not only by internal (domestic political, economic, ideological) factors but significantly by external determinants -- systemic and environmental conditions beyond the state''s direct control that constrain and shape its available choices.

Key external determinants: (i) The structure of the international system -- whether unipolar, bipolar or multipolar, following Kenneth Waltz''s structural realism, fundamentally shapes what alliance and balancing behaviours are rational and available to any given state; a state''s foreign policy options differ sharply depending on this systemic distribution of power. (ii) Geopolitical/geographic position -- a state''s location, neighbours, access to sea lanes and resource endowments (geopolitics, in the classical Mackinder/Spykman tradition) constrain and shape strategic priorities (e.g., India''s Himalayan and maritime geography shapes its China and Indian Ocean policies respectively). (iii) Behaviour and capabilities of other states -- the actions, alliances, and relative power of neighbouring and great powers directly constrain a state''s own choices (e.g., China''s rise reshaping Indian and broader Indo-Pacific foreign policy). (iv) International law, norms and institutions -- treaty commitments, UN Charter obligations, and international regime memberships (WTO, NPT, etc.) constrain unilateral state action and shape acceptable behaviour. (v) Global economic interdependence -- trade relationships, global supply chains, and financial market integration constrain policy choices by raising the cost of confrontational postures with major economic partners. (vi) Global and regional crises/shocks -- pandemics, financial crises, and conflicts (e.g., the Russia-Ukraine war''s global ripple effects on energy and food security) impose external shocks that force policy adjustment regardless of a state''s own preferences. (vii) Alliance commitments and great-power patronage -- for smaller/weaker states particularly, the foreign-policy preferences of a patron or allied great power can constrain independent choice.

Conclusion: together these external determinants -- systemic structure, geography, other states'' behaviour, international law/institutions, economic interdependence, and exogenous shocks -- form the environmental context within which any state''s foreign policy is necessarily formulated, meaning foreign policy analysis must always account for these constraints alongside a state''s internal/domestic determinants for a complete explanation.', 'A comprehensive answer should distinguish external determinants clearly from internal/domestic ones (public opinion, leadership, economic structure) which the question does not ask about, and should name multiple distinct categories (systemic structure, geography, other states'' behaviour, international institutions/law, economic interdependence, exogenous shocks) with brief real-world illustration for each.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q8(a). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('8f902af9-2354-4147-be83-015190af3d57', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 27, 'B', '8(b)', 15, 250, 'Discuss the significance of "West Asia Quad" in the light of India''s ''Look West'' policy.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('8f902af9-2354-4147-be83-015190af3d57', 'The ''West Asia Quad'' (also referred to as I2U2 -- India, Israel, UAE, USA), formed in 2022, is a non-security-focused minilateral grouping that has become a significant vehicle for India''s deepening engagement with West Asia/the Middle East under its broader ''Look West'' policy reorientation.

Structure and focus: I2U2 is explicitly a non-security minilateral mechanism (distinct from a defence alliance) focused on mobilising private-sector investment and expertise across six key collaborative sectors: water, energy, transportation, space, health, and food security, leveraging each member''s comparative advantage (Israeli/American technology, UAE capital, Indian markets/manpower and agricultural expertise).

Significance for India''s Look West policy: (i) De-hyphenation strategy -- I2U2 allows India to simultaneously deepen ties with Israel and the Gulf Arab states (historically seen as requiring a balancing act) within a single cooperative framework, reflecting India''s broader ''de-hyphenation'' approach to managing historically competing regional relationships. (ii) Economic weight -- the UAE is already India''s third-largest trading partner (India-UAE trade around US$73 billion in 2022) and a top export destination, and I2U2''s flagship projects (a food-corridor initiative linking Israeli/American agri-technology to Indian farmland, a hybrid renewable-energy facility in Gujarat) directly advance India''s economic and food/energy security interests. (iii) Technology access -- Israel is a major supplier of Indian defence equipment and advanced technology (agriculture, water, cybersecurity), and I2U2 formalises a channel for deeper technology cooperation. (iv) Complementing bilateral ties with a minilateral platform -- I2U2 provides India a flexible, low-institutional-cost forum (avoiding the rigidities of larger multilateral organisations) to advance West Asia engagement alongside existing bilateral relationships with Gulf states and Israel individually.

Limitations: critics note I2U2 remains a young, loosely institutionalised grouping without binding commitments or a permanent secretariat, and its long-term significance will depend on translating announced flagship projects into concrete, delivered outcomes.', 'I2U2''s identity as I2U2 (India-Israel-UAE-USA) should be named explicitly since ''West Asia Quad'' is the paper''s descriptive phrase for this specific grouping; candidates should cite the six-sector cooperative focus and at least one flagship project (the food corridor or Gujarat renewable-energy facility) as concrete evidence rather than describing it only in the abstract.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q8(b). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('ddfd3186-0396-41c9-8be6-b56596384f94', '4a11e53c-ebf8-4b15-af6e-a859527cdd83', 28, 'B', '8(c)', 15, 250, 'Discuss the major drivers of India''s interests in Africa.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('ddfd3186-0396-41c9-8be6-b56596384f94', 'India''s engagement with Africa is driven by a combination of historical, economic, strategic and normative factors that together explain its growing prioritisation of the continent.

Major drivers: (i) Historical and civilisational ties -- shared anti-colonial solidarity (Non-Aligned Movement era), a substantial and long-established Indian diaspora across East and Southern Africa, and India''s own historical experience as a colonised nation give it a distinct, less-fraught entry point compared to former colonial powers or, increasingly, China. (ii) Economic and trade interests -- Africa''s growing markets, natural resource endowments (oil, minerals, agricultural land) and demographic dividend make it economically significant for India''s energy security and export markets, with India-Africa trade having grown substantially over the past two decades. (iii) Development partnership model -- India promotes a demand-driven, non-conditional partnership model (the ''Kampala Principles'', articulated at the India-Africa Forum Summit) explicitly contrasted with colonial-style extraction or perceived Chinese debt-driven infrastructure lending, emphasising capacity-building, lines of credit, and technology transfer (e.g., the Pan-African e-Network Project for tele-education/tele-medicine). (iv) Strategic/security interests -- India''s Indian Ocean security role (as a ''net security provider''), naval engagement with African littoral states (Africa-India Field Training Exercise, AFINDEX), and counter-piracy cooperation reflect India''s maritime strategic interest in East Africa and Indian Ocean sea lanes. (v) Multilateral and diplomatic support -- Africa''s 54-plus votes make it a critical bloc for India''s global diplomatic priorities, including India''s UN Security Council reform ambitions. (vi) Counter-balancing China''s expanding African footprint -- India''s growing Africa engagement is also partly a response to China''s much larger Belt and Road-linked presence, positioning India as an alternative, more equal partnership model.

Conclusion: these drivers -- historical solidarity, economic opportunity, a distinctive non-conditional partnership model, maritime security interest and diplomatic bloc significance -- together explain why Africa has become an increasingly prioritised dimension of India''s contemporary foreign policy.', 'Naming the Kampala Principles and the Pan-African e-Network Project gives concrete institutional substance beyond generic ''India and Africa have historical ties''; candidates should also explicitly note the implicit China-competition dimension, since this is a major, well-documented driver of India''s accelerated Africa outreach in the current period.', 'UPSC CSE Mains 2023, PSIR Optional Paper II, Section B, Q8(c). Verified verbatim against a scanned official-format coaching-institute reproduction of the exact question (Sleepy Classes IAS archive, sleepyclasses.com, "PSIR Paper 2 - B, UPSC 2023"), cross-checked against independent topic-wise question summaries on Synopsis IAS (synopsisias.com) and Edukemy (edukemy.com), which matched in content, wording and marks.');
