-- ============================================================
-- Quiz coverage for devops/terraform, devops/ansible, devops/helm
-- -- overview, fundamentals, intermediate, advanced (the four
-- tabs actually live for all three technologies this batch).
--
-- Registry note: for all three technologies, devops/{tech}/{overview,
-- fundamentals,intermediate,advanced} remain ALIASED to
-- infrastructure/{tech}/* (unlike git in batch 2, infrastructure/*
-- turned out correctly-topical and higher quality than the generic
-- devops/{tech}/* template copies for all three -- see the batch 4
-- commit message for the full comparison). Every question below is
-- grounded in the infrastructure/{tech}/* content, since that is what
-- actually renders at /academies/devops/{tech}/{section}.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES

-- ---------- devops/terraform/overview ----------
('devops', 'terraform', 'overview', 'Per Terraform''s own recommended split of responsibilities, what is the difference between using Terraform and using Ansible together?', '["They are interchangeable and a team should only ever use one", "Terraform is declarative and best for provisioning infrastructure; Ansible is imperative and best for configuration management -- common practice is Terraform to provision, Ansible to configure", "Ansible replaces Terraform for all cloud provisioning tasks", "Terraform can only manage AWS, so Ansible is required for any other cloud"]', 1, 'Terraform defines the desired end state of infrastructure (declarative); Ansible defines the steps to configure something (imperative). Many production setups use Terraform to stand up the infrastructure and Ansible to configure what runs on it.', 'beginner'),
('devops', 'terraform', 'overview', 'Why does a Terraform backend configuration for a team typically include a dynamodb_table setting alongside the S3 bucket?', '["It stores a backup copy of the state file", "It provides state locking, preventing two people from running terraform apply against the same state at the same time", "It is required for encryption to work", "It caches provider plugin downloads for faster init"]', 1, 'Without locking, two concurrent applies against the same state file can corrupt it or produce conflicting changes. The DynamoDB table (with a LockID primary key) is what backs S3-based state locking.', 'intermediate'),
('devops', 'terraform', 'overview', 'What is the recommended way to pass a secret value like a database password into Terraform, according to standard security practice?', '["Hardcode it directly in the .tf resource block for simplicity", "Store it in terraform.tfvars and commit that file so the whole team has it", "Use an environment variable (TF_VAR_db_password) or fetch it from a secrets manager / Vault via a data source at apply time", "Put it in the state file manually after apply completes"]', 2, 'Secrets should never be hardcoded or committed. TF_VAR_ environment variables, and data sources against AWS Secrets Manager, Azure Key Vault, or HashiCorp Vault, keep secret material out of version control entirely.', 'intermediate'),
('devops', 'terraform', 'overview', 'Why is terraform.tfstate considered sensitive and worth encrypting at rest?', '["It is empty until the first apply, so it does not matter", "It can contain plaintext sensitive values (passwords, keys) that ended up in resource attributes or outputs, plus a full map of your infrastructure", "State files are automatically encrypted by Terraform regardless of backend", "Only .tfvars files can contain sensitive data, never the state file"]', 1, 'Anything Terraform reads back from a provider -- including values that started out as secrets -- can end up in state in plaintext. This is why remote backends should enable server-side encryption (e.g. S3 SSE with a KMS key) and restrict access.', 'intermediate'),
('devops', 'terraform', 'overview', 'In a CI/CD pipeline, why is OIDC federation (e.g. GitHub Actions assuming an AWS IAM role) preferred over storing static AWS access keys as pipeline secrets?', '["OIDC is faster to set up initially", "OIDC issues short-lived, scoped credentials tied to a specific workflow run instead of long-lived static keys that must be manually rotated and can leak", "Static keys are not supported by Terraform at all", "OIDC removes the need for any IAM permissions"]', 1, 'Static long-lived keys sitting in CI secrets are a standing credential-leak risk. OIDC federation lets the CI provider present a signed token that AWS exchanges for a short-lived, narrowly-scoped session -- nothing long-lived to leak or rotate.', 'advanced'),

-- ---------- devops/terraform/fundamentals ----------
('devops', 'terraform', 'fundamentals', 'In a required_providers block, what does the version constraint "~> 5.0" mean?', '["Exactly version 5.0 and no other", "Any version greater than or equal to 5.0 but less than 6.0 (allows 5.x patch/minor upgrades, blocks the next major version)", "Any version at all, the constraint is ignored", "Only pre-release versions of 5.0"]', 1, 'The ~> (pessimistic constraint) operator locks the leftmost non-specified segment -- "~> 5.0" allows 5.1, 5.2, etc. but not 6.0, which protects against unexpected breaking changes from a major version bump.', 'beginner'),
('devops', 'terraform', 'fundamentals', 'What is the purpose of a data source like data "aws_ami" "amazon_linux" in Terraform?', '["It creates a new AMI in AWS", "It reads information about an existing resource that Terraform does NOT manage, so the value can be referenced elsewhere in the configuration", "It deletes an existing AMI", "Data sources can only be used with the AWS provider"]', 1, 'Data sources let you look up existing infrastructure -- like the latest AMI matching a filter -- without Terraform trying to create or manage that resource itself.', 'beginner'),
('devops', 'terraform', 'fundamentals', 'What does terraform fmt -recursive do, and why does it matter in a team setting?', '["It applies infrastructure changes across all subdirectories", "It formats all .tf files in the working directory and subdirectories to Terraform''s canonical style, keeping code style consistent across a codebase with modules in subfolders", "It validates the syntax of every .tf file for errors", "It recursively deletes unused variable declarations"]', 1, 'fmt is purely cosmetic/style formatting (whitespace, alignment) -- it does not check correctness. -recursive extends it beyond the current directory, which matters once a project has a modules/ subfolder.', 'beginner'),
('devops', 'terraform', 'fundamentals', 'What does the merge() function do in an expression like merge(local.common_tags, { Name = "main-vpc" })?', '["It deletes duplicate keys from both maps", "It combines two or more maps into one, with later arguments'' keys overriding earlier ones on conflict", "It merges two Terraform state files together", "It only works on lists, not maps"]', 1, 'merge() is commonly used to combine a shared set of tags (like common_tags) with resource-specific tags, letting the resource-specific value win if the same key appears in both.', 'intermediate'),
('devops', 'terraform', 'fundamentals', 'What is the difference between a variable block and an output block in Terraform?', '["They are the same thing, just different names", "A variable is an input into the configuration (parameterizes it); an output is a value exposed FROM the configuration after apply, for use by other configs, the CLI, or a human", "Outputs are only visible during terraform plan, never after apply", "Variables cannot have default values, only outputs can"]', 1, 'variable declares something the config receives from outside (a default, -var flag, tfvars file, or env var); output declares something the config exposes after creating resources, e.g. a VPC ID other modules or team members need.', 'beginner'),

-- ---------- devops/terraform/intermediate ----------
('devops', 'terraform', 'intermediate', 'When calling a local module with source = "./modules/vpc", why must the module''s own variable and output blocks exist inside that module directory?', '["They don''t need to -- Terraform infers them automatically from resource blocks", "A module is just a self-contained Terraform configuration; its variable blocks define what inputs it accepts, and its output blocks define what values the calling configuration can read back via module.vpc.output_name", "Variables are optional; only resource blocks are required in a module", "Modules can only use variables already declared in the root configuration"]', 1, 'Modules are encapsulated -- the calling configuration cannot reach into a module''s internals directly. variable blocks define the module''s public inputs and output blocks define its public outputs; everything else stays private to the module.', 'intermediate'),
('devops', 'terraform', 'intermediate', 'What does referencing terraform.workspace inside a resource block actually do, e.g. var.instance_type[terraform.workspace]?', '["It always returns "default" regardless of the active workspace", "It evaluates to the name of the currently selected workspace (e.g. "staging"), letting a single configuration branch its behavior per environment via a lookup map", "It creates a new workspace automatically if one doesn''t exist", "It is only valid inside a variable block, not a resource block"]', 1, 'terraform.workspace is a read-only value equal to the name of whichever workspace is currently selected (via terraform workspace select). It''s commonly used exactly this way -- as a map key -- to vary settings like instance size per environment without duplicating the whole configuration.', 'intermediate'),
('devops', 'terraform', 'intermediate', 'In a dynamic "ingress" block with for_each = var.ingress_rules, what does ingress.value refer to inside the nested content block?', '["The static string "ingress"", "The current element of the list/map being iterated -- e.g. ingress.value.port refers to the port field of the current ingress rule object", "The total count of items in ingress_rules", "It always refers to the first item in the list, regardless of iteration"]', 1, 'Inside a dynamic block, the block''s own name becomes the iterator variable -- ingress.value is the current item from for_each, and ingress.key is its index or map key, mirroring how for_each works on resources.', 'intermediate'),
('devops', 'terraform', 'intermediate', 'What is the practical effect of setting prevent_destroy = true in a resource''s lifecycle block?', '["It silently skips the resource during terraform destroy with no error", "Terraform will error out and refuse to proceed if a plan or apply would destroy that resource, protecting it from accidental deletion", "It prevents the resource from ever being modified, only created once", "It only applies during terraform plan, not terraform apply"]', 1, 'This is a safety guard commonly used on production databases and other resources where accidental deletion would be catastrophic -- Terraform will halt with an error rather than destroying the resource, even if -auto-approve is used.', 'intermediate'),
('devops', 'terraform', 'intermediate', 'What problem does a data "terraform_remote_state" "vpc" block solve?', '["It duplicates the entire remote state file locally for faster reads", "It lets one Terraform configuration read the outputs of a different, separately-applied Terraform configuration''s state (e.g. a VPC stack''s subnet IDs), enabling cross-stack references without merging everything into one giant configuration", "It automatically imports every resource from another state file into the current one", "It is used to migrate state between different backend types"]', 1, 'Splitting infrastructure into separate state files (e.g. one for networking, one per service) is a common pattern for blast-radius control; terraform_remote_state is how a downstream config reads specific outputs (like private_subnets) from an upstream state without owning those resources itself.', 'advanced'),

-- ---------- devops/terraform/advanced ----------
('devops', 'terraform', 'advanced', 'When declaring a module block with source = "terraform-aws-modules/vpc/aws" and version = "~> 5.0", why include the version constraint for a registry module specifically?', '["Registry modules ignore version constraints entirely", "Without pinning, a later terraform init could pull a newer major version of the module with breaking changes to its inputs/outputs, unexpectedly changing what gets applied", "Version constraints are required for local modules but meaningless for registry modules", "It only affects documentation generation, not actual behavior"]', 1, 'Registry modules are versioned independently of your own code. Pinning to a range like ~> 5.0 gets you compatible patch/minor updates while blocking an unreviewed jump to a new major version that could restructure the module''s interface.', 'advanced'),
('devops', 'terraform', 'advanced', 'What is the purpose of enabling versioning on the S3 bucket used as a Terraform backend (aws_s3_bucket_versioning)?', '["It speeds up state file reads", "It keeps a full history of every past state file version, so a corrupted or bad state write can be recovered by restoring a previous object version", "It is required for DynamoDB locking to function", "It automatically encrypts the state file"]', 1, 'S3 versioning means every write to the state object creates a new version rather than overwriting it destructively -- if a bad apply or manual edit corrupts state, a previous good version can be restored.', 'advanced'),
('devops', 'terraform', 'advanced', 'In the example Terraform GitHub Actions workflow, why does the job request permissions: id-token: write?', '["It is required to write log output to the console", "It allows the workflow to request an OIDC token from GitHub, which is then exchanged with AWS (via configure-aws-credentials) for temporary credentials -- no static AWS keys stored in the repo", "It grants write access to the GitHub repository''s issues", "It is unrelated to AWS and only affects artifact uploads"]', 1, 'id-token: write is the permission that lets a GitHub Actions job mint a short-lived OIDC token identifying the workflow run; aws-actions/configure-aws-credentials then presents that token to AWS STS to assume a role, avoiding any long-lived AWS secret in GitHub.', 'advanced'),
('devops', 'terraform', 'advanced', 'What does terraform force-unlock <lock-id> do, and why is it dangerous to run without first confirming no apply is actually running?', '["It permanently deletes the state file", "It manually clears a state lock left behind by a crashed or interrupted apply -- if another apply IS actually still running, force-unlocking lets a second apply start concurrently and risk corrupting state", "It forces an immediate apply, skipping the plan step", "It only works on local state, never on remote backends"]', 1, 'A lock is supposed to be the safeguard against two concurrent applies. force-unlock exists for the case where a crash left a stale lock behind, but running it while an apply is genuinely still in progress defeats the entire purpose of locking.', 'advanced'),
('devops', 'terraform', 'advanced', 'Why is terraform apply -target=module.vpc described as "dangerous -- use sparingly" rather than a routine tool?', '["It always fails when targeting a module instead of a single resource", "Targeted applies only update the specified resource(s) and skip evaluating the rest of the configuration''s dependency graph, which can leave the overall infrastructure in a state that doesn''t match what a full plan would produce", "It requires a paid Terraform Cloud license to use", "-target only works with the local backend, never with remote state"]', 1, 'Because -target bypasses Terraform''s normal full-graph evaluation, repeated or habitual use of it can let configuration and real infrastructure drift out of sync in ways a subsequent unrestricted plan/apply then has to reconcile -- it is meant for emergency/surgical fixes, not routine workflow.', 'advanced'),

-- ---------- devops/ansible/overview ----------
('devops', 'ansible', 'overview', 'Why is Ansible described as "agentless," and what actually runs on a managed node during a playbook run?', '["Ansible installs a lightweight permanent daemon on every managed node", "No persistent agent is installed -- Ansible connects over SSH, temporarily copies a Python module to the target, executes it, returns the result, and cleans up, leaving nothing running afterward", "Managed nodes must run a Docker container for Ansible to work", "Agentless means Ansible only works on cloud VMs, not physical servers"]', 1, 'This statelessness from the target''s perspective is the core architectural difference from agent-based tools like Chef or Puppet, which require a persistent client process installed and kept running on every managed node.', 'beginner'),
('devops', 'ansible', 'overview', 'What does it mean for an Ansible module to be idempotent, using apt: name=nginx state=present as the example?', '["The task always reinstalls nginx every time the playbook runs, to guarantee freshness", "Running the task repeatedly produces the same end state -- if nginx is already installed and present, running it again makes no change and reports "ok" instead of "changed"", "Idempotent tasks can only be run once per managed node, ever", "It means the module ignores errors automatically"]', 1, 'Idempotency is why Ansible playbooks can be run safely and repeatedly (after failures, on a schedule, in CI) -- a correctly idempotent module checks current state first and only acts if a change is actually needed.', 'beginner'),
('devops', 'ansible', 'overview', 'What is the key difference between static and dynamic inventory in Ansible?', '["Static inventory only works with YAML, dynamic only works with INI", "Static inventory is a fixed file listing hosts; dynamic inventory is generated in real time by querying cloud provider APIs (AWS, Azure, GCP), so it automatically reflects currently-running instances", "Dynamic inventory requires a paid Ansible Tower/AWX license", "Static inventory cannot be grouped, only dynamic inventory supports host groups"]', 1, 'In cloud environments where instances are created and destroyed frequently (autoscaling groups, ephemeral environments), a static file would go stale immediately -- dynamic inventory plugins query the cloud API at run time instead.', 'beginner'),
('devops', 'ansible', 'overview', 'What problem does Ansible Vault solve?', '["It replaces the need for SSH keys entirely", "It encrypts sensitive data (passwords, API keys, certificates) inside YAML files, so secrets can be safely committed to version control alongside playbooks and decrypted only at run time", "It is a package repository for community-contributed roles", "It automatically rotates all secrets on a schedule"]', 1, 'Without Vault, secrets needed by a playbook would either have to live in plaintext in the repo (a real risk) or be managed completely outside of Ansible. Vault encrypts the file itself, decrypting it transparently when a correct password/vault-id is supplied at run time.', 'intermediate'),
('devops', 'ansible', 'overview', 'Per the comparison of configuration management tools, what distinguishes Ansible from Chef and Puppet in terms of infrastructure requirements?', '["Ansible requires a dedicated agent process (chef-client equivalent) on every managed node, same as Chef and Puppet", "Chef and Puppet both require an agent installed on managed nodes; Ansible needs only SSH access and Python already present on the target, no agent installation", "Puppet is agentless while Ansible and Chef both require agents", "All three tools are functionally identical in their agent requirements"]', 1, 'This is the single biggest practical differentiator driving Ansible adoption for teams managing existing infrastructure -- there''s no rollout step of installing and maintaining an agent across a fleet before automation can begin.', 'intermediate'),

-- ---------- devops/ansible/fundamentals ----------
('devops', 'ansible', 'fundamentals', 'In the ad-hoc command ansible webservers -m yum -a "name=httpd state=present" --become, what does --become do?', '["It runs the command only on hosts named "webservers"", "It escalates privileges (typically to sudo/root) for that command, needed since installing packages usually requires root", "It creates a new host group called "become"", "It forces the module to run in check mode without making changes"]', 1, 'become is Ansible''s privilege escalation mechanism -- without it, a task that needs root (like installing a package via yum) would fail with a permissions error on a non-root connection user.', 'beginner'),
('devops', 'ansible', 'fundamentals', 'What does setting pipelining = True under [ssh_connection] in ansible.cfg do, and why is it commonly recommended?', '["It runs multiple playbooks in parallel", "It reduces the number of SSH operations per task by executing modules without transferring them as separate files first, meaningfully speeding up playbook execution (often 10-30%)", "It enables pipe (|) syntax inside Jinja2 templates", "It is required for any playbook using the shell module"]', 1, 'Without pipelining, Ansible has to write the module to a temporary file on the remote host over a separate connection before executing it, which is slower over high-latency connections -- pipelining avoids that extra round trip.', 'intermediate'),
('devops', 'ansible', 'fundamentals', 'In a playbook task, what triggers a handler to run, and when does it actually execute?', '["Handlers run before every task automatically, regardless of notify", "A task with notify: <handler name> marks that handler as needing to run, but the handler only actually executes once, at the end of the play (not immediately when notified)", "Handlers run immediately and can be triggered multiple times per play if notified multiple times", "Handlers require a separate playbook file to be defined"]', 1, 'This deferred, once-per-play execution is intentional -- it means notifying a handler like "restart nginx" from five different tasks in the same play still only restarts nginx once at the end, not five times.', 'intermediate'),
('devops', 'ansible', 'fundamentals', 'In an inventory file, what does a [webservers:vars] section do?', '["It defines a new host group called "webservers:vars"", "It sets variables that apply to every host inside the [webservers] group, such as a shared ansible_user or python interpreter path", "It lists variable names without values, as documentation only", "It is only valid in dynamic inventory, not static INI files"]', 1, 'The :vars suffix on a group name is INI-inventory syntax for group-scoped variables -- every host inside [webservers] inherits whatever is defined in the corresponding [webservers:vars] block.', 'beginner'),
('devops', 'ansible', 'fundamentals', 'In a PLAY RECAP summary, what does a nonzero "skipped" count for a host mean?', '["That host failed to connect via SSH", "One or more tasks had a when: condition that evaluated to false for that host, so the task was not executed for it", "The host was excluded from the inventory entirely", "The playbook crashed before reaching that host"]', 1, 'skipped tasks are a normal, expected outcome of conditional logic (when:) -- it means the condition correctly determined the task didn''t apply to that particular host, not that something went wrong.', 'beginner'),

-- ---------- devops/ansible/intermediate ----------
('devops', 'ansible', 'intermediate', 'What is the functional difference between loading variables with vars_files and with include_vars?', '["They are exactly equivalent, just different syntax for the same behavior", "vars_files preprocesses and loads variables once at playbook start; include_vars loads variables dynamically at the point in task execution where it appears, which matters if the file path depends on a runtime condition", "include_vars can only load JSON files, vars_files only loads YAML", "vars_files works on remote hosts, include_vars only works on the control node"]', 1, 'Because vars_files is resolved before the play starts, it can''t depend on facts gathered during the play. include_vars runs as a task, so it can be placed conditionally or after facts are known, at the cost of being less immediately obvious than a static vars_files declaration.', 'intermediate'),
('devops', 'ansible', 'intermediate', 'Why does looping directly over a dictionary with loop: "{{ employee }}" fail in Ansible, and what is the fix?', '["Dictionaries cannot be used in Ansible at all", "loop requires a list, not a dictionary -- the dict2items filter must be used to convert the dictionary into a list of {key, value} objects first: loop: "{{ employee | dict2items }}"", "The fix is to rename the variable to something Ansible reserves for dictionaries", "with_items must be used instead, loop never supports dictionaries even with a filter"]', 1, 'This is a well-known Ansible gotcha -- the error message is literally "Invalid data passed to \'loop\', it requires a list". dict2items produces items with .key and .value attributes usable inside the loop body.', 'intermediate'),
('devops', 'ansible', 'intermediate', 'What is the practical difference between import_playbook and include (dynamic include) in Ansible?', '["They behave identically in every situation", "import is static and processed at parse time before the playbook runs; include is dynamic and processed at execution time as the playbook is running, which matters when the included file path depends on a runtime variable", "include can only be used for playbooks, import only for tasks", "import always requires an absolute file path, include does not"]', 1, 'Because import is resolved before execution starts, it can''t use a variable determined mid-run to pick which file to load -- that''s exactly the case dynamic include exists for, at the cost of some static-analysis capability (like --list-tasks not being able to fully preview a dynamic include ahead of time).', 'intermediate'),
('devops', 'ansible', 'intermediate', 'In a block/rescue/always structure, what happens to the rescue section if a task inside the block fails but has ignore_errors: yes set on it?', '["rescue always runs regardless of ignore_errors", "rescue does NOT run, because ignore_errors suppressed the failure before the block''s own failure-handling logic ever triggered -- the task is treated as not having failed", "The play immediately aborts instead of running rescue", "ignore_errors and rescue cannot be used in the same block, Ansible raises a syntax error"]', 1, 'ignore_errors and block/rescue solve overlapping but different problems -- ignore_errors makes a task''s failure be treated as if it succeeded (so rescue never even sees a failure to react to), whereas rescue is meant to catch and react to a real failure.', 'advanced'),
('devops', 'ansible', 'intermediate', 'What is required for a custom fact file to actually be picked up by Ansible as ansible_local.<name>?', '["Any file placed anywhere in /etc/ansible works automatically", "The file must be placed in /etc/ansible/facts.d/ on the managed node and have a .fact extension; its contents (INI-style) then become accessible under ansible_local.<filename_without_extension>.<section>.<key>", "Custom facts must be registered as Ansible Galaxy roles first", "Facts.d files must be written in YAML, not INI format"]', 1, 'This is a specific, easy-to-miss requirement -- both the directory (/etc/ansible/facts.d/) and the .fact extension are mandatory for Ansible''s fact-gathering step to discover and parse the file into ansible_local.', 'advanced'),

-- ---------- devops/ansible/advanced ----------
('devops', 'ansible', 'advanced', 'When running ansible-vault rekey on an encrypted file, what must you provide, in what order?', '["Only the new password -- the old one is not needed", "The current (old) vault password first, to prove access, followed by the new password to re-encrypt the file with", "Both passwords simultaneously in a single prompt", "rekey does not require any password, it uses the SSH key instead"]', 1, 'Vault requires proving you can already decrypt the file (old password) before it will let you re-encrypt it with a new one -- this prevents rekey from being usable as a way to lock legitimate users out or bypass the existing encryption.', 'intermediate'),
('devops', 'ansible', 'advanced', 'In an Ansible role''s directory structure, which has HIGHER precedence when the same variable is defined in both: vars/main.yml or defaults/main.yml?', '["defaults/ always wins, regardless of vars/", "vars/main.yml has higher precedence -- defaults/ is specifically the lowest-precedence layer, meant to be easily overridden by role callers, while vars/ is meant to hold values the role itself relies on", "They have identical precedence and Ansible raises an error on conflict", "Precedence depends on alphabetical directory order"]', 1, 'This is intentional design: defaults/ exists specifically so a role''s consumer can override sensible starting values (e.g. via play-level vars or -e), whereas vars/ is for values the role author intends to be much harder to override.', 'advanced'),
('devops', 'ansible', 'advanced', 'In an AWS EC2 dynamic inventory YAML file, what does a keyed_groups entry like { key: tags.Environment, prefix: env } do?', '["It filters out all instances that don''t have an Environment tag", "It automatically creates inventory groups named env_<value> based on each instance''s Environment tag value (e.g. env_production, env_staging), without manually maintaining those groups", "It sets an environment variable named env on the control node", "It requires the AWS instance to already belong to a group with that exact name"]', 1, 'keyed_groups is how dynamic inventory plugins turn arbitrary cloud metadata (tags, instance type, region) into usable Ansible groups automatically, so playbooks can target e.g. hosts: env_production without static group membership lists.', 'advanced'),
('devops', 'ansible', 'advanced', 'What does running ansible-playbook playbook.yml --check actually do, and what is its limitation?', '["It permanently applies all changes and then verifies they were correct", "It performs a dry run -- reporting what WOULD change without making any real changes -- but some modules (especially those wrapping shell/command, or with complex external state) cannot accurately predict their own outcome in check mode", "It only checks YAML syntax, without evaluating any task logic", "It requires --diff to be passed together, otherwise it has no effect"]', 1, '--check is extremely useful for previewing a playbook''s effect before running it for real, but it is not a guarantee -- modules that shell out to external commands often can''t truly know what those commands would do without actually running them, so check-mode output for those tasks can be incomplete or wrong.', 'advanced'),
('devops', 'ansible', 'advanced', 'What is the practical difference between import_role and include_role when applying a role conditionally with when:?', '["There is no difference -- both behave identically with when:", "import_role is static (resolved at parse time), so a when: condition on it applies to every individual task inside the role rather than skipping the role as a single unit; include_role is dynamic and evaluates the condition once, more intuitively skipping the whole role", "when: cannot be used with either import_role or include_role", "import_role always ignores when: conditions entirely"]', 1, 'This is a genuinely confusing gotcha in Ansible -- because import_role expands statically before execution, attaching when: to it applies that same condition individually to every task the role contains, which is usually not what someone expects when they write "skip this role conditionally."', 'advanced'),

-- ---------- devops/helm/overview ----------
('devops', 'helm', 'overview', 'What problem does Helm solve that plain kubectl apply of raw YAML files does not?', '["Helm makes Kubernetes YAML files run faster", "Helm packages a full application''s Kubernetes manifests as a reusable, configurable unit (a Chart) with defaults you can override per environment, tracked as a Release with upgrade/rollback history -- avoiding dozens of hand-maintained, drifting YAML files per environment", "Helm replaces the need for a Kubernetes cluster entirely", "kubectl apply and Helm are functionally identical, Helm is just a GUI wrapper"]', 1, 'Without Helm, deploying the same application across dev/staging/prod with slightly different settings usually means maintaining near-duplicate YAML files per environment that gradually drift apart -- Helm''s values.yaml + overrides model solves that directly.', 'beginner'),
('devops', 'helm', 'overview', 'In a CI/CD pipeline, why is helm upgrade --install used instead of plain helm install?', '["upgrade --install is faster at rendering templates", "helm install fails if the release already exists; helm upgrade --install is idempotent -- it installs on the first run and upgrades on every subsequent run, so the same command works whether or not the release already exists", "upgrade --install skips running any hooks, making it safer for automation", "install and upgrade --install are exactly the same command, just an alias"]', 1, 'This idempotency is exactly what CI/CD needs -- a pipeline that runs the same deploy command on every push shouldn''t have to first check whether this is the very first deploy or the hundredth.', 'beginner'),
('devops', 'helm', 'overview', 'What does the --atomic flag do during a helm upgrade, and why is it recommended for production CI/CD?', '["It makes the upgrade run faster by skipping validation", "If the deployment fails to become healthy within the timeout, Helm automatically rolls back to the previous successful release, instead of leaving the release in a broken, half-upgraded state", "It prevents any other Helm command from running until the upgrade finishes", "It atomically merges values from all -f files into one before applying"]', 1, 'Without --atomic, a failed upgrade can leave a release stuck in a failed/partial state requiring manual rollback. --atomic makes failure self-healing by automatically reverting to the last known-good release.', 'intermediate'),
('devops', 'helm', 'overview', 'Why should real secret values never be placed directly in a chart''s values.yaml?', '["values.yaml has a hard size limit that secrets would exceed", "values.yaml is typically committed to Git alongside the rest of the chart, so any real secret placed there would be permanently exposed in version control history", "Helm automatically encrypts values.yaml on save, but only if it contains no secrets", "Kubernetes rejects any values.yaml file containing a field named password or key"]', 1, 'This is the same reasoning as never hardcoding secrets in application source code -- values.yaml is chart content meant to be reviewed and versioned, not a secret store. Real secrets should come from CI-time --set overrides sourced from a secret manager, External Secrets Operator, sealed-secrets, or a SOPS-encrypted values file via the Helm Secrets plugin.', 'intermediate'),
('devops', 'helm', 'overview', 'What does helm template ./my-chart --values values-prod.yaml do, and how does it differ from helm install?', '["It is identical to helm install but slower", "It renders the chart''s templates into plain Kubernetes YAML locally, WITHOUT installing anything into a cluster or creating a Helm release -- useful for review, debugging, or piping into kubectl/GitOps tooling", "It only works for charts that have no dependencies", "It permanently modifies the chart''s values.yaml file with the rendered output"]', 1, 'This is the standard way to inspect exactly what manifests a given values combination would produce before actually applying anything, and it''s also how some GitOps workflows render Helm charts to plain YAML ahead of time rather than running Helm at deploy time.', 'beginner'),

-- ---------- devops/helm/fundamentals ----------
('devops', 'helm', 'fundamentals', 'In a Helm chart directory, what is the purpose of _helpers.tpl specifically, compared to files directly under templates/?', '["It is the only file Helm actually reads; all others are ignored", "_helpers.tpl defines reusable named templates (like a shared label block or name-generation logic) that other template files call via {{ include \\"name\\" . }} -- it is not rendered into its own Kubernetes manifest", "It stores the default values for the chart, replacing values.yaml", "It must contain exactly one Kubernetes resource definition, same as any other templates/ file"]', 1, 'Files under templates/ are each expected to render into Kubernetes manifests (or be empty); _helpers.tpl is a convention for defining named template snippets that get included elsewhere, avoiding repetition of things like standard label blocks across every manifest.', 'intermediate'),
('devops', 'helm', 'fundamentals', 'Before installing a chart from a repository, what does helm show values bitnami/nginx let you do?', '["It installs the chart with default values immediately", "It displays the chart''s full default values.yaml content, so you can see every configurable option before deciding what to override with --values or --set", "It shows the values currently applied to an existing, already-installed release", "It only works for locally-created charts, not repository charts"]', 1, 'This is the standard way to discover what a third-party chart actually supports configuring before writing your own override file -- helm get values, by contrast, shows values for an already-installed release rather than an uninstalled chart.', 'beginner'),
('devops', 'helm', 'fundamentals', 'Why should helm lint be run before packaging or publishing a chart?', '["It automatically fixes any errors found in the chart", "It checks the chart for structural and syntax issues (like malformed YAML or template errors) that could otherwise only be caught when someone tries to actually install it and it fails", "It is required before helm create will scaffold a new chart", "lint only checks values.yaml, not the templates directory"]', 1, 'Catching a broken template at lint time, before packaging and distributing the chart, is far cheaper than having a consumer''s helm install fail with a cryptic template rendering error.', 'beginner'),
('devops', 'helm', 'fundamentals', 'What information does helm history my-nginx give you, and how does it relate to helm rollback?', '["It shows CPU/memory usage history for the release''s pods", "It lists the revision history of a release (each install/upgrade as a numbered revision), which tells you which revision number to pass to helm rollback my-nginx <N> to go back to", "It shows the Git commit history of the chart source repository", "History is only available if the --atomic flag was used during install"]', 1, 'Every helm install/upgrade against a release creates a new numbered revision that Helm stores (as a Secret in the cluster by default); helm history lists them so you know exactly which revision number represents the state you want to roll back to.', 'beginner'),
('devops', 'helm', 'fundamentals', 'What is the purpose of pushing a packaged chart to an OCI registry with helm push myapp-1.2.0.tgz oci://ghcr.io/myorg/charts?', '["OCI registries are required for Helm to function at all, even locally", "It publishes the chart as an OCI artifact to a container-style registry, allowing it to be installed directly via helm install ... oci://... without needing a separate classic Helm chart repository (index.yaml-based)", "It converts the chart into a Docker image that can be run directly", "It permanently deletes the chart from local storage after pushing"]', 1, 'Modern Helm (3.8+) supports OCI registries as a first-class alternative to the older HTTP index.yaml-based chart repository model, letting teams reuse existing container registry infrastructure (ECR, GHCR, ACR) to also host charts.', 'intermediate'),

-- ---------- devops/helm/intermediate ----------
('devops', 'helm', 'intermediate', 'In a Chart.yaml dependencies entry, what does condition: postgresql.enabled do?', '["It makes the dependency mandatory regardless of any values setting", "It ties the subchart''s installation to a boolean value in the parent chart''s values.yaml (postgresql.enabled) -- the dependency is only actually installed if that value is set to true", "It sets the PostgreSQL version to whatever "enabled" resolves to", "condition only affects documentation, dependencies always install regardless"]', 1, 'This is how a chart offers an optional bundled dependency (like an in-cluster PostgreSQL for dev/test) that a consumer can turn off entirely by setting postgresql.enabled: false in their own values, e.g. when using an external managed database in production instead.', 'intermediate'),
('devops', 'helm', 'intermediate', 'What does the alias: cache field do on a dependency entry for a chart named redis?', '["It renames the actual Redis application running inside the pod", "It lets the parent chart reference this dependency''s values under a different key (cache: instead of redis:) in its own values.yaml -- useful when using the same chart twice for different purposes, or for a more meaningful name", "It creates a DNS alias/Service pointing at the Redis pods", "alias is required for every dependency, not optional"]', 1, 'Aliasing is what makes it possible to declare the same dependency chart more than once under different roles (e.g. two redis dependencies aliased as cache and sessions), each configured independently in the parent''s values.yaml.', 'advanced'),
('devops', 'helm', 'intermediate', 'What do the "helm.sh/hook-weight" and "helm.sh/hook-delete-policy" annotations control on a Helm hook resource?', '["hook-weight sets CPU resource weight; hook-delete-policy controls pod eviction priority", "hook-weight determines execution order among multiple hooks of the same type (lower runs first); hook-delete-policy determines when the hook resource itself gets cleaned up (e.g. before the hook re-runs, or after it succeeds)", "Both annotations are purely informational and have no functional effect on hook behavior", "hook-weight only matters for pre-install hooks, not any other hook type"]', 1, 'A database-migration Job as a pre-upgrade hook, for example, commonly uses a low hook-weight to guarantee it runs before other pre-upgrade hooks, and hook-delete-policy: before-hook-creation to clean up the previous run''s Job object before creating a new one.', 'advanced'),
('devops', 'helm', 'intermediate', 'What does helm dependency update my-app/ actually do?', '["It upgrades the currently-installed release to the latest chart version", "It reads Chart.yaml''s dependencies list and downloads the specified chart versions into the chart''s charts/ subdirectory, so they''re available when the chart is installed or templated", "It updates the parent chart''s own version number in Chart.yaml automatically", "It pushes the chart''s dependencies to a remote registry"]', 1, 'Chart dependencies are declared (name/version/repository) but not automatically fetched -- helm dependency update is the step that actually downloads the matching chart archives into charts/, which is what helm install/template then actually use.', 'beginner'),
('devops', 'helm', 'intermediate', 'In a Helm named template like {{- define "myapp.fullname" -}} ... {{- end }}, what does {{ include "myapp.fullname" . }} do when used elsewhere in a manifest?', '["It only works within the same file where the template was defined", "It calls the named template, passing the current context (.) into it, and inserts the resulting rendered string wherever the include call appears -- commonly used to build a consistent, DRY resource-name across templates", "It includes the literal text of _helpers.tpl at the top of the current file", "include can only be used for labels, never for names or other fields"]', 1, 'Named templates defined with define/end can be called with include from ANY template file in the chart, regardless of which file defined them -- this is exactly how logic like the fullname/labels convention stays consistent and DRY across deployment.yaml, service.yaml, etc.', 'intermediate'),

-- ---------- devops/helm/advanced ----------
('devops', 'helm', 'advanced', 'What distinguishes a library chart (type: library in Chart.yaml) from a normal application chart?', '["Library charts run faster because they skip validation", "A library chart cannot be installed directly (helm install would fail on it) -- it exists purely to provide shared named templates that other, consuming charts declare as a dependency and call via include", "Library charts are only usable with Helmfile, never with plain helm CLI", "type: library is purely cosmetic and has no functional effect"]', 1, 'Library charts are how organizations share common templating logic (a standard Deployment shape, common labels, etc.) across many application charts without copy-pasting the same _helpers.tpl content into every chart repo.', 'advanced'),
('devops', 'helm', 'advanced', 'Why would a team render a chart with helm template ./chart --values values-prod.yaml > manifests/prod/my-app.yaml rather than deploying directly with helm install/upgrade?', '["helm template is required before helm install will work at all", "Some GitOps workflows want plain, reviewable Kubernetes YAML committed to a repo (for a tool like Argo CD/Flux to apply) rather than having Helm itself talk to the cluster at deploy time -- rendering ahead of time produces exactly that", "It permanently converts the chart format so it can never be installed with Helm again", "It is only useful for charts that have zero templates"]', 1, 'This pattern decouples "what Kubernetes manifests should exist" (produced by Helm rendering) from "how they get applied to the cluster" (handled by a separate GitOps controller), which some teams prefer over letting Helm itself perform live cluster operations.', 'advanced'),
('devops', 'helm', 'advanced', 'In a Helmfile releases entry, what does specifying values: [infra/ingress-values.yaml] alongside chart and version accomplish across an entire platform?', '["It replaces the need for a chart entirely -- Helmfile installs raw values as manifests", "Helmfile lets many Helm releases (each potentially a different chart, version, and values file) be declared together in one file, so a single helmfile sync command can install/upgrade an entire platform''s worth of releases consistently instead of running many separate helm upgrade commands by hand", "It is only used for local testing, never in production", "Helmfile requires OCI registries; it cannot reference traditional chart repositories"]', 1, 'Helmfile addresses the problem of coordinating many interdependent Helm releases (ingress controller, cert-manager, the application itself, etc.) as one declarative unit rather than a sequence of manually-run helm commands that have to be kept in sync by hand.', 'advanced'),
('devops', 'helm', 'advanced', 'Which of the following is NOT one of the recommended chart security best practices for a production workload?', '["Set resources limits so a misbehaving pod can''t exhaust node capacity", "Set runAsNonRoot: true and drop all Linux capabilities in the securityContext", "Hardcode secret values directly into values.yaml so they deploy correctly every time without depending on external secret stores", "Use secretKeyRef / an external secrets mechanism instead of plaintext values for sensitive data"]', 2, 'Hardcoding secrets into values.yaml is the opposite of a security best practice -- values.yaml is chart content typically committed to version control, so real secrets belong in a Kubernetes Secret referenced via secretKeyRef, or fetched at deploy time from an external secret manager, never baked directly into the chart''s values.', 'intermediate'),
('devops', 'helm', 'advanced', 'What is the purpose of helm package --sign --key ''Your Name'' followed later by helm verify?', '["Signing compresses the chart into a smaller archive", "It cryptographically signs the packaged chart with GPG so that anyone installing it later can run helm verify to confirm the chart hasn''t been tampered with and genuinely came from the claimed signer", "verify checks that all required values are set before installation", "Signing is required before a chart can be pushed to any registry, OCI or classic"]', 1, 'Chart signing addresses supply-chain integrity -- without it, there''s no cryptographic way for a consumer to confirm a downloaded .tgz chart file matches what the original author actually published and wasn''t altered in transit or by a compromised mirror.', 'advanced')

ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
