-- ============================================================
-- Quiz coverage for devops/git (overview, fundamentals -- the
-- only two tabs this batch actually ships/unshadows) and
-- devops/nginx/overview (grounded in infrastructure/nginx's
-- overview.md content, which is what's actually live there --
-- devops/nginx's registry entry was deliberately left pointing
-- at infrastructure/nginx since it's the better content).
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES

-- ---------- devops/git/overview ----------
('devops', 'git', 'overview', 'What is the actual difference between the working directory, the staging area, and the repository in Git?', '["They are three different names for the same thing", "Working directory is files on disk; staging area is a snapshot of what the NEXT commit will contain; repository is the committed history", "Staging area only exists when using git add -p", "Repository refers only to the remote, never the local .git folder"]', 1, 'git add moves changes from working directory into staging; git commit turns whatever is currently staged into a permanent snapshot in the repository -- editing a file after git add without re-adding it means the new edits are NOT in the next commit.', 'beginner'),
('devops', 'git', 'overview', 'Why does creating a new Git branch happen instantly, regardless of repository size?', '["Git only creates branches for small repositories", "A branch is just a lightweight, movable pointer to a commit -- creating one writes a small pointer file, not a copy of the codebase", "Branches are created lazily and only materialize on first commit", "Git compresses the repository before creating a branch"]', 1, 'This is why git branch/switch -c is instant even on a massive repository -- nothing is being copied, just a pointer reference.', 'beginner'),
('devops', 'git', 'overview', 'Using git diff main...feature/search (three dots), what exactly gets shown?', '["A full bidirectional diff between the two branch tips", "Only what changed ON the feature branch since it diverged from main -- excludes anything that landed on main afterward", "The same thing as two dots (main..feature/search)", "Nothing -- three-dot syntax is invalid"]', 1, 'Two-dot diff is a flat comparison between the two tips directly; three-dot diffs against the merge-base, showing only the feature branch''s own changes since divergence -- a common source of confusion between the two.', 'intermediate'),
('devops', 'git', 'overview', 'Why is .git/hooks/pre-commit not a reliable way to enforce a check across an entire team?', '["Pre-commit hooks are deprecated in current Git", "The hooks directory is not version-controlled -- committing a hook script to the repo does not distribute it to teammates or CI, each person must add it manually", "Pre-commit hooks can only check file size, nothing else", "Hooks require a paid Git hosting plan to function"]', 1, 'For team-wide enforcement, point core.hooksPath at a directory that IS tracked in the repo, or use a framework like Husky/the pre-commit framework that installs hooks as part of normal setup.', 'intermediate'),
('devops', 'git', 'overview', 'What is the safe, standard way to remove a secret that was accidentally committed and pushed to a remote?', '["Just delete the file and commit again -- the secret is gone from history automatically", "Rotate the secret immediately (assume compromised), THEN remove it from history using a tool like BFG Repo Cleaner or git filter-repo on a fresh clone, then have the team re-clone", "Force-push an empty commit over it", "Nothing can be done once a commit is pushed"]', 1, 'Deleting the file in a new commit does not remove it from history -- anyone with access to the repo can still find it in an old commit. Rotating the secret first is critical since the old value must be treated as compromised regardless of cleanup.', 'advanced'),

-- ---------- devops/git/fundamentals ----------
('devops', 'git', 'fundamentals', 'What is the key practical difference between git merge and git rebase?', '["They produce identical results always", "Merge creates a new commit preserving both branches'' history exactly as it happened; rebase replays commits on top of another branch, producing linear history but rewriting commit hashes", "Rebase is always safer than merge", "Merge can only be used on the main branch"]', 1, 'The practical rule: never rebase commits that have already been pushed and that someone else might have pulled -- rewriting hashes that others already have creates painful history divergence.', 'intermediate'),
('devops', 'git', 'fundamentals', 'What is the difference between git revert and git reset for undoing a commit?', '["They are interchangeable in every situation", "revert creates a NEW commit undoing a previous one (safe for shared/pushed history); reset rewrites what the branch pointer refers to (only safe for purely local, unpushed commits)", "reset only works on the most recent commit", "revert requires admin permissions on GitHub"]', 1, 'revert never rewrites existing history, just adds a compensating commit -- safe even if others have already pulled the commit being undone. reset actually moves the branch pointer, which is dangerous once pushed and pulled by others.', 'intermediate'),
('devops', 'git', 'fundamentals', 'What does git stash actually do?', '["Permanently deletes uncommitted changes", "Temporarily saves uncommitted changes and restores the working directory to the last commit, so you can switch branches cleanly without committing half-finished work", "Creates a new branch automatically", "Only works on staged changes, never unstaged ones"]', 1, 'The common use case: mid-way through changes, need to switch branches for something urgent, not ready to commit yet -- stash clears the working directory without losing anything.', 'beginner'),
('devops', 'git', 'fundamentals', 'Why should annotated tags (git tag -a) be preferred over lightweight tags for marking an actual release?', '["Lightweight tags are deprecated and no longer supported", "Annotated tags store metadata (tagger, date, message) that a lightweight tag doesn''t -- useful when someone needs to understand release history months later", "Lightweight tags cannot be pushed to a remote", "Annotated tags are required for CI/CD to function"]', 1, 'A lightweight tag is just a name pointing at a commit with no extra metadata; an annotated tag carries real information about the release itself.', 'intermediate'),
('devops', 'git', 'fundamentals', 'By default, does git push also push your local tags to the remote?', '["Yes, tags are always pushed automatically with commits", "No -- tags are NOT pushed automatically with a normal git push; use git push origin --tags or push the specific tag explicitly", "Only annotated tags are pushed automatically, lightweight tags are not", "Tags can only be pushed using a separate git tag-push command"]', 1, 'This is a common surprise -- creating a tag locally and running a normal git push does not send it to the remote; an explicit --tags (or naming the tag) is required.', 'intermediate'),

-- ---------- devops/nginx/overview ----------
('devops', 'nginx', 'overview', 'Why does nginx use dramatically less memory than a process-per-connection server model under high concurrent load?', '["nginx compresses all responses by default", "nginx uses an event-driven, asynchronous architecture with a small fixed number of worker processes handling many thousands of connections via non-blocking I/O, rather than one process/thread per connection", "nginx limits the total number of connections it accepts", "nginx caches all responses in memory automatically"]', 1, 'A worker isn''t blocked waiting on one slow client while it could be servicing others -- this is the core architectural reason nginx scales connection count so efficiently.', 'intermediate'),
('devops', 'nginx', 'overview', 'In an nginx reverse-proxy config, what happens if proxy_set_header Host $host is omitted?', '["Nothing changes -- Host is always forwarded automatically", "The backend receives whatever Host value nginx itself sends by default, not the actual client-requested hostname -- breaking anything backend-side that depends on the real Host (multi-tenant routing, generating URLs)", "The request is rejected with a 400 error", "SSL termination stops working"]', 1, 'This is one of several headers (along with X-Real-IP, X-Forwarded-For, X-Forwarded-Proto) that are close to mandatory for a real reverse-proxy setup, not optional extras.', 'intermediate'),
('devops', 'nginx', 'overview', 'Why is serving static files (images, CSS, JS) directly via nginx''s root/location block faster than routing them through the backend application?', '["Static files are automatically compressed by nginx but not by application servers", "Static assets never need application logic to serve -- nginx reading and returning a file directly from disk is faster and cheaper than round-tripping through an app server that would do the same read anyway", "Backend application servers cannot serve files at all", "nginx caches static files in a way application servers cannot"]', 1, 'This is one of the most common, highest-impact nginx optimizations -- a dedicated location block for static assets bypasses the backend entirely for anything that does not need real application logic.', 'beginner'),
('devops', 'nginx', 'overview', 'What is the correct redirect target variable for an HTTP-to-HTTPS redirect, and why does it matter?', '["$server_name -- it always reflects the actual requested host", "$host -- $server_name only reflects the FIRST name declared in that server block''s server_name directive, not necessarily what the client actually requested", "Either variable works identically in all cases", "Neither variable exists in nginx; use $http_host instead exclusively"]', 1, 'Using $server_name breaks silently for server aliases, wildcard matches, or requests by IP address, since it does not reflect the actual Host header the client sent -- $host is the reliable choice.', 'advanced'),
('devops', 'nginx', 'overview', 'What must be true for nginx''s gzip compression to actually compress CSS/JS/JSON responses, not just HTML?', '["Nothing extra -- gzip on; compresses every response type by default", "gzip_types must explicitly list the additional MIME types (text/css, application/javascript, application/json, etc.) -- gzip on; alone only compresses text/html by default", "gzip only works with HTTP/2, never HTTP/1.1", "A separate gzip_static module must be compiled in, gzip on; has no effect otherwise"]', 1, 'This is a common, easy-to-miss misconfiguration -- gzip on; looks like it should be sufficient on its own, but the default gzip_types is text/html only.', 'intermediate')

ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
