-- ============================================================
-- /learn quiz: CBSE Class 10 English -- all 4 chapters: A Letter to
-- God, Nelson Mandela: Long Walk to Freedom, Two Stories About Flying,
-- Grammar and Writing Skills. Unlike Maths/Science, these chapters
-- carry no pyqYears badge -- this is a new scope (not badge-backing),
-- approved separately, using differentiated question styles: literature
-- comprehension (plot/character/theme recall grounded in the actual
-- fixed NCERT text) for the three story chapters, and objective
-- grammar-rule application for the fourth.
--
-- SOURCING: authored to match real CBSE Section-A exam style; NOT
-- copied from any official question paper. Literature questions are
-- grounded in the actual, stable plot/theme content of these
-- long-published NCERT "First Flight"/"Footprints without Feet"
-- stories (low factual-error risk since the text itself never
-- changes); grammar questions are objective rule-application, checked
-- against standard English grammar before writing.
--
-- Applied via @supabase/supabase-js, upsert(rows, { onConflict:
-- "academy_slug,technology_slug,section_slug,question", ignoreDuplicates:
-- true }) -- functionally identical to this file's ON CONFLICT clause.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES
('education', 'class-10/english', 'a-letter-to-god', 'What natural disaster destroys Lencho''s crop in "A Letter to God"?', '["A hailstorm", "A drought", "A flood", "A locust attack"]', 0, 'A sudden hailstorm ruins Lencho''s entire cornfield, driving him to write his letter asking God for help.', 'beginner'),
('education', 'class-10/english', 'a-letter-to-god', 'How much money does Lencho ask God for in his letter?', '["100 pesos", "70 pesos", "50 pesos", "120 pesos"]', 0, 'Lencho calculates he needs 100 pesos to resow his field and survive until the next harvest, and asks God for exactly that amount.', 'beginner'),
('education', 'class-10/english', 'a-letter-to-god', 'Who is moved by Lencho''s faith and decides to help him?', '["The postmaster", "The priest", "His neighbor", "A stranger"]', 0, 'The postmaster, touched by Lencho''s unwavering faith in receiving a reply from God, organizes a collection to help him.', 'beginner'),
('education', 'class-10/english', 'a-letter-to-god', 'How much money do the postmaster and his colleagues actually manage to collect for Lencho?', '["70 pesos", "100 pesos", "30 pesos", "50 pesos"]', 0, 'Despite their efforts, the postmaster and his colleagues could only gather 70 of the 100 pesos Lencho requested.', 'beginner'),
('education', 'class-10/english', 'a-letter-to-god', 'What does Lencho accuse the post office employees of, in his second letter?', '["Stealing part of the money", "Losing his letter", "Ignoring his request", "Mocking his faith"]', 0, 'Since 30 pesos were short of what he asked for, Lencho concludes the post office employees must have kept the rest for themselves, calling them "a bunch of crooks."', 'intermediate'),
('education', 'class-10/english', 'nelson-mandela', 'According to Mandela''s speech, courage is best described as:', '["The triumph over fear, not the absence of it", "The complete absence of fear", "Never feeling afraid", "Avoiding dangerous situations"]', 0, 'Mandela explicitly redefines courage as triumphing over fear rather than never experiencing it at all.', 'beginner'),
('education', 'class-10/english', 'nelson-mandela', 'Mandela describes his life as shaped by "twin obligations" -- freedom for himself and freedom for:', '["His people", "His family", "His political party", "His children"]', 0, 'Mandela speaks of his personal freedom being inseparable from the collective freedom of his people.', 'beginner'),
('education', 'class-10/english', 'nelson-mandela', 'According to Mandela, to be truly free means to live in a way that:', '["Respects and enhances the freedom of others", "Ignores the needs of others", "Focuses only on personal gain", "Avoids all responsibility"]', 0, 'Mandela states that true freedom is not merely casting off one''s own chains, but living so as to respect and enhance the freedom of others.', 'intermediate'),
('education', 'class-10/english', 'nelson-mandela', 'This extract from "Long Walk to Freedom" is set at which event in Mandela''s life?', '["His presidential inauguration", "His release from prison", "His trial", "His wedding"]', 0, 'The extract describes Mandela''s reflections delivered at his inauguration as President of South Africa.', 'beginner'),
('education', 'class-10/english', 'nelson-mandela', 'Mandela argues that the oppressor must also be liberated because oppression:', '["Robs the oppressor of humanity too", "Only harms the oppressed", "Has no effect on the oppressor", "Benefits the oppressor completely"]', 0, 'Mandela states that the oppressor is as much in need of liberation as the oppressed, since denying another''s humanity diminishes one''s own.', 'intermediate'),
('education', 'class-10/english', 'two-stories-flying', 'In "His First Flight," why is the young seagull initially afraid to fly?', '["He fears he doesn''t know how to fly", "He is injured", "He dislikes the sea", "He is too young by law"]', 0, 'The young seagull is terrified of the vast drop to the sea below and doubts his own ability to fly, despite his siblings already flying.', 'beginner'),
('education', 'class-10/english', 'two-stories-flying', 'What finally forces the young seagull to fly in "His First Flight"?', '["Hunger, after his family stops feeding him", "A predator attacks him", "A storm pushes him off the ledge", "His mother physically pushes him"]', 0, 'His family flies off and stops feeding him, and hunger eventually drives him to dive off the ledge and discover he can fly.', 'beginner'),
('education', 'class-10/english', 'two-stories-flying', 'In "Black Aeroplane," what problem does the narrator''s plane face while flying?', '["He flies into a severe storm and loses his bearings", "He runs out of fuel", "His radio breaks before takeoff", "He collides with a bird"]', 0, 'The narrator flies into a massive, unexpected storm over the English Channel, losing visibility and his sense of direction.', 'beginner'),
('education', 'class-10/english', 'two-stories-flying', 'In "Black Aeroplane," what guides the narrator''s plane safely through the storm?', '["A mysterious black aeroplane", "Air traffic control", "A fellow pilot on the radio", "His own memory of the route"]', 0, 'A mysterious black aeroplane appears and leads the narrator''s plane safely out of the storm to a runway.', 'beginner'),
('education', 'class-10/english', 'two-stories-flying', 'What surprising fact does the narrator learn about the black aeroplane at the end of the story?', '["No such plane was recorded as flying that night", "It was a spy plane", "It was his own future self", "It was a weather balloon"]', 0, 'The control tower confirms no other aircraft was recorded in the sky that night, leaving the black aeroplane''s true nature a mystery.', 'intermediate'),
('education', 'class-10/english', 'grammar-writing', 'Which of the following sentences is grammatically correct?', '["Neither of the boys has completed his homework.", "Neither of the boys have completed his homework.", "Neither of the boys has completed their homework.", "Neither of the boys having completed his homework."]', 0, '"Neither" is a singular subject and takes a singular verb ("has"), matched with the singular possessive "his."', 'intermediate'),
('education', 'class-10/english', 'grammar-writing', 'Which is the correctly punctuated salutation for a formal letter?', '["Dear Sir,", "Dear Sir.", "Dear Sir!", "Dear sir,"]', 0, 'A formal letter''s salutation is followed by a comma, with "Sir" capitalized as a form of address.', 'beginner'),
('education', 'class-10/english', 'grammar-writing', 'Choose the correct passive voice form of: "The teacher is checking the papers."', '["The papers are being checked by the teacher.", "The papers were checked by the teacher.", "The papers is being checked by the teacher.", "The papers being checked by the teacher."]', 0, 'Present continuous active ("is checking") converts to present continuous passive: "are being checked," matching the plural subject "papers."', 'intermediate'),
('education', 'class-10/english', 'grammar-writing', 'Which preposition correctly completes the sentence: "She is good ___ mathematics."?', '["at", "in", "on", "for"]', 0, '"Good at" is the standard idiomatic preposition used to describe skill in a subject.', 'beginner'),
('education', 'class-10/english', 'grammar-writing', 'Which of the following is an essential component of a formal notice?', '["The date of issue and the issuing authority''s signature", "A detailed personal opinion", "An informal greeting", "A long narrative introduction"]', 0, 'A formal notice must clearly state the date of issue and be signed by the issuing authority to be considered valid and official.', 'beginner')
ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
