-- ============================================================
-- /learn quiz: GATE CSE -- Operating Systems (4 chapters: Process
-- Management, Process Synchronisation, Memory Management, File
-- Systems) and DBMS (5 chapters: ER Model, Relational Algebra, SQL,
-- Normalisation, Transactions and Concurrency). Completes GATE CSE
-- alongside the DSA batch.
--
-- SOURCING: same disclosed limitation as every /learn quiz batch this
-- session -- authored to match real GATE CSE single-correct-MCQ style,
-- topic distribution, and difficulty for each chapter; NOT copied from
-- any official GATE question paper. Every claim below was independently
-- checked before writing.
--
-- Applied via @supabase/supabase-js, upsert(rows, { onConflict:
-- "academy_slug,technology_slug,section_slug,question", ignoreDuplicates:
-- true }) -- functionally identical to this file's ON CONFLICT clause.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES
('education', 'gate-cse/os', 'process-management', 'A Process Control Block (PCB) stores information such as:', '["Process state, program counter, CPU registers, and memory management info", "Only the process ID and nothing else", "Only the source code of the process", "The entire compiled binary of the program"]', 0, 'The PCB is the OS data structure holding all information the kernel needs to manage a process, including its state, program counter, CPU register values, and memory allocation details.', 'beginner'),
('education', 'gate-cse/os', 'process-management', 'The First-Come, First-Served (FCFS) CPU scheduling algorithm can suffer from a phenomenon known as the:', '["Convoy effect", "Starvation only", "Priority inversion", "Thrashing"]', 0, 'FCFS can cause the convoy effect, where a long process at the front of the queue makes many short processes wait unnecessarily long.', 'intermediate'),
('education', 'gate-cse/os', 'process-management', 'The Shortest Job First (SJF) scheduling algorithm is provably optimal for minimizing:', '["Average waiting time", "CPU utilization only", "Total execution time of all processes combined", "Number of context switches"]', 0, 'Among non-preemptive scheduling algorithms, SJF minimizes the average waiting time of the process queue.', 'intermediate'),
('education', 'gate-cse/os', 'process-management', 'The Round Robin CPU scheduling algorithm allocates the CPU to each process for a fixed:', '["Time quantum (slice)", "Priority level", "Number of I/O operations", "Memory allocation"]', 0, 'Round Robin cycles through the ready queue, giving each process a fixed time quantum before moving to the next, ensuring fairness among processes.', 'beginner'),
('education', 'gate-cse/os', 'process-management', 'A context switch primarily involves:', '["Saving the state of the currently running process and loading the state of the next process", "Permanently terminating the current process", "Allocating new physical memory to a process", "Compiling the next process''s source code"]', 0, 'A context switch saves the CPU state (registers, program counter, etc.) of the outgoing process and restores the saved state of the incoming process.', 'beginner'),
('education', 'gate-cse/os', 'synchronisation', 'A critical section refers to a segment of code where:', '["A process accesses shared resources that require mutual exclusion", "No shared resources are ever accessed", "Only read-only operations are permitted", "The process is guaranteed to run without interruption"]', 0, 'A critical section is code that accesses shared resources, requiring mutual exclusion so that no two processes execute it concurrently in a conflicting way.', 'beginner'),
('education', 'gate-cse/os', 'synchronisation', 'A semaphore is a synchronization tool used primarily to:', '["Control access to shared resources via wait and signal operations", "Compile source code faster", "Allocate physical memory pages", "Schedule processes by priority alone"]', 0, 'A semaphore is an integer variable manipulated only through atomic wait (P) and signal (V) operations, used to coordinate access to shared resources among processes.', 'beginner'),
('education', 'gate-cse/os', 'synchronisation', 'Peterson''s Solution provides a software-based mutual exclusion mechanism for:', '["Exactly two processes", "Any arbitrary number of processes", "A single process only", "Processes running on different machines"]', 0, 'Peterson''s Solution is a classic algorithm specifically designed to guarantee mutual exclusion between exactly two competing processes.', 'intermediate'),
('education', 'gate-cse/os', 'synchronisation', 'Which of the following is NOT one of the four necessary conditions for deadlock?', '["Preemption of resources", "Mutual exclusion", "Hold and wait", "Circular wait"]', 0, 'The four necessary (Coffman) conditions for deadlock are mutual exclusion, hold and wait, NO preemption, and circular wait -- preemption being possible is what PREVENTS deadlock, not a condition for causing it.', 'intermediate'),
('education', 'gate-cse/os', 'synchronisation', 'The Banker''s Algorithm is primarily used for:', '["Deadlock avoidance", "Deadlock detection after it occurs", "CPU scheduling", "Memory compaction"]', 0, 'The Banker''s Algorithm proactively checks whether granting a resource request would leave the system in a safe state, avoiding deadlock before it happens.', 'intermediate'),
('education', 'gate-cse/os', 'memory-management', 'Paging is a memory management scheme that primarily eliminates:', '["External fragmentation", "Internal fragmentation entirely", "The need for a page table", "The need for virtual memory"]', 0, 'By dividing memory into fixed-size pages and frames, paging eliminates external fragmentation, though it can still cause some internal fragmentation within the last page of a process.', 'intermediate'),
('education', 'gate-cse/os', 'memory-management', 'Segmentation, which divides a process into logical, variable-sized units, can lead to:', '["External fragmentation", "No fragmentation of any kind", "Only internal fragmentation, never external", "Guaranteed contiguous free memory"]', 0, 'Because segments are variable-sized, allocating and freeing them over time can leave scattered free memory blocks too small to be useful -- external fragmentation.', 'intermediate'),
('education', 'gate-cse/os', 'memory-management', 'Virtual memory allows a system to:', '["Execute processes larger than available physical memory, using disk as an extension", "Run processes without any memory allocation at all", "Bypass the CPU entirely for I/O operations", "Guarantee zero page faults"]', 0, 'Virtual memory uses disk storage to extend the apparent address space available to processes, allowing programs larger than physical RAM to run.', 'beginner'),
('education', 'gate-cse/os', 'memory-management', 'Thrashing occurs when a system spends most of its time:', '["Paging/swapping rather than executing actual process instructions", "Executing processes at maximum CPU efficiency", "Waiting for user input", "Compiling source code"]', 0, 'Thrashing happens when the degree of multiprogramming is too high relative to available memory, causing excessive page faults and swapping that dominates over useful execution.', 'intermediate'),
('education', 'gate-cse/os', 'memory-management', 'LRU (Least Recently Used) is an example of a:', '["Page replacement algorithm", "CPU scheduling algorithm", "Disk scheduling algorithm", "Deadlock avoidance algorithm"]', 0, 'LRU is a common page replacement algorithm that evicts the page which has not been used for the longest time, approximating optimal replacement.', 'beginner'),
('education', 'gate-cse/os', 'file-systems', 'FCFS disk scheduling processes I/O requests in the order:', '["They arrive", "Of increasing track number only", "Of the shortest seek time first", "Determined by file priority"]', 0, 'FCFS disk scheduling is the simplest scheme: requests are serviced strictly in the order they arrived, regardless of disk head position.', 'beginner'),
('education', 'gate-cse/os', 'file-systems', 'The SCAN disk scheduling algorithm is also commonly known as the:', '["Elevator algorithm", "Shortest path algorithm", "Round robin algorithm", "First fit algorithm"]', 0, 'SCAN moves the disk head in one direction, servicing requests along the way, then reverses -- behaving like an elevator, hence the nickname.', 'intermediate'),
('education', 'gate-cse/os', 'file-systems', 'The SSTF (Shortest Seek Time First) disk scheduling algorithm selects the request that is:', '["Closest to the current head position", "First in the arrival queue", "Farthest from the current head position", "Assigned the highest file priority"]', 0, 'SSTF greedily selects whichever pending request requires the least head movement from the current position, minimizing seek time for that step.', 'intermediate'),
('education', 'gate-cse/os', 'file-systems', 'A directory structure in a file system primarily organizes:', '["Files and their metadata in a hierarchical or other structured form", "Only the physical location of the hard disk platters", "The CPU''s register allocation", "Network routing tables"]', 0, 'A directory structure organizes files, their names, and associated metadata (size, permissions, location) in a structured (often hierarchical/tree) form.', 'beginner'),
('education', 'gate-cse/os', 'file-systems', 'Contiguous file allocation stores a file''s data blocks:', '["In consecutive disk blocks", "Scattered across the disk, linked by pointers", "Only in a fixed-size index block", "Randomly, with no fixed pattern"]', 0, 'Contiguous allocation places all of a file''s blocks in adjacent disk locations, enabling fast sequential access but requiring the free space to be available in one contiguous run.', 'beginner'),
('education', 'gate-cse/dbms', 'er-model', 'In the ER (Entity-Relationship) model, an entity is best described as:', '["A real-world object with independent existence, distinguishable from other objects", "A relationship between two attributes", "A numeric value stored in a table", "A query used to retrieve data"]', 0, 'An entity represents a distinguishable real-world object or concept (e.g. a specific employee or product) about which data is stored.', 'beginner'),
('education', 'gate-cse/dbms', 'er-model', 'A weak entity in the ER model depends on a strong (owner) entity because it:', '["Lacks a sufficient set of attributes to form its own primary key alone", "Has more attributes than the strong entity", "Cannot participate in any relationship", "Is always mapped to multiple tables"]', 0, 'A weak entity cannot be uniquely identified by its own attributes alone; it relies on a partial key combined with the primary key of its owning strong entity.', 'intermediate'),
('education', 'gate-cse/dbms', 'er-model', 'A "one-to-many" relationship cardinality between entities A and B means:', '["One instance of A can relate to multiple instances of B, but each instance of B relates to only one A", "Each instance of A relates to exactly one instance of B", "Multiple instances of A can relate to multiple instances of B", "No instance of A can relate to more than zero instances of B"]', 0, 'A one-to-many cardinality means a single A entity can be associated with several B entities, while each B entity is associated with only one A entity.', 'beginner'),
('education', 'gate-cse/dbms', 'er-model', 'In ER-to-relational mapping, a multi-valued attribute is typically converted into:', '["A separate relation (table) referencing the owning entity''s primary key", "A single additional column in the existing table", "It is simply discarded during mapping", "A view, never an actual table"]', 0, 'Because a relational table column must hold a single value, multi-valued attributes are mapped to their own table, linked to the owning entity via a foreign key.', 'intermediate'),
('education', 'gate-cse/dbms', 'er-model', 'A "many-to-many" relationship between two entities is typically mapped in the relational model to:', '["A separate junction (relationship) table containing the primary keys of both entities", "A single merged table combining both entities'' attributes", "No table at all -- it cannot be represented relationally", "A view over the two original entity tables"]', 0, 'Many-to-many relationships require a separate junction table holding foreign keys referencing both participating entities, since neither entity table alone can represent the relationship.', 'intermediate'),
('education', 'gate-cse/dbms', 'relational-algebra', 'The Selection operation (sigma) in relational algebra:', '["Filters rows (tuples) based on a given condition", "Selects specific columns (attributes)", "Combines two relations into one", "Removes duplicate rows"]', 0, 'Selection (sigma) is a unary operation that filters tuples from a relation based on a specified predicate/condition.', 'beginner'),
('education', 'gate-cse/dbms', 'relational-algebra', 'The Projection operation (pi) in relational algebra:', '["Selects specific columns (attributes) from a relation", "Filters rows based on a condition", "Joins two relations", "Computes the union of two relations"]', 0, 'Projection (pi) is a unary operation that extracts specified columns from a relation, discarding the rest.', 'beginner'),
('education', 'gate-cse/dbms', 'relational-algebra', 'A Natural Join between two relations combines tuples that have:', '["Equal values on their common attributes, with duplicate columns removed", "Any values at all, regardless of matching", "No common attributes whatsoever", "Only primary key columns retained from both relations"]', 0, 'A natural join automatically matches tuples on attributes with the same name and compatible type across both relations, and removes the duplicate copy of the joining column(s).', 'intermediate'),
('education', 'gate-cse/dbms', 'relational-algebra', 'The Cartesian Product of two relations R (with m tuples) and S (with n tuples) produces a result with:', '["m x n tuples", "m + n tuples", "max(m,n) tuples", "min(m,n) tuples"]', 0, 'The Cartesian Product pairs every tuple of R with every tuple of S, producing exactly m x n resulting tuples.', 'beginner'),
('education', 'gate-cse/dbms', 'relational-algebra', 'The Division operation in relational algebra is primarily used to answer queries of the form:', '["Find X that are related to ALL Y (e.g. students enrolled in every course)", "Find X that are related to AT LEAST ONE Y", "Find the total count of all tuples in a relation", "Remove duplicate rows from a relation"]', 0, 'Division is specifically suited to "for all" style queries, such as finding entities associated with every member of another set, unlike simpler operations.', 'intermediate'),
('education', 'gate-cse/dbms', 'sql', 'The SQL command used to permanently remove a table''s entire structure (along with its data) from the database is:', '["DROP", "DELETE", "TRUNCATE", "REMOVE"]', 0, 'DROP TABLE removes both the table''s structure and all its data permanently, unlike DELETE or TRUNCATE which only remove rows while keeping the table structure intact.', 'beginner'),
('education', 'gate-cse/dbms', 'sql', 'The SQL command that removes ALL rows from a table (keeping its structure) and, unlike DELETE, cannot be filtered with a WHERE clause is:', '["TRUNCATE", "DROP", "SELECT", "ALTER"]', 0, 'TRUNCATE removes every row from a table in one fast operation, keeping the table structure intact, but it operates on the whole table and does not support a WHERE clause the way DELETE does.', 'intermediate'),
('education', 'gate-cse/dbms', 'sql', 'An INNER JOIN between two tables returns:', '["Only the rows that have matching values in both tables", "All rows from both tables, matched or not", "Only rows from the left table, regardless of a match", "Only rows from the right table, regardless of a match"]', 0, 'An INNER JOIN returns only the rows where the join condition finds a match in both participating tables, excluding unmatched rows from either side.', 'beginner'),
('education', 'gate-cse/dbms', 'sql', 'The GROUP BY clause, typically used together with aggregate functions, is used to:', '["Group rows sharing a common value and compute an aggregate per group", "Filter individual rows before aggregation", "Sort the final result set", "Join two or more tables together"]', 0, 'GROUP BY partitions the result set into groups sharing a specified column''s value, so aggregate functions (COUNT, SUM, AVG, etc.) compute one result per group.', 'beginner'),
('education', 'gate-cse/dbms', 'sql', 'A subquery placed inside a WHERE clause is commonly referred to as a:', '["Nested query", "Join query", "Union query", "View"]', 0, 'A subquery within a WHERE clause -- used to filter rows based on the result of an inner query -- is commonly called a nested query.', 'beginner'),
('education', 'gate-cse/dbms', 'normalisation', 'A relation is said to be in First Normal Form (1NF) if:', '["All attribute values are atomic (no repeating groups or multivalued attributes)", "It has no functional dependencies", "Every non-key attribute depends on the full candidate key", "It contains no transitive dependencies"]', 0, '1NF requires every attribute to hold a single, indivisible (atomic) value -- no lists, sets, or repeating groups within a single cell.', 'beginner'),
('education', 'gate-cse/dbms', 'normalisation', 'Second Normal Form (2NF) requires a relation to be in 1NF and additionally have:', '["No partial dependency of any non-prime attribute on a candidate key", "No transitive dependency at all", "Only atomic attribute values", "Every determinant be a candidate key"]', 0, '2NF eliminates partial dependencies -- cases where a non-prime attribute depends on only part of a composite candidate key, rather than the whole key.', 'intermediate'),
('education', 'gate-cse/dbms', 'normalisation', 'Third Normal Form (3NF) requires a relation to be in 2NF and additionally have:', '["No transitive dependency of non-prime attributes on the candidate key", "No partial dependency only", "Only atomic values in every column", "At least one multivalued attribute"]', 0, '3NF eliminates transitive dependencies -- cases where a non-prime attribute depends on another non-prime attribute rather than directly on a candidate key.', 'intermediate'),
('education', 'gate-cse/dbms', 'normalisation', 'Boyce-Codd Normal Form (BCNF) requires that for every non-trivial functional dependency X -> Y:', '["X must be a super key of the relation", "Y must be a super key of the relation", "X and Y must both be prime attributes", "The relation must already be in 1NF only"]', 0, 'BCNF is a stricter form of 3NF, requiring the determinant (X) of every non-trivial functional dependency to be a super key.', 'intermediate'),
('education', 'gate-cse/dbms', 'normalisation', 'A lossless decomposition of a relation ensures that:', '["Joining the decomposed relations back together reproduces the original relation exactly, with no spurious tuples", "The decomposed relations always have fewer total attributes than the original", "Some information is necessarily lost during decomposition", "The decomposition always increases the number of functional dependencies"]', 0, 'A lossless-join decomposition guarantees that re-joining the decomposed tables recreates exactly the original relation, without introducing extra (spurious) tuples.', 'intermediate'),
('education', 'gate-cse/dbms', 'transactions', 'The acronym ACID, describing key transaction properties, stands for:', '["Atomicity, Consistency, Isolation, Durability", "Availability, Consistency, Isolation, Durability", "Atomicity, Concurrency, Isolation, Durability", "Atomicity, Consistency, Integrity, Durability"]', 0, 'ACID properties -- Atomicity, Consistency, Isolation, Durability -- define the guarantees a reliable database transaction must uphold.', 'beginner'),
('education', 'gate-cse/dbms', 'transactions', 'A schedule of concurrent transactions is called serializable if it:', '["Produces the same effect as some serial (one-at-a-time) execution of those transactions", "Executes all transactions strictly one after another", "Never allows any transaction to wait", "Always uses the timestamp ordering protocol"]', 0, 'Serializability means a concurrent schedule''s final result matches what some serial ordering of the same transactions would have produced.', 'intermediate'),
('education', 'gate-cse/dbms', 'transactions', 'The Two-Phase Locking (2PL) protocol divides a transaction''s execution into which two phases?', '["A growing phase (acquiring locks) and a shrinking phase (releasing locks)", "A read phase and a write phase", "A commit phase and a rollback phase", "A local phase and a distributed phase"]', 0, '2PL requires a transaction to first only acquire locks (growing phase), then only release locks (shrinking phase), never interleaving the two.', 'intermediate'),
('education', 'gate-cse/dbms', 'transactions', 'Conflict serializability of a schedule is typically checked by constructing and analyzing a:', '["Precedence graph, checking whether it is acyclic", "Truth table of all transactions", "B-tree index of operations", "Hash table of lock requests"]', 0, 'A precedence (serialization) graph is built from conflicting operations between transactions; the schedule is conflict serializable if and only if this graph is acyclic.', 'intermediate'),
('education', 'gate-cse/dbms', 'transactions', 'The Timestamp Ordering Protocol ensures serializability by:', '["Assigning each transaction a unique timestamp and ordering conflicting operations accordingly", "Locking the entire database for each transaction", "Ignoring the order of conflicting operations entirely", "Allowing only one transaction to run at any given time"]', 0, 'The Timestamp Ordering Protocol assigns transactions unique timestamps and enforces that conflicting operations execute in timestamp order, guaranteeing a serializable schedule.', 'intermediate')
ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
