-- ============================================================
-- Quiz coverage for devops/shell-scripting -- batch 2, sourced from
-- docs/Vishnu prepared content/shell scripting/quiz.md (15 questions).
--
-- 3 of the 15 source questions were excluded as substantive duplicates
-- of questions already seeded in docs/quiz-questions-openshift-python-shell.sql
-- for the same section (devops/shell-scripting/overview) -- same core
-- fact tested, near-identical framing, not just topical overlap:
--   - source Q1 ("What does set -euo pipefail do") duplicates the
--     existing "What do the three flags in set -euo pipefail each do?"
--   - source Q9 (2>&1 > file vs > file 2>&1 ordering) duplicates the
--     existing "command 2>&1 > file vs command > file 2>&1" question,
--     same specific command pattern.
--   - source Q10 (safe file line-reading pattern) duplicates the
--     existing "correct, safe pattern for reading a file line by line"
--     question, same while IFS= read -r answer.
-- The remaining 12 were fact-checked independently against actual bash
-- behavior before seeding (all correct as written in the source file;
-- no corrections needed to answer index or explanation text).
--
-- quiz.md has no section field of its own -- these are general
-- shell-scripting quiz content, not tied to a specific fundamentals/
-- intermediate/advanced split, so seeded under "overview" to match
-- where the existing 5 shell-scripting questions already live.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES

-- ---------- devops/shell-scripting/overview (batch 2) ----------
('devops', 'shell-scripting', 'overview', 'Why is $(command) preferred over `command` (backticks) for command substitution?', '["Backticks are POSIX-only and therefore more portable", "$(command) nests cleanly ($(cmd1 $(cmd2))) and handles internal quoting far more predictably; backticks require awkward escaping and cannot nest cleanly", "$(command) executes faster at runtime", "$[command] is the modern replacement for both"]', 1, 'Backticks are POSIX and do still work -- that is why the portability option is tempting -- but that does not outweigh the nesting/escaping problems in practice. $[expr] is a real but unrelated legacy construct (old arithmetic expansion, deprecated in favor of $((expr))), included because it is easy to confuse with command substitution syntax.', 'beginner'),
('devops', 'shell-scripting', 'overview', 'In `[[ "$INPUT" =~ ^[0-9]+$ ]]`, what does =~ do?', '["Tests string equality", "Performs a regular-expression match -- only valid inside [[ ]], not [ ]", "Tests whether a file exists", "Performs a numeric comparison"]', 1, '=~ is bash''s regex-match operator and is specific to the [[ ]] extended test construct; POSIX [ ] has no equivalent.', 'beginner'),
('devops', 'shell-scripting', 'overview', 'Why does `[ $UNDEFINED_VAR = "hello" ]` risk failing with a syntax error, while `[[ $UNDEFINED_VAR = "hello" ]]` does not?', '["There is no real difference -- both fail identically","[ ] is POSIX test and word-splits its arguments; an unquoted, unset variable can vanish entirely and leave [ = \"hello\" ], which is a syntax error. [[ ]] does not word-split, so the same unset/unquoted variable is just treated as an empty string","[[ ]] is POSIX and portable; [ ] is bash-only","[ ] supports regex matching and [[ ]] does not"]', 1, 'This has it backwards if you assume [[ ]] is the portable one -- [ ] is actually the POSIX-portable form, [[ ]] is the bash extension, and it is specifically [[ ]]''s lack of word-splitting that avoids the syntax-error risk here.', 'intermediate'),
('devops', 'shell-scripting', 'overview', 'Given filename="archive.tar.gz", what does echo "${filename%%.*}" print?', '["archive.tar.gz", "archive.tar", "archive", ".gz"]', 2, '%% strips the longest matching suffix for the pattern .* (any dot onward), removing .tar.gz entirely and leaving archive. The single-% form (${filename%.*}, shortest match) would instead leave archive.tar -- that is the classic mix-up between % and %%.', 'intermediate'),
('devops', 'shell-scripting', 'overview', 'Given the same filename="archive.tar.gz", what does echo "${filename##*.}" print?', '["archive.tar.gz", "tar.gz", "gz", "archive"]', 2, '## strips the longest matching prefix for *., leaving just the final extension gz. The single-# form (shortest prefix match) would instead leave tar.gz.', 'intermediate'),
('devops', 'shell-scripting', 'overview', 'What is the actual purpose of `local` inside a bash function?', '["Makes the variable persist after the function returns, for use elsewhere in the script", "Scopes the variable to that function call only, so it cannot leak into or overwrite global variables of the same name", "Marks the variable read-only for the rest of the script", "Exports the variable into the environment of any child process the function launches"]', 1, 'Without local, a variable assigned inside a bash function is global by default -- local is what creates function-scoped variables and prevents accidental collisions with same-named variables elsewhere in the script.', 'beginner'),
('devops', 'shell-scripting', 'overview', 'What does appending 2>&1 to a command do?', '["Redirects stdout to a file and discards stderr", "Redirects file descriptor 2 (stderr) to wherever file descriptor 1 (stdout) currently points", "Duplicates stdin onto stdout", "Suppresses both stdout and stderr entirely"]', 1, '2>&1 is a file-descriptor duplication, evaluated left to right at the point it appears -- it sends stderr to whatever stdout''s current target is at that moment in the command line, not to a fixed destination.', 'beginner'),
('devops', 'shell-scripting', 'overview', 'Why is `command -v mycmd &>/dev/null` generally preferred over `which mycmd` for existence checks in scripts?', '["It checks whether mycmd is currently running, which which cannot do at all", "command -v is a POSIX shell builtin that reliably reports whether mycmd resolves to a builtin, function, alias, or PATH executable, with no output needed; which is an external program whose availability and exact behavior varies by OS/distro", "It compiles mycmd and reports syntax errors before running it", "It behaves identically to which mycmd in every respect, just with different syntax"]', 1, 'which is not guaranteed to exist on every system and its behavior (e.g. whether it checks aliases/functions) varies by implementation; command -v is a shell builtin with consistent, portable behavior.', 'intermediate'),
('devops', 'shell-scripting', 'overview', 'What is the practical difference between `trap cleanup EXIT` and `trap cleanup ERR`?', '["EXIT only fires when the script errors out; ERR fires on every exit, including success", "EXIT fires on script termination for essentially any reason (normal completion, exit, or an uncaught signal); ERR fires specifically when a command returns non-zero, subject to the same exceptions that apply to set -e (e.g., commands in an if condition do not trigger it)", "They are interchangeable aliases for the same trap", "ERR traps only work under /bin/sh, never under bash"]', 1, 'EXIT is the broader, always-fires-on-termination trap commonly used for cleanup regardless of success/failure; ERR fires only on a non-zero exit status and follows the same contexts where set -e itself does not trigger (e.g. inside an if condition or before &&/||).', 'advanced'),
('devops', 'shell-scripting', 'overview', 'Why does `false | true; echo $?` print 0, and what does `set -o pipefail` change about that?', '["Bash reports the exit status of the last command in a pipeline by default; pipefail instead makes the pipeline''s overall exit status the rightmost non-zero status of any stage (or 0 if every stage succeeded)", "false | true is invalid syntax, so this cannot actually happen", "pipefail disables piping between commands entirely", "Bash reports the exit status of the first command by default, making pipefail redundant here"]', 0, 'This is exactly why pipefail matters for scripts that pipe into tee, grep, or similar -- without it, a failing step upstream can be silently masked by a later command in the pipe that succeeds.', 'advanced'),
('devops', 'shell-scripting', 'overview', 'In a function defined as `retry() { local n=$1; shift; local delay=$1; shift; "$@"; }`, what does "$@" refer to by the time it is used?', '["The original n and delay values, preserved", "Whatever positional arguments remain after both shifts have removed n and delay -- i.e., the actual command (and its arguments) to retry", "An empty value, since shift clears $@", "Only the next single remaining argument, not all of them"]', 1, 'Each shift removes the current $1 and shifts every remaining positional argument down by one; after two shifts remove n and delay, "$@" holds whatever the caller passed after those first two arguments -- the command to actually retry.', 'advanced'),
('devops', 'shell-scripting', 'overview', 'What is the main risk of writing `rm -rf $DIR` instead of `rm -rf "$DIR"` in a script?', '["There is no risk -- bash always treats $DIR as a single value regardless of quoting", "If $DIR is unset, empty, or contains spaces/globs, the unquoted expansion can word-split or glob-expand into something unintended -- in the worst case ($DIR empty and combined with a trailing path segment) this can delete far more than intended", "rm does not accept unquoted variables at all and will simply error out", "This only matters for cp, not rm"]', 1, 'This is the single most cited "one bash bug that caused real damage" pattern -- an unquoted, unexpectedly-empty $DIR can turn rm -rf $DIR/ into rm -rf / in effect, which is exactly why quoting every variable is a standing rule, not just a style preference.', 'intermediate')

ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
