-- ============================================================
-- Quiz coverage for Prometheus, Grafana, and ELK Stack under the
-- devops academy (Phase 2 batch 5).
--
-- Registry note: all three technologies keep their existing alias
-- to infrastructure/{prometheus,grafana,elk-stack}/* -- that content
-- was audited and found correctly-topical and high quality (same
-- outcome as nginx/jenkins/argocd/terraform/ansible/helm in prior
-- batches, not git's outcome). Questions below are grounded in the
-- infrastructure/* content actually served at devops/{tech}/{section},
-- for the four tabs that follow the established overview/fundamentals/
-- intermediate/advanced pattern.
--
-- devops/elk vs devops/elk-stack: devops/elk-stack is the only
-- technology slug registered in lib/data/academies.ts for the devops
-- academy and is what all real navigation/labs/blog links point to.
-- devops/elk (a separate, self-referencing registry entry with its
-- own 4 files on disk) is NOT reachable from any real site URL --
-- see the batch report for the full finding. Quiz rows below use
-- technology_slug = 'elk-stack' only.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES

-- ---------- devops/prometheus/overview ----------
('devops', 'prometheus', 'overview', 'Why does Prometheus use a pull model (scraping /metrics) instead of applications pushing metrics to it?', '["Pull is always faster over the network", "Prometheus controls scrape timing, can tell immediately when a target is unreachable (the scrape fails), and applications don''t need to know where the monitoring system lives", "Push models are not supported by any monitoring tool", "Pull avoids the need for a time-series database entirely"]', 1, 'A failed scrape itself is a useful signal (up == 0) -- this is why the Pushgateway exists only as a deliberate exception for short-lived batch jobs that would finish before a scrape could reach them, not a contradiction of the pull model.', 'beginner'),
('devops', 'prometheus', 'overview', 'Why should you never query a raw Counter value directly on a dashboard?', '["Counters are stored as strings, not numbers", "A Counter only ever increases (or resets to 0 on restart) -- its raw cumulative value has no direct meaningful interpretation; rate() converts it into a per-second rate", "Counters cannot be graphed by Grafana", "Raw counters are always empty until a recording rule populates them"]', 1, 'This is one of the most common real beginner mistakes -- rate(http_requests_total[5m]) gives requests/second, which is what dashboards and alerts actually need, not the ever-growing raw total.', 'beginner'),
('devops', 'prometheus', 'overview', 'What does the ServiceMonitor CRD''s `release: prometheus` label actually do?', '["It sets the Prometheus release version to scrape with", "It must match the label selector the Prometheus Operator''s Prometheus resource uses to discover ServiceMonitors -- without a match, the ServiceMonitor is silently ignored", "It restarts Prometheus when changed", "It has no functional effect, it is purely cosmetic"]', 1, 'A ServiceMonitor whose labels don''t match the Prometheus resource''s selector is a common, silent cause of "why isn''t my service showing up as a target" -- kubectl get servicemonitor and checking the selector is the standard first debugging step.', 'intermediate'),
('devops', 'prometheus', 'overview', 'Why does a PrometheusRule alert typically include `for: 5m` rather than firing the instant the expression becomes true?', '["for: is required syntax with no functional effect", "It requires the condition to stay true for the full duration before transitioning from Pending to Firing, preventing brief, transient spikes from paging someone unnecessarily", "It delays evaluation of the expression itself by 5 minutes", "It controls how long Alertmanager waits before routing the alert"]', 1, 'Without a for: duration, a single noisy data point can fire and resolve an alert with no sustained problem behind it -- the tradeoff is that a genuinely short-lived real issue might not fire at all.', 'intermediate'),
('devops', 'prometheus', 'overview', 'When would you reach for Thanos or Mimir instead of just running Prometheus alone?', '["When you need PromQL support for the first time", "When you need retention/history beyond local disk limits, or a single query view across multiple Prometheus instances/clusters -- Prometheus itself has no built-in clustering or long-term storage", "When you want to replace Grafana entirely", "When Alertmanager needs to route to more than one receiver"]', 1, 'Prometheus is designed to run as a single binary with local disk storage; Thanos/Mimir/Cortex add the global query view, downsampling, and durable object-storage retention that a single Prometheus instance cannot provide on its own.', 'advanced'),

-- ---------- devops/prometheus/fundamentals ----------
('devops', 'prometheus', 'fundamentals', 'What are the four core Prometheus metric types?', '["Integer, Float, String, Boolean", "Counter, Gauge, Histogram, Summary", "Line, Bar, Gauge, Table", "Push, Pull, Scrape, Alert"]', 1, 'Counter only increases; Gauge goes up and down; Histogram buckets observations for percentile calculation server-side; Summary calculates quantiles client-side (less flexible, not aggregatable across instances).', 'beginner'),
('devops', 'prometheus', 'fundamentals', 'In a Kubernetes scrape config using kubernetes_sd_configs, what is the purpose of the relabel_configs step that keeps only pods with `prometheus.io/scrape: "true"`?', '["It deletes pods that don''t match", "It filters WHICH discovered targets Prometheus actually scrapes, so only pods that opted in via annotation are polled, instead of every pod in the cluster", "It sets the scrape interval for matching pods", "It converts the pod''s labels into Kubernetes annotations"]', 1, 'Relabeling happens before scraping begins -- an action: keep step with a regex match against the annotation label is the standard way to make scraping opt-in rather than scraping every pod indiscriminately.', 'intermediate'),
('devops', 'prometheus', 'fundamentals', 'Why does histogram_quantile() require the `le` label to be preserved in a `by()` aggregation?', '["le stands for "label expression" and is required syntax with no functional role", "le (less-than-or-equal) identifies each histogram bucket''s upper boundary -- histogram_quantile needs all the bucket boundaries intact to interpolate a percentile; dropping it produces a meaningless or erroring result", "le controls how many buckets are created", "le is only needed for Summary metrics, not Histograms"]', 1, 'sum(rate(x_bucket[5m])) by (le, service) keeps the per-bucket breakdown that histogram_quantile needs to estimate a percentile -- aggregating away le is a common, real mistake when writing this query from memory.', 'intermediate'),
('devops', 'prometheus', 'fundamentals', 'What is the actual mechanism through which Alertmanager prevents one incident (e.g. 50 crashing pods) from generating 50 separate Slack notifications?', '["Alertmanager only allows one alert to fire per hour", "group_by groups related alerts sharing specified labels into one notification instead of sending one per matching alert", "Slack itself deduplicates identical messages", "Prometheus only evaluates one alert rule at a time"]', 1, 'route.group_by (e.g. [alertname, cluster]) is what turns 50 individual pod-restart alerts into a single grouped notification -- without it, every matching alert fires its own separate message.', 'intermediate'),
('devops', 'prometheus', 'fundamentals', 'A Kubernetes service discovery scrape config filters on a pod annotation using `regex: "true"` (a quoted string). Functionally, how does this differ from writing `regex: true` (unquoted) in the same YAML position?', '["They are functionally different -- unquoted true is invalid YAML in this context and the config fails to load", "In YAML, an unquoted true is parsed as a boolean and then coerced to the string "true" for regex matching, so both forms match the same annotation value in practice, though the quoted form is the clearer, less error-prone style", "regex: true matches any value, while regex: "true" matches only the literal string", "Unquoted true disables the relabel rule entirely"]', 1, 'Both forms end up matching the literal annotation value "true" -- Prometheus config parsing coerces the YAML boolean to a string for regex purposes -- but quoting it explicitly avoids relying on that coercion and is the safer habit.', 'advanced'),

-- ---------- devops/prometheus/intermediate ----------
('devops', 'prometheus', 'intermediate', 'A Prometheus alert fired but the Grafana dashboard looks completely normal. What is the FIRST thing worth checking, before assuming something is broken?', '["Restart Prometheus immediately", "The dashboard''s time range -- if it defaults to the last hour but the alert fired on a spike now outside that window, the dashboard will look clean even though the alert was legitimate", "Delete the alert rule", "Increase the scrape interval"]', 1, 'This is one of the most common real confusions -- widening the dashboard''s time range to cover when the alert actually fired is a faster, more reliable first check than assuming the alert or the data pipeline is broken.', 'intermediate'),
('devops', 'prometheus', 'intermediate', 'Why is high cardinality (e.g. a `user_id` label on a metric) specifically dangerous for Prometheus, rather than just "using more disk"?', '["It only affects disk usage, nothing else", "Every unique combination of label values creates a separate stored time series -- an unbounded label can produce millions of series from one metric definition, degrading both memory and query performance across every dashboard querying that metric", "High cardinality only affects Grafana, not Prometheus itself", "It causes PromQL syntax errors"]', 1, 'The fix is to drop the high-cardinality label via metric_relabel_configs and, longer-term, catch this in code review before custom metrics ship -- it''s cheaper to prevent than to recover from after a production memory incident.', 'intermediate'),
('devops', 'prometheus', 'intermediate', 'What problem do recording rules solve?', '["They make Prometheus scrape targets faster", "They pre-compute an expensive, frequently-used PromQL expression on a schedule and store the result as a new, cheap-to-query metric, instead of recalculating it on every dashboard load", "They replace the need for Alertmanager", "They automatically fix high-cardinality metrics"]', 1, 'A dashboard re-running a heavy aggregation across many series on every page refresh is slow and adds repeated load to Prometheus -- a recording rule computes it once per evaluation interval and dashboards query the cheap, pre-computed result instead.', 'intermediate'),
('devops', 'prometheus', 'intermediate', 'In a Kubernetes pod-discovery scrape config, why does the annotation-filtering relabel rule matter for a rapidly scaling deployment?', '["It doesn''t matter -- static target lists work fine for dynamic environments", "A static scrape target list goes stale within minutes as pods are created/destroyed; Kubernetes service discovery queries the API continuously so Prometheus starts/stops scraping targets automatically as they appear and disappear", "It only matters for StatefulSets, not Deployments", "It prevents Prometheus from ever scraping more than 100 targets"]', 1, 'Without service discovery, every deployment or scale event would require manually editing prometheus.yml -- kubernetes_sd_configs makes the target list follow the cluster''s actual current state.', 'beginner'),
('devops', 'prometheus', 'intermediate', 'Why is rate() generally preferred over irate() for values shown on a dashboard, while irate() is sometimes preferred for very responsive alerting?', '["rate() and irate() always return identical results", "rate() averages over the full time window given (smoother, better for human-readable graphs); irate() uses only the last two data points (more responsive to sudden spikes, but noisier), which can matter for fast-reacting alerts", "irate() is deprecated and should never be used", "rate() only works on Gauges, irate() only works on Counters"]', 1, 'The tradeoff is smoothness vs. responsiveness -- a dashboard usually benefits from the smoother rate() average, while a use case needing to react to a very recent spike might prefer irate()''s sensitivity to the last two samples.', 'advanced'),

-- ---------- devops/prometheus/advanced ----------
('devops', 'prometheus', 'advanced', 'In a multi-window, multi-burn-rate SLO alert, what does a "14x burn rate" actually represent?', '["Prometheus is scraping 14 times faster than normal", "The error budget is being consumed 14 times faster than the rate that would exactly exhaust it over the full SLO period -- at that rate the budget would run out in a small fraction of the intended window, justifying an immediate page", "14 separate alerts have fired for the same service", "The service has been down for 14 minutes"]', 1, 'A 14x burn rate against a 30-day error budget means that budget would be fully consumed in roughly 2 days if sustained -- combining a fast-burn (short window, high multiplier, page now) and slow-burn (long window, lower multiplier, ticket) alert is the standard Google SRE-book pattern.', 'advanced'),
('devops', 'prometheus', 'advanced', 'What is the actual role of Thanos Sidecar in a long-term-storage setup?', '["It replaces Prometheus entirely", "It runs alongside each Prometheus instance and periodically uploads TSDB blocks to object storage (S3/GCS), extending retention beyond Prometheus''s local disk", "It evaluates alert rules instead of Prometheus", "It compresses Prometheus''s scrape configuration files"]', 1, 'Thanos Query then federates across all the sidecars'' uploaded data (and live Prometheus instances) to provide one global query view across clusters, with the Compactor handling downsampling of older data.', 'advanced'),
('devops', 'prometheus', 'advanced', 'Why would inhibit_rules be configured to suppress a "warning" alert when a related "critical" alert is already firing for the same service?', '["To reduce Alertmanager''s CPU usage", "Because the warning is very likely a downstream symptom of the same root cause already being paged on -- inhibition avoids redundant, noisy notifications for what is effectively the same incident", "Warning alerts are always false positives", "Inhibition is required by Prometheus syntax, not an operational choice"]', 1, 'inhibit_rules match a source alert (e.g. NodeDown) against a target alert pattern and a set of equal labels -- when both are true for the same underlying resource, only the source alert notifies, cutting duplicate noise during a single real incident.', 'advanced'),
('devops', 'prometheus', 'advanced', 'A custom Python exporter uses `QUEUE_SIZE.labels(queue_name).set(-1)` when a health check to an external API fails. What does this pattern accomplish, and what is the tradeoff?', '["It stops the exporter from being scraped at all", "It lets a Gauge represent an explicit error state distinct from a real queue depth of 0, at the cost of requiring every downstream query/alert to know that -1 means "error" and handle it specially", "It automatically retries the failed request", "It converts the Gauge into a Counter"]', 1, 'Using a sentinel value like -1 is a common but imperfect pattern -- it keeps the metric present (avoiding a silent absence, which is often worse) but pushes the burden of interpreting the sentinel onto every consumer of that metric.', 'advanced'),
('devops', 'prometheus', 'advanced', 'For Prometheus Operator HA, what does setting `replicas: 2` on the Prometheus CRD actually provide, and what does it NOT provide on its own?', '["It provides automatic long-term storage -- nothing else is needed", "It runs two independent Prometheus instances scraping the same targets so a single instance failure doesn''t lose monitoring coverage, but it does NOT by itself provide long-term retention beyond local disk or deduplicated global querying -- that still requires Thanos/Mimir/Cortex", "It doubles the scrape interval automatically", "It replaces the need for Alertmanager deduplication"]', 1, 'Both replicas evaluate alerts independently, so Alertmanager''s own deduplication (based on matching labels) is what prevents duplicate notifications from the two replicas -- replicas alone solve availability, not long-term storage or cross-cluster querying.', 'advanced'),

-- ---------- devops/grafana/overview ----------
('devops', 'grafana', 'overview', 'What is the fundamental architectural difference between Grafana and Prometheus?', '["They are two names for the same underlying software", "Grafana stores no data of its own -- it queries external data sources (Prometheus, Loki, Elasticsearch, and 100+ others) and renders the results; Prometheus is the one that actually collects and stores time-series data", "Prometheus can only be used with Grafana, never standalone", "Grafana replaces the need for a database entirely"]', 1, 'You can use Grafana without Prometheus (against other data sources) and Prometheus without Grafana (via its own expression browser) -- together they form the common open-source metrics stack, but neither depends on the other to function.', 'beginner'),
('devops', 'grafana', 'overview', 'What actually correct components make up Grafana''s open-source "LGTM Stack"?', '["Loki, Grafana, Tempo, Mimir", "Loki, Grafana, Tempo, Prometheus", "Logstash, Grafana, Telegraf, Mimir", "Loki, Grafana, Tableau, MySQL"]', 0, 'LGTM = Loki (logs) + Grafana (visualization) + Tempo (traces) + Mimir (Prometheus-compatible metrics at scale) -- Mimir, not Prometheus itself, completes the acronym, though Mimir speaks the same PromQL/remote-write interface Prometheus does.', 'intermediate'),
('devops', 'grafana', 'overview', 'What is the practical benefit of defining a dashboard variable like `$namespace` instead of hardcoding a namespace into every panel query?', '["Variables make queries run faster at the database level", "One dashboard definition then works for every namespace/cluster/service via a dropdown, instead of maintaining N nearly-identical dashboards that inevitably drift out of sync over time", "Variables are required for Grafana to save a dashboard at all", "Variables only work with SQL data sources, not Prometheus"]', 1, 'A panel fix or new panel on a variable-driven dashboard applies everywhere at once; maintaining separate dashboards per environment means every change must be manually repeated and reliably drifts.', 'beginner'),
('devops', 'grafana', 'overview', 'Why does Grafana Alerting differ meaningfully from Prometheus/Alertmanager-based alerting?', '["Grafana Alerting cannot send notifications to Slack or PagerDuty", "Grafana can alert on any configured data source (SQL, CloudWatch, Loki -- not just Prometheus-compatible sources), while Alertmanager is specifically the Prometheus ecosystem''s alert router", "Grafana Alerting requires a paid Grafana Cloud subscription", "Alertmanager can only route alerts, never evaluate conditions"]', 1, 'Neither is universally "better" -- the practical choice depends on whether alerting needs span multiple non-Prometheus source types (favoring Grafana Alerting) or the shop is Prometheus-only with a mature existing Alertmanager setup.', 'intermediate'),
('devops', 'grafana', 'overview', 'A dashboard variable query uses `label_values(kube_pod_info{namespace=~"$namespace"}, pod)` for a `$pod` variable. What does this dependency on `$namespace` accomplish?', '["It has no effect -- $namespace is ignored inside label_values", "It chains the two variables so the $pod dropdown only shows pods that actually exist within whichever namespace is currently selected, instead of listing every pod across the whole cluster", "It forces $namespace and $pod to always have the same selected value", "It disables the $pod variable until $namespace is manually typed"]', 1, 'Chained/dependent variables are a common pattern for keeping large multi-value dropdowns relevant -- changing $namespace automatically re-queries and narrows the $pod list to match.', 'advanced'),

-- ---------- devops/grafana/fundamentals ----------
('devops', 'grafana', 'fundamentals', 'Why does Grafana provisioning (YAML-defined data sources/dashboards) get recommended over configuring them by hand in the UI?', '["Provisioning is required -- the UI configuration option does not actually exist", "Provisioning is version-controlled and reproducible without manual clicks, so the same setup can be recreated identically across environments and reviewed via pull request", "UI-configured data sources are automatically deleted on every Grafana restart", "Provisioning is the only way to connect to a Prometheus data source"]', 1, 'Manual UI edits alongside provisioning-managed dashboards can silently get overwritten on the next re-provisioning -- a clear convention (UI for prototyping only, JSON+provisioning for anything meant to persist) avoids the two paths drifting apart.', 'intermediate'),
('devops', 'grafana', 'fundamentals', 'What is the correct place to store an actual secret (like a data source password) in a Grafana provisioning YAML file?', '["jsonData, since it is loaded first", "secureJsonData, which is encrypted at rest and never returned in plaintext by the API -- unlike jsonData, which is plain config", "Directly in the dashboard JSON file", "Grafana provisioning does not support secrets at all"]', 1, 'Putting a credential under jsonData instead of secureJsonData is a common, avoidable mistake, especially when the provisioning files themselves are committed to Git.', 'intermediate'),
('devops', 'grafana', 'fundamentals', 'In a Grafana panel query using `sum(rate(http_requests_total{status=~"5.."}[5m])) by (le))`-style syntax for a latency panel, what would be wrong if `le` were dropped from the `by()` clause on a histogram_quantile query?', '["Nothing -- le is optional decoration", "histogram_quantile needs the le (bucket boundary) label preserved in the aggregation to correctly estimate a percentile; dropping it breaks the calculation", "It would make the query run faster with no downside", "It would convert the histogram into a gauge automatically"]', 1, 'This mirrors the same PromQL rule that applies whether the query originates in Prometheus directly or inside a Grafana panel -- le must survive the aggregation for histogram_quantile to work.', 'advanced'),
('devops', 'grafana', 'fundamentals', 'What is the practical difference between the Stat panel and the Gauge panel types?', '["They are functionally identical, only the color scheme differs", "Stat shows a single current value (optionally with a trend/sparkline and threshold coloring); Gauge shows that value visually positioned within a defined min/max range (e.g. a dial or bar)", "Gauge can only display percentages, Stat can only display raw counts", "Stat panels cannot use PromQL queries, only Gauge panels can"]', 1, 'Both are single-value panels, but Gauge is specifically suited to "how close to a limit" visualizations (disk %, CPU %) where the min/max range itself carries meaning.', 'beginner'),
('devops', 'grafana', 'fundamentals', 'Why does a Grafana alert rule need both a query (refId A) and a separate threshold/condition expression (refId C, `classic_conditions` or `threshold`)?', '["Grafana requires exactly two queries per alert rule regardless of purpose", "The data query computes the actual value being watched; the condition expression is evaluated against that value to decide firing state -- separating them lets one query feed multiple different threshold conditions", "refId C is a legacy field with no current function", "Splitting them is only needed for multi-data-source alerts"]', 1, 'This split (query -> condition) is core to Grafana''s unified alerting model, distinct from simply writing threshold logic directly into the PromQL expression itself.', 'advanced'),

-- ---------- devops/grafana/intermediate ----------
('devops', 'grafana', 'intermediate', 'A Grafana panel returns "No data" even though the same PromQL query returns results in Prometheus''s own UI. What does this specifically point to?', '["The metric definitely does not exist in Prometheus", "The problem is downstream of the raw query -- likely the panel''s time range, the data source configuration (URL/auth), or drift after a Prometheus redeploy changed its address, since the query itself is proven to work", "Grafana never supports the query that just worked in Prometheus", "The dashboard needs to be re-imported from scratch"]', 1, 'Checking the raw query in Prometheus''s UI first isolates whether the problem is the query/data itself or something in the Grafana-to-Prometheus connection -- a faster diagnostic path than guessing.', 'intermediate'),
('devops', 'grafana', 'intermediate', 'Why can''t a Summary metric''s pre-computed quantiles be correctly aggregated across multiple instances, the way a Histogram''s can?', '["Summaries do not support labels", "A Summary calculates its quantiles client-side, per instance, at scrape time -- averaging or combining already-computed per-instance quantiles across instances does not produce a mathematically valid fleet-wide quantile the way histogram_quantile() over combined bucket counts does", "Summaries are deprecated and no longer supported by Prometheus client libraries", "Summary metrics can only be queried from Grafana, not Prometheus directly"]', 1, 'This is the concrete, practical reason Histogram is generally preferred over Summary for anything that might need a fleet-wide percentile view later.', 'advanced'),
('devops', 'grafana', 'intermediate', 'What specifically makes a Grafana Terraform provider (`grafana_dashboard` resource) useful compared to manually exporting/importing dashboard JSON?', '["Terraform can query Prometheus directly without Grafana", "It brings dashboard changes into the same review/plan/apply workflow as the rest of the infrastructure, instead of a separate manual export/import step that''s easy to forget or apply inconsistently across environments", "Terraform-managed dashboards render faster in the browser", "It removes the need to write any PromQL in panel queries"]', 1, 'Whether via Grafonnet, exported JSON in Git, or the Terraform provider, the shared goal is the same one provisioning solves generally: version control, reviewability, and reproducibility instead of undocumented manual UI changes.', 'intermediate'),
('devops', 'grafana', 'intermediate', 'In Loki/LogQL, what is the correct way to compute a percentile (e.g. P99) from a numeric field extracted out of unstructured log lines?', '["A bare aggregation like `p99 by (endpoint)` is valid LogQL", "quantile_over_time(0.99, [5m]) applied after unwrapping the numeric field -- a bare percentile aggregation without unwrap/quantile_over_time is not valid LogQL syntax", "LogQL cannot compute percentiles at all, only Prometheus can", "Percentiles require exporting logs to Elasticsearch first"]', 1, '{app="api"} | json | unwrap duration_ms | quantile_over_time(0.99, [5m]) by (endpoint) is the correct form -- treating LogQL as if bare percentile syntax from PromQL applies directly is a common, real mistake.', 'advanced'),
('devops', 'grafana', 'intermediate', 'Why is high-cardinality data (like a raw request path or user ID) better handled as a Loki log label / Tempo trace attribute than as a Prometheus metric label?', '["Loki and Tempo have no cardinality limits at all", "Each unique metric label combination becomes a separate stored Prometheus time series, multiplying cost and degrading every dashboard querying that metric -- logs/traces are built to hold per-request detail without that same multiplicative cost, and can be correlated back to metrics via exemplars", "Prometheus cannot store string labels, only numeric ones", "Grafana blocks queries against high-cardinality Prometheus labels automatically"]', 1, 'The general operating principle: keep high-cardinality, per-request detail in logs/traces, and correlate back to aggregate metrics via exemplars, rather than exploding a metric''s series count with unbounded labels.', 'advanced'),

-- ---------- devops/grafana/advanced ----------
('devops', 'grafana', 'advanced', 'What does Grafana OnCall''s escalation chain actually automate, beyond just sending an alert notification?', '["It automatically fixes the underlying incident without human involvement", "A defined sequence of ack-timeout-based escalation steps (e.g. push notification, then SMS, then a backup engineer, then the whole team) so an unacknowledged page doesn''t just sit unseen -- it keeps escalating until someone actually acknowledges it", "It replaces Alertmanager''s routing entirely for all alert types", "It only works for alerts originating from Grafana Alerting, never from Prometheus Alertmanager"]', 1, 'This addresses a real operational gap plain notification routing doesn''t solve on its own -- a page that goes to one person''s phone and is never acknowledged needs an escalation path, not just a delivery mechanism.', 'advanced'),
('devops', 'grafana', 'advanced', 'Why does a highly-available, multi-replica Grafana deployment require PostgreSQL or MySQL instead of the default SQLite?', '["SQLite cannot store dashboard JSON at all", "SQLite is a single-file, single-writer database unsuitable for multiple Grafana instances sharing state concurrently -- HA requires a real shared database (plus Redis for session/cache) so every replica sees the same dashboards, users, and sessions", "PostgreSQL is required only for Grafana Enterprise licensing reasons", "SQLite works fine for HA as long as replicas are behind a load balancer"]', 1, 'All Grafana instances in an HA deployment also need the same secret key for cookie encryption -- without it, a session created on one replica wouldn''t validate on another.', 'advanced'),
('devops', 'grafana', 'advanced', 'What does Grafana Tempo''s trace-to-logs/trace-to-metrics correlation actually enable in practice?', '["It automatically writes new Prometheus alert rules from trace data", "Clicking a trace span can jump directly to the correlated Loki log lines or Prometheus metrics for that same service at that same time -- turning a manual, time-consuming cross-tool investigation into a few clicks within one UI", "It replaces the need to instrument an application with OpenTelemetry", "Tempo stores metrics and logs itself, eliminating the need for Prometheus or Loki"]', 1, 'This is the practical payoff of the "big tent" unified observability approach -- correlating metrics, logs, and traces by shared identifiers (like trace ID) inside Grafana rather than pivoting between three separate tools by hand.', 'advanced'),
('devops', 'grafana', 'advanced', 'Why is `grafana-cli plugins install` (or the `GF_INSTALL_PLUGINS` env var) generally preferred over manually copying plugin files into the Grafana plugins directory?', '["Manual copying is not technically possible in any Grafana version", "It handles fetching, signature verification, and correct placement automatically, and integrates cleanly with provisioning/Docker-based deployment instead of requiring a manual file-management step on every instance", "grafana-cli is required for Grafana to start at all, even with zero plugins", "Manually copied plugins cannot be uninstalled afterward"]', 1, 'For production, provisioning-based plugin installation (e.g. via the GF_INSTALL_PLUGINS Docker environment variable) keeps plugin management reproducible across environments rather than a manual, easy-to-forget step per instance.', 'advanced'),
('devops', 'grafana', 'advanced', 'In Grafonnet/Jsonnet dashboard-as-code, what is the actual advantage over hand-authoring the equivalent dashboard JSON directly?', '["Jsonnet dashboards render faster in the browser than JSON ones", "Jsonnet allows reusable functions/templates (e.g. a shared panel-builder function used across many dashboards), so a common pattern is defined once and reused, rather than the same JSON structure being copy-pasted and drifting across every dashboard that needs it", "Grafana can only import dashboards defined in Jsonnet, not raw JSON", "Jsonnet is required for any dashboard using template variables"]', 1, 'The generated JSON is what Grafana actually imports either way -- the benefit is entirely in the authoring/maintenance workflow, especially at the scale of many similar dashboards across services.', 'advanced'),

-- ---------- devops/elk-stack/overview ----------
('devops', 'elk-stack', 'overview', 'What does each letter in "ELK" actually refer to, and where does Beats fit in?', '["Elasticsearch (storage/search), Logstash (collection/parsing), Kibana (UI) -- Beats (e.g. Filebeat) are lightweight shippers that run on hosts, not part of the acronym itself but present in nearly every real deployment", "Elastic, Log, Kibana -- Beats is a fourth mandatory core component included in the acronym", "Elasticsearch, Kafka, Kubernetes", "Engine, Logstash, Kibana"]', 0, 'Most production setups use Filebeat for lightweight collection and reserve Logstash specifically for transformation work Filebeat alone can''t do, such as grok-parsing unstructured text into fields.', 'beginner'),
('devops', 'elk-stack', 'overview', 'What does Elasticsearch cluster health "Yellow" actually mean, and is it usually an emergency?', '["Yellow means data has been permanently lost -- treat it as critical", "Yellow means every primary shard is healthy but at least one replica is unassigned -- commonly low-risk, especially expected on a single-node cluster with nowhere to place a replica", "Yellow only occurs during a full cluster outage", "Yellow means Kibana is disconnected from Elasticsearch"]', 1, 'Red is the state needing immediate attention -- a primary shard itself unassigned means that data is genuinely unavailable right now. Yellow, by contrast, is routine on dev/single-node setups.', 'beginner'),
('devops', 'elk-stack', 'overview', 'Why is an Index Lifecycle Management (ILM) policy considered close to mandatory rather than optional for a production ELK deployment?', '["ILM is required for Kibana to render any dashboard", "Without ILM, indices accumulate indefinitely on the most expensive storage tier -- skipping it is one of the most common ways a healthy ELK deployment turns into a full-disk incident months later", "ILM controls which users can query which indices", "ILM only affects search relevance scoring, not storage"]', 1, 'A hot -> warm -> delete (or cold) policy defined from day one moves aging indices to cheaper tiers and eventually deletes them automatically on size/age triggers, rather than requiring manual cleanup later under pressure.', 'intermediate'),
('devops', 'elk-stack', 'overview', 'When would a team choose Loki over the ELK stack for Kubernetes log observability?', '["Loki is always strictly better and ELK has no remaining use case", "Loki only indexes labels (not full log text), making it much cheaper to run for teams already on Prometheus/Grafana and needing simpler log streaming/filtering rather than deep full-text search and complex aggregations", "ELK cannot run inside Kubernetes at all", "Loki requires Elasticsearch to be installed as a dependency"]', 1, 'ELK''s full-text inverted index over every field enables powerful search and aggregation at roughly 10x the storage cost of Loki''s label-only indexing -- the right choice depends on whether that full-text/aggregation power is actually needed, e.g. for SIEM/compliance use cases.', 'intermediate'),
('devops', 'elk-stack', 'overview', 'In a high-volume ELK architecture, what specific problem does inserting Kafka between the log shippers and Logstash solve?', '["Kafka replaces the need for Elasticsearch entirely", "Kafka acts as a durable buffer -- if Elasticsearch slows down or goes down, logs queue safely in Kafka instead of backing up in Logstash and eventually being dropped", "Kafka automatically parses grok patterns instead of Logstash", "Kafka reduces the number of Elasticsearch shards needed"]', 1, 'At high volume (millions of logs/minute), a slow or temporarily unavailable Elasticsearch cluster without a buffer in front of it risks real data loss -- Kafka absorbs that gap durably until Elasticsearch catches up.', 'advanced'),

-- ---------- devops/elk-stack/fundamentals ----------
('devops', 'elk-stack', 'fundamentals', 'What is the practical difference between mapping an Elasticsearch field as `text` versus `keyword`?', '["They are interchangeable, only the storage location differs", "text fields are analyzed/tokenized for full-text search; keyword fields are stored as-is for exact matching, sorting, and aggregation -- using text for a field you only ever filter on exactly wastes analysis cost", "keyword fields cannot be searched at all, only displayed", "text is required for numeric fields, keyword for string fields"]', 1, 'A common real-world pattern is mapping the same field as both (multi-field) when both full-text search and exact aggregation are genuinely needed on it.', 'beginner'),
('devops', 'elk-stack', 'fundamentals', 'In a Logstash pipeline, why does field type ("status" as integer, "duration" as float) usually need explicit handling via a `mutate { convert => {...} }` filter after a `grok` match?', '["grok automatically infers and converts all field types correctly", "grok extracts fields as strings by default -- without an explicit conversion, a numeric-looking field like status stays a string, breaking range queries and numeric aggregations against it later", "mutate is only needed for renaming fields, never type conversion", "Elasticsearch automatically converts string fields to numbers on ingest regardless of Logstash"]', 1, 'This is a common, easy-to-miss step -- a grok-extracted "status" field that looks like a number in Kibana can still behave like a string in queries unless it was explicitly converted.', 'intermediate'),
('devops', 'elk-stack', 'fundamentals', 'What is the risk of defining an index''s field mappings implicitly (letting Elasticsearch infer types from the first indexed document) instead of via an explicit index template?', '["There is no risk -- dynamic mapping is always equivalent to an explicit template", "The type of the FIRST document to introduce a field determines that field''s type going forward -- if a later document sends a different, conflicting type for the same field, indexing errors or unusable queries can result", "Dynamic mapping disables search entirely for the affected index", "Explicit templates are only relevant for time-series indices, not general logs"]', 1, 'Defining an index template with explicit field types before data starts flowing avoids this class of inconsistency entirely, rather than relying on whatever the first document happened to look like.', 'intermediate'),
('devops', 'elk-stack', 'fundamentals', 'Why does Filebeat commonly ship logs to Logstash rather than directly to Elasticsearch, in a pipeline handling raw Nginx access logs?', '["Filebeat cannot connect to Elasticsearch directly under any configuration", "Nginx access log lines are unstructured text -- Logstash''s grok filter is what parses them into structured, individually-searchable fields (client_ip, status, response_time) before indexing; Filebeat alone has no equivalent parsing capability", "Logstash is required to enable TLS between Filebeat and Elasticsearch", "Direct Filebeat-to-Elasticsearch shipping is deprecated"]', 1, 'When logs are already structured (a service emitting JSON lines), direct Filebeat -> Elasticsearch shipping is sufficient and simpler -- Logstash earns its place specifically for the parsing/enrichment step unstructured text requires.', 'beginner'),
('devops', 'elk-stack', 'fundamentals', 'What is the operational value of Logstash''s dead-letter queue (routing `_grokparsefailure`-tagged events to a separate output) instead of letting failed-parse events flow to the normal index?', '["It automatically retries the grok pattern until it matches", "A grok match failure doesn''t error loudly by default -- the raw message is usually still indexed but with the intended structured fields missing; routing failures to a separate, visible index makes silent parsing gaps discoverable instead of quietly losing searchable structure", "It deletes the malformed event permanently", "It converts the failed event into a Kibana alert automatically"]', 1, 'Monitoring the volume of events landing in a dead-letter/parse-failure index is a direct way to catch grok patterns silently failing on log format variations that weren''t in the original test sample.', 'advanced'),

-- ---------- devops/elk-stack/intermediate ----------
('devops', 'elk-stack', 'intermediate', 'Why is `refresh_interval` commonly increased (e.g. from 1s to 30s) temporarily during a bulk data load?', '["It has no real effect and is a placebo setting", "A shorter refresh interval makes newly indexed documents searchable sooner but at a real indexing throughput cost -- during a bulk load where near-real-time search isn''t needed yet, a longer interval reduces that overhead significantly", "It permanently disables search on the index", "It only affects Kibana''s dashboard refresh, not Elasticsearch itself"]', 1, 'The standard pattern is to relax refresh_interval and set replicas to 0 during a bulk load, then restore both to production values (e.g. 1-5s refresh, replicas: 1) once the load completes.', 'intermediate'),
('devops', 'elk-stack', 'intermediate', 'What is the tradeoff of setting Logstash''s `index.translog.durability` to `async` instead of the default `request`?', '["There is no tradeoff -- async is strictly better in every case", "async improves indexing throughput but accepts a small risk of losing very recent, not-yet-fsynced writes if the node crashes -- a deliberate throughput-vs-durability tradeoff, not a free performance win", "async disables replication entirely", "async only affects Kibana queries, not indexing speed"]', 1, 'This mirrors a common pattern across durable-storage systems: relaxing a durability guarantee trades a small, bounded data-loss window for meaningfully higher write throughput.', 'advanced'),
('devops', 'elk-stack', 'intermediate', 'What is the main operational tradeoff of skipping Logstash entirely and using an Elasticsearch ingest pipeline for parsing instead?', '["Ingest pipelines cannot use grok patterns at all", "Ingest pipelines simplify deployment (no separate Logstash process to run) but run the parsing CPU cost on the same Elasticsearch node handling indexing/search, competing directly for those same resources", "Ingest pipelines require a completely different query language", "Ingest pipelines can only be used with Filebeat, never Logstash"]', 1, 'For modest parsing needs, skipping Logstash (Filebeat -> ingest pipeline -> Elasticsearch) is an increasingly common, simpler setup -- but at real scale, offloading parsing to a separate Logstash tier avoids competing with Elasticsearch''s own indexing and search workload.', 'advanced'),
('devops', 'elk-stack', 'intermediate', 'Why does the standard JVM heap sizing guidance for Elasticsearch cap out around 30-32GB even on a machine with much more RAM available?', '["Elasticsearch cannot use more than 32GB of RAM in total, for any purpose", "Above roughly 32GB, the JVM loses the ability to use compressed ordinary object pointers (compressed oops), which paradoxically makes a larger heap allocation less memory-efficient per object than staying under that threshold", "Elasticsearch licensing restricts heap size above 32GB without a paid tier", "It is an arbitrary historical default with no underlying technical reason"]', 1, 'The common guidance -- 50% of available RAM up to roughly 30-31GB, leaving the rest for the OS page cache Lucene relies on -- is a genuine JVM memory-addressing characteristic, not an arbitrary number.', 'advanced'),
('devops', 'elk-stack', 'intermediate', 'What does Logstash''s persistent queue (`queue.type: persisted`) protect against that the default in-memory queue does not?', '["It protects against grok pattern syntax errors", "It protects against event loss if the Logstash process itself crashes -- in-memory queued events that haven''t reached the output stage yet are otherwise lost on a crash", "It automatically compresses events before indexing", "It replaces the need for a dead-letter queue"]', 1, 'Persistent queues write buffered events to disk so a Logstash crash mid-pipeline doesn''t silently drop events that were already accepted from the input stage but not yet written to Elasticsearch.', 'intermediate'),

-- ---------- devops/elk-stack/advanced ----------
('devops', 'elk-stack', 'advanced', 'What does Cross-Cluster Replication (CCR) follow-index actually do, and what is a genuine use case?', '["It merges two separate clusters into one automatically", "A follower cluster continuously replicates a leader index''s data, commonly used for disaster recovery, geo-distribution, or maintaining a read-only dev/staging mirror of production data", "It splits one index into multiple smaller indices for performance", "It replaces the need for regular snapshot backups entirely"]', 1, 'CCR keeps a follower index in near-real-time sync with a leader index across clusters -- distinct from snapshot/restore, which is a point-in-time backup rather than continuous replication.', 'advanced'),
('devops', 'elk-stack', 'advanced', 'In an Elasticsearch role definition using `field_security` and a `query` restriction together, what kind of access control is actually being configured?', '["Only which indices a user may see, nothing more granular", "Both field-level security (which fields within a document a user can see, e.g. hiding sensitive_field) and document-level security (which documents a user can see at all, via the query restriction, e.g. only environment: production) simultaneously", "Only network-level access control (which IPs may connect)", "Only rate-limiting for that specific role"]', 1, 'Combining field_security and a document-level query restriction on one role is how Elasticsearch expresses "this user can search logs, but only production documents, and never the sensitive_field within them" in a single role definition.', 'advanced'),
('devops', 'elk-stack', 'advanced', 'When profiling a slow Elasticsearch query with `"profile": true`, what does a large `time_in_nanos` on a specific lucene query component actually indicate?', '["That component is a false positive and can be ignored", "That specific low-level query operation (e.g. a particular clause''s execution) is where most of the query''s actual time is being spent, pointing at exactly which part of a compound query to optimize rather than guessing at the whole query", "The entire cluster is under-provisioned regardless of which component is slow", "Profiling only measures network latency, not actual query execution time"]', 1, 'Profile output breaks a query down per-shard and per-clause, which is what makes it possible to target the actual expensive part of a bool query instead of rewriting the whole thing speculatively.', 'advanced'),
('devops', 'elk-stack', 'advanced', 'Why does high `fielddata` memory usage on a node specifically point to "aggregations on analyzed text fields" as the likely cause?', '["fielddata only tracks disk I/O, unrelated to aggregations", "Aggregating or sorting on an analyzed text field requires building an in-memory, per-term data structure at query time (since text fields aren''t stored in the doc-values structure keyword fields use) -- this is expensive and is exactly what fielddata usage measures", "fielddata usage is unrelated to query patterns and only reflects index size", "High fielddata always means a hardware failure is imminent"]', 1, 'The standard fix -- use the .keyword sub-field for aggregations instead of the analyzed text field -- avoids this cost entirely by aggregating against the already-exact-match-ready keyword representation.', 'advanced'),
('devops', 'elk-stack', 'advanced', 'What operational tradeoff does setting `number_of_replicas: 0` temporarily during a bulk load introduce, beyond faster indexing?', '["No tradeoff -- it is strictly beneficial with no downside", "It removes redundancy during the load window -- if the single (primary-only) shard copy is lost to a node failure before replicas are restored afterward, that data is genuinely gone, so this is a deliberate, time-boxed availability-for-throughput tradeoff", "It permanently disables replication for that index going forward", "It has no effect on indexing throughput, only on search latency"]', 1, 'This is the same class of throughput-vs-durability tradeoff as relaxing translog durability -- both are standard bulk-load optimizations that must be reverted to production settings afterward, not left in place indefinitely.', 'advanced')

ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
