-- ============================================================
-- /learn quiz: NEET Biology -- all 7 chapters: Cell - The Unit of
-- Life, Biomolecules, Principles of Inheritance and Variation,
-- Transport in Plants and Mineral Nutrition, Human Physiology, Plant
-- Kingdom, Ecology and Environment. First subject of the NEET board,
-- the final board for this /learn quiz-badge build.
--
-- SOURCING: same disclosed limitation as every /learn quiz batch this
-- session -- authored to match real NEET single-correct-MCQ style,
-- topic distribution, and difficulty for each chapter; NOT copied from
-- any official NEET question paper. Every biological claim below was
-- independently checked against standard NCERT Class 11/12 Biology
-- content before writing.
--
-- Applied via @supabase/supabase-js, upsert(rows, { onConflict:
-- "academy_slug,technology_slug,section_slug,question", ignoreDuplicates:
-- true }) -- functionally identical to this file's ON CONFLICT clause.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES
('education', 'neet/biology', 'cell-biology', 'The Cell Theory states that all living organisms are composed of cells and that:', '["Cells arise only from pre-existing cells", "Cells are always visible without a microscope", "All cells contain a nucleus", "Cells never divide once formed"]', 0, 'A core tenet of Cell Theory, added by Rudolf Virchow, is that new cells arise only from pre-existing cells (Omnis cellula e cellula), not by spontaneous generation.', 'beginner'),
('education', 'neet/biology', 'cell-biology', 'Prokaryotic cells are structurally distinguished from eukaryotic cells primarily by lacking:', '["A membrane-bound nucleus", "Any genetic material", "A cell membrane", "Ribosomes"]', 0, 'Prokaryotic cells lack a true, membrane-enclosed nucleus; their genetic material lies in the cytoplasm as a nucleoid region.', 'beginner'),
('education', 'neet/biology', 'cell-biology', 'The organelle primarily responsible for producing ATP through aerobic respiration is the:', '["Mitochondrion", "Golgi apparatus", "Lysosome", "Endoplasmic reticulum"]', 0, 'The mitochondrion, often called the "powerhouse of the cell," is the primary site of aerobic ATP production via oxidative phosphorylation.', 'beginner'),
('education', 'neet/biology', 'cell-biology', 'The structure of the plasma membrane is best described by the:', '["Fluid Mosaic Model", "Rigid Lattice Model", "Static Bilayer Model", "Single Protein Layer Model"]', 0, 'The Fluid Mosaic Model (Singer and Nicolson, 1972) describes the plasma membrane as a dynamic, fluid bilayer of phospholipids with embedded, mobile proteins.', 'intermediate'),
('education', 'neet/biology', 'cell-biology', 'The organelle responsible for photosynthesis in plant cells is the:', '["Chloroplast", "Mitochondrion", "Vacuole", "Nucleus"]', 0, 'The chloroplast, containing chlorophyll, is the site of photosynthesis, converting light energy into chemical energy in plant cells.', 'beginner'),
('education', 'neet/biology', 'biomolecules', 'The basic building block (monomer) of proteins is the:', '["Amino acid", "Glucose", "Fatty acid", "Nucleotide"]', 0, 'Proteins are polymers built from amino acid monomers linked by peptide bonds.', 'beginner'),
('education', 'neet/biology', 'biomolecules', 'Enzymes function primarily by acting as biological:', '["Catalysts that lower the activation energy of a reaction", "Structural components only, with no reactive role", "Energy sources for the cell", "Genetic material carriers"]', 0, 'Enzymes are biological catalysts that speed up reactions by lowering the activation energy required, without being consumed in the process.', 'beginner'),
('education', 'neet/biology', 'biomolecules', 'Which of the following is classified as a nucleic acid?', '["DNA", "Collagen", "Cellulose", "Cholesterol"]', 0, 'DNA (deoxyribonucleic acid) is a nucleic acid, a polymer of nucleotides; the other options are a protein, a polysaccharide, and a lipid respectively.', 'beginner'),
('education', 'neet/biology', 'biomolecules', 'The Michaelis constant (Km) of an enzyme represents the substrate concentration at which the reaction velocity is:', '["Half of the maximum velocity (Vmax)", "Equal to the maximum velocity (Vmax)", "Zero", "Twice the maximum velocity (Vmax)"]', 0, 'Km is defined as the substrate concentration at which the reaction rate reaches half of Vmax, a measure of an enzyme''s affinity for its substrate.', 'intermediate'),
('education', 'neet/biology', 'biomolecules', 'Lipids such as fats are primarily composed of fatty acids and:', '["Glycerol", "Amino acids", "Ribose sugar", "Nucleotide bases"]', 0, 'Common lipids (triglycerides) are formed by esterification of three fatty acid molecules with a glycerol backbone.', 'beginner'),
('education', 'neet/biology', 'genetics-principles', 'Mendel''s Law of Segregation states that:', '["The two alleles of a gene separate during gamete formation, so each gamete receives only one allele", "Alleles of different genes always assort independently", "Dominant alleles are always physically larger than recessive alleles", "Alleles blend together to form an intermediate trait"]', 0, 'The Law of Segregation states that the two alleles for a trait separate during meiosis, so each gamete carries only one allele of the gene pair.', 'beginner'),
('education', 'neet/biology', 'genetics-principles', 'In a dihybrid cross between two heterozygous parents (RrYy x RrYy), the expected phenotypic ratio in the offspring is:', '["9:3:3:1", "3:1", "1:2:1", "1:1:1:1"]', 0, 'A dihybrid cross between two double heterozygotes produces the classic 9:3:3:1 phenotypic ratio, assuming independent assortment of the two genes.', 'intermediate'),
('education', 'neet/biology', 'genetics-principles', 'Codominance is exhibited when:', '["Both alleles are fully and simultaneously expressed in the heterozygote (e.g. AB blood group)", "One allele completely masks the other", "The heterozygote shows a blended, intermediate phenotype", "Neither allele is expressed in the heterozygote"]', 0, 'Codominance occurs when both alleles in a heterozygote are fully expressed without blending, as seen in the AB blood group, where both A and B antigens are present.', 'intermediate'),
('education', 'neet/biology', 'genetics-principles', 'In humans, the sex of a child is determined by which sex chromosome is contributed by the father:', '["X (resulting in a female) or Y (resulting in a male)", "Only the mother''s chromosome determines sex", "An autosome determines sex, not a sex chromosome", "Sex is determined by hormone levels alone, not chromosomes"]', 0, 'The mother always contributes an X chromosome; the father''s contribution of either X or Y determines whether the offspring is female (XX) or male (XY).', 'beginner'),
('education', 'neet/biology', 'genetics-principles', 'Down syndrome in humans is caused by:', '["Trisomy of chromosome 21 (an extra copy)", "A deletion on the X chromosome", "Trisomy of chromosome 13", "A point mutation in a single gene"]', 0, 'Down syndrome results from the presence of an extra copy of chromosome 21 (trisomy 21), the most common chromosomal disorder in humans.', 'beginner'),
('education', 'neet/biology', 'plant-physiology', 'Osmosis is the movement of water molecules from a region of:', '["Higher water potential to lower water potential, through a selectively permeable membrane", "Lower water potential to higher water potential", "High solute concentration to low solute concentration directly", "Any concentration to any other, regardless of membrane"]', 0, 'Osmosis is the passive movement of water across a selectively permeable membrane, from a region of higher water potential to a region of lower water potential.', 'beginner'),
('education', 'neet/biology', 'plant-physiology', 'Plasmolysis occurs when a plant cell is placed in a:', '["Hypertonic solution, causing the protoplast to shrink away from the cell wall", "Hypotonic solution, causing the cell to swell and burst", "Isotonic solution, causing no net water movement", "Solution of pure water only"]', 0, 'In a hypertonic solution, water leaves the cell by osmosis, causing the protoplast (cell membrane and its contents) to shrink away from the rigid cell wall -- plasmolysis.', 'intermediate'),
('education', 'neet/biology', 'plant-physiology', 'Biological nitrogen fixation converts atmospheric nitrogen gas into a usable form, primarily:', '["Ammonia", "Nitrate directly, bypassing ammonia", "Nitrogen dioxide", "Nitrous oxide"]', 0, 'Nitrogen-fixing bacteria such as Rhizobium convert atmospheric N2 into ammonia (NH3), which plants can then use to synthesize amino acids and other compounds.', 'intermediate'),
('education', 'neet/biology', 'plant-physiology', 'Guard cells in plant leaves primarily regulate the:', '["Opening and closing of stomata", "Rate of cell division in the leaf", "Transport of sugars through the phloem", "Synthesis of chlorophyll"]', 0, 'Paired guard cells surround each stoma and change shape (due to turgor pressure changes) to open or close the stomatal pore, controlling gas exchange and water loss.', 'beginner'),
('education', 'neet/biology', 'plant-physiology', 'The Cohesion-Tension Theory explains the ascent of water (sap) in tall plants through the xylem, driven primarily by:', '["Transpiration pull combined with the cohesive properties of water molecules", "Active pumping by root cells alone", "Gravity pulling water upward", "Osmotic pressure in the phloem"]', 0, 'The Cohesion-Tension Theory explains water''s upward movement through xylem as a continuous column, pulled by transpiration at the leaves and held together by cohesive hydrogen bonding between water molecules.', 'intermediate'),
('education', 'neet/biology', 'human-physiology', 'The enzyme pepsin, which begins protein digestion, is secreted primarily in the:', '["Stomach", "Small intestine", "Mouth", "Liver"]', 0, 'Pepsin is secreted by gastric chief cells in the stomach (as inactive pepsinogen, activated by stomach acid) and begins breaking down proteins.', 'beginner'),
('education', 'neet/biology', 'human-physiology', 'The primary function of hemoglobin in red blood cells is to:', '["Transport oxygen (and some carbon dioxide) in the blood", "Fight bacterial infections", "Clot blood at wound sites", "Produce antibodies"]', 0, 'Hemoglobin binds oxygen in the lungs and releases it to tissues, and also carries a portion of carbon dioxide back to the lungs.', 'beginner'),
('education', 'neet/biology', 'human-physiology', 'The functional and structural unit of the human kidney, responsible for blood filtration, is the:', '["Nephron", "Alveolus", "Neuron", "Hepatocyte"]', 0, 'The nephron is the basic functional unit of the kidney, responsible for filtering blood plasma and forming urine.', 'beginner'),
('education', 'neet/biology', 'human-physiology', 'The natural pacemaker of the human heart, the SA (sinoatrial) node, is located in the:', '["Right atrium", "Left ventricle", "Right ventricle", "Left atrium"]', 0, 'The SA node, located in the wall of the right atrium, generates the electrical impulses that initiate each heartbeat.', 'intermediate'),
('education', 'neet/biology', 'human-physiology', 'Antidiuretic hormone (ADH) primarily regulates the body''s water balance by:', '["Increasing water reabsorption in the kidneys, reducing urine volume", "Increasing urine volume directly", "Regulating blood sugar levels", "Controlling heart rate"]', 0, 'ADH (vasopressin) increases water reabsorption in the kidney''s collecting ducts, concentrating urine and conserving body water.', 'intermediate'),
('education', 'neet/biology', 'plant-kingdom', 'Bryophytes are commonly referred to as the "amphibians of the plant kingdom" because they:', '["Require water for fertilization and represent a link between aquatic algae and land plants", "Live exclusively in water throughout their life cycle", "Have fully developed vascular tissue like ferns", "Produce seeds enclosed in fruit"]', 0, 'Bryophytes (mosses, liverworts) need a film of water for their motile sperm to reach the egg, tying them to moist habitats -- hence the "amphibian" comparison, as an evolutionary link between water-dependent algae and fully terrestrial plants.', 'intermediate'),
('education', 'neet/biology', 'plant-kingdom', 'Alternation of generations in plants refers to the life cycle alternating between:', '["A haploid gametophyte phase and a diploid sporophyte phase", "Two different diploid phases only", "Two different haploid phases only", "A single phase that never changes ploidy"]', 0, 'Plant life cycles alternate between a haploid, gamete-producing gametophyte generation and a diploid, spore-producing sporophyte generation.', 'intermediate'),
('education', 'neet/biology', 'plant-kingdom', 'Gymnosperms are characterized by seeds that are:', '["Not enclosed within a fruit (naked seeds)", "Always enclosed within a fruit", "Absent entirely, reproducing only by spores", "Formed without any fertilization process"]', 0, 'The term "gymnosperm" literally means "naked seed" -- their seeds develop exposed, typically on the scales of cones, unlike angiosperm seeds enclosed in a fruit.', 'beginner'),
('education', 'neet/biology', 'plant-kingdom', 'The primary distinguishing feature between monocot and dicot flowering plants is the:', '["Number of cotyledons in the seed (one versus two)", "Color of the flower", "Presence or absence of roots", "Overall height of the mature plant"]', 0, 'Monocots have a single cotyledon (seed leaf) in their embryo, while dicots have two -- the defining feature used to classify angiosperms into these two groups.', 'beginner'),
('education', 'neet/biology', 'plant-kingdom', 'Pteridophytes (ferns and their relatives) are notable in plant evolution as the first group of plants to develop:', '["True vascular tissue (xylem and phloem)", "Flowers", "Seeds", "Chlorophyll"]', 0, 'Pteridophytes were the first land plants to evolve well-differentiated vascular tissue (xylem and phloem), enabling more efficient transport and larger plant size than bryophytes.', 'intermediate'),
('education', 'neet/biology', 'ecology', 'In a food web, organisms that obtain energy by consuming other organisms are called:', '["Consumers (heterotrophs)", "Producers (autotrophs)", "Decomposers only", "Abiotic components"]', 0, 'Consumers (heterotrophs) obtain energy by feeding on other organisms, in contrast to producers, which generate their own food via photosynthesis.', 'beginner'),
('education', 'neet/biology', 'ecology', 'Biodiversity hotspots are regions characterized by:', '["High species richness and high endemism, facing significant threat", "Uniformly low species diversity", "Complete absence of human impact", "Only aquatic ecosystems"]', 0, 'Biodiversity hotspots are regions with exceptionally high numbers of endemic species (found nowhere else) that are also under significant threat from habitat loss.', 'intermediate'),
('education', 'neet/biology', 'ecology', 'The carbon cycle, which moves carbon through the atmosphere, oceans, and living organisms, is an example of a:', '["Biogeochemical cycle", "Food chain", "Trophic pyramid", "Population growth model"]', 0, 'The carbon cycle is a classic biogeochemical cycle, describing the movement of a chemical element through both biotic and abiotic components of the environment.', 'beginner'),
('education', 'neet/biology', 'ecology', 'Global warming is primarily attributed to an increased atmospheric concentration of:', '["Greenhouse gases (such as carbon dioxide and methane)", "Oxygen", "Nitrogen gas", "Ozone in the stratosphere"]', 0, 'Rising levels of greenhouse gases, particularly CO2 and methane, trap more heat in the atmosphere, driving global warming.', 'beginner'),
('education', 'neet/biology', 'ecology', 'The logistic growth model describes a population whose growth rate:', '["Slows as the population approaches the environment''s carrying capacity (K)", "Remains constant regardless of population size", "Increases indefinitely without any limit", "Is always negative"]', 0, 'Unlike unrestrained exponential growth, the logistic model accounts for limited resources, causing growth to slow and level off as the population nears the carrying capacity K.', 'intermediate')
ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
