-- ============================================================
-- /learn quiz: CBSE Class 10 Maths -- batch 3, final batch. Covers the
-- remaining 7 of the subject's 15 chapters (Some Applications of
-- Trigonometry, Circles, Constructions, Areas Related to Circles,
-- Surface Areas and Volumes, Statistics, Probability), completing the
-- subject started in the pilot batch (Real Numbers, Quadratic
-- Equations) and batch 2 (Polynomials, Linear Equations, Arithmetic
-- Progressions, Triangles, Coordinate Geometry, Trigonometry).
--
-- SOURCING: same disclosed limitation as batches 1-2 -- authored to
-- match real CBSE Section-A (1-mark objective) exam style, topic
-- distribution, and difficulty for each chapter; NOT copied from any
-- official CBSE question paper. Every numeric question below was
-- independently math-checked before writing.
--
-- Applied via @supabase/supabase-js, upsert(rows, { onConflict:
-- "academy_slug,technology_slug,section_slug,question", ignoreDuplicates:
-- true }) -- functionally identical to this file's ON CONFLICT clause.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES
('education', 'class-10/maths', 'heights-distances', 'The angle of elevation of an object is the angle formed by the line of sight with the horizontal when the object is:', '["Above the horizontal level of the observer", "Below the horizontal level of the observer", "At the same level as the observer", "Behind the observer"]', 0, 'The angle of elevation is measured upward from the horizontal to the line of sight when viewing an object above the observer''s eye level.', 'beginner'),
('education', 'class-10/maths', 'heights-distances', 'A tower casts a shadow of length 10 m when the angle of elevation of the sun is 45 degrees. The height of the tower is:', '["10 m", "5 m", "20 m", "10 x sqrt(3) m"]', 0, 'height/shadow = tan(45) = 1, so height = 10 x 1 = 10 m.', 'intermediate'),
('education', 'class-10/maths', 'heights-distances', 'From a point 30 m away from the base of a tower, the angle of elevation of its top is 30 degrees. The height of the tower is:', '["10 x sqrt(3) m", "30 x sqrt(3) m", "15 m", "30 m"]', 0, 'height = 30 x tan(30) = 30 x (1/sqrt(3)) = 30/sqrt(3) = 10 x sqrt(3) m.', 'intermediate'),
('education', 'class-10/maths', 'heights-distances', 'The angle of depression is measured from the horizontal line at the observer''s eye level to a line of sight directed toward an object:', '["Below the observer", "Above the observer", "At the same level as the observer", "Directly overhead"]', 0, 'The angle of depression is the angle below the horizontal when looking down at an object.', 'beginner'),
('education', 'class-10/maths', 'heights-distances', 'A ladder 10 m long leans against a wall, making an angle of 60 degrees with the ground. The height it reaches on the wall is:', '["5 x sqrt(3) m", "10 x sqrt(3) m", "5 m", "10/sqrt(3) m"]', 0, 'height = 10 x sin(60) = 10 x (sqrt(3)/2) = 5 x sqrt(3) m.', 'intermediate'),
('education', 'class-10/maths', 'circles', 'A tangent to a circle touches it at:', '["Exactly one point", "Exactly two points", "Three points", "Infinitely many points"]', 0, 'By definition, a tangent to a circle intersects it at exactly one point, the point of contact.', 'beginner'),
('education', 'class-10/maths', 'circles', 'From an external point, the number of tangents that can be drawn to a circle is:', '["2", "1", "0", "Infinite"]', 0, 'Exactly two tangents can always be drawn to a circle from any point outside it.', 'beginner'),
('education', 'class-10/maths', 'circles', 'The length of a tangent drawn from a point 13 cm away from the center of a circle of radius 5 cm is:', '["12 cm", "13 cm", "5 cm", "18 cm"]', 0, 'By the Pythagoras theorem (tangent is perpendicular to the radius at the point of contact): tangent length = sqrt(13^2 - 5^2) = sqrt(169-25) = sqrt(144) = 12 cm.', 'intermediate'),
('education', 'class-10/maths', 'circles', 'The tangent to a circle is always ___ to the radius at the point of contact.', '["Perpendicular", "Parallel", "At 45 degrees", "At 60 degrees"]', 0, 'A fundamental property of circles: the tangent at any point is perpendicular to the radius drawn to that point.', 'beginner'),
('education', 'class-10/maths', 'circles', 'If two tangents are drawn to a circle from the same external point, their lengths are:', '["Equal", "In the ratio 1:2", "Never equal", "Equal only if the point lies on the circle"]', 0, 'The two tangent segments from a common external point to a circle are always equal in length -- a standard, frequently proved theorem.', 'intermediate'),
('education', 'class-10/maths', 'constructions', 'To divide a line segment AB in the ratio m:n, the minimum number of equally spaced points that must be marked on the auxiliary ray is:', '["m + n", "m x n", "m - n", "Only 2, regardless of m and n"]', 0, 'The construction method requires marking exactly m+n equally spaced points on the auxiliary ray before joining the last point to B and drawing parallels.', 'intermediate'),
('education', 'class-10/maths', 'constructions', 'To construct a triangle similar to a given triangle with a scale factor smaller than 1 (e.g. 3/4), the construction relies on:', '["The Basic Proportionality Theorem (similar triangles)", "The Pythagoras Theorem", "The tangent-radius perpendicularity property", "The section formula"]', 0, 'Constructing a scaled similar triangle uses the Basic Proportionality Theorem to mark proportionate points and draw parallel lines.', 'intermediate'),
('education', 'class-10/maths', 'constructions', 'To construct the tangents to a circle from an external point P, the first step is to find the midpoint of:', '["The line segment joining the center and point P", "Any chord of the circle", "The diameter of the circle", "The tangent line itself"]', 0, 'A circle is drawn with the midpoint of OP (O = center, P = external point) as center and OP/2 as radius; where this circle intersects the original circle gives the points of tangency.', 'intermediate'),
('education', 'class-10/maths', 'constructions', 'The number of tangents that can be drawn to a circle from a point INSIDE the circle is:', '["0", "1", "2", "Infinite"]', 0, 'No tangent can be drawn from a point strictly inside a circle, since every line through an interior point intersects the circle at two points (a secant), not one.', 'beginner'),
('education', 'class-10/maths', 'constructions', 'To divide a line segment AB in the ratio 2:3, how many equally spaced points should be marked on the auxiliary ray AX?', '["5", "2", "3", "6"]', 0, 'The number of points required equals the sum of the ratio terms: 2+3 = 5.', 'beginner'),
('education', 'class-10/maths', 'areas-related-circles', 'The area of a circle with radius r is given by:', '["pi x r^2", "2 x pi x r", "pi x r", "4 x pi x r^2"]', 0, 'The standard formula for the area of a circle is pi x r^2.', 'beginner'),
('education', 'class-10/maths', 'areas-related-circles', 'The area of a sector of a circle with radius r and angle theta (in degrees) at the center is:', '["(theta/360) x pi x r^2", "(theta/180) x pi x r^2", "theta x pi x r^2", "(360/theta) x pi x r^2"]', 0, 'A sector''s area is the fraction (theta/360) of the full circle''s area, pi x r^2.', 'beginner'),
('education', 'class-10/maths', 'areas-related-circles', 'Using pi = 22/7, the area of a sector with radius 7 cm and angle 90 degrees is:', '["38.5 cm^2", "77 cm^2", "19.25 cm^2", "154 cm^2"]', 0, 'Area = (90/360) x (22/7) x 7^2 = (1/4) x 22 x 7 = 38.5 cm^2.', 'intermediate'),
('education', 'class-10/maths', 'areas-related-circles', 'Using pi = 22/7, the circumference of a circle with radius 14 cm is:', '["88 cm", "44 cm", "28 cm", "176 cm"]', 0, 'Circumference = 2 x pi x r = 2 x (22/7) x 14 = 88 cm.', 'beginner'),
('education', 'class-10/maths', 'areas-related-circles', 'Using pi = 22/7, the area of a circle with radius 7 cm is:', '["154 cm^2", "77 cm^2", "44 cm^2", "198 cm^2"]', 0, 'Area = pi x r^2 = (22/7) x 7^2 = (22/7) x 49 = 154 cm^2.', 'beginner'),
('education', 'class-10/maths', 'surface-areas-volumes', 'The volume of a right circular cylinder with radius r and height h is:', '["pi x r^2 x h", "(1/3) x pi x r^2 x h", "2 x pi x r x h", "(4/3) x pi x r^3"]', 0, 'The standard volume formula for a cylinder is pi x r^2 x h.', 'beginner'),
('education', 'class-10/maths', 'surface-areas-volumes', 'The volume of a right circular cone with radius r and height h is:', '["(1/3) x pi x r^2 x h", "pi x r^2 x h", "(4/3) x pi x r^3", "2 x pi x r x h"]', 0, 'A cone''s volume is exactly one-third of a cylinder with the same base radius and height: (1/3) x pi x r^2 x h.', 'beginner'),
('education', 'class-10/maths', 'surface-areas-volumes', 'The volume of a sphere with radius r is:', '["(4/3) x pi x r^3", "pi x r^2 x h", "4 x pi x r^2", "(1/3) x pi x r^3"]', 0, 'The standard formula for the volume of a sphere is (4/3) x pi x r^3.', 'beginner'),
('education', 'class-10/maths', 'surface-areas-volumes', 'Using pi = 22/7, the volume of a cylinder with radius 7 cm and height 10 cm is:', '["1540 cm^3", "770 cm^3", "3080 cm^3", "220 cm^3"]', 0, 'Volume = pi x r^2 x h = (22/7) x 49 x 10 = 22 x 7 x 10 = 1540 cm^3.', 'intermediate'),
('education', 'class-10/maths', 'surface-areas-volumes', 'When a cone is mounted on top of a cylinder to form a single combined solid, its total surface area equals:', '["CSA of cylinder + CSA of cone + area of one circular base", "CSA of cylinder + CSA of cone", "Volume of cylinder + volume of cone", "The sum of each solid''s own total surface area"]', 0, 'For a combined solid, the surfaces where the two shapes join are internal and excluded; only the curved surfaces plus the single exposed flat base are counted.', 'intermediate'),
('education', 'class-10/maths', 'statistics', 'The mean of grouped data by the direct method is calculated as:', '["Sum of (frequency x midpoint) divided by sum of frequencies", "Sum of frequencies divided by number of classes", "Midpoint of the class with highest frequency", "Sum of midpoints divided by number of classes"]', 0, 'The direct method formula is mean = (sum of fi*xi) / (sum of fi), where xi is each class midpoint and fi its frequency.', 'beginner'),
('education', 'class-10/maths', 'statistics', 'In finding the mode of grouped data, the class with the highest frequency is called the:', '["Modal class", "Median class", "Cumulative class", "Mean class"]', 0, 'The modal class is the class interval with the highest frequency, used as the basis for the mode formula.', 'beginner'),
('education', 'class-10/maths', 'statistics', 'The median class of grouped data is the class in which:', '["The cumulative frequency first equals or exceeds n/2", "The frequency is highest", "The class width is largest", "The midpoint equals the mean"]', 0, 'The median class is identified as the first class interval whose cumulative frequency reaches or exceeds n/2.', 'intermediate'),
('education', 'class-10/maths', 'statistics', 'The mean of the data 2, 4, 6, 8, 10 is:', '["6", "5", "8", "30"]', 0, 'Mean = sum of values / number of values = (2+4+6+8+10)/5 = 30/5 = 6.', 'beginner'),
('education', 'class-10/maths', 'statistics', 'An ogive (cumulative frequency curve) is primarily used to graphically determine the:', '["Median", "Mean", "Mode", "Range"]', 0, 'The ogive is the standard graphical method for determining the median of grouped data.', 'intermediate'),
('education', 'class-10/maths', 'probability', 'The probability of an event E is defined as:', '["Number of favourable outcomes divided by total number of possible outcomes", "Number of unfavourable outcomes divided by total outcomes", "Total outcomes divided by favourable outcomes", "Number of favourable outcomes minus total outcomes"]', 0, 'This is the classical (theoretical) definition of probability used throughout the CBSE Class 10 syllabus.', 'beginner'),
('education', 'class-10/maths', 'probability', 'The probability of a sure event is:', '["1", "0", "0.5", "Cannot be determined"]', 0, 'A sure (certain) event always occurs, so its probability is exactly 1.', 'beginner'),
('education', 'class-10/maths', 'probability', 'The probability of an impossible event is:', '["0", "1", "0.5", "Cannot be determined"]', 0, 'An impossible event never occurs, so its probability is exactly 0.', 'beginner'),
('education', 'class-10/maths', 'probability', 'A die is thrown once. The probability of getting an even number is:', '["1/2", "1/3", "1/6", "2/3"]', 0, 'Favourable outcomes {2,4,6} = 3 out of 6 total outcomes, so probability = 3/6 = 1/2.', 'beginner'),
('education', 'class-10/maths', 'probability', 'For any event E, the sum of P(E) and P(not E) (the complementary event) is always:', '["1", "0", "0.5", "Depends on the event"]', 0, 'An event and its complement together cover all possible outcomes, so their probabilities always sum to exactly 1.', 'beginner')
ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
