-- ============================================================
-- /learn quiz: JEE Physics -- batch 2, final Physics batch
-- (Gravitation, Thermodynamics, Electrostatics/Current/Magnetism,
-- Modern Physics): Gravitation, Thermodynamics, Electrostatics,
-- Current Electricity, Magnetic Effects of Current, Modern Physics.
-- Completes the remaining 6 of the subject's 11 chapters (batch 1
-- covered Mechanics).
--
-- SOURCING: same disclosed limitation as batch 1 -- authored to match
-- real JEE Main single-correct-MCQ style/difficulty, NOT copied from
-- any official JEE question paper. Every numeric/formula claim below
-- was independently checked before writing.
--
-- Applied via @supabase/supabase-js, upsert(rows, { onConflict:
-- "academy_slug,technology_slug,section_slug,question", ignoreDuplicates:
-- true }) -- functionally identical to this file's ON CONFLICT clause.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES
('education', 'jee/physics', 'gravitation', 'The Universal Law of Gravitation states that the gravitational force between two masses is given by:', '["F = G m1 m2 / r^2", "F = G m1 m2 / r", "F = G (m1+m2) / r^2", "F = G m1 m2 r^2"]', 0, 'Newton''s Universal Law of Gravitation: F = G m1 m2 / r^2, where G is the gravitational constant and r is the separation between the masses.', 'beginner'),
('education', 'jee/physics', 'gravitation', 'Kepler''s Third Law states that the square of a planet''s orbital period (T) is proportional to:', '["The cube of the semi-major axis of its orbit", "The semi-major axis of its orbit", "The square of the semi-major axis", "The planet''s mass"]', 0, 'Kepler''s Third Law: T^2 is proportional to a^3, where a is the semi-major axis of the planet''s elliptical orbit.', 'intermediate'),
('education', 'jee/physics', 'gravitation', 'The escape velocity from a planet of mass M and radius R is given by:', '["sqrt(2GM/R)", "sqrt(GM/R)", "GM/R^2", "sqrt(GM/R^2)"]', 0, 'Escape velocity is derived by equating kinetic energy to gravitational potential energy: v(escape) = sqrt(2GM/R).', 'intermediate'),
('education', 'jee/physics', 'gravitation', 'The orbital velocity of a satellite very close to a planet''s surface (radius R, surface gravity g) is given by:', '["sqrt(gR)", "sqrt(2gR)", "gR", "sqrt(g/R)"]', 0, 'For a satellite orbiting just above the surface, orbital velocity v(orbital) = sqrt(gR), derived by equating gravitational force to the required centripetal force.', 'intermediate'),
('education', 'jee/physics', 'gravitation', 'The escape velocity of a planet is related to its near-surface orbital velocity by:', '["v(escape) = sqrt(2) x v(orbital)", "v(escape) = v(orbital)", "v(escape) = 2 x v(orbital)", "v(escape) = v(orbital) / sqrt(2)"]', 0, 'Since v(escape)=sqrt(2gR) and v(orbital)=sqrt(gR), dividing gives v(escape) = sqrt(2) x v(orbital).', 'intermediate'),
('education', 'jee/physics', 'thermodynamics', 'The First Law of Thermodynamics can be stated as:', '["Heat supplied = change in internal energy + work done by the system", "Heat supplied = work done alone", "Internal energy is always conserved regardless of heat or work", "Work done = heat supplied minus entropy"]', 0, 'The First Law is a statement of energy conservation: dQ = dU + dW, where dQ is heat added, dU is change in internal energy, and dW is work done by the system.', 'beginner'),
('education', 'jee/physics', 'thermodynamics', 'The efficiency of a Carnot engine operating between source temperature T1 and sink temperature T2 (both in Kelvin) is given by:', '["1 - T2/T1", "T2/T1", "1 + T2/T1", "T1/T2"]', 0, 'Carnot efficiency = 1 - T2/T1, the maximum possible efficiency for any heat engine operating between these two temperatures.', 'intermediate'),
('education', 'jee/physics', 'thermodynamics', 'In an isothermal process, the temperature of the system:', '["Remains constant", "Increases continuously", "Decreases continuously", "Is undefined"]', 0, 'By definition, an isothermal process occurs at constant temperature throughout.', 'beginner'),
('education', 'jee/physics', 'thermodynamics', 'In an adiabatic process, the amount of heat exchanged with the surroundings is:', '["Zero (Q = 0)", "Maximum possible", "Equal to the work done", "Equal to the change in internal energy only"]', 0, 'An adiabatic process is defined by zero heat exchange with the surroundings (Q=0); any change in internal energy comes entirely from work done.', 'beginner'),
('education', 'jee/physics', 'thermodynamics', 'The Second Law of Thermodynamics implies that heat cannot flow spontaneously from a:', '["Colder body to a hotter body without external work", "Hotter body to a colder body", "System to its surroundings", "Gas to a liquid"]', 0, 'The Clausius statement of the Second Law: heat cannot spontaneously flow from a colder to a hotter body without external work being done on the system.', 'beginner'),
('education', 'jee/physics', 'electrostatics', 'Coulomb''s Law gives the electrostatic force between two point charges as:', '["F = k q1 q2 / r^2", "F = k q1 q2 / r", "F = k (q1+q2) / r^2", "F = k q1 q2 r^2"]', 0, 'Coulomb''s Law: F = k q1 q2 / r^2, analogous in form to Newton''s law of gravitation but for electric charges.', 'beginner'),
('education', 'jee/physics', 'electrostatics', 'The electric field due to a point charge q at distance r is given by:', '["E = k q / r^2", "E = k q / r", "E = k q r^2", "E = k q r"]', 0, 'The electric field of a point charge follows an inverse-square law: E = k q / r^2, consistent with Coulomb''s Law.', 'beginner'),
('education', 'jee/physics', 'electrostatics', 'The capacitance of a capacitor is defined as the ratio of:', '["Charge stored to the potential difference across it (C = Q/V)", "Potential difference to charge stored", "Charge to the electric field", "Energy stored to charge"]', 0, 'Capacitance is defined as C = Q/V, the charge stored per unit potential difference.', 'beginner'),
('education', 'jee/physics', 'electrostatics', 'For capacitors connected in series, the equivalent capacitance is given by:', '["1/Ceq = 1/C1 + 1/C2 + ...", "Ceq = C1 + C2 + ...", "Ceq = C1 x C2", "1/Ceq = C1 + C2"]', 0, 'In series, the reciprocals of individual capacitances add up: 1/Ceq = 1/C1 + 1/C2 + ..., the opposite pattern from series resistors.', 'intermediate'),
('education', 'jee/physics', 'electrostatics', 'For capacitors connected in parallel, the equivalent capacitance is given by:', '["Ceq = C1 + C2 + ...", "1/Ceq = 1/C1 + 1/C2 + ...", "Ceq = C1 x C2", "Ceq = C1 - C2"]', 0, 'In parallel, capacitances simply add: Ceq = C1 + C2 + ..., the opposite pattern from series capacitors.', 'intermediate'),
('education', 'jee/physics', 'current-electricity', 'Kirchhoff''s Current Law (junction rule) states that at any junction in a circuit:', '["The sum of currents entering equals the sum of currents leaving", "All currents must be equal", "Current is always conserved only in series circuits", "Voltage is conserved, not current"]', 0, 'Kirchhoff''s Current Law is a statement of charge conservation: total current entering a junction equals total current leaving it.', 'beginner'),
('education', 'jee/physics', 'current-electricity', 'Kirchhoff''s Voltage Law (loop rule) states that around any closed loop in a circuit:', '["The algebraic sum of potential differences is zero", "The sum of all currents is zero", "The total resistance is zero", "The total power dissipated is zero"]', 0, 'Kirchhoff''s Voltage Law is a statement of energy conservation: the sum of voltage rises and drops around any closed loop equals zero.', 'beginner'),
('education', 'jee/physics', 'current-electricity', 'In a balanced Wheatstone bridge with resistances P, Q, R, S arranged in the standard configuration, the balance condition is:', '["P/Q = R/S", "P x Q = R x S", "P + Q = R + S", "P - Q = R - S"]', 0, 'A Wheatstone bridge is balanced (no current through the galvanometer) when P/Q = R/S, the ratio condition of its four arms.', 'intermediate'),
('education', 'jee/physics', 'current-electricity', 'When resistors R1 and R2 are connected in series in a circuit, their equivalent resistance is:', '["R1 + R2", "(R1 x R2)/(R1+R2)", "1/R1 + 1/R2", "R1 - R2"]', 0, 'In series, resistances add directly: Req = R1 + R2.', 'beginner'),
('education', 'jee/physics', 'current-electricity', 'A potentiometer is primarily used to measure:', '["EMF and potential differences with high accuracy (null-deflection method)", "Only current, not voltage", "Only resistance directly", "Magnetic field strength"]', 0, 'A potentiometer measures EMF/potential difference precisely by balancing it against a known potential drop, drawing no current from the source being measured at balance.', 'intermediate'),
('education', 'jee/physics', 'magnetic-effects', 'The Biot-Savart Law gives the magnetic field produced by:', '["A small current-carrying element", "A stationary point charge", "A uniform electric field", "A capacitor"]', 0, 'The Biot-Savart Law describes the magnetic field contribution from a small element of current-carrying conductor.', 'beginner'),
('education', 'jee/physics', 'magnetic-effects', 'Ampere''s Circuital Law relates the line integral of the magnetic field around a closed loop to:', '["The total current enclosed by the loop", "The total charge enclosed by the loop", "The magnetic flux through the loop", "The EMF induced in the loop"]', 0, 'Ampere''s Circuital Law: the closed-loop line integral of B equals mu0 times the total current enclosed by that loop.', 'intermediate'),
('education', 'jee/physics', 'magnetic-effects', 'The force on a current-carrying conductor of length L carrying current I in a magnetic field B is given by:', '["F = BIL sin(theta)", "F = BIL cos(theta)", "F = BI/L", "F = B/(IL)"]', 0, 'The force on a current-carrying conductor in a magnetic field is F = BIL sin(theta), where theta is the angle between the current direction and the field.', 'intermediate'),
('education', 'jee/physics', 'magnetic-effects', 'In a moving coil galvanometer, the deflection of the coil is directly proportional to:', '["The current flowing through the coil", "The resistance of the coil", "The area of the coil only", "The magnetic field strength alone"]', 0, 'A moving coil galvanometer is designed so that its deflection is directly proportional to the current passing through the coil, enabling it to measure current.', 'beginner'),
('education', 'jee/physics', 'magnetic-effects', 'The magnetic field inside a long solenoid with n turns per unit length carrying current I is given by:', '["B = mu0 n I", "B = mu0 I / n", "B = mu0 n / I", "B = mu0 n I^2"]', 0, 'The magnetic field inside an ideal long solenoid is uniform and given by B = mu0 n I, where n is the number of turns per unit length.', 'intermediate'),
('education', 'jee/physics', 'modern-physics', 'According to Einstein''s photoelectric equation, the maximum kinetic energy of emitted photoelectrons is given by:', '["KE(max) = h(nu) - phi (work function)", "KE(max) = h(nu) + phi", "KE(max) = h/(nu)", "KE(max) = phi - h(nu)"]', 0, 'Einstein''s photoelectric equation: KE(max) = h(nu) - phi, where h(nu) is the photon energy and phi is the metal''s work function.', 'intermediate'),
('education', 'jee/physics', 'modern-physics', 'In the Bohr model of the atom, the angular momentum of an electron in the nth orbit is quantized as:', '["n h / (2 pi)", "n h", "h / (2 pi n)", "n^2 h / (2 pi)"]', 0, 'Bohr''s quantization postulate: the angular momentum of an orbiting electron is an integer multiple of h/(2 pi): L = n h / (2 pi).', 'intermediate'),
('education', 'jee/physics', 'modern-physics', 'The half-life of a radioactive substance is related to its decay constant (lambda) by:', '["t(1/2) = 0.693 / lambda", "t(1/2) = lambda / 0.693", "t(1/2) = 1 / lambda", "t(1/2) = lambda"]', 0, 'Half-life is related to the decay constant by t(1/2) = ln(2)/lambda = 0.693/lambda.', 'intermediate'),
('education', 'jee/physics', 'modern-physics', 'The continuous X-ray spectrum is primarily produced by:', '["Sudden deceleration of high-speed electrons striking a target (Bremsstrahlung)", "Electron transitions between fixed atomic energy levels only", "Nuclear fission reactions", "Photoelectric emission from the target"]', 0, 'Continuous (Bremsstrahlung) X-rays arise from the sudden deceleration of fast electrons as they strike a metal target, converting kinetic energy into a continuous spectrum of photon energies.', 'intermediate'),
('education', 'jee/physics', 'modern-physics', 'Unlike a typical metallic conductor, the electrical conductivity of a semiconductor generally:', '["Increases with increasing temperature", "Decreases with increasing temperature", "Remains constant with temperature", "Becomes zero at high temperature"]', 0, 'In semiconductors, rising temperature generates more charge carriers (electron-hole pairs), increasing conductivity -- the opposite trend from metals, where conductivity decreases as temperature rises.', 'intermediate')
ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
