-- ============================================================
-- Quiz coverage for Phase 3 batch 6 (Azure -- Network, K8s, DevOps):
-- cloud/azure-vnets, cloud/azure-aks, cloud/azure-devops.
-- 5 questions per tab, for overview/fundamentals/intermediate/advanced
-- (the four conceptual tabs), matching the pattern used in
-- quiz-questions-azure-identity-compute.sql.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES

-- ---------- cloud/azure-vnets/overview ----------
('cloud', 'azure-vnets', 'overview', 'Can an Azure VNet span multiple Azure regions?', '["Yes, a single VNet can span any number of regions", "No -- a VNet is confined to one region; cross-region connectivity requires VNet Peering or a VPN Gateway between separate VNets", "Only Standard SKU VNets can span regions", "Only if Azure Virtual WAN is enabled"]', 1, 'A VNet spans all availability zones within its region but cannot itself cross a region boundary -- connecting workloads across regions means peering (or VPN/ExpressRoute) between two distinct regional VNets, not one VNet stretched across both.', 'beginner'),
('cloud', 'azure-vnets', 'overview', 'In the hub-spoke architecture pattern, how are spoke VNets typically connected to each other?', '["Spokes are directly peered to every other spoke", "Spokes are peered only to the hub -- traffic between spokes routes through the hub (e.g. through Azure Firewall), not directly spoke-to-spoke", "Spokes communicate only via the public internet", "Spokes share a single VNet and use subnets instead of peering"]', 1, 'This is what makes hub-spoke centrally controllable -- since peering is non-transitive, spokes only connect to the hub, and any spoke-to-spoke traffic is forced through the hub''s shared services (typically a firewall) unless explicitly routed otherwise.', 'intermediate'),
('cloud', 'azure-vnets', 'overview', 'What is the default DNS behavior for resources inside an Azure VNet?', '["Resources must always be configured with a custom DNS server before they can resolve any name", "Azure provides a default DNS service (168.63.129.16) that resolves Azure-internal hostnames automatically, unless custom DNS servers are configured", "VNets have no DNS resolution unless Private DNS Zones are explicitly created", "DNS resolution requires a paid Azure DNS zone regardless of configuration"]', 1, 'Azure-provided DNS works out of the box for Azure-internal name resolution; custom DNS (an on-prem domain controller, a custom forwarder) is only needed when you need resolution behavior Azure''s default DNS doesn''t provide, such as resolving on-prem hostnames.', 'beginner'),
('cloud', 'azure-vnets', 'overview', 'What is the practical difference between a Service Endpoint and a Private Endpoint for accessing a PaaS service like Azure Storage from a VNet?', '["They are two names for the same feature", "A Service Endpoint routes traffic over the Azure backbone but the service keeps its public IP (traffic is VNet-restricted); a Private Endpoint gives the service an actual private IP inside your VNet, removing public exposure entirely", "Private Endpoints are cheaper and should always be used instead of Service Endpoints", "Service Endpoints require a Private DNS Zone; Private Endpoints do not"]', 1, 'Service Endpoints optimize routing and let you restrict a service to specific VNet subnets, but the service itself is still reachable via its public endpoint from elsewhere unless firewalled off. Private Endpoints actually place the service on your private IP space -- Private DNS Zones are required specifically for Private Endpoints to resolve correctly, not the other way around.', 'advanced'),
('cloud', 'azure-vnets', 'overview', 'What connects an on-premises datacenter to Azure over a private, non-internet circuit provided by a connectivity partner?', '["VNet Peering", "ExpressRoute", "NAT Gateway", "Service Endpoint"]', 1, 'ExpressRoute is a dedicated private circuit through a connectivity provider, distinct from a VPN Gateway (which tunnels over the public internet) and from VNet Peering (which connects two Azure VNets to each other, not an on-prem network).', 'beginner'),

-- ---------- cloud/azure-vnets/fundamentals ----------
('cloud', 'azure-vnets', 'fundamentals', 'How many IP addresses does Azure reserve out of every subnet, regardless of subnet size?', '["None -- all addresses in a subnet are usable", "5 -- the network address, default gateway, two for Azure DNS, and the broadcast address", "10, for redundancy purposes", "It depends on the subnet''s NSG configuration"]', 1, 'This is why a /24 subnet (256 addresses) only has 251 usable IPs, and why very small subnets like /29 (8 addresses) are impractical -- 5 are always reserved regardless of how small the subnet is.', 'beginner'),
('cloud', 'azure-vnets', 'fundamentals', 'Once a subnet is created using all of a VNet''s address space, what happens if you try to add a second subnet?', '["Azure automatically shrinks the first subnet to make room", "It fails -- there is no address space left; the first subnet already claims the whole VNet, and subnets cannot be resized down without recreating them", "The second subnet silently overlaps with the first", "VNets automatically expand their address space when a new subnet is requested"]', 1, 'This is why planning subnet sizes before deploying resources into them matters -- a subnet that consumes the entire VNet range leaves no room to carve out additional subnets later without deleting and recreating.', 'beginner'),
('cloud', 'azure-vnets', 'fundamentals', 'What happens if you attempt to create a new subnet with an address range that overlaps an existing subnet in the same VNet?', '["Azure merges the two subnets automatically", "Azure rejects the request with an address-space conflict error -- subnet ranges within a VNet must not overlap", "The newer subnet silently takes priority for any overlapping IPs", "Overlap is only a problem if both subnets have an NSG attached"]', 1, 'Non-overlapping subnet ranges are enforced by the platform -- attempting to create a conflicting range fails outright rather than producing ambiguous routing behavior.', 'intermediate'),
('cloud', 'azure-vnets', 'fundamentals', 'What kind of firewall is an Azure Network Security Group (NSG)?', '["A stateless packet filter that must have explicit rules for both directions of every connection", "A stateful firewall applied at the subnet or NIC level -- return traffic for an already-allowed connection is automatically permitted", "An application-layer (L7) firewall with FQDN filtering", "A DNS-based filtering service"]', 1, 'NSGs are stateful and operate at layer 4 (subnet or NIC level) -- once an inbound connection is allowed, its return traffic doesn''t need a separate outbound rule. This is different from Azure Firewall, which adds L7/FQDN-level filtering on top.', 'intermediate'),
('cloud', 'azure-vnets', 'fundamentals', 'In `az network nsg rule create`, what does the `--priority` value control?', '["The bandwidth allocated to traffic matching that rule", "The order rules are evaluated in -- lower numbers are evaluated first, and the first matching rule wins", "How long the rule stays active before expiring", "Which availability zone the rule applies to"]', 1, 'NSG rule priority ranges from 100-4096; a lower number is evaluated before a higher one, and processing stops at the first match -- this is why rule ordering (not just rule content) matters when designing NSGs.', 'beginner'),

-- ---------- cloud/azure-vnets/intermediate ----------
('cloud', 'azure-vnets', 'intermediate', 'When peering two VNets with `az network vnet peering create`, what is required to establish full bidirectional connectivity?', '["Nothing extra -- one peering command connects both VNets automatically", "A separate peering resource must be created in EACH VNet (one from A to B, and one from B to A)", "Only the VNet with the lower address range needs a peering resource", "Peering requires both VNets to be in the exact same resource group"]', 1, 'VNet Peering is not automatically bidirectional -- creating a peering from VNet A to VNet B only lets A reach B (or vice versa depending on settings); the reverse peering resource must be explicitly created in the other VNet too.', 'intermediate'),
('cloud', 'azure-vnets', 'intermediate', 'What is Azure Firewall, and how does it differ from an NSG?', '["They are functionally identical, just different names", "Azure Firewall is a managed, stateful firewall typically deployed centrally in a hub VNet for L3-L7/FQDN-based filtering; NSGs are simpler, local L4 allow/deny rules at the subnet or NIC level", "NSGs support FQDN filtering, Azure Firewall does not", "Azure Firewall replaces the need for any NSGs in the VNet"]', 1, 'The two are complementary, not interchangeable -- NSGs handle basic segmentation cheaply at the subnet/NIC level, while Azure Firewall centralizes more advanced filtering (FQDN rules, threat intelligence) typically for a hub-spoke topology.', 'intermediate'),
('cloud', 'azure-vnets', 'intermediate', 'In a layered NSG rule set restricting a database tier, why would a rule allow traffic only from the application subnet''s address range rather than allowing traffic from the entire VNet?', '["Allowing the whole VNet range is always faster to configure and has no downside", "Restricting the source to just the app tier''s subnet enforces least-privilege segmentation -- the web tier (and anything else in the VNet) has no direct path to the database", "NSGs cannot filter by subnet, only by individual IP", "The VNet-wide range is reserved and cannot be used in NSG rules"]', 1, 'This is the core idea behind tiered network segmentation -- each tier''s NSG should only allow the minimum traffic it actually needs, so a compromised web-tier VM still can''t reach the database tier directly.', 'intermediate'),
('cloud', 'azure-vnets', 'intermediate', 'What must be true before an Azure Firewall can be deployed into a VNet?', '["The VNet must have a dedicated subnet named exactly AzureFirewallSubnet, sized at least /26", "Azure Firewall can be deployed into any existing subnet without restriction", "The VNet must already have a VPN Gateway deployed", "Azure Firewall only works in VNets using kubenet networking"]', 0, 'Azure Firewall requires its own dedicated subnet with the reserved name AzureFirewallSubnet and a minimum size of /26 -- it cannot share a subnet with other resources.', 'advanced'),
('cloud', 'azure-vnets', 'intermediate', 'What does a Firewall Policy''s rule collection group let you do that individual NSG rules cannot?', '["Filter traffic by fully qualified domain name (FQDN), not just IP/port", "Apply rules retroactively to already-established connections", "Bypass VNet Peering restrictions", "Automatically encrypt all traffic passing through the firewall"]', 0, 'FQDN-based application rules are an Azure Firewall (L7) capability that NSGs, being an L4 filter, don''t provide -- this is one of the main reasons a centralized firewall is layered on top of NSGs in hub-spoke designs.', 'advanced'),

-- ---------- cloud/azure-vnets/advanced ----------
('cloud', 'azure-vnets', 'advanced', 'What is an Application Security Group (ASG) used for in NSG rules?', '["It replaces NSGs entirely with a simpler model", "It lets you reference a logical group of VMs (e.g. web-servers) in an NSG rule instead of hardcoding IP addresses -- membership updates automatically as VMs are added or removed", "It is only used for connecting to on-premises networks", "It is a billing construct with no effect on traffic filtering"]', 1, 'ASGs let NSG rules stay valid as the underlying VM fleet changes -- when a new web-tier VM''s NIC is added to the web-servers ASG, existing rules referencing that ASG automatically apply to it, with no rule rewrite needed.', 'intermediate'),
('cloud', 'azure-vnets', 'advanced', 'Why is VNet Peering described as "non-transitive"?', '["Because peered VNets cannot use the same address space", "Because if VNet A is peered to VNet B, and B is peered to C, A and C are NOT automatically connected -- transitive connectivity has to be explicitly built (e.g. via a hub, or a route)", "Because peering connections expire automatically after 90 days", "Because peering only works within the same Azure subscription"]', 1, 'Non-transitivity is exactly why hub-spoke topologies exist -- without it, you''d need a full mesh of peerings between every VNet that needs to talk to every other one; with a hub, everything just peers to the hub instead.', 'advanced'),
('cloud', 'azure-vnets', 'advanced', 'When checking `az network nic show-effective-nsg` on a VM''s NIC, what does the result reflect if both the subnet and the NIC have an NSG attached?', '["Only the subnet-level NSG is ever enforced", "Only the NIC-level NSG is ever enforced", "Both NSGs are evaluated, and the most restrictive combined result wins", "Whichever NSG was attached most recently takes sole effect"]', 2, 'When both a subnet NSG and a NIC NSG apply to the same traffic, the effective result is the more restrictive combination of the two -- checking effective rules is the reliable way to confirm what''s actually being enforced, rather than reasoning about each NSG in isolation.', 'advanced'),
('cloud', 'azure-vnets', 'advanced', 'What is required, in addition to creating a Private Endpoint, for DNS to correctly resolve a PaaS service''s hostname to its new private IP?', '["Nothing extra -- Private Endpoints automatically update public DNS", "A Private DNS Zone (e.g. privatelink.blob.core.windows.net) must be created and linked to the VNet", "The public DNS record for the service must be manually deleted", "A Service Endpoint must also be enabled on the same subnet"]', 1, 'Without a linked Private DNS Zone, clients inside the VNet would still resolve the service''s hostname to its public IP -- the Private DNS Zone is what redirects that same hostname to the private IP the Private Endpoint created.', 'advanced'),
('cloud', 'azure-vnets', 'advanced', 'What does the "Allow gateway transit" peering option enable?', '["It lets traffic between the two peered VNets bypass NSGs entirely", "It lets the peered VNet use THIS VNet''s VPN/ExpressRoute gateway instead of needing its own", "It automatically encrypts all peered traffic with IPsec", "It allows the peering to span more than two VNets at once"]', 1, 'This is commonly used in hub-spoke: the hub VNet has "allow gateway transit" enabled and owns the VPN/ExpressRoute gateway, while spoke VNets use "use remote gateways" so they don''t each need (and pay for) their own gateway.', 'advanced'),

-- ---------- cloud/azure-aks/overview ----------
('cloud', 'azure-aks', 'overview', 'Who is responsible for the AKS control plane (API server, etcd, scheduler), and what does it cost?', '["The customer manages and pays for it like any VM", "Microsoft manages it, and the base control plane itself has no separate charge -- you only pay for the worker node VMs (and any optional control-plane pricing tier you opt into)", "It is free but entirely self-managed by the customer", "It is billed per kubectl API call made"]', 1, 'This is the core value proposition of AKS versus self-managed Kubernetes -- Microsoft owns etcd backups, API server patching, and scheduler upgrades, and you pay for the node pool VMs actually running your workloads.', 'beginner'),
('cloud', 'azure-aks', 'overview', 'What is the purpose of tainting a System node pool with `CriticalAddonsOnly=true:NoSchedule`?', '["To prevent the system node pool from ever scaling", "To stop application workloads from being scheduled onto the nodes that must stay available for critical system pods like CoreDNS and kube-proxy", "To mark the node pool for deletion", "To disable monitoring on that node pool"]', 1, 'This separation protects cluster stability -- if application pods could land on system nodes and exhaust their resources, critical components like DNS resolution could be starved out, taking down more than just one app.', 'intermediate'),
('cloud', 'azure-aks', 'overview', 'With AKS Workload Identity, how does a pod get access to an Azure resource like Key Vault without storing any secret?', '["The pod embeds a service principal password directly in its container image", "The pod''s Kubernetes ServiceAccount is federated with an Azure managed identity via the cluster''s OIDC issuer -- the pod presents a signed K8s token that Azure AD exchanges for a short-lived Azure token", "AKS automatically grants every pod full subscription access", "Pods authenticate using the node VM''s SSH key"]', 1, 'This federated-credential flow means no long-lived Azure credential is ever stored in Kubernetes -- only a trust relationship between the cluster''s OIDC issuer and the managed identity, plus a signed, short-lived token exchange at runtime.', 'advanced'),
('cloud', 'azure-aks', 'overview', 'What is the main practical difference between Azure CNI and Kubenet networking modes in AKS?', '["Kubenet is always faster because it skips the VNet entirely", "With Azure CNI, pods get real IP addresses from the VNet subnet (directly routable); with Kubenet, pods get IPs from an overlay network (not native VNet IPs), which uses fewer VNet addresses but adds routing complexity", "Azure CNI cannot be used with Windows node pools", "Kubenet supports Azure Network Policy natively; Azure CNI does not"]', 1, 'Azure CNI gives pods first-class VNet identity at the cost of needing more IP address planning up front; Kubenet conserves VNet IP space via an overlay but requires more routing setup and has more feature limitations, which is why Azure CNI (or the newer overlay mode) is generally recommended for production.', 'intermediate'),
('cloud', 'azure-aks', 'overview', 'Why would a GPU node pool typically be created with `--node-count 0` and cluster autoscaler enabled with `--min-count 0`?', '["GPU node pools cannot be created with any initial nodes", "So the (expensive) GPU nodes only spin up when a workload that actually needs them is scheduled, and scale back to zero when idle, avoiding paying for idle GPU capacity", "Because GPU VMs require manual approval before they can run", "Node count 0 is required for the taint to take effect"]', 1, 'GPU-backed VM sizes are typically far more expensive per hour than general-purpose sizes, so starting at zero and letting the autoscaler bring nodes up only when GPU-tainted workloads are actually pending is a common cost-control pattern.', 'intermediate'),

-- ---------- cloud/azure-aks/fundamentals ----------
('cloud', 'azure-aks', 'fundamentals', 'When you run `kubectl` commands against an AKS cluster, what are you actually communicating with?', '["Directly with one of the worker node VMs", "The managed API server, a Microsoft-managed component you never SSH into or manage directly", "The Azure Portal''s backend servers", "A local kubectl-proxy container running on your machine only"]', 1, 'kubectl always talks to the Kubernetes API server, which in AKS is entirely managed by Microsoft -- the API server then decides which node (via the scheduler) any given workload actually runs on, and that decision is invisible to a plain kubectl command.', 'beginner'),
('cloud', 'azure-aks', 'fundamentals', 'What resource group holds an AKS cluster''s actual node VMs, load balancers, and disks?', '["The same resource group you specified with --resource-group when creating the cluster", "A separate, Azure-managed resource group (typically prefixed MC_) that AKS creates automatically, distinct from the resource group holding the AKS resource itself", "No resource group -- node VMs are not tracked as Azure resources", "A resource group named after the Kubernetes namespace"]', 1, 'The MC_ resource group is created and managed by AKS -- directly modifying resources inside it (instead of going through AKS APIs like `az aks nodepool`) is unsupported, since AKS reconciles what it expects to find there.', 'intermediate'),
('cloud', 'azure-aks', 'fundamentals', 'What is the difference between `--enable-managed-identity` and `--enable-workload-identity` when creating an AKS cluster?', '["They are two names for the same flag", "--enable-managed-identity gives the CLUSTER itself an identity to manage Azure resources like load balancers and disks; --enable-workload-identity lets individual PODS get their own Entra ID identity", "--enable-workload-identity is deprecated in favor of --enable-managed-identity", "Both flags configure the same underlying feature at the cluster vs. pod level, so only one is ever needed"]', 1, 'These operate at different levels: the cluster''s managed identity lets AKS itself provision things like load balancers on your behalf, while workload identity (paired with --enable-oidc-issuer) is what lets application pods authenticate to Azure services without stored secrets.', 'intermediate'),
('cloud', 'azure-aks', 'fundamentals', 'In the Azure CNI vs Kubenet comparison, what does "Azure CNI Overlay" offer that plain Kubenet does not?', '["Windows node pool support only", "Pods get overlay IPs like Kubenet (conserving VNet address space) but without requiring User Defined Routes (UDR), and with a feature set closer to standard Azure CNI", "It removes the need for an NSG entirely", "It is only available for private clusters"]', 1, 'Azure CNI Overlay was introduced to combine Kubenet''s IP conservation with fewer of its networking limitations -- notably, no UDR is required on subnets, simplifying the routing setup compared to classic Kubenet.', 'advanced'),
('cloud', 'azure-aks', 'fundamentals', 'When creating a federated credential with `az identity federated-credential create` for Workload Identity, what does the `--subject` value need to match?', '["The Azure subscription ID", "The Kubernetes ServiceAccount''s namespace and name, in the form system:serviceaccount:<namespace>:<sa-name>", "The name of the container image being deployed", "The AKS cluster''s resource ID"]', 1, 'The subject claim is what ties the federated credential to a specific Kubernetes ServiceAccount -- only tokens presented by that exact ServiceAccount (in that exact namespace) will be accepted for the token exchange.', 'advanced'),

-- ---------- cloud/azure-aks/intermediate ----------
('cloud', 'azure-aks', 'intermediate', 'What is KEDA used for in an AKS cluster?', '["Scaling the number of worker nodes based on CPU usage", "Event-driven autoscaling of PODS based on external metrics (e.g. queue length), rather than just CPU/memory", "Replacing the Kubernetes scheduler entirely", "Managing TLS certificates for ingress"]', 1, 'KEDA (Kubernetes Event-Driven Autoscaling) scales pod replicas based on event sources like a message queue''s depth, which the standard Horizontal Pod Autoscaler (CPU/memory-based) can''t do on its own -- it complements, rather than replaces, node-level Cluster Autoscaler.', 'intermediate'),
('cloud', 'azure-aks', 'intermediate', 'What does enabling a private AKS cluster (`--enable-private-cluster`) change about API server access?', '["Nothing -- it only affects node pool networking", "The API server gets a private endpoint reachable only from within the VNet (or peered/connected networks), instead of being reachable over the public internet", "It disables kubectl access entirely, requiring the Azure Portal for all operations", "It automatically enables Azure AD RBAC as a side effect"]', 1, 'A private cluster removes the API server''s public IP entirely -- access has to come from inside the VNet, a peered network, or through a jumpbox/VPN, which is a meaningfully different security posture from the default public (but IP-restrictable) API server endpoint.', 'advanced'),
('cloud', 'azure-aks', 'intermediate', 'What does the Azure Policy add-on for AKS (built on OPA Gatekeeper) provide?', '["Automatic cost optimization recommendations", "Policy-as-code enforcement of cluster configuration rules (e.g. requiring resource limits, blocking privileged containers) at admission time", "Automatic node pool scaling based on policy", "A replacement for Kubernetes RBAC"]', 1, 'The add-on enforces admission-time policies using the OPA Gatekeeper engine -- for example, rejecting a pod spec that requests privileged mode, before it''s ever scheduled, rather than catching the violation after the fact.', 'intermediate'),
('cloud', 'azure-aks', 'intermediate', 'Why might a team choose Application Gateway Ingress Controller (AGIC) over a plain NGINX ingress controller in AKS?', '["AGIC is the only ingress option that supports HTTPS", "AGIC integrates natively with Azure''s Application Gateway, giving WAF (Web Application Firewall) integration and Azure-native L7 load balancing managed as an Azure resource, not just a Kubernetes-internal one", "NGINX ingress cannot route based on hostname", "AGIC is required for any AKS cluster using Azure CNI"]', 1, 'AGIC is specifically valuable when a team wants ingress traffic managed through an actual Azure Application Gateway resource (with its WAF capabilities) rather than a purely in-cluster ingress controller like NGINX.', 'advanced'),
('cloud', 'azure-aks', 'intermediate', 'What does Microsoft Defender for Containers add to an AKS cluster when enabled with `az aks update --enable-defender`?', '["Automatic node autoscaling", "Runtime threat detection and vulnerability assessment for the cluster and its container images", "A built-in ingress controller", "Automatic certificate renewal for ingress TLS"]', 1, 'Defender for Containers is a security monitoring capability -- it is layered on top of, not a replacement for, network controls like NSGs or Azure Policy, and specifically targets runtime threats and image vulnerabilities.', 'intermediate'),

-- ---------- cloud/azure-aks/advanced ----------
('cloud', 'azure-aks', 'advanced', 'In a Spot node pool configuration with `--eviction-policy Delete`, what happens to a node when Azure reclaims the underlying Spot capacity?', '["The node is stopped but its VM is retained for later restart", "The node (and its VM) is deleted -- workloads on it must tolerate eviction and be rescheduled elsewhere", "The eviction is blocked until the workload finishes", "Nothing -- Spot nodes are never evicted once running"]', 1, 'Delete eviction policy actually removes the VM, unlike Deallocate (which stops but keeps the VM for possible restart) -- this is why Spot node pools are appropriate for fault-tolerant, interruptible workloads (batch jobs, CI runners) rather than anything holding long-lived state.', 'advanced'),
('cloud', 'azure-aks', 'advanced', 'What does `--api-server-authorized-ip-ranges` restrict?', '["Which pods can be scheduled on a node", "Which source IP ranges are allowed to reach the AKS API server at all -- requests from outside those ranges are rejected before authentication is even attempted", "Which container registries the cluster can pull images from", "Which Azure regions the cluster can be deployed to"]', 1, 'This is a network-layer restriction on the API server itself, distinct from Kubernetes RBAC (which controls what an authenticated identity can do) -- it''s commonly combined with RBAC as a defense-in-depth measure, not a replacement for it.', 'advanced'),
('cloud', 'azure-aks', 'advanced', 'What is the purpose of Flux (or Argo CD) deployed as a GitOps extension on AKS?', '["To replace the Kubernetes API server", "To continuously reconcile the cluster''s actual state with a Git repository''s declared desired state -- changes are made by committing to Git, not by running kubectl apply directly", "To provide the cluster''s DNS resolution", "To manage node pool scaling exclusively"]', 1, 'GitOps tools like Flux watch a Git repo and apply drift correction automatically -- if someone manually changes a resource with kubectl, Flux will revert it back to match what''s declared in Git, making Git the single source of truth for cluster state.', 'advanced'),
('cloud', 'azure-aks', 'advanced', 'Why enable Azure AD (Entra ID) RBAC on an AKS cluster instead of relying solely on native Kubernetes RBAC with local cluster admin credentials?', '["Azure AD RBAC is required for any cluster larger than 10 nodes", "It lets you manage Kubernetes access using the same Entra ID identities, groups, and Conditional Access policies already used elsewhere in the org, instead of maintaining a separate set of Kubernetes-only credentials", "Native Kubernetes RBAC does not support role bindings", "It automatically encrypts all pod-to-pod traffic"]', 1, 'Centralizing access control through Entra ID means offboarding a user from the organization automatically revokes their cluster access too, and existing Conditional Access policies (like requiring MFA) apply to cluster access as well -- versus a separate local credential that has to be managed independently.', 'advanced'),
('cloud', 'azure-aks', 'advanced', 'When upgrading node pools with `az aks nodepool upgrade --max-surge 1`, what does `--max-surge` control?', '["How many extra nodes are temporarily added during the rolling upgrade, so workloads can be shifted off an old node before it''s taken down", "The maximum number of pods allowed per node during the upgrade", "How many Kubernetes versions can be skipped in a single upgrade", "The number of retries before an upgrade is aborted"]', 0, 'max-surge controls the rolling-upgrade buffer -- with a surge of 1, AKS provisions one extra node, drains an old node onto available capacity (including the surge node), then repeats, keeping the pool at or above its expected capacity throughout the upgrade instead of removing capacity first.', 'advanced'),

-- ---------- cloud/azure-devops/overview ----------
('cloud', 'azure-devops', 'overview', 'What are the five core services that make up Azure DevOps?', '["Repos, Pipelines, Actions, Insights, Registry", "Boards, Repos, Pipelines, Artifacts, Test Plans", "Git, Jenkins, Jira, Artifactory, Selenium", "Portal, CLI, SDK, Marketplace, Extensions"]', 1, 'These five cover planning (Boards), source control (Repos), CI/CD (Pipelines), package management (Artifacts), and test case management (Test Plans) -- the combination is what distinguishes Azure DevOps from a CI/CD-only tool like GitHub Actions.', 'beginner'),
('cloud', 'azure-devops', 'overview', 'In an Azure Pipelines YAML file, what does referencing a variable group (`variables: - group: production-secrets`) do?', '["It creates a new variable group automatically if one doesn''t exist", "It pulls in variables (including secrets, which are masked in logs) that were defined centrally in Library, so they don''t need to be duplicated in every pipeline file", "It disables all other variables defined in the pipeline", "It is only valid for Classic pipelines, not YAML"]', 1, 'Variable groups let secrets and shared config live in one place (optionally backed by Azure Key Vault) and be reused across multiple pipelines, rather than being copy-pasted (and risked being committed) into each pipeline''s YAML.', 'intermediate'),
('cloud', 'azure-devops', 'overview', 'What happens when a secret variable is referenced in a pipeline log, e.g. `echo $(DB_PASSWORD)`?', '["The actual secret value is printed in plaintext", "Azure Pipelines automatically masks the value in the log output, showing *** instead", "The pipeline fails immediately with a security error", "The secret is only masked if explicitly wrapped in a mask() function"]', 1, 'Variables marked as secret (whether from a variable group or created directly) are automatically redacted from log output -- this is a safety net, but it''s still bad practice to intentionally echo a secret, since some redaction can be bypassed by manipulating the output.', 'intermediate'),
('cloud', 'azure-devops', 'overview', 'What is a Service Connection in Azure DevOps used for?', '["Linking two separate Azure DevOps organizations together", "Storing the credentials/permissions Azure Pipelines needs to authenticate to an external service (Azure subscription, Docker registry, Kubernetes cluster, GitHub) so pipeline steps can reference it by name instead of embedding credentials", "Connecting Azure Boards to a specific sprint", "A network-level connection between two Azure VNets"]', 1, 'Service connections centralize where the actual credentials/permissions live -- a pipeline step references the connection by name (e.g. azureSubscription: My-Azure-Subscription), and permissions on who can use that connection can be restricted separately from pipeline authoring access.', 'beginner'),
('cloud', 'azure-devops', 'overview', 'What is the most reliable way to link a Git commit to an Azure Boards work item so it shows up automatically in that work item''s history?', '["Just mention the work item title in the commit message", "Include AB#<work-item-id> in the commit message (e.g. \"Fix login timeout AB#1234\")", "Manually attach the commit hash to the work item afterward through the Portal only", "Work items and commits cannot be linked in Azure DevOps"]', 1, 'The AB# prefix is the reliable, unambiguous syntax for linking a commit to a work item in Azure Boards -- it works consistently across different repo/integration configurations, unlike a bare #1234 which can behave differently depending on setup.', 'intermediate'),

-- ---------- cloud/azure-devops/fundamentals ----------
('cloud', 'azure-devops', 'fundamentals', 'Why might a script that works fine on a developer''s own machine fail when run as a step on a Microsoft-hosted Azure Pipelines agent?', '["Hosted agents cannot run bash scripts, only PowerShell", "The hosted agent is a clean, ephemeral VM reset before each run -- it has none of the tools, caches, or installed dependencies a developer''s own machine has accumulated, unless the pipeline explicitly installs them", "Hosted agents run in a read-only filesystem", "Pipeline scripts are limited to 60 seconds of execution time"]', 1, 'This is a common early-pipeline surprise -- every dependency a script needs (a specific language runtime version, a CLI tool) has to be installed explicitly via a setup task or script step, since nothing carries over between runs on a fresh hosted agent.', 'beginner'),
('cloud', 'azure-devops', 'fundamentals', 'In a `canary` deployment strategy with `increments: [10, 25, 100]`, what does this configuration do?', '["Deploys to 10, then 25, then 100 separate Azure regions", "Rolls the new version out to 10% of traffic/instances, then 25%, then fully to 100%, typically with a chance to validate or halt between increments", "Runs the deployment 3 times for redundancy", "Limits the deployment to a maximum of 100 pods"]', 1, 'Canary increments let a rollout be validated on a small slice of traffic before going further -- if something looks wrong after the 10% increment, the rollout can be halted before affecting all traffic.', 'intermediate'),
('cloud', 'azure-devops', 'fundamentals', 'What are the main categories of Service Connection types available in Azure Pipelines?', '["Only Azure Resource Manager -- all other integrations require a marketplace extension", "Azure Resource Manager (deploy to Azure), Kubernetes (deploy to any cluster), Docker Registry (push/pull images), GitHub (checkout/trigger), and Generic (any REST service)", "Just GitHub and GitLab connections", "Database connections only (SQL Server, PostgreSQL, MySQL)"]', 1, 'These cover the common categories of external systems a pipeline needs to authenticate to -- each connection type stores the appropriate credential/permission model for that kind of target, created under Project Settings -> Service Connections.', 'beginner'),
('cloud', 'azure-devops', 'fundamentals', 'What does the `pr:` trigger section in azure-pipelines.yml control?', '["Which branches can be merged without review", "Which branches, when a pull request targets them, cause this pipeline to run automatically as a validation build", "The number of required reviewers on a pull request", "Whether pull requests are enabled for the repository at all"]', 1, 'The pr: trigger is what makes a pipeline run as a PR validation check -- combined with a branch policy requiring that build to succeed, it becomes a real merge gate rather than just informational.', 'intermediate'),
('cloud', 'azure-devops', 'fundamentals', 'Why does a job that needs Node.js typically include a `NodeTool@0` task before running `npm` commands?', '["NodeTool@0 is required to enable YAML pipeline syntax", "Because the hosted agent image may not have the exact Node.js version needed pre-installed (or may have a different default), so the task explicitly installs/selects the required version", "npm cannot run inside a pipeline without this task", "NodeTool@0 is what triggers the pipeline to run"]', 1, 'Pinning the runtime version explicitly with a setup task avoids relying on whatever version happens to be the hosted image''s current default, which can change between image updates.', 'beginner'),

-- ---------- cloud/azure-devops/intermediate ----------
('cloud', 'azure-devops', 'intermediate', 'In a multi-stage pipeline, what does `dependsOn: Build` on the `DeployStaging` stage guarantee?', '["DeployStaging will run in parallel with Build for speed", "DeployStaging will only start after the Build stage has completed (and, combined with a condition, typically only if it succeeded)", "DeployStaging inherits all variables defined in Build automatically with no extra configuration", "Build will be skipped if DeployStaging is disabled"]', 1, 'Stage dependencies control execution order across stages -- without dependsOn, stages would run in parallel by default, which is rarely what you want for a build-then-deploy pipeline.', 'intermediate'),
('cloud', 'azure-devops', 'intermediate', 'What does `condition: and(succeeded(), eq(variables[''Build.SourceBranch''], ''refs/heads/main''))` on a deploy stage achieve?', '["It deploys on every branch as long as the previous stage succeeded", "It only runs the stage if the previous stage succeeded AND the pipeline is running against the main branch specifically -- preventing feature-branch builds from deploying to production", "It requires manual approval regardless of branch", "It is a syntax error; conditions cannot combine two functions"]', 1, 'This is a common production-safety pattern -- production deploy stages are gated not just on prior success but on being triggered from the correct branch, so a build from a feature branch can''t accidentally trigger a production deployment.', 'intermediate'),
('cloud', 'azure-devops', 'intermediate', 'What is the purpose of creating a work item via the Azure DevOps REST API (`_apis/wit/workitems/$Bug`) from within a pipeline, as opposed to just checking pipeline status manually?', '["It is the only way to view pipeline logs", "It automates ticket creation -- for example, automatically filing a Bug work item when a pipeline fails, with details like the failing build already attached", "It is required for the pipeline to run at all", "REST API calls are needed to trigger any pipeline stage"]', 1, 'Automating work item creation on failure closes the loop between CI/CD and the team''s tracking system -- a failure doesn''t just show red in the pipeline UI, it becomes a trackable, assignable work item automatically.', 'advanced'),
('cloud', 'azure-devops', 'intermediate', 'What does the `HelmDeploy@0` task''s `overrideValues` input do in a Helm-based Kubernetes deployment step?', '["It replaces the entire Helm chart with a different one", "It overrides specific values from the chart''s values file at deploy time (e.g. setting image.tag to the current build ID) without editing the chart itself", "It disables Helm''s built-in values validation", "It is required only when deploying to a canary environment"]', 1, 'This is how a pipeline injects build-specific values (like the image tag just built) into a Helm release at deploy time, keeping the chart itself generic and reusable across environments and builds.', 'intermediate'),
('cloud', 'azure-devops', 'intermediate', 'Why would a `SecurityScan` job and a `Test` job both be listed as dependencies of a `BuildImage` job (`dependsOn: [Test, SecurityScan]`)?', '["To force Test and SecurityScan to run sequentially, one after another", "To let Test and SecurityScan run in parallel (since jobs within a stage without dependencies on each other run concurrently by default) while still ensuring BuildImage only starts after BOTH have finished", "Because Azure Pipelines requires at least two dependencies per job", "To automatically merge their test results into one report"]', 1, 'Listing multiple jobs in dependsOn is what lets independent checks (tests, security scanning) run in parallel for speed, while still gating the next step (building the image) on all of them succeeding -- a common pipeline optimization.', 'advanced'),

-- ---------- cloud/azure-devops/advanced ----------
('cloud', 'azure-devops', 'advanced', 'What is the benefit of extracting a deployment step into a reusable pipeline template (`templates/deploy-to-aks.yml`) referenced from multiple application pipelines?', '["Templates run faster than inline steps", "A change to the shared deployment pattern (e.g. adding a new smoke test) can be made once in the template and automatically applies to every pipeline that consumes it, instead of editing each pipeline individually", "Templates are required for canary deployments to function", "Templates remove the need for service connections"]', 1, 'This is the pipeline-as-code equivalent of a shared library or reusable module -- centralizing common logic means consistency across services and one place to fix or improve the deployment pattern.', 'advanced'),
('cloud', 'azure-devops', 'advanced', 'What does linking a Variable Group to Azure Key Vault accomplish that a plain (non-linked) Variable Group does not?', '["It makes the variables available to Classic pipelines only", "Secret values are pulled live from Key Vault at pipeline run time rather than being stored as pipeline-managed secrets, so rotating a secret in Key Vault updates every pipeline that uses it without editing the pipeline itself", "It automatically encrypts all pipeline logs", "It removes the need for a service connection to Azure"]', 1, 'This keeps Key Vault as the single source of truth for the secret''s current value -- a pipeline referencing the linked variable group always gets the latest value on each run, instead of a stale copy that has to be manually kept in sync.', 'advanced'),
('cloud', 'azure-devops', 'advanced', 'Why does the guidance recommend restricting which pipelines can use a given Service Connection (Project Settings -> Pipelines -> Service Connections -> pipeline permissions)?', '["Because Azure limits each subscription to a fixed number of active connections", "Because a Service Connection often carries real production access -- restricting which pipelines can use it limits the blast radius if a less-trusted or lower-environment pipeline is compromised or misconfigured", "Because unrestricted connections are automatically deleted after 30 days", "Restricting pipelines is required before a connection can be used in YAML at all"]', 1, 'A Service Connection with production-level Azure permissions being usable by any pipeline in the project (including ones written by less-trusted contributors) is a real privilege-escalation risk -- explicitly scoping which pipelines can reference it is a standard least-privilege control.', 'advanced'),
('cloud', 'azure-devops', 'advanced', 'What is the recommended identity type for a Service Connection authenticating Azure Pipelines to an Azure subscription, and why?', '["A service principal with a long-lived stored password, because it is simplest to configure", "A managed identity where possible, because Azure handles the underlying credential''s lifecycle, removing the need to manually rotate a stored secret", "A personal user account, so pipeline actions are attributed to a specific person", "Basic authentication with a shared username and password"]', 1, 'This mirrors the same Managed Identity-over-stored-credentials principle used elsewhere in Azure -- a leaked or forgotten long-lived service principal secret is a real, recurring source of security incidents that managed identity avoids entirely.', 'advanced'),
('cloud', 'azure-devops', 'advanced', 'What does `RunAsPreJob: true` on the `AzureKeyVault@2` task achieve?', '["It deletes the secrets from Key Vault after the job completes", "It fetches the specified secrets from Key Vault BEFORE the rest of the job''s steps run, making them available as pipeline variables for the whole job rather than only after this task''s own step", "It runs the task only on pre-production environments", "It requires the job to be manually approved before execution"]', 1, 'Running as a pre-job step means the secrets are already loaded as variables by the time any other step in the job executes, rather than only becoming available partway through -- useful when an early step in the same job also needs the secret value.', 'advanced')

ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
