-- ============================================================
-- /learn quiz: CBSE Class 10 Science -- batch 2 (Biology): Life
-- Processes, Control and Coordination, How Do Organisms Reproduce,
-- Heredity and Evolution, Our Environment. 5 more of the subject's 14
-- chapters, continuing from batch 1 (Chemistry).
--
-- SOURCING: same disclosed limitation as batch 1 -- authored to match
-- real CBSE Section-A exam style/difficulty, NOT copied from any
-- official CBSE question paper. Every factual claim independently
-- checked against standard NCERT Class 10 Science content.
--
-- Applied via @supabase/supabase-js, upsert(rows, { onConflict:
-- "academy_slug,technology_slug,section_slug,question", ignoreDuplicates:
-- true }) -- functionally identical to this file's ON CONFLICT clause.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES
('education', 'class-10/science', 'life-processes', 'The process by which green plants synthesize their own food using sunlight is called:', '["Photosynthesis", "Respiration", "Transpiration", "Excretion"]', 0, 'Photosynthesis is the process by which green plants convert carbon dioxide and water into glucose and oxygen using light energy.', 'beginner'),
('education', 'class-10/science', 'life-processes', 'In the human respiratory system, gas exchange between air and blood occurs in the:', '["Alveoli", "Trachea", "Bronchi", "Larynx"]', 0, 'The alveoli are tiny, thin-walled air sacs in the lungs where oxygen and carbon dioxide are exchanged with the blood.', 'beginner'),
('education', 'class-10/science', 'life-processes', 'Green plants that prepare their own food through photosynthesis exhibit which mode of nutrition?', '["Autotrophic nutrition", "Heterotrophic nutrition", "Saprophytic nutrition", "Parasitic nutrition"]', 0, 'Autotrophic organisms, like green plants, synthesize their own food from simple inorganic substances, unlike heterotrophs which depend on other organisms.', 'beginner'),
('education', 'class-10/science', 'life-processes', 'The organ primarily responsible for pumping blood throughout the human body is the:', '["Heart", "Liver", "Kidney", "Lungs"]', 0, 'The heart is a muscular pumping organ that circulates blood through the body via the circulatory system.', 'beginner'),
('education', 'class-10/science', 'life-processes', 'The basic structural and functional unit of excretion in the human kidney is the:', '["Nephron", "Neuron", "Alveolus", "Villus"]', 0, 'The nephron is the functional unit of the kidney, responsible for filtering blood and forming urine.', 'beginner'),
('education', 'class-10/science', 'control-coordination', 'The basic structural and functional unit of the nervous system is the:', '["Neuron", "Nephron", "Axon only", "Synapse"]', 0, 'The neuron (nerve cell) is the fundamental unit that transmits electrical and chemical signals throughout the nervous system.', 'beginner'),
('education', 'class-10/science', 'control-coordination', 'The small gap between two neurons across which nerve impulses pass is called a:', '["Synapse", "Dendrite", "Axon", "Node of Ranvier"]', 0, 'The synapse is the junction between two neurons where nerve impulses are transmitted, typically via chemical neurotransmitters.', 'beginner'),
('education', 'class-10/science', 'control-coordination', 'The hormone that regulates blood sugar levels in the human body is:', '["Insulin", "Adrenaline", "Thyroxine", "Testosterone"]', 0, 'Insulin, secreted by the pancreas, regulates blood glucose levels by promoting its uptake and storage.', 'beginner'),
('education', 'class-10/science', 'control-coordination', 'A quick, involuntary response to a stimulus, such as withdrawing a hand from a hot object, is primarily controlled by the:', '["Spinal cord (via a reflex arc)", "Cerebrum", "Cerebellum", "Pituitary gland"]', 0, 'Reflex actions are processed rapidly through the spinal cord via a reflex arc, bypassing the slower conscious processing of the brain.', 'intermediate'),
('education', 'class-10/science', 'control-coordination', 'The plant hormone primarily responsible for growth of a shoot toward light (phototropism) is:', '["Auxin", "Gibberellin", "Cytokinin", "Abscisic acid"]', 0, 'Auxin accumulates on the shaded side of a shoot, promoting faster cell elongation there and causing the shoot to bend toward light.', 'intermediate'),
('education', 'class-10/science', 'reproduction', 'Amoeba, a single-celled organism, typically reproduces asexually by:', '["Binary fission", "Budding", "Fragmentation", "Spore formation"]', 0, 'Amoeba reproduces by binary fission, where the parent cell divides into two roughly equal daughter cells.', 'beginner'),
('education', 'class-10/science', 'reproduction', 'In the human male reproductive system, sperm are produced in the:', '["Testes", "Prostate gland", "Vas deferens", "Urethra"]', 0, 'The testes are the primary male reproductive organs responsible for producing sperm and testosterone.', 'beginner'),
('education', 'class-10/science', 'reproduction', 'The female gamete in humans is called the:', '["Ovum", "Zygote", "Embryo", "Follicle"]', 0, 'The ovum (egg cell) is the female gamete, produced by the ovaries.', 'beginner'),
('education', 'class-10/science', 'reproduction', 'The fusion of a male gamete and a female gamete to form a zygote is called:', '["Fertilization", "Pollination", "Germination", "Implantation"]', 0, 'Fertilization is the process by which a sperm and an egg cell fuse to form a zygote, the first cell of a new organism.', 'beginner'),
('education', 'class-10/science', 'reproduction', 'In flowering plants, the transfer of pollen grains from the anther to the stigma is called:', '["Pollination", "Fertilization", "Germination", "Respiration"]', 0, 'Pollination is the transfer of pollen from the anther (male part) to the stigma (female part), a necessary step before fertilization can occur.', 'beginner'),
('education', 'class-10/science', 'heredity-evolution', 'Gregor Mendel conducted his classic hereditary experiments primarily on:', '["Pea plants", "Fruit flies", "Mice", "Maize plants"]', 0, 'Mendel''s foundational experiments on inheritance were carried out on garden pea plants (Pisum sativum).', 'beginner'),
('education', 'class-10/science', 'heredity-evolution', 'In a cross between two contrasting pure-bred traits, the trait that appears in the F1 (first filial) generation is called the:', '["Dominant trait", "Recessive trait", "Hybrid trait", "Mutant trait"]', 0, 'The trait that is expressed in the F1 generation, masking the other trait, is termed dominant in Mendelian genetics.', 'beginner'),
('education', 'class-10/science', 'heredity-evolution', 'In humans, the sex of a child is primarily determined by which chromosome contributed by the father:', '["X or Y chromosome", "Only the X chromosome", "Only the Y chromosome", "An autosome, not a sex chromosome"]', 0, 'The mother always contributes an X chromosome; the father contributes either an X (resulting in a female, XX) or a Y (resulting in a male, XY), so the father''s contribution determines the child''s sex.', 'intermediate'),
('education', 'class-10/science', 'heredity-evolution', 'Organs that have a similar basic structure due to common ancestry but may serve different functions are called:', '["Homologous organs", "Analogous organs", "Vestigial organs", "Fossil organs"]', 0, 'Homologous organs share a common evolutionary origin and basic structural plan (e.g. forelimbs of humans, bats, and whales), even when their functions differ.', 'intermediate'),
('education', 'class-10/science', 'heredity-evolution', 'Charles Darwin''s theory of evolution is primarily based on the mechanism of:', '["Natural selection", "Use and disuse of organs", "Inheritance of acquired characteristics", "Divine creation"]', 0, 'Darwin proposed natural selection -- the differential survival and reproduction of individuals with favourable variations -- as the primary mechanism driving evolution.', 'beginner'),
('education', 'class-10/science', 'environment', 'In a food chain, green plants occupy which trophic level, since they produce their own food?', '["Producers (first trophic level)", "Primary consumers", "Secondary consumers", "Decomposers"]', 0, 'Green plants, as autotrophs that produce food via photosynthesis, form the producer or first trophic level of any food chain.', 'beginner'),
('education', 'class-10/science', 'environment', 'The ozone layer in the atmosphere primarily protects living organisms on Earth from:', '["Harmful ultraviolet (UV) radiation", "Excess carbon dioxide", "Acid rain directly", "Global warming directly"]', 0, 'The ozone layer absorbs most of the sun''s harmful ultraviolet radiation, preventing it from reaching the Earth''s surface.', 'beginner'),
('education', 'class-10/science', 'environment', 'Which of the following is an example of non-biodegradable waste?', '["Plastic", "Vegetable peels", "Paper", "Cotton cloth"]', 0, 'Plastic is not broken down by natural biological processes and persists in the environment for a very long time, making it non-biodegradable.', 'beginner'),
('education', 'class-10/science', 'environment', 'A sequence of organisms in which each organism feeds on the one before it, transferring energy along the sequence, is called a:', '["Food chain", "Food web", "Trophic pyramid", "Ecosystem"]', 0, 'A food chain is a linear sequence showing the transfer of food energy from one organism to the next.', 'beginner'),
('education', 'class-10/science', 'environment', 'A network formed by several interconnected food chains within an ecosystem is called a:', '["Food web", "Food chain", "Trophic level", "Biomagnification chain"]', 0, 'A food web represents the complex, interconnected feeding relationships among multiple food chains within an ecosystem.', 'beginner')
ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
