-- ============================================================
-- /learn quiz: CBSE Class 10 Social Science -- all 6 chapters: The
-- Rise of Nationalism in Europe, Nationalism in India, Resources and
-- Development, Power Sharing, Development, Money and Credit. Same new
-- scope as English (no pyqYears badge here either), differentiated by
-- content type: history factual-recall (dates/movements/figures),
-- geography/civics conceptual (classification, case studies), and
-- economics conceptual+light-numeric.
--
-- SOURCING: authored to match real CBSE Section-A exam style; NOT
-- copied from any official question paper. Every historical date,
-- figure, and conceptual claim below was independently checked
-- against standard NCERT Class 10 Social Science content before
-- writing.
--
-- Applied via @supabase/supabase-js, upsert(rows, { onConflict:
-- "academy_slug,technology_slug,section_slug,question", ignoreDuplicates:
-- true }) -- functionally identical to this file's ON CONFLICT clause.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES
('education', 'class-10/social', 'rise-of-nationalism', 'The idea of nationalism first emerged clearly in Europe in association with which major event?', '["The French Revolution", "The Industrial Revolution", "World War I", "The Russian Revolution"]', 0, 'The French Revolution (1789) introduced concepts like the nation, citizenship, and collective political identity that became central to European nationalism.', 'beginner'),
('education', 'class-10/social', 'rise-of-nationalism', 'The concept of a centralized power exercising sovereign control over a clearly defined territory, central to 19th-century Europe, is called a:', '["Nation-state", "Empire", "City-state", "Colony"]', 0, 'The nation-state -- a single, sovereign political unit for a people sharing a common identity -- became the dominant political ideal in 19th-century Europe.', 'beginner'),
('education', 'class-10/social', 'rise-of-nationalism', 'The Congress of Vienna (1815) was convened primarily to:', '["Restore conservative monarchies after Napoleon''s defeat", "Establish the League of Nations", "End the First World War", "Unify Germany"]', 0, 'The Congress of Vienna, led by conservative powers, aimed to restore Europe''s pre-Napoleonic monarchical order and suppress revolutionary/nationalist movements.', 'intermediate'),
('education', 'class-10/social', 'rise-of-nationalism', 'Giuseppe Mazzini, an important figure in Italian unification, is best known for founding which organization?', '["Young Italy", "Young Europe only", "The Carbonari exclusively", "The Zollverein"]', 0, 'Mazzini founded Young Italy, a secret society dedicated to promoting Italian unification as a democratic republic.', 'intermediate'),
('education', 'class-10/social', 'rise-of-nationalism', 'The Zollverein, formed in 1834, was a:', '["Customs union among German states", "Military alliance against France", "Parliament of unified Italy", "Trade agreement between Britain and France"]', 0, 'The Zollverein was a customs union that abolished tariff barriers between German states, an important economic step toward eventual political unification.', 'intermediate'),
('education', 'class-10/social', 'nationalism-india', 'The Non-Cooperation Movement was launched by Mahatma Gandhi in which year?', '["1920", "1930", "1942", "1919"]', 0, 'Gandhi launched the Non-Cooperation Movement in 1920, calling on Indians to withdraw cooperation from British institutions.', 'beginner'),
('education', 'class-10/social', 'nationalism-india', 'The Non-Cooperation Movement was withdrawn following which incident?', '["The Chauri Chaura incident", "The Jallianwala Bagh massacre", "The Salt March", "The Quit India Movement"]', 0, 'Gandhi called off the Non-Cooperation Movement after violence broke out at Chauri Chaura in 1922, where a mob killed policemen.', 'intermediate'),
('education', 'class-10/social', 'nationalism-india', 'The Salt March (Dandi March) began in which year?', '["1930", "1920", "1942", "1935"]', 0, 'Gandhi began the Salt March from Sabarmati Ashram to Dandi in 1930, launching the Civil Disobedience Movement.', 'beginner'),
('education', 'class-10/social', 'nationalism-india', 'The Quit India Movement was launched in which year?', '["1942", "1930", "1920", "1947"]', 0, 'The Quit India Movement, demanding an immediate end to British rule, was launched by Gandhi in August 1942.', 'beginner'),
('education', 'class-10/social', 'nationalism-india', 'The Jallianwala Bagh massacre, a major turning point that fueled Indian nationalist sentiment, took place in which city?', '["Amritsar", "Delhi", "Lahore", "Ahmedabad"]', 0, 'The Jallianwala Bagh massacre occurred in Amritsar in 1919, when British troops fired on an unarmed gathering.', 'beginner'),
('education', 'class-10/social', 'resources-development', 'Resources that can be renewed or replenished by natural processes are called:', '["Renewable resources", "Non-renewable resources", "Abiotic resources", "Human-made resources"]', 0, 'Renewable resources, such as solar energy, wind, and forests, can regenerate naturally within a relatively short time span.', 'beginner'),
('education', 'class-10/social', 'resources-development', 'Which soil type is most extensively found in the Deccan Plateau, formed from volcanic (lava) activity?', '["Black soil", "Alluvial soil", "Red soil", "Laterite soil"]', 0, 'Black soil (regur soil), ideal for cotton cultivation, covers much of the Deccan Plateau, having formed from the solidification of volcanic lava.', 'beginner'),
('education', 'class-10/social', 'resources-development', 'Alluvial soil, the most fertile soil type in India, is primarily deposited by:', '["Rivers", "Wind", "Glaciers", "Volcanic activity"]', 0, 'Alluvial soil is deposited by rivers, particularly in the northern plains, making it highly fertile for agriculture.', 'beginner'),
('education', 'class-10/social', 'resources-development', 'Land degradation caused by the removal of topsoil due to water or wind action is called:', '["Soil erosion", "Soil salinity", "Waterlogging", "Desertification only"]', 0, 'Soil erosion is the wearing away and removal of the fertile top layer of soil by natural agents like water and wind.', 'beginner'),
('education', 'class-10/social', 'resources-development', 'Contour ploughing, a method used to conserve soil on sloped land, primarily helps by:', '["Slowing down water flow down a slope, reducing erosion", "Increasing soil salinity", "Adding chemical fertilizers", "Removing vegetation cover"]', 0, 'Ploughing along the natural contours of a slope (rather than up and down it) slows surface water runoff, reducing the soil erosion it would otherwise cause.', 'intermediate'),
('education', 'class-10/social', 'power-sharing', 'In Belgium, the power-sharing arrangement was designed to accommodate differences primarily between which two major linguistic communities?', '["Dutch-speaking and French-speaking communities", "Catholic and Protestant communities", "Northern and Southern regions only", "Urban and rural populations"]', 0, 'Belgium''s constitutional power-sharing arrangement addresses tensions between the majority Dutch-speaking Flemish community and the French-speaking Walloon community.', 'beginner'),
('education', 'class-10/social', 'power-sharing', 'In Sri Lanka, the failure to share power fairly between the majority Sinhala and minority Tamil communities led to:', '["A prolonged civil war", "Immediate reunification", "Peaceful power-sharing", "An economic boom"]', 0, 'Majoritarian policies favoring the Sinhala community alienated the Tamil minority, contributing to a prolonged and devastating civil war.', 'beginner'),
('education', 'class-10/social', 'power-sharing', 'Power sharing among different levels of government, such as the central and state governments, is known as:', '["Vertical power sharing", "Horizontal power sharing", "Community power sharing", "Coalition power sharing"]', 0, 'Vertical power sharing, seen in federal systems, distributes authority across different levels of government (central, state, local).', 'intermediate'),
('education', 'class-10/social', 'power-sharing', 'Power sharing among different organs of government at the same level -- executive, legislature, and judiciary -- is known as:', '["Horizontal power sharing", "Vertical power sharing", "Federal power sharing", "Community government"]', 0, 'Horizontal power sharing distributes authority among coequal institutions at the same level, checking and balancing one another.', 'intermediate'),
('education', 'class-10/social', 'power-sharing', 'A key argument in favour of power sharing is that it:', '["Reduces conflict between social groups and promotes stability", "Concentrates authority in a single leader", "Eliminates the need for elections", "Weakens democratic accountability"]', 0, 'By distributing authority among different groups and institutions, power sharing reduces the likelihood of conflict and strengthens the stability of a political system.', 'beginner'),
('education', 'class-10/social', 'development', 'The Human Development Index (HDI), used to compare development across countries, is based on indicators including income, education, and:', '["Health (life expectancy)", "Military strength", "Land area", "Population size alone"]', 0, 'HDI combines income, educational attainment, and health (measured via life expectancy) into a single composite measure of development.', 'beginner'),
('education', 'class-10/social', 'development', 'Per capita income is calculated by dividing a country''s total income by its:', '["Total population", "Total land area", "Number of workers only", "Number of households"]', 0, 'Per capita income is the average income per person, found by dividing total national income by the total population.', 'beginner'),
('education', 'class-10/social', 'development', 'Which organization publishes the annual Human Development Report ranking countries by HDI?', '["United Nations Development Programme (UNDP)", "World Trade Organization (WTO)", "International Monetary Fund (IMF)", "World Health Organization (WHO)"]', 0, 'The UNDP publishes the annual Human Development Report, which ranks and compares countries using the HDI.', 'beginner'),
('education', 'class-10/social', 'development', 'Using only per capita income to measure a country''s development has a key limitation because it:', '["Does not show how income is distributed among people", "Is too difficult to calculate", "Ignores a country''s total population", "Cannot be compared across countries"]', 0, 'Per capita income is an average and hides inequality -- a country could have a high average income while most of its wealth is concentrated among a few.', 'intermediate'),
('education', 'class-10/social', 'development', 'Sustainable development primarily emphasizes meeting present needs without:', '["Compromising future generations'' ability to meet their needs", "Increasing current economic growth", "Using any natural resources", "Involving government policy"]', 0, 'Sustainable development balances present needs against preserving resources and opportunities for future generations.', 'beginner'),
('education', 'class-10/social', 'money-credit', 'The system of exchanging goods directly for other goods, without using money, is called:', '["Barter system", "Credit system", "Currency system", "Banking system"]', 0, 'The barter system involves the direct exchange of goods and services, without any medium of exchange like money.', 'beginner'),
('education', 'class-10/social', 'money-credit', 'The central bank of India, which regulates the banking system and controls the money supply, is the:', '["Reserve Bank of India (RBI)", "State Bank of India (SBI)", "NABARD", "SEBI"]', 0, 'The RBI is India''s central bank, responsible for regulating banks, controlling money supply, and overseeing monetary policy.', 'beginner'),
('education', 'class-10/social', 'money-credit', 'Formal sources of credit include banks and cooperative societies, while informal sources include:', '["Moneylenders, traders, and relatives", "Only commercial banks", "Only government schemes", "Only large corporations"]', 0, 'Informal credit sources -- moneylenders, traders, employers, and relatives -- operate outside the regulatory oversight that governs formal banks and cooperatives.', 'beginner'),
('education', 'class-10/social', 'money-credit', 'Self Help Groups (SHGs) primarily help their members by:', '["Pooling savings to provide small loans to members", "Providing free money with no repayment", "Replacing the banking system entirely", "Only offering insurance products"]', 0, 'SHGs pool the small savings of their members, using the collective fund to provide small loans on reasonable terms without requiring collateral.', 'intermediate'),
('education', 'class-10/social', 'money-credit', 'A key disadvantage of borrowing from informal credit sources, such as moneylenders, is:', '["Higher interest rates and greater risk of exploitation", "Lower interest rates than banks", "A strict collateral requirement only", "A guaranteed government subsidy"]', 0, 'Informal lenders often charge much higher interest rates than formal institutions and are less regulated, increasing the risk of exploitative lending terms.', 'intermediate')
ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
