-- ============================================================
-- Quiz coverage for cloud/aws (overview, fundamentals,
-- intermediate) and cloud/aws-iam + cloud/aws-ec2 (overview,
-- fundamentals, intermediate, advanced -- all four tabs exist
-- and carry substantive live content for both technologies).
-- Phase 3 (Cloud academy), batch 1: AWS Identity & Compute.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES

-- ---------- cloud/aws/overview ----------
('cloud', 'aws', 'overview', 'Under the AWS Shared Responsibility Model, who is responsible for patching the guest operating system on an EC2 instance you launched?', '["AWS is always responsible for everything", "You are -- AWS secures the underlying cloud infrastructure (hardware, hypervisor, physical facilities); you are responsible for what you put IN the cloud, including the guest OS, application, and data", "Neither party is responsible -- patching is optional", "Only AWS Premium Support customers get OS patching from AWS"]', 1, 'The dividing line moves depending on the service -- for a fully managed service like RDS or Lambda, AWS takes on more of the stack -- but for a raw EC2 instance, the guest OS and everything on it is the customer''s responsibility.', 'beginner'),
('cloud', 'aws', 'overview', 'Why is deploying an application across at least 2 Availability Zones considered the production baseline on AWS, not an optional upgrade?', '["Multi-AZ is only needed for compliance paperwork, not actual resilience", "Each AZ is a physically separate facility with independent power and cooling -- a single-AZ deployment shares one failure domain, so an AZ-level event takes down everything in it regardless of how many redundant instances are running within that one zone", "AWS charges extra for single-AZ deployments to discourage them", "AZs within a region share the same physical power source, so multi-AZ has no real resilience benefit"]', 1, 'Redundancy within one AZ doesn''t protect against an AZ-level failure (power, fire, networking) -- only spreading across AZs does, which is why it''s treated as the actual minimum bar for production rather than a nice-to-have.', 'beginner'),
('cloud', 'aws', 'overview', 'What does IRSA (IAM Roles for Service Accounts) let an EKS pod do?', '["Assume a specific IAM role directly, scoped to that pod''s Kubernetes ServiceAccount, without any AWS access keys stored in the cluster", "Give every pod in the cluster full administrator access automatically", "Replace Kubernetes RBAC entirely", "Only works for pods running as root"]', 0, 'IRSA federates a Kubernetes-native identity (the ServiceAccount) directly to AWS IAM via OIDC -- the pod gets temporary AWS credentials with no long-lived key ever stored as a Kubernetes Secret.', 'intermediate'),
('cloud', 'aws', 'overview', 'What is the purpose of a Service Control Policy (SCP) in AWS Organizations?', '["To grant additional permissions to specific IAM users", "To set the maximum permissions an entire AWS account (or group of accounts) can have -- even that account''s own root user cannot exceed an SCP''s boundary", "To replace IAM policies entirely within an account", "SCPs only apply to S3 buckets"]', 1, 'SCPs are an outer guardrail at the organization level, not a grant of permission -- an account still needs IAM policies inside it to actually allow anything; the SCP just caps what those policies are ever allowed to permit.', 'intermediate'),
('cloud', 'aws', 'overview', 'Why should applications use IAM Roles rather than an IAM User''s long-term access keys?', '["Roles are always free while User access keys cost money", "A Role issues short-lived, temporary credentials that expire on their own within hours if leaked; a User''s access key is a long-lived static secret that remains valid indefinitely until someone manually notices and revokes it", "Roles can only be used by AWS support staff", "There is no real difference -- it is purely a naming convention"]', 1, 'This is the core reason applications/services should default to Roles: the blast radius of a leaked Role credential is bounded by its short expiry, while a leaked User access key stays dangerous until someone actively catches and rotates it.', 'beginner'),

-- ---------- cloud/aws/fundamentals ----------
('cloud', 'aws', 'fundamentals', 'In AWS IAM policy evaluation, what happens if one attached policy has an explicit Allow for an action and a different attached policy has an explicit Deny for that same action?', '["The Allow wins because it was evaluated first", "The Deny always wins -- an explicit Deny in any applicable policy overrides an Allow from any other policy", "AWS picks whichever policy was created most recently", "The request is queued for manual review"]', 1, 'This is the single most important rule in IAM policy evaluation: by default everything is denied, an explicit Allow grants access, but an explicit Deny anywhere always overrides any Allow, no matter where that Allow came from.', 'intermediate'),
('cloud', 'aws', 'fundamentals', 'What does a NAT Gateway let resources in a private subnet do?', '["Accept inbound connections directly from the internet", "Initiate outbound connections to the internet (e.g. downloading OS updates) without being directly reachable FROM the internet", "Replace the need for a Security Group", "Route traffic between two VPCs"]', 1, 'A NAT Gateway sits in a public subnet and lets private-subnet resources reach out (e.g. to pull package updates) while remaining unreachable from the outside -- the traffic is one-directional in terms of who can initiate it.', 'intermediate'),
('cloud', 'aws', 'fundamentals', 'What is the main tradeoff of using EC2 Spot Instances instead of On-Demand?', '["Spot Instances are slower CPUs", "Spot Instances can be significantly cheaper than On-Demand, but AWS can reclaim (interrupt) them with only about a 2-minute notice, making them suited to stateless or fault-tolerant workloads rather than anything that can''t tolerate sudden termination", "Spot Instances cannot run Linux", "Spot Instances have no networking access"]', 1, 'The cost savings come with a real constraint: a Spot Instance is not guaranteed to keep running, so workloads placed on Spot need to be able to checkpoint, restart elsewhere, or otherwise tolerate abrupt termination.', 'beginner'),
('cloud', 'aws', 'fundamentals', 'What is the key access-model difference between S3, EBS, and EFS?', '["They are three names for the same underlying service", "S3 is object storage accessed via an HTTP API (not a filesystem); EBS is block storage attached to one EC2 instance at a time; EFS is a network file system that multiple instances can mount and access simultaneously", "EBS can be accessed by unlimited instances at once, S3 cannot", "EFS is only for Windows instances"]', 1, 'Choosing between them depends on the access pattern needed: EBS for a single instance''s own disk (like a database''s data volume), EFS when multiple instances need to share the same filesystem, S3 for API-driven object storage at any scale.', 'beginner'),
('cloud', 'aws', 'fundamentals', 'What is the practical difference between RTO and RPO when planning disaster recovery?', '["They are two names for the same metric", "RTO (Recovery Time Objective) is how long the business can tolerably be down and drives how fast failover automation must work; RPO (Recovery Point Objective) is how much data can be lost and drives how frequently backups/replication must run", "RTO only applies to databases, RPO only applies to compute", "Neither metric affects the choice of DR strategy"]', 1, 'A strategy like Backup & Restore has a long RTO (hours) and depends on backup frequency for its RPO; Active-Active has a near-zero RTO and RPO but costs roughly double -- the right strategy is the one whose RTO/RPO actually matches the business requirement, not the most expensive option by default.', 'intermediate'),

-- ---------- cloud/aws/intermediate ----------
('cloud', 'aws', 'intermediate', 'Why is a leaked IAM Role credential generally less dangerous than a leaked IAM User access key?', '["Role credentials cannot be used to call any AWS API", "Role credentials are short-lived and expire on their own within hours; a User''s static access key remains valid indefinitely until someone manually rotates or revokes it", "Roles are only usable from inside AWS''s own network", "There is no meaningful difference in risk"]', 1, 'This is why the guidance is to always prefer Roles for applications and services -- the natural expiry of temporary credentials bounds the damage window even if one leaks, unlike a long-lived key that stays exploitable until someone notices.', 'intermediate'),
('cloud', 'aws', 'intermediate', 'What underlying pattern does IRSA (AWS), Azure Managed Identity, and GCP Workload Identity all share?', '["They are unrelated features specific to each cloud with no common concept", "All three federate a Kubernetes-native identity (a ServiceAccount) directly to the cloud provider''s IAM system, so pods get cloud credentials without any long-lived secret stored in the cluster", "Only AWS supports this pattern; Azure and GCP require storing static keys in Kubernetes Secrets", "They all require a third-party identity broker outside the cloud provider"]', 1, 'Recognizing this as the same underlying pattern across all three major clouds is useful -- the mechanism (OIDC federation from a K8s ServiceAccount to a cloud IAM role/identity) transfers even though the exact setup commands differ.', 'intermediate'),
('cloud', 'aws', 'intermediate', 'How does an SCP (Service Control Policy) differ from a regular IAM policy?', '["They are identical; SCP is just another name for an IAM policy", "IAM policies grant permissions within an account; SCPs set an outer boundary an account can never exceed, regardless of what IAM policies inside it grant -- SCPs apply at the AWS Organizations level, above individual accounts", "SCPs can only deny access to the root user, never to IAM roles", "SCPs replace the need for any IAM policies within the account"]', 1, 'A common real pattern is an SCP blocking entire regions or specific high-risk actions (like disabling CloudTrail) across every account in an organization, so no individual account''s IAM misconfiguration can violate an org-wide requirement.', 'advanced'),
('cloud', 'aws', 'intermediate', 'Why does VPC CIDR range planning matter disproportionately early in a project''s life, compared to most other configuration choices?', '["CIDR blocks cannot be changed at all after a VPC is created, ever, under any circumstances", "Changing a VPC''s CIDR block later is disruptive, and overlapping CIDR ranges between environments (prod/staging/dev) block VPC peering entirely, requiring a genuinely painful re-IP to fix after the fact", "CIDR ranges directly determine EC2 instance pricing", "AWS charges more for larger CIDR ranges"]', 1, 'This is a case where an early planning decision (choosing non-overlapping CIDR ranges across environments) is far cheaper to get right upfront than to retrofit once VPC peering or a multi-account setup is already needed and the ranges collide.', 'advanced'),
('cloud', 'aws', 'intermediate', 'Why is resource tagging described as a prerequisite for cost visibility rather than something to add later?', '["Untagged resources are automatically deleted by AWS after 30 days", "Cost Explorer and Cost Allocation Reports are only as useful as tagging discipline -- untagged resources show up as unattributed spend with no way to retroactively determine which team or project it belonged to without manual investigation", "Tagging is required for an EC2 instance to boot", "AWS bills are only itemized by tag, never by service"]', 1, 'Retrofitting tags onto hundreds of already-created, already-costing resources later is far more expensive than establishing tagging as a required, enforced convention (via SCPs or automated policy checks) before resource sprawl happens.', 'intermediate'),

-- ---------- cloud/aws-iam/overview ----------
('cloud', 'aws-iam', 'overview', 'What is the difference between Authentication and Authorization in IAM?', '["They are the same check performed twice for redundancy", "Authentication verifies identity (who are you?), done via access keys, passwords, or temporary credentials; Authorization verifies permissions (what can you do?), done via IAM policies evaluated at request time", "Authorization happens before Authentication", "Only IAM Users go through Authentication; Roles skip it"]', 1, 'Every AWS API call goes through both steps in order -- first proving who is making the request, then checking whether that identity''s policies actually permit the specific action being requested.', 'beginner'),
('cloud', 'aws-iam', 'overview', 'In IAM policy evaluation, what happens when no policy statement addresses a given action at all?', '["The action is allowed by default", "The action is implicitly denied -- by default, everything is denied unless an explicit Allow grants it", "AWS prompts the user to create a policy on the fly", "The action succeeds but is logged as a warning"]', 1, 'IAM''s default posture is deny-by-default: an action is only permitted if some applicable policy explicitly allows it; the absence of any matching statement results in an implicit deny, not an implicit allow.', 'beginner'),
('cloud', 'aws-iam', 'overview', 'What is the key functional difference between an IAM User and an IAM Role?', '["Users and Roles are functionally identical, only the name differs", "A User has permanent, long-term credentials (password/access keys); a Role has no permanent credentials at all -- it is assumed temporarily and AWS STS issues short-lived tokens for it", "Roles can only be assumed by the root user", "Users can be assumed by AWS services; Roles cannot"]', 1, 'This is why Roles are the recommended identity type for AWS services, EC2 instances, and Lambda functions -- there is no static secret sitting around waiting to be leaked, unlike a User''s access keys.', 'beginner'),
('cloud', 'aws-iam', 'overview', 'Why should inline IAM policies generally be avoided in favor of managed (AWS-managed or customer-managed) policies?', '["Inline policies do not support the Effect/Action/Resource structure", "Inline policies are embedded directly in a single user/group/role, which makes them harder to reuse, audit, and manage consistently across many identities compared to a standalone managed policy that can be attached to multiple identities and versioned independently", "Inline policies are billed separately by AWS", "Inline policies can only deny access, never allow it"]', 1, 'A managed policy is a standalone, reusable, versioned object you can attach to many identities and update in one place; an inline policy is tightly coupled to the one identity it was created on, making it easy to lose track of at scale.', 'intermediate'),
('cloud', 'aws-iam', 'overview', 'What does an IAM permissions boundary do?', '["It grants the maximum permissions an identity can have, on top of whatever its attached policies allow", "It sets the maximum permissions an IAM user or role can have -- even if an attached policy grants more, the boundary caps the effective permissions to the intersection of both", "It only applies to S3 bucket policies", "It is identical in function to a Service Control Policy and can only be set at the AWS Organizations level"]', 1, 'Permissions boundaries are commonly used to let a team delegate IAM role creation safely -- a developer can create roles, but any role they create is still capped by the boundary, preventing privilege escalation.', 'intermediate'),

-- ---------- cloud/aws-iam/fundamentals ----------
('cloud', 'aws-iam', 'fundamentals', 'In an IAM policy JSON document, what does the "Condition" block let you do?', '["Nothing -- it is optional metadata AWS ignores at evaluation time", "Restrict when a policy statement''s Allow or Deny actually applies, based on context like source IP, requested region, or whether MFA is present", "Replace the need for an Effect field", "Only works in resource-based policies, never identity-based ones"]', 1, 'Conditions let you scope a broad-looking Allow down to specific real-world circumstances -- for example, allowing an action only from a specific IP range or only when the request specifies a particular AWS region.', 'intermediate'),
('cloud', 'aws-iam', 'fundamentals', 'Why does attaching an IAM role to an EC2 instance require creating an instance profile, rather than attaching the role directly?', '["EC2 instances cannot use IAM roles at all, only ECS tasks can", "An instance profile is the container object that actually associates an IAM role with an EC2 instance -- EC2 does not support attaching a role object to an instance directly, it attaches an instance profile that wraps the role", "Instance profiles are only needed for Windows instances", "Instance profiles replace the need for a trust policy on the role"]', 1, 'This is a common point of confusion: `aws iam create-role` alone isn''t enough for EC2 -- you also need `create-instance-profile` and `add-role-to-instance-profile` before the role can actually be attached to a running or launching instance.', 'intermediate'),
('cloud', 'aws-iam', 'fundamentals', 'In cross-account role assumption, what does the ExternalId condition on the trust policy protect against?', '["SQL injection attacks", "The confused deputy problem -- it prevents a third party from tricking an intermediary into assuming a role on your behalf using credentials that were meant for a different, legitimate purpose", "It has no security purpose, it is purely for logging", "It replaces the need for MFA entirely"]', 1, 'ExternalId is specifically recommended when a third party (like a SaaS vendor) needs to assume a role in your account -- it ensures only requests that know and supply the correct external ID can successfully assume the role, closing a specific cross-account trust gap.', 'advanced'),
('cloud', 'aws-iam', 'fundamentals', 'Given a policy with `"Effect": "Deny", "Action": "s3:DeleteObject", "Resource": "*"` alongside a separate statement allowing `s3:*` on the same resource, what is the actual outcome for a DeleteObject call?', '["DeleteObject succeeds because Allow statements are evaluated first", "DeleteObject is denied -- an explicit Deny always overrides an Allow, even one as broad as s3:*", "The two statements cancel out and the action is allowed by default", "AWS returns an error because the policy is invalid"]', 1, 'This is exactly the kind of policy combination used intentionally to carve out an exception (e.g. allow broad S3 access but explicitly forbid deletion) -- the explicit Deny wins regardless of how permissive the Allow statement is.', 'intermediate'),
('cloud', 'aws-iam', 'fundamentals', 'What does `aws sts assume-role` return that lets code actually act as the assumed role?', '["A permanent replacement for the caller''s original credentials", "A set of temporary credentials (AccessKeyId, SecretAccessKey, SessionToken) that expire after a limited duration and are used to construct a new session acting as the role", "Nothing -- assume-role only validates permissions without returning usable credentials", "A password reset link for the role"]', 1, 'The returned SessionToken is required alongside the temporary access key/secret pair -- all three together let an SDK session authenticate as the assumed role until the credentials expire.', 'intermediate'),

-- ---------- cloud/aws-iam/intermediate ----------
('cloud', 'aws-iam', 'intermediate', 'What does Attribute-Based Access Control (ABAC) let you do that a purely role-based static policy cannot as easily?', '["ABAC removes the need for any IAM policies at all", "ABAC grants or restricts access dynamically based on matching tags (attributes) between the principal and the resource -- e.g. an engineer can only start/stop EC2 instances tagged with their own team, without needing a separate static policy per team", "ABAC only works for S3 buckets", "ABAC is identical to a permissions boundary"]', 1, 'Instead of writing and maintaining a separate policy per team or project, a single ABAC policy condition like matching `PrincipalTag/team` against `ResourceTag/team` scales automatically as new teams and tagged resources are added.', 'advanced'),
('cloud', 'aws-iam', 'intermediate', 'What is true of Service Control Policies (SCPs) applied at the AWS Organizations level?', '["SCPs grant permissions directly to IAM users in member accounts", "SCPs don''t grant any permissions themselves -- they set maximum permissions, meaning an account still needs its own IAM policies to actually allow anything, capped by whatever the SCP permits", "SCPs can only be applied to the organization''s management account", "SCPs override MFA requirements automatically"]', 1, 'An SCP denying `organizations:LeaveOrganization` or restricting actions outside approved regions is a guardrail, not a grant -- the actual permissions inside each account still come from that account''s own IAM policies, bounded by the SCP.', 'advanced'),
('cloud', 'aws-iam', 'intermediate', 'In an SCP that restricts actions to specific regions using `NotAction` with services like `iam:*`, `organizations:*`, and `budgets:*` excluded, why are those specific services carved out?', '["Those services are being deliberately blocked, not allowed", "Those are global services that don''t operate on a per-region basis, so excluding them from the region-restriction Deny prevents the SCP from accidentally breaking account-wide functionality that doesn''t have a regional concept", "IAM and Organizations are the only services AWS allows SCPs to target", "It is an arbitrary AWS requirement with no technical reason"]', 1, 'IAM, Organizations, and a handful of other services are global rather than regional -- if a region-restriction SCP didn''t exclude them, it could break basic account administration that has no single "region" to match against.', 'advanced'),
('cloud', 'aws-iam', 'intermediate', 'What is the role of a Permission Set in AWS IAM Identity Center (SSO)?', '["It stores a user''s password for cross-account login", "It defines what access a user or group gets when they log in and are assigned to a specific AWS account, functioning like a template of policies applied at sign-in time rather than permanent per-account IAM users", "It replaces the need for AWS accounts entirely", "It is only used for billing reports"]', 1, 'Permission Sets let an organization centrally define access levels (e.g. "DeveloperAccess") once and assign them to users/groups across many AWS accounts, issuing temporary credentials at login rather than requiring long-term IAM users in every account.', 'intermediate'),
('cloud', 'aws-iam', 'intermediate', 'In an SCP requiring MFA for sensitive actions, why is the condition written as `"BoolIfExists": {"aws:MultiFactorAuthPresent": "false"}` instead of a plain `"Bool"` condition?', '["BoolIfExists is just a stylistic alias with no functional difference from Bool", "BoolIfExists avoids errors/unexpected denials for requests where the MFA context key isn''t present at all (e.g. some role-assumption or service-to-service calls), only enforcing the check when the key IS present and evaluates to false", "BoolIfExists only works with numeric conditions, not booleans", "BoolIfExists disables the condition entirely"]', 1, 'A plain Bool condition can behave unexpectedly when the referenced context key is entirely absent from the request; the *IfExists variants are the standard, safer way to write conditions that should only apply when that key is actually present.', 'advanced'),

-- ---------- cloud/aws-iam/advanced ----------
('cloud', 'aws-iam', 'advanced', 'When both an identity-based policy and a permissions boundary are attached to a role, how is the effective (actual) set of permissions determined?', '["The identity-based policy alone determines effective permissions; the boundary is ignored", "The boundary alone determines effective permissions; the identity-based policy is ignored", "Effective permissions are the intersection (AND) of what the identity-based policy allows and what the permissions boundary allows -- an action must be permitted by both to actually work", "Effective permissions are the union (OR) of both, so either one allowing it is enough"]', 2, 'A permissions boundary caps the maximum the identity-based policy can ever grant -- even a very permissive identity policy is limited to whatever the boundary also allows, which is exactly why boundaries are used to safely delegate role/policy creation.', 'advanced'),
('cloud', 'aws-iam', 'advanced', 'What does IAM Access Analyzer help identify that a manual policy review would struggle to catch?', '["Syntax errors in JSON formatting only", "Resources (like S3 buckets or IAM roles) that are unintentionally accessible to external principals outside the account/organization, by analyzing resource-based policies for public or cross-account access paths", "CPU usage of EC2 instances", "Billing anomalies"]', 1, 'Access Analyzer specifically surfaces unintended external/public access findings -- the kind of misconfiguration (a bucket policy that''s broader than intended) that''s easy to miss reading policy JSON by eye but has real security consequences.', 'advanced'),
('cloud', 'aws-iam', 'advanced', 'What is the purpose of `aws iam simulate-principal-policy`?', '["It actually performs the specified API action for testing purposes", "It evaluates what a given principal''s attached policies would allow or deny for specified actions/resources, without actually making the live API call -- useful for testing policy changes before applying them", "It generates a new IAM policy automatically based on usage patterns", "It deletes unused policies"]', 1, 'This lets you validate "would this role be allowed to do X" as a dry run, which is far safer than granting a policy change and then testing it against production resources directly.', 'intermediate'),
('cloud', 'aws-iam', 'advanced', 'What does `aws iam generate-service-last-accessed-details` help you build?', '["A least-privilege policy, by showing what services/actions a role has ACTUALLY used over a recent window (e.g. the last 90 days), rather than what its policy merely permits", "A complete audit log of every API call ever made in the account", "A cost breakdown by IAM role", "A list of all IAM roles created in the account"]', 0, 'Comparing what a role is allowed to do against what it has actually used recently is the practical way to trim an overly broad policy down toward real least privilege, instead of guessing at what permissions are truly needed.', 'advanced'),
('cloud', 'aws-iam', 'advanced', 'What does `aws sts get-caller-identity` return, and why is it a common first debugging step?', '["The account''s billing information","The account ID, user/role ARN, and a unique ID for the identity making the call -- it answers the basic question \"who am I actually authenticated as right now\" before digging into more specific permission errors","A list of all IAM users in the account","The current region''s available AZs"]', 1, 'Before troubleshooting a specific AccessDenied error, confirming exactly which identity (which account, which role/user ARN) is actually making the call rules out a whole class of "wrong credentials loaded" problems first.', 'beginner'),

-- ---------- cloud/aws-ec2/overview ----------
('cloud', 'aws-ec2', 'overview', 'In the instance type name `c6i.2xlarge`, what does the `c` prefix indicate?', '["The 6th generation of all instance types", "The instance family''s optimization target -- in this case, compute-optimized (as opposed to `m` for general purpose, `r` for memory-optimized, etc.)", "The AWS region the instance runs in", "The number of vCPUs"]', 1, 'The naming convention encodes family (what it''s optimized for), generation number, processor type (Intel/AMD/Graviton), and size all in one string -- `c6i.2xlarge` is a 6th-generation, Intel-processor, compute-optimized instance at the 2xlarge size.', 'beginner'),
('cloud', 'aws-ec2', 'overview', 'What kind of firewall is an EC2 Security Group, and what rule types does it support?', '["Stateless, at the subnet level, supporting both allow and deny rules", "Stateful, at the instance level, supporting allow rules only -- there is no explicit deny; anything not explicitly allowed is implicitly blocked", "Stateful, at the VPC level, replacing the need for a VPC entirely", "Stateless, at the instance level, requiring both inbound and outbound rules for return traffic"]', 1, 'Because Security Groups are stateful, once inbound traffic is allowed, the corresponding return traffic is automatically permitted -- you never need a matching outbound rule just to let a response go back out.', 'beginner'),
('cloud', 'aws-ec2', 'overview', 'When is an Elastic IP address free, and when does it start costing money?', '["It is always free regardless of usage", "It is free while attached to a running instance, but incurs a charge while allocated but NOT attached to a running instance -- this is meant to discourage hoarding unused static IPs", "It is always charged from the moment it is allocated", "Cost depends only on the AWS region, never on attachment status"]', 1, 'This billing model exists specifically so that Elastic IPs (a scarce IPv4 resource) aren''t held indefinitely without being used -- allocating one and leaving it unattached is a common source of small unexpected charges.', 'beginner'),
('cloud', 'aws-ec2', 'overview', 'What is the key difference between stopping and terminating an EC2 instance?', '["They are functionally identical -- both permanently delete the instance", "Stopping preserves the instance and its EBS volumes (can be started again, same instance ID, no compute billing while stopped); terminating permanently deletes the instance and its root EBS volume (unless DeleteOnTermination is set to false), and cannot be undone", "Terminating pauses billing while keeping the instance recoverable; stopping deletes it permanently", "Stopping only applies to Windows instances"]', 1, 'This distinction matters operationally -- stopping is safe for cost savings on instances you''ll need again (e.g. dev environments overnight), while terminating is a one-way action reserved for instances you''re actually done with.', 'beginner'),
('cloud', 'aws-ec2', 'overview', 'Which EC2 pricing model offers the largest potential discount but comes with the risk of AWS reclaiming the instance with only a short notice period?', '["On-Demand", "Reserved Instances (3-year)", "Spot Instances", "Dedicated Host"]', 2, 'Spot Instances draw on AWS''s spare capacity at a steep discount, but that capacity can be reclaimed (with a short interruption notice) whenever AWS needs it back -- making Spot suited to fault-tolerant, interruptible workloads rather than anything that must stay running continuously.', 'beginner'),

-- ---------- cloud/aws-ec2/fundamentals ----------
('cloud', 'aws-ec2', 'fundamentals', 'Why does retrieving EC2 instance metadata with IMDSv2 require a PUT request for a token before any GET request to the metadata endpoint?', '["It is purely a legacy requirement with no security purpose", "The PUT-then-token pattern requires the caller to make a direct, deliberate request from the instance itself, which mitigates SSRF attacks -- a vulnerability that could trick the instance into forwarding an attacker''s GET request to the metadata service under IMDSv1 cannot as easily forward the PUT step", "It only exists to add latency for rate-limiting purposes", "PUT requests are cached, GET requests are not"]', 1, 'IMDSv1''s simple GET-only interface made it possible for certain server-side request forgery (SSRF) vulnerabilities in an application to be tricked into fetching instance credentials from the metadata service; IMDSv2''s token-based handshake closes that specific gap.', 'advanced'),
('cloud', 'aws-ec2', 'fundamentals', 'When does EC2 User Data (a bootstrap script) actually execute?', '["On every single boot of the instance, including every restart", "As root, once, when the instance first boots (launches) -- it is not re-run automatically on subsequent stop/start cycles by default", "Only when manually triggered via the AWS Console", "Only on Windows instances, never on Linux"]', 1, 'This is why User Data is used for one-time bootstrap tasks like installing packages or configuring the instance on first launch, rather than for anything that needs to run repeatedly -- that would need a different mechanism (like a systemd service or cron).', 'intermediate'),
('cloud', 'aws-ec2', 'fundamentals', 'In an Auto Scaling Group''s Target Tracking scaling policy set to a target CPU of 60%, what does AWS actually do?', '["It terminates any instance whose CPU exceeds 60% immediately", "It automatically adjusts the number of running instances (within min/max bounds) to try to keep the group''s average CPU utilization near the 60% target, scaling out when load is higher and scaling in when load is lower", "It caps every individual instance''s CPU usage at 60%", "It only scales up, never scales back down"]', 1, 'Target tracking works like a thermostat -- it continuously compares the actual metric (CPU here) against the target and adds or removes instances to close the gap, rather than requiring manually defined step thresholds.', 'intermediate'),
('cloud', 'aws-ec2', 'fundamentals', 'What does restricting a Security Group''s SSH ingress rule to `$(curl -s ifconfig.me)/32` accomplish, compared to `0.0.0.0/0`?', '["Nothing different -- both allow the same access", "It limits inbound port 22 access to only the caller''s own current public IP address (a /32 is a single exact IP), instead of allowing SSH from literally anywhere on the internet", "It disables SSH entirely", "It only works for IPv6 addresses"]', 1, 'Scoping SSH access to a known IP (your own, or your office''s) rather than the entire internet is a basic but important hardening step -- `0.0.0.0/0` on port 22 exposes the instance to SSH brute-force attempts from anywhere.', 'beginner'),
('cloud', 'aws-ec2', 'fundamentals', 'What is the practical difference between an EC2 System status check failure and an Instance status check failure?', '["They mean the same thing and require the same fix", "A System status check failure indicates an underlying AWS hardware/hypervisor issue (AWS''s responsibility to resolve, often fixed by stopping/starting to move to new hardware); an Instance status check failure indicates an OS/network-level problem inside the instance (the customer''s responsibility to diagnose)", "System checks only apply to Windows instances", "Instance checks are purely cosmetic and don''t indicate real problems"]', 1, 'Knowing which check failed tells you where to look first -- a System check failure is often resolved simply by stopping and starting the instance (which relocates it to different underlying hardware), while an Instance check failure needs investigation inside the guest OS.', 'intermediate'),

-- ---------- cloud/aws-ec2/intermediate ----------
('cloud', 'aws-ec2', 'intermediate', 'In a `mixed_instances_policy` Auto Scaling Group with `on_demand_base_capacity = 2` and the rest on Spot, what does that configuration guarantee?', '["All instances in the group will always be Spot, with no On-Demand at all", "At least 2 instances in the group are always kept On-Demand as a stable baseline, while additional capacity beyond that base is fulfilled by Spot Instances for cost savings", "Exactly 2 instances total will ever run, regardless of load", "Spot capacity is prioritized over the On-Demand base capacity"]', 1, 'This pattern gives a workload a guaranteed floor of stable, non-interruptible capacity (the base) while still capturing Spot''s cost savings for the elastic portion of capacity above that floor.', 'advanced'),
('cloud', 'aws-ec2', 'intermediate', 'Setting `http_tokens = "required"` in a launch template''s `metadata_options` enforces what?', '["That the instance cannot access the metadata service at all", "IMDSv2 -- callers must first obtain a session token via a PUT request before they can retrieve any instance metadata; plain GET requests without a token (IMDSv1-style) are rejected", "That only IPv6 metadata requests are allowed", "That user data must be base64-encoded"]', 1, 'Setting this at the launch template level ensures every instance launched from it enforces the more SSRF-resistant IMDSv2 flow by default, rather than leaving it as an optional per-instance setting.', 'advanced'),
('cloud', 'aws-ec2', 'intermediate', 'What does AWS Systems Manager (SSM) Session Manager let you do that traditional SSH access does not require?', '["A public IP address on the instance", "A direct connection to the instance without needing an open inbound SSH port, a bastion host, or a distributed SSH key -- it requires an IAM role with SSM permissions and the SSM Agent running on the instance instead", "Root access to the instance by default", "A VPN connection to the VPC"]', 1, 'Because the connection is established via the SSM Agent calling out to the SSM service (not an inbound connection to the instance), there''s no need to open port 22 in a security group at all -- reducing the instance''s network attack surface.', 'intermediate'),
('cloud', 'aws-ec2', 'intermediate', 'Why is SSM Parameter Store''s `SecureString` type used for values like a database connection URL, and what flag is needed to actually read the decrypted value back?', '["SecureString values cannot be read back at all once written", "SecureString encrypts the value at rest using KMS; retrieving it in plaintext requires explicitly passing `--with-decryption` on `get-parameter`, otherwise the encrypted ciphertext is returned instead", "SecureString is identical to the plain String type, only the name differs", "SecureString requires a separate AWS account to access"]', 1, 'This is a deliberate two-step design -- storing as SecureString protects the value at rest, and requiring an explicit `--with-decryption` flag on read means accidentally logging or displaying a parameter value without decryption doesn''t leak the actual secret.', 'intermediate'),
('cloud', 'aws-ec2', 'intermediate', 'What does an Auto Scaling Group''s `instance_refresh` with `strategy = "Rolling"` and `min_healthy_percentage = 90` accomplish when a launch template changes?', '["It terminates all instances at once and relaunches them simultaneously", "It replaces instances gradually, only terminating old ones as new ones become healthy, while ensuring at least 90% of the group stays healthy and in service throughout the rollout -- avoiding a capacity/availability drop during the update", "It only applies the new launch template to instances launched in the future, never touching existing ones", "It rolls back to the previous launch template automatically after replacement"]', 1, 'This is how a launch template change (say, a new AMI) safely propagates to a running ASG without an outage -- the rolling replacement respects a minimum healthy percentage so the group never drops too much capacity at once.', 'advanced'),

-- ---------- cloud/aws-ec2/advanced ----------
('cloud', 'aws-ec2', 'advanced', 'Why does a Spot Fleet request typically specify multiple instance types and multiple subnets/AZs rather than just one?', '["To reduce the total cost to zero", "To improve availability -- diversifying across instance types and AZs increases the pool of Spot capacity the fleet can draw from, reducing the chance that the entire fleet is interrupted at once when capacity for one specific instance type/AZ becomes scarce", "AWS requires at least 4 instance types per Spot Fleet request by policy", "Multiple instance types are required for the API call to be syntactically valid"]', 1, 'Concentrating an entire Spot Fleet on one instance type in one AZ means the whole fleet is exposed to that single pool''s capacity fluctuations; diversifying spreads that risk across many independent pools.', 'advanced'),
('cloud', 'aws-ec2', 'advanced', 'What is the correct way to react to a Spot Instance interruption notice polled from the instance metadata service?', '["Ignore it -- Spot Instances cannot actually be terminated once running", "Treat it as a roughly 2-minute warning to checkpoint in-progress work and gracefully stop accepting new work before the instance is reclaimed, since the interruption is otherwise abrupt and unrecoverable", "Immediately force-terminate all other instances in the fleet", "Increase the instance''s CPU credits to prevent the interruption"]', 1, 'Polling the `/spot/interruption-action` metadata path is the standard pattern for giving a batch job or stateful process the chance to save its state and drain connections cleanly in the short window before AWS actually reclaims the instance.', 'advanced'),
('cloud', 'aws-ec2', 'advanced', 'What does EC2 Image Builder automate compared to manually creating a "golden" AMI by hand?', '["Nothing -- Image Builder still requires manually launching and configuring an instance each time", "A repeatable pipeline that builds an image from a base/parent AMI plus defined components (installed packages, hardening scripts), and can be scheduled to run automatically and distribute the resulting AMI to multiple regions", "It only works for Windows AMIs, not Linux", "It replaces the need for any AMI at all by running instances from a live template each time"]', 1, 'Instead of a person manually launching an instance, installing/hardening it, then snapshotting an AMI by hand (a process that''s easy to do inconsistently), Image Builder codifies the recipe and can re-run it on a schedule so AMIs stay current with patches automatically.', 'intermediate'),
('cloud', 'aws-ec2', 'advanced', 'In a `request_spot_fleet` call, what does setting `"Type": "maintain"` do, compared to a one-time request?', '["It requests instances once and never replaces them even if interrupted", "It keeps the fleet at the target capacity on an ongoing basis, automatically requesting replacement Spot capacity whenever an instance is interrupted, rather than being a single point-in-time request", "It converts all instances in the fleet to On-Demand automatically", "It has no effect on fleet behavior"]', 1, '"maintain" is what makes a Spot Fleet suitable for a long-running service rather than a single batch job -- AWS actively works to keep the fleet at the requested target capacity over time, not just fulfill it once.', 'advanced'),
('cloud', 'aws-ec2', 'advanced', 'Why must EC2 User Data be base64-encoded before being included in a `run-instances` or launch template API call?', '["Because AWS only accepts image files as base64", "Because the EC2 API transmits User Data as part of a JSON/structured request, and base64 encoding is the standard way to safely embed arbitrary binary/text script content (which may include special characters) inside that request format", "Because base64 encoding compresses the script to reduce cost", "Base64 encoding is optional and has no functional purpose"]', 1, 'This is why example code that builds User Data programmatically (like a Python script assembling a Spot Fleet request) needs to explicitly base64-encode the script content before including it in the API payload -- passing raw, unencoded script text would not be interpreted correctly.', 'intermediate')

ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
