-- ============================================================
-- /learn quiz: CBSE Class 10 Science -- batch 3, final batch (Physics):
-- Light - Reflection and Refraction, Human Eye and the Colourful World,
-- Electricity, Magnetic Effects of Electric Current. Completes the
-- subject's remaining 4 of 14 chapters (Chemistry in batch 1, Biology
-- in batch 2).
--
-- SOURCING: same disclosed limitation as batches 1-2 -- authored to
-- match real CBSE Section-A exam style/difficulty, NOT copied from any
-- official CBSE question paper. Every factual/numeric claim below was
-- independently checked before writing.
--
-- Applied via @supabase/supabase-js, upsert(rows, { onConflict:
-- "academy_slug,technology_slug,section_slug,question", ignoreDuplicates:
-- true }) -- functionally identical to this file's ON CONFLICT clause.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES
('education', 'class-10/science', 'light', 'According to the laws of reflection, the angle of incidence is always:', '["Equal to the angle of reflection", "Twice the angle of reflection", "Half the angle of reflection", "Unrelated to the angle of reflection"]', 0, 'The first law of reflection states that the angle of incidence equals the angle of reflection, both measured from the normal.', 'beginner'),
('education', 'class-10/science', 'light', 'A convex mirror always forms an image that is:', '["Virtual and diminished", "Real and enlarged", "Virtual and enlarged", "Real and diminished"]', 0, 'A convex mirror always produces a virtual, erect, and diminished image, regardless of the object''s distance -- which is why they are used as vehicle side mirrors for a wider field of view.', 'beginner'),
('education', 'class-10/science', 'light', 'The refractive index of a medium is defined as the ratio of:', '["Speed of light in vacuum to speed of light in the medium", "Speed of light in the medium to speed of light in vacuum", "Angle of incidence to angle of refraction", "Wavelength in vacuum to wavelength in the medium"]', 0, 'Refractive index n = speed of light in vacuum / speed of light in the medium, a measure of how much the medium slows down and bends light.', 'intermediate'),
('education', 'class-10/science', 'light', 'A concave mirror has a radius of curvature of 20 cm. Its focal length is:', '["10 cm", "20 cm", "40 cm", "5 cm"]', 0, 'Focal length = radius of curvature / 2 = 20/2 = 10 cm, the standard relation between R and f for spherical mirrors.', 'intermediate'),
('education', 'class-10/science', 'light', 'A convex lens is also known as a:', '["Converging lens", "Diverging lens", "Plano-concave lens", "Cylindrical lens"]', 0, 'A convex lens bends parallel light rays inward to converge at a focal point, hence it is called a converging lens.', 'beginner'),
('education', 'class-10/science', 'human-eye', 'The part of the human eye that controls the amount of light entering by adjusting the size of the pupil is the:', '["Iris", "Cornea", "Retina", "Lens"]', 0, 'The iris is the coloured, muscular structure that contracts or dilates to control pupil size and regulate the amount of light entering the eye.', 'beginner'),
('education', 'class-10/science', 'human-eye', 'Myopia (near-sightedness), where distant objects appear blurred, is corrected using a:', '["Concave lens", "Convex lens", "Cylindrical lens", "Bifocal lens with only convex power"]', 0, 'A concave (diverging) lens shifts the image formed by the eye backward onto the retina, correcting myopia caused by the eyeball being too elongated or the lens too curved.', 'beginner'),
('education', 'class-10/science', 'human-eye', 'The ability of the eye lens to adjust its focal length to focus on objects at varying distances is called:', '["Power of accommodation", "Persistence of vision", "Power of resolution", "Visual acuity"]', 0, 'The power of accommodation refers to the ciliary muscles'' ability to change the eye lens''s curvature, allowing objects at different distances to be focused clearly.', 'beginner'),
('education', 'class-10/science', 'human-eye', 'The Tyndall effect refers to the scattering of light by:', '["Colloidal particles suspended in a medium", "Only red-wavelength light", "Water vapor exclusively", "Ozone molecules in the stratosphere"]', 0, 'The Tyndall effect is the scattering of a light beam by colloidal-sized particles (dust, smoke, or fine droplets) suspended in a medium, making the beam''s path visible.', 'intermediate'),
('education', 'class-10/science', 'human-eye', 'Hypermetropia (far-sightedness), where nearby objects appear blurred, is corrected using a:', '["Convex lens", "Concave lens", "Plano-concave lens", "No correction is possible with lenses"]', 0, 'A convex (converging) lens brings the image forward onto the retina, correcting hypermetropia caused by the eyeball being too short or the lens too weak.', 'beginner'),
('education', 'class-10/science', 'electricity', 'According to Ohm''s Law, the relationship between voltage (V), current (I), and resistance (R) is:', '["V = I x R", "V = I / R", "V = I + R", "V = I - R"]', 0, 'Ohm''s Law states that the voltage across a conductor is directly proportional to the current through it, with resistance as the constant of proportionality: V = IR.', 'beginner'),
('education', 'class-10/science', 'electricity', 'The SI unit of electrical resistance is the:', '["Ohm", "Volt", "Ampere", "Watt"]', 0, 'Electrical resistance is measured in ohms, symbolized by the Greek letter omega.', 'beginner'),
('education', 'class-10/science', 'electricity', 'When two resistors R1 and R2 are connected in series, their equivalent resistance is:', '["R1 + R2", "(R1 x R2) / (R1 + R2)", "1/R1 + 1/R2", "R1 - R2"]', 0, 'In a series combination, resistances simply add up: Req = R1 + R2.', 'beginner'),
('education', 'class-10/science', 'electricity', 'The electrical power consumed by a device is given by the formula:', '["P = V x I", "P = V / I", "P = V + I", "P = I / V"]', 0, 'Electrical power is the product of voltage and current: P = VI, derivable from combining Ohm''s Law with the definition of power.', 'beginner'),
('education', 'class-10/science', 'electricity', 'If a device operates at a voltage of 10 V and draws a current of 2 A, its resistance is:', '["5 ohm", "20 ohm", "0.2 ohm", "12 ohm"]', 0, 'By Ohm''s Law, R = V/I = 10/2 = 5 ohm.', 'intermediate'),
('education', 'class-10/science', 'magnetic-effects', 'A device that converts electrical energy into mechanical energy, based on the magnetic effect of current, is called a(n):', '["Electric motor", "Electric generator", "Transformer", "Galvanometer"]', 0, 'An electric motor uses the force experienced by a current-carrying conductor in a magnetic field to convert electrical energy into rotational mechanical energy.', 'beginner'),
('education', 'class-10/science', 'magnetic-effects', 'A device that converts mechanical energy into electrical energy using electromagnetic induction is called a(n):', '["Electric generator", "Electric motor", "Transformer", "Rectifier"]', 0, 'An electric generator (dynamo) rotates a coil within a magnetic field to induce an electric current, converting mechanical energy into electrical energy.', 'beginner'),
('education', 'class-10/science', 'magnetic-effects', 'The Right-Hand Thumb Rule is used to determine the:', '["Direction of the magnetic field around a current-carrying conductor", "Magnitude of induced EMF", "Direction of current flow in a circuit", "Polarity of a battery"]', 0, 'The Right-Hand Thumb Rule states that if the thumb points in the direction of conventional current, the curled fingers show the direction of the magnetic field lines around the conductor.', 'beginner'),
('education', 'class-10/science', 'magnetic-effects', 'Domestic electrical circuits are typically wired with appliances connected in:', '["Parallel", "Series", "A mix that is never parallel", "Neither series nor parallel"]', 0, 'Domestic circuits use a parallel arrangement so each appliance receives the same voltage and can be switched on/off independently without affecting others.', 'beginner'),
('education', 'class-10/science', 'magnetic-effects', 'The phenomenon by which a changing magnetic field induces an electric current in a nearby conductor is called:', '["Electromagnetic induction", "Magnetic saturation", "Electrostatic induction", "Faraday shielding"]', 0, 'Electromagnetic induction, discovered by Michael Faraday, is the production of an EMF (and consequently current) due to a changing magnetic flux.', 'beginner')
ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
