-- ============================================================
-- /learn quiz: JEE Maths -- batch 2, final Maths batch (Calculus,
-- Coordinate Geometry, Vectors/3D, Probability, Statistics): Limits and
-- Derivatives, Applications of Derivatives, Integrals, Coordinate
-- Geometry, Vectors and 3D Geometry, Probability, Statistics. Completes
-- the remaining 7 of the subject's 13 chapters (batch 1 covered
-- Algebra).
--
-- SOURCING: same disclosed limitation as batch 1 -- authored to match
-- real JEE Main single-correct-MCQ style/difficulty, NOT copied from
-- any official JEE question paper. Every mathematical claim below was
-- independently checked before writing.
--
-- Applied via @supabase/supabase-js, upsert(rows, { onConflict:
-- "academy_slug,technology_slug,section_slug,question", ignoreDuplicates:
-- true }) -- functionally identical to this file's ON CONFLICT clause.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES
('education', 'jee/maths', 'limits-derivatives', 'The standard limit lim(x->0) sin(x)/x equals:', '["1", "0", "infinity", "-1"]', 0, 'This is one of the most important standard limits in calculus: lim(x->0) sin(x)/x = 1.', 'beginner'),
('education', 'jee/maths', 'limits-derivatives', 'By the power rule, the derivative of x^n with respect to x is:', '["n x^(n-1)", "x^(n-1)", "n x^n", "(n-1) x^n"]', 0, 'The power rule states d/dx(x^n) = n x^(n-1).', 'beginner'),
('education', 'jee/maths', 'limits-derivatives', 'The derivative of sin(x) with respect to x is:', '["cos(x)", "-cos(x)", "-sin(x)", "tan(x)"]', 0, 'd/dx(sin x) = cos x, one of the standard trigonometric derivatives.', 'beginner'),
('education', 'jee/maths', 'limits-derivatives', 'The derivative of e^x with respect to x is:', '["e^x", "x e^(x-1)", "e^(x-1)", "1/e^x"]', 0, 'e^x is unique in that it is its own derivative: d/dx(e^x) = e^x.', 'beginner'),
('education', 'jee/maths', 'limits-derivatives', 'The derivative of x^3 evaluated at x = 2 is:', '["12", "8", "6", "24"]', 0, 'd/dx(x^3) = 3x^2; at x=2, this equals 3(4) = 12.', 'intermediate'),
('education', 'jee/maths', 'applications-derivatives', 'At a local maximum of a twice-differentiable function, the second derivative is generally:', '["Negative", "Positive", "Zero", "Undefined"]', 0, 'By the second derivative test, a negative second derivative at a critical point indicates a local maximum (the curve is concave down).', 'intermediate'),
('education', 'jee/maths', 'applications-derivatives', 'Rolle''s Theorem requires a function to be continuous and differentiable on an interval [a,b], with the additional condition:', '["f(a) = f(b)", "f(a) < f(b)", "f''(a) = f''(b)", "f(a) = 0"]', 0, 'Rolle''s Theorem requires f(a) = f(b), and then guarantees at least one point c in (a,b) where f''(c) = 0.', 'intermediate'),
('education', 'jee/maths', 'applications-derivatives', 'The slope of the tangent to the curve y = f(x) at the point x = a is given by:', '["f''(a)", "f(a)", "f''''(a)", "a x f(a)"]', 0, 'The derivative f''(a) gives the instantaneous rate of change of the function, which is the slope of the tangent line at x = a.', 'beginner'),
('education', 'jee/maths', 'applications-derivatives', 'A function is increasing on an interval if its derivative throughout that interval is:', '["Positive (or non-negative)", "Negative", "Zero", "Undefined"]', 0, 'A positive derivative means the function''s value is rising as x increases, which is the definition of an increasing function on that interval.', 'beginner'),
('education', 'jee/maths', 'applications-derivatives', 'The critical point of f(x) = x^2 - 4x + 3 is at:', '["x = 2", "x = 4", "x = 0", "x = -2"]', 0, 'Setting f''(x) = 2x - 4 = 0 gives x = 2, the only critical point of this parabola.', 'intermediate'),
('education', 'jee/maths', 'integrals', 'The indefinite integral of x^n (for n != -1) with respect to x is:', '["x^(n+1)/(n+1) + C", "x^n/n + C", "n x^(n-1) + C", "x^(n-1)/(n-1) + C"]', 0, 'The power rule for integration: integral of x^n dx = x^(n+1)/(n+1) + C, valid for n != -1.', 'beginner'),
('education', 'jee/maths', 'integrals', 'The indefinite integral of e^x with respect to x is:', '["e^x + C", "x e^x + C", "e^x / x + C", "x^2 e^x / 2 + C"]', 0, 'e^x integrates to itself: integral of e^x dx = e^x + C.', 'beginner'),
('education', 'jee/maths', 'integrals', 'The indefinite integral of 1/x with respect to x is:', '["ln|x| + C", "x^0 + C", "1/x^2 + C", "-1/x^2 + C"]', 0, 'This is the special case where the power rule fails (n=-1); instead, integral of 1/x dx = ln|x| + C.', 'intermediate'),
('education', 'jee/maths', 'integrals', 'The indefinite integral of cos(x) with respect to x is:', '["sin(x) + C", "-sin(x) + C", "-cos(x) + C", "tan(x) + C"]', 0, 'Since d/dx(sin x) = cos x, integrating cos(x) gives sin(x) + C.', 'beginner'),
('education', 'jee/maths', 'integrals', 'The value of the definite integral of x dx from 0 to 1 is:', '["1/2", "1", "0", "2"]', 0, 'Integral of x dx = x^2/2; evaluating from 0 to 1 gives (1/2 - 0) = 1/2.', 'intermediate'),
('education', 'jee/maths', 'coordinate-geometry', 'The slope-intercept form of the equation of a straight line is:', '["y = mx + c", "ax + by + c = 0", "x/a + y/b = 1", "y - y1 = m(x - x1)"]', 0, 'In slope-intercept form, m is the slope and c is the y-intercept: y = mx + c.', 'beginner'),
('education', 'jee/maths', 'coordinate-geometry', 'The equation of a circle with center (h,k) and radius r is:', '["(x-h)^2 + (y-k)^2 = r^2", "(x-h)^2 - (y-k)^2 = r^2", "x^2 + y^2 = r^2 + hk", "(x+h)^2 + (y+k)^2 = r"]', 0, 'This is the standard center-radius form of a circle''s equation, derived directly from the distance formula.', 'beginner'),
('education', 'jee/maths', 'coordinate-geometry', 'The standard parabola y^2 = 4ax (a > 0) opens in which direction, with its focus at (a,0)?', '["Rightward (positive x-direction)", "Leftward (negative x-direction)", "Upward (positive y-direction)", "Downward (negative y-direction)"]', 0, 'For y^2 = 4ax with a>0, the parabola opens to the right, with vertex at the origin and focus at (a,0).', 'intermediate'),
('education', 'jee/maths', 'coordinate-geometry', 'The eccentricity of an ellipse always satisfies:', '["0 < e < 1", "e = 1", "e > 1", "e = 0 always"]', 0, 'An ellipse always has eccentricity strictly between 0 and 1; e=0 gives a circle (a special case) and e=1 would be a parabola.', 'intermediate'),
('education', 'jee/maths', 'coordinate-geometry', 'The eccentricity of a hyperbola always satisfies:', '["e > 1", "0 < e < 1", "e = 1", "e = 0"]', 0, 'A hyperbola always has eccentricity greater than 1, distinguishing it from an ellipse (e<1) or a parabola (e=1).', 'intermediate'),
('education', 'jee/maths', 'vectors-3d', 'The dot product of two vectors a and b is given by:', '["|a||b| cos(theta)", "|a||b| sin(theta)", "|a| + |b|", "|a| x |b| tan(theta)"]', 0, 'The dot (scalar) product is a.b = |a||b|cos(theta), where theta is the angle between the two vectors.', 'beginner'),
('education', 'jee/maths', 'vectors-3d', 'The magnitude of the cross product of two vectors a and b is given by:', '["|a||b| sin(theta)", "|a||b| cos(theta)", "|a| + |b|", "|a| - |b|"]', 0, 'The cross (vector) product has magnitude |a x b| = |a||b|sin(theta), and its direction is perpendicular to both a and b (right-hand rule).', 'beginner'),
('education', 'jee/maths', 'vectors-3d', 'Two vectors a and b are perpendicular to each other if:', '["a . b = 0", "a x b = 0", "|a| = |b|", "a . b = |a||b|"]', 0, 'Perpendicular vectors have cos(theta) = cos(90) = 0, so their dot product a.b must equal zero.', 'beginner'),
('education', 'jee/maths', 'vectors-3d', 'The distance between two points (x1,y1,z1) and (x2,y2,z2) in 3D space is:', '["sqrt[(x2-x1)^2 + (y2-y1)^2 + (z2-z1)^2]", "(x2-x1) + (y2-y1) + (z2-z1)", "sqrt[(x2-x1) + (y2-y1) + (z2-z1)]", "(x2-x1)(y2-y1)(z2-z1)"]', 0, 'The 3D distance formula extends the 2D Pythagoras-based formula by adding a third squared coordinate difference under the square root.', 'beginner'),
('education', 'jee/maths', 'vectors-3d', 'The scalar triple product a . (b x c) geometrically represents the:', '["Volume of the parallelepiped formed by the three vectors", "Area of the parallelogram formed by two of the vectors", "Angle between the three vectors", "Sum of the magnitudes of the three vectors"]', 0, 'The scalar triple product gives the (signed) volume of the parallelepiped with edges along vectors a, b, and c.', 'intermediate'),
('education', 'jee/maths', 'probability', 'Bayes'' Theorem is primarily used to calculate:', '["A conditional probability P(A|B) given P(B|A) and prior probabilities", "The union of two independent events", "The variance of a random variable", "The mean of a binomial distribution"]', 0, 'Bayes'' Theorem relates conditional probabilities, allowing P(A|B) to be computed from P(B|A) and the prior probabilities of A and B.', 'intermediate'),
('education', 'jee/maths', 'probability', 'For two independent events A and B, the probability of both occurring, P(A ∩ B), equals:', '["P(A) x P(B)", "P(A) + P(B)", "P(A) - P(B)", "P(A) / P(B)"]', 0, 'Independence means the occurrence of one event does not affect the other, so their joint probability is simply the product of their individual probabilities.', 'beginner'),
('education', 'jee/maths', 'probability', 'The sum of the probabilities of all possible outcomes in a sample space is always:', '["1", "0", "0.5", "Depends on the sample space"]', 0, 'By the axioms of probability, the probabilities of all mutually exclusive and exhaustive outcomes in a sample space must sum to exactly 1.', 'beginner'),
('education', 'jee/maths', 'probability', 'If P(A) = 0.4 and P(B) = 0.3, and A and B are mutually exclusive events, then P(A ∪ B) equals:', '["0.7", "0.12", "0.1", "1"]', 0, 'For mutually exclusive events, P(A ∪ B) = P(A) + P(B) = 0.4 + 0.3 = 0.7 (since P(A ∩ B) = 0).', 'intermediate'),
('education', 'jee/maths', 'probability', 'In a binomial distribution with n trials and success probability p, the mean is given by:', '["n x p", "n + p", "n / p", "sqrt(np)"]', 0, 'The mean (expected value) of a binomial distribution is np, the number of trials times the probability of success on each trial.', 'intermediate'),
('education', 'jee/maths', 'statistics', 'Variance is defined as the square of the:', '["Standard deviation", "Mean", "Range", "Median"]', 0, 'Standard deviation is defined as the square root of variance, so equivalently, variance is the square of the standard deviation.', 'beginner'),
('education', 'jee/maths', 'statistics', 'The variance of a data set is calculated as the average of the:', '["Squared deviations of each value from the mean", "Absolute deviations of each value from the mean", "Deviations of each value from the median", "Values themselves"]', 0, 'Variance = (sum of (xi - mean)^2) / n, the average of the squared deviations from the mean.', 'beginner'),
('education', 'jee/maths', 'statistics', 'The standard deviation of a data set is always:', '["Non-negative (>= 0)", "Negative", "Equal to the mean", "Equal to the variance"]', 0, 'Since standard deviation is a square root of a sum of squares (variance), it can never be negative.', 'beginner'),
('education', 'jee/maths', 'statistics', 'Karl Pearson''s coefficient of correlation always lies within the range:', '["-1 to +1", "0 to 1", "-infinity to +infinity", "0 to 100"]', 0, 'The Pearson correlation coefficient is bounded between -1 (perfect negative correlation) and +1 (perfect positive correlation).', 'intermediate'),
('education', 'jee/maths', 'statistics', 'The variance of the data set {2, 4, 6} is:', '["8/3", "4", "2", "8"]', 0, 'Mean = 4; squared deviations = (2-4)^2, (4-4)^2, (6-4)^2 = 4, 0, 4; variance = (4+0+4)/3 = 8/3.', 'intermediate')
ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
