-- ============================================================
-- /learn quiz: GATE CSE -- Data Structures & Algorithms, all 7
-- chapters: Arrays and Strings, Linked Lists, Stacks and Queues, Trees,
-- Graphs, Sorting and Searching, Dynamic Programming.
--
-- SOURCING: same disclosed limitation as every /learn quiz batch this
-- session -- authored to match real GATE CSE single-correct-MCQ style,
-- topic distribution, and difficulty for each chapter; NOT copied from
-- any official GATE question paper. Every algorithmic/complexity claim
-- below was independently checked before writing.
--
-- Applied via @supabase/supabase-js, upsert(rows, { onConflict:
-- "academy_slug,technology_slug,section_slug,question", ignoreDuplicates:
-- true }) -- functionally identical to this file's ON CONFLICT clause.
-- ============================================================

INSERT INTO quiz_questions (academy_slug, technology_slug, section_slug, question, options, correct_index, explanation, difficulty) VALUES
('education', 'gate-cse/dsa', 'arrays-strings', 'The time complexity to access an element at a given index in an array is:', '["O(1)", "O(n)", "O(log n)", "O(n^2)"]', 0, 'Arrays provide direct, constant-time access to any element via its index, since the memory address can be computed directly.', 'beginner'),
('education', 'gate-cse/dsa', 'arrays-strings', 'The worst-case time complexity of linear search on an unsorted array of n elements is:', '["O(n)", "O(1)", "O(log n)", "O(n log n)"]', 0, 'Linear search may need to check every element in the worst case (element absent or at the end), giving O(n) time.', 'beginner'),
('education', 'gate-cse/dsa', 'arrays-strings', 'The time complexity of binary search on a sorted array of n elements is:', '["O(log n)", "O(n)", "O(1)", "O(n^2)"]', 0, 'Binary search halves the search space at each step, giving a logarithmic time complexity of O(log n).', 'beginner'),
('education', 'gate-cse/dsa', 'arrays-strings', 'The two-pointer technique is commonly used to efficiently solve problems such as:', '["Finding a pair with a given sum in a sorted array", "Sorting an unsorted array from scratch", "Computing the factorial of a number", "Reversing a singly linked list"]', 0, 'The two-pointer technique, using pointers from both ends of a sorted array moving toward each other, efficiently solves pair-sum-style problems in linear time.', 'intermediate'),
('education', 'gate-cse/dsa', 'arrays-strings', 'The time complexity of the KMP (Knuth-Morris-Pratt) string matching algorithm, for text length n and pattern length m, is:', '["O(n + m)", "O(n x m)", "O(n^2)", "O(log(n+m))"]', 0, 'KMP achieves linear time string matching, O(n+m), by avoiding redundant character comparisons using a precomputed failure function.', 'intermediate'),
('education', 'gate-cse/dsa', 'linked-lists', 'The time complexity to insert a new node at the head of a singly linked list is:', '["O(1)", "O(n)", "O(log n)", "O(n^2)"]', 0, 'Inserting at the head only requires updating the head pointer and the new node''s next pointer, both constant-time operations.', 'beginner'),
('education', 'gate-cse/dsa', 'linked-lists', 'The time complexity to access the nth element of a singly linked list (from the head) is:', '["O(n)", "O(1)", "O(log n)", "O(n^2)"]', 0, 'Unlike arrays, linked lists require traversal from the head node to reach the nth element, giving linear time.', 'beginner'),
('education', 'gate-cse/dsa', 'linked-lists', 'Floyd''s Cycle Detection Algorithm (the "tortoise and hare" method) is used to detect:', '["The presence of a cycle (loop) in a linked list", "The middle element of a linked list only", "Duplicate values in a linked list", "The length of a linked list"]', 0, 'Floyd''s algorithm uses two pointers moving at different speeds; if they ever meet, a cycle exists in the linked list.', 'intermediate'),
('education', 'gate-cse/dsa', 'linked-lists', 'A node in a doubly linked list contains pointers to:', '["Both the next node and the previous node", "Only the next node", "Only the previous node", "The head node only"]', 0, 'A doubly linked list node maintains two pointers, allowing traversal in both forward and backward directions, unlike a singly linked list.', 'beginner'),
('education', 'gate-cse/dsa', 'linked-lists', 'The standard time complexity to iteratively reverse a singly linked list of n nodes is:', '["O(n)", "O(1)", "O(log n)", "O(n^2)"]', 0, 'Reversing a linked list iteratively requires visiting each node exactly once to reverse its pointer, giving O(n) time.', 'intermediate'),
('education', 'gate-cse/dsa', 'stacks-queues', 'A stack data structure follows which access principle?', '["LIFO (Last In, First Out)", "FIFO (First In, First Out)", "Random access", "Priority-based access"]', 0, 'A stack allows insertion and removal only from one end (the top), so the last element inserted is the first one removed -- LIFO.', 'beginner'),
('education', 'gate-cse/dsa', 'stacks-queues', 'A queue data structure follows which access principle?', '["FIFO (First In, First Out)", "LIFO (Last In, First Out)", "Random access", "Priority-based access only"]', 0, 'A queue allows insertion at the rear and removal from the front, so the first element inserted is the first one removed -- FIFO.', 'beginner'),
('education', 'gate-cse/dsa', 'stacks-queues', 'The infix expression "a+b" converts to which postfix expression?', '["ab+", "+ab", "ba+", "a+b (unchanged)"]', 0, 'In postfix notation, operators follow their operands; "a+b" becomes "ab+", with the operator placed after both operands.', 'intermediate'),
('education', 'gate-cse/dsa', 'stacks-queues', 'A circular queue primarily solves which limitation of a simple array-based linear queue?', '["Wastage of space after dequeue operations (false overflow)", "Lack of a rear pointer", "Inability to store more than one data type", "The need for dynamic memory allocation"]', 0, 'In a linear queue, dequeued front space cannot be reused, eventually causing a false overflow; a circular queue wraps around to reuse that freed space.', 'intermediate'),
('education', 'gate-cse/dsa', 'stacks-queues', 'A priority queue, where elements are served based on priority rather than arrival order, is most commonly implemented using a:', '["Heap", "Simple array with no ordering", "Singly linked list only", "Hash table"]', 0, 'A heap (typically a binary heap) efficiently supports the insert and extract-highest-priority operations a priority queue needs, both in O(log n) time.', 'intermediate'),
('education', 'gate-cse/dsa', 'trees', 'In a Binary Search Tree, for any given node, all values in its left subtree are:', '["Less than the node''s value", "Greater than the node''s value", "Equal to the node''s value", "Unrelated to the node''s value"]', 0, 'The BST property requires the left subtree of any node to contain only smaller values, and the right subtree only larger values.', 'beginner'),
('education', 'gate-cse/dsa', 'trees', 'The time complexity of a search operation in a balanced Binary Search Tree is:', '["O(log n)", "O(n)", "O(1)", "O(n log n)"]', 0, 'A balanced BST has height O(log n), so search (which follows a root-to-leaf path) takes O(log n) time.', 'beginner'),
('education', 'gate-cse/dsa', 'trees', 'An AVL tree maintains balance by ensuring that, for every node, the height difference between its left and right subtrees is:', '["At most 1", "Exactly 0", "At most 2", "Unrestricted"]', 0, 'An AVL tree is a self-balancing BST that enforces a balance factor (height difference) of at most 1 at every node, guaranteeing O(log n) height.', 'intermediate'),
('education', 'gate-cse/dsa', 'trees', 'An in-order traversal of a Binary Search Tree visits nodes in which order?', '["Sorted (ascending) order", "Sorted (descending) order", "Random order", "Level-by-level order"]', 0, 'In-order traversal (left, root, right) of a BST visits nodes in ascending sorted order, a direct consequence of the BST property.', 'intermediate'),
('education', 'gate-cse/dsa', 'trees', 'A heap is typically implemented using which underlying data structure?', '["An array (representing a complete binary tree)", "A doubly linked list", "A hash table", "A graph adjacency list"]', 0, 'Because a heap is always a complete binary tree, it can be efficiently represented in a simple array using index arithmetic to locate parent/child nodes.', 'intermediate'),
('education', 'gate-cse/dsa', 'graphs', 'Breadth-First Search (BFS) traversal of a graph uses which underlying data structure?', '["Queue", "Stack", "Priority queue only", "Hash table"]', 0, 'BFS explores level by level, using a queue (FIFO) to process nodes in the order they are discovered.', 'beginner'),
('education', 'gate-cse/dsa', 'graphs', 'Depth-First Search (DFS) traversal of a graph is most naturally implemented using:', '["A stack (or recursion, which uses the call stack)", "A queue", "A priority queue", "A doubly linked list"]', 0, 'DFS explores as far as possible along a branch before backtracking, which is naturally implemented with a stack or, equivalently, recursion.', 'beginner'),
('education', 'gate-cse/dsa', 'graphs', 'Dijkstra''s Algorithm finds the shortest path from a single source to all other vertices in a graph, under the constraint that:', '["All edge weights are non-negative", "The graph must be a tree", "All edge weights must be equal", "The graph must be directed acyclic"]', 0, 'Dijkstra''s Algorithm requires non-negative edge weights; negative weights can cause it to produce incorrect shortest-path results.', 'intermediate'),
('education', 'gate-cse/dsa', 'graphs', 'Using a binary heap, the time complexity of Dijkstra''s Algorithm on a graph with V vertices and E edges is:', '["O((V+E) log V)", "O(V^2)", "O(E log E) only", "O(V x E)"]', 0, 'With a binary heap priority queue, Dijkstra''s Algorithm runs in O((V+E) log V), a standard complexity result for this implementation.', 'intermediate'),
('education', 'gate-cse/dsa', 'graphs', 'Kruskal''s Algorithm builds a Minimum Spanning Tree using a greedy approach that primarily relies on:', '["Sorting edges by weight and using a Union-Find (disjoint set) structure to avoid cycles", "Breadth-first traversal from an arbitrary starting vertex", "Dynamic programming over all possible spanning trees", "Randomly selecting edges until a tree is formed"]', 0, 'Kruskal''s Algorithm greedily adds the smallest-weight edges (via sorting) while using a Union-Find structure to detect and avoid cycles, until a spanning tree is built.', 'intermediate'),
('education', 'gate-cse/dsa', 'sorting', 'The worst-case time complexity of Merge Sort is:', '["O(n log n)", "O(n^2)", "O(n)", "O(log n)"]', 0, 'Merge Sort consistently divides the array in half and merges, giving O(n log n) time in the best, average, and worst cases alike.', 'beginner'),
('education', 'gate-cse/dsa', 'sorting', 'The worst-case time complexity of Quick Sort is:', '["O(n^2)", "O(n log n)", "O(n)", "O(log n)"]', 0, 'Quick Sort''s worst case (e.g. a poorly chosen pivot on an already-sorted array) degrades to O(n^2), even though its average case is O(n log n).', 'intermediate'),
('education', 'gate-cse/dsa', 'sorting', 'Among common comparison-based sorting algorithms, which of the following is a stable sort?', '["Merge Sort", "Quick Sort", "Heap Sort", "Selection Sort"]', 0, 'Merge Sort preserves the relative order of equal elements (is stable), unlike the standard implementations of Quick Sort, Heap Sort, and Selection Sort.', 'intermediate'),
('education', 'gate-cse/dsa', 'sorting', 'The time complexity of binary search, used as a searching technique on sorted data, is:', '["O(log n)", "O(n)", "O(1)", "O(n log n)"]', 0, 'Binary search repeatedly halves the search interval, achieving O(log n) time on sorted data.', 'beginner'),
('education', 'gate-cse/dsa', 'sorting', 'The time complexity of Counting Sort, where n is the number of elements and k is the range of input values, is:', '["O(n + k)", "O(n log n)", "O(n^2)", "O(k log k)"]', 0, 'Counting Sort is a non-comparison-based sort that runs in O(n+k) time, efficient when k (the value range) is not significantly larger than n.', 'intermediate'),
('education', 'gate-cse/dsa', 'dynamic-programming', 'Dynamic programming is applicable to a problem when it exhibits:', '["Overlapping subproblems and optimal substructure", "Only overlapping subproblems, without optimal substructure", "Only optimal substructure, without overlapping subproblems", "Neither overlapping subproblems nor optimal substructure"]', 0, 'Dynamic programming techniques (memoization/tabulation) are effective precisely when a problem has both overlapping subproblems and optimal substructure.', 'beginner'),
('education', 'gate-cse/dsa', 'dynamic-programming', 'Memoization refers to which dynamic programming approach?', '["Top-down, storing results of subproblems to avoid recomputation", "Bottom-up, building a table from the smallest subproblems first", "A greedy approach with no memory of past results", "A purely recursive approach without any caching"]', 0, 'Memoization is the top-down DP technique: solve recursively, but cache (memoize) each subproblem''s result so it is never recomputed.', 'intermediate'),
('education', 'gate-cse/dsa', 'dynamic-programming', 'Using dynamic programming (memoization or tabulation), the time complexity to compute the nth Fibonacci number is:', '["O(n)", "O(2^n)", "O(n^2)", "O(log n)"]', 0, 'DP avoids the exponential O(2^n) of naive recursion by computing and storing each Fibonacci value exactly once, giving O(n) time.', 'intermediate'),
('education', 'gate-cse/dsa', 'dynamic-programming', 'The dynamic programming solution to the 0/1 Knapsack problem, with n items and capacity W, has time complexity:', '["O(n x W)", "O(n + W)", "O(2^n)", "O(n log W)"]', 0, 'The standard DP table for 0/1 Knapsack has dimensions n x W, and each cell is filled in constant time, giving O(nW) overall.', 'intermediate'),
('education', 'gate-cse/dsa', 'dynamic-programming', 'The dynamic programming solution for the Longest Common Subsequence (LCS) of two strings of length m and n has time complexity:', '["O(m x n)", "O(m + n)", "O(m^2 + n^2)", "O(2^(m+n))"]', 0, 'The standard LCS DP table has dimensions (m+1) x (n+1), with each cell computed in constant time, giving O(mn) overall.', 'intermediate')
ON CONFLICT (academy_slug, technology_slug, section_slug, question) DO NOTHING;
