-- ============================================================
-- CompTIA Security+ (SY0-701) — Seed Data: Paper 8
-- New content, distinct topics from Papers 1-7 — no repeated scenarios.
-- Topic list checked directly against the actual question text of Papers
-- 1-7 (grepped from the files) before writing.
--
-- Domain-question-count breakdown, confirmed BEFORE writing any questions
-- (per standing process, adopted after multiple prior papers undercounted
-- a domain at the topic-list-finalization or write stage): General 2 +
-- Threats 4 + Architecture 4 + Operations 6 + Program Management 4 = 20,
-- confirmed.
--   General (2): 5-factor authentication taxonomy (know/have/are/
--     location/behavior), due diligence vs. due care.
--   Threats (4): worm vs. virus, Trojan horse, race condition (TOCTOU),
--     malicious USB/HID keystroke-injection attack.
--   Architecture (4): serverless security considerations, VM escape/
--     hypervisor attack surface, TPM/secure enclave, WPA2 vs. WPA3.
--   Operations (6): emergency/out-of-band patching, pentest rules of
--     engagement, incident severity classification, SOC analyst tiers,
--     vulnerability remediation SLA timelines, static vs. dynamic malware
--     analysis.
--   Program Management (4): first-party vs. third-party cyber insurance,
--     right-to-audit clause, SOX, asset management lifecycle.
--
-- IDs were generated via scripts/fill-seed-uuids.mjs, which replaces every
-- distinct placeholder token with a fresh, real UUID (consistently across
-- every occurrence) — this file has already had that script run against
-- it; the UUIDs below are real. Cross-checked against every other seed
-- file in the repo for zero collisions before finalizing, plus the
-- distractor-language sanity scan and a manual re-read of every answer key
-- against its option text. The question_papers ARRAY[...]::TEXT[] literal
-- and every option token were manually re-read once before running the
-- fill script.
-- Run this AFTER docs/question-bank-schema.sql.
-- ============================================================

INSERT INTO question_papers (id, slug, title, exam_type, focus_tags, question_count, difficulty, is_premium, sort_order, time_limit_minutes)
VALUES ('3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 'secplus-practice-8', 'CompTIA Security+ (SY0-701) Practice Paper 8', 'comptia-sec-plus', ARRAY['Authentication Factors', 'Due Diligence', 'Worm vs Virus', 'TOCTOU', 'TPM', 'WPA3', 'Rules of Engagement', 'SOC Tiers', 'SOX']::TEXT[], 20, 'standard', true, 8, 30);

-- ── Domain: General Security Concepts (12% — 2 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('2bc5414a-4d55-48d1-8f55-1ce12d696c4e', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 1, 'A company''s login system can verify identity using a password (something the user knows), a hardware security key (something the user has), a fingerprint scan (something the user is), the user''s current GPS location, and their typical typing rhythm/cadence. How many distinct categories of authentication factors does this represent, and what are they called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ce6a8b97-d19b-4c08-aefa-f7c0831308ba', '2bc5414a-4d55-48d1-8f55-1ce12d696c4e', 0, 'Five distinct factor categories — knowledge (something you know, like a password), possession (something you have, like a hardware key), inherence (something you are, like a fingerprint or other biometric), location (somewhere you are, like a verified GPS position or network origin), and behavior (something you do, like typing rhythm or gait) — MFA (covered generally in a prior paper) combines factors from at least two DIFFERENT categories, not simply two different examples from the SAME category (e.g., a password plus a PIN are both knowledge factors, so combining them does not actually constitute true multi-factor authentication).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d9801e6c-230a-4c20-8a82-6ed45dfcc1ad', '2bc5414a-4d55-48d1-8f55-1ce12d696c4e', 1, 'Two distinct factor categories, since knowledge, possession, inherence, location, and behavior are all considered the exact same single authentication factor category.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a5e0ae62-cac6-48ef-9411-4e1ab1fa417d', '2bc5414a-4d55-48d1-8f55-1ce12d696c4e', 2, 'A gap analysis, since gap analyses are specifically defined as the five-category taxonomy of authentication factors including knowledge, possession, inherence, location, and behavior.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5e6334bc-45ff-45fe-8aed-d50f31b0058a', '2bc5414a-4d55-48d1-8f55-1ce12d696c4e', 3, 'Authentication factors cannot meaningfully be grouped into any distinct categories; every authentication method is functionally identical regardless of its underlying mechanism.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('2bc5414a-4d55-48d1-8f55-1ce12d696c4e', 'ce6a8b97-d19b-4c08-aefa-f7c0831308ba', 'The five-category authentication factor taxonomy directly refines the general MFA concept (covered generally in a prior paper, using the password-plus-authenticator-code example) with the full, formal classification: knowledge (something known and reproducible mentally, like a password or PIN — the weakest category on its own, since knowledge can be phished, guessed, or shared), possession (something physically held, like a hardware security key or a phone receiving an OTP — defeated if the physical item is stolen, but not simply guessable), inherence (something biologically inherent to the person, like a fingerprint, iris scan, or facial recognition — genuinely hard to replicate but also genuinely hard to change if ever compromised, unlike a password), location (somewhere the user genuinely is, verified via GPS or network origin — used as a supplementary, contextual factor more often than a sole one), and behavior (something the user characteristically DOES, like typing rhythm, mouse movement patterns, or gait — a newer, continuous-authentication-oriented category). The genuinely important, directly testable nuance is that true multi-factor authentication requires factors from at least TWO DIFFERENT categories — a password plus a separate PIN are both knowledge factors, so despite requiring two separate pieces of information, that combination does NOT constitute genuine MFA the way a password (knowledge) plus a hardware key (possession) does.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('334d4af7-a35f-4794-a1e5-265188b6cec5', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 2, 'A company''s security team performs a genuinely thorough, reasonable investigation before selecting a new cloud vendor — reviewing the vendor''s security certifications, requesting audit reports, and assessing their track record — BEFORE signing the contract. Separately, once the vendor relationship is active, the company continues applying reasonable, ongoing security practices (patching, monitoring, access review) to the systems and data involved in that relationship. What are these two distinct concepts called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0e4a0430-0910-4a58-b38a-f05cc9f95fce', '334d4af7-a35f-4794-a1e5-265188b6cec5', 0, 'Due diligence (the reasonable INVESTIGATION performed BEFORE a decision or action — here, thoroughly researching the vendor before signing) and due care (the ongoing, ROUTINE, reasonable maintenance of security practices AFTER a decision has been made — here, continuing to patch, monitor, and review access on an ongoing basis); both terms describe a legally and practically meaningful standard of "reasonable" behavior, but due diligence is specifically about pre-decision investigation, while due care is about ongoing, sustained responsible practice afterward.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c540e26f-9488-46d6-ad32-f8f8316b4f61', '334d4af7-a35f-4794-a1e5-265188b6cec5', 1, 'Due care is specifically the pre-decision investigation performed before signing a contract, while due diligence is the ongoing, routine maintenance of security practices afterward — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7bcc2f71-4ce6-4ac5-b209-fb9aa75bdf82', '334d4af7-a35f-4794-a1e5-265188b6cec5', 2, 'Due diligence and due care are two different names for the exact same concept, with no meaningful distinction in timing or focus between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('20fb3c6b-c99c-4730-a724-ffce96624b47', '334d4af7-a35f-4794-a1e5-265188b6cec5', 3, 'Neither due diligence nor due care carries any real legal or practical significance; these are purely informal terms with no bearing on an organization''s actual responsibility or liability.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('334d4af7-a35f-4794-a1e5-265188b6cec5', '0e4a0430-0910-4a58-b38a-f05cc9f95fce', 'Due diligence and due care are genuinely distinct in TIMING and FOCUS, a directly testable distinction: due diligence is the reasonable INVESTIGATION performed BEFORE making a decision or taking an action — here, researching a prospective vendor''s security posture before signing, directly connecting to vendor risk management (covered in a prior paper) as one concrete application of due diligence — while due care is the ongoing, ROUTINE application of reasonable security practices AFTER that decision has been made and the relationship is active, continuing indefinitely rather than being a one-time, pre-decision check. Both terms carry genuine legal and practical significance — in many regulatory and liability contexts, an organization''s failure to exercise adequate due diligence (failing to reasonably investigate before a decision) or due care (failing to maintain reasonable ongoing practices afterward) can be directly relevant to determining fault or liability after an incident occurs, which is exactly why both are real, standard, and meaningful governance concepts rather than purely informal or legally inconsequential terms.');

-- ── Domain: Threats, Vulnerabilities & Mitigations (22% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('3dc80833-8e27-452a-83a5-8c56dbb66ee9', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 3, 'One piece of malware requires a user to open an infected file or attachment before it can execute and spread further, effectively "riding along" with that host file. A different piece of malware spreads entirely on its own across a network, actively seeking out and exploiting vulnerable systems, with no user action or host file required at all. What are these two distinct malware categories called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9a48dd22-3c56-496b-8ffc-f5a4dbba8ce5', '3dc80833-8e27-452a-83a5-8c56dbb66ee9', 0, 'A virus (requires a host file and typically some user action, like opening an infected attachment or running an infected program, to actually execute and begin spreading — it cannot propagate entirely on its own) and a worm (self-replicating and self-propagating across a network entirely independently, actively scanning for and exploiting vulnerable systems with NO user action and no host file required — making worms generally capable of spreading dramatically faster and more widely than a virus, since they don''t depend on a person unknowingly triggering them).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4139b0b4-93be-4418-b98b-a5ddaf038489', '3dc80833-8e27-452a-83a5-8c56dbb66ee9', 1, 'A worm is the malware requiring a host file and user action to spread, while a virus is the malware that spreads entirely on its own with no user action required — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b91ee518-e004-4335-8a28-34cef2fcb31f', '3dc80833-8e27-452a-83a5-8c56dbb66ee9', 2, 'Virus and worm are two different names for the exact same malware category, with no meaningful distinction in propagation mechanism between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0be05bc2-b760-4253-bed6-37efb689711d', '3dc80833-8e27-452a-83a5-8c56dbb66ee9', 3, 'Malware can never propagate across a network without some form of direct user action triggering each individual infection.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('3dc80833-8e27-452a-83a5-8c56dbb66ee9', '9a48dd22-3c56-496b-8ffc-f5a4dbba8ce5', 'The virus-versus-worm distinction is a foundational, frequently-tested malware classification specifically hinging on PROPAGATION MECHANISM and dependency on user action: a virus needs a host — it attaches to or embeds within a legitimate file or program, and generally requires a user to actually open, run, or otherwise trigger that infected host before the virus can execute and begin spreading further, meaning its spread rate is naturally limited by how quickly unsuspecting users trigger new infections. A worm, by contrast, is fully self-contained and self-propagating — it actively scans a network for other vulnerable, exploitable systems and spreads to them directly, entirely without any user needing to open a file or take any action at all, which is exactly why worms have historically been capable of spreading across networks explosively fast (a well-documented, historically significant characteristic) compared to virus-based malware that depends on human behavior to keep propagating. This is a genuinely important, real distinction — malware absolutely CAN and does spread with zero user interaction, contrary to the last distractor, which is precisely the defining characteristic that makes worm-based malware categorically more dangerous from a pure propagation-speed standpoint.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('4d814d13-9a1c-4edd-9432-8475ab5385e6', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 4, 'An employee downloads what appears to be a legitimate, useful free utility application from a website, and after installing it, discovers the application also secretly installed a hidden backdoor giving an attacker remote access to the machine — the malicious functionality was disguised inside something that looked entirely legitimate and desirable to install. What is this specific malware category called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d123d11a-a6a4-4940-8e40-210d3700ec6b', '4d814d13-9a1c-4edd-9432-8475ab5385e6', 0, 'A Trojan horse (or Trojan) — malware disguised as, or bundled within, seemingly legitimate and desirable software, relying on the victim VOLUNTARILY installing it because it appears genuinely useful or wanted, rather than exploiting a technical vulnerability to force its way onto a system the way a worm does, or requiring the victim to merely open an already-infected file the way a virus does; the deception here is specifically about the software''s APPARENT PURPOSE and legitimacy, not about hiding within an already-trusted file.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a89007cb-e029-45d1-b629-d96291b42bfa', '4d814d13-9a1c-4edd-9432-8475ab5385e6', 1, 'A worm, since worms are specifically defined as malware disguised as legitimate, desirable software that a victim voluntarily chooses to install.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0251ae62-4f86-423f-87fc-203184a8ce0a', '4d814d13-9a1c-4edd-9432-8475ab5385e6', 2, 'A rootkit, since rootkits are specifically defined as malware disguised as legitimate software that a victim voluntarily downloads and installs believing it to be genuinely useful.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2a7bcd7d-1615-4220-b577-119bbfc54fca', '4d814d13-9a1c-4edd-9432-8475ab5385e6', 3, 'Malware disguised as legitimate, desirable software is not a real or meaningful attack pattern, since users would always recognize and avoid genuinely malicious software regardless of its apparent purpose.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('4d814d13-9a1c-4edd-9432-8475ab5385e6', 'd123d11a-a6a4-4940-8e40-210d3700ec6b', 'A Trojan horse is specifically distinguished by relying on DECEPTION about the software''s apparent PURPOSE — the victim genuinely believes they''re installing something legitimately useful or desirable (a free utility, a cracked version of paid software, a seemingly helpful browser extension), and voluntarily installs it themselves, at which point the hidden malicious functionality (a backdoor, spyware, covered in a prior paper, or other payload) activates alongside or instead of the advertised functionality. This is genuinely different in mechanism from a worm (covered earlier this paper, which exploits a technical VULNERABILITY to spread with no user action or deception about apparent purpose involved at all) and from a virus (covered earlier this paper, which requires a user to open an already-infected file, but doesn''t necessarily rely on the file being deceptively DISGUISED as something else entirely) — a rootkit (covered in a prior paper) is specifically defined by its OS-level CONCEALMENT mechanism after infection, a different characteristic from how the initial infection is deceptively delivered. This is a real, extremely common, and historically significant attack pattern specifically BECAUSE users genuinely can be and regularly are deceived by sufficiently convincing disguises — dismissing it as unrealistic ignores a large share of real-world malware infections.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('2ae4c36d-115b-4b8b-bcae-85f74c74013d', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 5, 'A file-upload application CHECKS whether a user is authorized to overwrite a specific file, and then, in a separate step slightly afterward, actually performs the overwrite. An attacker exploits the small time gap between that check and the actual action by rapidly submitting a different, unauthorized file reference in between — so the authorization check passes for one file, but the actual overwrite happens on a different, unauthorized file. What is this specific vulnerability class called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('665f0898-41ca-4a28-9e57-b3f186155e4a', '2ae4c36d-115b-4b8b-bcae-85f74c74013d', 0, 'A race condition (specifically a Time-Of-Check to Time-Of-Use, or TOCTOU, vulnerability) — occurs when there is a meaningful time gap between when a system CHECKS a condition (like authorization) and when it actually ACTS on that check, and an attacker exploits that gap by changing the relevant state in between, so the action that ultimately executes no longer matches what was actually validated; the fix generally requires making the check-and-act sequence effectively ATOMIC (an indivisible, uninterruptible single operation) so no exploitable gap exists for an attacker to act within.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('58887a18-785c-47c8-b422-0658eb83cb87', '2ae4c36d-115b-4b8b-bcae-85f74c74013d', 1, 'A Trojan horse, since Trojan horses are specifically defined as exploiting a time gap between an authorization check and the actual action a system performs.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c5d343f8-a57c-46ef-a6f1-1ada41b60d7f', '2ae4c36d-115b-4b8b-bcae-85f74c74013d', 2, 'Directory traversal, since directory traversal is specifically defined as exploiting the time gap between when a system checks authorization and when it actually performs the corresponding action.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b263eb0a-a141-48b3-a17f-48c84c6f0a95', '2ae4c36d-115b-4b8b-bcae-85f74c74013d', 3, 'A meaningful time gap between an authorization check and the corresponding action can never actually exist in real software, making this described vulnerability class a technical impossibility.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('2ae4c36d-115b-4b8b-bcae-85f74c74013d', '665f0898-41ca-4a28-9e57-b3f186155e4a', 'A TOCTOU race condition is specifically defined by exploiting a genuine, real TIMING gap between two logically-related steps that a developer assumed would always happen together as one uninterrupted unit, but which the actual implementation performs as two SEPARATE steps with real time passing between them — an attacker who can act (or cause a relevant state change) DURING that gap can cause the eventually-executed action to no longer match what was actually checked and authorized, a genuinely subtle and easy-to-accidentally-introduce class of bug distinct from more directly input-driven vulnerabilities like directory traversal (covered in a prior paper, which exploits unsanitized PATH input rather than a timing gap) or a Trojan horse (covered earlier this paper, an entirely different, deception-based delivery mechanism, not a timing/logic flaw). The standard mitigation is making the check-and-act sequence genuinely ATOMIC — using a locking mechanism or a single, indivisible operation that combines the check and the action so no attacker-exploitable window exists between them at all. This kind of timing gap is a real, well-documented, and genuinely subtle vulnerability class that has caused real security incidents — it is emphatically not a technical impossibility, contrary to the last distractor.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('7086506d-8226-4919-8fd5-674926da0e1a', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 6, 'A penetration tester leaves a small, inexpensive USB device plugged into an unlocked, unattended workstation during an authorized physical-access engagement. The moment it''s plugged in, the target computer''s operating system recognizes it as a standard USB keyboard, and the device then automatically and rapidly "types" a pre-programmed sequence of keystrokes — opening a command prompt and downloading malware — without the device ever appearing as removable storage or requiring the victim to open any file at all. What is this specific attack technique called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('15d14d73-f64b-4419-9670-f41024c809b9', '7086506d-8226-4919-8fd5-674926da0e1a', 0, 'An HID (Human Interface Device) attack / keystroke-injection attack — a small device (physically resembling an ordinary USB flash drive) is programmed to identify itself to the target computer as a KEYBOARD rather than storage media, and then automatically "types" a pre-programmed, malicious sequence of keystrokes the instant it''s plugged in; because operating systems generally trust HID keyboard input implicitly with no separate file-opening or execution step required, and typically don''t apply the same removable-media scrutiny they might to a device identifying as storage, this technique can execute malicious commands essentially instantly upon connection.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bd104e1a-f989-4b88-a54f-2809865289e3', '7086506d-8226-4919-8fd5-674926da0e1a', 1, 'Baiting, since baiting is specifically defined as a device that identifies itself as a keyboard and automatically types pre-programmed malicious commands the instant it''s plugged in.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('98ba24e2-b02b-47cb-a687-0f8df4c0e0c3', '7086506d-8226-4919-8fd5-674926da0e1a', 2, 'A logic bomb, since logic bombs are specifically defined as a physical USB device that identifies itself as a keyboard and immediately types a pre-programmed malicious keystroke sequence.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8f5beb45-c3c1-46a5-94fb-826c7a4235cb', '7086506d-8226-4919-8fd5-674926da0e1a', 3, 'A USB device can never be programmed to identify itself as a keyboard or automatically inject keystrokes; this described attack mechanism is not technically achievable.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('7086506d-8226-4919-8fd5-674926da0e1a', '15d14d73-f64b-4419-9670-f41024c809b9', 'An HID/keystroke-injection attack specifically exploits the fact that most operating systems inherently trust a device that identifies itself via the standard USB Human Interface Device protocol as a genuine keyboard, with no additional prompt, file-open step, or execution confirmation required — the malicious device simply "types" its pre-programmed payload the instant it''s connected, exactly as if a person were physically typing at the keyboard, meaning no separate action (opening a file, running a program, clicking anything) is needed for the attack to execute, and it doesn''t appear as removable storage that antivirus or other file-scanning tools might otherwise inspect. This is a genuinely distinct MECHANISM from baiting (covered in a prior paper, which specifically describes the SOCIAL ENGINEERING tactic of luring a curious victim into voluntarily plugging in a device found somewhere — baiting explains HOW the device might get physically connected, while an HID attack describes WHAT the device technically does once it''s connected; the two concepts are genuinely complementary rather than the same thing, since an HID-attack device could be delivered via baiting, direct physical access, or other means). A logic bomb (covered in a prior paper) is defined by DELAYED, condition-triggered execution, not by a device''s HID protocol impersonation — this is a real, well-documented, and readily achievable attack technique using genuinely available, inexpensive hardware, not a technical impossibility.');

-- ── Domain: Security Architecture (18% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('70eb0a83-22b4-407d-8126-7dc26ea620fa', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 7, 'A company migrates an application to a serverless architecture (individual functions triggered by events, with no persistent server for the company to directly manage or patch). A security architect points out that while the underlying SERVER infrastructure is now the cloud provider''s responsibility, several NEW security considerations specifically emerge from the serverless model itself. What are these serverless-specific security considerations?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('89e1cdc4-549d-4509-9d42-833df88d11f1', '70eb0a83-22b4-407d-8126-7dc26ea620fa', 0, 'Function-level permission scoping (each individual function should have its own narrowly-scoped permissions specific to what IT needs, rather than one broad, shared permission set across every function — directly applying least privilege, covered in a prior paper, at a more granular level), securing the event sources that can actually TRIGGER a function (since an attacker who can inject or manipulate an event source can effectively trigger unauthorized function execution), and the greater difficulty of traditional host-based monitoring/EDR (covered in a prior paper) given functions'' genuinely ephemeral, short-lived execution — a real, distinct security profile shift from traditional server-based architecture, not simply an unchanged security posture handed off entirely to the provider.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b7ddae14-785b-48d7-8bac-2f72203c5fd2', '70eb0a83-22b4-407d-8126-7dc26ea620fa', 1, 'Serverless architecture eliminates every security consideration entirely, since the cloud provider''s full management of the underlying infrastructure means the customer bears absolutely no security responsibility of any kind.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d57e4ea7-b045-4c03-8043-8df8f6db0060', '70eb0a83-22b4-407d-8126-7dc26ea620fa', 2, 'Serverless functions should always share one single, broad permission set across every function in an application, since granular, function-specific permission scoping provides no meaningful security benefit.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ff6e5ec0-5f65-4b76-a128-587acfd0925c', '70eb0a83-22b4-407d-8126-7dc26ea620fa', 3, 'Serverless architecture and traditional server-based architecture present functionally identical security considerations, with no meaningful difference in appropriate security practices between them.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('70eb0a83-22b4-407d-8126-7dc26ea620fa', '89e1cdc4-549d-4509-9d42-833df88d11f1', 'Serverless computing genuinely shifts the security responsibility boundary (directly connecting to the cloud shared responsibility model covered generally in a prior paper) — the cloud provider now handles the underlying server OS, patching, and physical infrastructure entirely, which IS a real reduction in the customer''s traditional server-hardening burden — but this does NOT mean serverless architecture eliminates security considerations altogether; it specifically shifts WHERE the remaining, genuinely real considerations sit. Function-level permission scoping matters because a single, broad, shared permission set across every function in an application means a vulnerability or compromise in ANY ONE function could potentially be leveraged with the FULL combined permission set of every function, rather than being contained to just what that specific function actually needed — a direct, more granular application of least privilege. Securing event sources matters because in an event-driven serverless model, whatever can legitimately trigger a function execution becomes a genuinely real attack surface of its own, distinct from a traditional server''s network-listening ports. And functions'' genuinely short-lived, ephemeral execution lifecycle makes traditional, continuously-running host-based monitoring tools (EDR, covered in a prior paper) meaningfully harder to apply in the same way, requiring different, serverless-aware monitoring approaches. This is a real, genuinely distinct security profile shift, not an unchanged posture or a case where granular scoping provides no value.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('923aa232-4a51-4371-bb2c-cb6055747262', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 8, 'A company runs multiple virtual machines from DIFFERENT customers on the same shared physical host, relying on the hypervisor to keep each VM''s memory, storage, and processes fully isolated from every other VM on that host. A security researcher discovers a flaw allowing malicious code running INSIDE one VM to break out of that VM''s isolation boundary and directly access the underlying host system or OTHER VMs sharing the same hardware. What is this specific attack called, and why is it considered particularly severe?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('91872c90-9bc0-4a0e-bfc2-810a1c627095', '923aa232-4a51-4371-bb2c-cb6055747262', 0, 'A VM escape (or hypervisor escape) — malicious code running inside a guest VM breaks out of that VM''s isolation boundary and gains unauthorized access to the underlying HOST system or to OTHER VMs sharing the same physical hardware; this is considered particularly severe specifically because the entire premise of running multiple tenants'' workloads on shared physical hardware depends on the hypervisor''s isolation boundary genuinely holding — a successful VM escape potentially compromises every OTHER tenant sharing that same host, not just the originally-compromised VM, a fundamentally different and larger blast radius than a compromise contained within one VM.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5034b13a-e59d-402b-8817-6eb5d592520a', '923aa232-4a51-4371-bb2c-cb6055747262', 1, 'A container escape, since container escapes are specifically defined as malicious code breaking out of a hypervisor-managed virtual machine''s isolation boundary to access other VMs on the same host.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('89baf3c1-d735-4895-97d6-e8cab68ad28e', '923aa232-4a51-4371-bb2c-cb6055747262', 2, 'A race condition, since race conditions are specifically defined as malicious code breaking out of a VM''s hypervisor-enforced isolation boundary to access other tenants'' VMs on shared hardware.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f59ba9bd-c75e-40e5-94ae-0db9a42f3731', '923aa232-4a51-4371-bb2c-cb6055747262', 3, 'A hypervisor''s isolation between virtual machines running on the same physical host can never actually be broken or bypassed under any circumstance.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('923aa232-4a51-4371-bb2c-cb6055747262', '91872c90-9bc0-4a0e-bfc2-810a1c627095', 'A VM escape is specifically defined by breaking THROUGH the hypervisor''s isolation boundary itself — the mechanism the entire multi-tenant virtualization model fundamentally relies on to keep genuinely separate customers'' workloads from ever being able to touch each other despite physically sharing the same underlying hardware. This directly connects to and extends the cloud shared responsibility model and containerization concepts (both covered generally in prior papers) — containers (covered in a prior paper) share the same host OS KERNEL by design, generally considered a somewhat WEAKER isolation boundary than a full VM''s separate kernel (a nuance explicitly noted when containers were originally covered) — meaning a container escape is a genuinely related but architecturally DISTINCT concept from a VM escape, which breaks a hypervisor boundary specifically protecting genuinely separate operating system instances, not a shared-kernel boundary. The severity of a VM escape is specifically amplified by the multi-tenant blast radius: rather than a compromise being contained to the one VM that was actually attacked, a successful hypervisor escape potentially exposes every OTHER tenant''s VM sharing that same physical host to compromise as well, a fundamentally larger and more consequential impact than a single-VM compromise — this is a real, well-documented (if genuinely rare given how heavily hypervisor security is scrutinized), and historically demonstrated vulnerability class, not a theoretically impossible one.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('b348b9f3-6447-4e16-809c-079b44aa6d44', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 9, 'A company wants a hardware-based root of trust built directly into a device''s motherboard, specifically capable of securely generating and storing cryptographic keys, and verifying the integrity of the boot process (connecting to the secure/measured boot concept covered in a prior paper) — with those cryptographic operations happening in dedicated, tamper-resistant hardware rather than in general-purpose software that could potentially be compromised. What is this specific hardware component called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c50d47e3-0200-45ef-84f7-d138292d56ac', 'b348b9f3-6447-4e16-809c-079b44aa6d44', 0, 'A TPM (Trusted Platform Module) — a dedicated, tamper-resistant hardware chip (or an equivalent firmware-based implementation) built directly into a device, providing a genuine hardware root of trust specifically for securely generating and storing cryptographic keys (in a way that''s meaningfully harder to extract than keys stored purely in software) and supporting the secure/measured boot process (covered in a prior paper) by performing its cryptographic integrity-verification operations in dedicated hardware, rather than relying entirely on general-purpose software that could itself potentially be tampered with or compromised.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d7cb7c72-6905-4222-a8d3-31e1ff4df924', 'b348b9f3-6447-4e16-809c-079b44aa6d44', 1, 'A write blocker, since write blockers are specifically defined as a hardware-based root of trust for generating cryptographic keys and verifying boot process integrity.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('814bd1b8-89be-456a-8b75-79412e838f4c', 'b348b9f3-6447-4e16-809c-079b44aa6d44', 2, 'A CASB, since CASBs are specifically defined as a dedicated, tamper-resistant hardware chip built into a device''s motherboard for cryptographic key generation and boot-process verification.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e0045eea-2ef2-40f1-862c-3857002018d5', 'b348b9f3-6447-4e16-809c-079b44aa6d44', 3, 'No dedicated hardware component exists for cryptographic key generation or boot-process integrity verification; these operations can only ever be performed in general-purpose software.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('b348b9f3-6447-4e16-809c-079b44aa6d44', 'c50d47e3-0200-45ef-84f7-d138292d56ac', 'A TPM specifically provides a genuine HARDWARE root of trust — a dedicated, physically tamper-resistant chip performing cryptographic operations (key generation, secure key storage, and cryptographic measurement/attestation of boot-chain components) in isolated hardware, meaningfully harder for malicious software to extract keys from or tamper with compared to equivalent operations performed purely in general-purpose software running on the same general CPU an attacker might otherwise compromise. This directly underpins and enables the secure/measured boot process (covered in a prior paper) — the TPM is frequently the actual hardware component performing or anchoring the cryptographic measurements verifying each boot-chain component against a trusted baseline before allowing it to execute, and TPMs are also commonly used to securely store disk-encryption keys (connecting to full-disk encryption, covered in a prior paper) in a way that ties decryption specifically to that exact physical device''s verified, untampered boot state. A write blocker (covered in a prior paper) is an entirely unrelated forensic evidence-preservation tool, and a CASB (covered in a prior paper) is a cloud-security-policy-enforcement architecture concept — neither is a hardware cryptographic root-of-trust component. TPMs are real, standard, and increasingly widely deployed hardware components (built into most modern computers), not a purely theoretical, software-only alternative.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('80bd0fba-884f-4a2f-b051-34247fb2c036', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 10, 'A company is deciding which wireless security protocol to require for its corporate Wi-Fi network. WPA2 has been the long-standing standard, but WPA3 is newer. What are the meaningful security improvements WPA3 provides over WPA2, and why do these improvements matter?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('69bdbabb-817e-4256-a159-e2b661752291', '80bd0fba-884f-4a2f-b051-34247fb2c036', 0, 'WPA3 provides meaningfully stronger protection against offline password-guessing attacks against the network''s pre-shared key (via a more robust handshake specifically resistant to the kind of offline dictionary/brute-force attack that a weaker WPA2 handshake was genuinely vulnerable to), and adds individualized data encryption for each connected client on open/public networks (meaningfully limiting one connected user''s ability to passively eavesdrop on another user''s traffic on the same open network, a real gap WPA2 (and especially fully open, unencrypted Wi-Fi) did not adequately address) — genuine, meaningful security improvements over WPA2, not merely a version-number change with no substantive difference.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a4109887-71de-4832-beff-1cd593beb974', '80bd0fba-884f-4a2f-b051-34247fb2c036', 1, 'WPA2 provides meaningfully stronger protection against offline password-guessing attacks and individualized per-client encryption on open networks than WPA3 does, making WPA2 the objectively more secure choice in every respect.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6dfa7d9f-762b-42c2-81b6-2457f9be03a5', '80bd0fba-884f-4a2f-b051-34247fb2c036', 2, 'WPA2 and WPA3 are functionally and cryptographically identical protocols under two different marketing names, with no meaningful security improvement in either direction.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('44ff85b1-f655-486e-9b15-f28d556d3e31', '80bd0fba-884f-4a2f-b051-34247fb2c036', 3, 'Wireless network security protocols have no meaningful relationship to protecting against password-guessing attacks or eavesdropping between users on the same network.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('80bd0fba-884f-4a2f-b051-34247fb2c036', '69bdbabb-817e-4256-a159-e2b661752291', 'WPA3 represents genuine, substantive security improvements over WPA2, not merely an incremented version number — the most significant is a more robust key-establishment handshake specifically designed to resist OFFLINE password-guessing attacks against the network''s pre-shared key: WPA2''s handshake had a well-documented weakness allowing an attacker who captured the handshake to attempt guessing the password entirely offline, at whatever speed their own hardware allowed, with no way for the network to detect or rate-limit those guessing attempts at all — WPA3''s handshake meaningfully closes this gap, forcing an attacker into a much slower, detectable, ONLINE guessing process instead. WPA3 also adds individualized encryption for each connected client specifically on OPEN, password-less networks (like many public Wi-Fi hotspots) — under WPA2 (and certainly under fully open Wi-Fi with no password at all), traffic on an open network could potentially be eavesdropped on by another user connected to that SAME network, a real, practical privacy and security gap WPA3 specifically addresses by giving each client its own unique encryption even without a shared network password. This directly extends the general secure-protocol-selection principle (covered in a prior paper, for wired protocols like Telnet/SSH and SNMPv1/v3) into the wireless domain — genuinely choosing a newer, more secure protocol VERSION over an older one with known, real weaknesses, not a case of two functionally identical options.');

-- ── Domain: Security Operations (28% — 6 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('6c3bb75d-0d6c-49a1-bc27-99b670336011', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 11, 'A critical, actively-exploited vulnerability is publicly disclosed in software the company runs in production, and the vendor releases a patch the same day. The company''s NORMAL patch management process (covered generally in a prior paper) calls for testing every patch in a staging environment for two weeks before any production rollout — but waiting two full weeks while a known, actively-exploited vulnerability remains unpatched in production is clearly an unacceptable risk in this specific case. What process addresses deploying a patch faster than the normal cadence when the situation genuinely warrants it?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('99b5caaf-a333-4c93-ade3-0eaa00db09be', '6c3bb75d-0d6c-49a1-bc27-99b670336011', 0, 'Emergency (or out-of-band) patching — a deliberately expedited patch deployment process, used specifically when a vulnerability''s severity and active-exploitation status genuinely justify bypassing (or significantly compressing) the normal testing cadence, accepting a real, explicitly acknowledged trade-off of somewhat higher regression risk (since normal testing time is compressed or skipped) in exchange for closing a genuinely severe, actively-exploited security gap faster; this should be a deliberate, exception-based process reserved for genuinely warranted situations, not the organization''s standard operating cadence for every routine patch.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('44c1402e-e6e1-462c-8ff7-4536df3df8c7', '6c3bb75d-0d6c-49a1-bc27-99b670336011', 1, 'The normal, standard two-week testing cadence should always be followed without exception in every situation, regardless of a vulnerability''s severity or active-exploitation status.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('db31b2c0-473d-48f3-a8c0-425625b739c1', '6c3bb75d-0d6c-49a1-bc27-99b670336011', 2, 'Emergency patching and the organization''s normal, routine patch testing cadence are the exact same process, with no meaningful distinction in urgency, testing rigor, or risk trade-off between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6b647086-b338-43fb-864c-d449c229f6fc', '6c3bb75d-0d6c-49a1-bc27-99b670336011', 3, 'Patches can never realistically be deployed faster than an organization''s normal, standard testing cadence under any circumstance, regardless of a vulnerability''s actual severity.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('6c3bb75d-0d6c-49a1-bc27-99b670336011', '99b5caaf-a333-4c93-ade3-0eaa00db09be', 'Emergency/out-of-band patching directly refines the general patch management concept (covered generally in a prior paper) with the genuinely important operational nuance that NOT every patch situation is equally urgent, and a rigid, one-size-fits-all cadence applied uniformly regardless of actual severity is itself a real risk in a genuinely severe, actively-exploited scenario — connecting directly to CVSS severity scoring and vulnerability remediation timelines (both covered elsewhere in this project''s Security+ content), a critical, actively-exploited vulnerability genuinely warrants deliberately bypassing or significantly compressing the normal testing window, accepting the real, explicitly understood trade-off that less testing time increases the chance of an unexpected regression, specifically because the ALTERNATIVE risk (remaining exposed to active, known exploitation for the normal testing duration) is judged to be genuinely greater in that specific case. This should remain a deliberate EXCEPTION process, invoked specifically when the situation warrants it — not the organization''s new normal cadence for every routine patch, which would undermine the real value of proper testing for the vast majority of less time-critical patches. Patches genuinely CAN and regularly are deployed faster than a normal cadence when circumstances warrant it — this is a real, standard, and important operational capability, not a technical or organizational impossibility.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('9082b76d-453f-4117-acc9-c54689175eca', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 12, 'A company hires an external firm to perform a penetration test (covered generally in a prior paper), and before any actual testing begins, both parties formally document exactly what systems are IN scope and OUT of scope, the specific testing window/timeframe, what techniques are and are not authorized (e.g., is social engineering of employees permitted?), and emergency contact procedures if something unexpected happens during testing. What is this formal, pre-engagement document called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('beb204c4-de65-4bf6-bd74-5d46ed455344', '9082b76d-453f-4117-acc9-c54689175eca', 0, 'Rules of Engagement (RoE) — a formal document, agreed upon by both parties BEFORE any actual penetration testing activity begins, precisely defining what systems/scope are authorized for testing (and explicitly what is OUT of scope, genuinely important since testing an out-of-scope system could itself constitute an unauthorized, potentially illegal intrusion), the testing timeframe, which specific techniques are and are not permitted, and emergency escalation/contact procedures — this document is what transforms penetration testing from what would otherwise be indistinguishable from an actual unauthorized attack into a genuinely authorized, legally protected engagement.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b4d76dde-d299-4ac3-864b-275f49b23e7a', '9082b76d-453f-4117-acc9-c54689175eca', 1, 'A BAA, since BAAs are specifically defined as the formal, pre-engagement document establishing scope, timeframe, and authorized techniques for a penetration test.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c4388f1c-ee14-4fbc-adf4-f97cd8e69cdc', '9082b76d-453f-4117-acc9-c54689175eca', 2, 'A legal hold, since legal holds are specifically defined as the document establishing scope, timeframe, authorized techniques, and emergency contacts for a penetration test.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9df4fc6f-9411-46ba-b81a-26db0b47d171', '9082b76d-453f-4117-acc9-c54689175eca', 3, 'Penetration testing requires no formal, pre-agreed documentation of scope or authorized techniques; testers are always free to test whatever systems and use whatever techniques they judge appropriate.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('9082b76d-453f-4117-acc9-c54689175eca', 'beb204c4-de65-4bf6-bd74-5d46ed455344', 'Rules of Engagement is specifically the formal, pre-engagement document making the genuinely critical distinction between AUTHORIZED penetration testing and what would otherwise be indistinguishable from an actual, illegal unauthorized intrusion — directly refining the general vulnerability-scan-vs-pentest concept (covered generally in a prior paper) with the specific governing document that makes a real pentest legally and operationally sound: precisely defined scope (both what IS and, critically, what is explicitly NOT authorized for testing — testing a system genuinely outside the agreed scope could itself constitute unauthorized access, even during an otherwise-legitimate engagement), the specific authorized testing window, which techniques are permitted (e.g., is testing employees'' susceptibility to phishing/social engineering, covered in prior papers, actually authorized, or strictly off-limits), and emergency contact/escalation procedures for if something genuinely unexpected happens (a system unexpectedly crashes, real evidence of an ALREADY-existing, unrelated compromise is discovered during testing). A BAA (covered in a prior paper) is a HIPAA-specific vendor contract, and a legal hold (covered in a prior paper) is a litigation-driven data-preservation obligation — both entirely unrelated to penetration-testing engagement scoping. Formal RoE documentation is a real, standard, and essential prerequisite for any legitimate penetration testing engagement, not an optional or unnecessary formality.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('29d2890c-e328-46e1-9c3a-709dd383f3d9', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 13, 'A SOC receives many different security incidents simultaneously — a single phishing email reported by one employee, and separately, an active, confirmed ransomware outbreak spreading across dozens of production servers. The team needs a structured way to determine which incident demands immediate, all-hands attention versus which can be handled through normal, routine workflow. What framework addresses categorizing incidents by their actual business impact and urgency?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e08b068c-f533-423e-96e8-ad3ec899ffe4', '29d2890c-e328-46e1-9c3a-709dd383f3d9', 0, 'Incident severity classification (often using defined tiers like P1/Critical through P4/Low, or similar naming) — categorizes each incident by its actual BUSINESS IMPACT and urgency (scope of systems affected, data sensitivity involved, business-function disruption, whether active exploitation is confirmed and ongoing), directly driving how much resourcing, escalation, and response speed a given incident receives; this is a genuinely different concept from CVSS (covered in a prior paper, which scores the TECHNICAL severity of a VULNERABILITY in the abstract) — the SAME underlying vulnerability or incident TYPE can warrant a dramatically different severity classification depending on the SPECIFIC business context it''s actually occurring in.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('944bdef6-e2bb-4cae-b180-d830faea3e1e', '29d2890c-e328-46e1-9c3a-709dd383f3d9', 1, 'CVSS, since CVSS is specifically defined as categorizing an incident''s severity by its business impact and urgency rather than scoring a vulnerability''s abstract technical severity.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a96c044a-5f37-4306-a198-60ba74f98d5f', '29d2890c-e328-46e1-9c3a-709dd383f3d9', 2, 'MTTD and MTTR, since MTTD and MTTR are specifically defined as the framework for categorizing incidents by business impact and urgency, rather than measuring detection and response time.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7c44e93c-126f-482c-a561-5cf6e4ae9375', '29d2890c-e328-46e1-9c3a-709dd383f3d9', 3, 'Every security incident, regardless of its actual scope, sensitivity, or business impact, always warrants the exact same level of urgency, resourcing, and response speed.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('29d2890c-e328-46e1-9c3a-709dd383f3d9', 'e08b068c-f533-423e-96e8-ad3ec899ffe4', 'Incident severity classification directly addresses the real, practical need to differentiate response across genuinely different incidents happening at the same time — a SOC handling both a single reported phishing email and a confirmed, actively-spreading ransomware outbreak across dozens of production servers cannot reasonably treat both with identical urgency, and a formal severity-tier framework (commonly using labels like P1/Critical, P2/High, P3/Medium, P4/Low, though exact naming varies by organization) gives a structured, consistent, and communicable basis for that differentiation, directly driving concrete decisions like whether to activate the full CSIRT (covered in a prior paper) immediately or handle something through normal analyst workflow. This is genuinely distinct from CVSS (covered in a prior paper) — CVSS scores a VULNERABILITY''s technical severity in the ABSTRACT (attack vector, complexity, potential impact if exploited), independent of any specific organization''s actual context, while incident severity classification scores an ACTUAL, OCCURRING incident''s real business impact in THIS organization''s specific context right now — the exact same underlying vulnerability type could reasonably receive a very different incident severity classification depending on which specific systems are actually affected and what''s actually happening, a genuinely important distinction between abstract technical scoring and contextual, in-the-moment incident triage. Treating every incident with identical urgency regardless of genuinely different scope and impact would itself be a real operational failure, not a reasonable practice.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('f12b1ac7-6533-49bb-bbd7-395027baaeb8', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 14, 'A large SOC structures its analysts into distinct experience/responsibility levels: the first analysts to review an incoming alert perform initial triage and handle straightforward, well-understood cases themselves; genuinely complex or ambiguous cases get escalated to more experienced analysts who investigate more deeply; and the most senior analysts handle the most sophisticated threats and also work on longer-term threat hunting and detection-engineering projects. What is this tiered analyst structure commonly called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9d36c5ff-2060-4660-bca0-f7e2467227ba', 'f12b1ac7-6533-49bb-bbd7-395027baaeb8', 0, 'SOC tiers (commonly Tier 1, Tier 2, and Tier 3 analysts) — Tier 1 analysts perform initial alert triage, handling straightforward, well-understood cases directly and escalating anything genuinely ambiguous or complex; Tier 2 analysts investigate those escalated cases more deeply, with greater experience and typically broader tool access; and Tier 3 analysts (often the most senior) handle the most sophisticated, novel threats and also frequently work on proactive threat hunting (covered in a prior paper) and improving/tuning detection capability itself, rather than purely reactive alert handling — this tiered structure lets a SOC efficiently allocate its most experienced (and most limited, expensive) analyst time to genuinely complex problems rather than every alert consuming senior-level attention regardless of actual complexity.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7ab53d9d-fc21-442a-a250-b45f80a4dfa7', 'f12b1ac7-6533-49bb-bbd7-395027baaeb8', 1, 'A CSIRT, since CSIRT is specifically defined as the ongoing, tiered analyst structure (Tier 1/2/3) a SOC uses for routine, day-to-day alert triage and escalation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d3012015-ce96-49c6-a6e4-7cd38a63e0c0', 'f12b1ac7-6533-49bb-bbd7-395027baaeb8', 2, 'A RACI matrix, since RACI matrices are specifically defined as the tiered structure grouping SOC analysts into Tier 1, Tier 2, and Tier 3 experience levels.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ff222868-bc05-4ee5-9b1c-91d4dde3abdb', 'f12b1ac7-6533-49bb-bbd7-395027baaeb8', 3, 'SOC analysts are never organized into any distinct tiers or experience levels; every analyst in a security operations center always handles every type of alert identically regardless of complexity.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('f12b1ac7-6533-49bb-bbd7-395027baaeb8', '9d36c5ff-2060-4660-bca0-f7e2467227ba', 'SOC tiers describe the ONGOING, standing OPERATIONAL structure of a security operations center''s day-to-day staffing — genuinely distinct from a CSIRT (covered in a prior paper), which is specifically a cross-functional team (including non-technical roles like legal and communications) ACTIVATED for a SIGNIFICANT incident, not the routine, everyday tiered analyst structure handling the SOC''s continuous, ongoing alert volume. The tiered model exists specifically to efficiently allocate genuinely scarce, expensive senior analyst expertise: Tier 1 analysts (typically less experienced, or newer to the role) handle the high VOLUME of routine, well-understood alerts, escalating only what genuinely warrants deeper investigation; Tier 2 analysts bring more experience and typically broader access/tooling to those escalated, more ambiguous cases; and Tier 3 analysts, the most senior, handle the genuinely hardest, most sophisticated threats and often split time between reactive escalations and PROACTIVE work like threat hunting (covered in a prior paper) or improving the SOC''s own detection capability — a genuinely more efficient allocation than every alert, regardless of actual complexity, consuming the SOC''s most senior and limited analyst time. A RACI matrix (covered in a prior paper) assigns roles for a specific TASK or decision, a different concept from an ongoing organizational staffing tier structure.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('0c768a81-3950-4ed1-9ce2-34308e8d011d', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 15, 'A company defines a formal policy that critical (CVSS 9.0+) vulnerabilities on internet-facing systems must be remediated within 48 hours of discovery, high-severity vulnerabilities within 7 days, and medium-severity vulnerabilities within 30 days — with the vulnerability-management program tracking actual compliance against these defined timelines. What is the purpose of formally defining these specific remediation timeframes tied to severity, rather than simply remediating vulnerabilities in whatever order or timeframe feels convenient?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4274bdec-d730-4949-bfd0-f508a2b79a2c', '0c768a81-3950-4ed1-9ce2-34308e8d011d', 0, 'Formal remediation SLA timelines (tied to CVSS severity, covered earlier this paper, and often further weighted by real-world exploitability and asset exposure, connecting to the vulnerability-management prioritization concept covered in a prior paper) create an ACCOUNTABLE, measurable, and consistently-enforced standard for how quickly different severity levels must actually be addressed — enabling the organization to track genuine compliance against a defined commitment, identify systemic remediation delays before they become a real problem, and ensure the highest-severity, most exploitable vulnerabilities on the most exposed systems genuinely get fixed fastest, rather than remediation priority being decided ad hoc, inconsistently, or based on whichever team happens to have available time.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9678b308-994a-41e3-a85b-20a094320cf5', '0c768a81-3950-4ed1-9ce2-34308e8d011d', 1, 'Formal remediation timelines provide no meaningful organizational or security value, since remediating vulnerabilities in a genuinely ad hoc, inconsistent order based on convenience achieves an identical real-world security outcome.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('84cf033e-670a-453e-bd45-e9e3310c33d4', '0c768a81-3950-4ed1-9ce2-34308e8d011d', 2, 'A gap analysis, since gap analyses are specifically defined as formal, severity-tiered vulnerability remediation timelines like 48 hours for critical and 30 days for medium severity.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('01f26b8b-b396-4f37-9ca5-7e88bd3dd3c0', '0c768a81-3950-4ed1-9ce2-34308e8d011d', 3, 'Every vulnerability, regardless of its actual CVSS severity or real-world exploitability, should always be remediated within the exact same fixed timeframe with no differentiation by severity.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('0c768a81-3950-4ed1-9ce2-34308e8d011d', '4274bdec-d730-4949-bfd0-f508a2b79a2c', 'Formal, severity-tiered remediation SLAs directly operationalize the vulnerability-management prioritization concept (covered generally in a prior paper, which discussed weighing severity, real-world exploitability, and asset criticality) into a concrete, measurable, and enforceable COMMITMENT rather than leaving remediation speed to informal judgment or convenience each time — this matters because ad hoc prioritization, however well-intentioned, is genuinely prone to inconsistency (different people or teams making different judgment calls) and to the highest-severity issues quietly languishing simply because addressing them is inconvenient or requires cross-team coordination, exactly the kind of drift a formal, tracked timeline commitment is designed to catch and prevent. Tracking actual compliance against these defined timelines also gives leadership genuine, concrete visibility into whether the vulnerability-management program is actually functioning as intended — connecting to the broader security KPI/governance-dashboard concept covered in a prior paper — surfacing systemic remediation delays (a specific team or system type consistently missing its timeline) as an actionable finding rather than an invisible, ongoing risk. Applying an identical fixed timeframe regardless of actual severity would defeat the entire purpose of risk-based prioritization, treating a critical, actively-exploitable, internet-facing vulnerability identically to a low-severity internal one — exactly the undifferentiated approach a real vulnerability-management program is specifically designed to avoid.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('0fea3249-3e55-4e59-9d69-a5ced3784af6', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 16, 'A security analyst examines a suspicious executable file two different ways: first, opening it in a disassembler to examine its code structure, embedded strings, and imported functions WITHOUT ever actually running the file, and separately, executing that same file inside a sandbox (covered in a prior paper) to directly observe its real runtime behavior. What are these two distinct malware-analysis approaches called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6ec8b41d-084b-4e91-9331-f576373d6cbc', '0fea3249-3e55-4e59-9d69-a5ced3784af6', 0, 'Static analysis (examining a file''s code, structure, embedded strings, and other characteristics WITHOUT ever actually executing it — genuinely safer in one specific sense, since the file''s malicious payload never actually runs during this examination, but can be defeated by malware specifically designed to resist static inspection, like heavily obfuscated or packed code) and dynamic analysis (actually EXECUTING the file, typically inside an isolated sandbox environment, covered in a prior paper, to directly observe its real runtime behavior — file/registry changes, network connections attempted — catching genuinely evasive malware that behaves differently or reveals its true nature only once actually run, at the cost of the real supervision and isolation rigor sandboxing requires to safely allow that execution).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e206a921-b6b9-4040-9b9a-2ba4609b7249', '0fea3249-3e55-4e59-9d69-a5ced3784af6', 1, 'Dynamic analysis is examining a file''s code without executing it, while static analysis is actually running the file inside a sandbox to observe its behavior — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5b8f50f0-51eb-467e-84c9-8e9a1376443a', '0fea3249-3e55-4e59-9d69-a5ced3784af6', 2, 'Static and dynamic malware analysis are two different names for the exact same analytical approach, with no meaningful distinction in whether the file is actually executed.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5114ec68-6235-474f-b4c9-7d9d98cb262b', '0fea3249-3e55-4e59-9d69-a5ced3784af6', 3, 'A suspicious file''s actual behavior and characteristics can never be meaningfully analyzed through any technique without directly infecting a real, unprotected production system.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('0fea3249-3e55-4e59-9d69-a5ced3784af6', '6ec8b41d-084b-4e91-9331-f576373d6cbc', 'Static and dynamic analysis are genuinely complementary approaches distinguished specifically by whether the suspicious file is actually EXECUTED during examination, directly extending the sandboxing concept (covered in a prior paper, which IS specifically the environment dynamic analysis typically runs within) with the broader, two-sided malware-analysis framework it fits into: static analysis examines the file''s CODE and STRUCTURE directly — disassembling it, extracting embedded strings, reviewing imported/called functions — entirely WITHOUT running it, meaning it carries essentially zero risk of the payload actually executing during the analysis itself, but this approach can be genuinely defeated by malware specifically engineered to resist static inspection (heavily obfuscated code, packing/encryption that only reveals its true form once actually running). Dynamic analysis instead actually RUNS the file (safely, inside the isolated sandbox specifically covered in a prior paper) to directly observe its genuine runtime behavior, catching malware that behaves differently — or only reveals its true malicious nature — once actually executing, at the real cost of needing genuinely rigorous isolation to safely permit that execution at all. Real malware analysis practice typically uses BOTH approaches together for a fuller picture, rather than relying on either exclusively — and this can genuinely be done safely without infecting a real, unprotected production system, contrary to the last distractor, which is precisely the entire point of both careful static inspection and properly isolated sandboxed dynamic analysis.');

-- ── Domain: Security Program Management & Oversight (20% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('750645e7-2216-438b-98c0-9d4a9c4bdadb', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 17, 'A company purchases cyber insurance covering two distinct scenarios: (1) the company''s OWN direct costs from a breach — forensic investigation, system recovery, business interruption, and its own legal fees — and separately, (2) claims from OTHER parties (customers, business partners) suing the company because THEIR data or systems were harmed as a result of the breach. What are these two distinct categories of cyber insurance coverage called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0d5147b4-380f-4d1d-a00c-caacf9065574', '750645e7-2216-438b-98c0-9d4a9c4bdadb', 0, 'First-party coverage (protecting the INSURED company''s own direct losses and costs — forensic investigation, recovery, business interruption, its own legal defense costs) and third-party coverage (protecting against LIABILITY claims from OTHER parties — customers, partners, regulators — harmed by the breach and seeking compensation from the company); this directly refines the general cyber insurance concept (covered generally in a prior paper) with the important distinction that these are genuinely separate coverage categories, and a policy covering one does not automatically cover the other — an organization needs to deliberately evaluate whether its coverage genuinely addresses both realistic exposure categories.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0bc8a457-fe59-4647-acd5-a735c37b4dea', '750645e7-2216-438b-98c0-9d4a9c4bdadb', 1, 'Third-party coverage is specifically defined as protecting the insured company''s own direct losses, while first-party coverage protects against liability claims from other parties — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7de40d35-65a3-4c02-8486-4c012c0bbee0', '750645e7-2216-438b-98c0-9d4a9c4bdadb', 2, 'First-party and third-party cyber insurance coverage are two different names for the exact same coverage category, with no meaningful distinction between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bb98d662-8cfc-49dd-9b6d-f26069ab65f6', '750645e7-2216-438b-98c0-9d4a9c4bdadb', 3, 'Cyber insurance policies can only ever cover a company''s own direct losses; coverage for liability claims brought by other, external parties does not exist as a real insurance category.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('750645e7-2216-438b-98c0-9d4a9c4bdadb', '0d5147b4-380f-4d1d-a00c-caacf9065574', 'First-party and third-party coverage genuinely address two distinct financial exposure categories a company faces after a breach, directly refining the general cyber insurance concept (covered generally in a prior paper) with a real, practically important distinction: first-party coverage reimburses the INSURED organization''s OWN direct costs — the forensic investigation needed to understand what actually happened, system/data recovery, business interruption losses while systems are down, and even the company''s own legal defense costs — essentially, the company''s bill for cleaning up its own mess. Third-party coverage instead addresses LIABILITY — claims brought by OTHER parties (customers whose data was exposed, business partners whose systems were affected, or regulators imposing fines) who were harmed by the breach and are seeking compensation or legal remedy FROM the company. A genuinely comprehensive cyber insurance strategy needs to deliberately evaluate exposure to BOTH categories — a policy covering only first-party costs would leave the organization genuinely exposed to potentially very large third-party liability claims, and vice versa — this is a real, standard, and important distinction in cyber insurance coverage, not an artificial or non-existent one.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('aa453cf2-8e51-4f86-a7e5-c6d90f559e02', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 18, 'A company negotiating a contract with a critical third-party vendor insists on including a specific clause giving the company the explicit CONTRACTUAL RIGHT to conduct its own security audit of the vendor''s systems and practices (or send an independent auditor to do so), rather than relying solely on whatever audit reports or certifications the vendor voluntarily chooses to share. What is this specific contract clause called, and why might a company insist on it?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6cc5719f-f35d-4c99-afba-c447e8dfede6', 'aa453cf2-8e51-4f86-a7e5-c6d90f559e02', 0, 'A right-to-audit clause — a specific contractual provision giving the customer the EXPLICIT, LEGALLY ENFORCEABLE right to conduct (or commission) its own independent security audit of the vendor, rather than depending entirely on whatever information the vendor voluntarily chooses to share; this genuinely strengthens vendor risk management (covered in a prior paper) beyond passive reliance on vendor-provided attestations, since a vendor motivated to look good on paper might otherwise selectively share only favorable information, and this clause gives the customer real, independent verification power specifically written into the contract itself.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e4194124-917b-4187-bfa4-b891949e7575', 'aa453cf2-8e51-4f86-a7e5-c6d90f559e02', 1, 'A BAA, since BAAs are specifically defined as the general contractual clause giving a customer the right to independently audit any vendor''s security practices.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9de098b9-c87e-4fef-bb3f-31185ec57659', 'aa453cf2-8e51-4f86-a7e5-c6d90f559e02', 2, 'An MOU, since MOUs are specifically defined as the legally enforceable clause granting a customer the explicit contractual right to conduct an independent vendor security audit.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bb077c89-8cad-47f6-9127-f7041fcab8ea', 'aa453cf2-8e51-4f86-a7e5-c6d90f559e02', 3, 'A company can never contractually secure the right to independently audit a vendor''s security practices; verification must always rely entirely on whatever the vendor voluntarily chooses to share.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('aa453cf2-8e51-4f86-a7e5-c6d90f559e02', '6cc5719f-f35d-4c99-afba-c447e8dfede6', 'A right-to-audit clause directly strengthens vendor risk management (covered in a prior paper, which discussed reviewing a vendor''s certifications and audit reports before signing) by giving the customer a genuinely ENFORCEABLE contractual mechanism to independently VERIFY a vendor''s security posture, rather than being limited to whatever information the vendor voluntarily and selectively chooses to disclose — a real, meaningful gap, since a vendor motivated to win or keep a contract has a real incentive to present itself favorably, and pre-signing due diligence (covered earlier this paper) alone provides no ongoing, independently-verifiable mechanism for the RELATIONSHIP''S DURATION, only a one-time, vendor-controlled snapshot at signing. Including a right-to-audit clause specifically closes that gap by contractually guaranteeing the customer (or an independent auditor acting on the customer''s behalf) can actually go verify the vendor''s claims directly, rather than trusting entirely on faith or the vendor''s own self-reported assurances throughout the relationship. A BAA (covered in a prior paper) is a HIPAA-specific contract type, and an MOU (covered in a prior paper) is a general, typically NON-binding statement of shared understanding — a right-to-audit clause is instead specifically a real, legally enforceable provision commonly included WITHIN a broader vendor contract, genuinely achievable and commonly negotiated for exactly this purpose, not an unattainable ideal.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('7afda359-fbc0-438f-b532-124e590bee9c', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 19, 'A publicly traded company must maintain strong internal controls over its financial reporting and IT systems that touch financial data, specifically to ensure the accuracy and integrity of its published financial statements — driven by a specific US federal law enacted in response to major historical corporate accounting scandals. What is this specific regulation called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5b75e9d7-ca11-4e81-a15d-87081dec6981', '7afda359-fbc0-438f-b532-124e590bee9c', 0, 'SOX (the Sarbanes-Oxley Act) — a US federal law specifically requiring publicly traded companies to maintain strong, verifiable internal controls over financial reporting (including the IT systems and security controls protecting financial data''s integrity and accuracy), enacted specifically in response to major historical corporate accounting scandals that undermined public trust in published financial statements — genuinely distinct in scope and focus from HIPAA (covered in a prior paper, health information), GDPR (covered in a prior paper, EU personal data broadly), and PCI-DSS (covered in a prior paper, an industry standard for payment card data, not a government law) — SOX specifically targets the integrity of FINANCIAL REPORTING for publicly traded companies.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5f6012ea-3a6d-47ba-b2d0-539bdf03d991', '7afda359-fbc0-438f-b532-124e590bee9c', 1, 'PCI-DSS, since PCI-DSS is specifically the US federal law requiring publicly traded companies to maintain internal controls over financial reporting integrity.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('55d9ba83-035b-4ae1-b014-38e181c3a7de', '7afda359-fbc0-438f-b532-124e590bee9c', 2, 'HIPAA, since HIPAA is specifically the law enacted in response to corporate accounting scandals, requiring internal controls over publicly traded companies'' financial reporting.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0ec66996-c7b8-410c-9c7c-db56ff60da00', '7afda359-fbc0-438f-b532-124e590bee9c', 3, 'No US federal law imposes any requirement on publicly traded companies regarding internal controls over the accuracy or integrity of their financial reporting or related IT systems.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('7afda359-fbc0-438f-b532-124e590bee9c', '5b75e9d7-ca11-4e81-a15d-87081dec6981', 'SOX is specifically distinguished by its SCOPE and TRIGGER — a US federal LAW (like HIPAA, a government-enacted regulation with real legal force, not merely an industry standard like PCI-DSS) specifically focused on the integrity and accuracy of PUBLICLY TRADED companies'' FINANCIAL REPORTING, enacted in direct response to major historical corporate accounting scandals that severely damaged public and investor trust in reported financial statements. This directly requires publicly traded companies to maintain and be able to DEMONSTRATE strong internal controls — extending meaningfully into IT security specifically for any systems that touch, process, or could affect the accuracy of financial data, since a security failure in those systems could directly undermine the very financial-reporting integrity SOX exists to protect. This is a genuinely distinct regulation from every other compliance framework covered in this project''s Security+ content — HIPAA (health information specifically), GDPR (EU personal data broadly, regardless of the processing organization''s location), and PCI-DSS (payment card data specifically, an industry standard rather than a government law) — each targets a genuinely different data category, triggering condition, and source of authority, a common and directly testable point of confusion given how frequently these are grouped together loosely as "compliance requirements" without appreciating their real, distinct scopes.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('237e1348-57d3-4580-9c43-ec900ea533e6', '3ee0ee8f-80dc-44a7-91db-3ce4bac5dc4c', 20, 'A company wants a formal, structured process governing every physical and digital IT asset (laptops, servers, software licenses) from the moment it''s first acquired, through its active use, until it''s eventually retired and disposed of — including ensuring any sensitive data on a device is properly and securely erased before that device is disposed of, resold, or repurposed, rather than simply thrown away with data potentially still recoverable from it. What is this end-to-end governance process called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3d6b9f39-badd-4447-a5c8-6ebf5862793a', '237e1348-57d3-4580-9c43-ec900ea533e6', 0, 'Asset management (specifically covering the full asset lifecycle from acquisition through active use to secure disposal) — maintains a genuine, accurate inventory of every IT asset throughout its entire lifecycle, and critically includes secure data sanitization/destruction procedures BEFORE a device is disposed of, resold, or repurposed, since simply deleting files or performing a standard format does NOT reliably prevent forensic data recovery from the underlying storage media — proper sanitization (cryptographic erasure, physical destruction, or verified secure-wipe procedures, depending on the asset''s sensitivity and reuse plans) is what actually closes this real, practical, and often-overlooked data-exposure risk.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f08f22d9-beb8-4331-be03-881a13809229', '237e1348-57d3-4580-9c43-ec900ea533e6', 1, 'Data classification, since data classification is specifically defined as the end-to-end process governing a physical IT asset from acquisition through active use to secure disposal.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('83d19bbc-5858-45dc-880b-25067ceac689', '237e1348-57d3-4580-9c43-ec900ea533e6', 2, 'Onboarding, since onboarding is specifically defined as the governance process covering an IT asset''s full lifecycle from acquisition through secure disposal, rather than an employee''s pre-employment vetting.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5d703e4a-8942-45d8-a6a4-3c6eb713bf47', '237e1348-57d3-4580-9c43-ec900ea533e6', 3, 'Simply deleting files or performing a standard disk format before disposing of a device is always fully sufficient to prevent any possibility of the previously-stored data being recovered.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('237e1348-57d3-4580-9c43-ec900ea533e6', '3d6b9f39-badd-4447-a5c8-6ebf5862793a', 'Asset management''s full-lifecycle scope (acquisition through active use through disposal) is genuinely distinct from data classification (covered in a prior paper, which categorizes DATA by sensitivity tier, a related but different concept from tracking and governing physical/digital ASSETS themselves throughout their lifecycle) — the specific, practically critical piece this scenario highlights is SECURE DISPOSAL: a standard file deletion or even a routine disk format typically does NOT actually erase the underlying data from storage media at all — it generally only removes the file system''s POINTERS to that data, meaning the actual data often remains genuinely, forensically recoverable from the physical media using readily available tools, a real and well-documented risk when a device is later resold, donated, or simply discarded without proper sanitization. Proper asset disposal instead requires genuine data sanitization — methods like cryptographic erasure (rendering encrypted data unrecoverable by destroying the encryption key, connecting to encryption concepts covered in prior papers), a verified secure-wipe procedure that actually overwrites the underlying storage, or physical destruction of the media entirely for the most sensitive cases — matched appropriately to the asset''s sensitivity and its intended fate (resale, donation, destruction). This is a real, standard, and genuinely important governance practice specifically because the "just delete it" assumption is a well-documented, real security gap, not a reliably safe practice on its own.');
