-- ============================================================
-- CompTIA Security+ (SY0-701) — Seed Data: Paper 5
-- New content, distinct topics from Papers 1-4 — no repeated scenarios.
-- Topic list checked directly against the actual question text of Papers
-- 1-4 (not a summarized recollection) before writing, after Paper 4 was
-- found to have duplicated 3 of Paper 3's actual scenarios despite an
-- earlier good-faith topic check — see the fix commit on
-- docs/secplus_seed_paper_4.sql for the full account.
-- Same domain weighting: General Security Concepts 12% (2/20), Threats/
-- Vulnerabilities/Mitigations 22% (4/20), Security Architecture 18%
-- (4/20), Security Operations 28% (6/20), Security Program Management &
-- Oversight 20% (4/20).
--
-- IDs were generated via scripts/fill-seed-uuids.mjs, which replaces every
-- distinct placeholder token with a fresh, real UUID (consistently across
-- every occurrence) — this file has already had that script run against
-- it; the UUIDs below are real. Cross-checked against every other seed
-- file in the repo for zero collisions before finalizing, plus the
-- distractor-language sanity scan and a manual re-read of every answer key
-- against its option text.
-- Run this AFTER docs/question-bank-schema.sql.
-- ============================================================

INSERT INTO question_papers (id, slug, title, exam_type, focus_tags, question_count, difficulty, is_premium, sort_order, time_limit_minutes)
VALUES ('7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 'secplus-practice-5', 'CompTIA Security+ (SY0-701) Practice Paper 5', 'comptia-sec-plus', ARRAY['Control Categories', 'Insider Threat', 'Supply Chain', 'Credential Stuffing', 'HA Clustering', 'IoT Security', 'Threat Hunting', 'Honeytokens', 'Risk Register', 'Risk Appetite']::TEXT[], 20, 'standard', true, 5, 30);

-- ── Domain: General Security Concepts (12% — 2 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('17a12797-f02b-46a3-894c-8a5a9440ca76', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 1, 'A security policy classifies its safeguards into four categories: a written access-control policy (managerial), the technical enforcement of that policy through IAM permissions (technical), the actual day-to-day process of manually reviewing access requests (operational), and a locked server room door (physical). What is this four-way classification of security controls called, and how does it differ from classifying controls as preventive, detective, or corrective?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ae781164-603f-487e-a47a-444fa93e1126', '17a12797-f02b-46a3-894c-8a5a9440ca76', 0, 'Control categories — technical, managerial, operational, and physical describe WHO/WHAT implements a control and in what domain (a policy document vs. a software permission setting vs. a locked door), which is a genuinely separate classification axis from control TYPES (preventive, detective, corrective, deterrent, compensating), which describe WHEN and HOW a control acts relative to an event; the same real-world control is often classified along BOTH axes at once — e.g., a locked door is both a physical-category control and a preventive-type control.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1a7b71d6-c065-45be-8583-d2d8eaf2bc9c', '17a12797-f02b-46a3-894c-8a5a9440ca76', 1, 'Control categories and control types are the exact same classification system under two different names, with no meaningful distinction between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b35e9b7d-01fe-4397-b6a1-811ffdceaa82', '17a12797-f02b-46a3-894c-8a5a9440ca76', 2, 'A single control can only ever be classified under exactly one of these two systems, never both at the same time.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0b026ad8-2b0c-4ce5-b1c8-77d92e172c02', '17a12797-f02b-46a3-894c-8a5a9440ca76', 3, 'This four-way classification of technical, managerial, operational, and physical controls does not exist as a recognized security concept.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('17a12797-f02b-46a3-894c-8a5a9440ca76', 'ae781164-603f-487e-a47a-444fa93e1126', 'Control categories (technical, managerial, operational, physical) classify a control by its NATURE/domain: technical controls are enforced by technology itself (IAM permissions, encryption, a firewall rule); managerial controls are policies, procedures, and risk-management decisions made by people in a governance capacity (a written access-control policy, a risk acceptance decision); operational controls are the day-to-day human processes and procedures that implement policy (manually reviewing an access request, running a security awareness session); and physical controls are tangible, real-world barriers (locks, badges, fencing, physical power redundancy). This is a genuinely separate, complementary axis from control TYPES (preventive/detective/corrective/deterrent/compensating, the latter covered specifically in Paper 4), which instead classify a control by its TIMING/FUNCTION relative to a security event — a control can and often does sit at the intersection of both systems simultaneously (a locked door is physical-category AND preventive-type; a SIEM alert is technical-category AND detective-type), so treating these as interchangeable or mutually exclusive misses a genuinely useful, two-dimensional way of describing a security control''s full nature that the exam tests directly.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('1ba88717-9339-4683-bc49-d64fe3429825', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 2, 'A security team classifies their organization''s controls by WHEN/HOW they act relative to a security event: a firewall rule blocking traffic before it reaches a server, a SIEM alert flagging suspicious activity after it happens, and a rollback procedure restoring a system after a bad change. What is this timing-based classification called, and name the type each example represents?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cc62946f-9107-4003-9013-e43d66adb74d', '1ba88717-9339-4683-bc49-d64fe3429825', 0, 'Control types — the firewall rule is PREVENTIVE (stops the event before it occurs), the SIEM alert is DETECTIVE (identifies that an event has already occurred, after the fact), and the rollback procedure is CORRECTIVE (restores normal operation after an event has caused harm); a fourth common type, deterrent, discourages an event from being attempted in the first place (e.g., a visible warning sign) rather than technically blocking or detecting it.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d0be1a16-63d6-41eb-bbb0-17d97d1b9daf', '1ba88717-9339-4683-bc49-d64fe3429825', 1, 'Control categories, since control categories are specifically defined as classifying controls by their timing relative to a security event.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fc227cfe-8625-4a44-8182-4b2d1368befb', '1ba88717-9339-4683-bc49-d64fe3429825', 2, 'The CIA triad, since the CIA triad classifies controls as preventive, detective, or corrective based on timing.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('db3f1455-c672-4b87-8646-b5d26f9d425a', '1ba88717-9339-4683-bc49-d64fe3429825', 3, 'All security controls act at exactly the same point in time relative to an event, making this kind of timing-based classification meaningless.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('1ba88717-9339-4683-bc49-d64fe3429825', 'cc62946f-9107-4003-9013-e43d66adb74d', 'Control types classify a control specifically by WHEN it acts relative to a security event''s timeline: preventive controls stop an event from happening at all (a firewall rule, least privilege, covered in Paper 1); detective controls identify that an event has already occurred, typically enabling a response (a SIEM alert, covered in Paper 1, or FIM, covered in Paper 4); corrective controls restore normal state or limit ongoing damage after an event (a rollback, a patch applied after exploitation); and deterrent controls discourage an attempt from being made in the first place through visible presence rather than technical blocking (warning signage, visible security cameras) — genuinely distinct from PREVENTIVE, which technically stops an attempt already in progress, rather than discouraging the attempt from being tried at all. This is a directly complementary classification to control CATEGORIES (technical/managerial/operational/physical, covered in the prior question) — the two systems answer different questions ("what kind of thing is this control" vs. "when in the event timeline does it act") and are not restatements of each other, nor is this timing-based classification unrelated to the entirely separate CIA triad (confidentiality/integrity/availability, covered in Paper 1), which describes protection GOALS, not control timing.');

-- ── Domain: Threats, Vulnerabilities & Mitigations (22% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('4f50e366-0b29-4f4e-9629-d614a03ff7e3', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 3, 'A disgruntled employee with legitimate, authorized access to the company''s customer database deliberately exports the entire table and sells it to a competitor before resigning. No external attacker or technical exploit was involved at any point. What category of threat does this represent, and why is it often harder to detect than an external attack?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5a4f77c5-9a50-4192-99bc-1cd60d3479e4', '4f50e366-0b29-4f4e-9629-d614a03ff7e3', 0, 'An insider threat — a person with legitimate, authorized access misusing that access for a malicious purpose; it is often harder to detect than an external attack specifically because the activity (accessing the customer database) looks like ordinary, authorized behavior from a legitimate credential, rather than the anomalous, unauthorized access pattern that external-attacker detection tools are typically tuned to flag.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8a9a73c6-7e2f-4d64-8c35-657081d9d820', '4f50e366-0b29-4f4e-9629-d614a03ff7e3', 1, 'A zero-day vulnerability, since zero-day vulnerabilities are defined as a legitimate, authorized employee misusing their own access without any technical exploit.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('48781c45-3468-4ca5-8a78-fff802cb9ff3', '4f50e366-0b29-4f4e-9629-d614a03ff7e3', 2, 'A watering hole attack, since watering hole attacks are defined as an authorized employee exporting data using their own legitimate credentials.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('81deabef-538c-4da8-a711-32cdddf8208a', '4f50e366-0b29-4f4e-9629-d614a03ff7e3', 3, 'This scenario poses no real security risk, since the person involved had legitimate, authorized access to the data at the time.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('4f50e366-0b29-4f4e-9629-d614a03ff7e3', '5a4f77c5-9a50-4192-99bc-1cd60d3479e4', 'An insider threat is specifically defined by WHO the threat actor is (someone with legitimate, existing access — an employee, contractor, or partner) rather than by any particular technique, which is exactly what makes this category genuinely harder to detect than most external attacks: a firewall, an IDS (covered in Paper 2), or anomaly-based detection tools are largely built and tuned around identifying UNAUTHORIZED access attempts or unusual EXTERNAL traffic patterns, but an insider using their own valid, everyday credentials to access data they''re normally permitted to touch doesn''t trigger those same signals — the activity looks routine specifically because, from a pure access-control standpoint, it technically is. This is exactly why detection here leans more heavily on behavioral analytics like UEBA (covered in Paper 4, watching for anomalous BEHAVIOR from a legitimate account rather than unauthorized access attempts), DLP (covered in Paper 3, catching the actual data movement/exfiltration itself), and separation of duties/least privilege (covered in Papers 1 and 3, limiting how much damage any single insider could do even with malicious intent) — this is a real, well-documented, and specifically challenging threat category, not a risk-free scenario simply because the access itself was authorized at the time it occurred.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('cfba8579-f57c-4b97-891d-9e617e462d2f', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 4, 'A widely used open-source software library is compromised by an attacker who gains access to the maintainer''s publishing credentials and pushes a malicious update, which is then automatically pulled into thousands of downstream applications that depend on that library, without any of those downstream developers directly being attacked. What is this attack pattern called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dfbb2945-3c21-4110-92d0-5761383bba9b', 'cfba8579-f57c-4b97-891d-9e617e462d2f', 0, 'A supply chain attack — compromising a trusted upstream component (a software library, a vendor''s update mechanism, a hardware component during manufacturing) that many downstream organizations already depend on and trust, so that compromising ONE upstream target propagates the attacker''s access or malicious code into potentially thousands of downstream victims automatically, without directly attacking each of them individually.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cffb177b-dd0e-41a5-8a9e-cde33c26a634', 'cfba8579-f57c-4b97-891d-9e617e462d2f', 1, 'Credential stuffing, since credential stuffing is defined as compromising a widely used software library''s update mechanism to affect thousands of downstream applications.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('10ef2618-21ed-42f1-a9b9-dfa1de6594fb', 'cfba8579-f57c-4b97-891d-9e617e462d2f', 2, 'A buffer overflow, since buffer overflows are defined as compromising a software maintainer''s publishing credentials to distribute a malicious update.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ee815ac9-03ab-4860-bd49-ef46e34dcbc7', 'cfba8579-f57c-4b97-891d-9e617e462d2f', 3, 'This scenario is not a real, distinct attack pattern; compromising a shared upstream software dependency provides no meaningful advantage over attacking each downstream target individually.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('cfba8579-f57c-4b97-891d-9e617e462d2f', 'dfbb2945-3c21-4110-92d0-5761383bba9b', 'A supply chain attack is defined by exactly this leverage dynamic — rather than attacking many individual downstream targets directly (which takes proportionally more effort per victim), an attacker compromises ONE trusted upstream point that many others already depend on and implicitly trust, so that a single successful compromise cascades automatically into every downstream consumer of that dependency, often without the downstream victims ever being directly, individually targeted at all. This is a genuinely important, real, and increasingly common attack category precisely BECAUSE of that leverage — a single compromised widely-used library, a compromised legitimate software update mechanism, or a compromised hardware component introduced during manufacturing can each affect vastly more victims than the effort of compromising the single upstream point would suggest, which is exactly why vendor/supply-chain risk management (covered in Paper 3, from the due-diligence/pre-contract angle) and verifying software integrity (e.g., checking a package''s published hash, connecting to the hashing/integrity concept covered in Paper 2) are real, standard mitigations specifically aimed at this risk. Credential stuffing (a distinct attack using previously-breached username/password pairs against other services) and buffer overflows (a memory-safety vulnerability class) are both genuinely different, unrelated technical concepts from this specific trust-propagation attack pattern.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('c9bd850b-2e33-4b26-ad31-9ce4d5fe7e41', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 5, 'An attacker obtains a large list of username/password pairs leaked from a previous, unrelated data breach at a different company, and automatically attempts to log in to a totally different, unrelated service using those exact same username/password combinations — succeeding against users who reused the same password across both sites. What is this specific attack technique called, and how does it differ from a generic brute-force attack?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cec2482c-ac86-4d6e-bbb3-c3fa085cf18e', 'c9bd850b-2e33-4b26-ad31-9ce4d5fe7e41', 0, 'Credential stuffing — automatically attempting known, previously-breached username/password PAIRS (from an unrelated prior breach) against a different service, relying specifically on password reuse across sites for its success, distinct from a generic brute-force attack, which instead tries many GUESSED password possibilities (often systematically, e.g., every combination or a common-password list) against a single known username, with no reliance on any specific prior data breach.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fc08d62d-b4a6-42dd-bd5e-5eb548fe670b', 'c9bd850b-2e33-4b26-ad31-9ce4d5fe7e41', 1, 'A watering hole attack, since watering hole attacks are defined as attempting previously-breached username/password pairs against a different, unrelated service.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6617fb8e-eeae-4e52-9eca-c79d9548ed31', 'c9bd850b-2e33-4b26-ad31-9ce4d5fe7e41', 2, 'A supply chain attack, since supply chain attacks are defined as reusing leaked username/password pairs from an unrelated prior breach against a different service.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5f143af0-f58e-4dda-909f-4315b1e6a107', 'c9bd850b-2e33-4b26-ad31-9ce4d5fe7e41', 3, 'Credential stuffing and a generic brute-force attack are identical techniques with no meaningful distinction between them.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('c9bd850b-2e33-4b26-ad31-9ce4d5fe7e41', 'cec2482c-ac86-4d6e-bbb3-c3fa085cf18e', 'Credential stuffing is specifically distinguished by its INPUT SOURCE and the assumption it relies on: it uses ACTUAL, previously-leaked, real username/password pairs (from a genuinely different, unrelated breach) rather than guessed or generated password possibilities, and succeeds specifically against users who reused that exact same password on the now-targeted service — meaning its success rate depends heavily on how common password reuse is among the target user base, not on password strength or complexity the way brute-forcing does. A generic brute-force attack, by contrast, systematically tries many possible passwords (from a wordlist, or exhaustively) against a KNOWN username with no dependency on any specific prior breach data at all — meaningfully different mechanisms even though both are automated, high-volume login-attempt techniques, a distinction worth being precise about since the two are commonly conflated. This is exactly why MFA (covered in Paper 1) is such an effective mitigation against credential stuffing specifically — even a correctly-guessed/reused password alone is insufficient to complete authentication if a second factor is also required, and why encouraging (or technically enforcing) unique passwords per site directly removes the underlying condition credential stuffing depends on.');

-- ── Domain: Security Architecture (18% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('ecb18e7a-3a26-451e-b089-caf1315fd94c', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 6, 'A company runs a critical application across two data centers and wants BOTH data centers actively handling live production traffic simultaneously at all times, rather than one data center sitting idle as a standby that only activates if the primary fails. What high-availability architecture pattern describes this "both sides always active" approach, and what is its main advantage over a standby-based pattern?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('85156e3c-9d67-4e4c-9f82-60e0c645c0ea', 'ecb18e7a-3a26-451e-b089-caf1315fd94c', 0, 'Active/active clustering — both nodes (or data centers) actively handle live production traffic simultaneously at all times, rather than one sitting idle as a passive standby; its main advantage over active/passive is that failover, if one side does fail, is faster and less disruptive (the surviving side is already actively serving traffic and simply absorbs more of it, rather than a previously-idle standby needing to be activated and warmed up from a cold or lightly-used state).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2d71e041-195f-4240-8ea8-675445e993e4', 'ecb18e7a-3a26-451e-b089-caf1315fd94c', 1, 'Active/passive clustering, since active/passive clustering is specifically defined as both data centers actively handling live production traffic simultaneously.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b50836a3-2bb8-49ed-b5b3-df94cc68e1e8', 'ecb18e7a-3a26-451e-b089-caf1315fd94c', 2, 'An air-gapped network, since air-gapped networks describe two data centers actively sharing live production traffic simultaneously at all times.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4ed62825-1569-48fb-a6d2-a6f2c022b4b3', 'ecb18e7a-3a26-451e-b089-caf1315fd94c', 3, 'There is no meaningful architectural difference between having both data centers actively serving traffic versus one sitting idle as a standby.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('ecb18e7a-3a26-451e-b089-caf1315fd94c', '85156e3c-9d67-4e4c-9f82-60e0c645c0ea', 'Active/active clustering is specifically defined by having every node/site genuinely serving live production traffic concurrently, rather than the active/passive pattern (the inverse arrangement — one side actively serving traffic while the other sits idle, only taking over upon a detected failure of the active side). The real, testable advantage of active/active is failover SPEED and smoothness: since the surviving side in an active/active setup is ALREADY actively handling real traffic (not cold or newly-spinning-up), it simply absorbs the failed side''s traffic share, versus active/passive, where the previously-idle passive side must first be activated/promoted (a process that, depending on how "warm" the standby was kept, can introduce a real, meaningful delay) — this same active/passive-vs-active/active trade-off shows up elsewhere too, echoing the Multi-AZ-vs-read-replica-promotion distinction covered in AWS SAA content, though the underlying HA-clustering CONCEPT itself is a general, cloud-agnostic architecture pattern, not specific to any one platform. An air-gapped network (covered in Paper 3) describes the complete ABSENCE of network connectivity between systems — the conceptual opposite of two data centers actively sharing live traffic, making it an unrelated and genuinely contradictory distractor here.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('552a4cee-d3a5-40c9-9138-fd934b4d27c2', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 7, 'A security architect describes data protection requirements across three distinct states: data sitting in a database on disk, data actively moving across a network connection, and data currently loaded into a running application''s memory being actively processed. What are these three states called, and why does protecting each typically require a different specific technique?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a56f536d-e5e1-40f8-b575-b82d500b957c', '552a4cee-d3a5-40c9-9138-fd934b4d27c2', 0, 'Data at rest, data in transit, and data in use — each state has a different exposure profile requiring a different protection technique: data AT REST (on disk/storage) is typically protected by encryption applied to the storage medium or file itself; data IN TRANSIT (moving across a network) is typically protected by transport-layer encryption like TLS; and data IN USE (actively being processed in memory) is the hardest to protect, since it must generally be decrypted to be usable by the processing application, requiring specialized techniques (like confidential computing / trusted execution environments) rather than the encryption approaches that work for the other two states.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b18a43c8-88e8-4d91-b3f0-bf8fde9c9aac', '552a4cee-d3a5-40c9-9138-fd934b4d27c2', 1, 'Public, Internal, and Confidential, since these are the standard terms for data at rest, data in transit, and data in use.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0e62570f-2a32-4cf5-adf7-e9641f659393', '552a4cee-d3a5-40c9-9138-fd934b4d27c2', 2, 'Preventive, detective, and corrective, since these terms specifically describe the three states data can exist in (on disk, in transit, and in memory).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('53d6d48d-2611-4be3-86d5-adce1e12a1c7', '552a4cee-d3a5-40c9-9138-fd934b4d27c2', 3, 'A single encryption technique protects data identically and completely across all three of these states, with no meaningful technical difference between them.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('552a4cee-d3a5-40c9-9138-fd934b4d27c2', 'a56f536d-e5e1-40f8-b575-b82d500b957c', 'The data states framework (at rest / in transit / in use) is foundational specifically because each state has a genuinely different exposure profile and therefore needs a genuinely different protection approach: at-rest protection (covered generally through encryption-type concepts in Paper 1) guards data sitting in storage against a scenario like stolen physical media or unauthorized filesystem access; in-transit protection (TLS, VPN tunnels, covered in Paper 2) guards data actively moving across a network against interception (an evil twin attack or on-path position, covered in Paper 3, is exactly the kind of threat in-transit protection defends against); and in-use protection is the hardest and most specialized of the three, because the whole point of loading data into memory is for the application to actively work with it in its usable, decrypted form — meaningfully protecting data WHILE it''s being processed (rather than only before or after) requires more specialized approaches like confidential computing/trusted execution environments, a genuinely more advanced and less universally deployed technique than standard at-rest or in-transit encryption. This is entirely distinct from data classification tiers (Public/Internal/Confidential/Restricted, covered in Paper 2, which classify data by SENSITIVITY, not by its current state) and from control types (preventive/detective/corrective, covered earlier this paper, an unrelated classification of controls rather than of data states) — a single encryption approach does not uniformly cover all three states, which is exactly the point this distinction tests.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('ca3cd510-7e89-4715-9e17-9211d06d48f3', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 8, 'A company deploys hundreds of low-cost IoT sensors across a factory floor. These devices have limited processing power and memory, often run outdated or unpatchable firmware from the manufacturer, and use lightweight, sometimes weaker protocols compared to standard enterprise IT systems. What security approach is most appropriate given these devices'' specific constraints?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ba85f7e2-d552-4aa8-9e02-441a1a84def9', 'ca3cd510-7e89-4715-9e17-9211d06d48f3', 0, 'Network-level compensating controls specifically suited to constrained/embedded devices — since the devices themselves often cannot support strong on-device security (limited compute for encryption, unpatchable firmware, weak native protocols), isolate them on a dedicated, tightly restricted network segment (connecting to network segmentation/micro-segmentation concepts covered in Paper 2), monitor their traffic closely for anomalies, and limit what they can reach — treating the NETWORK as the primary control layer specifically because the devices themselves cannot reliably provide strong security on their own.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6adc720c-eb9e-4557-b209-6b03e2385027', 'ca3cd510-7e89-4715-9e17-9211d06d48f3', 1, 'Every IoT device of this kind should always be given full, unrestricted access to the corporate network with no segmentation or restriction of any kind.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d29c0c45-8260-4420-88b3-675e153f4d71', 'ca3cd510-7e89-4715-9e17-9211d06d48f3', 2, 'Resource-constrained IoT devices always support the exact same strong on-device security capabilities as a standard enterprise server, requiring no different security approach at all.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3e80e3e2-e5f2-426d-ba4e-4d012353a2d4', 'ca3cd510-7e89-4715-9e17-9211d06d48f3', 3, 'No security measures of any kind are possible for resource-constrained embedded/IoT devices; they must simply be left completely unprotected.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('ca3cd510-7e89-4715-9e17-9211d06d48f3', 'ba85f7e2-d552-4aa8-9e02-441a1a84def9', 'Embedded/IoT devices represent a genuinely distinct security-architecture challenge specifically BECAUSE their real constraints (limited compute/memory ruling out heavier cryptographic operations, frequently unpatchable or infrequently-updated firmware, and lightweight protocols that may lack the security features standard enterprise protocols have) mean strong on-device security often genuinely isn''t achievable the way it would be on a standard server — which is exactly why the practical, standard mitigation approach shifts the primary security burden to the NETWORK layer around the device rather than the device itself: isolating IoT devices on their own dedicated, tightly restricted network segment, closely monitoring their traffic for anomalous behavior (since a compromised IoT device''s traffic pattern will often look different from its normal narrow function), and strictly limiting what those segments can reach elsewhere on the network — directly connecting to compensating controls (covered in Paper 4, applied here to the specific case of unpatchable/constrained devices rather than legacy systems generally) and micro-segmentation (covered in Paper 2). Treating IoT devices as capable of the same on-device security as a full server, or as requiring no security consideration at all in either direction (fully open or fully abandoned), both ignore the real, well-documented constraint this question describes.');

-- ── Domain: Security Operations (28% — 6 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('3a963657-6738-4991-8e7d-f6b367b7e2ae', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 9, 'A security analyst does not wait for a SIEM alert to appear, but instead proactively forms a hypothesis (e.g., "an attacker may have already established persistence in our environment using a technique that wouldn''t trigger our current detection rules") and actively searches logs and system state for evidence supporting or disproving it. What is this proactive practice called, and how does it differ from standard, alert-driven SOC monitoring?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ffb72ad8-54d8-4acc-a27f-e7652fbbac2f', '3a963657-6738-4991-8e7d-f6b367b7e2ae', 0, 'Threat hunting — a proactive, hypothesis-driven search for evidence of compromise that may not have triggered any existing automated detection rule, distinct from standard SOC monitoring, which is fundamentally REACTIVE (responding to alerts already generated by existing detection tooling like a SIEM); threat hunting specifically assumes detection gaps may exist and actively looks for what automated tooling might have missed, rather than waiting for tooling to surface something on its own.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a0f42da7-c91f-429f-8c59-888c6025691b', '3a963657-6738-4991-8e7d-f6b367b7e2ae', 1, 'Vulnerability scanning, since vulnerability scanning is defined as proactively forming a hypothesis about undetected compromise and searching for supporting evidence.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3fbedfb6-442c-4243-b28e-17b20d3aa4a1', '3a963657-6738-4991-8e7d-f6b367b7e2ae', 2, 'A tabletop exercise, since tabletop exercises are defined as proactively searching system logs for evidence of undetected compromise.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5e09bf13-b70e-4bdc-9e12-424612ec518a', '3a963657-6738-4991-8e7d-f6b367b7e2ae', 3, 'Threat hunting and standard alert-driven SOC monitoring are identical practices with no meaningful distinction between them.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('3a963657-6738-4991-8e7d-f6b367b7e2ae', 'ffb72ad8-54d8-4acc-a27f-e7652fbbac2f', 'Threat hunting is specifically defined by its PROACTIVE, hypothesis-driven nature — rather than waiting for an existing detection rule (in a SIEM, covered in Paper 1, or EDR, also covered in Paper 1) to fire an alert, a threat hunter starts from an informed hypothesis about how an attacker MIGHT have evaded current detection (often informed by threat intelligence/IOCs, covered in Paper 3, about techniques currently being used in the wild) and actively digs through logs, system state, and network data looking for supporting or disproving evidence — a fundamentally different posture from standard SOC monitoring, which is largely REACTIVE by design, responding to whatever the existing detection tooling already surfaces on its own. This distinction matters because detection tooling, however well-tuned, inherently has gaps and blind spots (a genuinely novel technique, or one specifically designed to evade known detection signatures, won''t trigger an existing rule by definition) — threat hunting exists specifically to actively probe for exactly those gaps rather than assuming "no alert" means "no compromise." Vulnerability scanning (covered in Paper 1) looks for known, catalogued WEAKNESSES in systems, a different activity from actively hunting for evidence of an actual, potentially-already-occurring compromise.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('48a9e858-eba8-4d2e-ba3d-294af3fd0906', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 10, 'During a forensic investigation, an analyst needs to examine a suspect hard drive''s contents without any risk of accidentally modifying a single bit of data on it, since any modification could compromise the evidence''s integrity and its admissibility later. What tool is specifically used to physically or logically guarantee that a storage device being examined cannot be written to during the process?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6cbee749-8fbb-41a4-890d-46cfd62672f6', '48a9e858-eba8-4d2e-ba3d-294af3fd0906', 0, 'A write blocker — a hardware device (or software-enforced equivalent) placed between the storage media being examined and the analyst''s forensic workstation, physically or logically preventing ANY write command from reaching the original media, so the analyst can safely read from and create a forensic image of the drive with a mathematical guarantee that the original evidence remains completely unmodified throughout the process.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3a98d9d2-9a01-40e3-b3eb-c52511277df9', '48a9e858-eba8-4d2e-ba3d-294af3fd0906', 1, 'A honeytoken, since honeytokens are the standard tool for physically preventing write commands from reaching a storage device during forensic examination.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3720bca6-0132-4a68-bd11-1721d7a239c9', '48a9e858-eba8-4d2e-ba3d-294af3fd0906', 2, 'A SOAR playbook, since SOAR playbooks are specifically designed to prevent write access to storage media during a forensic investigation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('06151409-4ef3-474c-b4f0-e853e9df343b', '48a9e858-eba8-4d2e-ba3d-294af3fd0906', 3, 'No tool or technique can guarantee that examining a hard drive''s contents leaves the original data completely unmodified.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('48a9e858-eba8-4d2e-ba3d-294af3fd0906', '6cbee749-8fbb-41a4-890d-46cfd62672f6', 'A write blocker is specifically the standard forensic tool for this exact guarantee — sitting between the original evidence media and the examining system, it intercepts and rejects any write command before it can reach the original drive, while still allowing legitimate read access, so an analyst can safely create a forensic image (a complete, verified bit-for-bit copy, typically confirmed with a cryptographic hash — connecting to the hashing/integrity concept covered in Paper 2 — matching before and after imaging) without any risk of altering the original evidence in the process. This directly supports chain of custody (covered in Paper 1) and the broader admissibility of evidence in any later legal proceeding — evidence that was even accidentally modified during examination has a real, documented, and damaging credibility problem, which is exactly why write blockers are treated as a mandatory, standard tool in real forensic practice rather than an optional precaution. A honeytoken (a decoy credential or file used as a tripwire, distinct from write-blocking) and a SOAR playbook (an automated incident-response action sequence, covered in Paper 4) are both genuinely unrelated tools to this specific evidence-preservation need.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('2b1b2845-97a3-41f5-9853-f91070eadb68', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 11, 'A security team runs two different types of vulnerability scans against the same server: one scan has no login credentials and can only see what''s visible from outside (open ports, banner information), while the other scan logs in with valid credentials and can inspect the actual installed software versions and configuration settings from inside the system. What is the key practical difference in the depth and accuracy of findings between these two scan types?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0ad678c6-0eed-49de-aeb2-4e9effd58319', '2b1b2845-97a3-41f5-9853-f91070eadb68', 0, 'A non-credentialed scan sees only what''s visible externally (open ports, service banners, responses to network probes), typically producing a less detailed, sometimes less accurate picture, while a credentialed scan logs in and directly inspects actual installed package versions, patch levels, and configuration settings from inside the system, generally producing more accurate, more detailed findings with fewer false positives/negatives, at the cost of needing valid credentials provisioned for the scanner ahead of time.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('83c377ca-6502-4e76-b203-3c1221f94fba', '2b1b2845-97a3-41f5-9853-f91070eadb68', 1, 'A credentialed scan can only see externally visible information like open ports, while a non-credentialed scan directly inspects internal installed software versions and configuration settings.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3c2957cb-a325-45b4-a816-ace513f007a4', '2b1b2845-97a3-41f5-9853-f91070eadb68', 2, 'Credentialed and non-credentialed scans always produce identical results with no difference in depth, detail, or accuracy.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('14cce3eb-22bc-4590-aa58-8773449372ae', '2b1b2845-97a3-41f5-9853-f91070eadb68', 3, 'Vulnerability scanning can only ever be performed as a non-credentialed scan; credentialed scanning does not exist as a real technique.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('2b1b2845-97a3-41f5-9853-f91070eadb68', '0ad678c6-0eed-49de-aeb2-4e9effd58319', 'This refines the general vulnerability scanning concept (covered in Paper 1, and the broader vulnerability management lifecycle covering prioritization/verification in Paper 3) with a genuinely important practical distinction: a non-credentialed scan is limited to what''s observable from OUTSIDE the system with no login (open ports, service banners, how the system responds to specific network probes) — useful for understanding what an external attacker with no valid credentials could see, but it can miss vulnerabilities in software or configurations that aren''t visible externally, and can also produce false positives from imprecise external fingerprinting (e.g., guessing a software version from a banner that turns out to be wrong or has been deliberately obscured). A credentialed scan authenticates directly to the target system and inspects ACTUAL installed package versions, patch levels, and configuration settings from the inside, generally producing a meaningfully more accurate and detailed picture with fewer false positives/negatives — the trade-off being the operational overhead of provisioning and securely managing scanner credentials across the target fleet. Both scan types are real, standard, and commonly used for different purposes (external-attacker-perspective vs. internal-configuration-accuracy) — this is not a case where one approach is meaningless or non-existent, nor are the two descriptions reversible.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('d2116281-9249-4071-9f8d-057c1d6ab824', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 12, 'A security team wants ongoing visibility into every device, service, and application that is internet-facing or otherwise reachable across the organization''s entire environment — including systems that might have been stood up by an individual team without going through the normal, centrally-tracked provisioning process ("shadow IT"). What security operations practice specifically addresses maintaining this kind of continuously up-to-date, comprehensive inventory and exposure visibility?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b0c555d6-932b-4381-8d43-77f6e1f5f198', 'd2116281-9249-4071-9f8d-057c1d6ab824', 0, 'Attack surface management — continuously discovering, inventorying, and monitoring every internet-facing and internally-reachable asset across an organization''s real environment (including previously-unknown or informally-provisioned "shadow IT" systems that never went through the normal, centrally-tracked process), specifically because a security team cannot properly assess or reduce risk on assets it doesn''t even know exist.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d6de6eb0-3c23-4a31-b83d-da7ee568b7fa', 'd2116281-9249-4071-9f8d-057c1d6ab824', 1, 'A legal hold, since legal holds are the standard practice for maintaining a continuously updated inventory of internet-facing assets across an organization.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('117e97c9-77f2-498b-827d-9be4c2e922f2', 'd2116281-9249-4071-9f8d-057c1d6ab824', 2, 'Mandatory vacation, since mandatory vacation policies are specifically designed to maintain visibility into an organization''s internet-facing and internally-reachable assets.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e4b1faec-75af-4aee-adac-47dca7193229', 'd2116281-9249-4071-9f8d-057c1d6ab824', 3, 'An organization''s asset inventory is always automatically complete and accurate with no ongoing effort required, including any systems provisioned outside the normal process.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('d2116281-9249-4071-9f8d-057c1d6ab824', 'b0c555d6-932b-4381-8d43-77f6e1f5f198', 'Attack surface management addresses a genuinely foundational security gap: a huge share of real-world security risk comes specifically from assets a security team doesn''t even know exist — a "shadow IT" system stood up by an individual team for a quick need, an old server that was supposed to be decommissioned but wasn''t, or a misconfigured cloud resource nobody centrally tracked — and no other security control (patching, monitoring, access control) can meaningfully protect an asset that isn''t even in the organization''s known inventory in the first place, since you cannot secure what you don''t know exists. Attack surface management specifically addresses this through continuous, ongoing discovery (not a one-time inventory snapshot) of everything internet-facing or internally reachable, deliberately looking for exactly the kind of informally-provisioned systems that fall outside normal, centrally-tracked processes. This connects to, but is a broader, more continuous practice than, vulnerability scanning (covered in Paper 1 and refined earlier this paper) — scanning finds weaknesses in KNOWN assets, while attack surface management specifically works to first ensure the asset inventory itself is actually complete and current, a genuinely real and ongoing operational challenge, not something that happens automatically with no effort.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('d73c8d30-70dd-4640-8bac-53f0b9aa10a5', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 13, 'During a significant security incident, a company activates its incident response team, which includes clearly designated roles: one person coordinating overall response and communication, technical analysts investigating and containing the threat, a legal representative advising on regulatory/notification obligations, and a communications lead managing external messaging. What is this kind of dedicated, cross-functional incident response team commonly called, and why does defining roles in advance matter?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('112a1633-0d72-45c4-b247-513bba0c3028', 'd73c8d30-70dd-4640-8bac-53f0b9aa10a5', 0, 'A CSIRT (Computer Security Incident Response Team) — a dedicated, cross-functional team with clearly pre-defined roles (incident commander/coordinator, technical analysts, legal, communications, and often others depending on the organization) that activates during a significant incident; defining these roles IN ADVANCE (rather than figuring it out during an active, high-pressure incident) matters because it eliminates confusion about who''s responsible for what at exactly the moment that confusion would be most costly and time-sensitive.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f3f8ccfb-9e63-4313-b1ae-e17fb369445d', 'd73c8d30-70dd-4640-8bac-53f0b9aa10a5', 1, 'A honeynet, since honeynets are defined as a cross-functional team with pre-designated incident commander, technical, legal, and communications roles.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('68e31667-c5ad-478e-886e-68bc9899ab7f', 'd73c8d30-70dd-4640-8bac-53f0b9aa10a5', 2, 'An SLA (Service Level Agreement), since SLAs specifically define the incident commander, technical analyst, legal, and communications roles activated during a security incident.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7edd9be3-a70d-4327-928d-8ae820017bca', 'd73c8d30-70dd-4640-8bac-53f0b9aa10a5', 3, 'Defining incident response roles in advance provides no real benefit, since roles can always be assigned equally effectively in the middle of an active incident with no downside.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('d73c8d30-70dd-4640-8bac-53f0b9aa10a5', '112a1633-0d72-45c4-b247-513bba0c3028', 'A CSIRT is specifically the dedicated, cross-functional team structure organizations stand up (or maintain on an ongoing basis) for coordinated incident response, with roles spanning well beyond just technical investigation — legal representation is critical for navigating breach notification law obligations (covered in Paper 2) correctly and on the right timeline, and a communications lead ensures external messaging (to customers, regulators, or media) is accurate and consistent rather than ad-hoc and potentially damaging or legally risky if handled by whoever happens to be available. The real, practical reason to define these roles IN ADVANCE rather than improvising during an active incident is that a genuine incident is precisely the highest-pressure, most time-sensitive moment to be figuring out "wait, whose job is it to talk to the regulator" — pre-defined roles (directly connecting to the RACI matrix concept covered in Paper 4, applied specifically to incident response) eliminate exactly that costly confusion at exactly the worst possible time to have it. A honeynet (covered in Paper 2) is a deliberate decoy environment, and an SLA is a service-performance commitment between parties — both entirely unrelated to incident response team structure.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('2cd95d6e-1142-40a0-a7cd-519aa7475979', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 14, 'A security team creates a fake database record for a customer named "Test Customer 000001" that no legitimate system or process ever actually queries or touches, then configures an alert to trigger immediately if that specific record is EVER accessed by anyone. What is this decoy technique called, and how does it differ from a honeynet?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('61df6d99-1e67-451d-bf4c-f14fede17c88', '2cd95d6e-1142-40a0-a7cd-519aa7475979', 0, 'A honeytoken — a single decoy piece of DATA (a fake record, credential, file, or API key) planted specifically to have no legitimate reason to ever be accessed, so that ANY access to it is a near-certain signal of unauthorized/malicious activity; this differs from a honeynet (covered in Paper 2), which is an entire decoy NETWORK/ENVIRONMENT built to attract and study attacker behavior in depth, rather than a single, narrow tripwire data point.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('aab9ccef-0210-4424-86b3-ccce84e54cea', '2cd95d6e-1142-40a0-a7cd-519aa7475979', 1, 'A honeynet, since honeynets are specifically defined as a single fake database record configured to trigger an alert upon access.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('05696fc2-ef03-43cf-95e2-dd1af1280675', '2cd95d6e-1142-40a0-a7cd-519aa7475979', 2, 'A write blocker, since write blockers are the standard tool for creating fake decoy database records that trigger an alert when accessed.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b3062298-c075-4eca-83b8-ce1d734d7b6a', '2cd95d6e-1142-40a0-a7cd-519aa7475979', 3, 'This technique provides no real detection value, since a fake record with no legitimate purpose could never meaningfully indicate unauthorized activity.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('2cd95d6e-1142-40a0-a7cd-519aa7475979', '61df6d99-1e67-451d-bf4c-f14fede17c88', 'A honeytoken is specifically a single, narrow decoy DATA point (as opposed to an entire decoy environment) — precisely because it has no legitimate business reason to ever be touched by any real user or process, essentially ANY interaction with it is an extremely high-confidence signal that something unauthorized is happening, whether an external attacker who''s gained unauthorized database access and is browsing records, or an insider threat (covered earlier this paper) doing the same. This makes honeytokens a genuinely useful, low-noise detective control specifically because legitimate activity essentially never triggers a false positive against them, unlike broader anomaly-detection approaches that have to distinguish subtler patterns. The key distinction from a honeynet (covered in Paper 2) is scope and purpose: a honeynet is a full, deliberately vulnerable-looking decoy NETWORK/ENVIRONMENT built to draw attackers in and let defenders study their techniques over an extended interaction, while a honeytoken is a single, narrow tripwire data point requiring no elaborate environment at all — related decoy-based concepts, but genuinely different in scale and mechanism, a distinction worth being precise about rather than treating the two terms as interchangeable.');

-- ── Domain: Security Program Management & Oversight (20% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('8b3ced56-3daa-4d59-8ea4-184a673f1ca0', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 15, 'A security governance team maintains a living document listing every identified risk to the organization, along with each risk''s estimated likelihood, potential impact, a named owner responsible for managing it, and its current treatment status (accepted, mitigated, transferred, or avoided). What is this document called, and what is its ongoing governance purpose?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ee5a3006-3cd2-48d0-bdb8-cb01334f20fe', '8b3ced56-3daa-4d59-8ea4-184a673f1ca0', 0, 'A risk register — a living, continuously maintained record of every identified risk, tracking its likelihood, impact, assigned owner, and current treatment status (accepted, mitigated, transferred, or avoided); its ongoing governance purpose is providing leadership a single, centralized, current view of the organization''s full risk landscape, so risk-related decisions are made deliberately and with full visibility rather than piecemeal and forgotten once a risk is initially identified.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('aecb7178-8896-46a1-ae87-e5879e0de415', '8b3ced56-3daa-4d59-8ea4-184a673f1ca0', 1, 'A RACI matrix, since RACI matrices are specifically defined as tracking every identified risk''s likelihood, impact, owner, and treatment status.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1c9f4097-ac33-40fa-9246-df9000c0406f', '8b3ced56-3daa-4d59-8ea4-184a673f1ca0', 2, 'An AUP (Acceptable Use Policy), since AUPs are the standard document for tracking organizational risk likelihood, impact, ownership, and treatment status.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f1d9467f-bb75-468f-bc95-c85e659cb108', '8b3ced56-3daa-4d59-8ea4-184a673f1ca0', 3, 'Once a risk is initially identified and documented one time, no ongoing tracking or maintenance of that record is necessary or useful.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('8b3ced56-3daa-4d59-8ea4-184a673f1ca0', 'ee5a3006-3cd2-48d0-bdb8-cb01334f20fe', 'A risk register is specifically the standing, continuously-maintained governance artifact for tracking an organization''s FULL risk landscape over time — not a one-time snapshot, but a living record that gets updated as risks are newly identified, as their likelihood/impact estimates change, as treatment decisions are made (connecting directly to risk acceptance, covered in Paper 1, as one of the four standard risk TREATMENT options alongside mitigating, transferring — e.g., via cyber insurance, covered in Paper 2 — or avoiding a risk entirely), and as ownership changes. Its real governance value is giving leadership ONE centralized, current, comprehensive view of risk across the whole organization, rather than risk knowledge living only in individual people''s heads or scattered across disconnected conversations and easily forgotten once a risk is first noted — directly supporting informed, deliberate, and accountable risk-related decision-making at a leadership level. A RACI matrix (covered in Paper 4) assigns ROLES for a specific task or decision, and an AUP (covered in Paper 2) governs acceptable employee IT usage — both real, useful governance tools, but neither is the risk-tracking artifact itself.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('530b87f0-257a-43c8-93fa-9f46ba602fc9', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 16, 'A company processing personal data of EU residents (connecting to the GDPR concept covered in a prior paper) appoints a specific, designated individual whose formal responsibility is overseeing the organization''s data protection compliance, serving as a point of contact for regulators, and advising on privacy-impact considerations for new projects. What is this specific governance role called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5f8eaa3f-f2da-4a42-bd03-960a2c9bd3a3', '530b87f0-257a-43c8-93fa-9f46ba602fc9', 0, 'A Data Protection Officer (DPO) — a formally designated individual responsible for overseeing an organization''s data protection compliance, serving as a point of contact for data protection regulators and for individuals exercising their data rights, and advising on privacy considerations for new projects or data-processing activities; certain organizations processing personal data at scale (particularly under GDPR) are specifically required to designate one.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b9bff423-95c0-4f90-b929-71cacc646f72', '530b87f0-257a-43c8-93fa-9f46ba602fc9', 1, 'A bastion host, since a bastion host is specifically defined as a designated individual overseeing an organization''s data protection compliance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6fb60e1c-4fda-4ebb-b153-2a586265852a', '530b87f0-257a-43c8-93fa-9f46ba602fc9', 2, 'A CSIRT, since a CSIRT is specifically the individual role responsible for ongoing data protection compliance oversight and serving as the regulator point of contact.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('121bf076-e014-49d8-9b9c-5ee62a067172', '530b87f0-257a-43c8-93fa-9f46ba602fc9', 3, 'No formal, named governance role exists anywhere for overseeing an organization''s data protection compliance on an ongoing basis.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('530b87f0-257a-43c8-93fa-9f46ba602fc9', '5f8eaa3f-f2da-4a42-bd03-960a2c9bd3a3', 'A Data Protection Officer is specifically the named, formal governance ROLE (a person, not a document or technical control) responsible for an organization''s ongoing data protection compliance posture — this is a genuinely distinct, real, and in many cases LEGALLY REQUIRED position under frameworks like GDPR (covered in Paper 4) for organizations meeting certain data-processing-scale thresholds, tasked with monitoring compliance, serving as the accessible point of contact both for regulators and for individuals wanting to exercise their own data rights (like requesting what personal data is held about them), and advising on privacy considerations proactively as new projects or data uses are being designed, rather than only reacting after a problem has already occurred. This is a meaningfully different concept from a CSIRT (covered earlier this paper, an incident-response TEAM activated during a security incident, not an ongoing individual compliance role) and from a bastion host (covered in Paper 3, an entirely unrelated NETWORK ARCHITECTURE concept, not a governance role at all) — this is a real, standard, and in many contexts mandatory governance position, not a hypothetical or non-existent one.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('41ac958c-cdca-4ba7-8547-7ac4d9b08820', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 17, 'A company adopts a widely recognized structure (like the NIST Cybersecurity Framework or ISO 27001) that organizes security practices into standard categories and provides a common structure for assessing and communicating security maturity — without itself being a specific, legally-binding regulation the way a law like HIPAA is. What is this kind of adopted structure generally called, and how does it differ from a specific regulatory requirement?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f0251027-30ab-4fc7-afb1-43819210a3fa', '41ac958c-cdca-4ba7-8547-7ac4d9b08820', 0, 'A security framework/standard — a structured, widely recognized set of best-practice categories and guidance (like NIST CSF or ISO 27001) that an organization can voluntarily adopt to organize its security program and communicate its maturity in a common, recognizable structure; this differs from a specific regulation (like HIPAA, covered in Paper 1, or GDPR, covered in Paper 4) in that a framework is generally not itself a legally-binding requirement (though it can be REFERENCED or effectively required within a specific contract, industry certification, or regulation), while a regulation carries direct legal force and specific penalties for non-compliance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cc22a592-32a6-4807-9870-12d42fdace71', '41ac958c-cdca-4ba7-8547-7ac4d9b08820', 1, 'A risk register, since risk registers are specifically defined as a widely recognized structure like NIST CSF or ISO 27001 for organizing security best practices.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bd29b3ce-02f9-4a3e-859d-82373b13a0c8', '41ac958c-cdca-4ba7-8547-7ac4d9b08820', 2, 'An attack surface management program, since attack surface management is specifically defined as adopting a recognized security framework like NIST CSF or ISO 27001.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ce4aef6d-5418-4755-9d44-796a29b84092', '41ac958c-cdca-4ba7-8547-7ac4d9b08820', 3, 'A security framework and a specific legal regulation are functionally and legally identical in every respect, with no meaningful distinction between them.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('41ac958c-cdca-4ba7-8547-7ac4d9b08820', 'f0251027-30ab-4fc7-afb1-43819210a3fa', 'A security framework/standard provides a structured, common vocabulary and set of categories (like NIST CSF''s core functions, or ISO 27001''s control domains) that an organization can voluntarily adopt to organize, assess, and communicate its security program''s maturity in a way that''s recognizable to auditors, partners, and other outside parties — connecting directly to the third-party audits concept covered in Paper 2, since an audit is frequently performed specifically AGAINST a named framework''s standard. The genuinely important, testable distinction from a specific REGULATION (like HIPAA, covered in Paper 1, a legally-binding requirement with specific penalties for non-compliance) is that adopting a framework is typically voluntary on its own — though a framework can still become EFFECTIVELY mandatory through a specific contract requiring it, an industry certification requiring it, or because a regulation itself references or requires alignment with a specific framework''s controls. This is a real, meaningful distinction the exam tests directly — a framework and a specific binding law are not the same category of thing, even though organizations often pursue both together as part of the same overall compliance and governance program.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('4da24a4a-150b-48cf-8f84-bb231c74d327', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 18, 'A company''s board of directors formally decides "we are willing to accept a moderate level of operational risk in exchange for faster product delivery, but we will not accept any risk that could result in a regulatory fine or public data breach" — a general, organization-wide policy statement about how much risk the company is willing to tolerate, made BEFORE any specific individual risk is being evaluated. What is this kind of overarching, board-level statement called, and how does it differ from a decision to accept one specific, already-identified risk?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f4e35074-773d-495a-88a4-00189c92253e', '4da24a4a-150b-48cf-8f84-bb231c74d327', 0, 'Risk appetite (or risk tolerance) — a general, organization-wide statement of how much risk a company is willing to accept in pursuit of its objectives, set at a governance/board level BEFORE any specific individual risk is evaluated; this differs from risk acceptance (covered in Paper 1), which is a decision made about one SPECIFIC, already-identified risk, ideally guided by the organization''s previously-established risk appetite rather than decided independently and inconsistently case by case.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8cd06b5d-c833-4711-a8ce-3c32844fba12', '4da24a4a-150b-48cf-8f84-bb231c74d327', 1, 'A honeytoken, since honeytokens are specifically defined as a board-level, organization-wide policy statement about acceptable risk tolerance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cf54c89a-459e-4407-accf-90970539bd8e', '4da24a4a-150b-48cf-8f84-bb231c74d327', 2, 'Risk acceptance, since risk acceptance and this general, organization-wide policy statement are the exact same concept with no meaningful distinction.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('26a26d7e-f0dd-4c19-bce7-027864ccd5f5', '4da24a4a-150b-48cf-8f84-bb231c74d327', 3, 'Organizations never make general, advance statements about their overall risk tolerance; every risk decision is always made in complete isolation with no consistent guiding principle.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('4da24a4a-150b-48cf-8f84-bb231c74d327', 'f4e35074-773d-495a-88a4-00189c92253e', 'Risk appetite (sometimes called risk tolerance) is specifically a GENERAL, forward-looking, governance-level statement of how much risk an organization is willing to accept overall in pursuit of its objectives, established BEFORE any individual, specific risk is on the table — providing consistent guidance for later, individual risk decisions rather than leaving each one to be decided independently with no shared reference point. This is a genuinely important, testable distinction from risk acceptance (covered in Paper 1): risk acceptance is the decision made about one SPECIFIC, already-identified risk (e.g., "we accept the risk of not implementing control X because the cost of mitigation exceeds the potential impact"), and IDEALLY that specific decision is made consistently WITHIN the boundaries the organization''s risk appetite already established, rather than each specific risk decision being made in a vacuum with no connection to any broader, deliberate risk-tolerance policy. This directly complements the risk register (covered earlier this paper), which tracks individual risks and their treatment — risk appetite is the governing policy context those individual, specific decisions should operate within, not the same concept restated under a different name.');

-- ── Domain: Threats, Vulnerabilities & Mitigations (additional — question 19) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('43bff02a-ce5b-4fb4-9324-e4030ed4d1f9', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 19, 'An application written in a memory-unsafe language accepts user input into a fixed-size memory buffer without validating the input''s length. An attacker submits input deliberately longer than that buffer, overwriting adjacent memory (potentially including the program''s own execution instructions) and causing the application to crash or, in a more severe case, execute attacker-supplied code. What is this specific class of vulnerability called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bbd94bac-31b9-4fe9-8e20-b5647a456848', '43bff02a-ce5b-4fb4-9324-e4030ed4d1f9', 0, 'A buffer overflow — occurs when a program writes more data into a fixed-size memory buffer than that buffer was actually allocated to hold, and without proper bounds checking, that excess data overwrites adjacent memory; at minimum this typically crashes the program (a denial-of-service effect), but if the attacker carefully controls what gets written into the overwritten memory, it can potentially lead to arbitrary code execution, making this a genuinely severe, foundational memory-safety vulnerability class.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d18369dd-ced1-4748-9ae5-8b635c648a5f', '43bff02a-ce5b-4fb4-9324-e4030ed4d1f9', 1, 'Credential stuffing, since credential stuffing is defined as writing more data into a fixed-size memory buffer than it was allocated to hold.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fc3c57ee-1981-4541-b521-457438c14214', '43bff02a-ce5b-4fb4-9324-e4030ed4d1f9', 2, 'A supply chain attack, since supply chain attacks are defined as overwriting adjacent memory by submitting input longer than an allocated buffer.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f487f074-77f6-4098-86e5-b717fd371830', '43bff02a-ce5b-4fb4-9324-e4030ed4d1f9', 3, 'This scenario cannot actually cause a program to crash or behave unexpectedly, since input length has no real effect on memory allocated for it.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('43bff02a-ce5b-4fb4-9324-e4030ed4d1f9', 'bbd94bac-31b9-4fe9-8e20-b5647a456848', 'A buffer overflow is specifically a MEMORY-SAFETY vulnerability, distinct in mechanism from every other vulnerability class covered so far — SQL injection (covered in Paper 1) manipulates a database QUERY via unsanitized input, and CSRF/XSS (covered in Paper 3) exploit browser trust/session behavior or inject script, while a buffer overflow operates at a lower level entirely, directly on how a program manages its own memory: writing past the end of an allocated buffer corrupts whatever memory sits adjacent to it, which — depending on exactly what''s overwritten and how precisely an attacker can control the overflow''s content — can range from a simple crash (the program encounters corrupted, nonsensical state and halts, a denial-of-service outcome) up to full arbitrary code execution if the attacker can overwrite something like a return address with a location pointing to their own injected code. This is exactly why memory-safe programming languages (which perform automatic bounds checking) and secure coding practices (explicit input-length validation before writing into any fixed buffer) are standard, foundational mitigations specifically targeting this vulnerability class — buffer overflows are a real, well-documented, and historically extremely significant vulnerability category (underlying many major real-world exploits), not a theoretical impossibility.');

-- ── Domain: Security Architecture (additional — question 20) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('075424c1-9157-48f8-8032-2992a048afe7', '7be2ac0d-9ce2-4fc2-9d37-5b76e5b64552', 20, 'A company exposes a REST API to external partner applications, allowing them to query and update customer data programmatically. The security team wants to ensure each calling application is properly authenticated, that no single application can overwhelm the API with excessive request volume, and that each application can only access the specific data it''s been authorized for. What set of concerns does this describe, and what mechanisms address them?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a6fd2235-b838-4a49-9dcb-161ea4350e4b', '075424c1-9157-48f8-8032-2992a048afe7', 0, 'API security — addressed through API keys or OAuth tokens for authenticating each calling application, rate limiting (often enforced at an API gateway) to prevent any single caller from overwhelming the API with excessive volume, and fine-grained authorization scoping so each authenticated caller can only access the specific data/operations it''s actually been granted, rather than broad, undifferentiated access to the entire API surface once any valid credential is presented.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0589fcc6-8f35-4eb8-8402-bd655da9c3c6', '075424c1-9157-48f8-8032-2992a048afe7', 1, 'An air-gapped network, since air-gapped networks are the standard mechanism for authenticating external partner applications and rate-limiting their API request volume.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6f751212-65f9-4db9-ba69-51cea64e9dc7', '075424c1-9157-48f8-8032-2992a048afe7', 2, 'A honeytoken, since honeytokens are specifically used to authenticate calling applications and enforce per-application rate limits on a REST API.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8e6f5ddc-9b89-481c-9eec-60180523d161', '075424c1-9157-48f8-8032-2992a048afe7', 3, 'Once a REST API is deployed, no further authentication, rate limiting, or access scoping is possible or necessary for any calling application.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('075424c1-9157-48f8-8032-2992a048afe7', 'a6fd2235-b838-4a49-9dcb-161ea4350e4b', 'API security specifically addresses this exact combination of concerns for programmatic, application-to-application access, distinct from the more general access-control concepts covered elsewhere: authentication (verifying WHICH calling application is making a request, typically via an API key or an OAuth-issued token, connecting to the identity-verification piece of the AAA framework covered in Paper 3), rate limiting (a specific technical control — often enforced at an API gateway sitting in front of the actual API — that caps how many requests a given caller can make in a given time window, protecting against both accidental runaway callers and deliberate abuse, distinct from DDoS mitigation, covered in Paper 4, though related in spirit), and authorization scoping (ensuring an authenticated caller''s access is limited to specifically what THAT application has been granted, rather than blanket access to everything once any valid credential is presented — directly applying the least privilege principle, covered in Paper 1, at the API-caller level). This is a real, standard, and increasingly critical security architecture domain specifically because APIs are frequently the DIRECT path external systems use to reach sensitive internal data, making these controls a first-line defense rather than an afterthought — an air-gapped network (covered in Paper 3, the complete absence of connectivity) and a honeytoken (covered earlier this paper, a decoy data tripwire) are both genuinely unrelated concepts to authenticating and rate-limiting a live, intentionally-exposed API.');
