-- ============================================================
-- CompTIA Security+ (SY0-701) — Seed Data: Paper 7
-- New content, distinct topics from Papers 1-6 — no repeated scenarios.
-- Topic list checked directly against the actual question text of Papers
-- 1-6 (grepped from the files, not recalled from memory) before writing,
-- continuing the discipline adopted after Paper 4's duplication bug.
-- The question_papers ARRAY[...]::TEXT[] literal and every option token
-- were manually re-read once before running the fill script, after Paper
-- 6 was found to have both a duplicated option token and a stray syntax
-- error at this exact stage.
-- Same domain weighting: General Security Concepts 12% (2/20), Threats/
-- Vulnerabilities/Mitigations 22% (4/20), Security Architecture 18%
-- (4/20), Security Operations 28% (6/20), Security Program Management &
-- Oversight 20% (4/20).
--
-- IDs were generated via scripts/fill-seed-uuids.mjs, which replaces every
-- distinct placeholder token with a fresh, real UUID (consistently across
-- every occurrence) — this file has already had that script run against
-- it; the UUIDs below are real. Cross-checked against every other seed
-- file in the repo for zero collisions before finalizing, plus the
-- distractor-language sanity scan and a manual re-read of every answer key
-- against its option text.
-- Run this AFTER docs/question-bank-schema.sql.
-- ============================================================

INSERT INTO question_papers (id, slug, title, exam_type, focus_tags, question_count, difficulty, is_premium, sort_order, time_limit_minutes)
VALUES ('62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 'secplus-practice-7', 'CompTIA Security+ (SY0-701) Practice Paper 7', 'comptia-sec-plus', ARRAY['Quantitative Risk', 'ARP Poisoning', 'Tokenization', 'CASB', 'SBOM', 'CVSS', 'OCSP vs CRL', 'MTTD/MTTR', 'PCI-DSS', 'BAA']::TEXT[], 20, 'standard', true, 7, 30);

-- ── Domain: General Security Concepts (12% — 2 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('cb3f5f83-4dee-48a1-944d-4820530113be', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 1, 'A risk assessment team wants to express a specific risk in concrete dollar terms: an asset worth $500,000 has a 20% chance of being fully lost in any given year due to a specific threat. What is the calculated annual expected loss called, and what is the standard formula for it?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e98d3645-974c-467f-8c0d-3795da6595fe', 'cb3f5f83-4dee-48a1-944d-4820530113be', 0, 'This is Annualized Loss Expectancy (ALE) — calculated as Single Loss Expectancy (SLE, the monetary loss from ONE occurrence — here $500,000, the asset''s full value) multiplied by the Annualized Rate of Occurrence (ARO, how many times per year the event is expected to happen — here 0.20, since a 20% annual chance equates to an ARO of 0.2), giving ALE = $500,000 × 0.20 = $100,000 per year; this quantitative approach expresses risk in concrete financial terms, distinct from a QUALITATIVE risk assessment, which instead uses relative categories like High/Medium/Low without assigning specific dollar figures.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('be007761-586c-4f53-9a79-9ef704573f86', 'cb3f5f83-4dee-48a1-944d-4820530113be', 1, 'This is a risk register, since risk registers are specifically defined as the formula multiplying Single Loss Expectancy by the Annualized Rate of Occurrence.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cc6ca84a-3df9-435b-9d6b-5c8e8a6359ed', 'cb3f5f83-4dee-48a1-944d-4820530113be', 2, 'This is a gap analysis, since gap analyses are specifically defined as calculating an asset''s Single Loss Expectancy multiplied by its Annualized Rate of Occurrence.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('00956f8f-4f71-40fa-80ec-0f9cb176b8f2', 'cb3f5f83-4dee-48a1-944d-4820530113be', 3, 'Risk can never be meaningfully expressed in specific quantitative dollar terms; only qualitative High/Medium/Low categories are ever used in risk assessment.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('cb3f5f83-4dee-48a1-944d-4820530113be', 'e98d3645-974c-467f-8c0d-3795da6595fe', 'ALE is the standard quantitative risk metric specifically designed to express risk in concrete, comparable financial terms, built from two component figures: SLE (the dollar impact of ONE occurrence of the risk event — here, the asset''s full $500,000 value, assuming total loss) and ARO (how frequently, on average, that event is expected to occur per year — here 0.20, derived directly from the stated 20% annual likelihood). Multiplying these gives ALE = $100,000/year, a figure that''s directly useful for cost-benefit comparisons — for instance, weighing this $100,000 annual expected loss against the ANNUAL cost of a specific mitigating control, connecting directly to the risk acceptance concept covered in a prior paper (a control costing more per year than the ALE it would reduce may reasonably be judged not worth implementing). This quantitative approach is genuinely distinct from qualitative risk assessment, which instead uses relative, non-monetary categories (High/Medium/Low, or a numbered scale) — a real, complementary alternative approach used when precise dollar figures for asset value or event likelihood aren''t reliably available, not the only valid risk assessment method as the last distractor implies.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('10fe7152-90ce-4bd7-99e6-7389a6f32e81', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 2, 'A company relies on the fact that their custom-built network protocol''s technical details are not publicly documented as their PRIMARY defense against attack, believing that if attackers don''t know how the protocol works, they can''t exploit it — with no other meaningful security control layered on top. What is the flaw in relying on undisclosed technical details as a SOLE security control called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ca66de53-2f09-46f6-b4a9-bb6892af53cf', '10fe7152-90ce-4bd7-99e6-7389a6f32e81', 0, 'Security through obscurity — relying on the secrecy of a system''s design or implementation details as the PRIMARY or SOLE protection mechanism, rather than on genuinely robust, independently-verifiable security controls; this is considered a flawed sole strategy specifically because once the obscured details are discovered (through reverse engineering, an insider leak, or independent research — a real, common occurrence), NO underlying protection remains at all, whereas obscurity used as one MINOR, additional layer alongside genuinely robust controls (defense-in-depth, covered in a prior paper) is a different, more defensible use of the same underlying idea.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e7c71210-c007-45bb-90f5-711d079c333f', '10fe7152-90ce-4bd7-99e6-7389a6f32e81', 1, 'Defense-in-depth, since defense-in-depth is specifically defined as relying solely on undisclosed technical details as a system''s only protection mechanism.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8612059c-6b77-4c17-b697-833c90fae095', '10fe7152-90ce-4bd7-99e6-7389a6f32e81', 2, 'Zero Trust, since Zero Trust is specifically defined as relying on the secrecy of a system''s design as its primary and sole security control.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('da0f1fd7-0d84-41e9-b0a4-ea26d79724f7', '10fe7152-90ce-4bd7-99e6-7389a6f32e81', 3, 'Keeping technical implementation details undisclosed provides no risk of any kind and is always an equally valid, complete security strategy on its own.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('10fe7152-90ce-4bd7-99e6-7389a6f32e81', 'ca66de53-2f09-46f6-b4a9-bb6892af53cf', 'Security through obscurity specifically names the flawed practice of treating SECRECY of design/implementation as a system''s primary or only real protection, rather than genuine, independently-verifiable security controls (strong authentication, encryption, access control) that remain effective even if their existence or general mechanism is publicly known — the fundamental problem is that once obscured details are actually discovered (a real, common occurrence via reverse engineering, an insider leak, or simply independent research eventually finding the same thing), a system relying SOLELY on that secrecy has NOTHING left protecting it, since no other meaningful control was ever actually in place. This is genuinely distinct from defense-in-depth (covered in a prior paper, MULTIPLE independent, overlapping, genuinely robust layers — the opposite philosophy of relying on any single point, secret or otherwise) and from Zero Trust (covered in a prior paper, continuous verification regardless of network position, an entirely different concept). It''s worth noting obscurity isn''t ENTIRELY worthless as a minor, ADDITIONAL layer alongside genuinely robust controls (not revealing unnecessary technical detail publicly has some real, if limited, value) — the flaw specifically being tested here is relying on it as the SOLE or PRIMARY defense, which is a real, well-documented, and historically significant security anti-pattern.');

-- ── Domain: Threats, Vulnerabilities & Mitigations (22% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('751ae6b1-916d-45ca-a2f3-c7288a56af03', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 3, 'An attacker on the same local network segment as a victim sends forged ARP (Address Resolution Protocol) messages, tricking the victim''s device into associating the attacker''s MAC address with the network''s legitimate gateway IP address — causing the victim''s outbound traffic to be silently routed through the attacker''s machine first. What is this Layer 2 network attack called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f2b52a7e-6913-4b1e-8ea6-8ca12bbbe2e1', '751ae6b1-916d-45ca-a2f3-c7288a56af03', 0, 'ARP poisoning (also called ARP spoofing) — sending forged ARP messages on a local network segment to associate the attacker''s own MAC address with a legitimate IP address (typically the default gateway), causing other devices on that segment to unknowingly send their traffic to the attacker''s machine instead of its real intended destination, putting the attacker in a genuine on-path position to intercept, inspect, or modify that traffic — a Layer 2-specific mechanism distinct from DNS poisoning (covered in a prior paper, which manipulates DOMAIN-NAME resolution rather than local network address mapping).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cab633a4-4c2e-4810-b26c-20d78b4ac693', '751ae6b1-916d-45ca-a2f3-c7288a56af03', 1, 'DNS poisoning, since DNS poisoning is specifically defined as forging ARP messages to associate an attacker''s MAC address with a legitimate gateway IP address on a local network segment.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('57955344-3063-4b06-aad9-870b54c895ae', '751ae6b1-916d-45ca-a2f3-c7288a56af03', 2, 'A logic bomb, since logic bombs are defined as forging Layer 2 ARP messages to redirect a victim''s local network traffic through an attacker''s machine.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b65a68ff-6768-4057-aa02-0a539a62407f', '751ae6b1-916d-45ca-a2f3-c7288a56af03', 3, 'ARP messages cannot be forged or manipulated by an attacker under any circumstance; a device''s ARP table always reflects only genuine, accurate network information.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('751ae6b1-916d-45ca-a2f3-c7288a56af03', 'f2b52a7e-6913-4b1e-8ea6-8ca12bbbe2e1', 'ARP poisoning specifically exploits the fact that ARP (the protocol mapping IP addresses to physical MAC addresses on a local network segment) was not originally designed with any built-in authentication for the responses it accepts — a device generally just trusts whatever ARP response it receives and updates its local ARP table accordingly, making it possible for an attacker on the same local segment to send forged, unsolicited ARP responses claiming their own MAC address corresponds to the gateway''s (or another target device''s) IP address, silently rerouting the victim''s traffic through the attacker''s machine first, placing the attacker in a genuine ON-PATH position to intercept or manipulate that traffic before it continues to its real destination. This is meaningfully different from DNS poisoning (covered in a prior paper), which operates at a completely different layer — manipulating DOMAIN-NAME-to-IP resolution rather than local-network IP-to-MAC address mapping — both are real, distinct on-path-enabling techniques operating at genuinely different points in the network stack, a common and directly testable point of confusion given their similarly-structured names ("X poisoning"). ARP messages genuinely CAN be forged by design, absent additional protections like Dynamic ARP Inspection on network switches — this is a real, well-documented, and historically significant local-network attack technique, not a technical impossibility.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('94100aed-9d17-4cb7-b121-acc193a752bc', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 4, 'A vulnerable web application constructs file paths by directly appending user-supplied input to a base directory, without validating that input — allowing an attacker to submit a value like "../../../../etc/passwd" to make the application read and return a file completely OUTSIDE the intended directory, potentially exposing sensitive system files never meant to be accessible through the web application at all. What is this vulnerability called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c15afca7-ca48-4cd7-b481-946c14c73bb4', '94100aed-9d17-4cb7-b121-acc193a752bc', 0, 'Directory traversal (also called path traversal) — occurs when an application uses unsanitized user input to construct a file system path, allowing an attacker to include sequences like "../" to navigate OUTSIDE the intended, restricted directory and access arbitrary files elsewhere on the file system that were never meant to be reachable through the application at all, a genuinely different mechanism and target from SQL injection (covered in a prior paper, which manipulates a DATABASE query rather than a file system PATH).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e882ddc5-4c9a-4a84-aa79-2d9353dbc763', '94100aed-9d17-4cb7-b121-acc193a752bc', 1, 'CSRF, since CSRF is defined as using unsanitized user input to construct a file system path and access files outside the intended directory.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7b93d377-eb36-4a78-8fe6-7a77e543f93b', '94100aed-9d17-4cb7-b121-acc193a752bc', 2, 'A buffer overflow, since buffer overflows are defined as using directory-traversal sequences like "../" to access arbitrary files outside an application''s intended directory.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('051d494f-aed0-4187-8325-23e3af790b7d', '94100aed-9d17-4cb7-b121-acc193a752bc', 3, 'This scenario is not a realistic vulnerability, since a web application can never be tricked into reading a file outside its own intended directory regardless of user input.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('94100aed-9d17-4cb7-b121-acc193a752bc', 'c15afca7-ca48-4cd7-b481-946c14c73bb4', 'Directory traversal is specifically a FILE-SYSTEM-PATH manipulation vulnerability — the application trusts unsanitized user input to build a file path directly, and the "../" sequence (meaning "go up one directory level" in most file systems) lets an attacker walk the resulting path outside whatever directory the application intended to restrict access to, potentially reaching sensitive system files (configuration files, credential stores, or in the classic example, a Unix password file) that were never meant to be reachable through the web application''s normal, intended functionality at all. This is a genuinely different mechanism and target from SQL injection (covered in a prior paper, which manipulates a DATABASE QUERY''S structure, not a file system path) and from CSRF (covered in a prior paper, which forges a REQUEST using an already-authenticated victim''s session, an entirely different mechanism) — the standard mitigation is proper input validation and sanitization specifically rejecting or normalizing directory-traversal sequences before ever using user input to construct a file path, plus running the application with the LEAST PRIVILEGE (covered in a prior paper) necessary so even a successful traversal has limited reach. This is a real, well-documented, and historically significant web application vulnerability class, not a hypothetical impossibility.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('2ffe54a9-7ab0-4d06-9330-21968b055449', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 5, 'An attacker successfully sends phishing emails that appear to come FROM a company''s own legitimate domain, even though the attacker has no actual access to that domain''s mail servers, specifically because the domain never published DNS records specifying which mail servers are actually authorized to send email on its behalf. What set of email-authentication DNS records, if properly published and enforced, would have prevented recipients'' mail servers from accepting this spoofed mail as legitimate?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7dfc944f-2766-427b-9ae0-836c23db56f9', '2ffe54a9-7ab0-4d06-9330-21968b055449', 0, 'SPF, DKIM, and DMARC — SPF (Sender Policy Framework) publishes which mail servers are authorized to send email for a domain; DKIM (DomainKeys Identified Mail) cryptographically signs outgoing messages so receivers can verify they genuinely came from the claimed domain and weren''t altered in transit; and DMARC (Domain-based Message Authentication, Reporting & Conformance) tells receiving mail servers what to actually DO (reject, quarantine, or allow) when a message fails SPF/DKIM checks — together, these three records let a receiving mail server reject email falsely claiming to be from a domain that never actually sent it.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('13a7e362-8078-4f2c-8749-7dde0fa894e6', '2ffe54a9-7ab0-4d06-9330-21968b055449', 1, 'MFA, since MFA is the standard DNS record type that specifies which mail servers are authorized to send email on a domain''s behalf.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1c007b46-7665-45e3-b21c-cc978e9a7da5', '2ffe54a9-7ab0-4d06-9330-21968b055449', 2, 'IOCs, since IOCs are the DNS records that cryptographically sign outgoing email and specify enforcement action for messages that fail authentication.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6eebfeb2-a2c1-4de6-a5e9-cf5cf71dbfc8', '2ffe54a9-7ab0-4d06-9330-21968b055449', 3, 'No DNS-based mechanism exists to verify whether an email claiming to be from a specific domain genuinely originated from that domain''s authorized mail servers.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('2ffe54a9-7ab0-4d06-9330-21968b055449', '7dfc944f-2766-427b-9ae0-836c23db56f9', 'SPF, DKIM, and DMARC together form the standard, real email-authentication framework specifically designed to prevent exactly this kind of domain-spoofing phishing — without them published, ANY mail server anywhere can simply claim a message is "From: someone@legitimate-company.com" with no verification mechanism forcing a receiving mail server to check whether that claim is actually true, which is exactly the gap this scenario describes. SPF publishes a DNS record listing which specific mail servers/IP addresses are authorized to send mail for a domain, letting a receiver check whether the ACTUAL sending server matches that authorized list; DKIM adds a cryptographic signature to outgoing mail (verifiable via a public key also published in DNS) proving the message genuinely originated from the claimed domain and wasn''t tampered with in transit; and DMARC ties the two together by publishing an explicit POLICY telling receivers what to actually do with mail that fails those checks (reject it outright, quarantine it as suspicious, or merely monitor/report on failures) — without a properly configured and ENFORCED DMARC policy specifically, SPF and DKIM records alone don''t guarantee receivers will actually reject spoofed mail, they simply enable the check to be performed. This directly connects to BEC and whaling (covered in prior papers, which frequently rely on exactly this kind of domain impersonation) — properly configuring these three record types is a real, standard, and directly impactful mitigation against email-based domain spoofing specifically.');

-- ── Domain: Security Architecture (18% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('eaeb9645-fffb-4976-b4cc-cca47041dc1f', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 6, 'A company deploys encryption at several different levels of granularity across its infrastructure: encrypting an ENTIRE laptop''s hard drive so its contents are unreadable if the device is physically stolen, encrypting just SPECIFIC sensitive files regardless of where they''re copied, and encrypting SPECIFIC fields within a database (like a Social Security number column) while leaving other columns in that same database readable. What are these different granularities of encryption called, and why would a company choose one over another for a given need?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('eaf6efcd-4973-4195-87cd-086f219bd053', 'eaeb9645-fffb-4976-b4cc-cca47041dc1f', 0, 'Full-disk encryption, file-level encryption, and field-level (or column-level) database encryption — full-disk encryption protects against physical device theft specifically (the whole drive is unreadable without the decryption key, but offers no protection once the device is unlocked and running) while file-level and field-level encryption instead protect SPECIFIC data regardless of where it''s copied or which broader system it lives within, at the cost of more granular key/access management complexity — the right granularity depends on the specific threat being addressed, not a one-size-fits-all choice.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e0e897d8-8ed6-4a21-bd5b-446ede744318', 'eaeb9645-fffb-4976-b4cc-cca47041dc1f', 1, 'These three granularities of encryption are functionally identical, providing the exact same protection against the exact same threats with no meaningful distinction between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('52f4a45e-bf04-464c-9103-70eb155a93e9', 'eaeb9645-fffb-4976-b4cc-cca47041dc1f', 2, 'Tokenization, since tokenization is specifically defined as the practice of choosing between full-disk, file-level, and field-level encryption granularity.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('354b2b3b-1352-4d46-a8bf-705db218e484', 'eaeb9645-fffb-4976-b4cc-cca47041dc1f', 3, 'Encryption can only ever be applied to an entire storage device at once; encrypting individual files or specific database fields independently is not technically possible.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('eaeb9645-fffb-4976-b4cc-cca47041dc1f', 'eaf6efcd-4973-4195-87cd-086f219bd053', 'These three granularities genuinely address different real threat scenarios, extending the general encryption/data-states concepts (covered generally in prior papers) with a practical, directly testable "which level of granularity fits which need" distinction: full-disk encryption specifically protects against a device being physically stolen or lost WHILE POWERED OFF/LOCKED — the entire drive is unreadable without the key — but provides essentially no additional protection once the device is unlocked and actively running (at which point the OS and any running application can read the decrypted data normally), which is exactly why it''s not a complete answer on its own for protecting specific sensitive data from, say, an application-level vulnerability or an authorized-but-malicious user already logged into a running system. File-level encryption instead protects a SPECIFIC file regardless of where it''s later copied or moved, remaining encrypted independent of the underlying disk''s encryption status. Field-level (or column-level) database encryption goes even more granular still, encrypting only SPECIFIC sensitive columns (like a Social Security number field) while leaving other, less sensitive columns in the SAME database readable and directly queryable — useful when only a narrow subset of data genuinely needs this extra protection, without encrypting an entire database wholesale. Choosing the right granularity for a given real threat and use case is a genuine, practical architecture decision — not an arbitrary or meaningless one, and certainly not a case where only whole-device encryption is technically achievable.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('41d4e113-08c6-4096-8cc1-4bafde999f1e', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 7, 'A retail company processes credit card numbers but wants to avoid storing the actual, real card numbers anywhere in its own systems beyond the initial transaction moment — instead storing a randomly generated substitute value that has NO mathematical relationship to the original card number and cannot be reverse-computed back to it, while a separate, tightly-controlled vault maps that substitute value back to the real number only when genuinely needed. What is this data-protection technique called, and how does it differ fundamentally from encryption?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2109959e-bd6b-4e1b-b8cc-d94b8a7eb916', '41d4e113-08c6-4096-8cc1-4bafde999f1e', 0, 'Tokenization — replaces sensitive data with a randomly generated, non-mathematically-related substitute value (a "token"), with the actual mapping between token and real value stored ONLY in a separate, tightly-controlled vault; this is fundamentally different from encryption, where the protected value CAN always be mathematically derived back from the ciphertext given the correct key — tokenization''s substitute value has NO such mathematical relationship to the original at all, meaning even a compromise of the tokenized data alone (without also separately compromising the vault) reveals nothing computable about the real value, a genuinely stronger property for reducing the SCOPE of systems that need to handle the truly sensitive original data (directly relevant to PCI-DSS compliance scope reduction).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c2de5c12-24d4-4868-8f7c-398fe1502248', '41d4e113-08c6-4096-8cc1-4bafde999f1e', 1, 'Tokenization and encryption are functionally and mathematically identical techniques, with a token always being mathematically derivable back to the original value using the correct key, just like ciphertext.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7d6103e3-5078-4825-a0fd-346f05b4abf7', '41d4e113-08c6-4096-8cc1-4bafde999f1e', 2, 'A CASB, since CASBs are specifically defined as replacing sensitive data with a randomly generated, non-mathematically-related substitute value stored in a separate vault.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('645eed6d-acca-4699-89a2-d914a838a528', '41d4e113-08c6-4096-8cc1-4bafde999f1e', 3, 'No technique exists for protecting sensitive data other than encryption; storing a substitute value with no mathematical relationship to the original is not technically achievable.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('41d4e113-08c6-4096-8cc1-4bafde999f1e', '2109959e-bd6b-4e1b-b8cc-d94b8a7eb916', 'Tokenization is genuinely, fundamentally different from encryption (covered generally in prior papers) in a way that matters practically, not just terminologically: encrypted ciphertext ALWAYS has a real, mathematical relationship back to the original plaintext — given the correct decryption key, the original value can always be computed back out, meaning the ciphertext itself is a mathematically-derived representation of the real data. A token, by contrast, is typically a RANDOMLY GENERATED value with NO mathematical relationship to the original sensitive value at all — the only way to map a token back to its real underlying value is by looking it up in a separate, tightly-controlled vault/database that holds that specific mapping, meaning the token itself, even if somehow obtained by an attacker, reveals nothing computable about the real card number without ALSO separately compromising that vault. This genuinely reduces the security SCOPE of every OTHER system that only ever needs to handle the token (not the real card number) for its normal operations — directly relevant to reducing PCI-DSS compliance scope, since systems handling only tokens (not real card data) generally fall under meaningfully lighter compliance requirements than systems that directly touch real cardholder data. A CASB (a cloud security architecture concept, addressed in the next question) is an entirely different, unrelated concept — tokenization is a real, standard, and increasingly common technique specifically because of this genuine security property distinguishing it from encryption, not a redundant restatement of it.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('49b4d8c2-cecf-4716-8f95-0139425b629e', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 8, 'A company''s employees increasingly use various third-party cloud SaaS applications (file sharing, collaboration tools) that IT never directly provisioned or has full visibility into, and the security team wants a single control point to enforce consistent security policy (data loss prevention, access control, encryption requirements) across ALL of these cloud services being used, rather than trying to configure security individually within each separate SaaS application''s own settings. What category of security architecture is purpose-built for this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d8c0834e-c3d2-4d8f-8c2a-31b91e13e439', '49b4d8c2-cecf-4716-8f95-0139425b629e', 0, 'A CASB (Cloud Access Security Broker) — sits as an enforcement point BETWEEN an organization''s users and the cloud services they access (whether known/sanctioned or discovered "shadow IT" usage, connecting to the attack surface management concept covered in a prior paper), applying consistent security policies (DLP, covered in a prior paper; access control; encryption requirements; visibility into usage) across MULTIPLE cloud services from one central point, rather than requiring separate, inconsistent configuration within each individual SaaS application''s own native settings.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a87604a8-0ae7-45cd-8d6d-28d3efb6482b', '49b4d8c2-cecf-4716-8f95-0139425b629e', 1, 'A bastion host, since bastion hosts are specifically defined as a single enforcement point applying consistent DLP, access control, and encryption policy across multiple third-party cloud SaaS applications.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f54adead-f476-4806-a720-5ef2178df52f', '49b4d8c2-cecf-4716-8f95-0139425b629e', 2, 'An air-gapped network, since air-gapped networks are the standard architecture for centrally enforcing consistent security policy across multiple cloud SaaS applications.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fa6a6c61-9649-4906-88cd-9d862e9ccb79', '49b4d8c2-cecf-4716-8f95-0139425b629e', 3, 'No architecture exists for centrally enforcing consistent security policy across multiple third-party cloud services; each SaaS application''s security must always be configured entirely independently with no shared control point.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('49b4d8c2-cecf-4716-8f95-0139425b629e', 'd8c0834e-c3d2-4d8f-8c2a-31b91e13e439', 'A CASB fills a genuinely distinct architectural role from SASE (covered in a prior paper, which converges NETWORKING and security functions for a distributed workforce''s CONNECTIVITY generally) — a CASB is specifically focused on brokering and enforcing consistent policy across an organization''s use of CLOUD SERVICES/SaaS applications specifically, whether officially sanctioned by IT or informally adopted "shadow IT" usage IT never directly provisioned, giving visibility into what cloud services are actually being used and applying uniform DLP, access control, and encryption policy across all of them from ONE central enforcement point, rather than the security team needing to separately and inconsistently configure each individual SaaS application''s own native (and often more limited) security settings. This is a real, standard, and purpose-built cloud-security architecture category — note that SASE and CASB capabilities do genuinely overlap and are sometimes offered together by the same vendor/platform, but CASB''s specific, defining focus is cloud-SERVICE-usage policy enforcement and visibility, not general network connectivity. A bastion host (covered in a prior paper) and an air-gapped network (also covered in a prior paper) are both entirely unrelated network-architecture concepts to this specific cloud-security-broker function.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('ce149368-dd2a-4f25-8ad0-6b442d72bb32', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 9, 'A company building software wants a complete, itemized inventory of every third-party and open-source component (and their specific versions) that goes into their final application — so that when a new vulnerability is publicly disclosed in a specific widely-used library, they can immediately and accurately determine whether and where that vulnerable library is actually used across their own products, rather than having to manually audit every codebase to find out. What artifact provides this kind of complete component inventory?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9c55edeb-d375-4d28-9022-75f6a1c1c218', 'ce149368-dd2a-4f25-8ad0-6b442d72bb32', 0, 'An SBOM (Software Bill of Materials) — a complete, itemized inventory of every component (including third-party and open-source libraries, and their specific versions) that makes up a piece of software, letting an organization immediately and accurately determine whether and where a newly-disclosed vulnerability in a specific component actually affects their own products, without needing to manually audit every codebase from scratch each time a new vulnerability disclosure happens — directly relevant to both supply chain attack risk (covered in a prior paper) and the general vulnerability management lifecycle (covered in a prior paper).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6fb21430-23fb-4f34-9f50-b0c4c0e77f59', 'ce149368-dd2a-4f25-8ad0-6b442d72bb32', 1, 'A risk register, since risk registers are specifically defined as a complete, itemized inventory of every third-party and open-source software component used in a product.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5d7d7847-e082-47a1-9b78-d7e5205d18a9', 'ce149368-dd2a-4f25-8ad0-6b442d72bb32', 2, 'A RACI matrix, since RACI matrices are specifically defined as an itemized inventory of third-party and open-source software components and their specific versions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('823198de-9ccc-480c-8026-d933c8b07010', 'ce149368-dd2a-4f25-8ad0-6b442d72bb32', 3, 'No practical way exists to maintain an inventory of every third-party and open-source component used across a software product; this would always require manually auditing the codebase from scratch for every new vulnerability disclosure.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('ce149368-dd2a-4f25-8ad0-6b442d72bb32', '9c55edeb-d375-4d28-9022-75f6a1c1c218', 'An SBOM is specifically the standard artifact for this exact need — a structured, complete inventory listing every component (direct and often TRANSITIVE/nested dependencies too) that goes into a piece of software, along with specific version information, generated as part of the build process rather than maintained manually. This directly connects to and mitigates the practical impact of a supply chain attack (covered in a prior paper, where a widely-used shared component being compromised can affect vastly many downstream consumers) — when a new vulnerability is publicly disclosed in a specific library, an organization with accurate, up-to-date SBOMs for all their products can immediately, mechanically CHECK across every SBOM whether and where that specific vulnerable component/version is actually used, dramatically faster and more reliably than manually auditing potentially many separate codebases by hand to find out. This is a real, increasingly standard, and in some contexts regulatorily-encouraged or required practice (particularly for software sold to government/critical infrastructure customers) — a risk register (covered in a prior paper) tracks identified RISKS generally, not a component-level software inventory, and a RACI matrix (covered in a prior paper) assigns roles/responsibilities, an entirely unrelated concept.');

-- ── Domain: Security Operations (28% — 6 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('7ebb6883-e54d-4377-97f7-1dc42f14f0a9', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 10, 'A vulnerability scan returns two findings: one rated 9.8 out of 10, and another rated 3.1 out of 10. Both scores were calculated using a standardized methodology considering factors like how the vulnerability is exploited (over a network vs. requiring physical access), how complex exploitation is, and what impact a successful exploit would have. What is this standardized vulnerability-severity scoring methodology called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('98ddf2c3-813a-41ab-84e7-97f56243f5db', '7ebb6883-e54d-4377-97f7-1dc42f14f0a9', 0, 'CVSS (Common Vulnerability Scoring System) — a standardized, widely-adopted methodology for scoring a vulnerability''s severity on a consistent 0-to-10 scale, based on factors like the attack vector (network-reachable vs. requiring local/physical access), attack complexity, privileges required, and the impact on confidentiality/integrity/availability if successfully exploited, giving security teams a CONSISTENT, comparable basis for the prioritization decisions covered generally in a prior paper (which also weighs real-world exploitability and asset criticality alongside the raw CVSS score itself).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1db93ae9-27ad-45b1-9710-b9160e1c9ee2', '7ebb6883-e54d-4377-97f7-1dc42f14f0a9', 1, 'IOC, since IOCs are specifically defined as the standardized 0-to-10 methodology for scoring a vulnerability''s severity based on attack vector and impact.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('295ac213-3776-4d6c-9652-640a25cce308', '7ebb6883-e54d-4377-97f7-1dc42f14f0a9', 2, 'RACI, since RACI is specifically defined as the standardized methodology for scoring vulnerability severity based on attack complexity and privileges required.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bb393ea3-4c77-4d96-b66d-06c6fb365452', '7ebb6883-e54d-4377-97f7-1dc42f14f0a9', 3, 'No standardized methodology exists for scoring vulnerability severity; every vulnerability scanning tool always assigns severity ratings using its own entirely proprietary, non-comparable scale.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('7ebb6883-e54d-4377-97f7-1dc42f14f0a9', '98ddf2c3-813a-41ab-84e7-97f56243f5db', 'CVSS is specifically the widely-adopted, standardized methodology providing consistent, comparable severity scores across DIFFERENT vulnerabilities and DIFFERENT scanning tools/sources, directly refining the general vulnerability-management-lifecycle prioritization concept (covered in a prior paper, which discussed weighing severity alongside real-world exploitability and asset criticality) with the specific, standard scoring mechanism that CVSS provides for the "severity" component of that weighing. A CVSS score is derived from multiple specific factors combined into the final 0-to-10 figure — the attack vector (can it be exploited remotely over a network, or does it require local/physical access — a network-exploitable vulnerability generally scores meaningfully higher, all else equal), attack complexity, privileges required to exploit it, and the confidentiality/integrity/availability impact of a successful exploit — giving security teams a genuinely standardized, comparable basis for triage rather than relying on each individual tool''s own inconsistent, non-comparable proprietary rating. This is a real, industry-standard methodology (not a proprietary, tool-specific scale, contrary to the last distractor) — IOC (covered in a prior paper, indicators of a KNOWN compromise) and RACI (covered in a prior paper, a role-assignment matrix) are both entirely unrelated concepts to vulnerability severity SCORING.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('bcc743e3-ef04-4d95-aa24-861824b20991', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 11, 'A company''s backup strategy takes a COMPLETE backup of all data every Sunday, and on every other day of the week, backs up ONLY the data that has changed since the LAST backup (whether that was Sunday''s full backup or the previous day''s partial backup). What is this specific backup strategy called, and what is its key restore-time trade-off compared to an alternative that always backs up everything changed since the LAST FULL backup specifically?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('213b6813-2a45-403c-8dd8-d1ab5869bdf3', 'bcc743e3-ef04-4d95-aa24-861824b20991', 0, 'This is an incremental backup strategy — each day''s backup captures only data changed since the MOST RECENT backup of any kind (full or incremental), making each individual daily backup fast and small, but RESTORATION requires applying the last full backup PLUS every single incremental backup since then, in exact sequential order; this contrasts with a differential backup strategy, which backs up everything changed since the last FULL backup specifically (making each differential backup progressively larger through the week, but restoration only ever needs the last full backup plus the SINGLE most recent differential, a genuinely faster and simpler restore process).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('97f4e782-cae1-40bc-bb6c-c2c599179394', 'bcc743e3-ef04-4d95-aa24-861824b20991', 1, 'This is a differential backup strategy, since differential backups are specifically defined as capturing only data changed since the most recent backup of any kind, whether full or partial.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f4cb9efd-dacc-438f-919d-cb0a61557548', 'bcc743e3-ef04-4d95-aa24-861824b20991', 2, 'Incremental and differential backup strategies are functionally identical, with no meaningful difference in backup size or restoration process between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bf802515-4545-4b68-9170-42d304927e74', 'bcc743e3-ef04-4d95-aa24-861824b20991', 3, 'Backing up only changed data since a prior backup is not technically possible; every backup must always capture a complete copy of all data regardless of what has changed.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('bcc743e3-ef04-4d95-aa24-861824b20991', '213b6813-2a45-403c-8dd8-d1ab5869bdf3', 'Incremental and differential backups both build on the full backup concept (implicitly connecting to backup restore testing, covered in a prior paper) but make a genuinely different, directly testable trade-off between BACKUP-TIME efficiency and RESTORE-TIME simplicity: incremental backups are the smallest and fastest to CREATE each time, since each one only captures what changed since the immediately preceding backup (whatever type it was) — but this means restoring requires carefully reapplying the original full backup and then EVERY incremental backup since, in the exact correct sequential order, since each incremental only makes sense relative to the one before it, making the restore process slower and more failure-prone (a single missing or corrupted incremental in the chain breaks the whole restoration). Differential backups instead always capture everything changed since the last FULL backup specifically (not since the last differential), meaning each day''s differential grows progressively larger through the week as more changes accumulate — but restoration only ever needs the ORIGINAL full backup plus the SINGLE most recent differential, a meaningfully simpler and generally faster restore process with fewer pieces that could go wrong. This is a real, standard, and genuinely practical trade-off organizations weigh when designing a backup strategy — not an arbitrary distinction, and both approaches are real, established alternatives to backing up everything in full every single time.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('c8515f41-3058-40e9-96fe-0b966a66c2b4', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 12, 'A company wants to measure how well its security operations team is actually performing, tracking two specific metrics: the average time between when a genuine security incident actually BEGINS and when it''s first identified/detected, and separately, the average time between detection and the incident being fully contained/resolved. What are these two operational metrics called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('271f8d5d-8c02-404e-b721-01abb9d36ed6', 'c8515f41-3058-40e9-96fe-0b966a66c2b4', 0, 'MTTD (Mean Time To Detect) and MTTR (Mean Time To Respond/Remediate) — MTTD measures the average time between an incident actually beginning and it being detected, a direct measure of DETECTION capability (a longer MTTD means threats are dwelling undetected longer, connecting to the value of threat hunting, covered in a prior paper, in proactively reducing this dwell time); MTTR measures the average time from detection to actual containment/resolution, a direct measure of RESPONSE effectiveness — together, these give leadership concrete, trackable metrics for security operations performance over time, distinct from the general security KPI concept covered in a prior paper by naming these two specific, standard, widely-used metrics.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('cf10867e-a780-4e65-9835-5a60bde6649b', 'c8515f41-3058-40e9-96fe-0b966a66c2b4', 1, 'RTO and RPO, since RTO and RPO are specifically defined as measuring the average time to detect an incident and the average time from detection to containment.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a34ffefe-1574-42a1-ba85-dd5230a539bd', 'c8515f41-3058-40e9-96fe-0b966a66c2b4', 2, 'SLE and ARO, since SLE and ARO are specifically defined as the average time to detect and the average time to respond to a security incident.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e1b716ee-00b8-4838-bf55-97aa3520eb63', 'c8515f41-3058-40e9-96fe-0b966a66c2b4', 3, 'Security operations performance can never be meaningfully measured with concrete, trackable metrics; only qualitative, subjective assessment is possible.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('c8515f41-3058-40e9-96fe-0b966a66c2b4', '271f8d5d-8c02-404e-b721-01abb9d36ed6', 'MTTD and MTTR are specifically the standard, named operational metrics for measuring detection and response performance separately, refining the general security KPI/governance-dashboard concept (covered in a prior paper) with these two concrete, widely-used, and directly comparable-over-time figures. MTTD captures how long a threat genuinely dwells in an environment UNDETECTED — a critically important figure since real damage (data exfiltration, lateral movement, further compromise) often continues accumulating for the entire dwell-time window before detection even occurs, directly motivating proactive practices like threat hunting (covered in a prior paper) specifically aimed at shortening this window rather than passively waiting for existing detection tooling to eventually catch something. MTTR then separately measures how efficiently the team acts ONCE something is actually detected — the containment/response phase specifically. These are genuinely distinct, complementary metrics (a team could have excellent MTTR but poor MTTD, or vice versa, and improving each requires different specific interventions) rather than a single combined figure. RTO/RPO (covered generally in a prior paper via BIA) measure ACCEPTABLE recovery targets for business continuity planning, a related but different concept from MEASURING actual historical detection/response performance, and SLE/ARO (covered earlier this paper) are quantitative risk-calculation inputs, entirely unrelated to operational performance metrics.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('0999eb24-aa31-45e4-bd26-3435518ba20d', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 13, 'A company wants its endpoints to run ONLY software explicitly approved in advance by IT, automatically blocking any executable not on that pre-approved list — including entirely new or unknown malware that has never been seen before and therefore has no existing antivirus signature. What security technique enforces this "default deny, only run what''s explicitly approved" posture?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ad7a8eff-e898-45ba-a65d-210e5cc27fe5', '0999eb24-aa31-45e4-bd26-3435518ba20d', 0, 'Application allowlisting (also called application whitelisting) — explicitly defines which specific applications/executables are PERMITTED to run on a system, blocking everything else by default, including entirely novel, previously-unseen malware with no existing signature, since the control isn''t based on recognizing something as BAD (the way signature-based antivirus, covered in a prior paper, works) but rather on the software simply not being on the approved list at all — the inverse, and generally more restrictive, approach compared to application denylisting (blacklisting), which instead explicitly blocks only KNOWN-bad software while permitting everything else by default.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4a8b9a2f-16a0-4ad6-ab2e-f9eaff516fcc', '0999eb24-aa31-45e4-bd26-3435518ba20d', 1, 'Application denylisting, since denylisting is specifically defined as blocking every application by default except those explicitly pre-approved by IT in advance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0865c149-ef4e-4e4f-a08e-8a107c800e0b', '0999eb24-aa31-45e4-bd26-3435518ba20d', 2, 'NAC, since NAC is specifically defined as blocking every application by default except those explicitly pre-approved by IT, based on the application itself rather than device posture.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2683e75a-717a-483c-8345-d817e8bbb5b5', '0999eb24-aa31-45e4-bd26-3435518ba20d', 3, 'No security technique can block previously-unseen, unknown malware with no existing signature; only known, catalogued threats can ever be blocked by any endpoint control.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('0999eb24-aa31-45e4-bd26-3435518ba20d', 'ad7a8eff-e898-45ba-a65d-210e5cc27fe5', 'Application allowlisting flips the more common "block known-bad" model on its head to "permit only known-good," which is exactly what gives it a genuine, meaningful advantage against entirely novel threats: traditional signature-based antivirus (covered generally in a prior paper) needs to already recognize something as malicious to block it, meaning a brand-new, never-before-seen piece of malware with no existing signature can simply run undetected — but allowlisting doesn''t care whether something is recognized as BAD, only whether it''s on the explicitly APPROVED list at all, so any unapproved software (malicious or not, known or entirely novel) is blocked by default regardless of whether any signature or behavioral pattern for it exists yet. This directly connects to and extends the compensating-controls example (application allowlisting specifically mentioned for unpatchable legacy systems, covered in a prior paper) into its own standalone, general endpoint-hardening technique. Application DENYLISTING (blacklisting) is the inverse, more permissive approach — explicitly blocking only KNOWN-bad software while allowing everything else to run by default, meaning (unlike allowlisting) it offers no protection against genuinely novel, unrecognized threats. NAC (covered in a prior paper) evaluates DEVICE-level posture (patch status, antivirus currency) before granting NETWORK access, a genuinely different control layer and mechanism from application-level execution control on an already-connected device.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('c4ebfd0c-ca30-4162-aa78-6692e72eec42', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 14, 'A client application needs to verify, in real time, whether a specific TLS certificate it just received has been revoked by its issuing CA — but downloading and checking an entire, potentially large Certificate Revocation List (CRL) for every single connection is slow and inefficient. What alternative, faster real-time certificate-status-checking protocol addresses this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c8c8d935-9ad7-4ebf-abf8-4c2b24c77a8e', 'c4ebfd0c-ca30-4162-aa78-6692e72eec42', 0, 'OCSP (Online Certificate Status Protocol) — lets a client query a CA''s OCSP responder in real time for the revocation status of ONE SPECIFIC certificate, receiving a direct, targeted answer without needing to download an entire CRL (which lists EVERY revoked certificate for that CA, potentially a large file, covered generally as part of PKI/CA concepts in a prior paper); this is meaningfully faster and more efficient for a single per-connection revocation check, at the trade-off of the OCSP responder itself being a real-time dependency (and, in some implementations, potentially able to observe which specific certificates/sites a given client is checking, a genuine privacy consideration OCSP Stapling was later introduced to address).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7f369016-5b7f-4259-869d-c90286f1c35c', 'c4ebfd0c-ca30-4162-aa78-6692e72eec42', 1, 'A CRL, since a CRL is specifically defined as the faster, real-time, per-certificate alternative to querying an OCSP responder.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d5a7c891-56ab-4fec-bfc1-3146e82a04de', 'c4ebfd0c-ca30-4162-aa78-6692e72eec42', 2, 'CVSS, since CVSS is the protocol specifically used for real-time, per-certificate revocation status checking as an alternative to downloading a full CRL.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bde722df-7c18-43d3-a5b7-a73f8a5a5778', 'c4ebfd0c-ca30-4162-aa78-6692e72eec42', 3, 'No faster alternative to downloading a complete CRL exists; every certificate revocation check always requires retrieving the full revocation list.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('c4ebfd0c-ca30-4162-aa78-6692e72eec42', 'c8c8d935-9ad7-4ebf-abf8-4c2b24c77a8e', 'OCSP directly refines the general PKI/certificate-revocation concept (covered generally in a prior paper) with the specific, faster real-time-checking mechanism that addresses the CRL''s core inefficiency — a CRL is a complete LIST of every certificate a given CA has revoked, which a client would otherwise need to download and search through in full just to check the status of ONE specific certificate, becoming genuinely slow and bandwidth-heavy as that list grows large over time. OCSP instead lets a client send a targeted query — "is THIS specific certificate currently revoked?" — directly to the CA''s OCSP responder, and receive a direct yes/no/unknown answer without downloading the CA''s entire revocation list at all, meaningfully faster for the common case of checking one certificate at a time during a live connection. The genuine trade-off is that OCSP introduces a real-time DEPENDENCY on the responder actually being reachable and responsive at the moment of connection (a CRL, once downloaded, can be checked offline/locally), and in some implementations the OCSP responder could observe which specific sites/certificates a client is checking — a real privacy consideration that OCSP Stapling (where the SERVER itself periodically fetches and "staples" its own current OCSP response to the TLS handshake, removing the client''s need to separately query the responder at all) was specifically introduced to address. This is a real, standard alternative mechanism, not a redundant restatement of CRL checking.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('8963ea06-268e-47a9-a458-d2b6bf986b20', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 15, 'A vulnerability scanner flags a specific finding as a critical vulnerability, but manual investigation confirms the flagged software isn''t actually present on that system at all — the scanner was simply wrong. Separately, an actual real vulnerability exists on a different system, but the scanner failed to flag it at all, giving that system a clean report despite the real, unaddressed weakness. What are these two distinct types of scanning errors called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e7948ffc-ff7e-49b9-877e-de2af4e61351', '8963ea06-268e-47a9-a458-d2b6bf986b20', 0, 'A false positive (the scanner flagged something that actually isn''t there or isn''t actually a real problem) and a false negative (the scanner missed something that genuinely IS a real problem, giving a false sense of security); false negatives are generally considered the MORE dangerous error type, since a false positive merely wastes investigation time confirming a non-issue, while a false negative leaves a genuine, real vulnerability completely unaddressed and unknown, with the organization believing (incorrectly) that the system is clean.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0aab070d-daa5-47dc-9db7-97f4de21dffa', '8963ea06-268e-47a9-a458-d2b6bf986b20', 1, 'A false negative is when the scanner flags something that isn''t actually there, and a false positive is when the scanner misses a genuinely real vulnerability — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7f216c2e-9747-466a-84f6-e55583e488fb', '8963ea06-268e-47a9-a458-d2b6bf986b20', 2, 'False positives and false negatives are two different names for the exact same type of scanning error, with no meaningful distinction between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('924c441b-ec16-4a39-af84-8e7d8decc35f', '8963ea06-268e-47a9-a458-d2b6bf986b20', 3, 'Vulnerability scanning tools are always perfectly accurate and never produce either a false positive or a false negative under any circumstance.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('8963ea06-268e-47a9-a458-d2b6bf986b20', 'e7948ffc-ff7e-49b9-877e-de2af4e61351', 'False positive and false negative are standard, precisely-defined terms directly relevant to interpreting scan results — refining the general vulnerability scanning and credentialed-vs-non-credentialed scanning concepts (both covered in prior papers) with the genuinely important question of how to interpret and TRUST what a scan actually reports: a false positive incorrectly flags something as a problem when it genuinely isn''t one (wasting real analyst time chasing down and confirming a non-issue, connecting to the alert fatigue concept covered in a prior paper, since a scanner with a high false-positive rate trains analysts to start reflexively dismissing its findings), while a false negative is the more dangerous failure mode — the scanner MISSES a genuinely real vulnerability entirely, leaving the organization with a false sense of security believing a system is clean when it actually isn''t, with no alert at all prompting anyone to look closer. This same false-positive/false-negative framework applies broadly beyond vulnerability scanning specifically — it''s the identical underlying concept behind the distractor-language false-positive pattern this project''s own paper-verification process has repeatedly needed to manually check for, and the same framework used to evaluate IDS/IPS (covered in a prior paper) detection accuracy. Real scanning tools genuinely do produce both error types with some non-zero rate — no tool is perfectly accurate — which is exactly why understanding and correctly interpreting these two distinct error types matters in practice.');

-- ── Domain: Security Program Management & Oversight (20% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('fcaa62e6-2e1b-40bf-a74e-e0c4b29f2dbc', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 16, 'A company''s general data retention SCHEDULE calls for deleting customer support tickets after 2 years as routine practice. Separately, the company is notified of pending litigation requiring specific support tickets to be preserved indefinitely until the matter concludes. How do these two obligations relate to each other, and which one governs the affected data in the meantime?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dcc1b73a-2d2e-417f-94aa-9aff9a16286b', 'fcaa62e6-2e1b-40bf-a74e-e0c4b29f2dbc', 0, 'A standard data retention policy sets the ROUTINE, ordinary schedule for how long data is normally kept before deletion (here, 2 years for support tickets) — but a legal hold (covered in a prior paper) is a distinct, EXTERNALLY-TRIGGERED exception that specifically OVERRIDES the routine retention schedule for any data covered by the hold, suspending normal deletion for that specific data until the legal matter concludes, regardless of what the standard schedule would otherwise call for; the two are genuinely complementary policies operating at different times for different reasons, not the same policy under two names.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4a643552-29f1-48a8-a457-4d44e4a7666c', 'fcaa62e6-2e1b-40bf-a74e-e0c4b29f2dbc', 1, 'A legal hold and a standard data retention policy are the exact same policy under two different names, with the legal hold having no ability to override the routine retention schedule.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bbe4182b-f9ef-4255-b033-186cb1f8beda', 'fcaa62e6-2e1b-40bf-a74e-e0c4b29f2dbc', 2, 'The routine 2-year retention schedule always continues to govern and delete the affected data on schedule regardless of any pending litigation or legal hold notification.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f21f2f24-b713-407c-a437-816935eba094', 'fcaa62e6-2e1b-40bf-a74e-e0c4b29f2dbc', 3, 'Companies have no obligation of any kind to preserve data differently in response to pending litigation; a legal hold carries no real practical or legal significance.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('fcaa62e6-2e1b-40bf-a74e-e0c4b29f2dbc', 'dcc1b73a-2d2e-417f-94aa-9aff9a16286b', 'A standard data retention policy establishes the routine, PLANNED schedule an organization normally follows for how long different categories of data are kept before ordinary deletion (here, 2 years for support tickets) — a genuinely different governance instrument from a legal hold (covered in a prior paper), which is an EXTERNALLY-TRIGGERED, litigation-driven exception that specifically SUSPENDS that routine schedule for whatever specific data the hold covers, for as long as the underlying legal matter remains active, regardless of what the normal schedule would otherwise dictate. Continuing to delete data on the routine schedule AFTER a legal hold has been triggered for that specific data is a real, serious legal problem (spoliation of evidence, as covered in the prior paper''s legal hold content) — meaning the legal hold genuinely DOES override the routine schedule for its covered data, the two are complementary policies operating in sequence (routine schedule governs by default, until/unless a legal hold specifically intervenes for specific data), not identical policies, and not something a company can simply ignore. This is a real, legally significant distinction any organization handling both routine data lifecycle management AND potential litigation needs to understand and correctly implement.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('8c6ed419-88ce-44c7-b7a5-6b049827c92b', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 17, 'A company that processes credit card payments (accepting Visa, Mastercard, and other major card brands) must comply with a specific INDUSTRY-established security standard governing how cardholder data is stored, processed, and transmitted — distinct from a government-enacted law, since it''s established and enforced by the payment card industry itself rather than a legislative body. What is this specific standard called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('14d97f88-ae30-4b78-8cdb-9bf94a47c2d2', '8c6ed419-88ce-44c7-b7a5-6b049827c92b', 0, 'PCI-DSS (Payment Card Industry Data Security Standard) — an INDUSTRY-established (not government-legislated) security standard specifically governing how organizations that handle cardholder data must store, process, and transmit it, created and enforced by the payment card industry itself (the major card brands and the PCI Security Standards Council) rather than by a government legislative body, distinct from a law like HIPAA (covered in a prior paper, government-enacted, governing health information specifically) or GDPR (covered in a prior paper, a government-enacted EU regulation) — directly connecting to tokenization (covered earlier this paper) as one common, real technique organizations use specifically to reduce their PCI-DSS compliance scope.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8b0b789b-891c-4da4-bba4-0ae08ad31512', '8c6ed419-88ce-44c7-b7a5-6b049827c92b', 1, 'HIPAA, since HIPAA is specifically the industry-established (not government-legislated) standard governing how cardholder payment data must be stored, processed, and transmitted.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f2e886ad-18f4-4a76-8abb-5b8f381acd92', '8c6ed419-88ce-44c7-b7a5-6b049827c92b', 2, 'GDPR, since GDPR is specifically an industry-established payment card security standard rather than a government-enacted data protection regulation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fe52b54e-b5dc-4111-97f5-4deb2cd77258', '8c6ed419-88ce-44c7-b7a5-6b049827c92b', 3, 'No standard or regulatory requirement of any kind governs how organizations that process credit card payments must protect cardholder data.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('8c6ed419-88ce-44c7-b7a5-6b049827c92b', '14d97f88-ae30-4b78-8cdb-9bf94a47c2d2', 'PCI-DSS is specifically distinguished by being an INDUSTRY-established standard (created and enforced by the payment card brands and the PCI Security Standards Council) rather than a government-enacted LAW — a genuinely important, directly testable distinction from both HIPAA (covered in a prior paper, a US federal LAW specifically governing protected health information, an entirely different data category and enforcement mechanism) and GDPR (covered in a prior paper, an EU government REGULATION governing personal data broadly) — despite all three sharing the general shape of "a compliance framework a company must follow," their SOURCE of authority and SCOPE of data covered are genuinely different, a common point of exam confusion given how frequently these three are mentioned together as "compliance requirements." PCI-DSS specifically covers cardholder data (card numbers, expiration dates, security codes) and mandates specific technical and procedural controls (network segmentation isolating cardholder data environments, encryption, access control, and specifically tokenization or similar techniques, covered earlier this paper, to REDUCE the scope of systems that must fully comply by minimizing which systems actually touch real card data) — a real, genuinely significant, and directly enforced industry standard, not a non-existent or optional requirement for any organization actually handling card payments.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('dbe8b55d-6c75-4082-9bab-0da5c43ecf90', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 18, 'A company establishes a confidential channel — a dedicated phone line and email address, operated by a party independent of an employee''s direct management chain — specifically so employees can report suspected fraud, ethics violations, or security incidents without fear of retaliation from those they might be reporting on. What is this kind of protected reporting mechanism called, and why does independence from the normal management chain matter?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bd1890a7-fbe0-4d6b-9a60-c3a4a88566c1', 'dbe8b55d-6c75-4082-9bab-0da5c43ecf90', 0, 'A whistleblower protection program (often implemented via an anonymous or confidential reporting channel/hotline) — specifically designed to let employees report suspected wrongdoing without fear of retaliation, which is exactly why independence from the normal management chain matters: if reports had to go through an employee''s own direct manager (who might themselves be implicated, or personally motivated to suppress the report to protect their own team/reputation), genuinely serious issues would be far less likely to ever actually surface at all.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c1e76a4a-57ac-424c-b8cf-493712b6f1cb', 'dbe8b55d-6c75-4082-9bab-0da5c43ecf90', 1, 'A BAA (Business Associate Agreement), since BAAs are specifically defined as a confidential channel letting employees report suspected fraud or ethics violations without fear of retaliation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c0b3c94f-9455-4fee-8a9e-c5e1aa44913f', 'dbe8b55d-6c75-4082-9bab-0da5c43ecf90', 2, 'A CASB, since CASBs are specifically defined as the confidential, independent reporting channel employees use to report suspected fraud or security incidents.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('714472a6-0493-4cd6-807e-89975db11522', 'dbe8b55d-6c75-4082-9bab-0da5c43ecf90', 3, 'Providing employees a confidential channel to report suspected wrongdoing offers no meaningful organizational or security value and is not a real, standard governance practice.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('dbe8b55d-6c75-4082-9bab-0da5c43ecf90', 'bd1890a7-fbe0-4d6b-9a60-c3a4a88566c1', 'A whistleblower protection program (commonly implemented via a confidential or anonymous reporting hotline/channel) exists specifically to address a genuine, well-documented organizational problem: serious wrongdoing — fraud, ethics violations, or even security incidents an employee is aware of but hesitant to report — often goes unreported specifically because the person aware of it fears retaliation, especially if reporting would have to go through their own direct manager, who might be personally implicated, motivated to protect their own team''s reputation, or simply uncomfortable being the one to escalate a colleague''s wrongdoing. Deliberately routing reports through a channel INDEPENDENT of the normal management chain (a dedicated hotline, a third-party-operated reporting service, or a designated compliance/ethics office reporting directly to a level like the board or an audit committee rather than through normal operational management) removes that specific conflict of interest and fear, directly increasing the real likelihood that genuine issues actually surface and get addressed rather than being silently suppressed. This connects to and complements separation of duties and mandatory vacation (both covered in prior papers) as another layer specifically aimed at surfacing fraud or wrongdoing that might otherwise go undetected — a BAA (a HIPAA-specific vendor contract type) and a CASB (a cloud-security architecture control, covered earlier this paper) are both entirely unrelated concepts to this specific employee-reporting governance mechanism.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('331d6339-1c7f-45da-90fc-4d295bdb2ac0', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 19, 'A hospital wants to share patient data with a third-party billing company to process insurance claims on the hospital''s behalf. Under HIPAA (covered in a prior paper), what specific type of contract must be in place between the hospital and this third party BEFORE any protected health information can be legally shared with them?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('444159f2-73dc-424d-98e6-45c46b779d08', '331d6339-1c7f-45da-90fc-4d295bdb2ac0', 0, 'A Business Associate Agreement (BAA) — a legally required contract under HIPAA between a covered entity (like the hospital) and any third party (a "business associate," here the billing company) that will handle protected health information on the covered entity''s behalf, specifically obligating that business associate to appropriately safeguard the health information and outlining permitted uses, required security measures, and breach notification obligations — legally required to be in place BEFORE any protected health information is shared with that third party, not an optional or after-the-fact formality.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('14fdb55e-13ea-44cb-a46e-f0563733cd0a', '331d6339-1c7f-45da-90fc-4d295bdb2ac0', 1, 'An MOU, since MOUs are specifically the legally required HIPAA contract type between a covered entity and any third party handling protected health information on its behalf.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2a12eae4-243f-4cf4-b47c-ffe297fde3f2', '331d6339-1c7f-45da-90fc-4d295bdb2ac0', 2, 'An SLA, since SLAs are specifically the legally required HIPAA contract type obligating a third party to safeguard protected health information before it can be shared.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9de998b1-17c0-4d7f-8fd5-01bf5cee8457', '331d6339-1c7f-45da-90fc-4d295bdb2ac0', 3, 'HIPAA imposes no contractual requirement of any kind before a covered entity shares protected health information with a third-party business associate.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('331d6339-1c7f-45da-90fc-4d295bdb2ac0', '444159f2-73dc-424d-98e6-45c46b779d08', 'A BAA is specifically the LEGALLY MANDATED (not merely a best-practice recommendation) contract type HIPAA (covered in a prior paper) requires between a covered entity and any "business associate" — any third party that will create, receive, maintain, or transmit protected health information on the covered entity''s behalf, such as this billing company processing insurance claims — and it must genuinely be in place BEFORE any such data sharing occurs, not negotiated or finalized after the fact. A BAA specifically obligates the business associate to appropriately safeguard the health information it handles, spells out what uses of that data are actually permitted, and establishes the business associate''s own breach notification obligations if something goes wrong on their end — directly extending accountability for protecting health information beyond just the covered entity itself to every third party that legitimately touches it. This is a genuinely distinct, HIPAA-specific contract type from a general SLA (covered in a prior paper, a performance-commitment contract not specifically tied to HIPAA''s health-information-protection requirements) or an MOU (covered in a prior paper, a general, typically non-binding statement of shared understanding) — a BAA is a real, legally mandated, and specifically regulated contract type under HIPAA, not an optional formality a hospital could reasonably skip.');

-- ── Domain: Threats, Vulnerabilities & Mitigations (additional — question 20) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('9c20ea5e-702f-4145-acec-eafd3518ff19', '62a003f2-51ee-42d5-8c39-1e43f9fa52e9', 20, 'A user notices their web browser''s homepage has been changed without their consent, unfamiliar toolbars have appeared, and they are bombarded with an unusually high volume of pop-up advertisements — while a separate, less visible program on the same machine is silently tracking the user''s browsing habits and keystrokes and transmitting that data to a remote server, without displaying any obvious symptoms at all. What are these two distinct categories of malware called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('35a3c195-4ea8-4ecb-8d4d-8fdfc51ebc21', '9c20ea5e-702f-4145-acec-eafd3518ff19', 0, 'Adware (the visible, disruptive category — unwanted advertisements, browser hijacking, unfamiliar toolbars, generally more of a nuisance than a severe security threat on its own) and spyware (the covert, invisible category — silently monitoring and transmitting user activity like browsing habits or keystrokes without the user''s knowledge, a genuinely more serious security and privacy concern precisely because it''s designed to remain undetected rather than announce its presence through obvious symptoms the way adware typically does).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2b11a551-baf5-46cb-bb7d-53a0ddbdbee3', '9c20ea5e-702f-4145-acec-eafd3518ff19', 1, 'Spyware is the visible, disruptive category producing pop-up ads and browser hijacking, while adware is the covert category silently tracking and transmitting user activity — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b482f88d-0751-46e0-a292-ed8874f2f309', '9c20ea5e-702f-4145-acec-eafd3518ff19', 2, 'Adware and spyware are two different names for the exact same malware category, with no meaningful distinction in visibility, behavior, or severity between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bf764b51-da5c-4dc6-b04e-771ea88075a2', '9c20ea5e-702f-4145-acec-eafd3518ff19', 3, 'Malware can never operate covertly without producing any visible symptoms; every malware infection always announces its presence through obvious, noticeable changes to the system.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('9c20ea5e-702f-4145-acec-eafd3518ff19', '35a3c195-4ea8-4ecb-8d4d-8fdfc51ebc21', 'Adware and spyware sit at genuinely different points on a visibility-and-severity spectrum, a directly testable distinction from other malware categories covered in prior papers (ransomware''s overt encrypt-and-extort behavior, a rootkit''s deliberate OS-level concealment, a logic bomb''s delayed-trigger mechanism): adware is generally the more VISIBLE, disruptive category — its whole business model typically depends on actually being seen (displaying ads, hijacking a browser''s homepage or search settings), making it annoying and disruptive but often (not always) less severe from a pure data-theft standpoint than other malware categories. Spyware, by contrast, is specifically designed to operate COVERTLY — silently monitoring and exfiltrating genuinely sensitive information (browsing habits, keystrokes, potentially credentials typed into a keylogger-equipped variant) to a remote party, without producing the kind of obvious, noticeable symptoms adware typically does, making it meaningfully harder for an average user to even realize it''s present at all, and generally a more serious security/privacy concern specifically because of that covert operation. This is a real, genuinely useful distinction for understanding malware behavior and appropriate response — malware absolutely CAN and often deliberately DOES operate without any visible symptoms at all, contrary to the last distractor, which is exactly why detection tools like EDR (covered in a prior paper) matter for catching threats that don''t announce themselves the way adware does.');

