-- ============================================================
-- CompTIA Security+ (SY0-701) — Seed Data: Paper 9
-- New content, distinct topics from Papers 1-8 — no repeated scenarios.
-- Topic list checked directly against the actual question text of Papers
-- 1-8 (grepped from the files) before writing.
--
-- Domain-question-count breakdown, confirmed BEFORE writing any questions:
-- General 2 + Threats 4 + Architecture 4 + Operations 6 + Program
-- Management 4 = 20, confirmed.
--   General (2): impact categories (reputational/financial/operational/
--     legal), threat actor types & motivations.
--   Threats (4): fileless malware, Bluetooth attacks (bluejacking/
--     bluesnarfing), privilege escalation (vertical/horizontal),
--     deepfakes in social engineering.
--   Architecture (4): cloud deployment models, Infrastructure as Code
--     (IaC) security, physical security controls (CCTV/guards/bollards),
--     East-West vs. North-South traffic segmentation.
--   Operations (6): eDiscovery, agent-based vs. agentless vulnerability
--     scanning, root cause analysis (5 Whys/fishbone), DLP deployment
--     types, COOP leadership/personnel succession, vulnerability
--     disclosure/bug bounty programs.
--   Program Management (4): FISMA/FedRAMP, SOC 2 Type I vs. Type II,
--     generative AI acceptable use policy, BCP/DR test types.
--
-- IDs were generated via scripts/fill-seed-uuids.mjs, which replaces every
-- distinct placeholder token with a fresh, real UUID (consistently across
-- every occurrence) — this file has already had that script run against
-- it; the UUIDs below are real. Cross-checked against every other seed
-- file in the repo for zero collisions before finalizing, plus the
-- distractor-language sanity scan and a manual re-read of every answer key
-- against its option text. The question_papers ARRAY[...]::TEXT[] literal
-- and every option token were manually re-read once before running the
-- fill script.
-- Run this AFTER docs/question-bank-schema.sql.
-- ============================================================

INSERT INTO question_papers (id, slug, title, exam_type, focus_tags, question_count, difficulty, is_premium, sort_order, time_limit_minutes)
VALUES ('cde3aa69-4bbc-49cd-9577-f5f79381db57', 'secplus-practice-9', 'CompTIA Security+ (SY0-701) Practice Paper 9', 'comptia-sec-plus', ARRAY['Threat Actors', 'Fileless Malware', 'Privilege Escalation', 'Deepfakes', 'IaC Security', 'eDiscovery', 'Bug Bounty', 'FedRAMP', 'SOC 2']::TEXT[], 20, 'standard', true, 9, 30);

-- ── Domain: General Security Concepts (12% — 2 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('7c6a8213-17b2-45de-9488-bc66b2db5176', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 1, 'A company assesses the impact of a hypothetical data breach across several distinct dimensions: the direct cost of remediation and regulatory fines, the loss of customer trust and negative media coverage, the disruption to normal business operations while systems are being restored, and the potential for lawsuits or regulatory enforcement action. What are these distinct dimensions of impact called, and why does considering all of them matter?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dfbdf6fb-7e64-4757-b022-89caf98ab6b9', '7c6a8213-17b2-45de-9488-bc66b2db5176', 0, 'Impact categories — financial (direct costs, fines, remediation expenses), reputational (loss of customer trust, negative publicity), operational (business disruption while systems are restored), and legal/regulatory (lawsuits, enforcement actions, penalties); considering all four matters because focusing on only one category (commonly, just the direct financial cost) can significantly understate an incident''s TRUE total impact — a breach with a modest direct remediation cost could still cause severe, lasting reputational damage or trigger a major regulatory penalty, impacts a narrow financial-only view would miss entirely.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d980023e-3241-4c38-8f53-66dbb9f56edf', '7c6a8213-17b2-45de-9488-bc66b2db5176', 1, 'Control types, since control types are specifically defined as the financial, reputational, operational, and legal/regulatory dimensions of an incident''s impact.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('43dbcec7-4eab-4def-8a79-d121c3fbbe8c', '7c6a8213-17b2-45de-9488-bc66b2db5176', 2, 'ALE (Annualized Loss Expectancy), since ALE is specifically defined as the four distinct dimensions of impact — financial, reputational, operational, and legal/regulatory — rather than a single calculated dollar figure.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dd85fcf2-cad1-4b45-af71-1cd2fb711d3e', '7c6a8213-17b2-45de-9488-bc66b2db5176', 3, 'A security incident''s impact can only ever be meaningfully measured in direct financial terms; reputational, operational, and legal dimensions carry no real, separate significance.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('7c6a8213-17b2-45de-9488-bc66b2db5176', 'dfbdf6fb-7e64-4757-b022-89caf98ab6b9', 'Impact categories provide a genuinely important, multi-dimensional framework for risk assessment specifically because a narrow, single-dimension view — most commonly, evaluating only direct FINANCIAL cost — can badly understate an incident''s true total significance, directly complementing the quantitative ALE calculation (covered in a prior paper, which itself produces a single financial figure) with the broader, non-purely-financial dimensions that figure alone doesn''t capture. Reputational impact (lost customer trust, negative media coverage) can genuinely outlast and outweigh the direct remediation cost, sometimes for years; operational impact (business disruption, lost productivity while systems are down or being restored) is a real, separate cost distinct from the remediation bill itself; and legal/regulatory impact (lawsuits, enforcement actions, and connecting to specific regulations like GDPR, HIPAA, PCI-DSS, and SOX, all covered across prior papers) can impose costs and consequences having little direct relationship to the technical remediation cost at all. A genuinely thorough risk assessment considers all four dimensions together, since focusing on financial cost alone is exactly the kind of narrow view that leads organizations to systematically underinvest in security relative to their TRUE total exposure.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('6172408c-bb2c-4166-bb5b-44fbe4d5e6f9', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 2, 'A security team profiles different categories of adversaries they might realistically face: a nation-state actor with substantial resources and a specific espionage or sabotage objective, a hacktivist motivated by a political or social cause, an organized crime group motivated purely by financial profit, and an unskilled attacker running pre-built attack tools with little understanding of how they actually work. What is this classification called, and why does it matter for defensive planning?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('20978c6d-e43b-4bd9-a664-554e077d1426', '6172408c-bb2c-4166-bb5b-44fbe4d5e6f9', 0, 'Threat actor types (and their motivations) — nation-state actors (highly resourced, sophisticated, often patient and persistent, motivated by espionage/geopolitical objectives), hacktivists (motivated by ideology, often prioritizing public visibility/embarrassment over financial gain), organized crime (financially motivated, often running attacks at genuine commercial scale), and script kiddies (low skill, using pre-built tools with limited understanding); understanding this taxonomy matters because a realistic assessment of WHICH actor types an organization is actually likely to face — and their typical resources, sophistication, and motivations — should genuinely inform proportionate defensive prioritization, rather than treating every threat as equally sophisticated or equally likely.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bf8d9818-077f-4e48-a55f-c64786481308', '6172408c-bb2c-4166-bb5b-44fbe4d5e6f9', 1, 'Control categories, since control categories are specifically defined as the classification of adversaries by their resources, sophistication, and motivation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c7d7610a-56ca-4703-8ac7-b17db97db1d5', '6172408c-bb2c-4166-bb5b-44fbe4d5e6f9', 2, 'A risk register, since risk registers are specifically defined as the classification framework for nation-state, hacktivist, organized crime, and script kiddie threat actors.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('871c3518-069b-45f2-8121-693a5b3893f3', '6172408c-bb2c-4166-bb5b-44fbe4d5e6f9', 3, 'Every real-world attacker, regardless of actual resources, sophistication, or motivation, poses an identical level of threat and should always be defended against with an identical response.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('6172408c-bb2c-4166-bb5b-44fbe4d5e6f9', '20978c6d-e43b-4bd9-a664-554e077d1426', 'Threat actor typing provides a genuinely useful, realistic framework for proportionate defensive planning, distinct from — though a broader category encompassing — the insider threat concept (covered in a prior paper, which specifically describes an actor with EXISTING, legitimate authorized access, a different characteristic axis from this EXTERNAL-actor-type taxonomy based on resources and motivation). A nation-state actor typically brings substantial resources, patience, and sophistication toward specific geopolitical or espionage goals, often representing the highest-tier threat a typical organization might realistically face, though usually only if the organization''s data or function is genuinely strategically relevant. A hacktivist is motivated by ideology and often specifically seeks public visibility or embarrassment for a cause rather than covert financial gain. Organized crime groups operate with genuine financial motivation, sometimes at real commercial scale and sophistication rivaling nation-state actors specifically for profit-driven attacks like ransomware. Script kiddies represent the lowest sophistication tier, using pre-built, publicly-available tools with limited genuine technical understanding, but can still cause real damage particularly against poorly-defended targets. Understanding which of these an organization realistically faces genuinely should inform proportionate, realistic defensive prioritization — treating every threat as equally likely and equally sophisticated wastes limited security resources on the wrong priorities.');

-- ── Domain: Threats, Vulnerabilities & Mitigations (22% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('c27ce1a1-911f-4286-b221-3097dd750ddd', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 3, 'An attacker compromises a system and, rather than dropping a traditional malicious executable file to disk, instead uses legitimate, already-installed system administration tools (like PowerShell) to carry out malicious actions entirely in memory, leaving little to no trace on the disk itself for traditional file-based antivirus scanning to detect. What is this specific malware/attack technique called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d5b389f1-070b-4649-a679-87972cce7e94', 'c27ce1a1-911f-4286-b221-3097dd750ddd', 0, 'Fileless malware (sometimes described as a "living off the land" technique) — operates primarily or entirely in memory, using legitimate, already-trusted, pre-installed system tools and scripting engines (like PowerShell) to carry out malicious actions, rather than dropping a traditional standalone executable file to disk — this makes it genuinely harder for traditional, SIGNATURE-based antivirus (covered generally in a prior paper, which specifically scans FILES on disk against known-bad signatures) to detect, since there''s often little to no malicious FILE for that kind of scanning to actually examine, requiring behavioral/EDR-based detection (also covered generally in a prior paper) instead, which watches for anomalous BEHAVIOR — even from an otherwise-legitimate, trusted tool — rather than relying on file signatures alone.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e072ba3f-79bd-44a3-938f-6527f7addbb7', 'c27ce1a1-911f-4286-b221-3097dd750ddd', 1, 'A logic bomb, since logic bombs are specifically defined as operating entirely in memory using legitimate, pre-installed system tools rather than a dropped executable file.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bb14120d-4d54-4636-b1dd-a10569790d81', 'c27ce1a1-911f-4286-b221-3097dd750ddd', 2, 'A rootkit, since rootkits are specifically defined as using only legitimate, pre-installed administrative tools like PowerShell with no OS-level concealment mechanism involved.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e49e2371-d2ca-4359-bcdc-41bff3b955e5', 'c27ce1a1-911f-4286-b221-3097dd750ddd', 3, 'Malware can never operate without eventually writing a traditional, detectable executable file to disk; purely in-memory, file-free malicious activity is a technical impossibility.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('c27ce1a1-911f-4286-b221-3097dd750ddd', 'd5b389f1-070b-4649-a679-87972cce7e94', 'Fileless malware is specifically distinguished by AVOIDING the traditional "drop a malicious executable to disk" pattern that most signature-based antivirus (covered generally in a prior paper) is fundamentally built to catch — by instead abusing already-trusted, pre-installed administrative tools and scripting engines (PowerShell being a particularly common example, given its deep legitimate system access) to carry out malicious actions primarily or entirely in memory, fileless techniques leave meaningfully less for traditional file-scanning to actually examine, since the "malware" is really just legitimate tools being MISUSED rather than a distinctly identifiable malicious file existing on disk at all. This is exactly why EDR (covered generally in a prior paper, which watches BEHAVIOR rather than relying purely on file signatures) is a genuinely more effective detection approach against this specific technique — a behavioral monitor can flag PowerShell being used in an anomalous, suspicious WAY, even though PowerShell itself is completely legitimate and wouldn''t itself ever be flagged by a file-signature-based scan. This is genuinely different from a rootkit (covered in a prior paper, defined by OS-level CONCEALMENT of an existing compromise, a different characteristic from fileless malware''s specific avoidance of ever dropping a file at all) and a logic bomb (covered in a prior paper, defined by delayed, condition-based TRIGGERING, an unrelated characteristic) — this is a real, well-documented, and increasingly common technique specifically because it genuinely evades a meaningful category of traditional detection.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('8b09a23b-aa4c-4fd9-a281-26c9f381d2b8', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 4, 'An attacker within physical proximity of a target''s Bluetooth-enabled device exploits a vulnerability to access and copy the device''s stored contact list and messages without the device owner''s knowledge or authorization — distinct from simply sending the victim an unsolicited, unwanted message over Bluetooth. What is this specific, more severe Bluetooth attack called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1af24112-af20-4c50-9075-7b8088f02097', '8b09a23b-aa4c-4fd9-a281-26c9f381d2b8', 0, 'Bluesnarfing — unauthorized ACCESS to and theft of data (contacts, messages, files) from a Bluetooth-enabled device, exploiting a Bluetooth vulnerability without the device owner''s knowledge or consent; this is meaningfully more severe than bluejacking (sending unsolicited, unwanted messages to a nearby Bluetooth device — essentially a nuisance, not a genuine data-theft vector), since bluesnarfing represents an actual confidentiality breach of the device''s real, stored data, not merely an unwanted, harmless message appearing on screen.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6224d0c2-b54c-4bce-ae4b-305d79b5b9e5', '8b09a23b-aa4c-4fd9-a281-26c9f381d2b8', 1, 'Bluejacking, since bluejacking is specifically defined as unauthorized access to and theft of a device''s stored contacts and messages, rather than sending unsolicited messages.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('de66cfb9-28fd-4e2f-b2b4-d98d5eade40c', '8b09a23b-aa4c-4fd9-a281-26c9f381d2b8', 2, 'An evil twin attack, since evil twin attacks are specifically defined as exploiting a Bluetooth vulnerability to steal a device''s stored contacts and messages.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2a5a69f9-64ab-4f3c-bf12-346bf30f43de', '8b09a23b-aa4c-4fd9-a281-26c9f381d2b8', 3, 'Bluetooth-enabled devices can never be exploited to access or steal stored data without the device owner''s explicit, active participation in the process.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('8b09a23b-aa4c-4fd9-a281-26c9f381d2b8', '1af24112-af20-4c50-9075-7b8088f02097', 'Bluesnarfing is specifically distinguished from bluejacking by the SEVERITY and NATURE of what actually happens — bluejacking is essentially a nuisance-level attack, sending an unsolicited, unwanted message to a nearby Bluetooth-discoverable device (annoying, but not itself a confidentiality breach of any real stored data), while bluesnarfing represents an actual, genuine theft of the device''s real stored data — contacts, messages, potentially other files — exploiting a Bluetooth protocol or implementation vulnerability to access that data without the device owner''s knowledge or authorization at all. This is a genuinely important, directly testable severity distinction between two similarly-named Bluetooth attack terms that are frequently confused given how similar they sound — a real, meaningful difference between "someone sent me an annoying message" and "someone silently stole my contact list." This connects to the broader wireless security theme covered elsewhere (evil twin, covered in a prior paper, for Wi-Fi impersonation; WPA2/WPA3, covered in a prior paper, for Wi-Fi encryption) extended specifically to the Bluetooth protocol — this is a real, well-documented Bluetooth vulnerability class, not a technical impossibility requiring the victim''s active participation.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('c6dda936-b77d-44e3-868c-380dcdf8906b', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 5, 'An attacker who has compromised a low-privileged standard user account on a system exploits a separate vulnerability to elevate that account''s access to full administrator/root level on the SAME system. A DIFFERENT attacker, having compromised one standard user account, instead accesses a DIFFERENT user''s account at the SAME privilege level (not elevating to a higher level at all, but moving to a different, equally-privileged account). What are these two distinct privilege-escalation patterns called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('35d58512-8dc5-4b9c-b70f-d291867dabb6', 'c6dda936-b77d-44e3-868c-380dcdf8906b', 0, 'Vertical privilege escalation (moving from a LOWER privilege level to a HIGHER one — standard user to administrator/root — genuinely increasing the attacker''s level of access and control) and horizontal privilege escalation (moving to a DIFFERENT account or resource at the SAME privilege level — not increasing the attacker''s privilege TIER, but expanding what specific data or accounts they can access at that same tier, e.g., accessing a different user''s files or account without ever gaining administrator rights).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ce224145-f024-4cac-be86-08c0e326290e', 'c6dda936-b77d-44e3-868c-380dcdf8906b', 1, 'Horizontal privilege escalation is specifically defined as elevating from a standard user account to full administrator/root level, while vertical privilege escalation means accessing a different account at the same privilege level — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f97bcdf2-239d-4e92-b245-bd9d25c5b792', 'c6dda936-b77d-44e3-868c-380dcdf8906b', 2, 'Vertical and horizontal privilege escalation are two different names for the exact same attack pattern, with no meaningful distinction between elevating privilege level versus accessing a different account at the same level.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e9a9c032-35a5-42d0-849b-80edf0dff4cf', 'c6dda936-b77d-44e3-868c-380dcdf8906b', 3, 'A compromised low-privileged account can never be used to gain access to a higher privilege level or to a different account; the originally compromised account''s access level and identity are always a fixed, permanent ceiling.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('c6dda936-b77d-44e3-868c-380dcdf8906b', '35d58512-8dc5-4b9c-b70f-d291867dabb6', 'Vertical and horizontal privilege escalation are genuinely distinguished by the DIRECTION of the escalation — vertical specifically means moving UP the privilege hierarchy (standard user to administrator, or administrator to root/system-level access), a genuine increase in the attacker''s overall level of control and capability on the compromised system, directly connecting to why least privilege (covered generally in a prior paper) matters as a mitigation — a compromised account with genuinely minimal privileges to begin with has meaningfully less to escalate FROM. Horizontal escalation instead means moving SIDEWAYS — accessing a DIFFERENT account or resource at the SAME privilege tier, without actually gaining any higher-level access at all — for example, a compromised standard user account being used to access a DIFFERENT standard user''s files or data, expanding what the attacker can reach without ever obtaining administrator rights. Both represent genuine attacker goals AFTER an initial compromise, and separation of duties and least privilege (both covered generally in prior papers) specifically help limit the practical impact of either escalation pattern by constraining what any single compromised account can actually reach or do, even before any escalation attempt succeeds. This is a real, well-documented, and directly testable distinction — a compromised account''s initial access level is emphatically NOT always a fixed, permanent ceiling, which is precisely the vulnerability this pair of concepts describes exploiting.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('f7b895d4-9edd-4f50-9441-00b178593dc4', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 6, 'An attacker creates a highly realistic, AI-generated synthetic video of a company''s CEO appearing to give urgent, legitimate-sounding verbal instructions to the finance team to wire a large sum of money to a specific account — the video and voice are convincing enough that finance staff genuinely believe they''re watching and hearing the real CEO. What is this AI-generated synthetic media technique called, and how does it relate to BEC?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1f6c6c35-68eb-4877-9c1f-7046003ecbc6', 'f7b895d4-9edd-4f50-9441-00b178593dc4', 0, 'A deepfake — AI-generated synthetic video or audio convincingly mimicking a real person''s appearance and/or voice, used here to add a genuinely more convincing, harder-to-doubt layer of social engineering on top of a BEC-style attack (covered generally in a prior paper, which traditionally relied on a spoofed EMAIL alone) — a realistic deepfake video/audio of a trusted executive genuinely giving verbal instructions is significantly more psychologically convincing and harder for a target to doubt than a text-based email alone, representing a real, increasingly relevant evolution of the same underlying "impersonate a trusted authority figure to manipulate a financial action" attack pattern.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('436c7120-081c-4a96-a63f-9808e1bba997', 'f7b895d4-9edd-4f50-9441-00b178593dc4', 1, 'Pretexting, since pretexting is specifically defined as AI-generated synthetic video or audio convincingly mimicking a real person''s appearance and voice.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3f35cc3c-b016-4f02-9734-d0a813db2b7f', 'f7b895d4-9edd-4f50-9441-00b178593dc4', 2, 'Baiting, since baiting is specifically defined as creating a convincing, AI-generated synthetic video of a company executive giving verbal financial instructions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('72fa7b99-68f7-43f1-962e-91a32fbe2244', 'f7b895d4-9edd-4f50-9441-00b178593dc4', 3, 'AI-generated synthetic video and audio convincing enough to be mistaken for a real person do not currently exist as a genuine, real-world capability.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('f7b895d4-9edd-4f50-9441-00b178593dc4', '1f6c6c35-68eb-4877-9c1f-7046003ecbc6', 'Deepfakes represent a genuinely real, increasingly capable evolution of the social engineering threat landscape, directly relevant to and extending BEC (covered in a prior paper, which classically relies on a spoofed or lookalike EMAIL address impersonating a trusted party) — rather than a text-based email a target might scrutinize for subtle inconsistencies, a sufficiently convincing deepfake video or audio genuinely mimicking a trusted executive''s actual appearance and voice adds a dramatically more psychologically persuasive, harder-to-doubt layer to the exact same underlying manipulation goal: getting a target to take an urgent financial or data-disclosure action based on apparent authority. This is genuinely distinct from pretexting (covered in a prior paper, which relies on a FABRICATED SCENARIO/STORY as its core mechanism, not synthetic media specifically) and baiting (covered in a prior paper, which relies on an enticing LURE, an entirely different mechanism) — deepfake technology is a real, demonstrated, and increasingly accessible capability (not a hypothetical or non-existent one), which is exactly why organizations are increasingly adopting specific verification procedures (like an independently-initiated callback to a known number, rather than trusting a video/audio call alone) as a direct mitigation against exactly this evolving threat.');

-- ── Domain: Security Architecture (18% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('76130181-f032-447c-90a4-3cb53a0e58aa', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 7, 'A company evaluates several ways to deploy its infrastructure: entirely within a public cloud provider''s shared infrastructure, entirely within its own privately-owned and operated data center, a combination of both used together deliberately, and infrastructure spread across MULTIPLE different public cloud providers simultaneously. What are these distinct deployment models called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c69376f9-cd10-4ae6-a68d-10a835aa8605', '76130181-f032-447c-90a4-3cb53a0e58aa', 0, 'Public cloud (infrastructure hosted on a shared, multi-tenant cloud provider''s infrastructure, connecting to the shared responsibility model covered generally in a prior paper), private cloud (infrastructure run entirely within an organization''s own, dedicated infrastructure — either on-premises or a dedicated hosted environment — with no external multi-tenant sharing), hybrid cloud (a deliberate combination of public and private cloud used together for different workloads or purposes), and multi-cloud (infrastructure deliberately spread across MULTIPLE different public cloud providers simultaneously, often specifically to avoid dependency on any single vendor, or to use each provider''s particular strengths).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5007ea91-838f-4424-a2ae-0353188eb7b5', '76130181-f032-447c-90a4-3cb53a0e58aa', 1, 'Private cloud is specifically defined as infrastructure hosted on a shared, multi-tenant public provider, while public cloud means infrastructure run entirely within an organization''s own dedicated environment — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f361babe-0c77-4233-9ffa-b04a4f833478', '76130181-f032-447c-90a4-3cb53a0e58aa', 2, 'Public, private, hybrid, and multi-cloud are four different names for the exact same deployment model, with no meaningful distinction in infrastructure ownership or provider count between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('eaea6efe-08aa-42f7-b15a-49be58fc2704', '76130181-f032-447c-90a4-3cb53a0e58aa', 3, 'Organizations can only ever deploy infrastructure using exactly one single cloud provider or one single on-premises data center; combining multiple providers or environments is not a real, available option.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('76130181-f032-447c-90a4-3cb53a0e58aa', 'c69376f9-cd10-4ae6-a68d-10a835aa8605', 'These four deployment models directly extend the cloud shared responsibility model concept (covered generally in a prior paper, which focused specifically on public-versus-private security responsibility DIVISION) with the broader classification of the deployment models themselves. Public cloud means the shared, multi-tenant infrastructure a provider makes available to many customers, with the shared-responsibility division covered previously applying directly. Private cloud means an organization runs its OWN dedicated infrastructure with no external multi-tenancy at all — as covered previously, this generally means the organization itself bears MORE total responsibility across every layer, without a provider offloading any of it. Hybrid cloud deliberately combines both, typically routing different specific workloads to whichever environment best fits their particular requirements (a workload with strict data-residency needs staying on private infrastructure, while a more elastic, bursty workload runs in public cloud). Multi-cloud specifically means deliberately spreading infrastructure across MULTIPLE different public cloud PROVIDERS simultaneously — a genuinely distinct strategy from hybrid cloud''s public-plus-private combination — often specifically to avoid single-vendor lock-in risk or to leverage different providers'' particular strengths for different workloads. This is a real, standard, and genuinely important architectural classification, with organizations genuinely choosing among all four models based on real, practical trade-offs, not an arbitrary or non-existent distinction.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('b4ff38a5-1854-4474-afcf-bf9a54955a9f', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 8, 'A company defines its entire cloud infrastructure — networks, servers, security groups — as version-controlled CODE (using a tool like Terraform or CloudFormation) rather than manually clicking through a cloud console to configure resources one at a time. A security team wants to understand what NEW security considerations this Infrastructure as Code (IaC) approach specifically introduces, beyond the underlying infrastructure''s own security requirements.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3be91704-dd45-49df-ad66-aae6da80d02d', 'b4ff38a5-1854-4474-afcf-bf9a54955a9f', 0, 'IaC-specific security considerations include: the IaC code/templates themselves need to be scanned for security misconfigurations BEFORE deployment (connecting to SAST, covered generally in a prior paper, applied specifically to infrastructure-definition code rather than application code), the version control system storing that IaC code becomes a genuinely high-value target itself (since compromising it could let an attacker inject a malicious infrastructure change that then gets automatically deployed), and IaC templates frequently contain or reference sensitive values (credentials, keys) that need careful handling (connecting to Secrets Manager-style external secret storage rather than hardcoding sensitive values directly into version-controlled template code) — genuinely new considerations beyond simply securing the resulting infrastructure once deployed.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('01b356aa-97fd-4370-a32b-e192af5cbb4b', 'b4ff38a5-1854-4474-afcf-bf9a54955a9f', 1, 'Infrastructure as Code introduces no new security considerations of any kind beyond the underlying infrastructure''s own requirements, since the code defining that infrastructure carries no independent security significance.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ad0abbb9-0cee-44a6-b9ee-8f3d3b092eb9', 'b4ff38a5-1854-4474-afcf-bf9a54955a9f', 2, 'IaC templates should always hardcode credentials and sensitive values directly into the version-controlled code, since external secret storage provides no meaningful security benefit for infrastructure-definition code specifically.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6752149c-9741-488e-96aa-887e1a44057a', 'b4ff38a5-1854-4474-afcf-bf9a54955a9f', 3, 'The version control system storing an organization''s IaC templates carries no meaningful security significance and requires no different level of protection than any other, unrelated code repository.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('b4ff38a5-1854-4474-afcf-bf9a54955a9f', '3be91704-dd45-49df-ad66-aae6da80d02d', 'IaC genuinely introduces real, distinct security considerations specifically because the infrastructure DEFINITION itself becomes CODE with its own real security implications, beyond simply securing whatever infrastructure that code eventually produces — directly extending SAST (covered generally in a prior paper, for scanning APPLICATION source code) to IaC-specific scanning tools that check infrastructure templates for security misconfigurations (an overly permissive security group rule, a publicly-exposed resource that shouldn''t be) BEFORE that misconfiguration is ever actually deployed, catching problems earlier and more cheaply than discovering them after live deployment. The version control system holding that IaC code becomes a genuinely high-value target in its own right — since a successful compromise there could let an attacker inject a malicious infrastructure change (opening an unauthorized network path, weakening a security control) that then gets AUTOMATICALLY deployed through the normal IaC pipeline, a real and meaningfully different attack surface from simply attacking the deployed infrastructure directly. And IaC templates frequently need to reference genuinely sensitive values (database credentials, API keys) — hardcoding those directly into version-controlled code is a real, well-documented anti-pattern (since version history often persists that sensitive value even after later removal, and repository access effectively becomes credential access), which is exactly why external secret storage (Secrets Manager-style patterns, covered generally elsewhere) referenced dynamically at deployment time, rather than embedded directly in the code, is the standard, recommended approach.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('9dc81d6f-ac12-460f-a09f-0e8c89a210ef', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 9, 'A company protecting a physical data center deploys a layered set of physical security controls: CCTV cameras providing continuous visual monitoring and a recorded evidentiary trail, uniformed security guards performing active patrols and visitor verification, and concrete bollards positioned around the building''s perimeter specifically to prevent a vehicle from being deliberately driven into the structure. What is the general security principle these three DIFFERENT types of physical controls collectively illustrate?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('23b8bf52-e58b-4bd4-b3db-3c132b82069c', '9dc81d6f-ac12-460f-a09f-0e8c89a210ef', 0, 'Physical security defense-in-depth — deploying MULTIPLE, genuinely different TYPES of physical controls together (detective: CCTV, providing monitoring and evidentiary recording; a human-judgment-capable deterrent/detective control: security guards, who can actively assess and respond to a situation in ways a passive camera alone cannot; and a preventive control: bollards, which physically stop a specific vehicle-ramming attack vector outright) — directly applying the same layered, overlapping-controls philosophy as the general defense-in-depth concept (covered generally in a prior paper for logical/network controls) to the PHYSICAL security domain specifically, since no single physical control type alone (cameras alone, or guards alone, or barriers alone) provides complete protection against every realistic physical threat.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('147ad461-9bf3-47bc-901b-9b9a4475f548', '9dc81d6f-ac12-460f-a09f-0e8c89a210ef', 1, 'A mantrap, since mantraps are specifically defined as the general principle of deploying multiple different types of physical security controls together in layers.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7570ee55-22fc-42c2-8759-3fa531415e7d', '9dc81d6f-ac12-460f-a09f-0e8c89a210ef', 2, 'A Faraday cage, since Faraday cages are specifically defined as CCTV cameras, security guards, and vehicle-barrier bollards deployed together as layered physical controls.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b49ad6d1-0fae-4903-8feb-7cd5ed3581fc', '9dc81d6f-ac12-460f-a09f-0e8c89a210ef', 3, 'Physical security controls provide no meaningful security value when combined with other, different physical control types; each individual physical control type should always be relied upon entirely independently.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('9dc81d6f-ac12-460f-a09f-0e8c89a210ef', '23b8bf52-e58b-4bd4-b3db-3c132b82069c', 'This directly extends defense-in-depth (covered generally in a prior paper, in the context of network/logical controls like firewalls and endpoint protection working together) into the PHYSICAL security domain specifically — the three example controls here genuinely occupy different roles within the control-TYPE taxonomy covered generally in a prior paper: CCTV is primarily a DETECTIVE control (recording what happened, providing evidence and after-the-fact visibility, though its visible presence also carries some deterrent value), security guards combine active DETERRENT presence with genuine, human-judgment-based DETECTIVE and response capability that a passive camera alone fundamentally cannot provide (a guard can actively investigate something suspicious and respond in real time, where a camera can only record it), and bollards are a purely PREVENTIVE physical control, specifically and directly blocking a particular attack vector (vehicle-ramming) outright before it could ever succeed. Layering these genuinely different control types together — rather than relying on any single one alone — directly mirrors why defense-in-depth matters in the logical/network domain: no single control type, physical or logical, realistically provides complete protection against every plausible threat on its own, and combining genuinely different, complementary control types closes gaps that any one type alone would leave open. A mantrap (covered generally in a prior paper) and a Faraday cage (covered generally in a prior paper) are both specific, individual PHYSICAL CONTROLS themselves, not the broader organizing principle this question asks about.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('0bfe161b-54d0-4b3b-96fe-ca4a39595db8', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 10, 'A network architect describes traffic flowing BETWEEN different servers/services WITHIN the same data center or VPC (e.g., a web server calling an internal API service) as one category, and traffic flowing IN or OUT of that data center/VPC boundary to/from external clients or the internet as a different category. What are these two traffic-direction categories called, and why does distinguishing them matter for network segmentation strategy?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('fb556b73-21ce-4451-bd85-02f0e92243fd', '0bfe161b-54d0-4b3b-96fe-ca4a39595db8', 0, 'East-West traffic (flowing BETWEEN servers/services WITHIN the same data center, VPC, or network segment — internal, server-to-server communication) and North-South traffic (flowing IN or OUT across the data center/network BOUNDARY, to or from external clients, users, or the internet); distinguishing them matters because traditional network security historically focused heavily on securing the North-South PERIMETER (the DMZ concept, covered generally in a prior paper), but East-West traffic has become an increasingly critical concern specifically because an attacker who successfully breaches the perimeter can otherwise move relatively freely EAST-WEST between internal systems — directly motivating micro-segmentation (covered generally in a prior paper) as a control specifically restricting that internal, East-West movement, not just the perimeter boundary.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dd223843-9040-4fd1-92ad-36d8faf4a753', '0bfe161b-54d0-4b3b-96fe-ca4a39595db8', 1, 'North-South traffic is specifically defined as flowing between servers within the same data center, while East-West traffic means flowing across the external network boundary — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5d369291-11f8-4644-b19c-f179ecf66b15', '0bfe161b-54d0-4b3b-96fe-ca4a39595db8', 2, 'East-West and North-South traffic are two different names for the exact same network traffic direction, with no meaningful distinction between internal server-to-server communication and external boundary-crossing traffic.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('88039dea-f974-40ca-bec7-d51dc0d9f5f4', '0bfe161b-54d0-4b3b-96fe-ca4a39595db8', 3, 'Network security only needs to address traffic crossing the external network boundary; traffic flowing between internal servers within the same network carries no meaningful security significance of its own.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('0bfe161b-54d0-4b3b-96fe-ca4a39595db8', 'fb556b73-21ce-4451-bd85-02f0e92243fd', 'This East-West/North-South distinction directly explains WHY micro-segmentation (covered generally in a prior paper) matters as a genuinely distinct control from perimeter-focused defenses like a DMZ (covered generally in a prior paper) — traditional network security architecture historically concentrated heavily on the North-South boundary (the perimeter separating trusted internal infrastructure from the untrusted external internet), operating on an implicit assumption that once traffic was inside that perimeter, it could largely be trusted to move relatively freely between internal systems. This assumption creates a genuine, real vulnerability: an attacker who successfully breaches the North-South perimeter just once can then often move relatively unrestricted EAST-WEST between internal systems, directly enabling exactly the kind of lateral movement that turns a single initial compromise into a much broader, more damaging breach. Micro-segmentation directly addresses this by applying meaningful access controls to East-West traffic ITSELF, not just at the North-South perimeter — treating internal network segments with the same "don''t automatically trust" scrutiny previously reserved mainly for the external boundary, directly connecting to and operationalizing the Zero Trust principle (covered generally in a prior paper, "never trust, always verify") specifically at the internal-network-traffic level. This is a real, standard, and genuinely important distinction in modern network security architecture, not an arbitrary or meaningless traffic-direction label.');

-- ── Domain: Security Operations (28% — 6 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('df0a582d-cc56-47b3-bde4-a81e18120666', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 11, 'A company facing active litigation must identify, preserve, collect, and eventually produce all potentially RELEVANT electronic information (emails, documents, chat logs) across its systems for the opposing party''s legal review — a broader, more comprehensive process than simply placing a legal hold (covered generally in a prior paper) to pause routine deletion. What is this broader, structured process called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9d8890fe-b9f6-4b6a-9d8d-e257bca0df23', 'df0a582d-cc56-47b3-bde4-a81e18120666', 0, 'eDiscovery (electronic discovery) — the broader, structured legal process of identifying, preserving, collecting, reviewing, and ultimately PRODUCING potentially relevant electronic information for litigation, regulatory investigation, or a similar legal proceeding; a legal hold (covered generally in a prior paper) is specifically the PRESERVATION step WITHIN this broader eDiscovery process — pausing routine deletion so relevant data isn''t lost — but eDiscovery as a whole encompasses considerably more than preservation alone, including actually locating relevant data across systems, collecting it in a legally defensible manner, and reviewing/producing it to the opposing party or a court.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dabd84e7-23a6-47c1-867b-aa15dca0b55d', 'df0a582d-cc56-47b3-bde4-a81e18120666', 1, 'A legal hold and eDiscovery are two different names for the exact same complete process, with legal hold already encompassing identification, collection, review, and production, not merely preservation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0c6c8f56-fce9-456e-a543-ad3f3401371d', 'df0a582d-cc56-47b3-bde4-a81e18120666', 2, 'A write blocker, since write blockers are specifically defined as the broader legal process of identifying, collecting, reviewing, and producing electronic information for litigation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bb82339d-95e8-40a7-b7d5-b4aa85fca6ac', 'df0a582d-cc56-47b3-bde4-a81e18120666', 3, 'Companies facing litigation have no formal, structured process for identifying and producing electronic information; every such request must always be handled in a fully ad hoc, unstructured manner.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('df0a582d-cc56-47b3-bde4-a81e18120666', '9d8890fe-b9f6-4b6a-9d8d-e257bca0df23', 'eDiscovery is specifically the BROADER, end-to-end legal process, genuinely encompassing more than just the preservation step a legal hold (covered generally in a prior paper) specifically addresses — a legal hold pauses routine deletion so potentially relevant data survives long enough to actually be found and used, but eDiscovery as a complete process also includes actually IDENTIFYING where relevant data might exist across potentially many different systems, COLLECTING it in a way that''s legally defensible (connecting to chain of custody and forensic imaging concepts, covered generally in prior papers, since evidence collected in a forensically unsound way can be challenged), REVIEWING it (often for both relevance and legal privilege before disclosure), and ultimately PRODUCING the relevant material to the opposing party or a court. This is a genuinely important, directly testable distinction — legal hold is one specific STEP within the larger eDiscovery process, not a synonym for the whole thing, and a write blocker (covered generally in a prior paper) is a specific forensic TOOL used during the collection step, not the overarching legal process itself. eDiscovery is a real, standard, and legally significant structured process organizations facing litigation genuinely must follow, not an ad hoc or informal undertaking.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('b80d8b59-a1a9-4924-a6e1-78cf99d011e4', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 12, 'A company runs two different vulnerability scanning approaches: one installs a small piece of software directly on each target system that continuously reports findings back to a central console, while the other scans targets remotely over the network with no software installed on the targets themselves. What are these two distinct scanning approaches called, and what is the key trade-off between them?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4e7f1b09-aff6-457d-8eeb-ea8755b269f8', 'b80d8b59-a1a9-4924-a6e1-78cf99d011e4', 0, 'Agent-based scanning (a small agent installed directly on each target, continuously reporting findings — genuinely well suited to systems that move frequently between networks, like laptops, or systems behind restrictive network segmentation that a remote scan couldn''t easily reach, at the cost of needing to deploy, maintain, and keep that agent software itself updated across the entire fleet) and agentless scanning (scanning targets remotely over the network with no software installed on the target at all — simpler to deploy at scale with no per-target agent management overhead, but genuinely limited by network reachability/segmentation and by whether the scan can obtain sufficient access, connecting to the credentialed-vs-non-credentialed scanning distinction covered generally in a prior paper, to produce accurate results).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('19c1a0c7-3d6c-43c5-a768-af284f6eb29d', 'b80d8b59-a1a9-4924-a6e1-78cf99d011e4', 1, 'Agentless scanning is specifically defined as installing software directly on each target system, while agent-based scanning means scanning remotely over the network with no software installed on the target — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d96d7821-4112-4f53-83af-27738a31c38d', 'b80d8b59-a1a9-4924-a6e1-78cf99d011e4', 2, 'Agent-based and agentless vulnerability scanning are two different names for the exact same scanning method, with no meaningful difference in deployment model or trade-offs between them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('63a27cea-d1d9-4f56-af04-0075043f5271', 'b80d8b59-a1a9-4924-a6e1-78cf99d011e4', 3, 'Vulnerability scanning can only ever be performed by installing dedicated agent software directly on every single target system, with no remote, agentless scanning option ever available.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('b80d8b59-a1a9-4924-a6e1-78cf99d011e4', '4e7f1b09-aff6-457d-8eeb-ea8755b269f8', 'This refines the general vulnerability scanning concept (covered generally in prior papers, including the credentialed-vs-non-credentialed distinction) with a genuinely important, directly testable DEPLOYMENT-MODEL distinction: agent-based scanning installs a small, persistent piece of software directly on each individual target, which then continuously monitors and reports findings back to a central console — genuinely well suited to systems that move frequently between different networks (a traveling employee''s laptop, which might not always be reachable for a remote scan) or systems sitting behind restrictive network segmentation that would otherwise block a remote scanner from ever reaching them at all, at the real, ongoing cost of needing to deploy, maintain, and keep that agent software itself patched and updated across an entire fleet — a genuine, non-trivial management burden of its own. Agentless scanning instead reaches out and scans targets remotely over the network with nothing installed on the target itself, which is genuinely simpler to deploy at scale with zero per-target agent management overhead, but is correspondingly limited by whatever network reachability actually exists between the scanner and the target (a target behind a restrictive firewall segment the scanner can''t reach simply won''t get scanned), and by whether sufficient access/credentials are available to produce genuinely accurate results, directly connecting to the credentialed-scan concept covered generally in a prior paper. This is a real, genuinely important operational trade-off organizations actively weigh when designing their vulnerability management program, not an arbitrary or non-existent distinction.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('f04af808-a73d-4f0f-839f-9f3758bd9f5e', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 13, 'After a significant security incident is fully resolved, the team holds the lessons-learned review (covered generally in a prior paper) — but specifically wants to use a structured analytical TECHNIQUE during that review to dig past the obvious, surface-level trigger and identify the actual, underlying, systemic cause the incident ultimately stemmed from, rather than stopping at a superficial explanation. What is this kind of structured, underlying-cause-focused analytical technique called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5c2e65b7-68d1-4a3e-952c-a42afafa9130', 'f04af808-a73d-4f0f-839f-9f3758bd9f5e', 0, 'Root cause analysis (using a structured technique such as the "5 Whys," repeatedly asking "why" to a surface-level explanation until reaching a genuinely underlying, systemic cause, or a fishbone/Ishikawa diagram organizing potential contributing factors into categories) — specifically the ANALYTICAL METHOD used to dig past a superficial, immediate trigger to find the actual, deeper, systemic cause, distinct from the lessons-learned review (covered generally in a prior paper) itself, which is the broader MEETING/PROCESS within which a technique like root cause analysis is often specifically applied as one structured tool.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3081daf0-7e56-4773-93a5-16b0eaae5617', 'f04af808-a73d-4f0f-839f-9f3758bd9f5e', 1, 'A lessons-learned review, since lessons-learned reviews are specifically defined as the structured analytical technique for digging past a surface-level trigger to a systemic underlying cause, rather than the broader meeting itself.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('550eddc0-6deb-4613-b1a2-b72d11797322', 'f04af808-a73d-4f0f-839f-9f3758bd9f5e', 2, 'A gap analysis, since gap analyses are specifically defined as the structured technique for digging past a superficial incident trigger to find its genuine, underlying systemic cause.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9a2a2430-a102-4d2a-8e99-79df6aeb6ab1', 'f04af808-a73d-4f0f-839f-9f3758bd9f5e', 3, 'Identifying a security incident''s genuine underlying cause, beyond its immediate, surface-level trigger, provides no meaningful additional value over simply addressing the immediate trigger alone.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('f04af808-a73d-4f0f-839f-9f3758bd9f5e', '5c2e65b7-68d1-4a3e-952c-a42afafa9130', 'Root cause analysis is specifically the ANALYTICAL TECHNIQUE applied to dig past a superficial, immediate trigger and reach the genuine, underlying, systemic cause an incident actually stemmed from — a genuinely important, directly testable distinction from the lessons-learned review (covered generally in a prior paper) itself, which is the broader MEETING/PROCESS structure within which a technique like root cause analysis is commonly and specifically applied as one of its structured analytical tools, not a synonym for the review meeting as a whole. The "5 Whys" technique specifically works by repeatedly asking "why" to each successive answer — "why did the breach happen" leads to an immediate technical answer, but asking "why" again about THAT answer, and again, and again, typically surfaces a genuinely deeper, more systemic cause (an inadequate patch management PROCESS, rather than simply "a specific unpatched server") that the immediate, surface-level trigger alone wouldn''t reveal. A fishbone (Ishikawa) diagram is an alternative structured technique organizing potential contributing factors into categories to visually map out possible root causes. This distinction matters practically because addressing only the immediate, surface-level trigger without identifying the genuine underlying systemic cause often means the SAME type of incident recurs later from the same unaddressed root cause — root cause analysis specifically exists to prevent exactly that recurrence, a real and meaningful value distinct from merely patching the immediate symptom.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('631d1ca4-e690-4e58-9e81-fe8494d5576f', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 14, 'A company deploys Data Loss Prevention (DLP, covered generally in a prior paper) in three distinct ways: monitoring traffic AT THE NETWORK LEVEL as data moves across the corporate network, monitoring activity DIRECTLY ON individual employee laptops/endpoints (catching a local file copy to USB, for example), and monitoring data stored within cloud SaaS applications the company uses. What are these three distinct DLP deployment types called, and why might an organization deploy more than one together?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('93d3ed66-6bc1-47a6-be3d-524ce91d87ff', '631d1ca4-e690-4e58-9e81-fe8494d5576f', 0, 'Network DLP (inspecting data as it moves across the network — email, web traffic, file transfers — genuinely well suited to catching data leaving via network-based channels, but unable to see purely LOCAL activity that never actually crosses the network, like a direct USB copy), endpoint DLP (an agent running directly on each individual device, able to catch genuinely local activity network-based monitoring alone would miss entirely, like a local file copy to removable media, at the cost of needing agent deployment and management across the endpoint fleet, echoing the agent-based-scanning trade-off covered earlier this paper), and cloud DLP (specifically monitoring data stored within cloud SaaS applications, connecting to the CASB concept covered generally in a prior paper, which often provides exactly this cloud-DLP-enforcement capability); deploying multiple DLP TYPES together provides genuinely more complete coverage, since each type alone has a real, different blind spot the others specifically cover.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4083349b-ff8f-44cf-9613-a73df7be84cc', '631d1ca4-e690-4e58-9e81-fe8494d5576f', 1, 'Endpoint DLP is specifically defined as inspecting data as it moves across the corporate network, while network DLP means monitoring activity directly on individual employee devices — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('5e075673-bffb-4e10-bbf4-0ff9f2dcd62a', '631d1ca4-e690-4e58-9e81-fe8494d5576f', 2, 'Network DLP, endpoint DLP, and cloud DLP are three different names for the exact same deployment approach, with no meaningful coverage difference or blind spot between any of them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e68fbba6-426c-44d1-a982-6a7f55dc5bec', '631d1ca4-e690-4e58-9e81-fe8494d5576f', 3, 'DLP can only ever be deployed as a single, undifferentiated capability with no distinction between network-level, endpoint-level, and cloud-application-level monitoring.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('631d1ca4-e690-4e58-9e81-fe8494d5576f', '93d3ed66-6bc1-47a6-be3d-524ce91d87ff', 'This refines the general DLP concept (covered generally in a prior paper) with the genuinely important, directly testable DEPLOYMENT-LOCATION distinction between three real, complementary DLP types, each with a genuinely different real-world BLIND SPOT the others specifically cover: network DLP inspects data actually crossing the network (email attachments, web uploads, file transfers) but is fundamentally blind to activity that never touches the network at all, like directly copying a file to a locally-attached USB drive. Endpoint DLP closes exactly that gap by running an agent directly on the device itself, able to observe and control genuinely local activity — directly echoing the same agent-based-monitoring trade-off (real visibility gained, at the cost of agent deployment/management overhead) covered earlier this paper for vulnerability scanning. Cloud DLP specifically addresses data living within cloud SaaS applications themselves — connecting directly to the CASB concept covered generally in a prior paper, since a CASB is frequently the actual platform ENFORCING cloud-specific DLP policy — a genuinely different data location from either network-in-transit or endpoint-local data. Deploying multiple DLP types together provides meaningfully more complete coverage precisely because each individual type''s real blind spot is a location the OTHER types are specifically positioned to cover, making a multi-layered DLP deployment a real, standard, and genuinely more effective practice than relying on any single DLP type alone.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('42c04a2d-027c-4d84-ac03-54ed3565932e', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 15, 'A company''s Business Continuity Plan addresses not just IT SYSTEM recovery, but also specifically plans for the scenario where a key LEADER or executive becomes genuinely unavailable during an actual disaster (incapacitated, unreachable, or otherwise unable to fulfill their role) — pre-designating who specifically assumes that person''s critical decision-making authority and responsibilities in that exact scenario. What is this specific planning practice called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('15b46f10-530d-4e36-843f-11769708eaf1', '42c04a2d-027c-4d84-ac03-54ed3565932e', 0, 'Continuity of Operations Planning (COOP), specifically its succession planning component — pre-designates, in a clear, unambiguous ORDER, who specifically assumes a key leader''s critical decision-making authority and responsibilities if that person becomes genuinely unavailable during an actual disaster, ensuring the organization''s LEADERSHIP and PERSONNEL continuity, genuinely distinct from (though a real, complementary component alongside) the IT-systems-focused BCP/DR concepts and hot/warm/cold alternate-site planning covered generally in prior papers, which address technology and facility recovery specifically, not who holds critical decision-making authority during a crisis.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('96fa56a7-b313-437c-997c-d7a52e5aae58', '42c04a2d-027c-4d84-ac03-54ed3565932e', 1, 'A hot site, since hot sites are specifically defined as pre-designating who assumes a key leader''s decision-making authority if that person becomes unavailable during a disaster.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ed423097-83da-40fb-a764-4273ffb7624b', '42c04a2d-027c-4d84-ac03-54ed3565932e', 2, 'A CSIRT, since CSIRTs are specifically defined as the ongoing organizational plan for leadership succession during a disaster, rather than a team activated for a specific incident.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9770a8c0-79cb-4f4e-a1e0-c8c5a1b69103', '42c04a2d-027c-4d84-ac03-54ed3565932e', 3, 'Business continuity planning only ever needs to address IT system and facility recovery; the availability and succession of key organizational leadership carries no meaningful continuity-planning significance of its own.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('42c04a2d-027c-4d84-ac03-54ed3565932e', '15b46f10-530d-4e36-843f-11769708eaf1', 'COOP succession planning specifically addresses a genuinely distinct continuity dimension from the IT-systems-and-facility-focused BCP/DR concepts covered generally in prior papers (including hot/warm/cold alternate sites) — even a technically flawless IT recovery plan and a fully-ready alternate site provide little practical value if there''s genuine confusion or a real vacuum in who actually holds critical DECISION-MAKING authority during an active crisis, precisely the kind of high-pressure, time-sensitive situation where clear, pre-established leadership succession matters most. COOP succession planning specifically pre-designates, in a clear, unambiguous order (a "line of succession"), exactly who assumes a key leader''s critical responsibilities and decision-making authority if that person becomes genuinely unavailable — incapacitated, unreachable, or otherwise unable to fulfill their role — during an actual disaster scenario, ensuring the organization''s ability to make critical decisions and take necessary action continues even if a specific key individual cannot personally be involved. This is a real, genuinely important, and complementary component of comprehensive continuity planning, distinct from a hot site (covered generally in a prior paper, an IT/facility recovery concept) and a CSIRT (covered generally in a prior paper, a team ACTIVATED for a specific incident, not an ongoing leadership-succession plan) — leadership and personnel continuity genuinely IS a real, standard, and directly addressed component of mature business continuity planning, not an afterthought.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('91349efc-866e-4d7e-863f-156c60dece83', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 16, 'A software company establishes a formal program specifically inviting independent, external security researchers to search for and report vulnerabilities in the company''s own products, offering a defined process for how to responsibly report a finding and, in some cases, a financial reward proportional to the severity of a genuine, confirmed vulnerability discovered. What is this kind of formal, external-researcher-facing program called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4f53091b-8264-41ff-be35-d7d6bb93287c', '91349efc-866e-4d7e-863f-156c60dece83', 0, 'A vulnerability disclosure program (VDP) — often including a bug bounty component specifically offering financial rewards for genuine, confirmed vulnerability findings — formally invites INDEPENDENT, EXTERNAL security researchers to search for and responsibly report vulnerabilities, providing a clear, defined reporting process and a stated commitment to how the company will respond, rather than leaving external researchers with no clear, safe, sanctioned channel to report a genuine finding (which can otherwise push a researcher toward either silence, or a public, non-coordinated disclosure that gives the company no advance opportunity to actually fix the issue before it becomes public knowledge).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('823d58f0-5d81-4723-8364-0562d565c37c', '91349efc-866e-4d7e-863f-156c60dece83', 1, 'Rules of Engagement, since Rules of Engagement are specifically defined as a formal program inviting independent, external security researchers to search for and report vulnerabilities in exchange for a financial reward.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('98956b67-7a6c-4eaf-8304-0ca7b081d1d9', '91349efc-866e-4d7e-863f-156c60dece83', 2, 'A penetration test, since penetration tests are specifically defined as an ongoing, open invitation to any independent external researcher to search for vulnerabilities, rather than an engagement scoped to one specific, pre-authorized firm.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c94b5dbc-00bf-449f-9f3c-9ef75220e9cf', '91349efc-866e-4d7e-863f-156c60dece83', 3, 'Companies should never invite independent, external security researchers to search for vulnerabilities in their own products, since doing so provides no genuine security value.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('91349efc-866e-4d7e-863f-156c60dece83', '4f53091b-8264-41ff-be35-d7d6bb93287c', 'A vulnerability disclosure program (often paired with a bug bounty component) is specifically distinguished from a traditional, scoped penetration test (covered generally in a prior paper, along with its own formal Rules of Engagement, also covered in a prior paper) by being a genuinely OPEN invitation to the broader independent security research community generally, rather than a single, specifically-authorized firm engaged for one defined, time-bound engagement — anyone in the eligible research community can participate on an ongoing basis, rather than the tightly scoped, pre-authorized, time-limited relationship a traditional pentest represents. This addresses a genuinely real, practical problem: independent researchers regularly DO discover real vulnerabilities in products they don''t work for, and without a clear, safe, sanctioned reporting channel and process, a researcher who finds something genuine faces an awkward choice — staying silent (meaning the company never learns about a real, exploitable issue at all), or disclosing it publicly with no advance coordination (which can leave the company with zero opportunity to actually fix the issue before it becomes public and potentially actively exploited). A formal VDP, with a bug bounty specifically offering a genuine financial incentive proportional to severity, gives researchers a real, positive reason to report responsibly through the sanctioned channel rather than defaulting to either alternative — this is a real, standard, and increasingly common industry practice specifically because it provides real, genuine security value that traditional, narrowly-scoped internal testing alone often misses.');

-- ── Domain: Security Program Management & Oversight (20% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('c7ae9fef-9b29-44cb-8d01-70679252cccf', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 17, 'A technology vendor wants to sell its cloud product to US federal government agencies, and discovers this requires obtaining a specific government-mandated security authorization — distinct from any of the private-sector-focused compliance frameworks or regulations covered elsewhere (HIPAA, PCI-DSS, GDPR, SOX) — specifically standardizing security assessment and authorization for cloud services used BY the US federal government. What is this specific government authorization program called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('e2062ed5-b679-4295-b96d-680783e4240f', 'c7ae9fef-9b29-44cb-8d01-70679252cccf', 0, 'FedRAMP (the Federal Risk and Authorization Management Program) — a US government program specifically standardizing security assessment, authorization, and continuous monitoring requirements for CLOUD services used by US federal agencies, distinct from FISMA (the broader Federal Information Security Management Act, which more generally governs federal information security overall, with FedRAMP specifically implementing FISMA''s requirements for the cloud-services context specifically) — genuinely distinct in both SCOPE (government agencies as the customer, not private-sector consumers or specific data types like health/payment/EU-personal data) and AUTHORITY (a specific US federal government program) from every other regulation or standard covered elsewhere (HIPAA, GDPR, PCI-DSS, SOX).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('abc77deb-ce7f-42ab-aec2-406c3a65a8f2', 'c7ae9fef-9b29-44cb-8d01-70679252cccf', 1, 'PCI-DSS, since PCI-DSS is specifically the US government program standardizing security assessment and authorization for cloud services used by US federal agencies.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('bbaf178f-c4d5-4b9c-8774-21f021725dd5', 'c7ae9fef-9b29-44cb-8d01-70679252cccf', 2, 'SOX, since SOX is specifically defined as the government program authorizing cloud services specifically for use by US federal agencies, rather than governing publicly traded companies'' financial reporting.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8382507f-6f63-4a03-a32e-53c0c881b515', 'c7ae9fef-9b29-44cb-8d01-70679252cccf', 3, 'No specific government authorization requirement exists for cloud services sold to US federal agencies; standard private-sector compliance frameworks alone are always sufficient for any government sale.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('c7ae9fef-9b29-44cb-8d01-70679252cccf', 'e2062ed5-b679-4295-b96d-680783e4240f', 'FedRAMP is specifically distinguished by its SCOPE and AUTHORITY — a US federal GOVERNMENT program (not an industry standard like PCI-DSS, covered generally in a prior paper, and not a general federal LAW like SOX, covered generally in a prior paper, which instead governs publicly traded companies'' financial reporting broadly) specifically standardizing how CLOUD services are security-assessed and authorized for actual use BY federal agencies, addressing the government''s own, genuinely distinct procurement and risk-tolerance requirements when adopting cloud technology, requirements meaningfully different from what any private-sector-focused framework addresses. FISMA is the broader federal law governing information security across federal agencies generally, with FedRAMP specifically implementing and standardizing FISMA''s requirements for the cloud-services procurement context in particular — a real, meaningful two-tier relationship (broad law, specific cloud-focused implementation program) rather than two interchangeable names for the same thing. This is genuinely distinct in both scope and authority from every other regulation covered elsewhere across this project''s Security+ content (HIPAA for health information, GDPR for EU personal data broadly, PCI-DSS for payment card data, SOX for financial reporting integrity) — a real, significant, and directly relevant authorization requirement for any vendor genuinely targeting the US federal government as a customer, not an optional or non-existent formality.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('c515889c-d481-4c03-baa5-04868bce276e', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 18, 'A company evaluating a SaaS vendor requests a SOC 2 report as part of their vendor risk assessment (covered generally in a prior paper). The vendor offers a choice between a "Type I" report and a "Type II" report. What is the key difference between these two SOC 2 report types, and which generally provides stronger assurance?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('72da9202-0d47-43b5-94bd-36ad7ff067c4', 'c515889c-d481-4c03-baa5-04868bce276e', 0, 'A SOC 2 Type I report assesses whether a vendor''s security controls are appropriately DESIGNED as of a single POINT IN TIME (a snapshot), while a SOC 2 Type II report goes further, assessing whether those same controls actually OPERATED EFFECTIVELY over an extended OBSERVATION PERIOD (typically 6-12 months) — Type II generally provides meaningfully stronger assurance specifically because it verifies genuine, sustained operational effectiveness over time, not merely that a control was well-designed on paper at one specific moment, which a Type I report alone cannot confirm.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('310465da-bfdc-47de-9879-fa5e4ccd63ca', 'c515889c-d481-4c03-baa5-04868bce276e', 1, 'A SOC 2 Type II report assesses controls at a single point in time, while a SOC 2 Type I report assesses control effectiveness over an extended observation period — the reverse of the correct definitions.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b2d1a76b-53a8-49af-8175-9900d632e984', 'c515889c-d481-4c03-baa5-04868bce276e', 2, 'SOC 2 Type I and Type II reports are functionally identical in scope and assurance level, with no meaningful difference in observation period or the strength of assurance either report actually provides.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f8030729-8b3f-413c-bd03-8f87cd0e052b', 'c515889c-d481-4c03-baa5-04868bce276e', 3, 'A SOC 2 report of either type only ever assesses whether a vendor''s security policy DOCUMENT exists, with no evaluation of whether the vendor''s actual controls are appropriately designed or genuinely operating as claimed.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('c515889c-d481-4c03-baa5-04868bce276e', '72da9202-0d47-43b5-94bd-36ad7ff067c4', 'This refines the general third-party audit and vendor risk management concepts (both covered generally in prior papers) with a genuinely important, directly testable nuance specific to SOC 2 reports — a Type I report is a narrower, POINT-IN-TIME assessment, confirming that a vendor''s described security controls are appropriately DESIGNED as of one specific date, but says nothing about whether those controls have actually operated effectively, consistently, and as intended over any meaningful stretch of real time. A Type II report goes meaningfully further, assessing whether those SAME controls genuinely operated effectively over an extended OBSERVATION PERIOD (commonly six to twelve months) — directly verifying sustained, real-world operational effectiveness, not merely a well-designed control existing on paper at a single snapshot moment. This is exactly why Type II is generally considered to provide meaningfully STRONGER assurance for vendor risk assessment purposes — a control that''s well-designed but poorly or inconsistently OPERATED in actual practice provides materially less real protection than the paper design alone might suggest, a gap only a Type II report''s extended observation period can actually verify. Understanding this Type I versus Type II distinction directly and practically matters when a company is genuinely evaluating which specific report type to request or accept as sufficient evidence during vendor due diligence.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('1b2363bf-dc01-4c57-b9ad-3f3d73d69328', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 19, 'A company''s employees have started using public generative AI chatbot tools for work tasks, including occasionally pasting genuinely sensitive internal information (unreleased product plans, customer data) into the chatbot to get help drafting or analyzing it — without realizing that data entered into a public AI tool may be retained, logged, or potentially used by the AI provider in ways the company never explicitly authorized or reviewed. What governance response specifically addresses this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6f6333c2-0383-4416-bfa8-3ca8e91325fd', '1b2363bf-dc01-4c57-b9ad-3f3d73d69328', 0, 'A formal generative AI acceptable use policy — explicitly defines what categories of company data may or may NOT be entered into external, public generative AI tools (directly connecting to data classification, covered generally in a prior paper, since a well-defined data classification scheme provides the natural basis for defining exactly which classification tiers are and aren''t appropriate to paste into a public AI tool), which specific AI tools (if any) are actually approved for work use, and what employees should genuinely understand about how their submitted data may be retained, logged, or otherwise used by the external AI provider — directly addressing this genuinely modern, real, and increasingly common data-exposure risk before an actual sensitive-data-leakage incident occurs, rather than after one already has.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2f85e2d8-32e4-44a1-8b51-85886f1f6bb7', '1b2363bf-dc01-4c57-b9ad-3f3d73d69328', 1, 'A BAA, since BAAs are specifically defined as the governance document establishing what categories of company data employees may or may not paste into an external generative AI tool.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3f2794b9-ec3d-4e28-add6-72bb2d3810c7', '1b2363bf-dc01-4c57-b9ad-3f3d73d69328', 2, 'A gap analysis, since gap analyses are specifically defined as the policy document establishing which generative AI tools are approved for work use and what data may be entered into them.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d8327751-569b-4e5d-8a46-99384b40ade1', '1b2363bf-dc01-4c57-b9ad-3f3d73d69328', 3, 'Employees pasting sensitive company data into a public, external generative AI tool poses no meaningful data-exposure risk, since AI providers never retain, log, or make any use of data submitted through their tools.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('1b2363bf-dc01-4c57-b9ad-3f3d73d69328', '6f6333c2-0383-4416-bfa8-3ca8e91325fd', 'A generative AI acceptable use policy directly extends the general AUP concept (covered generally in a prior paper, for acceptable IT usage broadly) with a genuinely modern, increasingly common, and real governance gap this scenario specifically illustrates — employees using a genuinely new, powerful class of external tool with real, non-obvious data-handling implications that most employees have no particular reason to already understand or think carefully about on their own. A well-constructed policy directly connects to and leverages the organization''s existing data classification scheme (covered generally in a prior paper) as its natural foundation — clearly stating, for instance, that Public and Internal-tier data might be acceptable to use with an approved AI tool, while Confidential and Restricted-tier data (connecting to the same classification concept) never should be, giving employees a clear, concrete, and already-familiar framework rather than a vague, generic "be careful" instruction. The policy should also specifically address which AI tools (if any) are actually organizationally approved, since different tools carry genuinely different data-retention and data-usage terms, and should ensure employees genuinely understand that data entered into many public AI tools may be logged, retained, or potentially used in ways the company never explicitly reviewed or approved — a real, legitimate, and non-hypothetical data-exposure risk this policy specifically exists to proactively address before an actual sensitive-data leak occurs, not merely after.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('e08922b0-f9ce-4ac9-b7d8-61b543ab825d', 'cde3aa69-4bbc-49cd-9577-f5f79381db57', 20, 'A company wants to test its Business Continuity/Disaster Recovery plan using progressively more rigorous methods: first, simply reviewing the written plan document as a group discussion (covered generally as a tabletop exercise in a prior paper); then, actually walking through the specific step-by-step PROCEDURES in detail without executing them for real; then, actually running the plan''s systems in parallel alongside normal production operations to confirm they genuinely work; and finally, a full test that actually interrupts normal production operations entirely to confirm the plan works completely for real. What is this progression of BCP/DR testing rigor called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0ba48048-fdae-4738-8aa0-3f6056a9f37f', 'e08922b0-f9ce-4ac9-b7d8-61b543ab825d', 0, 'BCP/DR test types, forming a progression of increasing rigor and realism: a tabletop exercise (covered generally in a prior paper, discussion-based, lowest cost and disruption), a walkthrough (a more detailed, step-by-step review of specific procedures, still without actually executing them), a parallel test (actually running the recovery systems alongside normal production to confirm they genuinely work, without disrupting production at all), and a full interruption test (the most rigorous and realistic, actually stopping normal production operations to confirm the plan works completely under real conditions) — each successive type provides genuinely stronger real-world confidence that the plan actually works, at correspondingly higher cost, complexity, and real operational risk/disruption.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('78e76cc1-c5ce-4410-b37a-5abbafd48783', 'e08922b0-f9ce-4ac9-b7d8-61b543ab825d', 1, 'A full interruption test is specifically defined as the lowest-rigor, discussion-based review with no actual disruption, while a tabletop exercise is the highest-rigor test that actually stops normal production operations — the reverse of the correct ordering.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('70e85b21-4a5d-412f-8109-91c4eb272319', 'e08922b0-f9ce-4ac9-b7d8-61b543ab825d', 2, 'Every BCP/DR test type provides functionally identical rigor, cost, and real-world confidence, with no meaningful progression or distinction in realism between a tabletop exercise and a full interruption test.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b678d299-5814-47f4-936b-1c5ba035906a', 'e08922b0-f9ce-4ac9-b7d8-61b543ab825d', 3, 'A Business Continuity/Disaster Recovery plan can only ever be tested using a single, undifferentiated method, with no distinction between a discussion-based review and an actual, full production interruption.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('e08922b0-f9ce-4ac9-b7d8-61b543ab825d', '0ba48048-fdae-4738-8aa0-3f6056a9f37f', 'This progression directly extends the tabletop exercise concept (covered generally in a prior paper, as the lowest-rigor, discussion-based method) into the FULL spectrum of standard BCP/DR test types, each providing genuinely increasing real-world confidence at correspondingly increasing cost, complexity, and operational risk: a tabletop exercise walks through the plan at a HIGH level as group discussion, with no actual technical execution of anything at all. A walkthrough goes a level deeper, reviewing the SPECIFIC, detailed, step-by-step procedures the plan actually calls for (who does exactly what, in what order) without yet actually executing any of those steps for real. A parallel test moves to genuine technical execution — actually standing up and running the recovery systems ALONGSIDE normal production operations, confirming those systems genuinely work as intended, but without touching or disrupting production at all, since production keeps running normally the whole time. A full interruption test is the most rigorous and realistic of all — actually stopping normal production operations entirely and genuinely relying on the recovery plan to bring things back, providing the strongest possible real-world confidence the plan actually works under genuinely real conditions, but at the real, meaningful cost of actually disrupting live production operations to run the test itself. This directly connects to and extends the hot/warm/cold alternate-site cost-versus-readiness trade-off (covered generally in a prior paper) — a genuinely similar underlying principle of increasing rigor and realism trading off against increasing cost and risk, applied here specifically to how the plan itself is TESTED and validated, not merely designed.');
