-- ============================================================
-- CompTIA Security+ (SY0-701) — Seed Data: Paper 2
-- New content, distinct topics from Paper 1 (docs/secplus_seed_paper_1.sql)
-- — no repeated scenarios. Same domain weighting: General Security Concepts
-- 12% (2/20), Threats/Vulnerabilities/Mitigations 22% (4/20), Security
-- Architecture 18% (4/20), Security Operations 28% (6/20), Security
-- Program Management & Oversight 20% (4/20).
--
-- IDs were generated via scripts/fill-seed-uuids.mjs, which replaces every
-- distinct placeholder token with a fresh, real UUID (consistently across
-- every occurrence of that token) — this file has already had that script
-- run against it; the UUIDs below are real. This is a deliberate process
-- change after two real UUID-collision
-- bugs in earlier papers (AWS SAA Papers 1 and 3) caused by manual
-- tracking errors across a long file — a script cannot make that mistake
-- the way manual bookkeeping did twice.
-- Run scripts/fill-seed-uuids.mjs on this file BEFORE running it against
-- the database. It is run AFTER docs/question-bank-schema.sql.
-- ============================================================

INSERT INTO question_papers (id, slug, title, exam_type, focus_tags, question_count, difficulty, is_premium, sort_order, time_limit_minutes)
VALUES ('da3fe4db-b47b-42f6-98dd-d09b7def39c8', 'secplus-practice-2', 'CompTIA Security+ (SY0-701) Practice Paper 2', 'comptia-sec-plus', ARRAY['PKI', 'VPN', 'Patch Management', 'IDS/IPS', 'Hashing', 'Business Impact Analysis', 'Insider Threat', 'Data Classification']::TEXT[], 20, 'standard', true, 2, 30);

-- ── Domain: General Security Concepts (12% — 2 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('a58a0c95-e0dd-43dc-89b2-10c552b7ddff', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 1, 'A file is downloaded and its SHA-256 hash is compared against the hash published by the vendor to confirm the file was not corrupted or tampered with during transfer. What security property is being verified here, and why is a hash (rather than encryption) the right tool?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4478847d-7e5d-4e56-8aa6-335144b7c1df', 'a58a0c95-e0dd-43dc-89b2-10c552b7ddff', 0, 'Confidentiality — hashing is used here because it hides the file''s contents from anyone who does not have the decryption key.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3d0e739c-5b49-45ac-b5c2-211278197ffb', 'a58a0c95-e0dd-43dc-89b2-10c552b7ddff', 1, 'Integrity — a cryptographic hash produces a fixed-size fingerprint that changes if even one bit of the input changes, so comparing hashes confirms the file is byte-for-byte identical to the original; hashing is used (not encryption) because the goal is verification, not concealment, and hashing is one-way (not meant to be reversed).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d5239e0a-c48e-4df9-b3e7-82282167acde', 'a58a0c95-e0dd-43dc-89b2-10c552b7ddff', 2, 'Non-repudiation — hashing proves who sent the file and prevents them from denying it.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f8d55c93-db29-4384-af29-c8395ecc41fa', 'a58a0c95-e0dd-43dc-89b2-10c552b7ddff', 3, 'Availability — hashing ensures the file will always be downloadable in the future.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('a58a0c95-e0dd-43dc-89b2-10c552b7ddff', '3d0e739c-5b49-45ac-b5c2-211278197ffb', 'A cryptographic hash function (SHA-256 being a current, strong example) takes an input of any size and produces a fixed-length output (the "digest" or "fingerprint") such that even a tiny change to the input produces a completely different output — this makes hash comparison an effective way to verify integrity (the file is exactly what it claims to be, unmodified). Hashing is the right tool specifically BECAUSE it''s one-way and not meant to reveal or protect the content''s secrecy — the goal here is verification, not concealment, which is why encryption (a two-way, reversible transformation meant to protect confidentiality) is not what''s being used or needed. Non-repudiation typically requires a digital signature (hash + asymmetric encryption combined, tied to an identity) — a plain hash comparison alone doesn''t prove WHO produced the file, only that it matches a known-good version. Hashing has no relationship to future availability of a file.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('b7130166-6242-4fcd-b55d-507f0e3ed89d', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 2, 'A company deploys a Public Key Infrastructure (PKI) to issue digital certificates to its internal servers. What is the core purpose of the Certificate Authority (CA) in this system, and what happens if a server''s private key is compromised?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c7612c33-8f89-4a5f-868c-784ee3442754', 'b7130166-6242-4fcd-b55d-507f0e3ed89d', 0, 'The CA''s role is to store every server''s private key centrally; if a private key is compromised, nothing needs to happen since the CA can simply issue a new copy of the same key.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f6dd7835-af12-41d8-8d0f-b4f921cde203', 'b7130166-6242-4fcd-b55d-507f0e3ed89d', 1, 'The CA is a trusted third party that issues and digitally signs certificates, vouching that a given public key genuinely belongs to the named entity; if a private key is compromised, the corresponding certificate must be revoked (e.g., via a CRL or OCSP) so relying parties stop trusting it, and a new key pair/certificate must be issued.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('da6cc938-9443-4ed7-9584-e6365f15b469', 'b7130166-6242-4fcd-b55d-507f0e3ed89d', 2, 'The CA has no role once a certificate is issued, and a compromised private key has no security implications as long as the certificate has not expired.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('86589183-f4ad-4115-a988-ba260a9f753f', 'b7130166-6242-4fcd-b55d-507f0e3ed89d', 3, 'The CA''s only function is to generate random encryption keys for VPN tunnels, unrelated to certificates.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('b7130166-6242-4fcd-b55d-507f0e3ed89d', 'f6dd7835-af12-41d8-8d0f-b4f921cde203', 'A Certificate Authority is a trusted third party whose core function is to verify an entity''s identity and then issue a digital certificate binding that entity''s public key to their verified identity, digitally signed by the CA itself — this is what lets a relying party trust "this public key really belongs to this server," rather than having to independently verify every single entity themselves. If a private key is compromised, the security guarantee is broken (an attacker could impersonate the server or decrypt intercepted traffic), so the certificate MUST be revoked — added to a Certificate Revocation List (CRL) or checked via OCSP (Online Certificate Status Protocol) — so that other systems stop trusting it, and a fresh key pair with a new certificate must be issued to replace it. A CA never stores or possesses a server''s PRIVATE key (only the public key is submitted for the certificate) — that would defeat the entire security model of asymmetric cryptography, since the private key must remain exclusively with its owner.');

-- ── Domain: Threats, Vulnerabilities & Mitigations (22% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('997f460a-2ae4-4359-96a5-2e262df54773', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 3, 'A company discovers that dozens of their servers remain unpatched for a critical, publicly known vulnerability six months after a patch was released, despite having a patch management process on paper. What is the most likely root operational failure, and what should the patch management process ensure going forward?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c9833d36-2549-45b6-940a-69334a9b6753', '997f460a-2ae4-4359-96a5-2e262df54773', 0, 'Patches should never be applied to production servers under any circumstances, since patching itself is the security risk.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('605de470-a8d7-40e2-b61f-e31e625a361a', '997f460a-2ae4-4359-96a5-2e262df54773', 1, 'The process likely lacks consistent tracking/enforcement (e.g., an inventory of what needs patching, a defined patch testing and deployment cadence, and verification that patches actually applied) — a written policy alone does not patch systems; the process needs measurable, enforced execution with visibility into which systems are actually up to date.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('41e24cfe-2b34-45d1-91a9-1552dafc5250', '997f460a-2ae4-4359-96a5-2e262df54773', 2, 'This is not a real operational risk as long as a firewall exists somewhere on the network.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4201d5dc-68be-4599-989f-766d6d08fb0a', '997f460a-2ae4-4359-96a5-2e262df54773', 3, 'Patch management is solely the responsibility of the software vendor, not the organization running the software.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('997f460a-2ae4-4359-96a5-2e262df54773', '605de470-a8d7-40e2-b61f-e31e625a361a', 'A patch management process existing "on paper" is not the same as patches actually being applied — a real, effective process requires an accurate asset/software inventory (so you know what needs patching), a defined cadence for testing and deploying patches (balancing speed against the risk of an untested patch breaking something), and verification/reporting that confirms patches were actually applied successfully across the fleet, not just scheduled. Six months unpatched against a KNOWN, PUBLIC vulnerability is a serious, realistic risk — attackers routinely scan for and exploit exactly this kind of known, unpatched weakness, and a firewall does not compensate for an unpatched, directly reachable (or even internally reachable, post-initial-compromise) vulnerable service. While a vendor releases the patch, applying it to the organization''s own systems is unambiguously the organization''s own operational responsibility, not something that happens automatically or is the vendor''s job to enforce.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('d6d09dd4-37f3-4678-9ba1-114c71c86cfe', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 4, 'An attacker gains physical access to a locked server room by closely following an authorized employee through a badge-controlled door without swiping their own badge, relying on the employee holding the door open. What social engineering/physical security term describes this, and what control specifically mitigates it?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('24ee86df-f9aa-4e99-a2f2-37d1c7bf2514', 'd6d09dd4-37f3-4678-9ba1-114c71c86cfe', 0, 'Tailgating (or piggybacking); mitigated by controls like mantraps (interlocking doors allowing only one person through per authenticated badge scan) and a security-awareness culture of not holding doors open for unbadged individuals.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('37de4c91-3d78-4a2c-9034-6371804ed0ed', 'd6d09dd4-37f3-4678-9ba1-114c71c86cfe', 1, 'Whaling; mitigated by antivirus software installed on the server room''s door lock system.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('170625a6-634a-4747-a28a-46ae76371b2d', 'd6d09dd4-37f3-4678-9ba1-114c71c86cfe', 2, 'Vishing; mitigated by disabling the phone lines in the server room.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8c2b6f7c-fb01-4dd4-a372-0c199336ec52', 'd6d09dd4-37f3-4678-9ba1-114c71c86cfe', 3, 'SQL injection; mitigated by parameterized queries on the badge reader''s database.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('d6d09dd4-37f3-4678-9ba1-114c71c86cfe', '24ee86df-f9aa-4e99-a2f2-37d1c7bf2514', 'Tailgating (also called piggybacking) is specifically the physical social engineering technique of following an authorized person through a secured entry point without independently authenticating — relying on courtesy (someone holding a door) rather than exploiting any technical vulnerability. The direct mitigation is a mantrap: a small interlocking-door vestibule that only allows one authenticated person through at a time (the outer door must close and lock before the inner door will open), physically preventing a second, unbadged person from following through — combined with security-awareness training teaching employees not to hold secured doors open for people who haven''t badged in themselves, even if it feels socially awkward not to. Whaling and vishing are both DIFFERENT social engineering categories (executive-targeted email, and voice/phone-based, respectively) — neither matches a physical-entry scenario. SQL injection is an unrelated web-application vulnerability class, irrelevant to a physical door.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('5a015e0c-a976-4056-a47f-32935953bcb2', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 5, 'A network security team deploys a device that monitors network traffic for known attack signatures and anomalous patterns; when configured in "inline" mode, it can automatically block detected malicious traffic in real time rather than only alerting after the fact. What is this device called in each mode?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0473cffd-beff-47cf-b90c-8940bdda29d3', '5a015e0c-a976-4056-a47f-32935953bcb2', 0, 'In passive/monitoring mode it is an IDS (Intrusion Detection System, which alerts but does not block); in inline/active-blocking mode it is an IPS (Intrusion Prevention System, which can automatically block detected malicious traffic in real time).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('4b11a811-b205-44e6-ba8e-369308d5bb5c', '5a015e0c-a976-4056-a47f-32935953bcb2', 1, 'IDS and IPS are fully interchangeable terms describing identical capability with no distinction in blocking behavior.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('988a6077-0571-4f12-9353-1411998e4754', '5a015e0c-a976-4056-a47f-32935953bcb2', 2, 'This device is called a VPN concentrator regardless of which mode it operates in.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('71ebebd8-28b5-4603-b844-fdaf4fcd4add', '5a015e0c-a976-4056-a47f-32935953bcb2', 3, 'This device is only ever called a firewall, and firewalls and IDS/IPS are the same technology.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('5a015e0c-a976-4056-a47f-32935953bcb2', '0473cffd-beff-47cf-b90c-8940bdda29d3', 'IDS (Intrusion Detection System) and IPS (Intrusion Prevention System) describe the same underlying detection technology deployed in two different modes, and Security+ tests this distinction precisely: an IDS is typically deployed passively (out-of-band, monitoring a copy of traffic) — it can DETECT and ALERT on suspicious patterns/signatures, but does not sit inline in the traffic path and cannot itself block anything. An IPS is deployed INLINE (directly in the traffic path), which lets it actively block/drop malicious traffic in real time as it''s detected, not just alert after the fact. This detect-only vs. actively-block distinction, tied directly to deployment mode (passive vs. inline), is exactly what the question is testing — the two terms are not interchangeable, and getting the mode-to-capability mapping backwards is a common mistake. A VPN concentrator handles encrypted remote-access tunnels, an unrelated function. A firewall filters traffic by rule (IP/port/protocol) but does not perform the same signature/anomaly-based traffic INSPECTION that IDS/IPS specifically does — firewalls and IDS/IPS are related but genuinely distinct security control types, often deployed together.');

-- ── Domain: Security Architecture (18% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('51d7ec57-8469-4ab3-9290-8e9451b49c92', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 6, 'A remote employee connects to the corporate network over the public internet using an encrypted tunnel, so their traffic cannot be read by anyone intercepting it on the untrusted network in between. What is this technology called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('040c7d6b-c9ec-4986-9e34-84e67a735ebc', '51d7ec57-8469-4ab3-9290-8e9451b49c92', 0, 'A VPN (Virtual Private Network), which creates an encrypted tunnel over an untrusted network (like the public internet), protecting the confidentiality of traffic passing through it between the remote endpoint and the corporate network.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('600be3c7-91c0-449d-be69-4233b0996e2d', '51d7ec57-8469-4ab3-9290-8e9451b49c92', 1, 'A DMZ, since DMZs are what create encrypted tunnels for remote employees.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ce80c341-be19-4743-9120-6e90098afc99', '51d7ec57-8469-4ab3-9290-8e9451b49c92', 2, 'A honeypot, since honeypots are designed to securely connect remote employees to the corporate network.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a95a99a5-848c-40c5-b117-fae41ff3e84f', '51d7ec57-8469-4ab3-9290-8e9451b49c92', 3, 'A load balancer, since load balancers provide encrypted remote connectivity for individual employees.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('51d7ec57-8469-4ab3-9290-8e9451b49c92', '040c7d6b-c9ec-4986-9e34-84e67a735ebc', 'A VPN establishes an encrypted tunnel between an endpoint (the remote employee''s device) and a destination network (the corporate network), so that even though the traffic physically traverses an untrusted network (the public internet) in between, anyone intercepting the raw packets cannot read the actual content — the encryption protects confidentiality across that untrusted segment specifically. A DMZ is a network segmentation concept for hosting public-facing servers (covered in Paper 1), unrelated to remote-user connectivity. A honeypot is a decoy system designed to attract and study attackers, not a legitimate connectivity mechanism. A load balancer distributes traffic across multiple backend servers for performance/availability — it has no inherent remote-access encryption function of its own.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('c8fbb0ee-cbe0-4afd-91cc-908292b4e290', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 7, 'A company wants to ensure that even if an attacker compromises one microservice in a containerized application, they cannot easily move laterally to access every other microservice and the underlying database directly. What architecture principle, applied at the network level between microservices, addresses this?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a5ce3504-354b-4845-98af-78764dbb094a', 'c8fbb0ee-cbe0-4afd-91cc-908292b4e290', 0, 'Micro-segmentation — applying granular network policies BETWEEN individual workloads/microservices (not just at the traditional network perimeter), so that a compromised service only has network access to the specific other services it genuinely needs to communicate with, not the entire environment.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('28fe0d96-c450-4ef7-8ed5-5fc62218a063', 'c8fbb0ee-cbe0-4afd-91cc-908292b4e290', 1, 'Allowing all microservices unrestricted network access to each other by default, since restricting internal traffic provides no security benefit once perimeter security exists.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('59d22ff5-13f9-4965-a6ed-8c8f755d21df', 'c8fbb0ee-cbe0-4afd-91cc-908292b4e290', 2, 'Relying exclusively on a single perimeter firewall at the network edge, with no internal traffic restrictions between services.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b8f47296-ee1a-4cce-9129-f772e1b738c3', 'c8fbb0ee-cbe0-4afd-91cc-908292b4e290', 3, 'Micro-segmentation refers only to physically splitting a data center into smaller buildings, unrelated to network policy.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('c8fbb0ee-cbe0-4afd-91cc-908292b4e290', 'a5ce3504-354b-4845-98af-78764dbb094a', 'Micro-segmentation extends the network-segmentation concept (like a DMZ, covered in Paper 1, which segments at a coarser level) down to the level of INDIVIDUAL workloads/microservices — instead of one broad internal network where everything can reach everything once past the perimeter, granular policies define exactly which specific services each microservice is allowed to communicate with. This directly limits an attacker''s ability to move laterally after compromising one component: even with that one service compromised, the attacker''s network reach is confined to only what that specific service legitimately needs, not the entire internal environment — a concrete implementation of both defense in depth and Zero Trust principles (covered in Paper 1) at the microservice level. Relying solely on a perimeter firewall with unrestricted lateral movement inside is exactly the "hard shell, soft interior" anti-pattern micro-segmentation and Zero Trust both exist to correct. It is a network/workload security concept, not a physical facilities term.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('5cdffc30-11cf-4147-b321-2fdeb342847e', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 8, 'A company maintains an environment that closely mimics production, complete with realistic-looking (but fake) data and services, specifically to lure and observe attackers, study their techniques, and divert them away from real production systems. What is this environment called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('43a37a1c-231a-48eb-9729-db44fb1d22e8', '5cdffc30-11cf-4147-b321-2fdeb342847e', 0, 'A honeynet (a network of honeypots) — a deliberately deployed decoy environment designed to attract attackers, allowing the security team to observe attacker behavior/techniques in a controlled setting while diverting them away from genuinely valuable production systems.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('faeb5fbf-8205-438a-a942-6085e594e1c3', '5cdffc30-11cf-4147-b321-2fdeb342847e', 1, 'A DMZ, since DMZs are specifically built with fake data to attract attackers.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f3e2c406-ab42-4506-8936-8a37318227b1', '5cdffc30-11cf-4147-b321-2fdeb342847e', 2, 'A SIEM, since SIEMs are decoy environments built to lure attackers.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('abc432dc-7760-44c8-b5cb-be2eac570461', '5cdffc30-11cf-4147-b321-2fdeb342847e', 3, 'A VPN concentrator, since VPN concentrators are designed to mimic production environments for attackers.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('5cdffc30-11cf-4147-b321-2fdeb342847e', '43a37a1c-231a-48eb-9729-db44fb1d22e8', 'A honeynet (a full decoy network/environment of honeypots — a single decoy system alone is a "honeypot") is deliberately designed to look like a genuine, valuable target, complete with realistic fake data and services, specifically to attract attacker attention. This serves multiple purposes: it diverts attackers away from real production assets, and it lets the security team observe exactly what techniques, tools, and objectives an attacker pursues once inside — real threat intelligence gathered in a controlled, contained setting with no real risk to actual production data. A DMZ hosts genuinely functional public-facing services, not fake decoy data, and serves a different purpose (isolating real public-facing systems, not luring attackers). A SIEM aggregates and correlates real log data for detection (covered in Paper 1) — it is a monitoring tool, not a decoy environment. A VPN concentrator handles real encrypted remote-access connections, unrelated to deception technology.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('d2d5263b-47a5-4852-94ec-8259ea75690e', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 9, 'A company classifies its data into tiers (e.g., Public, Internal, Confidential, Restricted) and applies different handling, storage, and access requirements to each tier based on its sensitivity. What is this practice called, and why does it matter for security program design?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('809f8a3f-a167-416e-8a83-7543d38a0fbd', 'd2d5263b-47a5-4852-94ec-8259ea75690e', 0, 'Data classification — labeling data by sensitivity level so appropriately-scaled controls (encryption requirements, access restrictions, retention rules) can be applied; without it, organizations tend to either under-protect sensitive data or waste resources over-protecting everything uniformly, including data that doesn''t need it.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d5349919-8980-45e4-9c03-2615855bfb74', 'd2d5263b-47a5-4852-94ec-8259ea75690e', 1, 'Data classification is purely a legal formality with no actual bearing on which technical security controls get applied.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3c8cb659-0221-4f06-953c-5c19deef5bdc', 'd2d5263b-47a5-4852-94ec-8259ea75690e', 2, 'This practice is called encryption, since assigning labels to data is the definition of encrypting it.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('08aff25d-7d94-4cde-96f7-f6f662557b63', 'd2d5263b-47a5-4852-94ec-8259ea75690e', 3, 'This practice provides no security benefit, since all data should always receive identical maximum protection regardless of actual sensitivity.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('d2d5263b-47a5-4852-94ec-8259ea75690e', '809f8a3f-a167-416e-8a83-7543d38a0fbd', 'Data classification is the practice of labeling data according to its sensitivity/impact level (common tiers: Public, Internal, Confidential, Restricted/Top Secret), which then drives which specific controls apply to each tier — e.g., Restricted data might require encryption at rest and in transit, strict access logging, and a short retention period, while Public data needs none of that. This matters directly for practical security program design because treating ALL data identically is inefficient in both directions: applying maximum controls uniformly wastes real resources (cost, performance, operational friction) on data that doesn''t need it, while a lack of classification often means genuinely sensitive data doesn''t get the elevated protection it actually requires, since nothing distinguished it from everything else. Classification is a foundational data-governance practice, not merely a legal formality, and it is a distinct concept from encryption (which is one POSSIBLE control applied AS A RESULT of a data''s classification, not the classification process itself).');

-- ── Domain: Security Operations (28% — 6 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('3d534325-5961-4929-9f13-8252ab42f2c8', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 10, 'A former employee''s user account is discovered still active with valid login credentials three months after their last day, and an investigation reveals they accessed company files during that window. What process failure does this represent, and what control specifically should have prevented it?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('0de5a35b-9aea-4dc0-9c17-9c5867d32f0f', '3d534325-5961-4929-9f13-8252ab42f2c8', 0, 'A failure in the offboarding/deprovisioning process — accounts should be disabled or removed as part of a defined offboarding checklist at (or immediately after) an employee''s departure date, not left active indefinitely; this is a common, real-world example of insider-threat risk persisting from a FORMER insider whose access was never properly revoked.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('71e0c2e3-cb03-4175-8439-5db4454a2a8b', '3d534325-5961-4929-9f13-8252ab42f2c8', 1, 'This is not a real security failure, since former employees have no meaningful ability to cause harm once they no longer work at the company.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('01ca5b91-cfd7-45b2-997d-25594ae1ebe2', '3d534325-5961-4929-9f13-8252ab42f2c8', 2, 'This is purely an HR issue with no security-team responsibility or overlap whatsoever.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('208ff887-b0d4-42c6-9a38-9b6564d6872a', '3d534325-5961-4929-9f13-8252ab42f2c8', 3, 'The correct fix is to give the former employee a new, stronger password rather than disabling the account.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('3d534325-5961-4929-9f13-8252ab42f2c8', '0de5a35b-9aea-4dc0-9c17-9c5867d32f0f', 'This scenario is a textbook offboarding/deprovisioning failure — account access should be revoked as a mandatory, timely step in the employee departure process (ideally on their last working day, sometimes even immediately upon notice for higher-risk roles), not left to linger. A former employee retaining valid access is a genuine, well-documented insider-threat risk category — someone with legitimate former credentials and (often) real knowledge of internal systems, potentially with motive if the departure was contentious. This is precisely why offboarding is treated as a JOINT HR-and-security responsibility in practice, not solely HR''s job — HR typically triggers the process (notifying security of the departure date), while the technical deprovisioning (disabling accounts, revoking access badges, retrieving devices) is a security/IT operations function. Issuing a new password to a departed employee''s account makes no sense — the account should be disabled/removed entirely, not kept active under any credentials.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('78034a3f-5b12-475d-90c6-a77788a6ca9d', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 11, 'A company wants to understand which business functions would cause the most severe operational and financial impact if disrupted, and how long each function could be unavailable before that impact becomes unacceptable, in order to prioritize their disaster recovery investment. What process produces this analysis?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('495b05f0-a7e0-4786-95cf-a2a46eae4dae', '78034a3f-5b12-475d-90c6-a77788a6ca9d', 0, 'A Business Impact Analysis (BIA) — systematically identifies critical business functions, quantifies the impact of their disruption over time, and establishes metrics like RTO (Recovery Time Objective — how quickly a function must be restored) and RPO (Recovery Point Objective — how much data loss, measured in time, is tolerable) that then guide DR/BCP investment priorities.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d98abbad-9fa9-4760-a3a5-1c5ac05dc095', '78034a3f-5b12-475d-90c6-a77788a6ca9d', 1, 'A vulnerability scan, since vulnerability scans are what determine business-function criticality and financial impact.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('73a9d616-8b7f-40c8-aedd-3c59b361a702', '78034a3f-5b12-475d-90c6-a77788a6ca9d', 2, 'A penetration test, since pen tests are designed to calculate financial impact of business function downtime.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('f4bb8721-979b-4496-8ad9-6cbcd1bba952', '78034a3f-5b12-475d-90c6-a77788a6ca9d', 3, 'No formal process exists for this; business priorities are determined arbitrarily.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('78034a3f-5b12-475d-90c6-a77788a6ca9d', '495b05f0-a7e0-4786-95cf-a2a46eae4dae', 'A Business Impact Analysis is the formal, structured process specifically designed to answer exactly this question: which functions matter most, what does disruption actually cost (financially and operationally) over increasing lengths of downtime, and therefore where should limited DR/BCP investment be prioritized. Its outputs directly include RTO (how fast must this function be restored before the impact is unacceptable) and RPO (how much data loss, in time, can be tolerated) for each critical function — these BIA-derived metrics then directly shape the technical DR architecture decisions (e.g., a function with a 1-hour RTO needs a much more aggressive, expensive failover solution than one with a 48-hour RTO). Vulnerability scans and penetration tests both assess technical security weaknesses — neither is designed to quantify business/financial impact of downtime, a fundamentally different (business-continuity-focused, not vulnerability-focused) type of analysis.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('23d05be7-5120-4dae-9dbf-af93cf506873', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 12, 'A security analyst reviewing SIEM alerts flags dozens of alerts every day as false positives, and colleagues have started ignoring alerts from this particular detection rule altogether because "it''s always wrong." What is this phenomenon called, and why is it a genuine security risk on its own?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('aaa0f337-3020-46a3-be43-e9b649f9bbe2', '23d05be7-5120-4dae-9dbf-af93cf506873', 0, 'Alert fatigue — when a high volume of false positives (or low-value alerts generally) causes analysts to become desensitized and start ignoring or dismissing alerts, including the rare genuine threats mixed in among the noise; the risk is a real incident being missed simply because it looked like "just another false alarm."');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('8eecbf4d-e4a8-4b5f-a23f-6d7ba8078e20', '23d05be7-5120-4dae-9dbf-af93cf506873', 1, 'This is called "threat hunting," and it is a purely beneficial practice with no downside.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('68b834db-1c8b-41cf-987b-c7efc3530c9d', '23d05be7-5120-4dae-9dbf-af93cf506873', 2, 'This is called "zero-day exploitation," and it only affects unpatched systems.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('533f5cdf-27d4-4cfc-a455-73acf6839e54', '23d05be7-5120-4dae-9dbf-af93cf506873', 3, 'This has no name in security operations and carries no meaningful operational risk.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('23d05be7-5120-4dae-9dbf-af93cf506873', 'aaa0f337-3020-46a3-be43-e9b649f9bbe2', 'Alert fatigue is a well-documented, genuinely serious security operations risk: when a detection rule (or a SIEM overall) generates too many low-value or false-positive alerts, human analysts predictably become desensitized over time and start dismissing or deprioritizing alerts from that source — the real danger being that a genuine, serious incident can get lost/ignored in that same noisy stream, treated the same as the dozens of false alarms that came before it. This is why SOC teams invest specifically in TUNING detection rules (reducing false-positive rates) and prioritizing/scoring alerts by severity — not just deploying more detection and assuming more alerts is automatically better. Threat hunting is a distinct, proactive activity (searching for undetected threats, covered in Paper 1) — unrelated to alert-volume fatigue. "Zero-day exploitation" refers to attacks using a previously unknown vulnerability, an entirely different concept from alert-handling behavior.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('e800205a-9b7e-4ac4-beb7-7ab39106bed1', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 13, 'A company backs up its critical data daily, but has never actually attempted to restore from a backup to verify the process works. During a real ransomware incident, they discover the backups are corrupted and unusable. What operational practice would have caught this before it became a crisis?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('223e0297-5957-46d7-bca9-305c91c2fd19', 'e800205a-9b7e-4ac4-beb7-7ab39106bed1', 0, 'Regular backup restoration testing — periodically actually restoring from backups (not just confirming the backup JOB completed) to verify the backups are genuinely usable, since a backup that has never been tested for restoration is not a verified, reliable backup at all.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9fba6370-917d-4dde-beb2-6500a9ff9939', 'e800205a-9b7e-4ac4-beb7-7ab39106bed1', 1, 'Increasing the backup frequency from daily to hourly, since frequency alone guarantees backup integrity.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d41c9590-aa25-4621-8b7b-91874cbdc23a', 'e800205a-9b7e-4ac4-beb7-7ab39106bed1', 2, 'Backups never need to be tested, since a completed backup job is always guaranteed to be restorable.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b5d6cff2-9502-4c36-9050-e6692bb1c882', 'e800205a-9b7e-4ac4-beb7-7ab39106bed1', 3, 'Switching antivirus vendors, since antivirus software directly verifies backup restorability.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('e800205a-9b7e-4ac4-beb7-7ab39106bed1', '223e0297-5957-46d7-bca9-305c91c2fd19', 'This scenario is a genuinely common, real-world failure pattern: a backup JOB completing successfully (the scheduled task ran, files were copied) is not the same guarantee as the backup actually being RESTORABLE — corruption, incomplete captures, format/version incompatibilities, or misconfigured retention can all silently produce backups that look fine in a job log but fail when an actual restore is attempted. The only way to genuinely verify backups work is to periodically perform an actual test restoration (ideally to an isolated environment) and confirm the data comes back intact and usable — discovering backups are broken during an active ransomware incident, when there is no time left to fix the underlying problem, is exactly the worst possible moment to find out. Increasing backup FREQUENCY does nothing to address whether the backups being taken more often are actually restorable — it multiplies the same underlying flaw, not fixes it. Antivirus software has no function related to verifying backup restorability.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('51b7d17b-6ec7-4bff-8cab-319b3ac76187', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 14, 'During an active incident, the security team needs to determine the precise sequence of events — what happened first, what happened next — across systems with different, unsynchronized internal clocks. What foundational infrastructure practice, if properly implemented in advance, makes this kind of timeline reconstruction reliable?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b487124d-61e7-4b86-9aa0-3745f40e2d50', '51b7d17b-6ec7-4bff-8cab-319b3ac76187', 0, 'NTP (Network Time Protocol) synchronization across all systems to a common, accurate time source, ensuring every system''s logs use consistent, comparable timestamps — without this, correlating events across multiple systems'' logs during an investigation becomes unreliable or outright impossible.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6ae7f4e1-6f64-426a-882e-771d8e5cbe88', '51b7d17b-6ec7-4bff-8cab-319b3ac76187', 1, 'DNS, since DNS is responsible for synchronizing clocks across systems.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ddf078c9-5478-4d1a-8895-d20712dce2d0', '51b7d17b-6ec7-4bff-8cab-319b3ac76187', 2, 'DHCP, since DHCP''s primary function is time synchronization for log correlation.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('2a919ec7-0389-45ef-a865-f7d9c889bf7f', '51b7d17b-6ec7-4bff-8cab-319b3ac76187', 3, 'Clock synchronization has no bearing on incident investigation or log analysis.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('51b7d17b-6ec7-4bff-8cab-319b3ac76187', 'b487124d-61e7-4b86-9aa0-3745f40e2d50', 'NTP synchronizes every participating system''s clock to a common, accurate time reference — this seemingly small infrastructure detail is foundational to reliable incident investigation: if System A''s clock is 3 minutes fast and System B''s is 2 minutes slow, correlating "which event happened first" across their logs becomes genuinely unreliable or actively misleading during exactly the kind of precise timeline reconstruction an incident investigation requires (e.g., proving initial access preceded lateral movement preceded data exfiltration, in the correct order). This is why NTP configuration is a standard security/operations baseline requirement, not an afterthought. DNS resolves names to IP addresses and DHCP assigns IP addresses — both are foundational network services, but neither has any role in time synchronization, a distinct and unrelated network service (NTP specifically).');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('24b9c335-f6dc-414f-847c-e4cab37c8265', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 15, 'After a confirmed data breach affecting customer personal information, a company must determine which specific laws or regulations require them to notify affected individuals and/or regulators, and within what timeframe. What does this determination primarily depend on?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('9cba3764-8b3e-4cc7-97b1-358a173381d8', '24b9c335-f6dc-414f-847c-e4cab37c8265', 0, 'Breach notification requirements are universally identical worldwide with one single global standard, so jurisdiction and data type are irrelevant to the determination.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('183d4eef-45a9-4214-beb2-ef8ea6cd7251', '24b9c335-f6dc-414f-847c-e4cab37c8265', 1, 'It primarily depends on the applicable jurisdiction(s) (based on where affected individuals reside and where the company operates) and the specific type of data involved (e.g., health data, payment card data, and general PII often carry different, specifically-defined notification obligations and timeframes under different laws).');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('a04abc6c-a359-45aa-9689-8fae9d5248d5', '24b9c335-f6dc-414f-847c-e4cab37c8265', 2, 'Notification is entirely optional and left to the company''s sole discretion in every jurisdiction, with no legal requirement anywhere.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c999eef3-41bb-465d-8593-89243ae8b717', '24b9c335-f6dc-414f-847c-e4cab37c8265', 3, 'Notification requirements depend solely on the size of the company''s IT budget.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('24b9c335-f6dc-414f-847c-e4cab37c8265', '183d4eef-45a9-4214-beb2-ef8ea6cd7251', 'Breach notification obligations genuinely vary by jurisdiction (different countries, and even different US states, have their own specific breach notification laws with different triggers and timeframes) AND by the type of data involved (health data may trigger HIPAA-specific breach notification rules, payment card data may involve PCI-DSS-related obligations to card brands/processors, general PII may trigger state-specific or GDPR-style requirements depending on where the affected individuals reside) — an organization operating across multiple jurisdictions and handling multiple data types genuinely may face several overlapping notification obligations from a single breach, each with its own timeline and required content, which is why this determination requires real legal/compliance analysis specific to the incident, not a single universal answer. This is neither purely discretionary nor determined by IT budget — it is a genuine, often strict legal requirement with real penalties for non-compliance in many jurisdictions.');

-- ── Domain: Security Program Management & Oversight (20% — 4 questions) ──

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('f1e06ddf-24a5-4324-98f3-ce0e34447c1f', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 16, 'A company decides to purchase cyber insurance to cover potential financial losses from a future data breach, rather than investing further in additional preventive security controls for a specific, lower-probability risk. What risk response strategy does purchasing insurance represent?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('6d72dfe4-c6ed-4827-818d-d7e4ee4ca73b', 'f1e06ddf-24a5-4324-98f3-ce0e34447c1f', 0, 'Risk avoidance, since purchasing insurance eliminates the underlying risk entirely.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('71c23a36-1512-4fc1-8d7f-1b587b059c2f', 'f1e06ddf-24a5-4324-98f3-ce0e34447c1f', 1, 'Risk transference — shifting the FINANCIAL impact of a risk to a third party (the insurer) in exchange for a premium, without eliminating the underlying technical risk or vulnerability itself, which still exists and could still result in an actual breach event.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('81af5f14-028b-44bb-bc6f-839687eacc0a', 'f1e06ddf-24a5-4324-98f3-ce0e34447c1f', 2, 'Risk mitigation, since buying insurance directly reduces the technical likelihood of a breach occurring.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c5f0dbcc-1b12-4ab1-8b80-2e0c240cc41a', 'f1e06ddf-24a5-4324-98f3-ce0e34447c1f', 3, 'Risk acceptance, since purchasing insurance means formally taking no action of any kind regarding the risk.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('f1e06ddf-24a5-4324-98f3-ce0e34447c1f', '71c23a36-1512-4fc1-8d7f-1b587b059c2f', 'Cyber insurance is a textbook example of risk transference: the company pays a premium to shift the FINANCIAL consequences of a breach to the insurer, but this does absolutely nothing to reduce the actual likelihood of a breach occurring or the technical vulnerability that could cause one — the underlying risk (in the sense of "could this happen") is unchanged; only who bears the financial fallout if it does happen has shifted. This is a genuinely important distinction from Mitigation (which would mean actually reducing the likelihood/impact via a technical or process control) and from Avoidance (eliminating the risk entirely, e.g., by not collecting the sensitive data in the first place) — insurance does neither of those; it specifically addresses financial exposure after the fact. It is also not Acceptance (doing nothing at all) — purchasing insurance IS an active, deliberate risk response, just one focused on financial consequence rather than technical prevention.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('babb81b6-219d-4fa7-b256-f707fd4627c4', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 17, 'A company undergoes a third-party audit to formally verify their security controls meet a recognized industry standard, resulting in a certification they can show to prospective customers as evidence of their security posture. What is this type of independent verification generally called, and why do customers often require it before signing a contract?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('ee46cdc5-5543-4bc7-aea4-5c7e099c47c2', 'babb81b6-219d-4fa7-b256-f707fd4627c4', 0, 'An internal self-assessment, since only the company''s own internal staff can perform any form of compliance verification, and no external auditor is ever involved.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('40ce7039-8d5b-4e8d-80a2-34d126ebce98', 'babb81b6-219d-4fa7-b256-f707fd4627c4', 1, 'A compliance audit/attestation (e.g., against a framework like SOC 2 or ISO 27001) — performed by an independent third party specifically because customers generally trust an independent, objective assessment far more than a vendor''s own self-reported claims about their security posture, especially when entrusting that vendor with sensitive data.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('62961621-e604-4047-9426-f800d8765a61', 'babb81b6-219d-4fa7-b256-f707fd4627c4', 2, 'A penetration test, since penetration tests are the only recognized form of compliance certification.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('544ce9bb-4433-451b-8639-4948b9a0fc11', 'babb81b6-219d-4fa7-b256-f707fd4627c4', 3, 'This type of verification does not exist; customers never require any form of security evidence before signing contracts.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('babb81b6-219d-4fa7-b256-f707fd4627c4', '40ce7039-8d5b-4e8d-80a2-34d126ebce98', 'Third-party compliance audits (against recognized frameworks like SOC 2, ISO 27001, or others depending on industry) are performed specifically BY AN INDEPENDENT PARTY, not the company being assessed — this independence is the entire point: a vendor simply claiming "we take security seriously" carries far less weight with a prospective customer than an objective, independent audit report verifying specific controls are actually in place and operating effectively. This is exactly why B2B customers, especially in regulated industries or when sensitive data will be shared, frequently require proof of a specific compliance certification/attestation before signing a contract — it substitutes for the customer having to independently audit every vendor themselves. A penetration test is a different, narrower activity (actively testing for exploitable technical vulnerabilities, covered in Paper 1) — it is sometimes a COMPONENT of a broader compliance framework''s requirements, but is not itself the general term for a compliance certification, and is not the "only" recognized form of one.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('f8470633-1485-4c90-be97-57c7d7fc3bb4', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 18, 'A new regulation requires a company to conduct an annual assessment specifically evaluating whether their security controls adequately address their current threat landscape, and to formally document any gaps along with a remediation timeline. What ongoing management practice does this describe?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('1d1d00ad-5ea2-4ccf-a31d-50313a0ca669', 'f8470633-1485-4c90-be97-57c7d7fc3bb4', 0, 'Risk assessment (or a broader risk management/governance program) — a recurring, formal process to identify current risks, evaluate whether existing controls adequately address them, document any identified gaps, and track remediation over time; a ONE-TIME assessment is insufficient since threats and the environment both change continuously.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dbaf13e3-e704-4ad5-8411-7e27ef8a82a4', 'f8470633-1485-4c90-be97-57c7d7fc3bb4', 1, 'This is called incident response, since incident response is performed proactively once per year regardless of whether an incident has occurred.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('521681a8-a628-4e22-965c-58af915a4844', 'f8470633-1485-4c90-be97-57c7d7fc3bb4', 2, 'This is called digital forensics, since forensics is conducted annually as a preventive measure rather than after an incident.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('dba702d5-7184-43f3-a6d0-6f65c129c760', 'f8470633-1485-4c90-be97-57c7d7fc3bb4', 3, 'Formal, recurring risk assessment provides no real value once a company has been assessed a single time.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('f8470633-1485-4c90-be97-57c7d7fc3bb4', '1d1d00ad-5ea2-4ccf-a31d-50313a0ca669', 'Risk assessment, performed as a recurring (often annual, sometimes more frequent depending on regulation/risk tolerance) formal process, is exactly this: systematically identifying current risks against the CURRENT threat landscape and environment, evaluating whether existing controls genuinely address those risks adequately, formally documenting any gaps found, and establishing a remediation timeline with accountability for closing them. It must be recurring, not one-time, specifically because both the threat landscape (new attack techniques, new vulnerabilities) and the organization''s own environment (new systems, new data, new regulations) change continuously — a risk assessment from three years ago says little about current risk. Incident response is reactive, triggered by an actual (or suspected) security incident, not performed annually regardless of incidents — a fundamentally different trigger and purpose. Digital forensics is likewise incident-triggered evidence investigation, not a proactive annual practice.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('eb273cca-098a-44c6-a51f-bca1a41eebdf', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 19, 'A company requires every employee to complete a legal agreement, before they can access any sensitive systems, formally acknowledging acceptable and prohibited uses of company IT resources (e.g., no using company systems for illegal activity, no installing unauthorized software). What is this document called?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('efcad267-141a-46b6-b88f-a332f2732de0', 'eb273cca-098a-44c6-a51f-bca1a41eebdf', 0, 'An Acceptable Use Policy (AUP) — a formal document defining what employees are and are not permitted to do with company IT resources, typically requiring signed acknowledgment before granting system access, serving both as a behavioral guideline and as a legal/HR reference if violations occur.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('3c80b725-e935-481e-82f9-cf20262af0ed', 'eb273cca-098a-44c6-a51f-bca1a41eebdf', 1, 'A Business Impact Analysis, since BIAs are the standard document employees sign to acknowledge acceptable IT use.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('7dcc27ce-f3b4-498a-b567-07b2a3733089', 'eb273cca-098a-44c6-a51f-bca1a41eebdf', 2, 'A Service Level Agreement, since SLAs define acceptable employee behavior regarding company IT systems.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('b7948d9b-bdc4-48fa-879c-a30d523f67b3', 'eb273cca-098a-44c6-a51f-bca1a41eebdf', 3, 'Companies are legally prohibited from requiring employees to sign any IT usage agreement.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('eb273cca-098a-44c6-a51f-bca1a41eebdf', 'efcad267-141a-46b6-b88f-a332f2732de0', 'An Acceptable Use Policy is exactly this standard document: it defines the boundaries of permitted and prohibited behavior regarding company IT resources (systems, network, data, email, internet access), and employees are typically required to read and formally acknowledge/sign it before being granted access to sensitive systems — this serves a dual purpose, setting clear behavioral expectations up front AND providing a documented, legally-relevant reference if an employee''s actions later need to be addressed as a policy violation. A BIA (covered earlier in this paper) analyzes business-function criticality and downtime impact — an entirely different type of document with a different purpose. An SLA defines service performance commitments (typically between a vendor and customer, or between internal teams), not individual employee behavioral expectations. Requiring an AUP acknowledgment before granting access is a completely standard, legally permitted, and widely recommended security practice — not prohibited.');

INSERT INTO questions (id, paper_id, sort_order, question_text)
VALUES ('6a28f158-392a-4ca3-8be8-3076317fc824', 'da3fe4db-b47b-42f6-98dd-d09b7def39c8', 20, 'A security governance team wants ongoing visibility into whether the organization''s security posture is improving or degrading over time, using consistent, quantifiable measurements (e.g., percentage of systems patched within SLA, mean time to detect an incident, percentage of employees completing required training) reported regularly to leadership. What does this practice represent?');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('de4ca0c4-e24c-4197-81de-f3dbf3aee3c2', '6a28f158-392a-4ca3-8be8-3076317fc824', 0, 'Security metrics/KPIs (Key Performance Indicators) as part of ongoing security governance — quantifiable, consistently-tracked measurements reported to leadership, enabling objective trend analysis over time and informed resource-allocation decisions, rather than relying on subjective impressions of security posture.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('d95cb705-3a22-423f-b4d3-246a98c6fdeb', '6a28f158-392a-4ca3-8be8-3076317fc824', 1, 'This is called penetration testing, since pen testing is performed continuously to generate ongoing quantifiable trend metrics.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('846b8d65-2d82-413b-932b-8d8fbfdea158', '6a28f158-392a-4ca3-8be8-3076317fc824', 2, 'This is called digital forensics, since forensics produces the organization''s ongoing security trend metrics.');
INSERT INTO question_options (id, question_id, sort_order, option_text) VALUES ('c88f20b1-0c8f-4f62-b286-c4d728b45cf0', '6a28f158-392a-4ca3-8be8-3076317fc824', 3, 'Tracking security metrics over time provides no actionable governance value.');
INSERT INTO question_answers (question_id, correct_option_id, explanation)
VALUES ('6a28f158-392a-4ca3-8be8-3076317fc824', 'de4ca0c4-e24c-4197-81de-f3dbf3aee3c2', 'Security metrics/KPIs are specifically quantifiable, consistently-defined measurements (like patch compliance percentage, mean time to detect/respond, training completion rate) tracked and reported regularly to leadership/governance bodies — this is what allows an organization to answer "is our security posture actually improving or degrading" with objective evidence over time, rather than relying on anecdote or subjective impression, and it directly informs where security investment/resources should be prioritized going forward. This is a core, ongoing security GOVERNANCE practice (matching this domain''s "Program Management & Oversight" scope), distinct from point-in-time technical activities like penetration testing (an episodic technical assessment, not a continuous metrics-reporting practice) or digital forensics (incident-triggered investigation, also not a continuous governance metric). Tracking these metrics over time is precisely what gives leadership the objective visibility needed for informed governance decisions — the entire practical value of doing it.');
