-- ============================================================
-- UPSC Sociology Optional Paper II — PYQ & Model Answers (2023)
-- PYQ + Model Answer collection (28 questions)
-- ============================================================

-- ---------- Collection ----------
INSERT INTO pyq_collections (id, slug, subject, title, exam_paper, year, is_premium, question_count, sort_order)
VALUES ('9cc25cdd-9c03-432f-893b-47d2bc4a5595', 'upsc-sociology-optional-paper-2-pyq', 'sociology', 'UPSC Sociology Optional Paper II — PYQ & Model Answers (2023)', 'paper-2', 2023, true, 28, 2);

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('ed36451c-bf5d-4867-a992-62ba3becdffe', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 1, 'A', '1(a)', 10, 150, 'Highlight the significant features of A.R. Desai''s ''Dialectical Perspective'' to study Indian Society.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('ed36451c-bf5d-4867-a992-62ba3becdffe', 'A.R. Desai, India''s foremost Marxist sociologist (Social Background of Indian Nationalism, 1948), applied Marxist historical materialism dialectically to the study of Indian society, sharply departing from both colonial-administrative and nationalist-idealist accounts.

Significant features: (i) Historical-materialist foundation -- Desai analysed Indian social structures (caste, village community, agrarian relations) as products of specific material and economic conditions, particularly the transformative impact of British colonial capitalism, rather than as timeless cultural essences. (ii) Critique of the ''idyllic village community'' myth -- he rejected the romanticised nationalist and Orientalist depiction of the pre-colonial Indian village as a self-sufficient, harmonious republic, arguing this obscured real internal exploitation (caste-based, landlord-tenant) and colonial capitalism''s disruptive, often destructive, restructuring of agrarian relations. (iii) Dialectical method -- Desai viewed Indian society as a site of ongoing contradictions (between colonial capital and traditional structures, between classes, between town and country) whose resolution drives social change, rather than a static, harmonious system (a direct challenge to structural-functionalist readings of Indian society). (iv) Class analysis of nationalism -- he analysed the Indian national movement itself through class interests (the differential stakes of the bourgeoisie, peasantry and working class), a materialist reading distinct from purely idealist or Gandhian-moral accounts of the freedom struggle.

Desai''s perspective thus established Marxist political economy as a rigorous, empirically grounded lens for Indian sociology.', 'Desai''s critique of the romanticised ''idyllic village community'' and his class-based reading of Indian nationalism are the two specific, examinable contributions beyond a generic ''Desai used Marxism'' answer. Naming Social Background of Indian Nationalism anchors the answer concretely.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q1a. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/1a/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('aeafa22e-ca07-4b9c-910b-967c5324982a', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 2, 'A', '1(b)', 10, 150, '"The decade of 1950 was the golden period of village studies in Indian Sociology." Explain the statement.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('aeafa22e-ca07-4b9c-910b-967c5324982a', 'The 1950s are considered the ''golden period'' of Indian village studies because this decade saw the first wave of intensive, empirically grounded field-based ethnographic studies of Indian villages by both Indian and Western-trained sociologists/social anthropologists, establishing the village as the foundational unit of Indian sociological inquiry.

Why this decade was pivotal: (i) A cohort of scholars -- M.N. Srinivas, S.C. Dube, McKim Marriott, Oscar Lewis, Andre Beteille (slightly later) -- conducted landmark village monographs (Srinivas''s Rampura/Coorg studies, Dube''s Shamirpet study ''Indian Village'', Marriott''s edited ''Village India'') using first-hand participant observation rather than relying on colonial administrative reports or textual/scriptural sources. (ii) This generated foundational concepts still central to Indian sociology -- Sanskritisation, dominant caste, the little/great tradition distinction (Redfield/Marriott), and jajmani system studies -- all developed FROM this village fieldwork. (iii) Newly independent India''s developmental planning (Community Development Programme) gave village studies practical policy relevance, further encouraging academic and government interest in rigorous village-level data. (iv) It marked Indian sociology''s methodological coming-of-age -- shifting from indological/textual approaches to empirical, fieldwork-based social anthropology comparable to international standards.

This concentrated burst of foundational fieldwork and concept-generation in a single decade is why it is termed the discipline''s ''golden period''.', 'Naming specific 1950s village monographs (Srinivas''s Rampura, Dube''s Shamirpet/''Indian Village'', Marriott''s ''Village India'') and the concepts they generated (Sanskritisation, dominant caste, little/great tradition) is what separates a strong answer from a vague claim about ''many studies happening''.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q1b. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/1b/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('04b71175-fc7a-4459-87d3-bc47999cd65f', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 3, 'A', '1(c)', 10, 150, 'Analyse the difference between the attributional and interactional approach in studying the caste system.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('04b71175-fc7a-4459-87d3-bc47999cd65f', 'These are two classical methodological approaches, distinguished by McKim Marriott and later systematised by Mysore Marriott and Ronald Inden, and further discussed by Andre Beteille, for empirically studying caste hierarchy in Indian villages.

Attributional approach: ranks castes according to fixed, largely a priori cultural/ritual ATTRIBUTES they are believed to possess -- purity/pollution status, dietary practices, occupation, ritual customs -- independent of actual observed behaviour. It treats caste rank as a matter of cultural classification (closely tied to Louis Dumont''s ideology of purity and pollution in Homo Hierarchicus), producing a relatively fixed, textually/normatively derived hierarchy.

Interactional approach: derives caste rank empirically from actually OBSERVED patterns of interaction between castes in a specific local setting -- who accepts food/water from whom, who can enter whose houses, patterns of deference and avoidance in everyday village life. Rank here is inferred inductively from concrete behavioural transactions rather than assumed from abstract cultural attributes, and can therefore vary somewhat from village to village, revealing local, empirically grounded variation that a purely attributional model would miss.

Analysis: the attributional approach is more deductive/textual and cross-locally uniform, while the interactional approach is more empirical/field-based and locally sensitive -- together they represent complementary methodological strategies (categorical classification versus behavioural observation) for the same underlying object, caste hierarchy.', 'Marriott''s methodological distinction must be explicitly named, and Dumont''s purity/pollution ideology is the standard theoretical anchor for the attributional side. A complete answer treats the two as complementary methodological strategies rather than simply opposed.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q1c. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/1c/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('2b4ff3ce-c094-45b7-9675-0583f3e90e16', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 4, 'A', '1(d)', 10, 150, 'Are Tradition and Modernity antithetical to each other? Comment.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('2b4ff3ce-c094-45b7-9675-0583f3e90e16', 'Classical modernisation theory (following a linear evolutionary model, e.g. early Talcott Parsons'' pattern variables) tended to treat tradition and modernity as a strict dichotomy -- tradition (ascriptive status, particularism, diffuse relations, religious/customary authority) opposed to modernity (achievement-based status, universalism, specificity, rational-legal authority) -- implying societies must shed tradition to become modern.

Case against strict antithesis: extensive Indian sociological evidence (Milton Singer''s study of Madras industrialists, Yogendra Singh''s ''Modernization of Indian Tradition'') shows tradition and modernity frequently coexist and even mutually reinforce rather than replace each other -- traditional joint-family capital and kinship networks have financed and organised much of Indian modern industrial entrepreneurship; caste associations have modernised into political-mobilisation vehicles (caste-based political parties) rather than disappearing; religious ritual persists robustly alongside advanced technology use. Singer termed this compatibility ''modernization of tradition'' rather than modernization AGAINST tradition.

Where real tension exists: some traditional practices (rigid caste endogamy, patriarchal inheritance, certain ritual restrictions) do come into direct conflict with modern legal-constitutional values (equality, individual rights), producing genuine friction and contestation, not seamless coexistence.

Conclusion: tradition and modernity are not inherently antithetical -- Indian experience shows selective synthesis and adaptive coexistence is the more common pattern, though specific traditional practices can and do clash with modern values in identifiable instances.', 'Yogendra Singh''s ''Modernization of Indian Tradition'' and Milton Singer''s industrialist study are the specific Indian-context citations examiners expect; a nuanced answer avoids a flat yes/no and instead shows both compatibility (the norm) and specific friction points (the exception).', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q1d. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/1d/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('e5d1813d-1ff7-47f0-b124-2b4793f10397', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 5, 'A', '1(e)', 10, 150, 'Discuss the main features of Land Reforms in post-independence India.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('e5d1813d-1ff7-47f0-b124-2b4793f10397', 'Post-independence Indian land reforms aimed to restructure agrarian relations inherited from the colonial and zamindari era, pursuing both equity and productivity goals through state legislation from the 1950s onward.

Main features/components: (i) Abolition of intermediaries (zamindari abolition acts, from the early 1950s) -- eliminating zamindars, jagirdars and other rent-collecting intermediaries between the state and actual cultivators, aiming to establish direct cultivator-state relations. (ii) Tenancy reforms -- regulating rent, providing security of tenure, and in some states enabling tenants to acquire ownership rights (''land to the tiller'' principle), though implementation varied hugely by state (West Bengal''s Operation Barga being a notably successful case). (iii) Land ceiling legislation -- imposing legal upper limits on individual/family landholding size, with surplus land meant for redistribution to landless and marginal farmers, though widely evaded through benami transfers and fragmented family holdings. (iv) Consolidation of holdings -- merging fragmented, scattered plots into consolidated, more efficiently farmable units. (v) Cooperative farming initiatives -- promoted in some states, with limited overall success.

Outcomes: implementation was highly uneven across states (strongest in West Bengal and Kerala, weakest in much of North India), often diluted by landlord evasion, weak state political will, and administrative capacity gaps -- leaving India''s land reform record widely assessed as a partial, incomplete success.', 'The four core legislative components (zamindari abolition, tenancy reform, land ceilings, consolidation) must all be named; a critical note on uneven state-wise implementation (West Bengal/Kerala success versus weak enforcement elsewhere) is expected for a complete answer.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q1e. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/1e/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('82ec97c2-1840-4105-8f6b-5645d06ad72e', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 6, 'A', '2(a)', 20, 350, 'Do you agree with the view of Andre Beteille that India''s villages are representative of Indian society''s basic civilizational values? Present a sociological overview.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('82ec97c2-1840-4105-8f6b-5645d06ad72e', 'Introduction: Andre Beteille, drawing on his own intensive fieldwork (Sripuram village, Tamil Nadu -- Caste, Class and Power, 1965), argued Indian villages function as microcosms that concretely embody and reproduce the broader civilisational structures and values of Indian society, particularly caste hierarchy, ritual purity-pollution, and the interlocking of caste with class and political power.

Supporting evidence: village studies (Srinivas, Dube, Beteille) consistently found the same core civilisational patterns replicated at village level -- caste-based ritual hierarchy governing commensality and marriage, dominant-caste control over land and local political power, jajmani-style economic interdependence between castes, and shared religious/ritual calendars connecting village practice to pan-Indian ''great tradition'' Hinduism (Redfield-Marriott''s little/great tradition framework). Beteille''s own work showed how caste, class and power, though analytically distinct, substantially overlapped in the village setting, mirroring the broader Indian civilisational pattern of status-hierarchy interlocking with economic and political dominance.

Case for agreement: the village has historically been India''s most numerous and demographically dominant social unit, and its persistence as the primary site of caste practice, kinship organisation and ritual life does make it a genuinely representative -- though not exhaustive -- lens onto core civilisational values (hierarchy, purity/pollution, kinship-based solidarity).

Caveats and limits: critics note the ''village as microcosm'' view risks overgeneralising from specific, often South Indian, fieldwork sites to all of India''s genuinely vast regional, linguistic and social diversity; villages themselves are far from static or uniform, and post-independence changes (land reforms, Panchayati Raj, market integration, migration, urbanisation) have significantly altered village social structure since Beteille''s own 1960s fieldwork, meaning any ''representative'' snapshot risks being historically dated. Urban India, moreover, increasingly houses the demographic and economic majority of Indians, limiting how far the village alone can represent contemporary Indian society.

Conclusion: Beteille''s view holds significant validity as a description of historically rooted civilisational patterns (caste, hierarchy, kinship) still visible in villages, but should be qualified by acknowledging regional diversity, ongoing village transformation, and rising urban demographic weight -- making the village a valuable but partial and evolving, rather than complete and static, representation of Indian civilisational values.', 'A strong answer must both substantiate Beteille''s thesis with concrete village-study evidence AND critically qualify it (regional diversity, post-1960s change, urbanisation) -- an uncritical ''yes, villages represent India'' answer misses the analytical balance a 20-mark question demands.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q2a. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/2a/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('7d98f4f6-d09d-4d09-9570-59fb47635f43', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 7, 'A', '2(b)', 20, 350, 'Elaborate the salient features and the role of middle class in India''s democracy and development.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('7d98f4f6-d09d-4d09-9570-59fb47635f43', 'Introduction: India''s middle class -- a heterogeneous, rapidly expanding stratum defined less by a single income line than by education, salaried/professional occupation, urban residence and aspirational consumption patterns -- has become a central subject of Indian sociological and political analysis since liberalisation (1991).

Salient features: (i) Heterogeneity -- spans government employees, private-sector professionals, small business owners and an increasingly visible new IT/service-sector segment, cutting across caste and regional lines, though historically dominated by upper and intermediate castes. (ii) Education and aspiration-driven identity -- defined more by cultural capital (English education, professional credentials) and consumption aspirations than strict income thresholds. (iii) Post-liberalisation expansion -- economic reforms since 1991 dramatically expanded a new, globally-oriented, consumoption-driven middle class (the ''new middle class'', per Leela Fernandes and Pavan Varma), distinct from the more state-employment-anchored older middle class. (iv) Political assertiveness -- increasingly vocal in urban civic and anti-corruption movements (India Against Corruption, 2011) and in shaping media/public discourse disproportionate to its numerical size.

Role in democracy: the middle class provides much of India''s professional bureaucratic, judicial, media and civil-society leadership, and has been central to anti-corruption and governance-accountability movements, functioning as an influential (if not always representative) democratic voice; however, critics (Partha Chatterjee, Fernandes) note middle-class politics can also be exclusionary -- prioritising urban civic order, consumer interests and anti-poor slum-clearance/beautification agendas over redistributive concerns of the urban and rural poor, producing a democracy weighted toward middle-class priorities.

Role in development: the middle class supplies skilled human capital driving the service and knowledge economy (IT, finance, professional services) that has been central to India''s post-1991 growth story, and its consumption demand has been a significant driver of domestic market expansion; however, its growth has also been criticised for outpacing genuinely inclusive development, with middle-class prosperity coexisting alongside persistent mass poverty and informal-sector precarity.

Conclusion: India''s middle class plays an outsized, genuinely double-edged role -- driving economic dynamism and civic/democratic assertiveness on one hand, while its interests and political voice can crowd out more redistributive, pro-poor development and democratic priorities on the other.', 'Leela Fernandes'' ''new middle class'' concept and Partha Chatterjee''s critique of middle-class politics as exclusionary toward the urban poor are the specific theoretical citations examiners expect; a purely celebratory account of the middle class as a development/democracy driver misses this critical dimension.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q2b. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/2b/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('64746356-a092-4854-8bf0-d61785688144', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 8, 'A', '2(c)', 10, 150, 'Analyse the role of market and modern forces in understanding the changing trends in marriage systems in India.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('64746356-a092-4854-8bf0-d61785688144', 'Market and modernising forces -- education, urbanisation, employment mobility, media and digital technology -- have substantially reshaped Indian marriage practices, though within continuing, adapted traditional frameworks rather than a wholesale replacement.

Key changes: (i) Matrimonial markets have digitised -- online matrimonial platforms and apps have replaced or supplemented traditional kin/community-based matchmaking networks, expanding the pool of potential partners while often still filtering by caste, religion and community (revealing persistence of traditional criteria within a modernised medium). (ii) Rising age at marriage and growing (though still minority) individual choice in partner selection, linked to increased female education and workforce participation, which delays marriage and increases bargaining power within it. (iii) Dowry, though legally banned, has adapted into modern, monetised and consumerist forms (cash, vehicles, urban property) rather than disappearing, showing market forces can intensify rather than erode certain traditional practices. (iv) Rising inter-caste and inter-religious marriages, still statistically small but growing and increasingly visible, enabled by urban anonymity, employment-driven mobility and reduced dependence on natal community approval. (v) Commercialisation of the wedding industry itself (destination weddings, wedding planning services) reflects consumerist market logic reshaping marriage as a status-display event.

Conclusion: market and modern forces have changed the MEANS and visible form of Indian marriage practices substantially, while caste and community endogamy remain resilient underlying norms, illustrating selective rather than total transformation.', 'A nuanced answer shows market forces both eroding some traditional constraints (matchmaking gatekeeping, age at marriage) AND adapting/intensifying others (dowry''s monetisation, caste filtering via matrimonial apps) rather than a simple ''modernisation erodes tradition'' narrative.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q2c. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/2c/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('c1c3839e-5850-4742-8c4c-b559b269229f', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 9, 'A', '3(a)', 20, 350, 'Contextualize Louis Dumont''s concept of ''binary opposition'' with reference to caste system in India.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('c1c3839e-5850-4742-8c4c-b559b269229f', 'Introduction: Louis Dumont''s structuralist analysis of caste (Homo Hierarchicus, 1966) treats the caste system as organised around a fundamental binary opposition between the pure and the impure (purity/pollution), which he argues constitutes the ideological core that structurally orders all other caste distinctions in India.

The binary opposition explained: for Dumont, caste hierarchy is not primarily about power, wealth or occupation (which he treats as secondary, empirical variables) but about a structuralist, ideological opposition between purity and pollution, encompassing and organising the entire system -- Brahmins occupy the position of maximum ritual purity, while castes associated with polluting occupations (handling death, waste, leather) occupy the position of maximum impurity, with all other castes ranked along this single ideological axis. This is a structuralist method directly influenced by Levi-Strauss -- caste as a total ideological system best understood through its underlying binary logic, not through empirical, situational observation of interaction (Dumont explicitly criticised the interactional/attributional ''multiple hierarchies'' approach of American cultural anthropologists like Marriott for missing this deeper structural logic).

Hierarchy encompasses power, for Dumont: he further argued that in traditional Indian ideology, status/ritual purity (hierarchy) structurally ENCOMPASSES temporal power (the King/Kshatriya is ritually subordinate to the Brahmin even while holding political power) -- a distinctively Indian, hierarchical logic he contrasts with modern Western egalitarian ideology where power and equality are the organising values instead.

Criticism and contextualisation: Dumont''s binary-opposition model has been extensively criticised -- by M.N. Srinivas (dominant caste concept shows real power, not just ritual status, structures caste dynamics), by Marxist scholars (for ignoring material/economic exploitation underlying caste), and by scholars of caste politics (for underestimating how democratic politics, reservation policy and caste-based mobilisation have reconfigured caste around power and numbers rather than pure/impure ideology alone). Dalit scholars (following Ambedkar) also argue Dumont''s textual, Brahmanical-idealist framing understates caste as a system of graded, exploitative inequality experienced materially, not merely a neutral structural-ideological order.

Conclusion: Dumont''s binary opposition offers an influential structuralist account of caste''s ideological core, but is best read as one significant, contested lens among several (interactional, materialist, power-based) rather than a complete or uncontested account of how caste actually operates in contemporary India.', 'Dumont''s purity/pollution binary and his ''hierarchy encompasses power'' thesis must both be explained, and a strong answer situates Dumont against his critics (Srinivas''s dominant caste, Marxist materialist critiques, Ambedkarite critiques) rather than presenting his framework uncritically.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q3a. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/3a/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('bf5b3a5b-4c43-4112-8bfe-f6ac24e3e52a', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 10, 'A', '3(b)', 20, 350, 'Define the concepts of ''Descent'' and ''Alliance''. Differentiate between North Indian and South Indian Kinship systems with examples.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('bf5b3a5b-4c43-4112-8bfe-f6ac24e3e52a', 'Introduction: Descent and alliance are the two major classical theoretical frameworks in kinship anthropology, and their differential applicability to North and South India is a foundational finding of Indian kinship studies (Iravati Karve, Louis Dumont).

Descent theory (associated with British structural-functionalists, Radcliffe-Brown, Evans-Pritchard) defines kinship groups primarily through lines of biological descent from a common ancestor -- patrilineal, matrilineal or bilateral -- with descent determining group membership, inheritance and identity, largely independent of marriage patterns.

Alliance theory (Levi-Strauss, Structural Anthropology) instead centres kinship on MARRIAGE as the fundamental organising institution, particularly the exchange of women between groups through prescribed marriage rules (e.g. cross-cousin marriage), viewing kinship groups as bound together through ongoing reciprocal marriage alliances rather than descent lines alone.

North Indian kinship system: predominantly patrilineal descent combined with strict clan exogamy (gotra exogamy) and village exogamy -- marriage is prohibited within one''s own gotra/clan and often one''s natal village, and there is a strong taboo on marrying any recognisable kin, however distant, making North Indian kinship better explained by DESCENT theory (with marriage functioning to create entirely new, non-repeating alliances rather than following prescribed patterns) and reflecting hypergamous tendencies (bride''s family status equal or lower than groom''s).

South Indian kinship system: characterised by cross-cousin marriage and uncle-niece marriage preferences (marriage prescribed WITHIN a defined category of kin, e.g. a man''s mother''s brother''s daughter), clan/lineage exogamy but NOT village exogamy (marriage within the same village or nearby kin network is permitted and even preferred), and a general absence of the strict hypergamy seen in the North. This system is better explained by ALLIANCE theory, since marriage here follows a repeating, prescribed structural pattern of exchange between allied kin groups across generations, rather than the North''s pattern of creating entirely new affinal ties each generation.

Conclusion: Karve''s foundational comparative work established that North and South India represent genuinely distinct kinship ''zones'', mapped respectively onto descent-theory and alliance-theory frameworks -- illustrating how a single sub-continent can exhibit fundamentally different structural kinship logics.', 'Iravati Karve''s North-South kinship zone distinction is the specific, expected Indian anchor; a complete answer must map descent theory onto the North (clan/village exogamy, non-repeating alliances) and alliance theory onto the South (cross-cousin marriage, prescribed repeating exchange) explicitly, not just describe the theories abstractly.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q3b. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/3b/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('fa884285-1425-4c0f-8d7a-12bc5ff7a144', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 11, 'A', '3(c)', 10, 150, 'Critically examine the concept of Sanskritization with suitable illustrations.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('fa884285-1425-4c0f-8d7a-12bc5ff7a144', 'M.N. Srinivas''s concept of Sanskritisation (Religion and Society among the Coorgs of South India, 1952) describes the process by which a lower or middle Hindu caste, or tribal group, seeks upward social mobility by adopting the customs, rituals, ideology and lifestyle of a higher, typically ''twice-born'', caste -- vegetarianism, teetotalism, particular deity worship, Brahmanical ritual practices -- over a generation or two, claiming a higher position in the caste hierarchy.

Illustrations: the Vaishyas'' historical adoption of Kshatriya-like practices, the Coorgs'' adoption of Brahmanical vegetarian and ritual practices Srinivas originally documented, and numerous caste groups across India adopting surname changes, temple-going patterns and dietary restrictions associated with higher castes to claim upward mobility.

Critical examination: Sanskritisation offered a genuinely valuable, empirically grounded alternative to purely textual (Dumont-style) accounts of caste, showing caste hierarchy is not rigidly fixed but subject to real, observable mobility strategies. However, it has been criticised for: (i) being culturally reductive, always taking upper-caste/Brahmanical norms as the singular reference point for ''upward'' mobility, implicitly privileging Brahmanical culture; (ii) achieving only RITUAL status mobility, often without corresponding change in real economic or political power; (iii) being increasingly superseded in explanatory power by democratic and electoral mobilisation (caste-based political assertion, reservation politics) as the dominant contemporary mode of caste mobility, rather than cultural emulation.', 'Srinivas and the Coorgs study must be named; the critical half should include the reference-point critique (Brahmanical culture as the singular aspirational model) and the modern shift toward political/electoral mobility as caste mobility''s contemporary primary channel.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q3c. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/3c/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('ce779794-abe1-4787-b36a-837df18e242c', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 12, 'A', '4(a)', 20, 350, 'Analyse the perspectives of Isolation, Assimilation and Integration in understanding the trajectories of India Tribal Development.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('ce779794-abe1-4787-b36a-837df18e242c', 'Introduction: Indian policy and academic thinking on tribal development has historically oscillated between three broad perspectives -- isolation, assimilation and integration -- each carrying distinct implications for tribal autonomy, culture and development outcomes.

Isolation perspective: associated with the colonial-era ''Excluded/Partially Excluded Areas'' policy and later championed academically by Verrier Elwin in his early writings, this view held that tribal communities should be shielded from mainstream contact and left to develop according to their own indigenous cultural patterns, protecting them from exploitation by outsiders (traders, moneylenders) and cultural disruption. Critics argued this risked freezing tribal communities in a ''human zoo''-like state, denying them access to modern education, healthcare and development benefits, and could itself become a tool of colonial administrative convenience.

Assimilation perspective: the opposite pole, advocating the full absorption of tribal communities into mainstream (Hindu, national) society and culture, treating tribal culture as something to be superseded rather than preserved -- a position associated with some early nationalist reformist thinking (G.S. Ghurye''s characterisation of tribes as ''backward Hindus''). Critics argue this approach disregards and erases tribal cultural identity, autonomy and self-determination, often serving mainstream/dominant-caste interests in absorbing tribal land and resources.

Integration perspective: the middle path, ultimately adopted as India''s constitutional and policy approach (reflected in Nehru''s ''Panchsheel for Tribals'' and Elwin''s later, revised position), which seeks to bring tribal communities into the developmental and economic mainstream (education, healthcare, infrastructure, political representation via Fifth/Sixth Schedule protections and ST reservations) while respecting and preserving tribal cultural autonomy, land rights and self-governance to the extent possible -- development WITH tribal consent and cultural continuity, not development that erases tribal identity.

Assessment of trajectories: independent India''s policy has formally embraced integration (Panchsheel principles, Schedule V/VI protections, PESA Act 1996 extending local self-governance to tribal areas), but critics note actual outcomes often drift toward de facto assimilation (land alienation, displacement by mining/dam projects, weak PESA implementation) or neglect resembling isolation-by-default (poor healthcare/education access in remote tribal regions), showing a persistent gap between the constitutionally endorsed integration ideal and lived tribal development reality.

Conclusion: while integration remains India''s stated normative framework, tribal development trajectories in practice continue to be contested between genuine integration, de facto assimilation pressures from resource extraction and market integration, and persistent isolation-by-neglect in remote regions.', 'Verrier Elwin (isolation, later revised) and Nehru''s Panchsheel for Tribals (integration) are the specific, named theoretical/policy anchors examiners expect; a strong answer notes the gap between the constitutionally endorsed integration ideal and real displacement/neglect outcomes.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q4a. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/4a/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('3f3ee92b-4f4c-43d0-a72b-a536e531549c', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 13, 'A', '4(b)', 20, 350, 'Explain the implication and the impact of globalization in situating the changing agrarian class structure in India.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('3f3ee92b-4f4c-43d0-a72b-a536e531549c', 'Introduction: Economic globalisation -- trade liberalisation, integration into global agricultural markets, corporate agribusiness penetration, and technology/input market changes since 1991 -- has significantly restructured India''s agrarian class relations beyond the older landlord-tenant-labourer framework.

Key impacts: (i) Differentiation among the peasantry has intensified -- globalisation-linked market integration has benefited larger, capital-intensive, export-oriented farmers (contract farming for global agribusiness, cash-crop cultivation) while smallholder and marginal farmers face heightened price volatility, input-cost pressure (globalised seed/fertiliser/pesticide markets) and debt vulnerability, sharpening class differentiation within the peasantry itself (following the Marxist agrarian-question tradition, Utsa Patnaik''s analysis of intensifying rural class polarisation). (ii) Rise of contract farming and corporate agribusiness -- global agri-corporations increasingly shape production decisions through contract arrangements, altering farmers'' autonomy and creating new dependent relationships resembling a rural ''putting-out'' system. (iii) Land-use shifts toward cash crops and export commodities, sometimes at the expense of food-crop security for subsistence-dependent smallholders. (iv) Agrarian distress and out-migration -- price volatility and debt stress linked to global market exposure have contributed to significant distress migration of marginal farmers and landless labourers to urban informal labour markets, changing the agrarian class structure''s composition by shrinking the resident agricultural labour force in some regions. (v) Technology-driven changes (mechanisation, in some cases enabled by global capital/equipment markets) have reduced demand for agricultural labour, affecting the position of landless labourers.

Critical assessment: while some capital-rich farmers have benefited from globalisation''s market access and technology diffusion, the dominant sociological finding (Patnaik, various agrarian-distress studies) is that globalisation has intensified inequality within the agrarian class structure -- widening the gap between capitalised farmers integrated into global value chains and marginal/landless cultivators facing heightened precarity, debt and displacement pressure, a pattern visible in the recurring farmer-distress and farmers''-protest movements of the past two decades.

Conclusion: globalisation has not simply modernised Indian agriculture uniformly, but has restructured agrarian class relations along lines of differential access to capital, markets and technology, generally sharpening rather than reducing class polarisation within the peasantry.', 'Utsa Patnaik''s agrarian-class-polarisation analysis is the specific theoretical citation examiners expect; a complete answer connects globalisation''s impact to the real-world farmers'' distress/protest phenomenon rather than treating the effect only abstractly.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q4b. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/4b/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('92992314-e851-487d-bdc0-c7df8d2dbb71', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 14, 'A', '4(c)', 10, 150, 'Critique the victory narratives of Green Revolution in the context of Indian society.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('92992314-e851-487d-bdc0-c7df8d2dbb71', 'The Green Revolution (from the mid-1960s) is officially celebrated as a triumphant success narrative -- transforming India from food-deficit to food-surplus status through high-yielding variety seeds, chemical fertilisers, irrigation expansion and mechanisation, primarily in Punjab, Haryana and western UP.

Critique of this victory narrative: (i) Regional inequality -- benefits were heavily concentrated in irrigated, resource-rich regions (Punjab, Haryana), while rain-fed and resource-poor regions (much of central and eastern India) saw far weaker gains, widening inter-regional disparity. (ii) Class polarisation -- the new technology package favoured larger farmers with capital to invest in seeds, fertiliser, irrigation and machinery, marginalising small and marginal farmers and increasing rural class differentiation (documented extensively by agrarian sociologists like Utsa Patnaik and Francine Frankel). (iii) Ecological costs -- groundwater depletion, soil degradation from intensive chemical input use, and biodiversity loss from monocropping have produced serious, now widely acknowledged, long-term environmental damage, particularly visible in Punjab''s current water crisis. (iv) Health impacts -- pesticide/fertiliser overuse has been linked to health problems in intensively farmed regions (e.g. Punjab''s documented cancer belt concerns). (v) Continuing agrarian distress -- despite aggregate food self-sufficiency, farmer suicides and agrarian distress have persisted and recurred, showing the Green Revolution did not resolve underlying structural agrarian vulnerability.

The ''victory'' narrative therefore requires substantial qualification: national food security was achieved, but at significant, unevenly distributed social, ecological and health costs.', 'A complete critique must go beyond aggregate food-security success to name the specific regional, class, ecological (groundwater/soil) and health costs -- Punjab''s groundwater depletion and Patnaik/Frankel''s class-polarisation findings are the standard citations expected here.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section A, Q4c. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/4c/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('a8e0e308-2a86-4a8f-b273-db9ab5860868', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 15, 'B', '5(a)', 10, 150, 'Citing some case studies, expand the concept of ''Development-induced Displacement''.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('a8e0e308-2a86-4a8f-b273-db9ab5860868', 'Development-induced displacement (DID) refers to the forced relocation of communities -- typically involuntary and disproportionately affecting the poor, tribal and rural populations -- caused by large-scale development projects such as dams, mines, industrial corridors, and infrastructure/urban expansion projects.

Key features: displaced populations frequently face inadequate compensation, loss of land-based livelihoods without comparable alternatives, cultural and community disruption (especially severe for tribal groups with land-based identity and kinship structures), and prolonged, often unresolved, rehabilitation processes.

Case studies: (i) The Narmada Bachao Andolan (Sardar Sarovar Dam, Narmada Valley) -- one of India''s most studied DID cases, displacing tens of thousands, predominantly tribal and rural households, sparking a sustained social movement over inadequate rehabilitation (led by Medha Patkar). (ii) The Tehri Dam (Uttarakhand) -- large-scale displacement with contested resettlement outcomes. (iii) POSCO and Vedanta/Niyamgiri mining projects in Odisha -- displacement and land-alienation conflicts involving tribal communities (Dongria Kondh), where Supreme Court intervention (the Niyamgiri gram sabha referendum) became a landmark case affirming tribal consent rights under the Forest Rights Act. (iv) Coal-mining displacement in Jharkhand and Chhattisgarh, disproportionately affecting Adivasi populations.

These cases collectively illustrate that DID in India disproportionately burdens tribal and marginalised rural populations, and that rehabilitation and resettlement frameworks (despite the 2013 Land Acquisition Act''s stronger provisions) remain frequently inadequate relative to the scale of displacement caused.', 'At least two concrete named case studies (Narmada/Sardar Sarovar and one mining case like Niyamgiri/POSCO) are required, as the question explicitly asks for case studies. Noting the disproportionate tribal/Adivasi burden is the key analytical point examiners expect.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q5a. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/5a/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('e8082974-ea6f-4aff-a459-a63053d0ffd5', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 16, 'B', '5(b)', 10, 150, 'Examine the concept of ''Cultural Pluralism'' in the context of India''s Unity in Diversity.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('e8082974-ea6f-4aff-a459-a63053d0ffd5', 'Cultural pluralism refers to a social arrangement in which multiple distinct cultural, religious, linguistic and ethnic groups coexist within a shared political/national framework, each retaining its distinctive identity and practices rather than being assimilated into a single homogeneous culture.

Application to India: India''s constitutional and civilisational ethos of ''Unity in Diversity'' represents a deliberate embrace of cultural pluralism rather than either forced assimilation or mere toleration -- reflected in constitutional protections for religious and linguistic minorities (Articles 25-30), linguistic federalism (states organised partly along linguistic lines), and a secular state that does not mandate a single national religion or culture. India''s historical civilisational pattern of absorbing and layering diverse religious traditions (Hindu, Buddhist, Jain, Islamic, Sikh, Christian, tribal) without complete assimilation of any into another exemplifies this pluralism.

Tensions: cultural pluralism in India coexists with periodic communal tension, regional/linguistic assertion (sometimes secessionist), and debates over uniform civil code versus personal-law pluralism, showing pluralism requires continuous political and institutional management rather than being an automatically stable equilibrium.

Significance: cultural pluralism is often presented as India''s civilisational strength and a model of managing diversity democratically, though its stability depends on sustained constitutional secularism, minority protection and inter-community dialogue rather than diversity alone guaranteeing harmony.', 'A strong answer connects the abstract concept explicitly to India''s specific constitutional mechanisms (Articles 25-30, linguistic federalism) and notes that pluralism requires active institutional management, not just acknowledging diversity exists.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q5b. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/5b/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('7a57ec97-3875-4007-aaf2-bc7e7f16dc1a', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 17, 'B', '5(c)', 10, 150, 'Highlight the salient features of the New Education Policy (NEP) 2020.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('7a57ec97-3875-4007-aaf2-bc7e7f16dc1a', 'The National Education Policy (NEP) 2020 replaced India''s 1986 policy framework, proposing wide-ranging structural and pedagogical reforms across school and higher education.

Salient features: (i) Restructured school system -- replacing the 10+2 structure with a 5+3+3+4 framework aligned to cognitive developmental stages (foundational, preparatory, middle, secondary), with stronger emphasis on early childhood care and education (ages 3-6). (ii) Multilingual and mother-tongue emphasis -- promoting instruction in mother tongue/regional language at least through grade 5 where possible, alongside a flexible three-language formula. (iii) Reduced curriculum content in favour of critical thinking, conceptual understanding and experiential/holistic learning over rote memorisation. (iv) Vocational education integration from grade 6 onward, aiming to reduce the academic-vocational divide. (v) Higher education reforms -- multiple entry-exit options with an Academic Bank of Credits, a four-year undergraduate degree with research option, dissolution of rigid discipline silos in favour of multidisciplinary education, and the establishment of a single regulatory body (Higher Education Commission of India) replacing multiple existing regulators. (vi) Target of 6% of GDP public investment in education and universalising access to school education by 2030. (vii) Technology integration (National Educational Technology Forum) for digital learning.

Critics note implementation challenges around resourcing, teacher training, and the practicality of mother-tongue instruction across India''s linguistically diverse and often under-resourced school systems.', 'The 5+3+3+4 structure, multilingual policy, and higher-education credit-bank/multidisciplinary reforms are the specific, checkable facts examiners expect; a brief note on implementation feasibility challenges (resourcing, teacher capacity) adds critical depth.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q5c. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/5c/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('195db7b3-ae3c-472e-9c50-c97cf65029eb', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 18, 'B', '5(d)', 10, 150, 'Analyse the sociological interconnections between Social Media and Mass Mobilization in India.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('195db7b3-ae3c-472e-9c50-c97cf65029eb', 'Social media has become a central infrastructure for mass mobilisation in contemporary India, sociologically significant for how it changes the speed, scale, organisational form and social composition of collective action.

Interconnections: (i) Rapid mobilisation -- platforms (WhatsApp, Twitter/X, Facebook) enable near-instantaneous coordination of protests without dependence on traditional party or union organisational infrastructure, exemplified by the 2011 India Against Corruption movement and the 2019-20 anti-CAA/NRC protests, both substantially organised and amplified through social media. (ii) Cross-regional and diaspora linkage -- social media connects geographically dispersed protest actors (urban and rural, domestic and diaspora), as seen in the 2020-21 farmers'' protests'' extensive digital coordination and global diaspora solidarity/fundraising. (iii) Hashtag-driven agenda-setting -- campaigns (#MeTooIndia, farmer-protest hashtags) shape public discourse and pressure media/political attention independent of traditional gatekeepers. (iv) Double-edged dynamics -- social media also enables state and partisan counter-mobilisation, misinformation, and surveillance of activists, and algorithmically amplified content can both mobilise supporters and entrench polarised, communally charged narratives.

Sociological significance: social media has shifted Indian mass mobilisation toward more decentralised, rapidly assembled, and digitally documented forms of protest, while also making movements more vulnerable to misinformation-driven fragmentation and state digital surveillance than earlier, organisationally denser movements.', 'Concrete Indian examples (anti-CAA/NRC protests, farmers'' protests, India Against Corruption) are essential since the question specifies ''in India''; noting the double-edged nature (mobilisation capacity alongside misinformation/surveillance vulnerability) rounds out the analysis.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q5d. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/5d/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('7573c0ab-37fc-4b5f-8963-d90463763527', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 19, 'B', '5(e)', 10, 150, 'Discuss the nature of regional variations in sex ratio in India. Stating reasons thereof.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('7573c0ab-37fc-4b5f-8963-d90463763527', 'India''s sex ratio (females per 1000 males) exhibits significant regional variation, revealing deep-seated socio-cultural rather than purely biological determinants.

Regional pattern: northern and northwestern states (Haryana, Punjab, parts of Rajasthan and Uttar Pradesh) have historically recorded markedly adverse (low female-to-male) sex ratios and especially skewed child sex ratios, while southern states (Kerala, Tamil Nadu) and several northeastern states have recorded comparatively favourable, sometimes female-majority, sex ratios.

Reasons for the variation: (i) Son preference is culturally stronger in northern patrilineal, patrilocal kinship systems where sons are seen as essential for lineage continuity, old-age support, and property inheritance, combined with dowry-linked perception of daughters as economic burdens -- driving historically higher female infanticide/neglect and, since the 1980s-90s, sex-selective abortion enabled by ultrasound technology (particularly severe in Haryana and Punjab despite their relative economic prosperity, showing prosperity alone does not correct the imbalance). (ii) Southern states'' generally more favourable female sex ratios are linked to historically better female literacy, workforce participation, comparatively lower dowry burden in some communities, and in Kerala''s case, matrilineal inheritance traditions (Nair community) and strong social-development indicators (Kerala model of development). (iii) Legal measures (PCPNDT Act banning sex-selective testing, Beti Bachao Beti Padhao scheme) have had uneven regional impact, given continued enforcement gaps.

This regional pattern demonstrates that sex ratio imbalance is driven primarily by patriarchal kinship structure and son preference, not poverty alone.', 'The counterintuitive point that economically prosperous Haryana/Punjab have the WORST child sex ratios (contradicting a poverty-driven explanation) is the key analytical insight examiners look for, alongside Kerala''s matrilineal/high-female-literacy contrast.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q5e. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/5e/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('c34d8fd0-77ba-4331-b1f5-2aa12a2a802c', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 20, 'B', '6(a)', 20, 350, 'How do you account for the increasing significance of religion in public and personal spheres in the context of secularization thesis in India? Explain.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('c34d8fd0-77ba-4331-b1f5-2aa12a2a802c', 'Introduction: Classical secularisation theory (Weber''s disenchantment, later systematised by Peter Berger and Bryan Wilson) predicted that modernisation -- industrialisation, education, science, rationalisation -- would progressively diminish religion''s social significance in both public institutions and personal life. India''s contemporary trajectory, however, shows religion''s INCREASING rather than declining visibility and significance, requiring explanation.

Evidence of increasing religious significance: growing religiosity in personal life (rising participation in religious tourism, festivals, and ritual observance even among educated, urban, professionally successful Indians); the political mainstreaming of religious-nationalist discourse and religiously inflected political mobilisation; increased visibility of religious identity in public life (religious symbols, personal-law debates, communal politics); and the flourishing of new/reformed religious movements and gurus with large urban, educated followings.

Accounting for this trend, against the classical secularisation thesis: (i) T.N. Madan and Ashis Nandy''s critique of secularisation theory as a Western, ethnocentric model that misreads non-Western societies -- they argue religion in India was never a purely ''private'' matter separable from public/political life the way European secularisation theory assumed, making its ''resurgence'' partly an artefact of a flawed initial theoretical expectation rather than a genuine reversal. (ii) Post-liberalisation identity anxiety -- rapid economic change, urban dislocation and status uncertainty under globalisation have, per several sociologists, driven a search for stable religious/communal identity anchors as a psychological and social response to disorienting modernisation (paralleling global patterns of religious resurgence amid globalisation-linked anxiety). (iii) Political instrumentalisation -- religious identity has been actively mobilised by political actors for electoral consolidation, deliberately increasing religion''s public salience rather than this being a spontaneous cultural process alone. (iv) Modern technology (satellite TV, social media) has actually EXPANDED religion''s reach and visibility (televangelist gurus, viral religious content), showing modernisation''s tools can amplify rather than erode religious significance -- a direct empirical challenge to simple secularisation-equals-modernisation logic. (v) Peter Berger himself later revised his own secularisation thesis, acknowledging global religious resurgence as a major, unanticipated late-20th/21st-century pattern (his ''desecularization of the world'' reassessment).

Conclusion: India''s experience -- alongside Berger''s own revision -- suggests classical secularisation theory''s linear modernisation-erodes-religion model does not hold universally; religion''s persistence and rising public salience in India reflects both a flawed Western-derived initial theory (Madan/Nandy) and genuine contemporary drivers (identity anxiety, political instrumentalisation, media amplification) that actively increase rather than diminish religion''s social significance.', 'T.N. Madan and Ashis Nandy''s critique of secularisation theory as ethnocentric, and Peter Berger''s own later revision (''desecularization of the world''), are the specific theoretical citations that distinguish a strong answer from a purely descriptive account of rising religiosity.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q6a. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/6a/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('82bb83e2-fc24-4dc4-8e61-c81f7363df89', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 21, 'B', '6(b)', 20, 350, 'In the face of rising global climatic concerns, how do you contextualize the relevance of Chipko Movement and its Gandhian tone? Answer analytically.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('82bb83e2-fc24-4dc4-8e61-c81f7363df89', 'Introduction: The Chipko movement (1973 onward, Uttarakhand Himalayas), in which villagers -- prominently women -- physically embraced trees to prevent commercial felling, remains a foundational Indian environmental movement whose Gandhian methodology and underlying philosophy carry renewed relevance amid today''s global climate crisis.

Gandhian tone: Chipko drew directly on Gandhian methods and philosophy -- non-violent civil resistance (satyagraha-style direct action, embracing trees rather than confrontation or property destruction), a critique of extractive, profit-driven industrial development in favour of self-reliant, sustainable local economies (echoing Gandhi''s swadeshi and village-republic ideals), and moral appeal/persuasion rather than purely legal or violent contestation. Leaders like Sunderlal Bahuguna explicitly framed the movement in Gandhian ecological-ethical terms, linking forest conservation to subsistence justice and non-violence toward nature itself.

Sociological significance -- ''environmentalism of the poor'': Chipko is a paradigm case of what Ramachandra Guha and Joan Martinez-Alier call ''environmentalism of the poor'' -- environmental action rooted not in abstract wilderness-preservation values but in immediate subsistence survival (forest-dependent Himalayan villagers'' livelihoods threatened by commercial logging), distinguishing it from Western post-material conservationism. It was also notable for centring women''s agency, since women bore the direct burden of forest-resource collection and ecological degradation''s daily impact.

Contemporary relevance amid climate concerns: Chipko''s core insights anticipate several now-central climate-justice themes -- the recognition that environmental degradation disproportionately harms the poor and marginalised (climate justice framing), that local/indigenous ecological knowledge and community forest stewardship can be more sustainable than centralised commercial extraction, that non-violent grassroots mobilisation remains a viable strategy for environmental advocacy (visible in contemporary global climate movements'' emphasis on civil, non-violent protest), and that development models must weigh ecological limits against short-term commercial gain -- a tension now central to global climate policy debates around growth versus sustainability.

Conclusion: Chipko''s Gandhian, non-violent, subsistence-justice-oriented approach anticipated key elements of contemporary climate-justice thinking, making it not merely a historical episode but an early, still-relevant template for grassroots, ethically grounded environmental action in the climate-crisis era.', 'Naming Sunderlal Bahuguna''s explicit Gandhian framing, and Guha/Martinez-Alier''s ''environmentalism of the poor'' concept, are the specific citations examiners expect; the question demands an explicit connection to CONTEMPORARY global climate concerns, not just a historical description of the 1973 movement.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q6b. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/6b/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('dce10617-5e49-4824-9624-ca4640fb2989', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 22, 'B', '6(c)', 10, 150, 'What actionable measures would you suggest to curb the recurrent child labour menace in India?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('dce10617-5e49-4824-9624-ca4640fb2989', 'Despite constitutional (Article 24) and legal prohibitions (Child Labour Prohibition and Regulation Act, amended 2016), child labour persists in India, particularly in agriculture, home-based industries, domestic work and informal manufacturing, rooted in poverty, weak enforcement and social acceptance in certain sectors.

Actionable measures: (i) Strengthen enforcement -- increase labour inspection capacity, impose stricter penalties on employers, and close loopholes permitting ''family enterprise'' child labour that is frequently exploited to disguise commercial employment. (ii) Address root economic causes -- expand direct income support and employment guarantee schemes (strengthening MGNREGA-style safety nets) for poor households, since child labour is substantially driven by family economic distress. (iii) Universalise access to quality, genuinely free schooling with adequate mid-day meal and scholarship incentives, making schooling a more viable and attractive alternative to child labour -- linking Right to Education Act implementation more effectively to at-risk households. (iv) Supply-chain accountability -- mandate corporate due diligence and certification (e.g. in carpet, garment, and gem-cutting export industries historically linked to child labour) to eliminate child labour from formal and informal supply chains. (v) Community-level awareness and NGO partnership (building on models like the Kailash Satyarthi-founded Bachpan Bachao Andolan) to identify, rescue and rehabilitate child labourers with follow-up education/vocational support, not just removal. (vi) Strengthen birth registration and identity systems to make age verification and enforcement more effective.', 'The answer should combine legal-enforcement measures with the root-cause economic angle (poverty-driven family reliance on child income) -- a purely punitive/legalistic answer without addressing economic drivers is considered incomplete for this kind of applied policy question.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q6c. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/6c/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('afd00ea2-5cd5-4301-9ba4-ddb57097a821', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 23, 'B', '7(a)', 20, 350, 'Do you think that the decades of Dalit political mobilizations and movements have helped in strengthening India''s democracy? Substantiate your arguments with facts.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('afd00ea2-5cd5-4301-9ba4-ddb57097a821', 'Introduction: Dalit political mobilisation -- from the Ambedkarite movement through post-independence electoral and social-movement organising -- represents one of independent India''s most significant instances of a historically excluded group actively claiming democratic citizenship, with substantial (though incomplete) effects on strengthening Indian democracy.

How Dalit mobilisation has strengthened democracy: (i) Constitutional and legal gains -- Ambedkar''s leadership in drafting the Constitution embedded anti-untouchability provisions (Article 17), reservations in education/employment/legislatures (Articles 15(4), 16(4), 330, 332), and later the SC/ST Prevention of Atrocities Act (1989), institutionalising formal democratic protections that would not have existed without sustained Dalit political pressure. (ii) Electoral mobilisation and representation -- the rise of Dalit-led political formations (the Republican Party of India, and most significantly the Bahujan Samaj Party under Kanshi Ram and Mayawati) transformed Dalits from a passive vote bank into an organised, assertive electoral bloc, producing India''s first Dalit-led state government (Uttar Pradesh) and demonstrating democracy''s genuine capacity for historically marginalised groups to capture political power through the ballot. (iii) Deepening substantive democracy -- Dalit movements have pushed democratic practice beyond mere procedural voting rights toward genuine social and dignity-based citizenship, challenging caste-based social exclusion in public institutions, temples, and civic spaces, and building grassroots political consciousness and participation (panchayat-level reservation for SCs under the 73rd Amendment). (iv) Cultural and ideological contribution -- Ambedkarite thought has provided India''s most systematic indigenous critique of social hierarchy and articulation of substantive equality, enriching Indian democratic and constitutional discourse itself.

Limitations and continuing challenges: despite these gains, Dalit political power has not eliminated social discrimination, atrocity incidents (documented in NCRB data) persist, and some argue electoral mobilisation (particularly identity-based coalition politics) has at times prioritised elite Dalit leadership interests over grassroots welfare, and continuing economic marginalisation of large sections of the Dalit population shows political mobilisation alone has not achieved full substantive equality.

Conclusion: Dalit political mobilisation has substantially and measurably strengthened Indian democracy by institutionalising legal protections, achieving real electoral representation and power, and deepening democratic practice beyond formal proceduralism -- even though significant gaps between formal political gains and substantive social/economic equality remain.', 'The BSP''s rise under Kanshi Ram/Mayawati and the specific constitutional provisions (Articles 17, 15(4), 16(4), the 1989 Atrocities Act) are the concrete facts the question''s ''substantiate with facts'' instruction requires; a balanced answer must also note persistent atrocities/inequality as the limiting counterpoint.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q7a. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/7a/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('e6e1a887-5464-48be-a962-c9dd3c6f2eb4', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 24, 'B', '7(b)', 20, 350, 'What is ''reverse migration''? Discuss its features, causes and consequences in India.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('e6e1a887-5464-48be-a962-c9dd3c6f2eb4', 'Introduction: Reverse migration refers to the movement of migrants back from urban/destination areas to their rural or native origin areas, reversing the typically dominant rural-to-urban migration flow -- an issue that gained dramatic national visibility in India during the 2020 COVID-19 lockdown, when millions of informal-sector migrant workers returned to their home states/villages.

Features: (i) It is often sudden, large-scale and crisis-driven (as in the COVID-19 lockdown exodus) rather than a gradual, planned relocation, distinguishing it from routine circular/seasonal migration patterns that had long existed in Indian labour markets. (ii) It disproportionately affects informal-sector migrant workers (construction, manufacturing, domestic work, gig/daily-wage labour) who lack job security, social protection or savings buffers to weather urban economic shocks. (iii) It can also occur in less crisis-driven forms -- return migration after retirement, land/property inheritance obligations, or as failed migration when urban opportunities do not materialise as expected.

Causes: (i) Economic shocks in destination areas -- job/income loss during crises (COVID-19 lockdown being the starkest recent example), economic downturns, or automation-driven job displacement. (ii) Absence of adequate urban social security nets for informal workers, making continued urban residence unsustainable without income. (iii) Poor and precarious urban living conditions (informal settlements, lack of healthcare access) that become unbearable during crises. (iv) Emotional/social pull of family and community ties during periods of uncertainty. (v) In some cases, improving conditions or opportunities in origin regions (rural employment schemes, local economic development).

Consequences: (i) Severe hardship and even fatalities during the pace and manner of the COVID-19 reverse migration, exposing the vulnerability and invisibility of India''s vast informal migrant workforce to policymakers and the public. (ii) Labour shortages in destination urban/industrial areas, disrupting production and construction activity. (iii) Strain on origin-area rural economies and employment schemes (surge in MGNREGA demand) as returning migrants sought local livelihood alternatives. (iv) Renewed policy attention to portable social security, One Nation One Ration Card, and migrant worker registration systems, though implementation gaps persist. (v) For some, permanent resettlement in origin areas, altering long-term rural-urban demographic and labour-market balances in certain regions.

Conclusion: reverse migration during COVID-19 was a stark sociological revelation of the precarity underlying India''s urban informal economy, prompting overdue but still incomplete policy attention to migrant workers'' social security and rights.', 'The 2020 COVID-19 lockdown exodus is the specific, expected empirical anchor for this question; a complete answer covers all three explicitly asked dimensions (features, causes, consequences) and notes concrete policy responses like MGNREGA demand surge and One Nation One Ration Card.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q7b. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/7b/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('e2613aca-a122-4f4e-85b5-35352c651b5d', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 25, 'B', '7(c)', 10, 150, 'Discuss the phenomenon of rural-urban continuum with suitable examples.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('e2613aca-a122-4f4e-85b5-35352c651b5d', 'The rural-urban continuum concept challenges the classical rural-urban dichotomy (associated with Tonnies'' Gemeinschaft/Gesellschaft and Redfield''s folk-urban continuum), arguing that rural and urban are not sharply bounded, opposite categories but exist along a graduated spectrum of intermediate social forms sharing overlapping features.

Explanation: rather than a binary break, real settlements exhibit a continuum -- from purely agrarian villages, through peri-urban/rurban settlements (villages absorbed into expanding metropolitan peripheries, exhibiting mixed agricultural and urban-employment characteristics), to small towns and finally large metropolitan cities. Migration, commuting, media penetration, market integration and non-farm employment diversification blur the traditional rural-urban social and economic boundary.

Indian examples: villages on the outskirts of expanding cities (Delhi NCR''s peri-urban villages, Bengaluru''s urban-fringe villages) show rapid land-use conversion, non-agricultural employment, and lifestyle changes while retaining some rural social structures (caste panchayats, agricultural land ownership); large ''census towns'' (rural areas administratively reclassified as urban due to non-agricultural employment share, per Census criteria) exemplify this continuum concretely; and circular labour migration (workers commuting or cyclically migrating between village and city) sustains ongoing rural-urban social and economic linkage rather than a clean rural-to-urban transition.

Significance: the continuum concept better captures contemporary India''s blurred settlement reality than a rigid rural/urban binary.', 'Naming census towns and peri-urban/''rurban'' settlements as concrete Indian examples is expected, along with the theoretical anchor (Redfield''s folk-urban continuum, or Tonnies'' Gemeinschaft-Gesellschaft as the classical dichotomy being challenged).', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q7c. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/7c/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('fec46364-7a28-42b1-85f5-8a30f39ad5ee', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 26, 'B', '8(a)', 20, 350, 'Explain the thematic linkages between ''Patriarchy'' and ''Honour killing'' in India, citing some recent cases.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('fec46364-7a28-42b1-85f5-8a30f39ad5ee', 'Introduction: Honour killing -- the murder of a family member (overwhelmingly women, and men who partner with them) for perceived transgression of family/community ''honour'' norms, typically involving marriage or relationship choices -- is not an isolated criminal aberration but a direct, extreme manifestation of underlying patriarchal control over female sexuality, choice and family reputation.

Thematic linkages: (i) Control over female autonomy -- patriarchal ideology treats women''s marital and sexual choices as family/community property rather than individual rights; honour killings occur precisely when women exercise autonomous choice (inter-caste, inter-religious, or self-arranged ''love'' marriages) that patriarchal family structures perceive as a loss of control and a threat to family reputation. (ii) Caste and community endogamy enforcement -- patriarchy in India is deeply intertwined with caste hierarchy; honour killings disproportionately occur in cases of inter-caste marriage, especially where a woman from a higher/dominant caste marries a man from a lower caste, since this is seen as doubly transgressive -- violating both gender and caste hierarchy simultaneously. (iii) Khap panchayats and extra-legal community sanctioning -- informal caste/community councils, particularly in parts of Haryana, western UP and Rajasthan, have historically sanctioned or pressured families toward honour killings, reflecting institutionalised patriarchal-caste authority operating alongside, and sometimes in defiance of, the formal legal system. (iv) ''Honour'' as a patriarchal social currency -- family/community status is measured partly through control over women''s conduct, making violence against transgressing women a means of publicly restoring perceived lost honour and reasserting patriarchal authority before the community.

Recent illustrative cases: continuing incidents in Haryana, Uttar Pradesh, Rajasthan and Tamil Nadu of inter-caste couples murdered by family members (several documented and prosecuted under IPC provisions and, following Shakti Vahini v. Union of India, 2018, under Supreme Court directives mandating state action against khap-sanctioned violence and protection for consenting adult couples) illustrate the continuing prevalence of the phenomenon despite legal prohibition.

Policy/legal response: the Supreme Court''s Shakti Vahini judgment directed states to set up special cells and safe houses for threatened couples and treat khap panchawat interference as illegal, though enforcement remains inconsistent given entrenched local social sanction for such violence.

Conclusion: honour killing is best understood not as isolated familial violence but as patriarchy''s most extreme enforcement mechanism, intersecting directly with caste endogamy norms, making it a specifically Indian articulation of gender-based violence rooted in the intersection of patriarchal and caste ideologies.', 'The caste-endogamy dimension (inter-caste marriage as the most common trigger) and khap panchayats'' institutional role are the specific Indian-context facts examiners expect; citing the Shakti Vahini v. Union of India (2018) Supreme Court judgment satisfies the ''recent cases'' requirement with a concrete, checkable reference.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q8a. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/8a/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('950fd8bb-806e-41d3-ae63-a9d0e2bb7356', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 27, 'B', '8(b)', 20, 350, 'Discuss the challenges faced by the cooperative movements in India. Suggest measures to strengthen the movement at the grass-roots level.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('950fd8bb-806e-41d3-ae63-a9d0e2bb7356', 'Introduction: India''s cooperative movement -- spanning credit cooperatives, agricultural marketing cooperatives (notably dairy cooperatives like Amul/Anand pattern), and consumer cooperatives -- has historically been envisioned as a democratic, self-help alternative to both purely state-run and purely private-capitalist economic organisation, but faces persistent structural challenges.

Challenges: (i) Excessive government control and bureaucratisation -- many cooperatives, particularly credit and agricultural marketing cooperatives, have become heavily dependent on and controlled by state government departments and political patronage rather than functioning as genuinely member-driven democratic institutions, undermining the cooperative principle of self-governance. (ii) Political interference and elite capture -- cooperative leadership positions are frequently captured by locally dominant, politically connected elites (often from dominant landholding castes), diverting benefits away from smaller/marginal members and undermining democratic participation. (iii) Financial mismanagement and weak professional capacity -- many cooperative credit institutions suffer from poor loan recovery, financial irregularities and inadequate professional management expertise. (iv) Limited member participation and awareness -- ordinary members, particularly small and marginal farmers, often have low awareness of their rights and limited actual participation in cooperative governance and decision-making. (v) Competition from private and corporate players -- liberalisation has exposed cooperatives (particularly in dairy, sugar and marketing) to more efficient and better-capitalised private-sector competition. (vi) Regional unevenness -- successful models (Amul in Gujarat, Kerala''s cooperative sector) coexist with widespread dysfunction and financial distress in cooperative institutions in many other states.

Measures to strengthen at the grassroots level: (i) Reduce bureaucratic and political control, granting cooperatives genuine functional and financial autonomy consistent with the 97th Constitutional Amendment''s cooperative-autonomy provisions. (ii) Strengthen member education and capacity-building programmes to increase informed grassroots participation in governance and decision-making. (iii) Introduce professional management and financial audit standards while preserving democratic member-control structures (professionalisation without de-democratisation). (iv) Replicate successful federated structures like the Amul three-tier model (village-district-state cooperative federation) in other sectors and regions, adapting its incentive-aligned, farmer-first design. (v) Expand digital technology use for transparent record-keeping, transaction tracking and member communication, reducing opportunities for elite capture and mismanagement. (vi) Strengthen women''s and marginal farmers'' representation within cooperative governance structures to broaden genuine grassroots participation.

Conclusion: cooperative movements retain real potential as a democratic, equity-oriented economic model, but require depoliticisation, professionalisation and genuine grassroots capacity-building to overcome persistent elite capture and bureaucratic control.', 'The Amul/Anand three-tier dairy cooperative model is the standard positive counter-example examiners expect cited alongside the challenges; the 97th Constitutional Amendment (2011, cooperative autonomy) is the specific policy/legal anchor for the ''measures'' half.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q8b. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/8b/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('e4e99806-e472-4189-b65e-49555e4fa4f1', '9cc25cdd-9c03-432f-893b-47d2bc4a5595', 28, 'B', '8(c)', 10, 150, 'What is ''Ageing''? Discuss the major problems of aged people in India.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('e4e99806-e472-4189-b65e-49555e4fa4f1', 'Ageing refers to the progressive biological, psychological and social process of growing older, and at the population level, to the demographic phenomenon of a rising proportion of elderly persons (conventionally 60+ in India) within a society -- a trend accelerating in India due to declining fertility and rising life expectancy.

Major problems faced by aged people in India: (i) Economic insecurity -- the vast majority of India''s elderly, particularly in the informal sector, lack pension coverage or adequate retirement savings, leaving many dependent on family support or continued precarious work. (ii) Health challenges -- rising incidence of chronic and age-related illnesses, combined with inadequate geriatric healthcare infrastructure and high out-of-pocket medical costs. (iii) Weakening of traditional family-based old-age support -- nuclearisation of families, migration of adult children for employment, and changing intergenerational living arrangements have eroded the traditional joint-family safety net elderly Indians historically relied upon, increasingly leaving elderly parents alone or in old-age homes. (iv) Social isolation and loneliness, particularly for widowed or single elderly persons living apart from family. (v) Elder abuse and neglect, including financial exploitation, documented by studies like HelpAge India''s surveys. (vi) Gender dimension -- elderly women face compounded vulnerability through widowhood, lower lifetime asset ownership, and weaker independent economic means compared to elderly men.

Policy responses (Maintenance and Welfare of Parents and Senior Citizens Act, 2007; National Policy on Older Persons) exist but face implementation gaps.', 'The erosion of joint-family-based old-age support due to nuclearisation/migration is the central sociological point examiners expect, connecting this question thematically to the paper''s other kinship/family-change questions; citing the 2007 Maintenance Act shows applied policy awareness.', 'UPSC CSE Mains 2023, Sociology Optional Paper II, Section B, Q8c. Verified against three independent sources that matched in wording, numbering and marks: Sleepy Classes'' topic-wise PYQ compilation (sleepyclasses.com, "Sociology Optional Paper 2 -- PYQs Topic-Wise Segregated till 2023", which tags each question with an explicit (2023/II/8c/marks) code), Synopsis IAS''s per-question solution blog (synopsisias.com, titled with near-verbatim question text, year and marks), and Triumph IAS''s full paper-structure summary (triumphias.com, "Sociology Paper 2 2023 | 24 SEP 2023").');
