-- ============================================================
-- UPSC GS Paper III — PYQ & Model Answers (2026)
-- PYQ + Model Answer collection (20 questions)
-- ============================================================

-- ---------- Collection ----------
INSERT INTO pyq_collections (id, slug, subject, title, exam_paper, year, is_premium, question_count, sort_order)
VALUES ('67e8b893-3d31-4b17-a55c-a0a9269dcf10', 'upsc-gs3-2026-pyq', 'upsc-mains', 'UPSC GS Paper III — PYQ & Model Answers (2026)', 'gs3', 2026, true, 20, 4);

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('7a3a8dd8-2d28-4fe9-b645-4501f92064ac', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 1, NULL, '1', 10, 150, 'What do you mean by Digital Rupee? In this context, explain the working and progress of India''s Central Bank Digital Currency (CBDC).');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('7a3a8dd8-2d28-4fe9-b645-4501f92064ac', 'The Digital Rupee (e₹) is India''s Central Bank Digital Currency -- a digital form of the rupee issued and backed directly by the RBI, distinct from private cryptocurrency because it is sovereign legal tender with the RBI''s balance sheet behind it, and distinct from UPI/digital wallets because it is the currency itself in digital form, not merely a payment rail moving existing bank-deposit money.

It works through two variants: the Wholesale CBDC (e₹-W), used for interbank settlement (first piloted for government securities settlement, reducing settlement risk between banks), and the Retail CBDC (e₹-R), distributed to the public through empanelled banks via a digital wallet, usable for everyday person-to-person and person-to-merchant transactions, including offline transactions in later pilot phases -- a genuine advantage over UPI in low-connectivity areas.

Its progress has been gradual and pilot-based rather than a single nationwide launch: beginning with limited-city retail pilots in 2022-23, expanding merchant and user coverage progressively, and integrating with UPI''s QR infrastructure to ease adoption. Actual transaction volumes remain modest relative to UPI''s massive existing scale, reflecting RBI''s deliberately cautious, phased rollout given the CBDC''s implications for monetary policy transmission and the banking system''s deposit base.', 'Strong answers distinguish CBDC clearly from both private cryptocurrency (no sovereign backing) and UPI (a payment rail, not currency itself), and name the wholesale/retail distinction specifically rather than describing ''digital rupee'' as one undifferentiated concept.', 'UPSC CSE Mains 2026, GS Paper III, Q1 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('b8a657ce-6a62-40b9-ae3c-44771f4fedf3', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 2, NULL, '2', 10, 150, 'Examine the view that financial inclusion is an integral part of social and economic inclusion in a country like India. Also throw light on the usefulness of the R.B.I.''s Financial Inclusion Index.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('b8a657ce-6a62-40b9-ae3c-44771f4fedf3', 'Financial inclusion is integral to broader social and economic inclusion because access to formal banking, credit, and insurance is a precondition for participating in most other economic opportunity -- without a bank account, a person cannot receive Direct Benefit Transfer welfare payments efficiently, cannot build a credit history to access formal loans instead of exploitative informal lending, and cannot accumulate savings safely, meaning financial exclusion compounds and reinforces existing social exclusion (rural, female, and lower-income populations have historically been the most financially excluded).

India''s own experience supports this view directly: the Pradhan Mantri Jan Dhan Yojana''s near-universal bank-account coverage was the essential precondition that made DBT, PM-KISAN, and pandemic-relief cash transfers reach beneficiaries directly, reducing leakage that plagued earlier, less financially-included welfare delivery.

The RBI''s Financial Inclusion Index (FI-Index), a composite measure incorporating access, usage, and quality of financial services across banking, investment, insurance, and pension parameters, is useful precisely because it moves beyond simple ''number of bank accounts opened'' metrics (which can overstate genuine inclusion if accounts remain dormant) to a fuller, more accurate national and state-wise picture of actual financial-service usage -- allowing policy to be targeted at where inclusion is shallow (accounts exist but aren''t actively used) rather than only where accounts don''t yet exist.', 'Strong answers connect financial inclusion concretely to specific Indian welfare-delivery successes (Jan Dhan, DBT) rather than asserting the link abstractly, and explain specifically why a composite index (access + usage + quality) improves on a simpler account-count metric.', 'UPSC CSE Mains 2026, GS Paper III, Q2 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('5fe6f27a-a65c-4429-8c47-d6784e8ca48a', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 3, NULL, '3', 10, 150, 'Describe the various Technology Missions initiated in Indian agriculture and examine their role in food security.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('5fe6f27a-a65c-4429-8c47-d6784e8ca48a', 'India has run several Technology Missions targeting specific agricultural bottlenecks: the National Food Security Mission focuses on increasing production of rice, wheat, pulses, and coarse cereals through improved seed and package-of-practice adoption; the National Horticulture Mission (now under Mission for Integrated Development of Horticulture) targets fruit and vegetable production and post-harvest infrastructure; the National Mission on Sustainable Agriculture promotes climate-resilient farming practices; and the Rashtriya Krishi Vikas Yojana provides states flexible funding for locally-relevant agricultural infrastructure and technology adoption.

Their role in food security operates on multiple fronts. Production-focused missions have directly contributed to India''s shift from a food-deficit to a food-surplus and even food-exporting position for several major crops since the Green Revolution era, with these targeted missions sustaining and extending that gain into specific crop categories (pulses, oilseeds) where self-sufficiency lagged behind cereals. Post-harvest and horticulture-focused missions address a different, often underemphasized dimension of food security -- reducing the substantial post-harvest losses that occur between farm and consumer, meaning food security depends not only on how much is grown but on how much of it is actually preserved and reaches the market or plate.

Their limitation is uneven implementation across states, with technology adoption and mission-fund utilization varying substantially by state administrative capacity.', 'Strong answers name specific, real missions (National Food Security Mission, RKVY, horticulture mission) rather than describing ''agricultural technology schemes'' generically, and explicitly connect production-side and post-harvest-side missions to food security''s two distinct dimensions -- growing enough, and not losing what''s grown.', 'UPSC CSE Mains 2026, GS Paper III, Q3 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('d7543257-c822-45ca-8113-a93b340535e0', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 4, NULL, '4', 10, 150, 'Explain the factors responsible for inefficiency of agri-produce marketing. How e-commerce helps to reduce inefficiency of agri-produce marketing?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('d7543257-c822-45ca-8113-a93b340535e0', 'Indian agri-produce marketing has historically suffered from several structural inefficiencies: a long, fragmented intermediary chain between farmer and consumer (multiple layers of commission agents and middlemen, each taking a margin) that depresses farmer realization while raising consumer prices; mandatory routing of produce through regulated APMC mandis in many states, historically limiting farmers'' ability to sell directly to buyers of their choice or across state lines; inadequate cold-chain and storage infrastructure causing substantial post-harvest spoilage, particularly for perishables; and poor price-discovery information reaching farmers before they decide where and when to sell, leaving them dependent on local mandi-agent information asymmetry.

E-commerce platforms address several of these directly: the electronic National Agriculture Market (e-NAM) links mandis across states into a unified electronic trading platform, widening the buyer pool available to any given farmer and improving price discovery beyond the local mandi alone. Direct farmer-to-consumer and farmer-to-retailer e-commerce models shorten the intermediary chain by connecting farmers directly with bulk buyers or end consumers digitally. Mobile-based price-information services give farmers real-time price data across multiple markets before they commit to a sale, directly correcting the information-asymmetry problem that previously left farmers dependent on local intermediaries'' information alone.', 'This is a two-part question -- answers must genuinely address both the factors (structural, not just ''poor infrastructure'' vaguely) and the specific e-commerce mechanism that addresses each, rather than describing agricultural problems and e-commerce benefits as two separate, unconnected lists.', 'UPSC CSE Mains 2026, GS Paper III, Q4 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('ffe35fac-eca8-4f46-99b1-647919256aa0', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 5, NULL, '5', 10, 150, 'Explain by giving two examples, how biotechnology has helped the Indian farmers in processing their perishable crops.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('ffe35fac-eca8-4f46-99b1-647919256aa0', 'Biotechnology has helped Indian farmers manage perishable-crop losses through applications extending shelf life and preserving quality, addressing the substantial post-harvest wastage that perishable crops (fruits, vegetables, flowers) are especially vulnerable to given India''s still-developing cold-chain infrastructure.

First example -- delayed-ripening and shelf-life-extending biotechnology: genetically improved or biotechnology-assisted varieties of tomatoes and certain fruits have been developed with delayed ripening characteristics, giving farmers a longer window to transport and sell produce before spoilage, directly reducing the substantial pre-market losses perishable crops face on India''s often lengthy farm-to-market routes.

Second example -- biotechnology-based processing and value-addition techniques: enzymatic and fermentation-based processing methods (used in fruit-pulp preservation, biotechnology-assisted drying and dehydration techniques) allow farmers and small processors to convert highly perishable raw produce into shelf-stable processed products (pulps, concentrates, dried products) closer to the farm, capturing value that would otherwise be lost to spoilage before reaching a distant processing facility.

Together, these applications shift the point at which perishability becomes a loss risk -- either by extending the raw produce''s own viable window, or by converting it into a non-perishable form earlier in the supply chain -- both reducing the substantial farm-to-market wastage perishable crops are otherwise prone to.', 'The question specifically asks for two examples -- an answer giving only a general description of ''biotechnology helps agriculture'' without two distinct, named applications does not fully answer what is asked. Both examples should be genuinely about PERISHABLE crop processing specifically, not biotechnology in agriculture generally.', 'UPSC CSE Mains 2026, GS Paper III, Q5 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('ee08463d-53b2-45b8-b3b5-a2471bae7d70', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 6, NULL, '6', 10, 150, 'Distinguish between a Fast Breeder Reactor (FBR) and a thermal nuclear reactor. In the context of first indigenously developed prototype FBR at Kalpakkam, explain the term ''criticality''.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('ee08463d-53b2-45b8-b3b5-a2471bae7d70', 'A thermal nuclear reactor (India''s currently dominant reactor type, mostly Pressurized Heavy Water Reactors) uses slow (thermal) neutrons, moderated by a substance like heavy water, to sustain fission primarily in Uranium-235 -- the readily fissile isotope that makes up a small fraction of natural uranium. A Fast Breeder Reactor uses fast (unmoderated, high-energy) neutrons and, critically, is designed to ''breed'' more fissile fuel than it consumes -- it converts non-fissile Uranium-238 (the abundant uranium isotope thermal reactors cannot efficiently use) into fissile Plutonium-239 during operation, extracting vastly more energy from a given quantity of natural uranium and directly supporting the second stage of India''s three-stage nuclear power programme.

The Prototype Fast Breeder Reactor at Kalpakkam is India''s first indigenously developed FBR, using a plutonium-uranium mixed-oxide fuel core.

''Criticality'' refers to the state at which a nuclear reactor''s fission chain reaction becomes exactly self-sustaining -- each fission event triggers, on average, precisely one further fission event, producing a stable, controlled reaction rate rather than one that dies out (sub-critical) or escalates uncontrollably (super-critical). A reactor ''achieving criticality'' or ''going critical'' -- the milestone Kalpakkam''s PFBR has been working toward -- marks the point at which it begins sustained, self-supporting nuclear fission for the first time, the essential precondition before it can be ramped up to generate power.', 'Strong answers name the specific fuel-cycle mechanism (fast neutrons converting U-238 to Pu-239) that distinguishes a breeder reactor''s actual function, not just that it ''uses fast neutrons,'' and define criticality precisely as the self-sustaining chain-reaction threshold rather than vaguely as ''when the reactor starts working.''', 'UPSC CSE Mains 2026, GS Paper III, Q6 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('83e6ca75-4bce-4bdd-8343-68942dd10237', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 7, NULL, '7', 10, 150, 'Discuss how the contradiction between ''rapid infrastructure development'' and ''disaster-risk reduction'' in ecologically-sensitive areas of India can be managed, with suitable examples.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('83e6ca75-4bce-4bdd-8343-68942dd10237', 'Infrastructure development in ecologically sensitive zones -- Himalayan road-widening and hydropower projects, coastal construction, hill-station tourism infrastructure -- often directly increases disaster risk in the same areas it is meant to develop, since it disturbs slope stability, natural drainage, and forest cover that previously buffered against landslides, flash floods, and erosion. The Char Dham road-widening project''s link to increased Himalayan landslide incidence, and the Joshimath land-subsidence crisis (linked partly to unplanned construction and hydropower-tunnel activity in a geologically fragile zone), are real, documented instances of this exact contradiction playing out.

Managing this contradiction requires embedding disaster-risk assessment into project design itself, not treating it as a post-facto compliance checkbox: mandatory, genuinely rigorous Environmental and geological Impact Assessments before project approval (rather than assessments completed after design decisions are largely fixed); carrying-capacity studies for ecologically fragile regions determining how much construction and tourist/vehicular load an area can sustainably absorb; adopting eco-sensitive construction techniques (tunnel-boring methods that minimize slope disturbance, rather than open-cut methods, in Himalayan road projects); and strengthening early-warning and geological-monitoring systems specifically in zones where development is proceeding, so risk is actively monitored rather than assumed away.

The underlying management principle is that development and disaster-risk reduction need not be genuinely opposed goals if risk assessment is integrated into project design from the outset rather than bolted on afterward.', '''With suitable examples'' requires real, specific, named cases -- Joshimath and Char Dham are the clear, current, well-documented examples for this exact question and their absence weakens an otherwise sound answer. The management suggestions should be specific and technical (carrying-capacity studies, tunnel-boring methods) rather than a generic call for ''sustainable development.''', 'UPSC CSE Mains 2026, GS Paper III, Q7 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('2c815793-996b-4135-b55e-449ac18141e4', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 8, NULL, '8', 10, 150, 'Discuss the aim and goals of Kunming-Montreal global biodiversity framework. Mention India''s commitments and initiatives to achieve the goals.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('2c815793-996b-4135-b55e-449ac18141e4', 'The Kunming-Montreal Global Biodiversity Framework (GBF), adopted at COP15 in December 2022, sets the global biodiversity agenda for this decade, replacing the earlier Aichi Targets. Its central aim is halting and reversing biodiversity loss, structured around several headline goals: the widely-cited ''30x30'' target (conserving at least 30% of the world''s land and marine areas by 2030), restoring at least 30% of degraded ecosystems, reducing harmful subsidies that damage biodiversity, and mobilizing substantially increased biodiversity finance, particularly for developing countries.

India''s commitments align with the GBF through its National Biodiversity Strategy and Action Plan (NBSAP), updated to reflect the GBF''s targets, alongside India''s existing Protected Area network (national parks, wildlife sanctuaries, biosphere reserves) which the country is expanding and strengthening toward the 30% conservation target. India''s specific species-recovery initiatives -- Project Tiger and Project Elephant''s continued expansion, and the newer Project Cheetah reintroduction effort -- demonstrate concrete species-level action consistent with the GBF''s broader ecosystem-restoration goals. India has also emphasized, in international GBF negotiations, the framework''s finance and technology-transfer provisions specifically, given that developing countries bear a disproportionate share of global biodiversity but require international financial support to meet ambitious conservation targets without compromising development needs.', 'Strong answers name the GBF''s specific headline targets (30x30, ecosystem restoration percentage, finance mobilization) rather than describing it as a vague ''global conservation agreement,'' and connect India''s specific real initiatives (NBSAP update, Project Tiger/Cheetah) to specific GBF goals rather than listing Indian conservation programmes disconnected from the framework''s actual targets.', 'UPSC CSE Mains 2026, GS Paper III, Q8 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('505db634-a629-4276-ab43-0ef10ef2b1b3', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 9, NULL, '9', 10, 150, 'Explain how fake news and disinformation pose threat to Internal Security and Public Order in Indian context?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('505db634-a629-4276-ab43-0ef10ef2b1b3', 'Fake news and disinformation threaten internal security and public order in India through several distinct, documented mechanisms. Communal and identity-based disinformation -- fabricated or decontextualized images/videos falsely attributed to a specific community or incident -- has repeatedly triggered real communal violence and mob action, since panic and outrage spread faster through social media than fact-checking can follow, making the harm materialize before correction is even possible.

Cross-border and state-sponsored disinformation, increasingly amplified through coordinated social-media networks and AI-generated deepfakes, is used to inflame communal tension, undermine confidence in security-force operations (particularly in insurgency-affected regions like J&K and parts of the Northeast), and spread panic during actual security incidents, complicating genuine crisis response by flooding the information environment with false reports.

Disinformation around elections and public institutions erodes trust in democratic processes themselves, a slower-burning but genuinely serious internal-security-adjacent threat distinct from the more immediate mob-violence risk. Financial disinformation and scam networks, while less directly about public order, drain resources from vulnerable populations at scale, compounding social distress in already-vulnerable communities.

The common thread across all these mechanisms is that disinformation converts an information-space vulnerability into a physical or institutional security consequence, which is precisely why it is treated as an internal-security concern, not merely a media-literacy or platform-regulation issue.', 'Strong answers distinguish multiple distinct mechanisms (communal-violence triggering, cross-border/state-sponsored amplification, election/institutional-trust erosion) rather than treating ''fake news is bad for security'' as one undifferentiated claim, and explicitly explain WHY disinformation converts into physical security consequences (speed of spread outpacing correction) rather than just asserting that it does.', 'UPSC CSE Mains 2026, GS Paper III, Q9 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('3d66183e-54d9-4958-80c1-f33943b893b7', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 10, NULL, '10', 10, 150, 'Ladakh is strategically located between China and Pakistan. As a measure to win hearts and minds of locals, discuss the Border Area Development Programmes (BADP).');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('3d66183e-54d9-4958-80c1-f33943b893b7', 'Ladakh''s location, bordering both China (along the Line of Actual Control) and sharing proximity to Pakistan-administered territory, makes it one of India''s most strategically sensitive border regions -- and local population goodwill in such a region carries genuine security value, since a population that feels neglected or alienated from the Indian state is more vulnerable to external influence and less likely to cooperate with security forces on ground-level intelligence and support.

The Border Area Development Programme addresses this through targeted infrastructure and welfare investment specifically in border districts -- rural connectivity (roads bridging remote border villages to the wider network), basic services (health, education, drinking water, electrification) in areas that would otherwise lag behind due to sheer remoteness and difficult terrain, and livelihood support (tourism infrastructure, local employment schemes) tailored to the specific border-region context rather than generic rural development funding.

In Ladakh specifically, BADP-funded projects address the genuine remoteness-driven development gap the region''s harsh terrain and long winter isolation produce, while the programme''s underlying ''hearts and minds'' logic is that visible, tangible state investment in daily quality of life builds local trust and stake in the Indian state''s presence, a genuinely important complement to the region''s more visible military and security-infrastructure investment, since security presence alone does not by itself build local goodwill.', 'Strong answers connect BADP''s specific, concrete interventions (rural connectivity, health/education infrastructure, livelihood support) to the strategic ''hearts and minds'' logic explicitly -- explaining WHY local development investment has security value, not just describing BADP as a generic development scheme.', 'UPSC CSE Mains 2026, GS Paper III, Q10 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('6097c4ef-181c-4d94-8cbb-dbc50c380589', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 11, NULL, '11', 15, 250, 'Explain the key challenges for India''s energy security. What measures do you suggest for ensuring energy security along with economic growth and sustainability?');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('6097c4ef-181c-4d94-8cbb-dbc50c380589', 'India''s energy security faces several structural challenges. Import dependence is the most significant -- India imports a substantial majority of its crude oil and a significant share of its natural gas requirements, exposing the economy to global price volatility and geopolitical supply-chain risk beyond domestic control. Coal, while domestically abundant and still the dominant power-generation fuel, carries a heavy environmental and climate cost that increasingly conflicts with India''s own decarbonization commitments. Renewable energy''s rapid capacity growth (solar and wind) faces its own distinct challenges -- grid integration difficulty given renewables'' intermittency, inadequate battery-storage capacity at scale, and transmission-infrastructure bottlenecks connecting renewable-rich regions (Rajasthan, Gujarat, Tamil Nadu) to demand centres elsewhere. Critical-mineral dependence for battery and solar-panel manufacturing (lithium, cobalt, rare earths) is an emerging vulnerability, since India currently imports most of these inputs, largely from a concentrated set of supplier countries.

Measures to address these simultaneously with growth and sustainability goals: accelerating renewable capacity addition alongside matching investment in battery storage and transmission infrastructure, so intermittency does not become a growth-limiting bottleneck; diversifying oil and gas import sources and building strategic petroleum reserves to cushion price-shock exposure; developing domestic critical-mineral processing capacity (and securing overseas mineral assets, as India has begun doing) to reduce battery/solar supply-chain vulnerability; and continuing nuclear capacity expansion (including the Fast Breeder Reactor programme) as a genuinely low-carbon, dispatchable baseload option that complements variable renewable generation.

The throughline across these measures is treating energy security, growth, and sustainability as jointly achievable through diversification and storage investment, rather than a forced tradeoff between reliable power and clean power.', 'Strong answers name the specific, distinct challenges (import dependence, renewable intermittency/grid integration, critical-mineral dependence) with real specificity rather than a generic ''India needs more energy'' framing, and the suggested measures should map directly onto the challenges named, showing the answer''s two halves are genuinely connected.', 'UPSC CSE Mains 2026, GS Paper III, Q11 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('ca83dce8-3900-40c6-9e44-aaa467562577', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 12, NULL, '12', 15, 250, 'How are startups in India promoting entrepreneurship, innovation and employment? Discuss the global and domestic challenges in their working.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('ca83dce8-3900-40c6-9e44-aaa467562577', 'India''s startup ecosystem, substantially catalyzed by the Startup India initiative (2016) and a maturing venture-capital environment, has meaningfully expanded entrepreneurship by lowering barriers to founding a company -- simplified registration, tax benefits for recognized startups, and a growing angel/VC funding base have let founders outside traditional business-family backgrounds access capital that was previously far harder to reach.

On innovation, Indian startups have produced genuine product and business-model innovation adapted specifically to Indian market conditions -- fintech solutions built around UPI''s rails, agritech platforms addressing India-specific farm-to-market inefficiencies, and healthtech solutions designed for lower-resource healthcare settings -- representing innovation directed at real domestic problems, not merely imported models.

On employment, the sector has created substantial direct employment within startups themselves and, more significantly, has generated large-scale gig and platform-based employment (delivery, ride-hailing, home-services platforms) that, while raising its own job-quality and social-security questions, has genuinely expanded income-earning opportunity at scale, particularly for workers without traditional formal-sector entry points.

Domestic challenges include an uneven funding environment heavily concentrated in a handful of metro hubs, regulatory and compliance complexity that still burdens smaller startups disproportionately relative to established firms, and a limited domestic risk-capital base historically dependent on foreign venture capital. Global challenges include the well-documented 2022-23 global funding-winter''s chilling effect on valuations and follow-on funding availability, and increasing global competition for the same technology talent and capital that Indian startups also compete for.

The sector''s continued growth therefore depends on deepening domestic risk capital, extending startup infrastructure beyond metro clusters, and building genuine resilience to the funding cycles global capital markets impose on a still-foreign-capital-dependent ecosystem.', 'This question has two explicit halves (promoting E/I/E, and global+domestic challenges) that both need genuine, distinct treatment -- an answer heavy on startup success stories with only a brief challenges paragraph is incomplete relative to what is asked.', 'UPSC CSE Mains 2026, GS Paper III, Q12 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('716b42bc-b238-4f24-9f7f-903431872a8e', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 13, NULL, '13', 15, 250, 'How Indian agriculture has been transformed from food scarcity to food surplus level? Explain the various government policies implemented for diversification.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('716b42bc-b238-4f24-9f7f-903431872a8e', 'India''s transformation from a food-scarce, import-dependent nation in the 1960s to a food-surplus, net-exporting agricultural economy today is substantially attributable to the Green Revolution''s introduction of high-yielding seed varieties, expanded irrigation, and chemical-fertilizer use, concentrated initially in Punjab, Haryana, and western UP, which dramatically raised wheat and rice yields and ended the chronic food-grain deficits and import dependence (including the politically fraught PL-480 wheat imports) of the pre-Green-Revolution era.

Sustaining and extending this surplus required continued policy support: assured Minimum Support Prices for major crops gave farmers price certainty that encouraged continued production even as surplus accumulated; the Food Corporation of India''s procurement and buffer-stock system ensured surplus production translated into stored, distributable national food security rather than local market gluts; and continued agricultural research (ICAR''s variety-development work) extended yield gains beyond the initial Green Revolution crops.

Diversification policy has more recently targeted the Green Revolution''s own narrow-crop-focus limitation -- rice-wheat monoculture in the original Green Revolution belt has produced serious groundwater depletion and soil-health degradation. The National Food Security Mission''s expanded pulses and oilseed focus, the National Mission on Sustainable Agriculture''s crop-diversification and climate-resilience emphasis, and market-based interventions like the price-deficiency payment scheme for pulses/oilseeds (PM-AASHA) aim to shift farmer incentives away from water-intensive cereal monoculture toward more diversified, sustainable cropping patterns.

The overall trajectory, then, is a genuine two-phase story: Green Revolution intensification solved the original scarcity problem, and current diversification policy is addressing the environmental and nutritional limitations that same intensification approach created as an unintended consequence.', 'Strong answers structure the answer as the two distinct phases the question implies -- the historical scarcity-to-surplus transformation (Green Revolution, MSP, FCI procurement) and the CURRENT diversification policy response to that transformation''s own downsides (water depletion, monoculture) -- rather than treating both as one undifferentiated policy history.', 'UPSC CSE Mains 2026, GS Paper III, Q13 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('f2ab9b74-3698-4d98-b5bc-50adff871d34', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 14, NULL, '14', 15, 250, 'Discuss the different types of subsidies and supports provided by the Government of India to agricultural sector. Examine the related issues pertaining to Agreement on Agriculture of WTO.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('f2ab9b74-3698-4d98-b5bc-50adff871d34', 'India provides agricultural support across several categories. Input subsidies reduce farmers'' cost of key inputs -- fertilizer subsidy (keeping urea and other fertilizer prices below actual production/import cost), power subsidy for agricultural electricity (often free or heavily discounted in several states), and irrigation-water subsidy. Price support operates through Minimum Support Prices for major crops, backed by Food Corporation of India procurement, guaranteeing farmers a floor price regardless of market fluctuation. Credit support includes subsidized institutional agricultural credit (Kisan Credit Card) and interest subvention schemes reducing farmers'' effective borrowing cost. Direct income support, most prominently PM-KISAN, provides cash transfers directly to farmer households independent of production or input use. Insurance support through Pradhan Mantri Fasal Bima Yojana subsidizes crop-insurance premiums, sharing weather and yield risk with farmers.

The WTO''s Agreement on Agriculture classifies domestic support into categories with different treatment -- Amber Box support (trade-distorting, subject to reduction commitments and calculated against a fixed, decades-old external reference price) is where India''s MSP-based procurement faces recurring international scrutiny, since MSP for rice in particular is calculated well above the WTO''s outdated 1986-88 reference price, technically breaching India''s committed Aggregate Measurement of Support ceiling on paper.

India has consistently argued this reference-price methodology is unfair to developing countries given decades of inflation since it was fixed, and has secured a temporary ''Peace Clause'' protection shielding its public food-stockholding programmes from formal WTO dispute action while a permanent solution is negotiated. This remains an unresolved, actively contested issue in ongoing WTO agricultural negotiations, with India insisting food-security-motivated public stockholding be treated differently from purely trade-distorting export subsidies.', 'Strong answers name distinct subsidy CATEGORIES (input, price, credit, income, insurance) with a real named scheme for each, rather than listing schemes without categorizing them, and the WTO discussion should specifically explain the Amber Box/reference-price mechanics and the Peace Clause, not just assert that ''India''s subsidies face WTO scrutiny'' without explaining why.', 'UPSC CSE Mains 2026, GS Paper III, Q14 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('5ec3c958-0fac-4d40-837e-6923521e6c20', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 15, NULL, '15', 15, 250, 'Mention salient features of ''Mission Drishti''. Discuss the imaging techniques used in the satellite launched on 3rd May 2026.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('5ec3c958-0fac-4d40-837e-6923521e6c20', 'Mission Drishti is an ISRO earth-observation initiative focused on high-resolution imaging capability for domestic applications spanning security surveillance, disaster monitoring, and resource mapping -- its salient features include enhanced-resolution imaging capacity compared to earlier generations of Indian earth-observation satellites, a design emphasis on rapid-revisit capability (imaging the same location more frequently) to support time-sensitive applications like border surveillance and disaster response, and integration with India''s broader satellite-constellation strategy for continuous, layered earth-observation coverage rather than relying on any single satellite.

The satellite launched on 3rd May 2026 under this mission uses a combination of imaging techniques suited to its dual civilian-and-security mission profile. Optical (electro-optical) imaging captures high-resolution visible-spectrum imagery for detailed terrain, infrastructure, and land-use mapping, but is limited by cloud cover and darkness. To address this limitation, the satellite also carries Synthetic Aperture Radar (SAR) imaging capability, which actively transmits and receives its own radar signal rather than relying on reflected sunlight -- allowing all-weather, day-and-night imaging that optical sensors cannot achieve, a particularly valuable capability for border and disaster-monitoring applications where waiting for clear daytime conditions is often operationally unacceptable.

The combination of high-resolution optical and all-weather SAR imaging on the same platform reflects a deliberate design choice to cover each technique''s individual limitation with the other''s strength, producing a more operationally reliable and continuous surveillance and monitoring capability than either sensor type could provide alone.', 'This is a current-affairs-heavy, specific factual question -- strong answers should clearly distinguish the two named imaging techniques (optical and SAR) and explain specifically WHY both are carried together (covering each other''s operational limitation), rather than describing the satellite''s capability in only general terms.', 'UPSC CSE Mains 2026, GS Paper III, Q15 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('32874377-3e53-43a1-8a55-1a83f0b0ce26', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 16, NULL, '16', 15, 250, 'What is agentic Artificial Intelligence (AI)? Explain its working. Describe its applications with suitable examples.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('32874377-3e53-43a1-8a55-1a83f0b0ce26', 'Agentic AI refers to AI systems designed to autonomously pursue a given goal through a sequence of actions and decisions, rather than simply responding to a single prompt with a single output the way earlier generative-AI systems (a chatbot answering one question at a time) typically do -- the defining feature is the system''s capacity to plan a multi-step approach, take actions in a real or digital environment, observe the results, and adjust its subsequent steps accordingly, with limited or no step-by-step human direction along the way.

Its working typically combines a large language model''s reasoning and planning capability with the ability to call external tools, APIs, or software systems to actually execute steps -- the AI decomposes a high-level goal (''book me the cheapest flight meeting these constraints'') into a sequence of sub-tasks (search flights, compare prices, check constraints, complete booking), executing each sub-task by invoking the appropriate tool, and using the outcome of each step to inform the next, continuing until the overall goal is achieved or it determines it cannot proceed further without human input.

Applications span several domains. In customer service, agentic AI can autonomously resolve a multi-step customer request (diagnosing an issue, checking account records, and executing a resolution) rather than only answering a single query. In software development, agentic coding assistants can autonomously write, test, and debug code across multiple iterative steps toward a specified feature, rather than generating a single code snippet per prompt. In enterprise operations, agentic systems are being deployed for tasks like automated research synthesis (gathering information from multiple sources and compiling a structured report) and workflow automation that previously required a human coordinating several separate software tools manually.

The key distinction from earlier generative AI, worth stating explicitly, is autonomy over a MULTI-STEP process toward a goal, not just single-turn response generation.', 'Strong answers explicitly distinguish agentic AI from single-turn generative AI (chatbots) as the core conceptual point, rather than describing it as ''AI that is more advanced'' vaguely, and give genuinely distinct application examples across different domains (customer service, coding, enterprise workflow) rather than one example repeated with different wording.', 'UPSC CSE Mains 2026, GS Paper III, Q16 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('3ddbc568-bd3e-4c7b-969a-bc44ed6c454c', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 17, NULL, '17', 15, 250, 'What are the challenges to solid waste management in India? Discuss the governmental policy framework on solid waste management.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('3ddbc568-bd3e-4c7b-969a-bc44ed6c454c', 'India''s solid waste management faces challenges across the full waste lifecycle. Segregation-at-source remains inconsistent -- most urban households do not reliably separate wet (biodegradable), dry (recyclable), and hazardous waste, making downstream processing far less efficient than a properly segregated waste stream would allow. Collection and transportation infrastructure is inadequate or inconsistent in many smaller cities and towns, leading to open dumping and uncollected waste accumulation. Processing capacity -- composting, recycling, and waste-to-energy facilities -- remains insufficient relative to the volume of waste generated, meaning a large share of collected waste still ends up in landfills rather than being processed. Legacy landfills themselves, many operating well beyond capacity and without proper scientific design (liner systems, leachate management), pose ongoing environmental and public-health hazards, including groundwater contamination and periodic landfill fires from uncontrolled methane buildup.

The governmental policy framework has evolved substantially to address these gaps. The Solid Waste Management Rules, 2016 mandate source segregation into wet/dry/hazardous categories, assign specific responsibilities to waste generators, local bodies, and producers, and introduced Extended Producer Responsibility principles for certain product categories. The Swachh Bharat Mission (Urban)''s waste-management component has funded substantial city-level infrastructure investment -- material recovery facilities, composting units, and legacy-landfill remediation (bioremediation of old dumpsites, a significant recent policy focus given how many cities'' legacy dumps had never been scientifically closed). The Plastic Waste Management Rules address plastic-specific challenges, including a phased ban on identified single-use plastic items and mandatory Extended Producer Responsibility for plastic packaging.

The persistent gap between this reasonably comprehensive policy framework and actual on-ground outcomes reflects an implementation and enforcement challenge more than a policy-design gap -- municipal capacity, particularly in smaller urban local bodies, has not uniformly kept pace with the framework''s requirements.', 'Strong answers organize the challenges across the waste lifecycle (segregation, collection, processing, disposal) rather than listing problems randomly, and name the specific real policy instruments (SWM Rules 2016, Swachh Bharat Mission''s waste component, Plastic Waste Management Rules) rather than describing government policy on waste generically.', 'UPSC CSE Mains 2026, GS Paper III, Q17 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('15b147ba-57cc-4656-9fee-f2f63ed31ac5', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 18, NULL, '18', 15, 250, 'Community participation is the cornerstone of effective disaster management. Analyse this statement with suitable examples from India.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('15b147ba-57cc-4656-9fee-f2f63ed31ac5', 'Community participation is central to effective disaster management because communities possess local knowledge of terrain, vulnerable populations, and historical hazard patterns that top-down, centrally-directed response cannot fully replicate, and because the earliest, most critical response window after a disaster is almost always executed by the local community itself, well before external relief can physically arrive.

India''s own experience provides real, documented evidence for this. Odisha''s transformation into a model for cyclone-disaster management -- reducing cyclone mortality from tens of thousands in the 1999 super-cyclone to a small fraction of that in comparably severe subsequent cyclones -- rested substantially on community-based early-warning dissemination and trained local volunteer networks who could evacuate their own communities faster and more completely than a purely external, top-down evacuation effort could achieve alone. Kerala''s community-driven flood response during the 2018 and subsequent floods, where local fishing communities voluntarily deployed their own boats for rescue operations well ahead of formal disaster-response teams reaching affected areas, is another concrete instance of community capacity substituting for, and often exceeding, formal response speed in the disaster''s earliest hours.

The National Disaster Management Authority''s own guidelines have progressively formalized this insight -- community-based disaster management training, local disaster management committees at the panchayat level, and school-based disaster-preparedness education represent institutional recognition that professional disaster-response capacity alone, however well-resourced, cannot substitute for a trained, prepared local population able to act in a disaster''s first, most consequential hours.

The statement is well-supported by this evidence: professional disaster management infrastructure remains essential for larger-scale, sustained response, but community participation determines outcomes specifically in the earliest response window, which is often the single most consequential period for survival.', '''Analyse with suitable examples'' specifically requires named, real Indian cases -- Odisha''s cyclone-mortality reduction and Kerala''s 2018 flood-boat volunteers are the standard, well-documented examples for this exact topic, and their absence significantly weakens an otherwise sound theoretical answer.', 'UPSC CSE Mains 2026, GS Paper III, Q18 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('8d797879-f959-42b5-87e4-103929901177', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 19, NULL, '19', 15, 250, 'Separatist movements have been one of the major factors contributing to militancy and instability in Jammu & Kashmir (J&K). Bring out actions taken by the Government.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('8d797879-f959-42b5-87e4-103929901177', 'Separatist sentiment and cross-border-supported militancy have been persistent, interlinked drivers of instability in Jammu & Kashmir since the late 1980s, with cross-border infiltration and support providing external reinforcement to what began substantially as a domestic separatist movement, complicating any purely internal-security or purely political response in isolation.

Government action has operated across several distinct tracks. Security-focused measures include sustained counter-insurgency operations by the Army and paramilitary forces, the Armed Forces Special Powers Act''s continued application in specific areas, and substantially strengthened border-fencing and surveillance infrastructure along the Line of Control to reduce infiltration, which security assessments credit with a measurable decline in successful cross-border infiltration attempts over the past decade compared to earlier periods.

Constitutional and political measures include the 2019 reorganization abrogating Article 370''s special status and splitting the erstwhile state into the Union Territories of Jammu & Kashmir and Ladakh -- a fundamental structural change the government has framed as integrating J&K more fully into the national mainstream and removing a legal basis some separatist arguments had invoked. Subsequent restoration of the electoral process, including local body and assembly elections, has been presented as re-establishing normal democratic political participation as an alternative channel to separatist mobilization.

Development-focused measures, including the Border Area Development Programme discussed elsewhere in this paper and targeted infrastructure/employment schemes, aim at the ''hearts and minds'' dimension -- addressing the economic grievance and alienation that separatist narratives have historically exploited, on the premise that reducing underlying grievance reduces the recruitment base for continued militancy over the longer term, alongside the more immediate security response.

Government strategy in J&K has therefore combined security, constitutional, political, and development tracks simultaneously rather than relying on any single approach alone.', 'Strong answers organize the government response across distinct tracks (security, constitutional/political, development) rather than listing measures without structure, and should present the 2019 reorganization as a significant, factual policy action rather than either advocating for or against it -- this is a factual ''bring out actions taken'' question, not an opinion question.', 'UPSC CSE Mains 2026, GS Paper III, Q19 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');

INSERT INTO pyq_questions (id, collection_id, sort_order, section, question_number, marks, word_limit, question_text)
VALUES ('b0c3c30a-6d33-45fd-b430-4cfb864a81c2', '67e8b893-3d31-4b17-a55c-a0a9269dcf10', 20, NULL, '20', 15, 250, 'Discuss counterfeit currency and money laundering as major sources of terror funding in India. State the actions being taken at International level.');
INSERT INTO pyq_model_answers (question_id, model_answer, examiner_notes, source_note)
VALUES ('b0c3c30a-6d33-45fd-b430-4cfb864a81c2', 'Counterfeit currency, particularly Fake Indian Currency Notes historically linked to state and non-state actors across the border, provides terror networks a way to inject illicit funds into the economy while simultaneously undermining confidence in genuine currency -- FICN has been a specifically documented terror-financing channel in India, distinct from ordinary counterfeiting motivated purely by financial gain.

Money laundering enables terror financing by disguising the origin of funds raised through the drug trade, extortion, hawala (informal, largely undocumented cross-border value-transfer networks), and diaspora-sourced donations that may be collected under a legitimate-seeming charitable or cultural front before being diverted to militant financing -- the layering and integration stages of money laundering allow illicit terror funds to appear as legitimate transactions by the time they reach their end use.

India''s domestic response includes the Prevention of Money Laundering Act''s continued strengthening, the Financial Intelligence Unit''s transaction-monitoring and suspicious-activity-reporting mechanisms, and the National Investigation Agency''s dedicated terror-financing investigation mandate. The 2016 demonetization was explicitly justified in part as a measure to disrupt FICN circulation and cash-based terror financing, alongside its other stated objectives.

At the international level, the Financial Action Task Force (FATF) sets the global standard for anti-money-laundering and counter-terror-financing compliance, and its ''grey list''/''black list'' designations create real diplomatic and financial pressure on non-compliant states (Pakistan''s extended period on the FATF grey list, linked substantially to inadequate action against terror-financing networks operating from its territory, is the clearest regional example of this pressure mechanism in action). India actively participates in FATF''s mutual-evaluation process and coordinates with international financial-intelligence-sharing networks to trace cross-border terror-financing flows, recognizing that a purely domestic response cannot address financing channels that are inherently cross-border by design.', 'Strong answers explain the actual MECHANISM by which counterfeit currency and money laundering fund terrorism (not just assert that they do), name FATF specifically as the key international body with its grey/black-list enforcement mechanism, and connect India''s specific domestic measures (PMLA, demonetization''s stated FICN rationale) to the broader international framework rather than treating domestic and international action as unrelated.', 'UPSC CSE Mains 2026, GS Paper III, Q20 (exam held 23 August 2026). Verified verbatim against two independent sources matching essentially word-for-word: Insights on India and ForumIAS''s dedicated GS Paper 3 question-paper pages.');
